rebase.backend::
	rebase 默认使用的后端。可选值为 `apply` 或 `merge`。将来如果 merge 后端获得 apply 后端剩余的全部能力，该设置可能会变得无用。

rebase.stat::
	显示上次变基后上游变化的差异状态。差异状态也由配置选项 rebase.stat 控制。

rebase.autoSquash::
	如果设为 true，则在交互模式下默认启用 linkgit:git-rebase[1] 的 `--autosquash` 选项。可用 `--no-autosquash` 覆盖。

rebase.autoStash::
	当设为 true 时，会在操作开始前自动创建一个临时 stash 条目，并在操作结束后重新应用它。这意味着你可以在脏工作区上运行 rebase。不过请谨慎使用：成功 rebase 之后最后一次应用 stash 可能会导致并不简单的冲突。该选项可由 linkgit:git-rebase[1] 的 `--no-autostash` 和 `--autostash` 选项覆盖。默认值为 false。

rebase.updateRefs::
	如果设为 true，则默认启用 `--update-refs` 选项。

rebase.missingCommitsCheck::
	如果设为 "warn"，当某些提交被移除时（例如删除了一行），`git rebase -i` 会打印警告，但 rebase 仍会继续。如果设为 "error"，则会打印前述警告并停止 rebase，此时可使用 `git rebase --edit-todo` 来纠正错误。如果设为 "ignore"，则不做检查。若要在不产生警告或错误的情况下丢弃某个提交，请在 todo 列表中使用 `drop` 命令。默认值为 "ignore"。

rebase.instructionFormat::
	一个按 linkgit:git-log[1] 所规定的格式字符串，用于交互式 rebase 期间的 todo 列表。该格式会自动在前面附加提交哈希。

rebase.abbreviateCommands::
	如果设为 true，`git rebase` 会在 todo 列表中使用缩写命令名，结果类似于：
+
-------------------------------------------
p deadbee 本次提交的一行说明
p fa1afe1 下一次提交的一行说明
...
-------------------------------------------
+
而不是：
+
-------------------------------------------
pick deadbee 本次提交的一行说明
pick fa1afe1 下一次提交的一行说明
...
-------------------------------------------
+
默认值为 false。

rebase.rescheduleFailedExec::
	自动重新安排执行失败的 `exec` 命令。这只有在交互模式下（或提供了 `--exec` 选项时）才有意义。其效果与指定 `--reschedule-failed-exec` 选项相同。

rebase.forkPoint::
	如果设为 false，则默认启用 `--no-fork-point` 选项。

rebase.rebaseMerges::
	是否以及如何默认设置 `--rebase-merges` 选项。可以是 `rebase-cousins`、`no-rebase-cousins`，或布尔值。设为 true 或 `no-rebase-cousins` 等同于 `--rebase-merges=no-rebase-cousins`；设为 `rebase-cousins` 等同于 `--rebase-merges=rebase-cousins`；设为 false 等同于 `--no-rebase-merges`。在命令行上传递 `--rebase-merges`（无论是否带参数）都会覆盖任何 `rebase.rebaseMerges` 配置。

rebase.maxLabelLength::
	根据提交主题生成标签名时，会将名称截断到此长度。默认情况下，名称会被截断到略小于 `NAME_MAX` 的长度（以便例如为相应的松散 ref 写入 `.lock` 文件）。
