git-diff-tree(1)
================

名称
--
git-diff-tree - 比较通过两个树对象找到的 Blob 的内容和模式


概述
--
[verse]
'git diff-tree' [--stdin] [-m] [-s] [-v] [--no-commit-id] [--pretty]
	      [-t] [-r] [-c | --cc] [--combined-all-paths] [--root] [--merge-base]
	      [<common-diff-options>] <目录树对象> [<目录树对象>] [<路径>...]

描述
--
比较两个目录树对象中发现的 blob 的内容和模式。

如果只给出一个 <目录树对象>，则会将该提交与其父提交进行比较（见下文的 --stdin）。

请注意，'git diff-tree' 可以使用封装在提交对象中的树。

选项
--
include::diff-options.adoc[]

<tree-ish>::
	树对象的 id。

<路径>...::
	如果提供了该选项，则结果仅限于与所提供的路径规格之一相匹配的文件子集。

-r::
	向子树递归。

-t::
	展示目录树本身以及子树。 暗指 -r。

--root::
	当指定了 `--root` 时，初始提交将显示为一个大的创建事件。这相当于针对 NULL 树的差分。

--merge-base::
	不要直接比较 <树对象>，而是使用两个 <树对象> 之间的合并基数作为 "before" 边。 必须有两个 <树对象>，而且必须都是提交。

--stdin::
	如果指定了 `--stdin`，命令不会从命令行获取 <树对象> 参数。 相反，它会从标准输入中读取包含两个 <目录树>、一个 <提交> 或一个 <提交> 列表的行。 (使用单空格作为分隔符）
+
当给出两个树时，它会比较第一个目录树和第二个目录树。 如果给出的是单个提交，则会将该提交与其父提交进行比较。 如果给出了其余的提交，则会把它们当作第一个提交的父提交来使用。
+
比较两棵目录树时，会在差值前打印两棵目录树的 ID（用空格分隔并以换行结束）。 比较提交时，则会打印第一个（或唯一一个）提交的 ID，并以换行结束。
+
以下标记会进一步影响比较提交（而不是目录树树）时的行为。

-m::
	默认情况下，'git diff-tree --stdin' 不会显示合并提交的差异。 有了这个标记，它就会显示该提交与其所有父提交的差异。另请参阅 `-c`。

-s::
	默认情况下，'git diff-tree --stdin' 会以机器可读形式（不含 `-p`）或补丁形式（含 `-p`）显示差异。 该输出可以被抑制。 只有使用 `-v` 标志时才有用。

-v::
	该标记会使 'git diff-tree --stdin' 在差异之前显示提交信息。

include::pretty-options.adoc[]

--no-commit-id::
	'git diff-tree' outputs a line with the commit ID when applicable. This flag suppresses the commit ID output.

-c::
	这个标记改变了合并提交的显示方式（这意味着它只在命令为一个 <树对象> 或 `--stdin` 时有用）。 它会同时显示每个父文件与合并结果之间的差异，而不是一次一个地显示父文件与合并结果之间的成对差异（`-m` 选项就是这么做的）。 此外，它只列出从所有父文件修改过的文件。

--cc::
	这个标记改变了合并提交补丁的显示方式，与 `-c` 选项类似。它暗示了 `-c` 和 `-p` 选项，并通过省略不感兴趣的 hunk 来进一步压缩补丁输出，这些 hunk 的内容在父节点中只有两种变体，合并结果会选择其中之一而不做修改。 如果所有 hunk 都是无趣的，提交本身和提交日志信息都不会显示，就像其他 “空差异” 情况一样。

--combined-all-paths::
	该标记会导致合并差异（用于合并提交）列出所有父文件的文件名。 因此，它只有在指定 -c 或 --cc 时才有效，而且可能只有在检测到文件名更改时才有用（即请求重命名或复制检测时）。

--always::
	即使差异本身为空，也会显示提交本身和提交日志信息。


include::pretty-formats.adoc[]

include::diff-format.adoc[]

GIT
---
属于 linkgit:git[1] 文档
