git-commit-tree(1)
==================

名称
--
git-commit-tree -创建一个新的提交对象


概述
--
[verse]
'git commit-tree' <目录树> [(-p <父对象>)...]
'git commit-tree' [(-p <父对象>)...] [-S[<keyid>]] [(-m <消息>)...]
		  [(-F <文件>)...] <目录树>


描述
--
这通常不是最终用户想要直接运行的。 请参见 linkgit:git-commit[1]。

根据提供的树对象创建新的提交对象，并将新的提交对象 id 发送到 stdout。除非给出 `-m` 或 `-F`选项，否则日志信息将从标准输入读取。

`-m` 和 `-F` 选项可以以任意顺序给出任意次数。提交日志信息将按照选项的顺序排列。

一个提交对象可以有任意数量的父对象。如果只有一个父对象，它就是一个普通的提交。如果有一个以上的父提交对象，提交就会在多行历史记录之间进行合并。初始（根）提交没有父对象。

树表示工作目录的特定目录状态，而提交则表示 “时间” 上的状态，并说明如何到达该状态。

通常情况下，一次提交会确定一个新的 "HEAD" 状态，虽然 Git 并不关心你把关于该状态的注释保存在哪里，但在实践中，我们倾向于把结果写入 `.git/HEAD` 指向的文件，这样我们就能随时看到上次提交的状态。

选项
--
<目录树>::
	一个现有的目录树对象。

-p <父提交>::
	每个 `-p` 表示父提交对象的 id。

-m <信息>::
	提交日志信息中的一个段落。可以给出多个段落，每个 <信息> 都将成为自己的段落。

-F <文件>::
	从给定文件中读取提交日志信息。使用 `-` 从标准输入读取。可以多次给定该文件，每个文件的内容都会成为自己的段落。

-S[<keyid>]::
--gpg-sign[=<键 ID>]::
--no-gpg-sign::
	GPG 签名提交。`keyid` 参数是可选的，默认为提交者身份；如果指定，必须与选项粘连，不能有空格。`--no-gpg-sign` 用于抵消命令行中先前给出的 `--gpg-sign`选项。

提交信息
----

一个提交封装了：

- 所有父对象 ID
- 作者姓名、电子邮件和日期
- 提交者姓名、电子邮件和提交时间。

提交注释从标准输入流读取。如果没有通过 "<" 重定向提供更新日志条目，'git commit-tree' 就会等待输入条目，并以 ^D 结束。

include::date-formats.adoc[]

讨论
--

include::i18n.adoc[]

文件
--
/etc/mailname

参见
--
linkgit:git-write-tree[1] linkgit:git-commit[1]

GIT
---
属于 linkgit:git[1] 文档
