git-pull(1)
===========

名称
--
git-pull - 从另一个仓库或本地分支撷取并与之集成


概述
--
[synopsis]
'git pull' [<选项>] [<仓库> [<引用规范>...]]


描述
--

将远程仓库中的更改集成到当前分支中。

首先，`git pull` 会使用相同参数（不包括 merge 选项）运行 `git fetch`，以获取远程分支。然后它会决定要集成哪个远程分支：如果你执行 `git pull` 时不带参数，则默认使用当前分支的 <<UPSTREAM-BRANCHES,upstream>>。之后，它会将该分支集成到当前分支中。

将远程分支集成到当前分支主要有 4 种方式：

1. `git pull --ff-only` 只会执行“快进”更新：如果你的本地分支已经与远程分支发生分叉，它就会失败。这是默认行为。
2. `git pull --rebase` 会运行 `git rebase`
3. `git pull --no-rebase` 会运行 `git merge`。
4. `git pull --squash` 会运行 `git merge --squash`

你也可以通过配置 `pull.rebase`、`pull.squash` 或 `pull.ff` 选项来指定自己偏好的行为。

如果在 merge 或 rebase 过程中出现你不想处理的冲突，可以安全地使用 `git merge --abort` 或 `git rebase --abort` 来中止。

选项
--

_<仓库>_::
	作为获取或拉动操作的来源的 "remote" 仓库。 这个参数可以是一个 URL（见下面 <<URLS,GIT URLS>> 一节），也可以是一个远程仓库的名称（见下面 <<REMOTES,远程>> 一节）。
+
默认为当前分支已配置的上游分支；如果没有，则为 `origin`。关于如何配置上游分支，请参见下文 <<UPSTREAM-BRANCHES,UPSTREAM BRANCHES>>。

<引用规范>::
	要获取并集成到当前分支中的分支或其他引用，例如 `git pull origin main` 中的 `main`。默认值为当前分支配置的上游分支。
+
这可以是一个分支、标签或其他一组引用。完整语法请参见下文“Options related to fetching”下的 <<fetch-refspec,_<refspec>_>>，关于 `git pull` 如何使用此参数来决定集成哪个远程分支，请参见下文 <<DEFAULT-BEHAVIOUR,DEFAULT BEHAVIOUR>>。

`-q`::
`--quiet`::
	这将被传递给底层的 git-fetch，以便在传输过程中抑制报告，以及底层的 git-merge，以便在合并过程中抑制输出。

`-v`::
`--verbose`::
	将 --verbose 传给 git-fetch 和 git-merge。

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	这个选项控制是否应该获取已填充子模块的新提交，以及是否应该更新活动子模块的工作区（见linkgit:git-fetch[1], linkgit:git-config[1] 和 linkgit:gitmodules[5]）。
+
如果检出是通过变基完成的，那么本地子模块的提交也会被变基。
+
如果更新是通过合并完成的，子模块的冲突就会被解决并被检查出来。

与合并有关的选项
~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; 为真时，在获取后将当前分支变基到上游分支之上。如果有一个远程跟踪的分支与上游分支相对应，并且上游分支在上次获取后被重新建立了基础，那么变基就会使用该信息以避免重新建立非本地的变化。

`merges`;; 当设置为 `merges` 时，使用 `git rebase --rebase-merges` 进行重建，这样本地的合并提交就会包含在重建中（详见 linkgit:git-rebase[1]）。
`false`;; 如果为false，则将上游分支合并到当前分支中。
`interactive`;; 当设置为 `interactive` 时，启用变基的交互模式。

+
如果你想让 `git pull` 总是使用 `--rebase` 而不是合并，请参见 linkgit:git-config[1] 中的 `pull.rebase`, `branch.< 分支名 >.rebase` 和 `branch.autoSetupRebase`。
+
[NOTE]
这是一种潜在的「危险的」操作模式。 它重写了历史，当你已经发布了这些历史时，这并不是一个好兆头。 除非你仔细阅读了linkgit:git-rebase[1]，否则请「不要」使用这个选项。

`--no-rebase`::
	这是对 --rebase=false 的简写。

与获取有关的选项
~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
默认行为
----

人们经常使用 `git pull` 而不给任何参数。 传统上，这等同于说 `git pull origin`。 然而，当配置 `branch.<分支名>.remote` 在分支 `< 分支名 >` 上出现时，该值会被用来代替 `origin`。

为了确定使用什么 URL 来获取，将查询配置 `remote.<远程名>.url` 的值，如果没有这样的变量，将使用 `$GIT_DIR/remotes/< 远程名 >` 中 `URL:` 一行的值。

当命令行上没有任何引用规范参数时，为了确定要获取哪些远程分支（并可选择存储在远程跟踪分支中），会查询配置变量 `remote.<远程名>.fetch` 的值，如果没有，会查询 `$GIT_DIR/remotes/< 远程名 >` 并使用其 `Pull:` 行。 除了在『选项』部分描述的引用规范格式之外，你还可以有一个看起来像这样的引用规范通配符：

------------
refs/heads/*:refs/remotes/origin/*
------------

一个引用规范通配符必须有一个非空的 RHS（即必须存储在远程跟踪分支中获取的内容），其 LHS 和 RHS 必须以 `/*` 结尾。 以上规定了所有远程分支都使用同名的 `refs/remotes/origin/` 层次结构中的远程跟踪分支进行跟踪。

为了不破坏后向兼容性，确定在获取后合并哪个远程分支的规则有点复杂。

如果在 `git pull` 的命令行中给出了明确的引用规范，它们都会被合并。

当命令行没有给出引用规范时，那么 `git pull` 使用配置或 `$GIT_DIR/remotes/<远程名>` 中的引用规范。 在这种情况下，以下规则适用：

. 如果当前分支 `<分支名>` 的 `branch.< 分支名 >.merge` 配置存在，这就是被合并的远程站点的分支名称。

. 如果引用规范是全局的， 则不合并任何信息。

. 否则将合并第一个引用规范的远程分支。


实例
--

* 更新你所克隆的仓库的远程跟踪分支，然后将其中一个分支合并到你当前的分支：
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
通常情况下，合并进来的分支是远程仓库的 HEAD，但选择由 branch.<分支名>.remote 和 branch.< 分支名 >.merge 选项决定；详见 linkgit:git-config[1] 。

* 将远程分支 `next` 合并到当前分支：
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
这将在 FETCH_HEAD 中暂时留下 `next` 的副本，并更新远程跟踪分支 `origin/next`。 同样可以通过调用 fetch 和 merge 来完成：
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


如果你尝试了一次拉取，导致了复杂的冲突，想重新开始，你可以用 `git reset` 来恢复。


include::transfer-data-leaks.adoc[]

漏洞
--
使用 --recurse-submodules 现在只能获取已经检出的子模块的新提交。例如，当上游在刚刚获取的超级项目的提交中添加了一个新的子模块时，子模块本身不能被获取，这使得以后不需要再次获取就能检出该子模块。这个问题有望在未来的 Git 版本中被修复。

参见
--
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
属于 linkgit:git[1] 文档
