git-check-mailmap(1)
====================

名称
--
git-check-mailmap - 显示联系人的规范名称和电子邮件地址


概述
--
[verse]
'git check-mailmap' [<选项>] <连接>...


描述
--

For each ``Name $$<user@host>$$'', ``$$<user@host>$$'', or ``$$user@host$$'' from the command-line or standard input (when using `--stdin`), look up the person's canonical name and email address (see "Mapping Authors" below). If found, print them; otherwise print the input as-is.


选项
--
--stdin::
	在用完命令行上提供的联系人后，从标准输入中读取联系人，每行一个。

--mailmap-file=<file>::
	除任何已配置的邮件映射文件外，读取指定的邮件映射文件。该文件中的条目优先于默认邮件映射文件或任何已配置邮件映射文件中的条目。

--mailmap-blob=<blob>::
	类似于 `--mailmap-file` 选项，但将值视为对仓库中 blob 的引用。如果同时指定了 `--mailmap-file` 和 `--mailmap-blob` 选项，则优先使用 `--mailmap-file` 选项中的条目。

输出
--

对于每个联系人，都会输出一行，以换行结束。 如果名字被提供或被 'mailmap' 知道，``Name $$<user@host>$$'' 被打印；否则只有 ``$$<user@host>$$'' 被打印。


配置
--

参见 linkgit:git-config[1] 中的 `mailmap.file` 和 `mailmap.blob`，了解如何指定一个自定义的 `.mailmap` 目标文件或对象。


制图作者
----

参见 linkgit:gitmailmap[5]。


GIT
---
属于 linkgit:git[1] 文档
