ФАЙЛ КОНФІГУРАЦІЇ
-----------------

Файл конфігурації Git містить низку змінних, які впливають на поведінку команд Git. Файли `.git/config` та, за бажанням, `config.worktree` (див. розділ «ФАЙЛ КОНФІГУРАЦІЇ» у linkgit:git-worktree[1]) у кожному репозиторії використовуються для зберігання конфігурації цього репозиторію, а `$HOME/.gitconfig` використовується для зберігання конфігурації для кожного користувача як резервних значень для файлу `.git/config`. Файл `/etc/gitconfig` можна використовувати для зберігання стандартної конфігурації для всієї системи.

Змінні конфігурації використовуються як внутрішніми механізмами Git (plumbing), так і зовнішніми командами (porcelain). Змінні поділяються на секції, де повне ім’я самої змінної є останнім сегментом, відокремленим крапкою, а ім’я секції — це все, що знаходиться перед останньою крапкою. У назвах змінних не враховується регістр, допускаються лише алфавітно-цифрові символи та `-`, а починатися вони повинні з літери. Деякі змінні можуть зустрічатися кілька разів; у такому випадку ми говоримо, що змінна є багатозначною.

Синтаксис
~~~~~~~~~

Синтаксис є досить гнучким і несуворим. Символи пробілів, до яких у цьому контексті належать пробіл (SP) та горизонтальна табуляція (HT), здебільшого ігноруються. Символи «#» та «;» позначають початок коментарів, що тривають до кінця рядка. Порожні рядки ігноруються.

Файл складається з розділів і змінних. Розділ починається з назви розділу в квадратних дужках і триває до початку наступного розділу. У назвах розділів не враховується регістр. У назвах розділів допускаються лише алфавітно-цифрові символи, а також символи `-` і `.`. Кожна змінна повинна належати до якогось розділу, тобто перед першим значенням змінної має бути заголовок розділу.

Розділи можна додатково поділяти на підрозділи. Щоб створити підрозділ, вкажіть його назву в подвійних лапках, відокремивши її пробілом від назви розділу, у заголовку розділу, як показано в прикладі нижче:

--------
	[section "subsection"]

--------

Назви підрозділів чутливі до регістру та можуть містити будь-які символи, окрім символу нового рядка та нульового байта. Подвійні лапки `"` та зворотну скісну риску можна включати, екрануючи їх як `\"` та `\\` відповідно. Зворотну скісну риску перед іншими символами пропускаються під час читання; наприклад, `\t` читається як `t`, а `\0` читається як `0`. Заголовки розділів не можуть охоплювати кілька рядків. Змінні можуть належати безпосередньо до розділу або до заданого підрозділу. Ви можете мати `[розділ]`, якщо у вас є `[розділ "підрозділ"]`, але це не обовʼязково.

Також існує застарілий синтаксис `[section.subsection]`. У цьому синтаксисі назва підрозділу перетворюється на малу літеру та порівнюється з урахуванням регістру. Ці назви підрозділів дотримуються тих самих обмежень, що й назви розділів.

Усі інші рядки (а також частина рядка, що йде після заголовка розділу) розпізнаються як визначення змінних у форматі 'name = value' (або просто 'name' що є скороченим записом, який означає, що змінна має булеве значення «true»). У назвах змінних не враховується регістр, допускаються лише алфавітно-цифрові символи та `-`, а починатися вони повинні з літери.

Пробільні символи навколо `name`, `=` та `value` відкидаються. Внутрішні пробільні символи всередині `value` зберігаються дослівно. Коментарі, що починаються з `#` або `;` і продовжуються до кінця рядка, відкидаються. Рядок, який визначає значення, можна продовжити до наступного рядка, завершивши його зворотною скісною рискою (`\`); зворотна скісна риска та символи кінця рядка відкидаються.

Якщо `value` має містити початкові або кінцеві пробіли, його потрібно взяти в подвійні лапки (`"`). Усередині подвійних лапок символи подвійних лапок (`"`) та зворотної скісної риски (`\`) повинні бути екрановані: використовуйте `\"` замість `"` та `\\` замість `\`.

Розпізнаються такі escape-послідовності (окрім `\"` та `\\`): `\n` для символу нового рядка (NL), `\t` для горизонтальної табуляції (HT, TAB) та `\b` для символу backspace (BS). Інші escape-послідовності символів (включаючи вісімкові escape-послідовності) є недійсними.


Розділ Include
~~~~~~~~~~~~~~

Розділи `include` та `includeIf` дозволяють вам включати директиви конфігурації з іншого джерела. Ці розділи поводяться ідентично один одному, за винятком того, що розділи `includeIf` можуть ігноруватися, якщо їхня умова не є true; див. "Умовні включення" нижче.

Ви можете включити файл конфігурації з іншого місця, встановивши для спеціальної змінної `include.path` (або `includeIf.*.path`) ім’я файлу, який потрібно включити. Ця змінна приймає шлях до файлу як значення, причому в ньому відбувається розгортання символів тильди. Ці змінні можна вказати кілька разів.

Вміст файлу, що включається, вставляється безпосередньо, ніби він був знайдений у місці розташування директиви include. Якщо значення змінної є відносним шляхом, цей шлях вважається відносним до конфігураційного файлу, в якому була знайдена директива include. Приклади наведено нижче.

Умовне включення
~~~~~~~~~~~~~~~~

Ви можете умовно включити файл конфігурації з іншого, встановивши для змінної `includeIf.<умова>.path` імʼя файлу, який потрібно включити.

Умова починається з ключового слова, за яким йде двокрапка та деякі дані, формат та значення яких залежать від ключового слова. Підтримувані ключові слова:

`gitdir`::
	Дані, що йдуть після ключового слова `gitdir` та двокрапки, використовуються як шаблон glob. Якщо розташування теки .git відповідає шаблону, умова включення виконується.
+
Розташування .git може бути автоматично виявлене або походити зі змінної середовища `$GIT_DIR`. Якщо репозиторій автоматично виявлено через файл .git (наприклад, з субмодулів або повʼязаного робочого дерева), розташування .git буде кінцевим розташуванням, де знаходиться тека .git, а не місцем, де знаходиться файл .git.
+
Шаблон може містити стандартні шаблони підстановки та два додаткові, `**/` та `/**`, які можуть відповідати кільком компонентам шляху. Для отримання детальної інформації зверніться до linkgit:gitignore[5]. Для зручності:

 * Якщо шаблон починається з `~/`, `~` буде замінено вмістом змінної середовища `HOME`.

 * Якщо шаблон починається з `./`, він замінюється назвою теки, що містить поточний файл конфігурації.

 * Якщо шаблон не починається з `~/`, `./` або `/`, автоматично буде додано `**/`. Наприклад, шаблон `foo/bar` стає `**/foo/bar` і відповідатиме `/any/path/to/foo/bar`.

 * Якщо шаблон закінчується на `/`, автоматично буде додано `**`. Наприклад, шаблон `foo/` стає `foo/**`. Іншими словами, він рекурсивно збігається з "foo" та всім, що всередині нього.

`gitdir/i`::
	Це те саме, що й `gitdir`, за винятком того, що під час порівняння не враховується регістр (наприклад, у файлових системах, що не розрізняють регістр)

`onbranch`::
	Дані, що йдуть після ключового слова `onbranch` та двокрапки, розглядаються як шаблон зі стандартними символами-замінниками для розширення та двома додатковими — `**/` і `/**`, які можуть відповідати кільком компонентам шляху. Якщо ми перебуваємо в робочому дереві, де назва гілки, яка наразі вибрана, відповідає цьому шаблону, умова включення вважається виконаною.
+
Якщо шаблон закінчується на `/`, автоматично буде додано `**`. Наприклад, шаблон `foo/` стає `foo/**`. Іншими словами, він відповідає всім гілкам, які починаються з `foo/`. Це корисно, якщо ваші гілки організовані ієрархічно, і ви хочете застосувати конфігурацію до всіх гілок у цій ієрархії.

`hasconfig:remote.*.url`::
	Дані, що йдуть після цього ключового слова та двокрапки, розглядаються як шаблон із стандартними символами-замінниками та двома додатковими — `**/` і `/**`, які можуть відповідати кільком компонентам. При першому виявленні цього ключового слова решта конфігураційних файлів буде перевірена на наявність віддалених URL-адрес (без застосування будь-яких значень). Якщо існує хоча б одна віддалена URL-адреса, що відповідає цьому шаблону, умова включення вважається виконаною.
+
Файли, що включаються цією опцією (прямо чи опосередковано), не можуть містити віддалені URL-адреси.
+
Зверніть увагу, що на відміну від інших умов includeIf, виконання цієї умови залежить від інформації, яка на момент зчитування умови ще не відома. Типовим випадком використання є ситуація, коли цей параметр присутній у конфігурації системного або глобального рівня, а віддалений URL — у конфігурації локального рівня; тому під час виконання цієї умови потребує попереднього сканування. Щоб уникнути проблеми «яйця та курки», в якій файли, що потенційно можуть бути включені, можуть впливати на те, чи будуть такі файли потенційно включені, Git розриває цей цикл, забороняючи цим файлам впливати на виконання цих умов (таким чином, забороняючи їм оголошувати віддалені URL-адреси).
+
Що стосується найменування цього ключового слова, то воно призначене для прямої сумісності зі схемою іменування, яка підтримує більше умов включення на основі змінних, але наразі Git підтримує лише точне ключове слово, описане вище.

Ще кілька зауважень щодо зіставлення через `gitdir` та `gitdir/i`:

 * Символічні посилання в `$GIT_DIR` не розгортаються перед зіставленням.

 * Поза межами `$GIT_DIR` будуть порівнюватися як символічні посилання, так і реальні шляхи. Наприклад, якщо ~/git є символічним посиланням на /mnt/storage/git, то обидва `gitdir:~/git` та `gitdir:/mnt/storage/git` будуть мати збіг.
+
У першому випуску цієї функції у версії 2.13.0 ситуація була іншою: там перевірялася лише версія realpath. У конфігурації, яка має бути сумісною з першим випуском цієї функції, потрібно вказати або лише версію realpath, або обидві версії.

 * Зверніть увагу, що "../" не є спеціальним символом і буде інтерпретуватися буквально, що, ймовірно, не відповідає вашим намірам.

Приклад
~~~~~~~

----
# Основні змінні
[core]
	; Не довіряти режимам файлів
	filemode = false

# Наш алгоритм diff
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

[branch "devel"]
	remote = origin
	merge = refs/heads/devel

# Налаштування проксі-сервера
[core]
	gitProxy="ssh" for "kernel.org"
	gitProxy=default-proxy ; for the rest

[include]
	path = /path/to/foo.inc ; include by absolute path
	path = foo.inc ; find "foo.inc" relative to the current file
	path = ~/foo.inc ; find "foo.inc" in your `$HOME` directory

; include if $GIT_DIR is /path/to/foo/.git
[includeIf "gitdir:/path/to/foo/.git"]
	path = /path/to/foo.inc

; include for all repositories inside /path/to/group
[includeIf "gitdir:/path/to/group/"]
	path = /path/to/foo.inc

; include for all repositories inside $HOME/to/group
[includeIf "gitdir:~/to/group/"]
	path = /path/to/foo.inc

; relative paths are always relative to the including
; file (if the condition is true); their location is not
; affected by the condition
[includeIf "gitdir:/path/to/group/"]
	path = foo.inc

; include only if we are in a worktree where foo-branch is
; currently checked out
[includeIf "onbranch:foo-branch"]
	path = foo.inc

; include only if a remote with the given URL exists (note
; that such a URL may be provided later in a file or in a
; file read after this file is read, as seen in this example)
[includeIf "hasconfig:remote.*.url:https://example.com/**"]
	path = foo.inc
[remote "origin"]
	url = https://example.com/git
----

Значення
~~~~~~~~

Значення багатьох змінних обробляються як простий рядок, але є змінні, які приймають значення певних типів, і існують правила їх написання.

булеві::

       Коли кажуть, що змінна приймає булеве значення, для слів «true» і «false» допускається багато синонімів; у всіх цих випадках регістр літер не має значення.

	true;; Булевими літералами, що означають «істина», є `yes`, `on`, `true` та `1`. Крім того, змінна, визначена без `= <значення>`, вважається істинною.

	false;; Булеві літерали «хибності» це: `no`, `off`, `false`, `0` та порожній рядок.
+
Під час перетворення значення до його канонічної форми за допомогою специфікатора типу `--type=bool`, 'git config' гарантуватиме, що вивід буде "true" або "false" (пишеться малими літерами).

integer::
       Значення багатьох змінних, що визначають різні розміри, можуть мати суфікси `k`, `M` тощо, що означають «масштабувати число на 1024», «на 1024x1024» тощо.

color::
       Значенням змінної, яка приймає колір, є список кольорів (щонайбільше два, один для символів та один для фону) та атрибутів (скільки завгодно), розділених пробілами.
+
Прийнятні основні кольори: `normal`, `black`, `red`, `green`, `yellow`, `blue`, `magenta`, `cyan`, `white` та `default`. Перший заданий колір — це колір символів; другий — колір фону. Усі основні кольори, крім `normal` та `default`, мають яскравий варіант, який можна вказати, додавши перед кольором префікс `bright`, наприклад, `brightred`.
+
Колір `normal` не змінює колір. Він такий самий, як порожній рядок, але може використовуватися як колір сиволів, якщо вказати лише колір фону (наприклад, "normal red").
+
Колір `default` явно скидає колір термінала до стандартного значення, наприклад, щоб вказати що потрібно очистити фон. Хоча це залежить від терміналу, зазвичай це не те саме, що встановити значення "white black".
+
Кольори також можуть бути задані числами від 0 до 255; вони використовують 256-кольоровий режим ANSI (але зауважте, що не всі термінали можуть підтримувати це). Якщо ваш термінал підтримує це, ви також можете вказати 24-бітні значення RGB у шістнадцятковому форматі, наприклад `#ff0ab3`, або 12-бітні значення RGB, наприклад `#f1b`, що еквівалентно 24-бітному кольору `#ff11bb`.
+
Допустимі атрибути: `bold`, `dim`, `ul`, `blink`, `reverse`, `italic` та `strike` (для перекреслених або «закреслених» літер). Положення будь-яких атрибутів відносно кольорів (до, після або посередині) не має значення. Певні атрибути можна вимкнути, додавши перед ними префікс `no` або `no-` (наприклад, `noreverse`, `no-ul` тощо).
+
Псевдоатрибут `reset` скидає всі кольори та атрибути перед застосуванням заданого кольору. Наприклад, `reset green` призведе до зеленого кольору символів на стандартному фоні без будь-яких активних атрибутів.
+
Порожній рядок кольору взагалі не створює жодного колірного ефекту. Це можна використовувати, щоб уникнути забарвлення певних елементів, не вимикаючи колір повністю.
+
Для попередньо визначених кольорових слотів git атрибути мають скидатися на початку кожного елемента у кольоровому виводі. Тож встановлення `color.decorate.branch` на `black` зафарбує назву цієї гілки у звичайний `black`, навіть якщо попередній елемент у тому ж рядку виводу (наприклад, відкриваюча дужка перед списком назв гілок у виводі `log --decorate`) налаштовано на зафарбовування `bold` або якимось іншим атрибутом. Однак, у власних форматах логів може використовуватися більш складне та багатошарове забарвлення, і там можуть стати в нагоді форми з запереченням.

pathname::
	Змінній, яка приймає значення шляху, можна надати рядок, що починається з "`~/`" або "`~user/`", і для такого рядка відбувається звичайне розгортання тильди: `~/` розгортається до значення `$HOME`, а `~user/  — до домашньої теки вказаного користувача.
+
Якщо шлях починається з `%(prefix)/`, решта інтерпретується як шлях відносно "префікса середовища виконання" Git, тобто відносно місця, де було встановлено сам Git. Наприклад, `%(prefix)/bin/` посилається на теку, в якій знаходиться сам виконуваний файл Git. Якщо Git було скомпільовано без підтримки префіксів середовища виконання, замість нього буде підставлено скомпільований префікс. У малоймовірному випадку, якщо потрібно вказати літерал шляху, який _не_ слід розгортати, його потрібно починати з `./`, ось так: `./%(prefix)/bin`.
+
Якщо перед змінною є префікс `:(optional)`, вона трактується так, ніби її не існує, якщо вказаний шлях не існує.

Змінні
~~~~~~

Зверніть увагу, що цей список не є вичерпним і не обовʼязково повним. Для змінних, що стосуються певних команд, ви знайдете детальніший опис у відповідній сторінці довідки.

Інші інструменти, пов’язані з Git, можуть використовувати власні змінні і насправді це роблять. Створюючи нові змінні для використання у власному інструменті, переконайтеся, що їхні імена не суперечать іменам, які використовує сам Git та інші популярні інструменти, і опишіть їх у своїй документації.

include::config/add.adoc[]

include::config/advice.adoc[]

include::config/alias.adoc[]

include::config/am.adoc[]

include::config/apply.adoc[]

include::config/attr.adoc[]

include::config/bitmap-pseudo-merge.adoc[]

include::config/blame.adoc[]

include::config/branch.adoc[]

include::config/browser.adoc[]

include::config/bundle.adoc[]

include::config/checkout.adoc[]

include::config/clean.adoc[]

include::config/clone.adoc[]

include::config/color.adoc[]

include::config/column.adoc[]

include::config/commit.adoc[]

include::config/commitgraph.adoc[]

include::config/completion.adoc[]

include::config/core.adoc[]

include::config/credential.adoc[]

include::config/diff.adoc[]

include::config/difftool.adoc[]

include::config/extensions.adoc[]

include::config/fastimport.adoc[]

include::config/feature.adoc[]

include::config/fetch.adoc[]

include::config/filter.adoc[]

include::config/format.adoc[]

include::config/fsck.adoc[]

include::config/fsmonitor--daemon.adoc[]

include::config/gc.adoc[]

include::config/gitcvs.adoc[]

include::config/gitweb.adoc[]

include::config/gpg.adoc[]

include::config/grep.adoc[]

include::config/gui.adoc[]

include::config/guitool.adoc[]

include::config/help.adoc[]

include::config/http.adoc[]

include::config/i18n.adoc[]

include::config/imap.adoc[]

include::config/includeif.adoc[]

include::config/index.adoc[]

include::config/init.adoc[]

include::config/instaweb.adoc[]

include::config/interactive.adoc[]

include::config/log.adoc[]

include::config/lsrefs.adoc[]

include::config/mailinfo.adoc[]

include::config/mailmap.adoc[]

include::config/maintenance.adoc[]

include::config/man.adoc[]

include::config/merge.adoc[]

include::config/mergetool.adoc[]

include::config/notes.adoc[]

include::config/pack.adoc[]

include::config/pager.adoc[]

include::config/pretty.adoc[]

include::config/promisor.adoc[]

include::config/protocol.adoc[]

include::config/pull.adoc[]

include::config/push.adoc[]

include::config/rebase.adoc[]

include::config/receive.adoc[]

include::config/reftable.adoc[]

include::config/remote.adoc[]

include::config/remotes.adoc[]

include::config/repack.adoc[]

include::config/rerere.adoc[]

include::config/revert.adoc[]

include::config/safe.adoc[]

include::config/sendemail.adoc[]

include::config/sequencer.adoc[]

include::config/showbranch.adoc[]

include::config/sparse.adoc[]

include::config/splitindex.adoc[]

include::config/ssh.adoc[]

include::config/stash.adoc[]

include::config/status.adoc[]

include::config/submodule.adoc[]

include::config/tag.adoc[]

include::config/tar.adoc[]

include::config/trace2.adoc[]

include::config/trailer.adoc[]

include::config/transfer.adoc[]

include::config/uploadarchive.adoc[]

include::config/uploadpack.adoc[]

include::config/url.adoc[]

include::config/user.adoc[]

include::config/versionsort.adoc[]

include::config/web.adoc[]

include::config/worktree.adoc[]
