ФОРМАТИ ДАТИ
------------

Змінні середовища `GIT_AUTHOR_DATE` та `GIT_COMMITTER_DATE` підтримують такі формати дати:

Внутрішній формат Git::
	Це `<unix-timestamp> <time-zone-offset>`, де `<unix-timestamp>` – це кількість секунд з епохи UNIX. `<time-zone-offset>` – це додатне або від’ємне зміщення відносно UTC. Наприклад, CET (що на 1 годину випереджає UTC) – це `+0100`.

RFC 2822::
	Стандартний формат дати, як описано в RFC 2822, наприклад, `Чт, 07 квітня 2005 22:13:13 +0200`.

ISO 8601::
	Час і дата, визначені стандартом ISO 8601, наприклад, `2005-04-07T22:13:13`. Парсер також приймає пробіл замість символу `T`. Дробові частини секунди будуть ігноруватися, наприклад, `2005-04-07T22:13:13.019` буде оброблено як `2005-04-07T22:13:13`.
+
NOTE: Крім того, частина дати приймається в таких форматах: `РРРР.ММ.ДД`, `ММ/ДД/РРРР` та `ДД.ММ.РРРР`.

ifdef::git-commit[]
Окрім розпізнавання всіх вищезазначених форматів дати, опція `--date` також спробує розібратися з іншими, більш орієнтованими на людину форматами дати, такими як відносні дати, такі як "вчора" або "минулої п'ятниці опівдні".
endif::git-commit[]
