[[generate_patch_text_with_p]]
Генерація тексту латки за допомогою -p
--------------------------------------

Виконання команд linkgit:git-diff[1], linkgit:git-log[1], linkgit:git-show[1], linkgit:git-diff-index[1], linkgit:git-diff-tree[1] або linkgit:git-diff-files[1] з опцією `-p` створює текст латки. Ви можете налаштувати створення тексту латки за допомогою змінних середовища `GIT_EXTERNAL_DIFF` та `GIT_DIFF_OPTS` (див. linkgit:git[1]), а також атрибута `diff` (див. linkgit:gitattributes[5]).

Текст, який ви отримаєте з використанням опції `-p`, дещо відрізняється від традиційного формату diff:

1.   Йому передує заголовок "git diff", який виглядає так:

       diff --git a/file1 b/file2
+
Імена файлів `a/` та `b/` однакові, якщо не йдеться про перейменування/копіювання. Зокрема, навіть для створення або видалення, `/dev/null` _не_ використовується замість імен файлів `a/` або `b/`.
+
Коли йдеться про перейменування/копіювання, `file1` та `file2` показують відповідно назву вихідного файлу перейменування/копіювання та назву файлу, який створюється в результаті перейменування/копіювання.

2.   За ним йде один або декілька рядків розширеного заголовка:
+
[synopsis]
старий режим <режим>
новий режим <режим>
видалений файл режим <режим>
новий файл режим <режим>
копіювати з <шлях>
копіювати до <шлях>
перейменувати з <шлях>
перейменувати в <шлях>
індекс подібності <номер>
індекс несхожості <номер>
індекс <хеш>..<хеш> <режим>
+
Режими файлів _<режим>_ виводиться у вигляді 6-значні вісімкових чисел, включаючи тип файлу та біти прав доступу до файлу.
+
Імена шляхів у розширених заголовках не містять префіксів `a/` та `b/`.
+
Індекс подібності — це відсоток незмінених рядків, а індекс несхожості — відсоток змінених рядків. Це округлене до меншого значення ціле число, за яким стоїть знак відсотка. Значення індексу подібності 100% таким чином зарезервовано для двох однакових файлів, тоді як несхожість 100% означає, що жоден рядок зі старого файлу не потрапив до нового.
+
Рядок індексу містить імена блоб-обʼєктів до та після зміни. _<Режим>_ додається, якщо режим файлу не змінюється; інакше окремі рядки вказують на старий та новий режими.

3.  Шляхи з «незвичайними» символами беруться в лапки, як це пояснено для змінної конфігурації `core.quotePath` (див. linkgit:git-config[1]).

4.  Усі файли `file1` у виводі посилаються на файли до коміту, а всі файли `file2` посилаються на файли після коміту. Неправильно застосовувати кожну зміну до кожного файлу послідовно. Наприклад, ця латка поміняє місцями a та b:

      diff --git a/a b/b
      rename from a
      rename to b
      diff --git a/b b/a
      rename from b
      rename to a

5.  У заголовках фрагмента згадується назва функції, до якої він застосовується. Див. "Визначення власного заголовка фрагмента" в linkgit:gitattributes[5] для отримання детальної інформації про те, як налаштувати це для конкретних мов (програмування).


Формат обʼєднаних відмінностей (combined diff)
----------------------------------------------

Будь-яка команда, що генерує відмінності, може використовувати опцію `-c` або `--cc` для створення «обʼєднаних відмінностей» під час показу злиття. Це стандартний формат під час показу злиття за допомогою linkgit:git-diff[1] або linkgit:git-show[1]. Також зауважте, що ви можете надати відповідну опцію `--diff-merges` будь-якій із цих команд, щоб примусово генерувати відмінності у певному форматі.

Формат «обʼєднаних відмінностей» виглядає так:

------------
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
------------

1.   Йому передує заголовок "git diff", який виглядає ось так (коли використовується опція `-c`):

       diff --combined file
+
або ось так (коли використовується опція `--cc`):

       diff --cc file

2.   За ним йде один або декілька розширених рядків заголовка (у цьому прикладі показано злиття з двома батьківськими обʼєктами):
+
[synopsis]
індекс <hash>,<hash>..<hash>
режим <mode>,<mode>..<mode>
новий файловий режим <mode>
режим видаленого файлу <mode>,<mode>
+
Рядок `mode <mode>,<mode>..<mode>` зʼявляється лише тоді, коли хоча б один з <mode> відрізняється від решти. Розширені заголовки з інформацією про виявлене переміщення контенту (перейменування та виявлення копіювання) спроєктовані для роботи з diff двох _<деревоподібних>_ обʼєктів і не використовуються форматом combined diff.

3.   Далі йде дворядковий заголовок from-file/to-file:

       --- a/файл
       +++ б/файл
+
Подібно до дворядкового заголовка для традиційного «уніфікованого» формату diff, `/dev/null` використовується для повідомлення про створені або видалені файли.
+
Однак, якщо вказано опцію --combined-all-paths, замість дворядкового заголовка from-file/to-file ви отримаєте N+1 рядковий заголовок from-file/to-file, де N — кількість батьківських обʼєктів у коміті злиття:

       --- a/файл
       --- a/файл
       --- a/файл
       +++ б/файл
+
Цей розширений формат може бути корисним, якщо активовано виявлення перейменування або копіювання, щоб дозволити вам бачити оригінальну назву файлу в різних батьківських обʼєктах.

4.   Формат заголовка фрагмента змінено, щоб запобігти випадковому передаванню його до `patch -p1`. Формат обʼєднаних відмінностей був створений для перегляду змін у комітах злиття та не призначався для їх впровадження. Зміна подібна до зміни в розширеному заголовку 'index':

       @@@ <from-file-range> <from-file-range> <to-file-range> @@@
+
У заголовку фрагмента є (кількість батьківських обʼєктів + 1) символи `@` для формату обʼєднаних відмінностей.

На відміну від традиційного «уніфікованого» формату відмінностей, який показує два файли A та B з одним стовпцем із префіксом `-` (мінус -- зʼявляється в A, але видалений в B), `+` (плюс -- відсутній в A, але доданий до B) або `" "` (пробіл -- без змін), цей формат порівнює два або більше файлів file1, file2,... з одним файлом X та показує, чим X відрізняється від кожного з fileN. Один стовпець для кожного з fileN додається до рядка виводу, щоб відзначити, чим рядок X відрізняється від нього.

Символ `-` у стовпці N означає, що рядок зʼявляється у файлі N, але не зʼявляється в результаті. Символ `+` у стовпці N означає, що рядок зʼявляється в результаті, а файл N не містить цього рядка (іншими словами, рядок було додано з погляду батьківського обʼєкта).

У наведеному вище прикладі виводу сигнатуру функції було змінено в обох файлах (отже, два видалення `-` з файлу file1 та файлу file2, плюс `++`, що означає, що один доданий рядок не відображається ні у файлі file1, ні у файлі file2). Також, вісім інших рядків є такими як у файлі file1, але не відображаються у файлі file2 (отже, з префіксом `+`).

Коли цей формат виводиться за допомогою команди `git diff-tree -c`, він порівнює батьківські обʼєкти коміту злиття з результатом злиття (тобто file1..fileN є батьками). У виводі за допомогою команди `git diff-files -c`, він порівнює два нерозвʼязані батьківські обʼєкти злиття з файлом робочого дерева (тобто file1 — це stage 2, також відомий як "наша версія", file2 — це stage 3, також відомий як "їхня версія").
