[[generate_patch_text_with_p]]
Генерація тексту патча за допомогою -p
--------------------------------------

Виконання команд linkgit:git-diff[1], linkgit:git-log[1], linkgit:git-show[1], linkgit:git-diff-index[1], linkgit:git-diff-tree[1] або linkgit:git-diff-files[1] з опцією `-p` створює текст патча. Ви можете налаштувати створення тексту патча за допомогою змінних середовища `GIT_EXTERNAL_DIFF` та `GIT_DIFF_OPTS` (див. linkgit:git[1]), а також атрибута `diff` (див. linkgit:gitattributes[5]).

Те, що видається опцією `-p`, дещо відрізняється від традиційного формату diff:

1.   Йому передує заголовок "git diff", який виглядає так:

       diff --git a/file1 b/file2
+
Імена файлів `a/` та `b/` однакові, якщо не йдеться про перейменування/копіювання. Зокрема, навіть для створення або видалення `/dev/null` _не_ використовується замість імен файлів `a/` або `b/`.
+
Коли йдеться про перейменування/копіювання, `file1` та `file2` показують відповідно назву вихідного файлу перейменування/копіювання та назву файлу, який створюється в результаті перейменування/копіювання.

2.   За ним йде один або декілька розширених рядків заголовка:
+
[synopsis]
старий режим <режим>
новий режим <режим>
видалений файл режим <режим>
новий файл режим <режим>
копіювати з <шлях>
копіювати до <шлях>
перейменувати з <шлях>
перейменувати в <шлях>
індекс подібності <номер>
індекс несхожості <номер>
індекс <хеш>..<хеш> <режим>
+
Режими файлів _<режим>_ друкуються як 6-значні вісімкові числа, включаючи тип файлу та біти прав доступу до файлу.
+
Імена шляхів у розширених заголовках не містять префіксів `a/` та `b/`.
+
Індекс подібності – це відсоток незмінених рядків, а індекс несхожості – відсоток змінених рядків. Це округлене до меншого значення ціле число, за яким стоїть знак відсотка. Значення індексу подібності 100% таким чином зарезервовано для двох однакових файлів, тоді як несхожість 100% означає, що жоден рядок зі старого файлу не потрапив до нового.
+
Рядок індексу містить імена блоб-об'єктів до та після зміни. _<mode>_ додається, якщо режим файлу не змінюється; інакше окремі рядки вказують на старий та новий режими.

3.  Шляхи з «незвичайними» символами взяті в лапки, як пояснено для змінної конфігурації `core.quotePath` (див. linkgit:git-config[1]).

4.  Усі файли `file1` у виводі посилаються на файли до коміту, а всі файли `file2` посилаються на файли після коміту. Неправильно застосовувати кожну зміну до кожного файлу послідовно. Наприклад, цей патч поміняє місцями a та b:

      diff --git a/a b/b
      rename from a
      rename to b
      diff --git a/b b/a
      rename from b
      rename to a

5.  У заголовках ханка згадується назва функції, до якої застосовується ханк. Див. "Визначення власного заголовка ханка" в linkgit:gitattributes[5] для отримання детальної інформації про те, як налаштувати це для певних мов.


Комбінований формат різниці
---------------------------

Будь-яка команда, що генерує різниці, може використовувати опцію `-c` або `--cc` для створення «об’єднаної різниці» під час показу злиття. Це формат за замовчуванням під час показу злиття за допомогою linkgit:git-diff[1] або linkgit:git-show[1]. Також зауважте, що ви можете надати відповідну опцію `--diff-merges` будь-якій із цих команд, щоб примусово генерувати різниці у певному форматі.

Формат "комбінованої різниці" виглядає так:

------------
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
------------

1.   Йому передує заголовок "git diff", який виглядає ось так (коли використовується опція `-c`):

       diff --combined file
+
або ось так (коли використовується опція `--cc`):

       diff --cc file

2.   За ним йде один або декілька розширених рядків заголовка (у цьому прикладі показано злиття з двома батьківськими об'єктами):
+
[synopsis]
індекс <hash>,<hash>..<hash>
режим <mode>,<mode>..<mode>
новий файловий режим <mode>
режим видаленого файлу <mode>,<mode>
+
Рядок `mode <mode>,<mode>..<mode>` з'являється лише тоді, коли хоча б один з <mode> відрізняється від решти. Розширені заголовки з інформацією про виявлене переміщення контенту (перейменування та виявлення копіювання) розроблені для роботи з diff двох _<tree-ish>_ і не використовуються комбінованим форматом diff.

3.   Далі йде дворядковий заголовок from-file/to-file:

       --- a/файл
       +++ б/файл
+
Подібно до дворядкового заголовка для традиційного «уніфікованого» формату diff, `/dev/null` використовується для сигналізації про створені або видалені файли.
+
Однак, якщо вказано опцію --combined-all-paths, замість дворядкового заголовка from-file/to-file ви отримаєте N+1 рядковий заголовок from-file/to-file, де N — кількість батьківських об'єктів у коміті злиття:

       --- a/файл
       --- a/файл
       --- a/файл
       +++ б/файл
+
Цей розширений формат може бути корисним, якщо активовано виявлення перейменування або копіювання, щоб дозволити вам бачити оригінальну назву файлу в різних батьківських об'єктах.

4.   Формат заголовка фрагмента змінено, щоб запобігти випадковому передаванню його до `patch -p1`. Комбінований формат різниці був створений для перегляду змін у комітах злиття та не призначався для застосування. Зміна подібна до зміни в розширеному заголовку 'index':

       @@@ <from-file-range> <from-file-range> <to-file-range> @@@
+
У заголовку фрагмента є (кількість батьківських об'єктів + 1) символи `@` для комбінованого формату різниці.

На відміну від традиційного «уніфікованого» формату порівняння, який показує два файли A та B з одним стовпцем із префіксом `-` (мінус -- з'являється в A, але видалений в B), `+` (плюс -- відсутній в A, але доданий до B) або `" "` (пробіл -- без змін), цей формат порівнює два або більше файлів file1, file2,... з одним файлом X та показує, чим X відрізняється від кожного з fileN. Один стовпець для кожного з fileN додається до рядка виводу, щоб відзначити, чим рядок X відрізняється від нього.

Символ `-` у стовпці N означає, що рядок з'являється у файлі N, але не з'являється в результаті. Символ `+` у стовпці N означає, що рядок з'являється в результаті, а файл N не містить цього рядка (іншими словами, рядок було додано з точки зору батьківського об'єкта).

У наведеному вище прикладі виводу сигнатуру функції було змінено з обох файлів (отже, два видалення символів `-` з файлу file1 та файлу file2, плюс `++`, що означає, що один доданий рядок не відображається ні у файлі file1, ні у файлі file2). Також, вісім інших рядків є такими ж з файлу file1, але не відображаються у файлі file2 (отже, з префіксом `+`).

Коли відображається за допомогою `git diff-tree -c`, він порівнює батьківські об'єкти коміту злиття з результатом злиття (тобто file1..fileN є батьками). Коли відображається за допомогою `git diff-files -c`, він порівнює два невирішені батьківські об'єкти злиття з робочим файлом дерева (тобто file1 — це етап 2, також відомий як "наша версія", file2 — це етап 3, також відомий як "їхня версія").
