Формат виводу RAW
-----------------

Формат необробленого виводу з `git-diff-index`, `git-diff-tree`, `git-diff-files` та `git diff --raw` дуже схожий.

Ці команди порівнюють два набори речей; те, що порівнюється, відрізняється:

`git-diff-index <tree-ish>`::
	порівнює _<дерево-подібне>_ та файли у файловій системі.

`git-diff-index --cached <tree-ish>`::
	порівнює _<деревоподібне>_ та індекс.

`git-diff-tree [-r] <tree-ish-1> <tree-ish-2> [<pattern>...]`::
        порівнює дерева, названі двома аргументами.

`git-diff-files [<візерунок>...]`::
        порівнює індекс та файли у файловій системі.

Команда `git-diff-tree` починає свій вивід з друку хешу порівнюваного файлу. Після цього всі команди друкують один рядок виводу для кожного зміненого файлу.

Вивідний рядок форматується таким чином:

------------------------------------------------
in-place edit  :100644 100644 bcd1234 0123456 M file0
copy-edit      :100644 100644 abcd123 1234567 C68 file1 file2
rename-edit    :100644 100644 abcd123 1234567 R86 file1 file3
create         :000000 100644 0000000 1234567 A file4
delete         :100644 000000 1234567 0000000 D file5
unmerged       :000000 000000 0000000 0000000 U file6
------------------------------------------------

Тобто, зліва направо:

. a colon.
. режим для "src"; 000000, якщо створення або роз'єднання.
. a space.
. режим для "dst"; 000000, якщо видалення або роз'єднання.
. a space.
. sha1 для "src"; 0\{40\} якщо створення або роз'єднання.
. a space.
. sha1 для "dst"; 0\{40\} якщо видалення, роз'єднання або "робоче дерево не синхронізоване з індексом".
. a space.
. статус, а потім необов'язкове число «оцінки».
. символ табуляції або NUL, коли використовується опція `-z`.
. шлях для "src"
. символ табуляції або NUL, коли використовується опція `-z`; існує лише для C або R.
. шлях для "dst"; існує лише для C або R.
. LF або NUL, коли використовується опція `-z`, для завершення запису.

Можливі статусні літери:

- `A`: додавання файлу
- `C`: копіювання файлу в новий
- `D`: видалення файлу
- `M`: зміна вмісту або режиму файлу
- `R`: перейменування файлу
- `T`: зміна типу файлу (звичайний файл, символічне посилання або підмодуль)
- `U`: файл роз’єднано (ви повинні завершити об’єднання, перш ніж його можна буде зафіксувати)
- `X`: тип зміни "невідомий" (скоріше за все, це помилка, будь ласка, повідомте про неї)

За літерами статусу `C` та `R` завжди йде оцінка (що позначає відсоток подібності між джерелом та цільовим об'єктом переміщення або копіювання). За літерою статусу `M` може йти оцінка (що позначає відсоток відмінності) для перезаписів файлів.

SHA1 для "dst" відображається як суцільні нулі, якщо файл у файловій системі не синхронізований з індексом.

Приклад:

------------------------------------------------
:100644 100644 5be4a4a 0000000 M file.c
------------------------------------------------

Без опції `-z` шляхи з "незвичайними" символами взяті в лапки, як пояснено для змінної конфігурації `core.quotePath` (див. linkgit:git-config[1]). При використанні `-z` ім'я файлу виводиться дослівно, а рядок завершується байтом NUL.

формат diff для злиття
----------------------

`git-diff-tree`, `git-diff-files` та `git-diff --raw` можуть приймати опцію `-c` або `--cc` для генерації виводу diff також для комітів злиття. Вивід відрізняється від формату, описаного вище, наступним чином:

. для кожного з батьків є двокрапка
. є більше режимів "src" та "src" sha1
. статус — це об'єднані символи статусу для кожного батьківського елемента
. немає додаткового числа "оцінка"
. шлях(и) до файлу, розділені табуляцією

Для `-c` та `--cc` відображається лише кінцевий шлях, навіть якщо файл було перейменовано на будь-якому етапі історії. З `--combined-all-paths` відображається назва шляху в кожному батьківському файлі, а потім назва шляху в коміті злиття.

Приклади для `-c` та `--cc` без `--combined-all-paths`:

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	phooey.c
------------------------------------------------

Приклади, коли `--combined-all-paths` додається до `-c` або `--cc`:

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c	desc.c	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	foo.sh	bar.sh	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	fooey.c	fuey.c	phooey.c
------------------------------------------------

Зверніть увагу, що «об’єднана різниця» відображає лише файли, які були змінені з усіх батьківських файлів.


include::diff-generate-patch.adoc[]


інші формати різниці
--------------------

Опція `--summary` описує щойно додані, видалені, перейменовані та скопійовані файли. Опція `--stat` додає графік `diffstat`(1) до виводу. Ці опції можна комбінувати з іншими опціями, такими як `-p`, і вони призначені для використання людиною.

Під час відображення зміни, що включає перейменування або копіювання, вивід `--stat` форматує шляхи компактно, поєднуючи спільний префікс та суфікс шляхів. Наприклад, зміна, яка переміщує `arch/i386/Makefile` на `arch/x86/Makefile` під час модифікації 4 рядків, буде відображена так:

------------------------------------
arch/{i386 => x86}/Makefile    |   4 +--
------------------------------------

Опція `--numstat` надає інформацію diffstat(1), але вона розроблена для легшого використання машиною. Запис у виводі `--numstat` виглядає так:

----------------------------------------
1	2	README
3	1	arch/{i386 => x86}/Makefile
----------------------------------------

Тобто з, зліва направо:

. кількість доданих рядків;
. вкладка;
. кількість видалених рядків;
. вкладка;
. шлях (можливо, з інформацією про перейменування/копіювання);
. новий рядок.

Коли активовано опцію виводу `-z`, вивід форматується таким чином:

----------------------------------------
1	2	README NUL
3	1	NUL arch/i386/Makefile NUL arch/x86/Makefile NUL
----------------------------------------

Тобто:

. кількість доданих рядків;
. вкладка;
. кількість видалених рядків;
. вкладка;
. NUL (існує лише якщо перейменовано/скопійовано);
. ім'я шляху в прообразі;
. NUL (існує лише якщо перейменовано/скопійовано);
. шлях у postimage (існує лише якщо перейменовано/скопійовано);
. NUL.

Додатковий `NUL` перед шляхом преобразу у випадку перейменування дозволяє скриптам, які читають вивід, визначити, чи є поточний запис, що читається, записом з одним шляхом, чи записом перейменування/копіювання без попереднього читання. Після читання доданих та видалених рядків, читання до `NUL` дасть ім'я шляху, але якщо це `NUL`, запис покаже два шляхи.
