// Please don't remove this comment as asciidoc behaves badly when
// the first non-empty line is ifdef/ifndef. The symptom is that
// without this comment the <git-diff-core> attribute conditionally
// defined below ends up being defined unconditionally.
// Last checked with asciidoc 7.0.2.

ifndef::git-format-patch[]
ifndef::git-diff[]
ifndef::git-log[]
:git-diff-core: 1
endif::git-log[]
endif::git-diff[]
endif::git-format-patch[]

ifdef::git-format-patch[]
-p::
--no-stat::
	Створення простих латок без будь-яких diffstats.
endif::git-format-patch[]

ifndef::git-format-patch[]
`-p`::
`-u`::
`--patch`::
	Створення латки (див. <<generate_patch_text_with_p>>).
ifdef::git-diff[]
	Стандартно.
endif::git-diff[]

`-s`::
`--no-patch`::
	Придушує весь вивід механізму порівняння. Це корисно для команд на кшталт `git show`, які стандартно показують латку, щоб придушити їхній вивід, або щоб скасувати дію таких опцій, як `--patch`, `--stat`, вказаних раніше в командному рядку в аліасі.

endif::git-format-patch[]

ifdef::git-log[]
`-m`::
	Показує відмінності для комітів злиття у стандартному форматі. Це схоже на `--diff-merges=on`, за винятком того, що `-m` не видаватиме жодних даних, якщо не вказано також `-p`.

`-c`::
	Створює вивід обʼєднаних відмінностей для комітів злиття. Скорочення для `--diff-merges=combined -p`.

`--cc`::
	Створює щільний вивід обʼєднаних відмінностей для комітів злиття. Скорочення для `--diff-merges=dense-combined -p`.

`--dd`::
	Створює diff відносно першого предка як для злиття, так і для звичайних комітів. Скорочений варіант для `--diff-merges=first-parent -p`.

`--remerge-diff`::
	Створює вивід remerge-diff для комітів злиття. Скорочений варіант для `--diff-merges=remerge -p`.

`--no-diff-merges`::
	Синонім до `--diff-merges=off`.

`--diff-merges=<формат>`::
	Вказує формат diff, який буде використовуватися для злиття комітів. Стандартним є {diff-merges-default}, якщо не використовується опція `--first-parent`; у цьому випадку стандартним є `first-parent`.
+
Підтримуються такі формати:
+
--
`off`::
`none`::
	Вмикає виведення diff для комітів злиття. Корисно для заміни неявного значення.

`on`::
`m`::
	Зробити так, щоб результати порівняння для злиття комітів відображалися у стандартному форматі. Стандартний формат можна змінити за допомогою параметра конфігурації `log.diffMerges`, стандартне значення якого — `separate`.

`first-parent`::
`1`::
	Показати весь diff відносно першого батьківського елемента. Це той самий формат, який створює `--patch` для комітів без злиття.

`separate`::
	Показати весь diff стосовно кожного з батьків. Окремий запис журналу та diff створюється для кожного з батьків.

`combined`::
`c`::
	Одночасно показувати відмінності від кожного з предків до результату злиття, замість того, щоб по черзі показувати парні відмінності між предком і результатом. Крім того, у списку відображаються лише ті файли, які були змінені порівняно з усіма предками.

`dense-combined`::
`cc`::
	Подальше стиснення виводу, отриманого за допомогою `--diff-merges=combined`, шляхом пропускання нецікавих фрагментів, вміст яких у батьківських обʼєктах має лише два варіанти, і результат злиття вибирає один з них без змін.

`remerge`::
`r`:: Повторне обʼєднання двох батьківських комітів злиття для створення тимчасового обʼєкта дерева — який може містити файли з позначками конфліктів тощо. Після цього відображається порівняння між цим тимчасовим деревом і фактичним комітом злиття.
--
+
Вивід, що видається під час використання цієї опції, може змінюватися, як і її взаємодія з іншими опціями (якщо це явно не задокументовано).


`--combined-all-paths`::
	Змушує обʼєднані відмінності (які використовуються для комітів злиття) відображати імена файлів усіх батьківських комітів. Отже, ця опція діє лише за умови використання параметра `--diff-merges=[dense-]combined` і, ймовірно, буде корисною лише в разі виявлення змін у назвах файлів (тобто коли було задано виявлення перейменування або копіювання).
endif::git-log[]

`-U<n>`::
`--unified=<n>`::
	Генерувати diff з _<n>_ рядками контексту замість звичайних трьох.
ifndef::git-format-patch[]
	Мається на увазі `--patch`.
endif::git-format-patch[]

`--output=<файл>`::
	Вивід у вказаний файл замість stdout.

`--output-indicator-new=<char>`::
`--output-indicator-old=<char>`::
`--output-indicator-context=<char>`::
	Визначає символ, який використовуватиметься для позначення нових, старих або контекстних рядків у згенерованій латці. Зазвичай це відповідно `+`, `-` та “ ”.

ifndef::git-format-patch[]
`--raw`::
ifndef::git-log[]
	Створювати diff в форматі raw.
ifdef::git-diff-core[]
	Стандартно.
endif::git-diff-core[]
endif::git-log[]
ifdef::git-log[]
	Для кожного коміту показати підсумок змін за допомогою raw diff
	формат. Див. розділ «ВИХІДНИЙ ФОРМАТ RAW»
	linkgit:git-diff[1]. Це відрізняється від відображення журналу
	 в необробленому форматі, чого можна досягти за допомогою
	`--format=raw`.
endif::git-log[]
endif::git-format-patch[]

ifndef::git-format-patch[]
`--patch-with-raw`::
	Синонім до `-p --raw`.
endif::git-format-patch[]

ifdef::git-log[]
`-t`::
	Показати обʼєкти дерева у виводі diff.
endif::git-log[]

`--indent-heuristic`::
	Увімкнути евристику, яка зсуває межі фрагментів diff, щоб зробити латки легшими для читання. Це стандартне значення.

`--no-indent-heuristic`::
	Вимкнути евристику відступів.

`--minimal`::
	Витрачає додатковий час, щоб переконатися, що отримано найменший можливий diff.

`--patience`::
	Створювати diff використовуючи алгоритм "patience diff".

`--histogram`::
	Створювати diff використовуючи алгоритм "histogram diff".

`--anchored=<text>`::
	Створювати diff використовуючи алгоритм "anchored diff".
+
Цей параметр можна вказати більше одного разу.
+
Якщо рядок існує як у вихідному, так і в цільовому тексті, зустрічається лише один раз і починається з _<текст>_, цей алгоритм намагається запобігти його появі у вигляді видалення або додавання у результаті. Внутрішньо він використовує алгоритм «patience diff».

include::diff-algorithm-option.adoc[]

`--stat[=<width>[,<name-width>[,<count>]]]`::
	Генерує diffstat. Як правило, для частини з іменами файлів використовується стільки місця, скільки потрібно, а решта — для частини з таблицями. Стандартна максимальна ширина дорівнює ширині терміналу або 80 стовпців, якщо підключення до терміналу відсутнє; це значення можна змінити за допомогою параметра _<width>_. Ширину частини імені файлу можна обмежити, вказавши іншу ширину _<name-width>_ після коми або встановивши `diff.statNameWidth=<name-width>`. Ширину частини таблиці можна обмежити, використовуючи `--stat-graph-width=<graph-width>` або встановивши `diff.statGraphWidth=<graph-width>`. Використання `--stat` або `--stat-graph-width` впливає на всі команди, що генерують граф статистики, тоді як встановлення `diff.statNameWidth` або `diff.statGraphWidth` не впливає на `git format-patch`. Вказавши третій параметр _<count>_, ви можете обмежити вивід першими _<count>_ рядками, за якими слідує `...`, якщо їх більше.
+
Ці параметри також можна встановити окремо за допомогою `--stat-width=<ширина>`, `--stat-name-width=<ширина-назви>` та `--stat-count=<кількість>`.

`--compact-summary`::
	Виводити у diffstat стислий звіт про інформацію розширеного заголовка, таку як створення або видалення файлів («new» або «gone», за бажанням із позначкою `+l`, якщо це символічне посилання), а також зміни прав доступу (`+x` або `-x` для додавання чи видалення біта виконуваності відповідно). Ця інформація розміщується між частиною з іменем файлу та частиною з графом. Передбачає використання опції `--stat`.

`--numstat`::
	Подібно до `--stat`, але показує кількість доданих та видалених рядків у десятковому форматі та шлях без скорочень, що робить його зручнішим для машинної обробки. Для бінарних файлів виводить два `-` замість `0 0`.

`--shortstat`::
	Виводіть лише останній рядок формату `--stat`, що містить загальну кількість змінених файлів, а також кількість доданих та видалених рядків.

`-X [<param>,...]`::
`--dirstat[=<param>,...]`::
	Виводіть розподіл відносної кількості змін для кожної субтеки. Поведінку `--dirstat` можна налаштувати, передавши список параметрів, розділених комами. Стандартне значення контролюються змінною конфігурації `diff.dirstat` (див. linkgit:git-config[1]). Доступні такі параметри:
+
--
`changes`;;
	Обчислює показники dirstat шляхом підрахунку рядків, які були видалені з вихідного файлу або додані до файлу призначення. При цьому не враховується кількість переміщень коду всередині самого файлу. Іншими словами, перегрупування рядків у файлі не враховується так само, як інші зміни. Це стандартна поведінка, якщо параметр не вказано.
`lines`;;
	Обчислює показники dirstat, виконуючи звичайний аналіз відмінностей на основі рядків та підсумовуючи кількість видалених/доданих рядків. (Для бінарних файлів рахує 64-байтові блоки, оскільки бінарні файли не мають природного поняття рядків). Такий підхід `--dirstat` є більш ресурсоємним, ніж підхід `changes`, але він враховує перегруповані рядки у файлі нарівні з іншими змінами. Отриманий результат відповідає тому, що ви отримуєте від інших опцій `--*stat`.
`files`;;
	Обчислює показники dirstat, рахуючи кількість змінених файлів. Кожен змінений файл має однакову вагу в аналізі dirstat. Це найменш ресурсомісткий варіант роботи опції `--dirstat`, оскільки він взагалі не вимагає аналізу вмісту файлів.
`cumulative`;;
	Також підраховуються зміни у дочірній теці батьківської теки. Зверніть увагу, що при використанні параметра `cumulative` сума вказаних відсотків може перевищувати 100%. Стандартну поведінку (без накопичення) можна вказати за допомогою параметра `noncumulative`.
_<limit>_;;
	Цілочисельний параметр визначає граничний відсоток (стандартно — 3%). Теки, що вносять менше змін, ніж цей відсоток, не відображаються у виводі.
--
+
Приклад: Наступна команда підрахує змінені файли, ігноруючи при цьому теки, в яких міститься менше ніж 10 % від загальної кількості змінених файлів, та підсумовуючи кількість файлів у дочірніх теках в батьківських теках: `--dirstat=files,10,cumulative`.

`--cumulative`::
	Синонім до `--dirstat=cumulative`.

`--dirstat-by-file[=<param>,...]`::
	Синонім до `--dirstat=files,<param>,...`.

`--summary`::
	Виводить стислий підсумок інформації розширеного заголовка, такої як створення, перейменування та зміни режиму.

ifndef::git-format-patch[]
`--patch-with-stat`::
	Синонім до `-p --stat`.
endif::git-format-patch[]

ifndef::git-format-patch[]

`-z`::
ifdef::git-log[]
	Розділяйте коміти символами __NUL__ замість символів нового рядка.
+
Також, коли вказано `--raw` або `--numstat`, не змінювати шляхи та використовуйте __NUL__ як символи завершення полів виводу.
endif::git-log[]
ifndef::git-log[]
	Якщо вказано параметри `--raw`, `--numstat`, `--name-only` або `--name-status`,
	не змінювати імена шляхів і використовувати символи NUL як роздільники полів у вихідних даних.
endif::git-log[]
+
Без цієї опції шляхи з «незвичайними» символами беруться в лапки, як це пояснено для змінної конфігурації `core.quotePath` (див. linkgit:git-config[1]).

`--name-only`::
	Показувати лише назву кожного зміненого файлу в дереві пост-образів. Назви файлів часто кодуються в UTF-8. Для отримання додаткової інформації див. обговорення кодування на сторінці довідки linkgit:git-log[1].

`--name-status`::
	Показувати лише імʼя(імена) та стан кожного зміненого файлу. Дивіться опис опції `--diff-filter` щодо значення літер стану. Так само як і `--name-only`, імена файлів часто кодуються в UTF-8.

`--submodule[=<формат>]`::
	Визначає, як відображатимуться відмінності в субмодулях. Для `--submodule=short` використовується формат `short`. Цей формат показує лише імена комітів на початку та в кінці діапазону. Якщо вказано `--submodule` або `--submodule=log`, використовується формат `log`. Цей формат перелічує коміти в діапазоні, як це робить linkgit:git-submodule[1] `summary`. При вказанні `--submodule=diff` використовується формат `diff`. Цей формат показує порівняння змін у вмісті субмодуля між діапазоном комітів. Стандартним є `diff.submodule` або формат `short`, якщо опція конфігурації не встановлена.

`--color[=<when>]`::
	Показує відмінності з кольоровою підсвіткою. `--color` (тобто без `=<when>`) те саме, що й `--color=always`. _<when>_ може бути одним із `always`, `never` або `auto`.
ifdef::git-diff[]
	Це можна змінити за допомогою параметрів конфігурації
	`color.ui` та `color.diff`.
endif::git-diff[]

`--no-color`::
	Вимикає кольорову підсвітку відмінностей.
ifdef::git-diff[]
	Цей параметр можна використовувати для зміни налаштувань конфігурації.
endif::git-diff[]
	Це те саме, що `--color=never`.

`--color-moved[=<режим>]`::
	Переміщені рядки коду забарвлюються по-різному.
ifdef::git-diff[]
	Це можна змінити за допомогою параметра конфігурації `diff.colorMoved`.
endif::git-diff[]
	Якщо параметр не вказано, типовим значенням для _<режим>_ є `no`, 
	а якщо вказано параметр без режиму — `zebra`.
	Режим повинен бути одним із таких:
+
--
`no`::
	Переміщені рядки не підсвічуються.
`default`::
	Є синонімом `zebra`. У майбутньому це може змінитися на раціональніший режим.
`plain`::
	Будь-який рядок, який було додано в одному місці та видалено в іншому, буде виділено кольором `color.diff.newMoved`. Аналогічно, колір `color.diff.oldMoved` застосовуватиметься до видалених рядків, які було додано в іншому місці в відмінностях. Цей режим виявляє будь-які переміщені рядки, але під час рецензування він не дуже корисний для визначення того, чи було переміщено блок коду без зміни порядку.
`blocks`::
	Блоки переміщеного тексту, що містять щонайменше 20 літерно-цифрових символів, виявляються за алгоритмом «greedy». Виявлені блоки зафарбовуються кольором `color.diff.(old|new)Moved`. Суміжні блоки неможливо розрізнити.
`zebra`::
	Блоки переміщеного тексту виявляються як у режимі `blocks`. Блоки зафарбовуються кольором `color.diff.(old|new)Moved` або `color.diff.(old|new)MovedAlternative`. Зміна між двома кольорами вказує на виявлення нового блоку.
`dimmed-zebra`::
	Подібно до `zebra`, але виконується додаткове затемнення нецікавих частин переміщеного коду. Лінії, що межують з двома суміжними блоками, вважаються цікавими, решта — нецікавими. `dimmed_zebra` — застарілий синонім.
--

`--no-color-moved`::
	Вимикає виявлення переміщення. Цю опцію можна використовувати для заміни параметрів конфігурації. Вона відповідає параметру `--color-moved=no`.

`--color-moved-ws=<режим>,...`::
	Налаштовує, як ігноруються пробіли під час виконання виявлення переміщення для `--color-moved`.
ifdef::git-diff[]
	Можна встановити за допомогою параметра конфігурації `diff.colorMovedWS`.
endif::git-diff[]
	Ці режими можна вказати у вигляді списку, розділеного комами:
+
--
`no`::
	Не ігнорувати пробіли під час виявлення переміщення.
`ignore-space-at-eol`::
	Ігнорувати зміни пробілів в кінці рядків.
`ignore-space-change`::
	Ігнорувати зміни кількості пробілів. Ігнорує пробіли в кінці рядка та вважає всі інші послідовності з одного або кількох пробільних символів еквівалентними.
`ignore-all-space`::
	Ігнорувати пробіли під час порівняння рядків. Ігнорує відмінності, навіть якщо один рядок має пробіли, а інший їх не має.
`allow-indentation-change`::
	Спочатку ігнорувати будь-які пробіли у виявленні переміщення, а потім групувати переміщені блоки коду в блок, лише якщо зміна пробілів однакова для кожного рядка. Це несумісно з іншими режимами.
--

`--no-color-moved-ws`::
	Не ігнорувати пробіли під час виявлення переміщення. Можна використовувати для перевизначення налаштувань конфігурації. Це те саме, що `--color-moved-ws=no`.

`--word-diff[=<mode>]`::
	Зазвичай слова розділяються пробілами; див. `--word-diff-regex` нижче. _<mode>_ стандартно має значення `plain` і має бути одним з:
+
--
`color`::
	Виділяє змінені слова, використовуючи лише кольори. Мається на увазі `--color`.
`plain`::
	Показує слова як ++[-removed-]++ та ++{+added+}++. Не намагається екранувати роздільники, якщо вони зʼявляються у вхідних даних, тому вивід може бути неоднозначним.
`porcelain`::
	Використовує спеціальний рядковий формат, призначений для використання скриптами. Додані/видалені/незмінені прогони виводяться у звичайному уніфікованому форматі відмінностей, починаючи з символу `+`/`-`/` ` на початку рядка та продовжуючи до кінця рядка. Перехід на новий рядок у вхідних даних позначається тильдою `~` на окремому рядку.
`none`::
	Знову вимкнути порівняння слів.
--
+
Зверніть увагу, що незважаючи на назву першого режиму, колір використовується для виділення змінених частин у всіх режимах, якщо вони ввімкнені.

`--word-diff-regex=<regex>`::
	Використовуйте _<regex>_ для визначення того, що є словом, замість того, щоб вважати послідовності символів, що не є пробілами, словами. Також передбачає використання параметра `--word-diff`, якщо він ще не був увімкнений.
+
Всі збіги виразу _<regex>_, що не перекриваються, вважаються словами. Все, що знаходиться між цими збігами, вважається пробілами та ігнорується(!) під час пошуку відмінностей. Можливо, вам варто додати `|[^[:space:]]` до вашого регулярного виразу, щоб переконатися, що він відповідає всім символам, які не є пробілами. Збіг, що містить символ нового рядка, без попередження обрізається(!) на цьому символі.
+
Наприклад, `--word-diff-regex=.` трактуватиме кожен символ як слово та, відповідно, показуватиме відмінності посимвольно.
+
Регулярний вираз також можна задати за допомогою драйвера порівняння або параметра конфігурації; див. linkgit:gitattributes[5] або linkgit:git-config[1]. Явне вказання цього параметра має пріоритет над будь-якими налаштуваннями драйвера порівняння або конфігурації. Драйвери порівняння мають пріоритет над налаштуваннями конфігурації.

`--color-words[=<regex>]`::
	Еквівалентно `--word-diff=color` плюс (якщо було вказано регулярний вираз) `--word-diff-regex=<regex>`.
endif::git-format-patch[]

`--no-renames`::
	Вимикає виявлення перейменування, навіть якщо у файлі конфігурації це є стандартним.

`--rename-empty`::
`--no-rename-empty`::
	Чи використовувати порожні блоби як джерело перейменування.

ifndef::git-format-patch[]
`--check`::
	Попереджає, якщо зміни призводять до появи маркерів конфлікту або помилок пробілів. Те, що вважається помилками пробілів, визначається параметром конфігурації `core.whitespace`. У стандартному режимі помилками пробілів вважаються пробіли в кінці рядка (включно з рядками, що складаються виключно з пробілів), а також пробіл, за яким одразу йде символ табуляції в межах початкового відступу рядка. У разі виявлення проблем закінчує роботу з ненульовим кодом стану. Несумісно з параметром `--exit-code`.

`--ws-error-highlight=<kind>`::
	Виділяє помилки пробілів у рядках `context`, `old` або `new` різниці. Кілька значень розділяються комами, `none` скидає попередні значення, `default` скидає список до `new`, а `all` — це скорочення від `old,new,context`. Якщо цей параметр не вказано, а змінна конфігурації `diff.wsErrorHighlight` не встановлена, виділяються лише помилки пробілів у рядках `new`. Помилки пробілів підсвічуються за допомогою `color.diff.whitespace`.

endif::git-format-patch[]

`--full-index`::
	Замість перших кількох символів, відображати повні назви обʼєктів blob для пре- та пост-образів в рядку "index" під час створення виводу у форматі латки.

`--binary`::
	Окрім `--full-index`, виводити бінарний diff, який можна застосувати за допомогою `git-apply`.
ifndef::git-format-patch[]
	Мається на увазі `--patch`.
endif::git-format-patch[]

`--abbrev[=<n>]`::
	Замість повного 40-байтового шістнадцяткового імені об’єкта у вихідних даних формату diff-raw та у заголовках рядків diff-tree показувати найкоротший префікс довжиною не менше _<n>_ шістнадцяткових цифр, який однозначно ідентифікує об’єкт. У форматі виводу diff-patch опція `--full-index` має вищий пріоритет, тобто якщо вказано `--full-index`, повні імена блобів будуть показані незалежно від `--abbrev`. Нестандартну кількість цифр можна вказати за допомогою `--abbrev=<n>`.

`-B[<n>][/<m>]`::
`--break-rewrites[=[<n>][/<m>]]`::
	Розбивати повні зміни перезапису на пари видалення та створення. Це служить двом цілям:
+
Це впливає на те, як зміна, яка зводиться до повного перезапису файлу, представляється не як серія видалення та вставки, змішаних разом з дуже невеликою кількістю рядків, які випадково відповідають контексту, а як одне видалення всього старого, за яким слідує одна вставка всього нового, і число _<m>_ контролює цей аспект опції `-B` (типово — 60%). `-B/70%` вказує, що менше 30% оригіналу має залишитися в результаті, щоб Git вважав це повним перезаписом (тобто інакше отримана латка буде серією видалення та вставки, змішаних разом з рядками контексту).
+
При використанні з `-M`, повністю перезаписаний файл також вважається джерелом перейменування (зазвичай `-M` розглядає лише файл, який зник, як джерело перейменування), а число _<n>_ контролює цей аспект опції `-B` (стандартно — 50%). `-B20%` вказує на те, що зміна з додаванням та видаленням порівняно з 20% або більше від розміру файлу може бути розглянута як можливе джерело перейменування на інший файл.

`-M[<n>]`::
`--find-renames[=<n>]`::
ifndef::git-log[]
	Виявлення перейменувань.
endif::git-log[]
ifdef::git-log[]
	Під час формування списку змін слід виявляти та повідомляти про
	перейменування для кожного коміту. Щоб відстежувати файли після їх
	перейменування під час перегляду історії, див. опцію `--follow`.
endif::git-log[]
	Якщо вказано _<n>_, це означає поріг для індексу схожості
	(тобто частка доданих/видалених даних порівняно з розміром файлу).
	Наприклад, `-M90%` означає, що Git повинен розглядати пару
	«видалення/додавання» як перейменування, якщо більше ніж 90% файлу
	не змінилося. Без знака `%` число слід читати як дріб, з десятковою
	крапкою перед ним. Тобто `-M5` стає 0,5, і, отже, дорівнює `-M50%`.
	Аналогічно, `-M05` дорівнює `-M5%`. Щоб обмежити виявлення лише
	точними перейменуваннями, використовуйте `-M100%`.
	Стандартно індекс схожості становить 50%.

`-C[<n>]`::
`--find-copies[=<n>]`::
	Виявляти копії, а також перейменування. Див. також `--find-copies-harder`. Якщо вказано _<n>_, це має те саме значення, що й `-M<n>`.

`--find-copies-harder`::
	З міркувань продуктивності, типово, опція `-C` знаходить копії, лише якщо оригінальний файл копії був змінений у тому ж наборі змін. Цей прапорець змушує команду перевіряти незмінені файли як кандидатів на джерело копії. Це дуже ресурсомістка операція для великих проєктів, тому використовуйте її з обережністю. Використання кількох опцій `-C` має той самий ефект.

`-D`::
`--irreversible-delete`::
	Не відображати вихідний текст для видалень, тобто виводити лише заголовок, але не різницю між вихідним текстом та `/dev/null`. Отримана латка не призначена для застосування за допомогою `patch` або `git apply`; вона призначена виключно для тих, хто хоче зосередитися лише на перегляді тексту після внесення змін. Крім того, у виведеній інформації явно бракує даних, щоб застосувати таку латку у зворотному напрямку, навіть вручну, звідси й назва цієї опції.
+
При використанні разом з `-B`, також пропускається вихідний текст у частині видалення пари видалення/створення.

`-l<num>`::
	Параметри `-M` та `-C` передбачають виконання деяких попередніх кроків, які дозволяють економічно виявити підмножини випадків перейменування/копіювання, після чого виконується вичерпна резервна перевірка, під час якої всі залишені неспарені місця призначення порівнюються з усіма відповідними джерелами. (Для перейменувань релевантними є лише залишені неспарені джерела; для копіювань — усі оригінальні джерела.) Для N джерел та цілей ця вичерпна перевірка має складність O(N^2). Ця опція запобігає виконанню вичерпної частини виявлення перейменувань/копіювань, якщо кількість залучених файлів-джерел/файлів-цілей перевищує вказану кількість. Стандартне значення — `diff.renameLimit`. Зверніть увагу, що значення 0 трактується як необмежене.

ifndef::git-format-patch[]
`--diff-filter=[(A|C|D|M|R|T|U|X|B)...[*]]`::
	Вибирати лише файли, які додані (`A`), скопійовані (`C`), видалені (`D`), змінені (`M`), перейменовані (`R`), мають змінений тип (наприклад, звичайний файл, символічне посилання, субмодуль тощо) (`T`), не обʼєднані (`U`), невідомі (`X`) або мають розірвану пару (`B`). Можна використовувати будь-яку комбінацію символів фільтра (навіть жодного). Коли до комбінації додається `*` (все-або-нічого), усі шляхи вибираються, якщо в порівнянні є файл, який відповідає іншим критеріям; якщо файлів, що відповідають іншим критеріям, немає, нічого не вибирається.
+
Також ці великі літери можна писати в нижньому регістрі, щоб вказати зворотну дію. Наприклад, `--diff-filter=ad` не включає додані та видалені шляхи.
+
Зверніть увагу, що не всі відмінності можуть відображати всі типи. Наприклад, скопійовані та перейменовані записи не можуть відображатися, якщо виявлення цих типів вимкнено.

`-S<string>`::
	Шукає відмінності, які змінюють кількість входжень зазначеного _<рядка>_ (тобто додавання/видалення) у файлі. Призначено для використання скриптером.
+
Корисно, коли ви шукаєте конкретний фрагмент коду (наприклад, структуру) і хочете дізнатися історію цього фрагмента від моменту його створення: використовуйте цю функцію послідовно, вводячи потрібний фрагмент у вихідні дані команди `-S`, і продовжуйте, доки не отримаєте найпершу версію цього фрагмента.
+
Також виконується пошук у бінарних файлах.

`-G<regex>`::
	Шукає відмінності, текст виправлення яких містить додані/видалені рядки, що відповідають _<regex>_.
+
Щоб проілюструвати різницю між `-S<regex>` `--pickaxe-regex` та `-G<regex>`, розглянемо коміт з наступним diff у тому ж файлі:
+
----
+    return frotz(nitfol, two->ptr, 1, 0);
...
-    hit = frotz(nitfol, mf2.ptr, 1, 0);
----
+
Хоча `git log -G"frotz\(nitfol"` покаже цей коміт, `git log -S"frotz\(nitfol" --pickaxe-regex` ні (оскільки кількість входжень цього рядка не змінилася).
+
Якщо не вказано параметр `--text`, фрагменти бінарних файлів без фільтра textconv будуть ігноруватися.
+
Дивіться опис «pickaxe» у linkgit:gitdiffcore[7] для отримання додаткової інформації.

`--find-object=<object-id>`::
	Шукає відмінності, які змінюють кількість входжень зазначеного обʼєкта. Подібно до `-S`, лише аргумент відрізняється тим, що він не шукає певний рядок, а певний ідентифікатор обʼєкта.
+
Об’єктом може бути блоб або коміт субмодуля. Це має на увазі опцію `-t` у команді `git-log`, яка дозволяє також знаходити дерева.

`--pickaxe-all`::
	Коли `-S` або `-G` знаходить зміну, показати всі зміни в цьому наборі змін, а не лише файли, що містять зміну в _<рядку>_.

`--pickaxe-regex`::
	Обробляти _<рядок>_, переданий `-S`, як розширений регулярний вираз POSIX для збігу.

endif::git-format-patch[]

`-O<файл-порядку>`::
	Керує порядком, у якому файли відображаються у вихідних даних. Замінює значення конфігураційної змінної `diff.orderFile` (див. linkgit:git-config[1]). Щоб скасувати дію `diff.orderFile`, використовуйте `-O/dev/null`.
+
Порядок виведення визначається порядком шаблонів у _<файлі-порядку>_. Спочатку виводяться всі файли, імена яких відповідають першому шаблону, потім — всі файли, імена яких відповідають другому шаблону (але не першому), і так далі. Усі файли, імена яких не відповідають жодному шаблону, виводяться останніми, ніби в кінці файлу був неявний шаблон, що відповідає всім. Якщо кілька імен мають однаковий ранг (вони відповідають одному й тому ж шаблону, але не відповідають попереднім шаблонам), їхній порядок виведення відносно один одного є звичайним.
+
_<файл-порядку>_ має наступний синтаксис:
+
--
 - Пусті рядки ігноруються, тому їх можна використовувати як роздільники для зручності читання.

 - Рядки, що починаються з хеш-символа ("`#`"), ігноруються, тому їх можна використовувати для коментарів. Додайте зворотну скісну риску ("`\`") на початок шаблону, якщо він починається з хеш-символа.

 - Кожен інший рядок містить один шаблон.
--
+
Шаблони мають той самий синтаксис і семантику, що й шаблони, що використовуються для `fnmatch`(3) без прапорця `FNM_PATHNAME`, за винятком того, що імʼя шляху також відповідає шаблону, якщо видалення будь-якої кількості компонентів кінцевого імені шляху відповідає шаблону. Наприклад, шаблон "`foo*bar`" відповідає "`fooasdfbar`" та "`foo/bar/baz/asdf`", але не "`foobarx`".

`--skip-to=<файл>`::
`--rotate-to=<файл>`::
	Вилучіть із виводу файли, що йдуть перед файлом із іменем _<file>_ (тобто «пропустити до»), або перемістіть їх у кінець виводу (тобто «перемістити до»). Ці параметри були розроблені переважно для використання з командою `git difftool` і в інших випадках можуть виявитися не надто корисними.

ifndef::git-format-patch[]
`-R`::
	Поміняти місцями два потоки вхідних даних; тобто показати відмінності між індексом або файлом на диску та вмістом дерева.
endif::git-format-patch[]

`--relative[=<шлях>]`::
`--no-relative`::
	Якщо запускати з субтеки проєкту, за допомогою цього параметра можна вказати, щоб виключити зміни поза межами цієї теки та показувати шляхи відносно неї. Якщо ви не перебуваєте в субтеці (наприклад, у «голому» репозиторії), ви можете вказати, щодо якої саме субтеки має бути відносний вивід, передавши _<path>_ як аргумент. `--no-relative` можна використовувати для скасування як опції конфігурації `diff.relative`, так і попереднього `--relative`.

`-a`::
`--text`::
	Обробляти всі файли як текст.

`--ignore-cr-at-eol`::
	Ігнорувати символ повернення каретки в кінці рядка під час порівняння.

`--ignore-space-at-eol`::
	Ігнорувати зміни пробілів в кінці рядків.

`-b`::
`--ignore-space-change`::
	Ігнорувати зміни кількості пробілів. Ігнорує пробіли в кінці рядка та вважає всі інші послідовності з одного або кількох пробільних символів еквівалентними.

`-w`::
`--ignore-all-space`::
	Ігнорувати пробіли під час порівняння рядків. Ігнорує відмінності, навіть якщо один рядок має пробіли, а інший їх не має.

`--ignore-blank-lines`::
	Ігнорувати зміни, рядки яких порожні.


`-I<регулярний вираз>`::
`--ignore-matching-lines=<регулярний вираз>`::
	Ігнорувати зміни, усі рядки яких відповідають _<регулярному виразу>_. Цей параметр можна вказувати більше одного разу.

`--inter-hunk-context=<number>`::
	Показує контекст між фрагментами відмінностей (diff hunks), до вказаної _<кількості>_ рядків, таким чином обʼєднуючи фрагменти, що знаходяться близько один до одного. Стандартно використовується значення `diff.interHunkContext` або 0, якщо параметр конфігурації не встановлено.

`-W`::
`--function-context`::
	Показувати повну функцію у вигляді контекстних рядків для кожної зміни. Імена функцій визначаються так само як `git diff` обчислює заголовки фрагментів латок (див. «Визначення власного заголовка фрагмента» у linkgit:gitattributes[5]).

ifndef::git-format-patch[]
ifndef::git-log[]
`--exit-code`::
	Зробити так, щоб програма завершувала роботу з кодами, аналогічними до `diff`(1). Тобто вона завершує роботу з кодом 1, якщо були виявлені відмінності, а код 0 означає відсутність відмінностей.

`--quiet`::
	Вимкнути весь вивід програми. Мається на увазі `--exit-code`. Вимкнути виконання зовнішніх помічників diff, код виходу яких не є довіреним, тобто їх відповідний параметр конфігурації `diff.trustExitCode` або ++diff.++__<driver>__++.trustExitCode++ або змінна середовища `GIT_EXTERNAL_DIFF_TRUST_EXIT_CODE` має значення false.
endif::git-log[]
endif::git-format-patch[]

`--ext-diff`::
	Дозволити виконання зовнішнього помічника diff. Якщо ви налаштували зовнішній драйвер diff за допомогою linkgit:gitattributes[5], вам потрібно використовувати цю опцію разом із linkgit:git-log[1] та подібними командами.

`--no-ext-diff`::
	Заборонити сторонні драйвери diff.

`--textconv`::
`--no-textconv`::
	Дозволити (або заборонити) використання зовнішніх фільтрів перетворення тексту під час порівняння бінарних файлів. Див. linkgit:gitattributes[5] для отримання детальної інформації. Оскільки фільтри textconv зазвичай є одностороннім перетворенням, отриманий diff придатний для використання людиною, але не може бути застосований. З цієї причини фільтри textconv стандартно увімкнено лише для linkgit:git-diff[1] та linkgit:git-log[1], але не для linkgit:git-format-patch[1] або команд diff plumbing.


`--ignore-submodules[=(none|untracked|dirty|all)]`::
	Ігнорувати зміни в субмодулях під час формування порівняння. Стандартним значенням є `all`. При використанні `none` субмодуль вважатиметься зміненим, якщо він містить не відстежувані або змінені файли, або якщо його `HEAD` відрізняється від коміту, записаного в суперпроєкті; це дозволяє замінити будь-які налаштування параметра `ignore` у файлах linkgit:git-config[1] або linkgit:gitmodules[5]. При використанні `untracked` субмодулі не вважаються зміненими, якщо вони містять лише не відстежуваний вміст (але вони все одно скануються на наявність зміненого вмісту). Використання `dirty` ігнорує всі зміни у робочому дереві субмодулів, показуються лише зміни у комітах, збережених у суперпроекті (така поведінка була до версії 1.7.0). Використання `all` приховує всі зміни у субмодулях.

`--src-prefix=<prefix>`::
	Показати вказаний _<prefix>_ для джерела замість "a/".

`--dst-prefix=<prefix>`::
	Показувати вказаний _<prefix>_ для призначення замість "b/".

`--no-prefix`::
	Не показувати жодного префікса для джерела чи призначення.

`--default-prefix`::
	Використовувати типові префікси джерела та призначення ("a/" та "b/"). Замінює змінні конфігурації, такі як `diff.noprefix`, `diff.srcPrefix`, `diff.dstPrefix` та `diff.mnemonicPrefix` (див. linkgit:git-config[1]).

`--line-prefix=<prefix>`::
	Додавати додатковий _<prefix>_ до кожного рядка виводу.

`--ita-invisible-in-index`::
	Стандартно записи, додані за допомогою команди `git add -N`, відображаються як наявні порожні файли в `git diff` і як нові файли в `git diff --cached`. Ця опція забезпечує відображення запису як нового файлу в `git diff` і як файлу, що не існує, в `git diff --cached`. Дія цієї опції можна скасувати за допомогою `--ita-visible-in-index`. Обидві опції є експериментальними і можуть бути вилучені в майбутньому.

--max-depth=<depth>::
	Для кожного специфікатора шляху, вказаного в командному рядку, слід просканувати не більше ніж `<depth>` рівнів тек. Значення `-1` означає відсутність обмеження. Не можна поєднувати з символами-замінниками у специфікаторі шляху. Якщо дерево містить `foo/bar/baz`, у наведеному нижче списку показано результати, отримані для кожного набору опцій:
+
--
 - `--max-depth=0 -- foo`: `foo`

 - `--max-depth=1 -- foo`: `foo/bar`

 - `--max-depth=1 -- foo/bar`: `foo/bar/baz`

 - `--max-depth=1 -- foo foo/bar`: `foo/bar/baz`

 - `--max-depth=2 -- foo`: `foo/bar/baz`
--
+
Якщо специфікатор шляху не вказано, глибина вимірюється так, ніби вказано всі записи верхнього рівня. Зверніть увагу, що це відрізняється від вимірювання від кореня тим, що при `--max-depth=0` все одно буде повернуто `foo`. Це дозволяє обмежувати глибину, запитуючи при цьому лише підмножину записів верхнього рівня.
+
Зверніть увагу, що ця опція підтримується лише для порівняння між об’єктами дерева, а не з індексом чи робочим деревом.

Для більш детального пояснення цих поширених опцій див. також linkgit:gitdiffcore[7].
