git-config(1)
=============

НАЗВА
-----
git-config  — Отримання та встановлення параметрів репозиторію або глобальних параметрів


СИНОПСИС
--------
[verse]
'git config list' [<file-option>] [<display-option>] [--includes]
'git config get' [<file-option>] [<display-option>] [--includes] [--all] [--regexp] [--value=<pattern>] [--fixed-value] [--default=<default>] [--url=<url>] <name>
'git config set' [<file-option>] [--type=<type>] [--all] [--value=<pattern>] [--fixed-value] <name> <value>
'git config unset' [<file-option>] [--all] [--value=<pattern>] [--fixed-value] <name>
'git config rename-section' [<file-option>] <old-name> <new-name>
'git config remove-section' [<file-option>] <name>
'git config edit' [<file-option>]
'git config' [<file-option>] --get-colorbool <name> [<stdout-is-tty>]

ОПИС
----
За допомогою цієї команди можна запитувати, встановлювати, замінювати або скидати параметри. Ім’я фактично складається з назви розділу та ключа, розділених крапкою, а значення буде екрановане.

До опції можна додати кілька рядків за допомогою опції `--append`. Якщо ви хочете оновити або скасувати значення опції, яка може зустрічатися в кількох рядках, потрібно вказати `--value=<шаблон>` (що є розширеним регулярним виразом, якщо не вказано опцію `--fixed-value`). Оновлюються або скасовуються лише наявні значення, які відповідають шаблону. Якщо ви хочете обробити рядки, які *не* відповідають шаблону, просто додайте один знак оклику попереду (див. також <<EXAMPLES,ПРИКЛАДИ>>), але зверніть увагу, що це працює лише тоді, коли опція `--fixed-value` не використовується.

Параметр `--type=<type>` вказує команді 'git config' забезпечити можливість канонізації вхідних і вихідних значень відповідно до заданого <type>. Якщо параметр `--type=<type>` не вказано, канонізація не виконуватиметься. Користувачі можуть скасувати дію наявного параметра `--type` за допомогою `--no-type`.

Під час зчитування, значення зазвичай беруться з системних, глобальних та локальних файлів конфігурації репозиторію, а параметри `--system`, `--global`, `--local`, `--worktree` та `--file <filename>` дозволяють вказати команді зчитувати дані лише з цього місця (див. <<FILES,ФАЙЛИ>>).

Під час запису, нове значення зазвичай записується у локальний файл конфігурації репозиторію, а параметри `--system`, `--global`, `--worktree`, `--file <filename>` можна використовувати, щоб вказати команді, куди саме слід записати дані (можна вказати `--local`, але це і так є стандартним значенням).

Ця команда завершиться невдачею з ненульовим статусом у разі помилки. Деякі коди виходу:

- Розділ або ключ недійсний (ret=1),
- не було вказано жодного розділу чи назви (ret=2),
- конфігураційний файл недійсний (ret=3),
- конфігураційний файл неможливо записати (ret=4),
- ви намагаєтеся скасувати значення параметра, якого не існує (ret=5),
- ви намагаєтеся скасувати/встановити параметр, якому відповідають кілька рядків (ret=5), або
- ви намагаєтеся використати недійсний регулярний вираз (ret=6).

У разі успіху команда повертає код виходу 0.

Список усіх доступних змінних конфігурації можна отримати за допомогою команди `git help --config`.

КОМАНДИ
-------

list::
	Вивести перелік всіх змінних, заданих у файлі конфігурації, разом із їхніми значеннями.

get::
	Видає значення вказаного ключа. Якщо ключ присутній кілька разів у конфігурації, видає останнє значення. Якщо вказано `--all`, видає всі значення, повʼязані з ключем. Повертає код помилки 1, якщо ключ відсутній.

set::
	Встановити значення для одного або кількох параметрів конфігурації. Зазвичай ця команда відмовляється записувати багатозначні параметри конфігурації. Передача `--all` замінить усі багатозначні параметри конфігурації новим значенням, тоді як `--value=` замінить усі параметри конфігурації, значення яких відповідають заданому шаблону.

unset::
	Скинути значення для одного або кількох параметрів конфігурації. Зазвичай ця команда відмовляється скидати значення багатозначних ключів. Передача `--all` скине всі багатозначні параметри конфігурації, тоді як `--value` скине всі параметри конфігурації, значення яких відповідають заданому шаблону.

rename-section::
	Перейменує вказаний розділ на нову назву.

remove-section::
	Видалить вказаний розділ з файлу конфігурації.

edit::
	Відкриває редактор для зміни вказаного конфігураційного файлу; `--system`, `--global`, `--local` (зазвичай), `--worktree` або `--file <файл-конфігурації>`.

[[OPTIONS]]
ОПЦІЇ
-----

--replace-all::
	Стандартною поведінкою є заміна не більше одного рядка. При цьому замінюються всі рядки, що відповідають ключу (а також, за бажанням, `--value=<pattern>`).

--append::
	Додає новий рядок до опції, не змінюючи жодних наявних значень. Це те саме, що й надання '--value=^$' у `set`.

--comment <повідомлення>::
	Додає коментар у кінці нових або змінених рядків.
+
Якщо _<повідомлення>_ починається з одного або кількох пробілів, за якими йде "#", воно використовується як є. Якщо воно починається з "#", перед ним додається пробіл. В іншому випадку до нього додається рядок " # " (пробіл, за яким йде хеш, а потім пробіл). Отриманий рядок розміщується одразу після значення, визначеного для змінної. _<Повідомлення>_ не повинно містити символів переведення рядка (багаторядкові коментарі не дозволені).

--all::
	За допомогою функції `get` повертає всі значення для багатозначного ключа.

--regexp::
	За допомогою команди `get` інтерпретує назву як регулярний вираз. Зіставлення регулярних виразів наразі враховує регістр і виконується з канонізованою версією ключа, в якій назви розділів і змінних пишуться у нижнього регістру, а назви підрозділів — ні.

--url=<URL>::
	Якщо вказано двокомпонентне імʼя <name> у форматі <section>.<key>, повертається значення для <section>.<URL>.<key>, частина <URL> якого найкраще збігається із вказаним URL (якщо такого ключа не існує, як запасний варіант використовується значення для <section>.<key>). Якщо вказано лише <section> як ім’я, ця операція виконується для всіх ключів у розділі та виводиться їх список. Повертає код помилки 1, якщо значення не знайдено.

--global::
	Для параметрів запису: записувати у глобальний файл `~/.gitconfig`, а не в репозиторій `.git/config`, записувати у файл `$XDG_CONFIG_HOME/git/config`, якщо цей файл існує, а файл `~/.gitconfig` ні.
+
Для параметрів читання: читати лише з глобального `~/.gitconfig` та з `$XDG_CONFIG_HOME/git/config`, а не з усіх доступних файлів.
+
Див. також <<FILES,ФАЙЛИ>>.

--system::
	Для параметрів запису: записувати до системного файлу `$(prefix)/etc/gitconfig`, а не до репозиторію `.git/config`.
+
Для параметрів читання: читати лише з загальносистемного `$(prefix)/etc/gitconfig`, а не з усіх доступних файлів.
+
Див. також <<FILES,ФАЙЛИ>>.

--local::
	Для параметрів запису: записувати у файл репозиторію `.git/config`. Це стандартна поведінка.
+
Для параметрів читання: читати лише з репозиторію `.git/config`, а не з усіх доступних файлів.
+
Див. також <<FILES,ФАЙЛИ>>.

--worktree::
	Подібно до `--local`, за винятком того, що `$GIT_DIR/config.worktree` зчитується або записується, якщо `extensions.worktreeConfig` увімкнено. Якщо ні, то це те саме, що й `--local`. Зверніть увагу, що `$GIT_DIR` дорівнює `$GIT_COMMON_DIR` для основного робочого дерева, але має вигляд `$GIT_DIR/worktrees/<id>/` для інших робочих дерев. Див. linkgit:git-worktree[1], щоб дізнатися, як увімкнути `extensions.worktreeConfig`.

-f <config-file>::
--file <config-file>::
	Для параметрів запису: записувати у вказаний файл, а не в репозиторій `.git/config`.
+
Для параметрів читання: читати лише з вказаного файлу, а не з усіх доступних файлів.
+
Див. також <<FILES,ФАЙЛИ>>.

--blob <blob>::
	Подібно до `--file`, але замість файлу використовується заданий блоб. Наприклад, ви можете використовувати 'master:.gitmodules' для зчитування значень з файлу '.gitmodules' у гілці master. Див. розділ "ВИЗНАЧЕННЯ РЕВІЗІЙ" у linkgit:gitrevisions[7] для повнішого списку способів написання імен блобів.

`--value=<pattern>`::
`--no-value`::
	З `get`, `set` та `unset`, зіставлення здійснюється лише з _<шаблоном>_. Шаблон є розширеним регулярним виразом, якщо не вказано `--fixed-value`.
+
Використовуйте `--no-value`, щоб скасувати встановлення _<шаблону>_.

--fixed-value::
	При використанні з `--value=<шаблон>`, _<шаблон>_ розглядається як точний рядок, а не як регулярний вираз. Це обмежить пари імʼя/значення, які збігаються, лише тими, де значення точно дорівнює _<шаблону>_.

--type <type>::
  Команда 'git config' гарантує, що будь-які вхідні або вихідні дані відповідають заданим обмеженням типів, а також перетворює вихідні значення у канонічну форму типу `<type>`.
+
Дійсні `<type>` включають:
+
- 'bool': канонізувати значення `true`, `yes`, `on` та додатні числа як "true", а значення `false`, `no`, `off` та `0` як "false".
- 'int': канонізувати значення як прості десяткові числа. Додатковий суфікс 'k', 'm' або 'g' призведе до множення значення на 1024, 1048576 або 1073741824 під час введення.
- 'bool-or-int': канонізувати відповідно до 'bool' або 'int', як описано вище.
- 'path': канонізувати, розгортаючи початковий символ `~` до значення `$HOME` та `~user` до домашньої теки зазначеного користувача. Цей специфікатор не впливає на встановлення значення (але ви можете використати `git config section.variable ~/` з командного рядка, щоб ваша оболонка виконала розгортання).
- 'expiry-date': канонізувати шляхом перетворення фіксованого або відносного рядка дати на відбиток часу. Цей специфікатор не впливає на встановлення значення.
- 'color': під час отримання значення виконується канонізація шляхом перетворення у послідовність кодування кольорів ANSI. Під час встановлення значення виконується перевірка на коректність, щоб переконатися, що задане значення можна канонізувати як колір ANSI, але воно записується без змін.
+

--bool::
--int::
--bool-or-int::
--path::
--expiry-date::
  Історичні опції вибору специфікатора типу. Використовуйте замість цього `--type` (див. вище).

--no-type::
  Скасовує попередньо встановлений специфікатор типу (якщо такий був раніше встановлений). Ця опція вимагає, щоб 'git config' не канонізував отриману змінну. `--no-type` не має ефекту без `--type=<тип>` або `--<тип>`.

-z::
--null::
	Для всіх опцій, що виводять значення та/або ключі, завжди завершувати значення символом null (замість символу нового рядка). Використовувати символ нового рядка як роздільник між ключем і значенням. Це дозволяє безпечно обробляти вивід, не плутаючись, наприклад, зі значеннями, що містять розриви рядків.

--name-only::
	Виводити лише назви змінних конфігурації для `list` або `get`.

`--show-names`::
`--no-show-names`::
	З опцією `get` показуються ключі конфігурації разом із їхніми значеннями. Стандартним значенням є `--no-show-names`, якщо не вказано `--url` і в _<name>_ немає підрозділів.

--show-origin::
	Доповнює вивід усіх запитуваних параметрів конфігурації типом походження (файл, стандартний ввід, блоб, командний рядок) та фактичним походженням (шлях до файлу конфігурації, посилання або ідентифікатор блобу, якщо застосовно).

--show-scope::
	Подібно до параметра `--show-origin`, доповнює вивід усіх запитаних параметрів конфігурації інформацією про область дії цього значення (worktree, local, global, system, command).

--get-colorbool <name> [<stdout-is-tty>]::

	Шукати налаштування кольору для `<name>` (наприклад, `color.diff`) та вивести "true" або "false". `<stdout-is-tty>` має бути або "true", або "false", і враховується, коли конфігурація вказує на "auto". Якщо `<stdout-is-tty>` відсутній, то перевіряється стандартний вивід самої команди та завершується зі статусом 0, якщо має використовуватися колір, або зі статусом 1 в іншому випадку. Коли налаштування кольору для `name` не визначено, команда використовує `color.ui` як резервний варіант.

--includes::
--no-includes::
	Під час пошуку значень враховувати директиви `include.*` у файлах конфігурації. Стандартне значення — `off`, якщо вказано конкретний файл (наприклад, за допомогою опцій `--file`, `--global` тощо), і `on` — під час пошуку у всіх файлах конфігурації.

--default <value>::
  Якщо використовується функція `get`, а запитувана змінна не знайдена, поводитись так, ніби <value> — це значення, призначене цій змінній.

ЗАСТАРІЛІ РЕЖИМИ
----------------

Наступні режими застаріли на користь субкоманд. Рекомендується перейти на новий синтаксис.

'git config <name>'::
	Замінено на `git config get <name>`.

'git config <name> <value> [<value-pattern>]'::
	Замінено на `git config set [--value=<pattern>] <name> <value>`.

-l::
--list::
	Замінено на `git config list`.

--get <name> [<value-pattern>]::
	Замінено на `git config get [--value=<pattern>] <name>`.

--get-all <name> [<value-pattern>]::
	Замінено на `git config get [--value=<pattern>] --all <name>`.

--get-regexp <ім'я-регулярний вираз>::
	Замінено на `git config get --all --show-names --regexp <name-regexp>`.

--get-urlmatch <name> <URL>::
	Замінено на `git config get --all --show-names --url=<URL> <name>`.

--get-color <name> [<default>]::
	Замінено на `git config get --type=color [--default=<default>] <name>`.

--add <name> <value>::
	Замінено на `git config set --append <name> <value>`.

--unset <name> [<value-pattern>]::
	Замінено на `git config unset [--value=<pattern>] <name>`.

--unset-all <name> [<value-pattern>]::
	Замінено на `git config unset [--value=<pattern>] --all <name>`.

--rename-section <old-name> <new-name>::
	Замінено на `git config rename-section <old-name> <new-name>`.

--remove-section <імʼя>::
	Замінено на `git config remove-section <name>`.

-e::
--edit::
	Замінено на `git config edit`.

КОНФІГУРАЦІЯ
------------
`pager.config` враховується лише під час перегляду списку конфігурацій, тобто при використанні команд `list` або `get`, які можуть повертати кілька результатів. Стандартним є використання pager.

[[FILES]]
ФАЙЛИ
-----

Зазвичай, 'git config' зчитуватиме параметри конфігурації з кількох файлів:

$(prefix)/etc/gitconfig::
	Загальносистемний файл конфігурації.

$XDG_CONFIG_HOME/git/config::
~/.gitconfig::
	Файли конфігурації для конкретного користувача. Якщо змінна середовища XDG_CONFIG_HOME не задана або має порожнє значення, як $XDG_CONFIG_HOME використовується тека $HOME/.config/.
+
Їх також називають «глобальними» файлами конфігурації. Якщо обидва файли існують, вони зчитуються в порядку, зазначеному вище.

$GIT_DIR/config::
	Файл конфігурації для конкретного репозиторію.

$GIT_DIR/config.worktree::
	Є необовʼязковим, пошук виконується лише тоді, коли `extensions.worktreeConfig` присутній у $GIT_DIR/config.

Ви також можете надати додаткові параметри конфігурації під час виконання будь-якої команди git, використовуючи опцію `-c`. Див. linkgit:git[1] для отримання детальної інформації.

Опції будуть зчитуватися з усіх доступних файлів. Якщо глобальні або системні файли конфігурації відсутні або нечитабельні, вони будуть проігноровані. Якщо файл конфігурації репозиторію відсутній або нечитабельний, 'git config' завершиться з ненульовим кодом помилки. Повідомлення про помилку виводиться, якщо файл нечитабельний, але не якщо він відсутній.

Файли зчитуються в порядку, зазначеному вище, причому останнє знайдене значення має пріоритет над значеннями, зчитаними раніше. Якщо взято кілька значень, то будуть використані всі значення ключа з усіх файлів.

Зазвичай, параметри записуються лише до конфігураційного файлу репозиторію. Зверніть увагу, що це також впливає на параметри, такі як `set` та `unset`. *'git config' змінюватиме лише один файл за раз*.

Ви можете обмежити джерела конфігурації, з яких зчитуються або куди записуються дані, вказавши шлях до файлу за допомогою опції `--file` або вказавши область конфігурації за допомогою `--system`, `--global`, `--local` або `--worktree`. Докладніше див. у <<OPTIONS,ПАРАМЕТРИ>> вище.

[[SCOPES]]
ОБЛАСТІ ДІЇ
-----------

Кожне джерело конфігурації потрапляє в певну область конфігурації. Це області дії:

system::
	$(prefix)/etc/gitconfig

global::
	$XDG_CONFIG_HOME/git/config
+
~/.gitconfig

local::
	$GIT_DIR/config

worktree::
	$GIT_DIR/config.worktree

command::
	Змінні середовища GIT_CONFIG_{COUNT,KEY,VALUE} (див. <<ENVIRONMENT>> нижче)
+
опція `-c`

За винятком 'command', кожна область дії відповідає параметру командного рядка: `--system`, `--global`, `--local`, `--worktree`.

Під час читання параметрів, якщо вказати область дії, параметри будуть зчитуватися лише з файлів у межах цієї області дії. Під час запису параметрів, якщо вказати область дії, параметри будуть записуватися у файли в межах цієї області (замість файлу конфігурації репозиторію). Повний опис див. у <<OPTIONS,ПАРАМЕТРАХ>> вище.

Більшість параметрів конфігурації враховуються незалежно від області їх визначення, але деякі параметри враховуються лише в певних областях. Повні відомості дивіться в документації відповідного параметра.

Захищена конфігурація
~~~~~~~~~~~~~~~~~~~~~

Захищена конфігурація стосується областей дії 'system', 'global' та 'command' . З міркувань безпеки певні параметри враховуються лише тоді, коли вони вказані в захищеній конфігурації, та ігноруються в іншому випадку.

Git обробляє ці області дії так, ніби вони контролюються користувачем або довіреним адміністратором. Це пояснюється тим, що зловмисник, який контролює ці області дії, може завдати значної шкоди без використання Git, тому передбачається, що середовище користувача захищає ці області дії від зловмисників.

[[ENVIRONMENT]]
НАВКОЛИШНЄ СЕРЕДОВИЩЕ
---------------------

GIT_CONFIG_GLOBAL::
GIT_CONFIG_SYSTEM::
	Використовує налаштування з вказаних файлів замість глобальних налаштувань або налаштувань на рівні системи. Детальніше див. linkgit:git[1].

GIT_CONFIG_NOSYSTEM::
	Чи слід пропускати зчитування налаштувань із системного файлу $(prefix)/etc/gitconfig. Див. linkgit:git[1] для отримання детальної інформації.

Див. також <<FILES,ФАЙЛИ>>.

GIT_CONFIG_COUNT::
GIT_CONFIG_KEY_<n>::
GIT_CONFIG_VALUE_<n>::
	Якщо для GIT_CONFIG_COUNT встановлено додатне число, усі пари середовища GIT_CONFIG_KEY_<n> та GIT_CONFIG_VALUE_<n> до цього числа будуть додані до конфігурації середовища виконання процесу. Пари конфігурацій мають нульовий індекс. Будь-який відсутній ключ або значення обробляється як помилка. Порожній GIT_CONFIG_COUNT обробляється так само, як GIT_CONFIG_COUNT=0, тобто жодні пари не обробляються. Ці змінні середовища перевизначають значення у файлах конфігурації, але будуть перевизначені будь-якими явними опціями, переданими через `git -c`.
+
Це корисно у випадках, коли ви хочете створити кілька команд git зі спільною конфігурацією, але не можете покладатися на файл конфігурації, наприклад, під час написання скриптів.

GIT_CONFIG::
	Якщо для `git config` не надано опцію `--file`, використовується файл, наданий `GIT_CONFIG`, так, ніби його надано через `--file`. Ця змінна не впливає на інші команди Git і здебільшого призначена для історичної сумісності; зазвичай немає причин використовувати її замість опції `--file`.

[[EXAMPLES]]
ПРИКЛАДИ
--------

Враховуючи що .git/config виглядає подібним чином:

------------
#
# Це конфігураційний файл, і
# символ '#' або ';' вказує
# на коментар
#

; основні змінні
[core]
	; Не покладатися на атрибути файлів
	filemode = false

; Наш diff алгоритм
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

; Налаштування проксі-сервера
[core]
	gitproxy=proxy-command for kernel.org
	gitproxy=default-proxy ; for all the rest

; HTTP
[http]
	sslVerify
[http "https://weak.example.com"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
------------

ви можете встановити файловий режим на true за допомогою

------------
% git config set core.filemode true
------------

Гіпотетичні записи команд проксі насправді мають постфікс, щоб розрізняти, до якої URL-адреси вони застосовуються. Ось як змінити запис для kernel.org на "ssh".

------------
% git config set --value='for kernel.org$' core.gitproxy '"ssh" for kernel.org'
------------

Це гарантує, що замінюється лише пара ключ/значення для kernel.org.

Щоб видалити запис для перейменування, виконайте такі дії

------------
% git config unset diff.renames
------------

Якщо ви хочете видалити запис для багатозначного параметра (наприклад, core.gitproxy, як показано вище), вам потрібно вказати регулярний вираз, який відповідає значенню тільки одного рядка.

Щоб запитати значення для заданого ключа, виконайте такі дії

------------
% git config get core.filemode
------------

або, щоб запитати багатозначний параметр:

------------
% git config get --value="for kernel.org$" core.gitproxy
------------

Якщо ви хочете дізнатися всі значення для змінної з кількома значеннями, виконайте наступне:

------------
% git config get --all --show-names core.gitproxy
------------

Якщо ви любите жити небезпечно, ви можете замінити *весь* core.gitproxy на новий з

------------
% git config set --all core.gitproxy ssh
------------

Однак, якщо ви дійсно хочете замінити лише рядок для стандартного проксі-сервера, тобто той, що без постфікса "for ...", зробіть щось подібне:

------------
% git config set --value='! for ' core.gitproxy ssh
------------

Щоб фактично знайти лише значення зі знаком оклику, потрібно

------------
% git config set --value='[!]' section.key value
------------

Щоб додати новий проксі-сервер, не змінюючи жодного з наявних, використовуйте

------------
% git config set --append core.gitproxy '"proxy-command" для example.com'
------------

Приклад використання налаштованого кольору з конфігурації у вашому скрипті:

------------
#!/bin/sh
WS=$(git config get --type=color --default="blue reverse" color.diff.whitespace)
RESET=$(git config get --type=color --default="reset" "")
echo "${WS}your whitespace color or blue reverse${RESET}"
------------

Для URL-адрес у `https://weak.example.com`, `http.sslVerify` має значення false, тоді як для всіх інших URL-адрес має значення `true`:

------------
% git config get --type=bool --url=https://good.example.com http.sslverify
true
% git config get --type=bool --url=https://weak.example.com http.sslverify
false
% git config get --url=https://weak.example.com http
http.cookieFile /tmp/cookie.txt
http.sslverify false
------------

include::config.adoc[]

ПОМИЛКИ
-------
Під час використання застарілого синтаксису `[section.subsection]` зміна значення призведе до додавання багаторядкового ключа замість зміни, якщо підрозділ задано принаймні одним символом верхнього регістру. Наприклад, коли конфігурація виглядає так

--------
  [section.subsection]
    key = value1
--------

а запуск `git config section.Subsection.key value2` призведе до

--------
  [section.subsection]
    key = value1
    key = value2
--------


GIT
---
Частина набору linkgit:git[1]
