git-diff-tree(1)
================

НАЗВА
-----
git-diff-tree - Порівнює вміст та режим блобів, знайдених за допомогою двох об'єктів дерева


СИНОПСИС
--------
[verse]
'git diff-tree' [--stdin] [-m] [-s] [-v] [--no-commit-id] [--pretty]
	      [-t] [-r] [-c | --cc] [--combined-all-paths] [--root] [--merge-base]
	      [<common-diff-options>] <tree-ish> [<tree-ish>] [<path>...]

ОПИС
----
Порівняйте вміст та режим роботи блобів, знайдених за допомогою двох об'єктів дерева.

Якщо задано лише один <tree-ish>, коміт порівнюється з його батьківськими елементами (див. --stdin нижче).

Зверніть увагу, що 'git diff-tree' може використовувати дерево, інкапсульоване в об'єкті commit.

ОПЦІЇ
-----
include::diff-options.adoc[]

<tree-ish>::
	Ідентифікатор об'єкта дерева.

<path>...::
	Якщо надано, результати обмежуються підмножиною файлів, що відповідають одній із наданих специфікацій шляху.

-r::
	Рекурсія в піддерева.

-t::
	Показати сам запис дерева, а також його піддерева. Має на увазі -r.

--root::
	Коли вказано `--root`, початковий коміт буде показано як велика подія створення. Це еквівалентно різниці (diff) з NULL-деревом.

--merge-base::
	Замість безпосереднього порівняння <tree-ish>, використовуйте базу злиття між двома <tree-ish> як сторону "до". Повинно бути задано два <tree-ish>, і обидва вони повинні бути комітами.

--stdin::
	Коли вказано `--stdin`, команда не приймає аргументи типу <tree-ish> з командного рядка. Натомість вона зчитує рядки, що містять або два <tree>, один <commit>, або список <commit> зі стандартного вводу. (Використовуйте один пробіл як роздільник.)
+
Коли задано два дерева, програма порівнює перше дерево з другим. Коли задано один коміт, програма порівнює його з його батьківськими елементами. Решта комітів, якщо їх задано, використовуються так, ніби вони є батьками першого коміта.
+
Під час порівняння двох дерев, ідентифікатори обох дерев (розділені пробілом і завершуються новим рядком) виводяться перед різницею. Під час порівняння комітів виводиться ідентифікатор першого (або єдиного) коміта, а потім новий рядок.
+
Наведені нижче прапорці додатково впливають на поведінку під час порівняння комітів (але не дерев).

-m::
	За замовчуванням, 'git diff-tree --stdin' не показує відмінності для комітів злиття. З цим прапорцем, він показує відмінності цього коміта від усіх його батьківських комітів. Див. також `-c`.

-s::
	За замовчуванням, 'git diff-tree --stdin' показує відмінності або у машиночитабельному вигляді (без `-p`), або у вигляді патча (з `-p`). Цей вивід можна приховати. Він корисний лише з прапорцем `-v`.

-v::
	Цей прапорець змушує 'git diff-tree --stdin' також показувати повідомлення коміту перед відмінностями.

include::pretty-options.adoc[]

--no-commit-id::
	«git diff-tree» виводить рядок з ідентифікатором коміта, коли це можливо. Цей прапорець пригнічує вивід ідентифікатора коміта.

-c::
	Цей прапорець змінює спосіб відображення коміту злиття (що означає, що він корисний лише тоді, коли команді задано один <tree-ish> або `--stdin`). Він показує відмінності від кожного з батьківських об'єктів до результату злиття одночасно, замість того, щоб показувати попарні різниці між батьківським об'єктом та результатом по одному (що робить опція `-m`). Крім того, він відображає лише файли, які були змінені з усіх батьківських об'єктів.

--cc::
	Цей прапорець змінює спосіб відображення патча коміту злиття, подібно до опції `-c`. Він має на увазі опції `-c` та `-p` і додатково стискає вивід патча, пропускаючи нецікаві шматки, вміст яких у батьківських елементах має лише два варіанти, і результат злиття вибирає один з них без змін. Коли всі шматки нецікаві, сам коміт і повідомлення журналу коміту не відображаються, як і в будь-якому іншому випадку "порожньої різниці".

--combined-all-paths::
	Цей прапорець змушує об'єднані різниці (які використовуються для злиття комітів) виводити назви файлів з усіх батьківських файлів. Таким чином, він має ефект лише тоді, коли вказано -c або --cc, і, ймовірно, корисний лише тоді, коли виявлено зміни назв файлів (тобто, коли було запрошено перейменування або виявлення копіювання).

--always::
	Показати сам коміт та повідомлення журналу комітів, навіть якщо сам список різниці порожній.


include::pretty-formats.adoc[]

include::diff-format.adoc[]

GIT
---
Частина набору linkgit:git[1]
