git-bugreport(1)
================

НАЗВА
-----
git-bugreport — Збір інформації для користувача, щоб він міг подавати звіт про помилку

СИНОПСИС
--------
[verse]
'git bugreport' [(-o | --output-directory) <path>]
		[(-s | --suffix) <format> | --no-suffix]
		[--diagnose[=<mode>]]

ОПИС
----
Збирає інформацію про компʼютер користувача, клієнт Git та стан репозиторію, а також дані з форми, в якій запитується інформація про поведінку, яку спостерігав користувач, і зберігає її в одному текстовому файлі, який користувач може потім надіслати, наприклад, у список розсилки Git, щоб повідомити про виявлену помилку.

У користувача запитується наступна інформація:

 - Кроки для відтворення дій
 - Очікувана поведінка
 - Фактична поведінка

Наступна інформація отримується автоматично:

 - 'git version --build-options'
 - uname рядки sysname, release, version та machine
 - Специфічний для компілятора інформаційний рядок
 - Список увімкнених гачків
 - $SHELL

Додаткову інформацію можна зібрати в окремий zip-архів за допомогою опції `--diagnose`, а також додати до документа зі звітом про помилку, щоб надати читачам додатковий контекст.

Цей інструмент викликається через типовий процес налаштування Git, а це означає, що в деяких випадках він може не запуститися, наприклад, якщо відповідний файл конфігурації нечитабельний. У такому випадку може бути корисним вручну зібрати перелічену вище інформацію, коли ви звертаєтесь за допомогою.

ОПЦІЇ
-----
-o <path>::
--output-directory <path>::
	Помістіть отриманий файл звіту про помилку в `<шлях>` замість поточної теки.

-s <format>::
--suffix <format>::
--no-suffix::
	Вкажіть альтернативний суфікс для назви звіту про помилку, щоб створити файл з назвою 'git-bugreport-<formatted-suffix>'. Він має мати форму рядка формату strftime(3); буде використано поточний місцевий час. `--no-suffix` вимикає суфікс, і файл буде називатися просто `git-bugreport` без будь-яких заходів узгодження.

--no-diagnose::
--diagnose[=<mode>]::
	Створіть zip-архів додаткової інформації про компʼютер користувача, клієнт Git та стан репозиторію. Архів записується в ту саму теку, що й звіт про помилку, і має назву 'git-diagnostics-<форматований-суфікс>'.
+
Якщо параметр `mode` не вказано, діагностичний архів міститиме стандартний набір статистичних даних, що надаються командою `git diagnose`. Можна вказати опціональне значення параметра `mode`, щоб змінити склад інформації, що включається до архіву. Перелік допустимих значень параметра `mode` та детальну інформацію про їх використання див. на сторінці linkgit:git-diagnose[1].

GIT
---
Частина набору linkgit:git[1]
