git-merge(1)
============

НАЗВА
-----
git-merge — Обʼєднання двох або більше гілок розробки


СИНОПСИС
--------
[synopsis]
git merge [-n] [--stat] [--compact-summary] [--no-commit] [--squash] [--[no-]edit]
	[--no-verify] [-s <strategy>] [-X <strategy-option>] [-S[<keyid>]]
	[--[no-]allow-unrelated-histories]
	[--[no-]rerere-autoupdate] [-m <msg>] [-F <file>]
	[--into-name <branch>] [<commit>...]
git merge (--continue | --abort | --quit)

ОПИС
----
Включає зміни з вказаних комітів (починаючи з моменту, коли їхні історії розійшлися з поточною гілкою) у поточну гілку. Ця команда використовується командою `git pull` для включення змін з іншого репозиторію, а також може використовуватися вручну для злиття змін з однієї гілки в іншу.

Припустимо, що існує наступна історія, а поточною гілкою є `master`:

------------
          A---B---C topic
         /
    D---E---F---G master
------------

Тоді команда `git merge topic` застосує зміни, внесені у гілці `topic` з моменту її відгалуження від `master` (тобто від `E`) до її поточного коміту (`C`) поверх гілки `master`, і збереже результат у новому коміті разом з іменами двох батьківських комітів та повідомленням у журналі від користувача, що описує зміни. Перед операцією `ORIG_HEAD` встановлюється на кінцеву точку поточної гілки (`G`).

------------
          A---B---C topic
         /         \
    D---E---F---G---H master
------------

Злиття зупиняється, якщо виникає конфлікт, який неможливо вирішити автоматично, або якщо під час ініціювання злиття було вказано параметр `--no-commit`. У цей момент ви можете виконати `git merge --abort` або `git merge --continue`.

Команда `git merge --abort` перерве процес злиття та спробує відновити стан, що існував до злиття. Однак, якщо на момент початку злиття були незбережені зміни (а особливо якщо ці зміни були додатково змінені після початку злиття), команда `git merge --abort` у деяких випадках не зможе відновити початкові (до злиття) зміни. Тому:

WARNING: Не рекомендується виконувати команду `git merge`, якщо є значні зміни, що не зафіксовані: хоча це й можливо, у разі конфлікту ви можете опинитися в ситуації, з якої важко буде вийти.

ОПЦІЇ
-----
:git-merge: 1

include::merge-options.adoc[]

`-m <msg>`::
	Встановлює повідомлення коміту, яке буде використовуватися для коміту злиття (якщо такий буде створено).
+
Якщо вказано `--log`, до вказаного повідомлення буде додано короткий журнал комітів, що обʼєднуються.
+
Команду `git fmt-merge-msg` можна використовувати для встановлення якісного стандартного повідомлення для автоматичних викликів `git merge`. Автоматизоване повідомлення може містити опис гілки.

`--into-name <branch>`::
	Створює стандартне повідомлення про злиття так, ніби злиття відбувається у гілку _<branch>_, замість назви тієї гілки, до якої насправді відбувається злиття.

`-F <файл>`::
`--file=<файл>`::
	Отримати повідомлення коміту, яке буде використано для коміту злиття (якщо такий буде створено).
+
Якщо вказано `--log`, до вказаного повідомлення буде додано короткий журнал комітів, що обʼєднуються.

include::rerere-options.adoc[]

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	Перезаписувати ігноровані файли в результаті злиття без попередження. Це стандартна поведінка. Для скасування використовуйте опцію `--no-overwrite-ignore`.

`--abort`::
	Перервати поточний процес розвʼязання конфліктів та спробувати відновити стан який був до початку процесу обʼєднання. Якщо запис autostash присутній, застосувати його до робочого дерева.
+
Якщо на початку злиття були присутні незафіксовані зміни в робочому дереві, `git merge --abort` у деяких випадках не зможе їх реконструювати. Тому рекомендується завжди зафіксувати або зберегти зміни перед запуском `git merge`.
+
`git merge --abort` є еквівалентом `git reset --merge`, коли присутній `MERGE_HEAD`, окрім випадків, коли також присутній `MERGE_AUTOSTASH`, у цьому випадку `git merge --abort` застосовує запис stash до робочого дерева, тоді як `git reset --merge` збереже збережені зміни у списку stash.

`--quit`::
	Ігнорувати поточне злиття. Залишити індекс та робоче дерево без змін. Якщо встановлено параметр `MERGE_AUTOSTASH`, запис stash буде збережено у списку stash.

`--continue`::
	Якщо команда `git merge` зупинилася через конфлікти, ви можете завершити злиття, виконавши команду `git merge --continue` (див. розділ «ЯК РОЗВʼЯЗУВАТИ КОНФЛІКТИ» нижче).

`<commit>...`::
	Коміти, це зазвичай вершини інших гілок, які потрібно обʼєднати з нашою гілкою. Якщо вказати більше одного коміту, буде створено злиття з більш ніж двома батьківськими комітами (яке жартома називають «злиттям Восьминога», Octopus merge).
+
Якщо в командному рядку не вказано жодного коміту, слід обʼєднати гілки віддаленого відстеження, які поточна гілка налаштована використовувати як своє джерело (upstream). Див. також розділ про налаштування на цій сторінці довідки.
+
Якщо вказано `FETCH_HEAD` (і жодного іншого коміту), гілки, записані у файлі `.git/FETCH_HEAD` під час попереднього виконання команди `git fetch` для злиття, зливаються з поточною гілкою.


ПЕРЕВІРКИ ПЕРЕД ЗЛИТТЯМ
-----------------------

Перш ніж застосовувати зовнішні зміни, слід привести власні зміни до ладу та зберегти їх локально, щоб у разі конфліктів вони не були загублені. Див. також linkgit:git-stash[1]. Команди `git pull` та `git merge` зупиняться, не виконавши жодних дій, якщо локальні незбережені зміни перекриваються з файлами, які `git pull`/`git merge` можуть оновлювати.

Щоб уникнути запису змін, що не стосуються злиття, команди `git pull` та `git merge` також припинять роботу, якщо в індексі зареєстровані будь-які зміни порівняно з комітом `HEAD`. (Залежно від використовуваної стратегії злиття можуть існувати окремі винятки з цього правила, але загалом індекс повинен збігатися з `HEAD`.)

Якщо всі вказані коміти вже є попередниками `HEAD`, команда `git merge` завершиться достроково з повідомленням «Already up to date» («Вже оновлено»).

ЗЛИТТЯ FAST-FORWARD
-------------------

Часто вершина поточної гілки є пращуром вказаного коміту. Це найпоширеніший випадок, особливо при виконанні команди `git pull`: ви відстежуєте репозиторій-джерело, не зафіксували жодних локальних змін і тепер хочете оновити репозиторій до нової версії з джерела. У цьому випадку для збереження обʼєднаної історії не потрібен новий коміт; натомість `HEAD` (разом з індексом) оновлюється, щоб вказувати на вказаний коміт, без створення додаткового коміту злиття.

Цю поведінку можна придушити за допомогою опції `--no-ff`.

СПРАВЖНЄ ЗЛИТТЯ
---------------

За винятком випадків злиття fast-forward (див. вище), гілки, що обʼєднуються, повинні бути повʼязані між собою комітом злиття, в якому обидві гілки є його батьками.

Обʼєднана версія, що враховує зміни з усіх гілок, які потрібно об’єднати, фіксується, а ваш `HEAD`, індекс та робоче дерево оновлюються відповідно до неї. У робочому дереві можуть бути зміни, якщо вони не перетинаються; під час оновлення вони будуть збережені.

Якщо не зрозуміло, як узгодити зміни, відбувається наступне:

1. Вказівник `HEAD` залишається незмінним.
2. Посилання `MERGE_HEAD` налаштовується так, щоб вказувати на вершину іншої гілки.
3. Шляхи, які були успішно об’єднані, оновлюються як у файлі індексу, так і у вашому робочому дереві.
4. У разі конфлікту шляхів індексний файл фіксує до трьох версій: у stage 1 зберігається версія від спільного предка, у stagе 2 — від `HEAD`, а у stage 3 — від `MERGE_HEAD` (переглянути stage можна за допомогою команди `git ls-files -u`). Файли робочого дерева містять результат операції злиття, тобто результати тристороннього злиття зі знайомими маркерами конфлікту +<<<+ `===` +>>>+.
5. Створюється посилання з іменем `AUTO_MERGE`, яке вказує на дерево, що відповідає поточному вмісту робочого дерева (включно з маркерами конфліктів для текстових конфліктів). Зверніть увагу, що це посилання створюється лише у разі використання стратегії злиття `ort` (зазвичай).
6. Жодних інших змін не вноситься. Зокрема, локальні зміни, які ви мали до початку злиття, залишаться незмінними, а записи індексу для них залишаться такими, якими вони були, тобто збігатимуться з `HEAD`.

Якщо ви спробували злиття, яке призвело до складних конфліктів, і хочете почати спочатку, ви можете відновити його за допомогою `git merge --abort`.

ОБʼЄДНАННЯ ТЕГА
---------------

Під час злиття тегу з анотацією (і, можливо, з підписом) Git завжди створює коміт злиття, навіть якщо можливе злиття методом «fast-forward», а шаблон повідомлення про коміт заповнюється текстом тегу. Крім того, якщо тег підписано, результат перевірки підпису відображається у вигляді коментаря в шаблоні повідомлення. Див. також linkgit:git-tag[1].

Якщо ви хочете просто інтегрувати зміни, що передують коміту, який випадково має тег, наприклад, для синхронізації з версією випуску upstream, вам, можливо, не варто створювати зайвий коміт злиття.

У такому випадку ви можете самостійно «розгорнути» тег перед тим, як передати його команді `git merge`, або вказати параметр `--ff-only`, якщо у вас немає власних змін. Наприклад:

----
git fetch origin
git merge v1.2.3^0
git merge --ff-only v1.2.3
----

ЯК ПОДАЮТЬСЯ КОНФЛІКТИ
----------------------

Під час злиття файли робочого дерева оновлюються, щоб відобразити результат злиття. Серед змін, внесених до версії спільного предка, ті, що не перекриваються (тобто ви змінили частину файлу, тоді як інша сторона залишила цю частину без змін, або навпаки), включаються до кінцевого результату дослівно. Однак, коли обидві сторони внесли зміни до однієї й тієї ж частини, Git не може довільно вибрати одну сторону замість іншої і просить вас виправити ситуацію, лишивши те, що обидві сторони зробили з цією частиною.

Зазвичай Git використовує той самий стиль, що й програма «merge» з набору RCS, для відображення такого фрагмента з конфліктом, наприклад:

------------
Ось рядки, які або залишилися без змін порівняно зі спільним
предком, або розвʼязані без конфліктів, оскільки змінилася лише одна сторона,
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
<<<<<<< ваш:sample.txt
Розвʼязання конфліктів — це складно;
Ходімо на закупи.
=======
Git спрощує розв’язання конфліктів.
>>>>>>> їхній:sample.txt
А ось ще один рядок, який розв’язано без конфліктів або який залишився без змін.
------------

Місце, де відбулася пара суперечливих змін, позначено маркерами +<<<<<<<+, `=======` та +>>>>>>>+. Частина перед `=======` зазвичай належить вам, а частина після — іншій стороні.

У стандартному форматі не показується, що саме було написано в оригінальному тексті у місці, де виникли розбіжності. Неможливо визначити, скільки рядків було видалено та замінено коментарем Барбі у вашій частині тексту. Єдине, що можна зрозуміти, — це те, що у вашій частині йдеться про те, що це складно і ви б воліли піти на закупи, тоді як у частині опонента стверджується, що це легко.

Альтернативний стиль можна використовувати, встановивши змінну конфігурації `merge.conflictStyle` на `diff3` або `zdiff3`. У стилі `diff3` вищезгаданий конфлікт може виглядати так:

------------
Ось рядки, які або залишилися без змін порівняно зі спільним
предком, або розвʼязані без конфліктів, оскільки змінилася лише одна сторона,
<<<<<<< ваш:sample.txt
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
Розвʼязання конфліктів — це складно;
Ходімо на закупи.
||||||| базовий:sample.txt
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
Розвʼязання конфліктів — це складно.
=======
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
Git спрощує вирішення конфліктів.
>>>>>>> їхній:sample.txt
А ось ще один рядок, який розв’язано без конфліктів або який залишився без змін.
------------

в той час як в `zdiff3` це може виглядати так:

------------
Ось рядки, які або залишилися без змін порівняно зі спільним
предком, або розвʼязані без конфліктів, оскільки змінилася лише одна сторона,
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
<<<<<<< ваш:sample.txt
Розвʼязання конфліктів — це складно;
Ходімо на закупи.
||||||| base:sample.txt
або розвʼязані без конфліктів, оскільки обидві сторони змінилися однаково.
Розвʼязання конфліктів — це складно.
=======
Git спрощує вирішення конфліктів.
>>>>>>> їхній:sample.txt
А ось ще один рядок, який розв’язано без конфліктів або який залишився без змін.
------------

Окрім маркерів +<<<<<<<+, `=======` та +>>>>>>>+, тут використовується ще один маркер +|||||||+, за яким йде оригінальний текст. З цього можна зрозуміти, що в оригіналі йшлося про констатацію факту, і ваша сторона просто погодилася з цим твердженням та поступилася, тоді як інша сторона намагалася зайняти більш позитивну позицію. Іноді, переглянувши оригінал, можна знайти краще рішення.


ЯК РОЗВʼЯЗУВАТИ КОНФЛІКТИ
-------------------------

Після виявлення конфлікту ви можете зробити дві речі:

 * Відмовитися від злиття. Єдине, що потрібно зробити для прибирання, — це скинути файл індексу до коміту `HEAD`, щоб скасувати stage 2, та прибрати зміни у робочому дереві, внесені stage 2 і 3; для цього можна використати команду `git merge --abort`.

 * Розвʼязати конфлікти. Git позначить конфлікти у робочому дереві. Відредагуйте файли та додайте їх до індексу за допомогою команди `git add`. Використовуйте `git commit` або `git merge --continue`, щоб завершити операцію. Остання команда перевіряє, чи триває (перерване) злиття, перш ніж запускати `git commit`.

Ви можете розвʼязати конфлікт за допомогою різних інструментів:

 * Використайте mergetool. `git mergetool` запускає графічний інтерфейс mergetool, який допоможе вам виконати злиття.

 * Перегляньте diff. Команда `git diff` покаже тристоронню різницю, виділивши зміни як у версії `HEAD`, так і в версії `MERGE_HEAD`. Команда `git diff AUTO_MERGE` покаже, які зміни ви внесли до цього моменту для вирішення текстових конфліктів.

 * Перегляньте відмінності з кожної гілки. `git log --merge -p <шлях>` спочатку покаже відмінності для версії `HEAD`, а потім для версії `MERGE_HEAD`.

 * Подивіться на оригінали. `git show :1:filename` показує спільного предка, `git show :2:filename` показує версію `HEAD`, а `git show :3:filename` показує версію `MERGE_HEAD`.


ПРИКЛАДИ
--------

* Злиття гілок `fixes` та `enhancements ` у поточну гілку, шляхом використання стратегії злиття "octopus":
+
------------------------------------------------
$ git merge fixes enhancements
------------------------------------------------

* Злиття гілки `obsolete` у поточну гілку, використовуючи стратегію злиття `ours`:
+
------------------------------------------------
$ git merge -s ours obsolete
------------------------------------------------

* Злиття гілки `maint` з поточною гілкою, але без автоматичного створення нового коміту:
+
------------------------------------------------
$ git merge --no-commit maint
------------------------------------------------
+
Це можна використовувати, коли ви хочете включити подальші зміни до злиття або хочете написати власне повідомлення коміту злиття.
+
Не слід зловживати цією опцією, щоб непомітно внести суттєві зміни в коміт злиття. Невеликі виправлення, такі як підвищення номера версії, є прийнятними.


include::merge-strategies.adoc[]

КОНФІГУРАЦІЯ
------------

`branch.<name>.mergeOptions`::
	Встановлює стандартні параметри для злиття у гілку _<назва>_. Синтаксис та підтримувані параметри такі ж, як і у `git merge`, але значення параметрів, що містять пробіли, наразі не підтримуються.

include::includes/cmd-config-section-rest.adoc[]

include::config/merge.adoc[]

ДИВ. ТАКОЖ
----------
linkgit:git-fmt-merge-msg[1], linkgit:git-pull[1], linkgit:gitattributes[5], linkgit:git-reset[1], linkgit:git-diff[1], linkgit:git-ls-files[1], linkgit:git-add[1], linkgit:git-rm[1], linkgit:git-mergetool[1]

GIT
---
Частина набору linkgit:git[1]
