git-cvsexportcommit(1)
======================

НАЗВА
-----
git-cvsexportcommit - Експорт одного коміту до CVS checkout


СИНОПСИС
--------
[verse]
'git cvsexportcommit' [-h] [-u] [-v] [-c] [-P] [-p] [-a] [-d <cvsroot>]
	[-w <cvs-workdir>] [-W] [-f] [-m <msgprefix>] [<parent-commit>] <commit-id>


ОПИС
----
Експортує коміт з Git до CVS-реконструкції, що спрощує об'єднання патчів з репозиторію Git до репозиторію CVS.

Вкажіть назву збірки CVS за допомогою параметра -w або виконайте її з кореневого каталогу робочої копії CVS. В останньому випадку необхідно визначити GIT_DIR. Дивіться приклади нижче.

Він робить усе можливе, щоб зробити це безпечно, перевіряє, чи файли незмінні та актуальні під час перевірки CVS, і не виконує автоматичне фіксування змін за замовчуванням.

Підтримує додавання, видалення та коміти файлів, що впливають на бінарні файли.

Якщо коміт є комітом злиття, ви повинні вказати 'git cvsexportcommit', для якого батьківського об'єкта слід застосувати набір змін.

ОПЦІЇ
-----

-c::
	Автоматично зафіксувати, якщо патч застосувався коректно. Зафіксувати не вдасться, якщо якісь фрагменти не застосувалися або виникли інші проблеми.

-p::
	Будьте педантичними (параноїдальними) під час застосування патчів. Викликає патч з --fuzz=0

-a::
	Додати інформацію про авторство. Додає рядок автора та комітер (якщо відрізняється від автора) до повідомлення.

-d::
	Встановіть альтернативний CVSROOT для використання. Це відповідає параметру CVS -d. Зазвичай користувачі не хочуть встановлювати це, окрім випадків використання CVS асиметричним чином.

-f::
	Примусово виконати об'єднання, навіть якщо файли застарілі.

-P::
	Примусово виконати батьківський коміт, навіть якщо він не є прямим батьком.

-m::
	Додайте наданий префікс перед повідомленням коміту. Корисно для серій патчів тощо.

-u::
	Оновіть уражені файли з репозиторію CVS перед спробою експорту.

-k::
	Зворотне розширення ключових слів CVS (наприклад, $Revision: 1.2.3.4$ стає $Revision$) у робочому CVS checkout перед застосуванням патчу.

-w::
	Вкажіть розташування збірки CVS, яку потрібно використовувати для експорту. Цей параметр не вимагає встановлення GIT_DIR перед виконанням, якщо поточний каталог знаходиться в репозиторії Git. Значення за замовчуванням — «cvsexportcommit.cvsdir».

-W::
	Повідомте cvsexportcommit, що поточний робочий каталог є не лише каталогом здачі Git, але й каталогом здачі CVS. Таким чином, Git скине робочий каталог до батьківського коміту, перш ніж продовжити.

-v::
	Багатослівний.

КОНФІГУРАЦІЯ
------------
cvsexportcommit.cvsdir::
	Розташування за замовчуванням для видачі CVS, яке використовуватиметься для експорту.

ПРИКЛАДИ
--------

Об'єднати один патч у CVS::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cvsexportcommit -v <commit-sha1>
$ cvs commit -F .msg <files>
------------

Об'єднати один патч у CVS (опції -c та -w). Робочий каталог знаходиться в Git Repo::
+
------------
	$ git cvsexportcommit -v -c -w ~/project_cvs_checkout <commit-sha1>
------------

Автоматично об'єднуйте очікуючі на розгляд патчі в CVS -- лише якщо ви дійсно знаєте, що робите::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cherry cvshead myhead | sed -n 's/^+ //p' | xargs -l1 git cvsexportcommit -c -p -v
------------

GIT
---
Частина набору linkgit:git[1]
