git-fetch-pack(1)
=================

НАЗВА
-----
git-fetch-pack  — Отримання відсутніх обʼєктів з іншого репозиторію


СИНОПСИС
--------
[verse]
'git fetch-pack' [--all] [--quiet|-q] [--keep|-k] [--thin] [--include-tag]
	[--upload-pack=<git-upload-pack>]
	[--depth=<n>] [--no-progress]
	[-v] <repository> [<refs>...]

ОПИС
----
Зазвичай вам варто використовувати 'git fetch', що є обгорткою вищого рівня для цієї команди.

Викликає 'git-upload-pack' на можливо віддаленому репозиторії та запитує його надіслати обʼєкти, відсутні в цьому репозиторії, для оновлення іменованих заголовків. Список комітів, доступних локально, виявляється шляхом сканування локальної ієрархії refs/ та надсилається до 'git-upload-pack', що працює на іншому кінці.

Ця команда зводиться до завантаження всіх даних, необхідних для завершення запитуваних посилань з віддаленого сервера, якщо на локальному сервері відсутній спільний попередній коміт.


ОПЦІЇ
-----
--all::
	Отримати всі віддалені посилання.

--stdin::
	Взяти список посилань зі stdin, по одному на рядок. Якщо в командному рядку, окрім цього параметра, є посилання, вказані в stdin, тоді посилання зі stdin обробляються після тих, що в командному рядку.
+
Якщо разом із цією опцією вказано `--stateless-rpc`, то список посилань має бути у форматі пакунка (pkt-line). Кожне посилання має бути в окремому пакунку, а список має закінчуватися пакунком flush.

-q::
--quiet::
	Передайте прапорець `-q` команді 'git unpack-objects'; це дозволить зменшити кількість повідомлень під час клонування.

-k::
--keep::
	Не викликати 'git unpack-objects' для отриманих даних, а створити з них окремий файл packfile та зберегти його в базі даних обʼєктів. Якщо параметр вказано двічі, то перепакування блокується.

--thin::
	Отримати "тонкий" пакунок, який записує обʼєкти у дельта-вигляді на основі обʼєктів, що не входять до пакунку, для зменшення мережевого трафіку.

--include-tag::
	Якщо віддалена сторона підтримує це, обʼєкти з анотаціями тегів будуть завантажені через те саме зʼєднання, що й інші обʼєкти, якщо завантажено обʼєкт, на який посилається тег. В іншому випадку, викликаюча сторона повинна визначити теги, які ця опція зробила доступними.

--upload-pack=<git-upload-pack>::
	Використовуйте це, щоб вказати шлях до 'git-upload-pack' на віддаленому сервері, якщо його не знайдено у вашому $PATH. Інсталяції sshd ігнорують скрипти налаштування середовища користувача для оболонок входу (наприклад, .bash_profile), і ваш особисто встановлений git може бути відсутнім у системному $PATH. Іншим запропонованим обхідним рішенням є налаштування вашого $PATH у файлі «.bashrc», але цей прапорець призначений для тих, хто не хоче нести додаткові витрати на неінтерактивні оболонки, маючи компактний файл .bashrc (вони налаштовують більшість речей у файлі .bash_profile).

--exec=<git-upload-pack>::
	Те саме, що --upload-pack=<git-upload-pack>.

--depth=<n>::
	Обмежити вибірку ланцюжками предків довжиною не більше n. 'git-upload-pack' трактує спеціальну глибину 2147483647 як нескінченну, навіть якщо існує ланцюжок предків такої довжини.

--shallow-since=<дата>::
	Поглибити або скоротити історію поверхневого репозиторію, щоб включити всі доступні коміти після <дати>.

--shallow-exclude=<посилання>::
	Поглибити або скоротити історію поверхневого репозиторію, щоб виключити коміти, доступні з вказаної віддаленої гілки або тегу. Цей параметр можна вказати кілька разів.

--deepen-relative::
	Аргумент --depth визначає кількість комітів з поточної поверхневої межі, а не з кінця історії кожної віддаленої гілки.

--refetch::
	Пропускає узгодження комітів із сервером для отримання всіх відповідних обʼєктів. Використовується для повторного застосування нового фільтра часткового клонування блобів/дерева.

--no-progress::
	Не показувати прогрес.

--check-self-contained-and-connected::
	Вивести повідомлення «connectivity-ok», якщо отриманий пакунок є самодостатнім і підключеним.

-v::
	Надавати повний (verbose) вивід.

<repository>::
	URL-адреса віддаленого репозиторію.

<refs>...::
	Віддалені вершини, з яких потрібно оновлювати. Це значення залежить від $GIT_DIR (наприклад, "HEAD", "refs/heads/master"). Якщо не вказано, оновлювати з усіх вершин, що є на віддаленій стороні.
+
Якщо у віддаленому репозиторії увімкнено опції `uploadpack.allowTipSHA1InWant`, `uploadpack.allowReachableSHA1InWant` або `uploadpack.allowAnySHA1InWant`, вони можуть бути як 40-шістнадцяткові sha1, присутні у віддаленому репозиторії.

ДИВ. ТАКОЖ
----------
linkgit:git-fetch[1]

GIT
---
Частина набору linkgit:git[1]
