git-request-pull(1)
===================

НАЗВА
-----
git-request-pull — Створення звіту про очікувані зміни

СИНОПСИС
--------
[verse]
'git request-pull' [-p] <start> <URL> [<end>]

ОПИС
----

Створює запит, у якому попросіть ваш upstream-проєкт завантажити зміни у своє дерево. Цей запит, що виводиться у стандартний вивід, починається з опису гілки, містить короткий опис змін та вказує, звідки їх можна завантажити.

Очікується, що upstream проєкт матиме коміт з назвою `<start>`, а вивід просить його інтегрувати зміни, внесені з моменту цього коміту, аж до коміту з назвою `<end>`, відвідавши репозиторій з назвою `<URL>`.


ОПЦІЇ
-----
-p::
	Включити текст латки у вивід.

<start>::
	Коміт, з якого потрібно почати. Це імʼя коміту, який вже є в історії upstream.

<URL>::
	URL-адреса репозиторію, з якого буде витягнуто дані.

<end>::
	Завершальний коміт (зазвичай HEAD). Вказує імʼя коміту на кінці історії, яку ви хочете завантажити.
+
Коли репозиторій з назвою `<URL>` має коміт у вершині посилання, яке відрізняється від локального посилання, ви можете використовувати синтаксис `<local>:<remote>`, щоб отримати його локальну назву, двокрапку `:` та його віддалену назву.


ПРИКЛАДИ
--------

Уявіть, що ви зібрали свою роботу в гілці `master` поверх релізу `v1.0` і хочете інтегрувати її в проєкт. Спочатку ви надсилаєте цю зміну до свого публічного репозиторію, щоб інші могли її побачити:

	git push https://git.ko.xz/project master

Потім ви виконуєте цю команду:

	git request-pull v1.0 https://git.ko.xz/project master

що призведе до створення запиту до сервера, у якому буде зроблено підсумок змін між версією `v1.0` та вашим `master`, щоб завантажити її з вашого публічного репозиторію.

Якщо ви надіслали зміни до гілки, назва якої відрізняється від тієї, що у вас локально, наприклад.

	git push https://git.ko.xz/project master:for-linus

тоді ви можете попросити, щоб це витягнули

	git request-pull v1.0 https://git.ko.xz/project master:for-linus


GIT
---
Частина набору linkgit:git[1]
