git-http-fetch(1)
=================

НАЗВА
-----
git-http-fetch - Завантаження з віддаленого репозиторію Git через HTTP


СИНОПСИС
--------
[verse]
'git http-fetch' [-c] [-t] [-a] [-d] [-v] [-w <filename>] [--recover] [--stdin | --packfile=<hash> | <commit>] <URL>

ОПИС
----
Завантажує віддалений репозиторій Git через HTTP.

Ця команда завжди отримує всі об'єкти. Історично існувало три опції `-a`, `-c` та `-t` для вибору об'єктів для завантаження. Зараз вони мовчки ігноруються.

ОПЦІЇ
-----
commit-id::
        Або хеш, або ім'я файлу в [URL]/refs/ для вилучення.

-a, -c, -t::
	Ці опції ігноруються з історичних причин.
-v::
	Повідомити про завантаження.

-w <filename>::
Записує commit-id у вказаний файл у $GIT_DIR/refs/<ім'я_файлу> на локальному кінці після завершення передачі.

--stdin::
	Замість ідентифікатора коміта в командному рядку (що в цьому випадку не очікується), 'git http-fetch' очікує рядки на stdin у форматі

		<commit-id>['\t'<filename-as-in--w>]

--packfile=<hash>::
	Тільки для внутрішнього використання. Замість ідентифікатора коміта в командному рядку (що в цьому випадку не очікується), 'git http-fetch' отримує packfile безпосередньо за вказаною URL-адресою та використовує index-pack для генерації відповідних файлів .idx та .keep. Хеш використовується для визначення назви тимчасового файлу та є довільним. Вивід index-pack виводиться на stdout. Потрібно --index-pack-args.

--index-pack-args=<args>::
	Тільки для внутрішнього використання. Команда для виконання з вмістом завантаженого пакета. Аргументи закодовані за URL-адресою та розділені пробілами.

--recover::
	Перевіряє, чи отримано все, що доступно з цілі. Використовується після переривання попередньої вибірки.

GIT
---
Частина набору linkgit:git[1]
