git-format-patch(1)
===================

НАЗВА
-----
git-format-patch —Підготовка латок для надсилання електронною поштою


СИНОПСИС
--------
[verse]
'git format-patch' [-k] [(-o|--output-directory) <dir> | --stdout]
		   [--no-thread | --thread[=<style>]]
		   [(--attach|--inline)[=<boundary>] | --no-attach]
		   [-s | --signoff]
		   [--signature=<signature> | --no-signature]
		   [--signature-file=<file>]
		   [-n | --numbered | -N | --no-numbered]
		   [--start-number <n>] [--numbered-files]
		   [--in-reply-to=<message-id>] [--suffix=.<sfx>]
		   [--ignore-if-in-upstream] [--always]
		   [--cover-from-description=<mode>]
		   [--rfc[=<rfc>]] [--subject-prefix=<subject-prefix>]
		   [(--reroll-count|-v) <n>]
		   [--to=<email>] [--cc=<email>]
		   [--[no-]cover-letter] [--quiet]
		   [--[no-]encode-email-headers]
		   [--no-notes | --notes[=<ref>]]
		   [--interdiff=<previous>]
		   [--range-diff=<previous> [--creation-factor=<percent>]]
		   [--filename-max-length=<n>]
		   [--progress]
		   [<common-diff-options>]
		   [ <since> | <revision-range> ]

ОПИС
----

Підготуйте кожен коміт, що не входить до злиття, разом із його «латкою» у вигляді одного «повідомлення» на кожен коміт, відформатованого так, щоб він нагадував поштову скриньку UNIX. Результат виконання цієї команди зручно використовувати для надсилання електронною поштою або для роботи з командою 'git am'.

«Повідомлення», згенероване командою, складається з трьох частин:

* Короткий заголовок метаданих, що починається з `From <commit>` з фіксованою міткою дати `Mon Sep 17 00:00:00 2001`, щоб допомогти програмам, таким як "file(1)", розпізнати, що файл є виводом цієї команди, поля, що записують ідентифікацію автора, дату авторства та назву зміни (взято з першого абзацу повідомлення журналу комітів).

* Другий та наступні абзаци повідомлення журналу комітів.

* «Латка», що є виводом «diff -p --stat» (див. linkgit:git-diff[1]) між комітом та його батьківським комітом.

Повідомлення журналу та латка розділені лінією з трьома дефісами.

Існує два способи вказати, з якими комітами працювати.

1. Один коміт <since> вказує, що будуть виведені коміти, що ведуть до вершини поточної гілки, яких немає в історії, що призводить до <since>.

2. Загальний вираз <revision-range> (див. розділ "ВИЗНАЧЕННЯ РЕВІЗІЙ" у linkgit:gitrevisions[7]) означає коміти у вказаному діапазоні.

Перше правило має пріоритет у випадку одного <commit>. Щоб застосувати друге правило, тобто відформатувати все з початку історії до <commit>, використовуйте опцію `--root`: `git format-patch --root <commit>`. Якщо ви хочете відформатувати лише сам <commit>, ви можете зробити це за допомогою `git format-patch -1 <commit>`.

Зазвичай кожен вихідний файл нумерується послідовно, починаючи з 1, як імʼя файлу використовується перший рядок повідомлення коміту (змінений для безпеки шляхів). З опцією `--numbered-files` імена вихідних файлів будуть лише числами, без додавання першого рядка коміту. Імена вихідних файлів виводяться в стандартний вивід, якщо не вказано опцію `--stdout`.

Якщо вказано `-o`, вихідні файли створюються в <dir>. В іншому випадку вони створюються в поточній робочій теці. Стандартний шлях можна встановити за допомогою параметра конфігурації `format.outputDirectory`. Параметр `-o` має пріоритет над `format.outputDirectory`. Щоб зберігати латку в поточній робочій теці, навіть якщо `format.outputDirectory` вказує на інше місце, використовуйте `-o`. Будуть створені всі компоненти теки.

Стандартно темою кожної окремої латки є «[PATCH] », за якою йде послідовність рядків із повідомлення про коміт аж до першого порожнього рядка (див. розділ ОБГОВОРЕННЯ на сторінці linkgit:git-commit[1]).

Коли виводиться кілька латок, префікс теми буде "[PATCH n/m]". Щоб примусово додати 1/1 для однієї латки, використовуйте `-n`. Щоб виключити кілька латок з теми, використовуйте `-N`.

Якщо вказано `--thread`, `git-format-patch` генеруватиме заголовки `In-Reply-To` та `References`, щоб другий та наступні листи з латкою показувались як відповіді на перший лист; це також генеруватиме заголовок `Message-ID` для посилання.

ОПЦІЇ
-----
:git-format-patch: 1
include::diff-options.adoc[]

-<n>::
	Підготувати латки з найвищих <n> комітів.

-o <dir>::
--output-directory <dir>::
	Використовувати <dir> для зберігання отриманих файлів замість поточної робочої теки.

-n::
--numbered::
	Назва виводу у форматі '[PATCH n/m]', навіть якщо це одна латка.

-N::
--no-numbered::
	Назва виводу в форматі '[PATCH]'.

--start-number <n>::
	Починати нумерацію латок з <n> замість 1.

--numbered-files::
	Імена вихідних файлів будуть простою числовою послідовністю без додавання першого стандартного рядка коміту.

-k::
--keep-subject::
	Не видаляти/додавати '[PATCH]' з першого рядка повідомлення журналу комітів.

-s::
--signoff::
	Додавати трейлер `Signed-off-by` до повідомлення коміту, використовуючи свій ідентифікатор комітера. Дивіться опцію підписання в linkgit:git-commit[1] для отримання додаткової інформації.

--stdout::
	Виводити всі коміти у стандартний вивід у форматі mbox, замість створення окремого файлу для кожного з них.

--attach[=<boundary>]::
	Створення вкладення типу «multipart/mixed», перша частина якого — це повідомлення про коміт, а друга — власне латка, із заголовком `Content-Disposition: attachment`.

--no-attach::
	Вимкнути створення вкладення, замінивши налаштування конфігурації.

--inline[=<boundary>]::
	Створення вкладення типу «multipart/mixed», перша частина якого — це повідомлення про коміт, а друга — власне латка, із заголовком `Content-Disposition: inline`.

--thread[=<style>]::
--no-thread::
	Керує додаванням заголовків `In-Reply-To` та `References`, щоб другий та наступні листи показувались як відповіді на перший. Також керує генерацією заголовка `Message-ID` для посилання.
+
Необовʼязковий аргумент <style> може мати значення `shallow` або `deep`. З `shallow` кожен лист є відповіддю на заголовок серії, де заголовок вибирається з супровідного листа, `--in-reply-to` та першого листа з латкою у такому порядку. `deep` робить кожен лист відповіддю на попередній.
+
Стандартно — `--no-thread`, якщо не встановлено конфігурацію `format.thread`. `--thread` без аргументу еквівалентно `--thread=shallow`.
+
Зверніть увагу, що стандартно команда 'git send-email' сама формує ланцюжок листів. Якщо ви хочете, щоб формування ланцюжка листів здійснювала команда `git format-patch`, вам слід переконатися, що ця функція вимкнена для команди `git send-email`.

--in-reply-to=<message-id>::
	Зробити так, щоб перший лист (або всі листи з `--no-thread`) gjrfpedfkbcm як відповідь на вказаний <message-id>, що дозволяє уникнути розриву потоків для створення нової серії латок.

--ignore-if-in-upstream::
	Не включати латку, що відповідає коміту, у <until>..<since>. Перевірити всі латки, доступні з <since>, але не з <until>, та порівняти їх зі згенерованими латками, а будь-яку латку, що має збіг, ігнорувати.

--always::
	Включити латки для комітів, які не вносять жодних змін, що стандартно пропускаються.

--cover-from-description=<mode>::
	Контролює, які частини супровідного листа будуть автоматично заповнені з використанням опису гілки.
+
Якщо `<mode>` має значення `message` або `default`, тема супровідного листа буде заповнена текстом-заповнювачем. Основна частина супровідного листа буде заповнена описом гілки. Це стандартний режим, коли не вказано жодної конфігурації чи параметра командного рядка.
+
Якщо `<mode>` має значення `subject`, то перший абзац опису гілки заповнить тему супровідного листа. Решта опису заповнить основну частину супровідного листа.
+
Якщо `<mode>` має значення `auto`, і перший абзац опису гілки перевищує 100 байт, тоді режим буде `message`, інакше буде використано `subject`.
+
Якщо `<mode>` має значення `none`, то і тема, і тіло супровідного листа будуть заповнені текстом-заповнювачем.

--description-file=<file>::
	Використовувати вміст <file> замість опису гілки для створення супровідного листа.

--subject-prefix=<subject-prefix>::
	Замість стандартного префікса '[PATCH]' у рядку теми листа використовувати '[<subject-prefix>]'. Його можна використовувати для назви серії латок, а також поєднувати з опцією `--numbered`.
+
Змінна конфігурації `format.subjectPrefix` також може бути використана для налаштування префікса теми, який застосовуватиметься до заданого репозиторію для всіх латок. Це часто корисно в списках розсилки, які отримують латки для кількох репозиторіїв, і може бути використано для усунення неоднозначності латок (наприклад, зі значенням "PATCH my-project").

--filename-max-length=<n>::
	Замість стандартних 64 байтів, скоротіть згенеровані назви вихідних файлів приблизно до '<n>' байтів (занадто коротке значення буде непомітно збільшено до прийнятної довжини). Стандартно використовується значення змінної конфігурації `format.filenameMaxLength` або 64, якщо не налаштовано.

--rfc[=<rfc>]::
	Додає рядок _<rfc>_ (типово "RFC") до префікса теми. Оскільки префікс теми зазвичай має значення "PATCH", ви отримаєте "RFC PATCH".
+
RFC означає «Запит на коментарі»; використовуйте це, надсилаючи експериментальну латку для обговорення, а не для її застосування. «--rfc=WIP» також може бути корисним способом вказати, що латку ще не завершено («WIP» означає «Work In Progress» — «Робота в процесі»).
+
Якщо за прийнятою практикою спільноти-одержувача додатковий рядок має розміщуватися _після_ префікса теми, перед рядком _<rfc>_ можна поставити тире («`-`»), щоб вказати, що решту рядка _<rfc>_ слід додати до префікса теми, наприклад, `--rfc='-(WIP)'` дасть результат «PATCH (WIP)» .

-v <n>::
--reroll-count=<n>::
	Позначте серію як <n>-ту ітерацію теми. До імен вихідних файлів додається `v<n>`, а до префікса теми (зазвичай "PATCH", але його можна налаштувати за допомогою опції `--subject-prefix`) додається `v<n>`. Наприклад, `--reroll-count=4` може створити файл `v4-0001-add-makefile.patch`, який містить "Subject: [PATCH v4 1/20] Додавання makefile". `<n>` не обовʼязково має бути цілим числом (наприклад, "--reroll-count=4.4" або "--reroll-count=4rev2" дозволені), але недоліком використання такого reroll-count є те, що range-diff/interdiff з попередньою версією не вказує точно, з якою версією порівнюється нова ітерація.

--to=<email>::
	Додайте заголовок `To:` до заголовків електронного листа. Це доповнення до будь-яких налаштованих заголовків і може використовуватися кілька разів. Заперечувана форма `--no-to` відкидає всі заголовки `To:`, додані до цього часу (з конфігурації або командного рядка).

--cc=<email>::
	Додайте заголовок `Cc:` до заголовків електронної пошти. Це доповнення до будь-яких налаштованих заголовків і може використовуватися кілька разів. Заперечувальна форма `--no-cc` відкидає всі заголовки `Cc:`, додані до цього часу (з конфігурації або командного рядка).

--from::
--from=<ident>::
	Використовуйте `ident` у заголовку `From:` кожного електронного листа з комітом. Якщо ідентифікатор автора коміта текстово не ідентичний наданому `ident`, розмістіть заголовок `From:` у тілі повідомлення з оригінальним автором. Якщо `ident` не вказано, використовуйте ідентифікатор коміта.
+
Зверніть увагу, що ця опція корисна лише тоді, коли ви фактично надсилаєте електронні листи та хочете ідентифікувати себе як відправника, але зберегти оригінального автора (і `git am` правильно отримає заголовок in-body). Також зауважте, що `git send-email` вже обробляє це перетворення за вас, і цю опцію не слід використовувати, якщо ви передаєте результат до `git send-email`.

--force-in-body-from::
--no-force-in-body-from::
	Якщо відправника електронної пошти вказано за допомогою опції `--from`, зазвичай у верхній частині повідомлення журналу комітів додається поле "From:" для ідентифікації справжнього автора коміта, якщо відправник відрізняється від автора. З цією опцією поле "From:" додається, навіть якщо відправник та автор мають однакове імʼя та адресу, що може допомогти, якщо програмне забезпечення списку розсилки спотворює особу відправника. Стандартно використовується значення змінної конфігурації `format.forceInBodyFrom`.

--add-header=<header>::
	Додайте довільний заголовок до заголовків електронного листа. Це доповнення до будь-яких налаштованих заголовків і може використовуватися кілька разів. Наприклад, `--add-header="Organization: git-foo"`. Заперечувана форма `--no-add-header` відкидає *всі* заголовки (`To:`, `Cc:` та власні), додані до цього моменту з конфігурації або командного рядка.

--cover-letter::
--no-cover-letter::
	Окрім латок, генерувати файл супровідного листа, що містить опис гілки, короткий журнал та загальну статистику змін. Ви можете заповнити опис у файлі перед його надсиланням.

--encode-email-headers::
--no-encode-email-headers::
	Кодувати заголовки електронних листів, що містять символи, відмінні від ASCII, за допомогою "Q-кодування" (описано в RFC 2047), замість дослівного виведення заголовків. Стандартно використовується значення змінної конфігурації `format.encodeEmailHeaders`.

--interdiff=<previous>::
	Як допоміжний засіб для рецензентів, вставте interdiff у супровідний лист або як коментар до окремої латки серії з однієї латки, показуючи відмінності між попередньою версією серії латки та серією, що наразі форматується. `previous` — це окрема ревізія з назвою вершини попередньої серії, яка має спільну основу з серією, що форматується (наприклад, `git format-patch --cover-letter --interdiff=feature/v1 -3 feature/v2`).

--range-diff=<previous>::
	Як допомога рецензентам, вставте range-diff (див. linkgit:git-range-diff[1]) у супровідний лист або як коментар до окремої латки серії з однієї латки, показуючи відмінності між попередньою версією серії латки та серією, що наразі форматується. `previous` може бути однією ревізією з назвою вершини попередньої серії, якщо вона має спільну основу з серією, що форматується (наприклад, `git format-patch --cover-letter --range-diff=feature/v1 -3 feature/v2`), або діапазоном ревізій, якщо дві версії серії не перетинаються (наприклад, `git format-patch --cover-letter --range-diff=feature/v1~3..feature/v1 -3 feature/v2`).
+
Зверніть увагу, що параметри diff, передані команді, впливають на те, як генерується основний продукт `format-patch`, і вони не передаються базовому механізму `range-diff`, який використовується для генерації матеріалу супровідного листа (це може змінитися в майбутньому).

--creation-factor=<percent>::
	Використовується з `--range-diff`, налаштовує евристику, яка зіставляє коміти між попередньою та поточною серією латок, коригуючи коефіцієнт витрат на створення/видалення. Див. linkgit:git-range-diff[1]) для деталей.
+
Стандартне значення — 999 (linkgit:git-range-diff[1] використовує 60), оскільки варіант використання полягає в тому, щоб показати порівняння зі старішою версією тієї ж теми, і інструмент повинен знайти більше відповідностей між двома наборами латок.

--notes[=<ref>]::
--no-notes::
	Додає примітки (див. linkgit:git-notes[1]) для коміту після лінії з трьох дефісів.
+
Очікуваним варіантом використання цього є написання підтверджувального пояснення для коміту, який не належить до власне повідомлення журналу комітів, та включення його до надісланої латки. Хоча можна просто написати ці пояснення після виконання `format-patch`, але перед надсиланням, збереження їх як нотаток Git дозволяє підтримувати їх між версіями серії латок (але дивіться обговорення параметрів конфігурації `notes.rewrite` у linkgit:git-notes[1] для використання цього робочого процесу).
+
Стандартне значення — `--no-notes`, якщо не встановлено конфігурацію `format.notes`.

--signature=<signature>::
--no-signature::
	Додайте підпис до кожного створеного повідомлення. Згідно з RFC 3676, підпис відділяється від тіла рядком із символом '--'. Якщо параметр підпису пропущено, для підпису зазвичай використовується номер версії Git.

--signature-file=<file>::
	Працює так само, як --signature, за винятком того, що підпис зчитується з файлу.

--suffix=.<sfx>::
	Замість використання `.patch` як суфікса для згенерованих назв файлів, використовувати вказаний суфікс. Поширеною альтернативою є `--suffix=.txt`. Якщо залишити це поле порожнім, суфікс `.patch` буде видалено.
+
Зверніть увагу, що початковий символ не обовʼязково має бути крапкою; наприклад, ви можете використовувати `--suffix=-patch`, щоб отримати `0001-description-of-my-change-patch`.

-q::
--quiet::
	Не виводити назви згенерованих файлів у стандартний вивід.

--no-binary::
	Не виводити вміст змін у бінарних файлах, натомість показувати повідомлення про те, що ці файли змінилися. Латки, згенеровані за допомогою цієї опції, не можуть бути застосовані належним чином, але вони все одно корисні для перевірки коду.

--zero-commit::
  Вивести хеш, що складається з нулів, у заголовку From кожної латки замість хешу коміта.

--no-base::
--base[=<commit>]::
	Записує інформацію про базове дерево, щоб визначити стан, до якого застосовується серія латок. Див. розділ ІНФОРМАЦІЯ ПРО БАЗОВЕ ДЕРЕВО нижче для отримання детальної інформації. Якщо <commit> має значення "auto", базовий коміт вибирається автоматично. Опція `--no-base` перевизначає конфігурацію `format.useAutoBase`.

--root::
	Розглядати аргумент revision як <revision-range>, навіть якщо це лише один коміт (який зазвичай розглядається як <since>). Зверніть увагу, що кореневі коміти, що входять до зазначеного діапазону, завжди форматуються як латки створення, незалежно від цього прапорця.

--progress::
	Виводити звіти про прогрес в stderr під час створення латок.

КОНФІГУРАЦІЯ
------------
Ви можете вказати додаткові рядки заголовка листа, які будуть додаватися до кожного повідомлення, задати стандартні значення для префікса теми та суфікса файлу, нумерувати латки при виведенні декількох латок, додавати заголовки «To:» або «Cc:», налаштовувати вкладення, змінювати теку виведення латок, а також підписувати латки за допомогою змінних конфігурації.

------------
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <email>
	cc = <email>
	attach [ = mime-boundary-string ]
	signOff = true
	outputDirectory = <directory>
	coverLetter = auto
	coverFromDescription = auto
------------


ОБГОВОРЕННЯ
-----------

Латка, створена командою 'git format-patch', має формат поштової скриньки UNIX з фіксованою «магічною» міткою часу, яка вказує на те, що файл виводиться з format-patch, а не зі справжньої поштової скриньки, ось так:

------------
From 8f72bad1baf19a53459661343e21d6491c3908d3 Mon Sep 17 00:00:00 2001
From: Tony Luck <tony.luck@intel.com>
Date: Tue, 13 Jul 2010 11:42:54 -0700
Subject: [PATCH] =?UTF-8?q?[IA64]=20Put=20ia64=20config=20files=20on=20the=20?=
 =?UTF-8?q?Uwe=20Kleine-K=C3=B6nig=20diet?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Файли конфігурації arch/arm були скорочені за допомогою скрипта Python
(Див. коментар до коміту c2330e286f68f1c408b4aa6515ba49d57f05beae)

Зробіть те саме для ia64, щоб ми могли мати елегантний та акуратний вигляд
...
------------

Зазвичай її розміщують у теці чернеток MUA, редагують для додавання своєчасних коментарів, які не повинні потрапляти до журналу змін після трьох дефісів, а потім надсилають як повідомлення, тіло якого, у нашому прикладі, починається з "файли конфігурації arch/arm були...". З іншого боку, читачі можуть зберігати цікаві латки у поштовій скриньці UNIX та застосовувати їх за допомогою linkgit:git-am[1].

Коли латка є частиною поточного обговорення, латку, згенеровану командою 'git format-patch', можна налаштувати, щоб скористатися перевагами функції 'git am --scissors'. Після вашої відповіді на обговорення йде рядок, який складається виключно з "`-- >8 --`" (ножиці та перфорація), а потім сама латка з видаленими непотрібними полями заголовка:

------------
...
> Отже, нам слід зробити те й те.

Мені зрозуміло. Як щодо цієї латки?

-- >8 --
Тема: [IA64] Додати конфігураційні файли ia64 до дієти Уве Кляйне-Кеніга

Файли конфігурації arch/arm були скорочені за допомогою скрипта Python
...
------------

Надсилаючи латку таким чином, найчастіше ви надсилаєте свою власну латку, тому, окрім маркера "`From $SHA1 $magic_timestamp`", вам слід пропустити рядки `From:` та `Date:` з файлу латки. Назва латки, ймовірно, відрізнятиметься від теми обговорення, на яке відповідає латка, тому, ймовірно, вам варто зберегти рядок Subject:, як у прикладі вище.

Перевірка на наявність пошкоджених латок
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Багато поштових програм, якщо їх неправильно налаштувати, пошкоджують пробіли. Ось два поширені типи пошкодження:

* Порожні рядки контексту, які не містять _будь-яких_ пробілів.

* Непорожні рядки контексту, що мають один додатковий пробіл на початку.

Один із способів перевірити, чи правильно налаштовано ваш MUA:

* Надішліть латку собі саме так, як і ви це зробили б, за винятком того, що рядки «Кому:» та «Копія:» не містять адреси списку та відповідальної особи.

* Збережіть цю латку в файлі у форматі поштової скриньки UNIX. Назвіть його, скажімо, a.patch.

* Виконайте наступне:

    $ git fetch <project> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

Якщо латка застосовується неправильно, на це може бути кілька причин.

* Сама латка застосовується не зовсім коректно. Це _погано_, але це не має великого стосунку до вашого MUA. У цьому випадку, можливо, варто перебазувати латку за допомогою linkgit:git-rebase[1] перед її повторною генерацією.

* MUA пошкодив вашу латку; "am" скаржився, що латка не застосовується. Перегляньте субтеку .git/rebase-apply/ та перевірте, що містить файл "patch", і перевірте наявність згаданих вище типових шаблонів пошкодження.

* Також перевірте файли 'info' та 'final-commit'. Якщо вміст 'final-commit' не зовсім відповідає тому, що ви хотіли б бачити в повідомленні журналу комітів, дуже ймовірно, що одержувач вручну редагуватиме повідомлення журналу під час застосування вашої латки. Такі речі, як "Привіт, це мій перший патч.\n" в електронному листі з латкою, повинні йти після рядка з трьох дефісів, що сигналізують про кінець повідомлення коміту.

РЕКОМЕНДАЦІЇ ДЛЯ MUA
--------------------
Ось кілька порад щодо успішного надсилання латок безпосередньо за допомогою різних поштових програм.

GMail
~~~~~
У веб-інтерфейсі GMail немає можливості вимкнути перенесення рядків, тому будь-які надіслані вами електронні листи будуть спотворені. Однак ви можете скористатися командою "git send-email" та надсилати свої латки через SMTP-сервер GMail або будь-яким поштовим клієнтом IMAP для підключення до сервера Google IMAP та пересилання електронних листів через нього.

Поради щодо використання 'git send-email' для надсилання латок через SMTP-сервер GMail дивіться в розділі ПРИКЛАД у документі linkgit:git-send-email[1].

Поради щодо надсилання за допомогою інтерфейсу IMAP див. у розділі ПРИКЛАД у файлі linkgit:git-imap-send[1].

Thunderbird
~~~~~~~~~~~
Зазвичай Thunderbird не тільки переносить текст листів на новий рядок, а й позначає їх як 'format=flowed', що робить отриманий файл електронного листа непридатним для використання в Git.

Існує три різні підходи: використовувати доповнення, щоб вимкнути перенесення рядків, налаштувати Thunderbird так, щоб він не спотворював латки, або використовувати зовнішній редактор, щоб Thunderbird не спотворював латки.

Підхід №1 (доповнення)
^^^^^^^^^^^^^^^^^^^^^^

Встановіть доповнення Toggle Line Wrap, доступне за адресою https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap. Воно додає кнопку «Line Wrap» на панель інструментів редактора, яку можна ввімкнути. Тепер ви можете складати повідомлення так само, як і зазвичай (вирізати + вставити, 'git format-patch' | 'git imap-send' тощо), але вам доведеться вручну вставляти розриви рядків у будь-який текст, який ви вводите.

Як бонусна функція, доповнення може виявляти текст латки в редакторі тексту та попереджати, коли перенесення рядків ще не вимкнено.

Для роботи доповнення потрібно внести кілька змін у розширену конфігурацію (about:config). Вони перелічені на сторінці завантаження.

Підхід №2 (конфігурація)
^^^^^^^^^^^^^^^^^^^^^^^^
Три кроки:

1. Налаштуйте створення листів на поштовому сервері у форматі простого тексту: «Редагувати»... «Налаштування облікового запису»... «Створення та адресація», зніміть галочку біля пункту «Створювати листи у форматі HTML».

2. Налаштуйте загальне вікно створення листів так, щоб текст не переносився.
+
У Thunderbird 2: Редагувати..Налаштування..Створення, переносити текстові повідомлення на 0
+
У Thunderbird 3: Редагувати... Налаштування... Додатково... Редактор конфігурацій. Знайдіть "mail.wrap_long_lines". Перемкніть його, щоб переконатися, що для нього встановлено значення `false`. Також знайдіть "mailnews.wraplength" і встановіть значення 0.

3. Вимкніть використання format=flowed: Редагувати..Налаштування..Додатково..Редактор конфігурацій. Знайдіть "mailnews.send_plaintext_flowed". Перемкніть його, щоб переконатися, що для нього встановлено значення `false`.

Після цього ви зможете писати електронні листи так, як це зазвичай робите (вирізати + вставити, 'git format-patch' | 'git imap-send' тощо), і латки не будуть пошкоджені.

Підхід №3 (зовнішній редактор)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Потрібні такі розширення Thunderbird: AboutConfig з https://mjg.github.io/AboutConfig/ та External Editor з https://globs.org/articles.php?lng=en&pg=8

1. Підготуйте латку у вигляді текстового файлу, використовуючи обраний вами метод.

2. Перш ніж відкривати вікно створення повідомлення, скористайтеся меню Редагувати->Налаштування облікового запису, щоб зняти прапорець «Створювати повідомлення у форматі HTML» на панелі «Створення та адресація» облікового запису, з якого потрібно надсилати латку.

3. У головному вікні Thunderbird, 'перед' відкриттям вікна створення латки, скористайтеся Інструменти->about:config, щоб встановити вказані значення для наступних параметрів:
+
----------
	mailnews.send_plaintext_flowed  => false
	mailnews.wraplength             => 0
----------

4. Відкрийте вікно створення листа та натисніть значок зовнішнього редактора.

5. У вікні зовнішнього редактора зчитайте файл латки та вийдіть з редактора звичайним способом.

Примітка: можливо, можна виконати крок 2 з about:config та наступними налаштуваннями, але ніхто ще не пробував.

----------
	mail.html_compose                       => false
	mail.identity.default.compose_html      => false
	mail.identity.id?.compose_html          => false
----------

У contrib/thunderbird-patch-inline є скрипт, який допоможе вам легко додавати латки за допомогою Thunderbird. Щоб його використовувати, виконайте наведені вище кроки, а потім використовуйте скрипт як зовнішній редактор.

KMail
~~~~~
Це має допомогти вам надсилати латки безпосередньо за допомогою KMail.

1. Підготуйте латку у вигляді текстового файлу.

2. Натисніть на «Новий лист».

3. Перейдіть до розділу "Параметри" у вікні редактора тексту та переконайтеся, що параметр "Перенос слів" не встановлено.

4. Використайте Повідомлення -> Вставити файл... та вставте латку.

5. Повернувшись у вікно створення листа: додайте до повідомлення будь-який інший текст, заповніть поля адреси та теми й натисніть «Надіслати».

ІНФОРМАЦІЯ ПРО БАЗОВЕ ДЕРЕВО
----------------------------

Блок інформації про базове дерево використовується для того, щоб розробники або сторонні тестувальники знали, до якого саме стану застосовується серія латок. Він складається з 'базового коміту' — це добре відомий коміт, що є частиною стабільної частини історії проєкту, на основі якої працюють усі інші, — та нуля або більше 'попередніх латок', які є добре відомими латками, що знаходяться в процесі розробки, ще не входять до 'базового коміту' і мають бути застосовані поверх 'базового коміту' у топологічному порядку, перш ніж можна буде застосувати інші латки.

'Базовий коміт' відображається як «base-commit:», а потім 40-шістнадцяткове число назви обʼєкта коміту. 'Попередня латка' показується як «prerequisite-patch-id:», а потім 40-шістнадцяткове число 'patch id', яке можна отримати, передавши латку за допомогою команди `git patch-id --stable`.

Уявіть, що поверх публічного коміту P ви застосували добре відомі латки X, Y та Z від когось іншого, а потім створили свою серію з трьох латок A, B, C, історія буде такою:

................................................
---P---X---Y---Z---A---B---C
................................................

З `git format-patch --base=P -3 C` (або його варіантами, наприклад, з `--cover-letter` або використанням `Z..C` замість `-3 C` для визначення діапазону), блок інформації про базове дерево показується в кінці першого повідомлення, яке виводить команда (або перша латка, або супровідний лист), ось так:

------------
base-commit: P
prerequisite-patch-id: X
prerequisite-patch-id: Y
prerequisite-patch-id: Z
------------

Для нелінійної топології, такої як

................................................
---P---X---A---M---C
    \         /
     Y---Z---B
................................................

Ви також можете використовувати `git format-patch --base=P -3 C` для створення латок для A, B та C, а ідентифікатори для P, X, Y, Z додаються в кінці першого повідомлення.

Якщо в командному рядку вказано параметр `--base=auto`, система автоматично обчислить базовий коміт як базу злиття для кінцевого коміту гілки, що відстежує віддалену гілку, та діапазону ревізій, зазначеного в командному рядку. Для локальної гілки перед використанням цього параметра необхідно налаштувати її на відстеження віддаленої гілки за допомогою команди `git branch --set-upstream-to`.

ПРИКЛАДИ
--------

* Отримання комітів між ревізіями R1 та R2 та застосування їх поверх поточної гілки за допомогою 'git am' для їх вибірки (cherry-pick):
+
------------
$ git format-patch -k --stdout R1..R2 | git am -3 -k
------------

* Отримати всі коміти, які знаходяться в поточній гілці, але не в початковій гілці:
+
------------
$ git format-patch origin
------------
+
Для кожного коміту створюється окремий файл у поточній теці.

* Отримання всіх комітів, що ведуть до 'origin' з моменту початку проєкту:
+
------------
$ git format-patch --root origin
------------

* Те саме, що й попередній приклад:
+
------------
$ git format-patch -M -B origin
------------
+
Крім того, він виявляє та обробляє перейменування й інтелектуально завершує перезаписи, створюючи латку для перейменування. Латка для перейменування зменшує обсяг виведеного тексту та загалом полегшує його перегляд. Зверніть увагу, що програми-"patch", які не підтримують Git, не розуміють латки для перейменування, тому використовуйте їх лише тоді, коли знаєте, що одержувач використовує Git для застосування вашої латки.

* Отримання трьох найвищих комітів з поточної гілки та форматування їх у вигляді латок для надсилання електронною поштою:
+
------------
$ git format-patch -3
------------

ЗАСТЕРЕЖЕННЯ
------------

Зверніть увагу, що `format-patch` пропустить коміти злиття з виводу, навіть якщо вони є частиною запитуваного діапазону. Проста "латка" не містить достатньо інформації для того, щоб отримувач зміг відтворити той самий коміт злиття.

ДИВ. ТАКОЖ
----------
linkgit:git-am[1], linkgit:git-send-email[1]

GIT
---
Частина набору linkgit:git[1]
