git-instaweb(1)
===============

НАЗВА
-----
git-instaweb — Миттєвий перегляд робочого репозиторію в gitweb

СИНОПСИС
--------
[verse]
'git instaweb' [--local] [--httpd=<httpd>] [--port=<port>]
               [--browser=<browser>]
'git instaweb' [--start] [--stop] [--restart]

ОПИС
----
Простий скрипт для налаштування `gitweb` та вебсервера для перегляду локального репозиторію.

ОПЦІЇ
-----

-l::
--local::
	Прив’язати вебсервер тільки до локальної IP-адреси (127.0.0.1).

-d::
--httpd::
	Командний рядок демона HTTP, який буде виконано. Тут можна вказати параметри командного рядка, а файл конфігурації буде додано в кінці командного рядка. Наразі підтримуються apache2, lighttpd, mongoose, plackup, python та webrick. (Зазвичай: lighttpd)

-m::
--module-path::
	Шлях до модуля (потрібен лише якщо httpd  — це Apache). (Стандартно — /usr/lib/apache2/modules)

-p::
--port::
	Номер порту для привʼязки httpd. (Стандартно — 1234)

-b::
--browser::
	Вебоглядач, який слід використовувати для перегляду сторінки gitweb. Його буде передано допоміжному скрипту 'git web{litdd}browse' разом з URL-адресою екземпляра gitweb. Див. linkgit:git-web{litdd}browse[1] для отримання додаткової інформації про це. Якщо скрипт завершиться невдачею, URL-адреса буде виведена на стандартний вивід.

start::
--start::
	Запуск екземпляру httpd та вихід із програми. За необхідності перегенеруйте файли конфігурації для запуску нового екземпляру.

stop::
--stop::
	Зупинити екземпляр httpd та вийти. Команда не генерує жодних файлів конфігурації для створення нового екземпляра, а також не закриває оглядач.

restart::
--restart::
	Перезапуск екземпляра httpd та вихід. За потреби згенерує файли конфігурації для створення нового екземпляра.

КОНФІГУРАЦІЯ
------------

Ви можете вказати конфігурацію у вашому .git/config

-----------------------------------------------------------------------
[instaweb]
	local = true
	httpd = apache2 -f
	port = 4321
	browser = konqueror
	modulePath = /usr/lib/apache2/modules

-----------------------------------------------------------------------

Якщо змінна конфігурації `instaweb.browser` не встановлена, замість неї буде використано `web.browser`, якщо вона визначена. Див. linkgit:git-web{litdd}browse[1] для отримання додаткової інформації про це.

ДИВ. ТАКОЖ
----------
linkgit:gitweb[1]

GIT
---
Частина набору linkgit:git[1]
