git-credential-cache(1)
=======================

НАЗВА
-----
git-credential-cache - Помічник для тимчасового зберігання паролів у пам'яті

СИНОПСИС
--------
-----------------------------
git config credential.helper 'cache [<options>]'
-----------------------------

ОПИС
----

Ця команда кешує облікові дані для використання майбутніми програмами Git. Збережені облікові дані зберігаються в пам'яті процесу cache-daemon (замість запису у файл) і забуваються після налаштованого тайм-ауту. Облікові дані забуваються швидше, якщо cache-daemon завершує роботу, наприклад, під час перезавантаження системи. Кеш доступний через сокет домену Unix, обмежений поточним користувачем правами файлової системи.

Ймовірно, вам не варто викликати цю команду безпосередньо; вона призначена для використання як допоміжний засіб для облікових даних іншими частинами Git. Див. linkgit:gitcredentials[7] або `ПРИКЛАДИ` нижче.

ОПЦІЇ
-----

--timeout <seconds>::

	Кількість секунд для кешування облікових даних (за замовчуванням: 900).

--socket <path>::

	Використовуйте `<шлях>`, щоб зв'язатися з запущеним демоном кешу (або запустити новий демон кешу, якщо він ще не запущений). За замовчуванням використовується `$XDG_CACHE_HOME/git/credential/socket`, якщо не існує `~/.git-credential-cache/`, у такому разі використовується `~/.git-credential-cache/socket`. Якщо ваш домашній каталог знаходиться на файловій системі, змонтованій у мережі, вам може знадобитися змінити її на локальну файлову систему. Ви повинні вказати абсолютний шлях.

КЕРУВАННЯ ДЕМОНОМ
-----------------

Якщо ви хочете, щоб демон завершив роботу раніше, забуваючи всі кешовані облікові дані до закінчення терміну їхньої дії, ви можете виконати дію `exit`:

--------------------------------------
git credential-cache exit
--------------------------------------

ПРИКЛАДИ
--------

Мета цього помічника — зменшити кількість разів, коли вам потрібно вводити своє ім’я користувача або пароль. Наприклад:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

[work for 5 more minutes]
$ git push http://example.com/repo.git
[your credentials are used automatically]
------------------------------------

Ви можете надати параметри через змінну конфігурації credential.helper (у цьому прикладі час кешування збільшується до 1 години):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

ОСОБИСТІ ТОКЕНИ ДОСТУПУ
-----------------------

Деякі пульти дистанційного керування приймають персональні токени доступу, які генеруються випадковим чином і їх важко запам'ятати. Зазвичай вони діють протягом тижнів або місяців.

git-credential-cache за своєю суттю непридатний для постійного зберігання персональних токенів доступу. Облікові дані будуть забуті після закінчення часу очікування кешу. Навіть якщо ви налаштуєте тривалий час очікування, облікові дані будуть забуті, якщо демон завершить роботу.

Щоб уникнути частого повторного створення особистих токенів доступу, налаштуйте допоміжний засіб облікових даних із постійним сховищем. Або ж налаштуйте допоміжний засіб облікових даних OAuth для автоматичної генерації облікових даних. Див. linkgit:gitcredentials[7], розділи «Доступні допоміжні засоби» та «OAuth».

GIT
---
Частина набору linkgit:git[1]
