git-archimport(1)
=================

НАЗВА
-----
git-archimport - Імпорт репозиторію GNU Arch у Git


СИНОПСИС
--------
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <depth>] [-t <tempdir>]
	       <archive>/<branch>[:<git-branch>]...

ОПИС
----
Імпортує проєкт з одного або кількох репозиторіїв GNU Arch. Він слідуватиме за гілками та репозиторіями в межах просторів імен, визначених наданими параметрами <archive>/<branch>. Якщо не вдається знайти віддалену гілку, з якої походить злиття, він просто імпортує її як звичайний коміт. Якщо ж його вдається знайти, він позначає його як злиття, коли це можливо (див. обговорення нижче).

Скрипт очікує від вас надання кореневих ключових тегів, з яких можна розпочати імпорт з коміту Arch типу «початковий імпорт» або «тег». Він буде слідувати та імпортувати нові гілки в межах наданих кореневих тегів.

Він очікує працювати лише з одним проектом. Якщо він побачить гілки з різними коренями, він відмовиться від запуску. У такому разі відредагуйте параметри <archive>/<branch>, щоб чітко визначити область імпорту.

'git archimport' активно використовує `tla` у фоновому режимі для доступу до репозиторію Arch. Переконайтеся, що у вас є остання версія `tla`, доступна у шляху. `tla` повинен знати про репозиторії, які ви передаєте до 'git archimport'.

Для початкового імпорту «git archimport» очікує знайти себе в порожньому каталозі. Щоб простежити розробку проекту, який використовує Arch, повторно запустіть «git archimport» з тими ж параметрами, що й для початкового імпорту, щоб виконати поступовий імпорт.

Хоча «git archimport» намагатиметься створити зрозумілі назви гілок для архівів, які він імпортує, також можна вказати назви гілок Git вручну. Для цього напишіть назву гілки Git після кожного параметра <archive>/<branch>, розділивши її двокрапкою. Таким чином, ви можете скоротити назви гілок Arch та перетворити жаргон Arch на жаргон Git, наприклад, зіставивши гілку "PROJECT{litdd}devo{litdd}VERSION" з "master".

Можливе пов'язування кількох гілок Arch з однією гілкою Git; результат буде найбільш логічним, лише якщо після створення другої гілки до першої гілки не буде зроблено жодних комітів. Тим не менш, це корисно для конвертації репозиторіїв Arch, які періодично ротувалися.


ОБ'ЄДНАННЯ
----------
Дані злиття патчів з Arch також використовуються для позначення злиття в Git. Git не дуже переймається відстеженням патчів і розглядає злиття лише тоді, коли гілка включає всі коміти з моменту їх розгалуження. Кінцевий результат полягає в тому, що Git матиме чітке уявлення про те, наскільки розійшлися гілки. Тож процес імпорту втрачає деякі метадані обміну патчами.

На щастя, коли ви намагаєтеся об'єднати гілки, імпортовані з Arch, Git знайде хорошу базу злиття, і у нього є хороші шанси виявити патчі, які були обміняні поза послідовністю між гілками.

ОПЦІЇ
-----

-h::
	Використання дисплея.

-v::
	Детальний вивід.

-T::
	Багато тегів. Створить тег для кожного коміту, що відображає назву коміту в репозиторії Arch.

-f::
	Використовуйте стратегію швидкого імпорту набору патчів. Це може бути значно швидшим для великих дерев, але не може обробляти перейменування каталогів або зміни дозволів. Стратегія за замовчуванням є повільною та безпечною.

-o::
	Використовуйте це для сумісності зі старим стилем імен гілок, що використовувалися попередніми версіями 'git archimport'. Старим стилем імен гілок були category{litdd}branch, тоді як новим стилем імен гілок були archive,category{litdd}branch{litdd}version. В обох випадках імена, задані в командному рядку, замінять автоматично згенеровані.

-D <depth>::
	Слідкуйте за походженням злиття та спробуйте імпортувати дерева, з яких було злито. Вкажіть глибину більше 1, якщо журнали латок були обрізані.

-a::
	Спроба автоматично зареєструвати архіви за адресою `http://mirrors.sourcecontrol.net`. Це особливо корисно з опцією -D.

-t <tmpdir>::
	Перевизначити тимчасовий каталог за замовчуванням.


<archive>/<branch>::
	Ідентифікатор <archive>/<branch> у форматі, який розуміє `tla log`.


GIT
---
Частина набору linkgit:git[1]
