git-var(1)
==========

НАЗВА
-----
git-var — Показ булевих змінних Git


СИНОПСИС
--------
[synopsis]
git var (-l | <variable>)

ОПИС
----
Виводить булеву змінну Git. Завершує роботу з кодом 1, якщо змінна не має значення.

ОПЦІЇ
-----
`-l`::
	Показати булеві змінні. Крім того, також відображаються всі змінні з файлу конфігурації Git .git/config. (Однак функція переліку змінних конфігурації більше не підтримується, натомість рекомендується використовувати команду `git config -l`.)

ПРИКЛАДИ
--------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


ЗМІННІ
------
`GIT_AUTHOR_IDENT`::
    Автор фрагмента коду.

`GIT_COMMITTER_IDENT`::
    Особа, яка додала фрагмент коду до Git.

`GIT_EDITOR`::
    Текстовий редактор для використання командами Git. Це значення має інтерпретуватися оболонкою під час використання. Приклади: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. Порядок пріоритету: спочатку `$GIT_EDITOR`, потім значення конфігурації `core.editor`, потім `$VISUAL`, потім `$EDITOR`, а потім стандартне значення, обране під час компіляції, яке зазвичай є 'vi'.
ifdef::git-default-editor[]
    У вашій збірці як стандартний редактор використовується '{git-default-editor}'.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Текстовий редактор, який використовується для редагування файлу «todo» під час виконання команди `git rebase -i`. Як і у випадку з `GIT_EDITOR`, значення має інтерпретуватися оболонкою під час його використання. Порядок пріоритетності такий: `$GIT_SEQUENCE_EDITOR`, потім значення конфігурації `sequence.editor`, а потім значення `git var GIT_EDITOR`.

`GIT_PAGER`::
    Текстовий переглядач для використання командами Git (наприклад, 'less'). Значення призначене для інтерпретації оболонкою. Порядок пріоритету такий: `$GIT_PAGER`, потім значення конфігурації `core.pager`, потім `$PAGER`, і нарешті стандартне значення, встановлене під час компіляції (зазвичай `less`).
ifdef::git-default-pager[]
    У вашій збірці використовується '{git-default-pager}' як стандартний засіб для перегляду.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    Назва першої гілки, створеної у щойно ініціалізованих репозиторіях.

`GIT_SHELL_PATH`::
    Шлях до бінарного файлу, що забезпечує роботу оболонки POSIX для команд, що використовують цю оболонку.

`GIT_ATTR_SYSTEM`::
    Шлях до системного файлу linkgit:gitattributes[5], якщо такий увімкнено.

`GIT_ATTR_GLOBAL`::
    Шлях до глобального (для кожного користувача) файлу linkgit:gitattributes[5].

`GIT_CONFIG_SYSTEM`::
    Шлях до файлу конфігурації системи, якщо він увімкнений.

`GIT_CONFIG_GLOBAL`::
    Шлях до глобальних (для кожного користувача) файлів конфігурації, якщо такі є.

Більшість значень шляху містять лише одне значення. Однак деякі можуть містити кілька значень, розділених символами нового рядка, які вказані в порядку від найвищого до найнижчого пріоритету. Користувачі повинні бути готові до того, що таке значення шляху може містити кілька елементів.

Зверніть увагу, що шляхи виводяться навіть якщо вони не існують, але не виводяться, якщо їх вимкнено іншими змінними середовища.

ДИВ. ТАКОЖ
----------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
Частина набору linkgit:git[1]
