git-mv(1)
=========

НАЗВА
-----
git-mv  — Переміщення або перейменування файлу, теки або символічного посилання


СИНОПСИС
--------

[synopsis]
git mv [-v] [-f] [-n] [-k] <source> <destination>
git mv [-v] [-f] [-n] [-k] <source>... <destination-directory>

ОПИС
----
Дозволяє переміщувати або перейменовувати файли, теки або символічні посилання.

У першій формі _<source>_, має існувати та бути або файлом, символічним посиланням або текою, перейменовується на _<destination>_. У другій формі _<destination-directory>_ має бути наявною текою; вказані джерела будуть переміщені до цієї теки.

Індекс оновлюється після успішного завершення, але зміни все одно необхідно зафіксувати.

ОПЦІЇ
-----
`-f`::
`--force`::
	Відбувається примусове перейменування або переміщення файлів, навіть якщо <destination> існує.
`-k`::
	Пропустити дії переміщення або перейменування, які можуть призвести до помилки. Помилка виникає, коли джерело не існує та не контролюється Git, або коли воно перезаписує наявний файл, якщо не вказано `-f`.
`-n`::
`--dry-run`::
	Нічого не робити; лише показати, що станеться

`-v`::
`--verbose`::
	Повідомляти імена файлів під час їх переміщення.

СУБМОДУЛІ
---------
Переміщення субмодуля за допомогою gitfile (що означає, що вони були клоновані за допомогою Git версії 1.7.8 або новішої) оновить налаштування gitfile та core.worktree, щоб субмодуль працював у новому місці. Також буде зроблено спробу оновити налаштування `submodule.<name>.path` у файлі linkgit:gitmodules[5] та розмістити цей файл (якщо не використовується `-n`).

ПОМИЛКИ
-------
Щоразу, коли оновлення суперпроєкту переміщує заповнений субмодуль (наприклад, під час перемикання між комітами до та після переміщення), застаріле отримання субмодуля залишатиметься у старому місці, а в новому місці зʼявиться порожня тека. Щоб знову заповнити субмодуль у новому місці, користувачеві доведеться виконати команду "git submodule update". Видалення старої теки є безпечним лише тоді, коли він використовує git-файл, оскільки інакше історія субмодуля також буде видалена. Обидва кроки будуть застарілими після реалізації рекурсивного оновлення субмодуля.

GIT
---
Частина набору linkgit:git[1]
