git-credential-store(1)
=======================

НАЗВА
-----
git-credential-store - Помічник для зберігання облікових даних на диску

СИНОПСИС
--------
-------------------
git config credential.helper 'store [<options>]'
-------------------

ОПИС
----

NOTE: Використання цього помічника зберігатиме ваші паролі на диску в незашифрованому вигляді, захищені лише правами доступу файлової системи. Якщо це неприйнятний компроміс з точки зору безпеки, спробуйте linkgit:git-credential-cache[1] або знайдіть помічник, який інтегрується з безпечним сховищем, що надається вашою операційною системою.

Ця команда зберігає облікові дані на диску на невизначений термін для використання майбутніми програмами Git.

Ймовірно, вам не варто викликати цю команду безпосередньо; вона призначена для використання як допоміжний засіб для облікових даних іншими частинами git. Див. linkgit:gitcredentials[7] або `ПРИКЛАДИ` нижче.

ОПЦІЇ
-----

--file=<path>::

	Використовуйте `<шлях>` для пошуку та зберігання облікових даних. Файл матиме встановлені дозволи файлової системи, щоб запобігти його читанню іншими користувачами системи, але він не буде зашифрований або іншим чином захищений. Якщо не вказано, облікові дані будуть шукатися в `~/.git-credentials` та `$XDG_CONFIG_HOME/git/credentials`, а облікові дані будуть записані в `~/.git-credentials`, якщо він існує, або в `$XDG_CONFIG_HOME/git/credentials`, якщо він існує, а перший ні. Див. також <<FILES>>.

[[FILES]]
ФАЙЛИ
-----

Якщо не встановлено явно за допомогою `--file`, є два файли, де git-credential-store шукатиме облікові дані в порядку пріоритету:

~/.git-credentials::
	Файл облікових даних користувача.

$XDG_CONFIG_HOME/git/credentials::
	Другий файл облікових даних користувача. Якщо '$XDG_CONFIG_HOME' не встановлено або він порожній, буде використано `$HOME/.config/git/credentials`. Будь-які облікові дані, що зберігаються в цьому файлі, не будуть використані, якщо `~/.git-credentials` також має відповідні облікові дані. Рекомендується не створювати цей файл, якщо ви іноді використовуєте старіші версії Git, які його не підтримують.

Для пошуку облікових даних файли зчитуються в порядку, зазначеному вище, причому перші знайдені відповідні облікові дані мають пріоритет над обліковими даними, знайденими у файлах далі у списку.

Сховище облікових даних за замовчуванням записуватиме дані в перший існуючий файл у списку. Якщо жодного з цих файлів не існує, буде створено та записано дані `~/.git-credentials`.

Під час стирання облікових даних відповідні облікові дані будуть видалені з усіх файлів.

ПРИКЛАДИ
--------

Мета цього помічника — зменшити кількість разів, коли вам потрібно вводити своє ім’я користувача або пароль. Наприклад:

------------------------------------------
$ git config credential.helper store
$ git push http://example.com/repo.git
Ім'я користувача: <type your username>
Пароль: <type your password>

[через кілька днів]
$ git push http://example.com/repo.git
[ваші облікові дані використовуються автоматично]
------------------------------------------

ФОРМАТ ЗБЕРІГАННЯ
-----------------

Файл `.git-credentials` зберігається у відкритому тексті. Кожні облікові дані зберігаються в окремому рядку як URL-адреса, наприклад:

------------------------------
https://user:pass@example.com
------------------------------

Жодні інші типи рядків (наприклад, порожні рядки або рядки коментарів) у файлі не допускаються, навіть якщо деякі з них можуть бути непомітно ігноровані. Не переглядайте та не редагуйте файл за допомогою редакторів.

Коли Git потребує автентифікації для певного контексту URL-адреси, credential-store вважатиме цей контекст шаблоном для зіставлення з кожним записом у файлі credentials. Якщо протокол, ім'я хоста та ім'я користувача (якщо воно вже є) збігаються, то пароль повертається до Git. Дивіться обговорення конфігурації в linkgit:gitcredentials[7] для отримання додаткової інформації.

GIT
---
Частина набору linkgit:git[1]
