git-pull(1)
===========

НАЗВА
-----
git-pull — Отримання та інтеграція даних з іншого репозиторію або локальної гілки


СИНОПСИС
--------
[synopsis]
git pull [<options>] [<repository> [<refspec>...]]


ОПИС
----

Інтеграція змін з віддаленого репозиторію в поточну гілку.

Спочатку команда `git pull` виконує команду `git fetch` з тими самими аргументами (за винятком опцій злиття), щоб завантажити віддалені гілки. Потім вона визначає, яку віддалену гілку потрібно інтегрувати: якщо запустити `git pull` без аргументів, типовим значенням для поточної гілки буде <<UPSTREAM-BRANCHES,upstream>>. Після цього ця гілка інтегрується в поточну гілку.

Існує 4 основні варіанти інтеграції віддаленого гілки:

1. Команда `git pull --ff-only` виконує лише оновлення перемотуванням вперед («fast-forward»): вона завершиться з помилкою, якщо ваша локальна гілка розійшлася з віддаленою гілкою. Це є стандартною поведінкою.
2. `git pull --rebase` запускає `git rebase`
3. `git pull --no-rebase` запускає `git merge`.
4. `git pull --squash` запускає `git merge --squash`

Ви також можете встановити параметри конфігурації `pull.rebase`, `pull.squash` або `pull.ff` з бажаною поведінкою.

Якщо під час злиття або ребейзу виник конфлікт, який ви не хочете розвʼязувати, ви можете безпечно перервати процес за допомогою команд `git merge --abort` або `git rebase --abort`.

ОПЦІЇ
-----

_<репозиторій>_::
	«Віддалений» ("remote") репозиторій, з якого потрібно завантажити дані. Це може бути або URL-адреса (див. розділ <<URLS,GIT URLS>> нижче), або ім’я віддаленого екземпляра (див. розділ <<REMOTES,ВІДДАЛЕНІ ЕКЗЕМПЛЯРИ>> нижче).
+
Стандартне значення — це налаштований upstream для поточної гілки або `origin`. Докладнішу інформацію про налаштування upstream див. у розділі <<UPSTREAM-BRANCHES,ВИСХІДНІ ГІЛКИ>> нижче.

_<refspec>_::
	Яку гілку або інші посилання потрібно завантажити та інтегрувати в поточну гілку, наприклад `main` у команді `git pull origin main`. Стандартним значенням є налаштований upstream для поточної гілки.
+
Це може бути гілка, тег або інший набір посилань. Повний синтаксис див. у <<fetch-refspec,_<refspec>_>> нижче в розділі «Параметри, повʼязані з вибіркою», а також у розділі <<DEFAULT-BEHAVIOUR,СТАНДАРТНА ПОВЕДІНКА>> нижче, щоб дізнатися, як `git pull` використовує цей аргумент для визначення віддаленої гілки для інтеграції.

`-q`::
`--quiet`::
	Цей параметр передається як базовій функції git-fetch для придушення повідомлень під час передачі, так і базовій функції git-merge для придушення виводу під час злиття.

`-v`::
`--verbose`::
	Передає `--verbose` до git-fetch та git-merge.

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	Цей параметр контролює, чи слід отримувати нові коміти заповнених субмодулів, а також чи слід оновлювати робочі дерева активних субмодулів (див. linkgit:git-fetch[1], linkgit:git-config[1] та linkgit:gitmodules[5]).
+
Якщо отримання виконується через перебазування, локальні коміти субмодулів також перебазуються.
+
Якщо оновлення виконується через злиття, конфлікти субмодулів розвʼязуються та перевіряються.

Параметри, повʼязані з обʼєднанням
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; перебазувати поточну гілку поверх висхідної (upsatream) гілки після отримання даних. Якщо існує гілка віддаленого відстеження, що відповідає висхідній гілці, і гілка upstream була перебазована з моменту останньої отримання даних, перебазування використовує цю інформацію, щоб уникнути перебазування нелокальних змін. Це стандартна поведінка.

`merges`;; перебазувати за допомогою `git rebase --rebase-merges`, щоб локальні коміти злиття були включені до перебазування (див. linkgit:git-rebase[1] для деталей).
`false`;; обʼєднати висхідну гілку (upstream) з поточною гілкою.
`interactive`;; увімкнути інтерактивний режим перебазування.

+
Дивіться `pull.rebase`, `branch.<name>.rebase` та `branch.autoSetupRebase` у linkgit:git-config[1], якщо ви хочете, щоб `git pull` завжди використовував `--rebase` замість злиття.
+
[NOTE]
Це потенційно _небезпечний_ режим роботи. Він переписує історію, що не віщує нічого доброго, враховуючи, що ви вже опублікували цю історію. *Не* використовуйте цю опцію, якщо ви уважно не прочитали linkgit:git-rebase[1].

`--no-rebase`::
	Це скорочення для `--rebase=false`.

Параметри, пов’язані з отриманням даних
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
СТАНДАРТНА ПОВЕДІНКА
--------------------

Часто люди використовують `git pull` без надання жодних параметрів. Традиційно це було еквівалентно використанню `git pull origin`. Однак, коли конфігурація `branch.<name>.remote` присутня у гілці `<name>`, це значення використовується замість `origin`.

Щоб визначити, з якої URL-адреси отримувати дані, використовується значення конфігурації `remote.<origin>.url`, і якщо такої змінної немає, використовується значення з рядка `URL:` у `$GIT_DIR/remotes/<origin>`.

Щоб визначити, які віддалені гілки потрібно отримати (і, за бажанням, зберегти у гілках віддаленого відстеження), коли команда виконується без будь-яких параметрів refspec у командному рядку, перевіряються значення змінної конфігурації `remote.<origin>.fetch`, а якщо таких немає, перевіряється `$GIT_DIR/remotes/<origin>` та використовуються її рядки `Pull:`. На додачу до форматів refspec, описаних у розділі ОПЦІЇ, ви можете мати шаблон refspec, який виглядає так:

------------
refs/heads/*:refs/remotes/origin/*
------------

Шаблон `<refspec>` повинен мати непусту праву частину (тобто, повинен зберігати те, що було отримано в гілках remote-tracking), і його ліва та права частини повинні закінчуватися на `/*`. Вище описано, що всі віддалені гілки відстежуються за допомогою гілок remote-tracking в ієрархії `refs/remotes/origin/` з однаковим іменем.

Правило визначення віддаленої гілки для обʼєднання після отримання даних дещо складне, щоб не порушувати зворотну сумісність.

Якщо в командному рядку команди `git pull` було вказано явні refspecs, то всі вони об’єднуються.

Якщо в командному рядку не було вказано refspec, тоді `git pull` використовує refspec з конфігурації або `$GIT_DIR/remotes/<origin>`. У таких випадках застосовуються такі правила:

. Якщо конфігурація `branch.<name>.merge` для поточної гілки _<name>_ існує, це назва гілки на віддаленому сайті, яка була обʼєднана.

. Якщо refspec є символом підстановки, об’єднання не відбувається.

. В іншому випадку віддалена гілка першого refspec обʼєднується.


ПРИКЛАДИ
--------

* Оновіть гілки віддаленого відстеження для репозиторію, з якого ви клонували, а потім обʼєднайте одну з них з вашою поточною гілкою:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
Зазвичай гілка, з якою здійснюється обʼєднання, це `HEAD` віддаленого репозиторію, але вибір визначається опціями `branch.<name>.remote` та `branch.<name>.merge`; див. linkgit:git-config[1] для отримання детальної інформації.

* Обʼєднати з поточною гілкою віддалену гілку `next`:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
Це тимчасово залишає копію `next` у `FETCH_HEAD` та оновлює гілку віддаленого відстеження `origin/next`. Те саме можна зробити, викликавши fetch та merge:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


Якщо ви спробували витягнути дані, що призвело до складних конфліктів, і хочете почати спочатку, ви можете відновити їх за допомогою `git reset`.


include::transfer-data-leaks.adoc[]

ПОМИЛКИ
-------
Наразі використання параметра `--recurse-submodules` дозволяє завантажувати лише нові коміти з уже завантажених субмодулів. Наприклад, якщо в щойно завантажених комітах суперпроєкту автори додали новий субмодуль, сам субмодуль не завантажується, що унеможливлює його подальше завантаження без повторного виконання команди fetch. Очікується, що ця проблема буде виправлена в майбутній версії Git.

ДИВ. ТАКОЖ
----------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
Частина набору linkgit:git[1]
