git-ls-remote(1)
================

НАЗВА
-----
git-ls-remote - Список посилань у віддаленому репозиторії


СИНОПСИС
--------
[verse]
'git ls-remote' [--branches] [--tags] [--refs] [--upload-pack=<exec>]
	      [-q | --quiet] [--exit-code] [--get-url] [--sort=<key>]
	      [--symref] [<repository> [<patterns>...]]

ОПИС
----
Відображає посилання, доступні у віддаленому репозиторії, разом із відповідними ідентифікаторами комітів.


ОПЦІЇ
-----
-b::
--branches::
-t::
--tags::
	Обмежтеся лише локальними гілками та локальними тегами відповідно. Ці опції _не_ є взаємовиключними; якщо задано обидва, відображаються посилання, що зберігаються в refs/heads та refs/tags. Зверніть увагу, що `--heads` та `-h` є застарілими синонімами `--branches` та `-b` і можуть бути видалені в майбутньому. Також зверніть увагу, що `git ls-remote -h`, що використовується без будь-яких інших команд у командному рядку, надає довідку, що узгоджується з іншими підкомандами git.

--refs::
	Не показуйте очищені теги або псевдопосилання, такі як `HEAD`, у виводі.

-q::
--quiet::
	Не виводити віддалену URL-адресу на stderr.

--upload-pack=<exec>::
	Вкажіть повний шлях до 'git-upload-pack' на віддаленому хості. Це дозволить переглянути посилання з репозиторіїв, доступ до яких здійснюється через SSH, і де демон SSH не використовує PATH, налаштований користувачем.

--exit-code::
	Вихід зі статусом "2", якщо у віддаленому репозиторії не знайдено відповідних посилань. Зазвичай команда завершується зі статусом "0", що вказує на успішне встановлення зв'язку з віддаленим репозиторієм, чи знайдено відповідні посилання.

--get-url::
	Розгорніть URL-адресу заданого віддаленого репозиторію, враховуючи будь-які налаштування конфігурації "url.<base>.insteadOf" (див. linkgit:git-config[1]), та вийдіть без звернення до віддаленого репозиторію.

--symref::
	Окрім об'єкта, на який вказує посилання, під час відображення символічного посилання відображати посилання, на яке вказує посилання. Наразі upload-pack показує лише symref HEAD, тому ls-remote відображатиме лише його.

--sort=<key>::
	Сортування на основі заданого ключа. Додайте префікс `-` для сортування у порядку спадання значення. Підтримує "version:refname" або "v:refname" (імена тегів обробляються як версії). Порядок сортування "version:refname" також може залежати від змінної конфігурації "versionsort.suffix". Див. linkgit:git-for-each-ref[1] для отримання додаткових параметрів сортування, але майте на увазі, що ключі, такі як `committerdate`, які потребують доступу до самих об'єктів, не працюватимуть для посилань, об'єкти яких ще не були отримані з віддаленого сервера, і видаватимуть помилку `missing object`.

-o <option>::
--server-option=<опція>::
	Передати заданий рядок на сервер під час зв'язку за протоколом версії 2. Заданий рядок не повинен містити символів NUL або LF. Якщо задано кілька `--server-option=<опція>`, усі вони надсилаються іншій стороні в порядку, зазначеному в командному рядку. Якщо `--server-option=<опція>` не задано в командному рядку, замість цього використовуються значення змінної конфігурації `remote.<назва>.serverOption`.

<repository>::
	«Віддалене» сховище для запиту. Цей параметр може бути або URL-адресою, або іменем віддаленого сховища (див. розділи GIT URLS та REMOTES у linkgit:git-fetch[1]).

<patterns>...::
	Якщо не вказано, відображаються всі посилання після фільтрації за допомогою --heads та --tags. Якщо вказано <patterns>..., відображаються лише посилання, що відповідають одному або кільком заданим шаблонам. Кожен шаблон інтерпретується як глобус (див. `glob` у linkgit:gitglossary[7]), який зіставляється з "хвостом" посилання, починаючи або з початку посилання (тому збігається повна назва, наприклад `refs/heads/foo`), або з роздільника склесної риски (тому `bar` збігається з `refs/heads/bar`, але не з `refs/heads/foobar`).

ВИХІД
-----

Вивід має формат:

------------
<oid> TAB <ref> LF
------------

Під час відображення анотованого тегу, якщо не вказано `--refs`, відображаються два такі рядки: один з назвою посилання для самого тегу як `<ref>`, а інший з `<ref>`, за яким йде `^{}`. `<oid>` в останньому рядку показує назву об'єкта, на який вказує тег.

ПРИКЛАДИ
--------

* Перелічіть усі посилання (включаючи символічні та псевдопосилання), відокремлюючи теги:
+
----
$ git ls-remote
27d43aaaf50ef0ae014b88bba294f93658016a2e	HEAD
950264636c68591989456e3ba0a5442f93152c1a	refs/heads/main
d9ab777d41f92a8c1684c91cfb02053d7dd1046b	refs/heads/next
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

* Перелічіть усі посилання, що відповідають заданим шаблонам:
+
----
$ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740	refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061	refs/heads/seen
----

* Вивести лише теги, що відповідають заданому шаблону підстановки:
+
----
$ git ls-remote --tags http://www.kernel.org/pub/scm/git/git.git v\*
485a869c64a68cc5795dd99689797c5900f4716d	refs/tags/v2.39.2
cbf04937d5b9fcf0a76c28f69e6294e9e3ecd7e6	refs/tags/v2.39.2^{}
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

ДИВ. ТАКОЖ
----------
linkgit:git-check-ref-format[1].

GIT
---
Частина набору linkgit:git[1]
