git-mailsplit(1)
================

НАЗВА
-----
git-mailsplit - Проста програма для розділення mbox у UNIX

СИНОПСИС
--------
[verse]
'git mailsplit' [-b] [-f<nn>] [-d<prec>] [--keep-cr] [--mboxrd]
		-o<directory> [--] [(<mbox>|<Maildir>)...]

ОПИС
----
Розділяє файл mbox або Maildir на список файлів: "0001" "0002" .. у вказаному каталозі, щоб ви могли обробити їх далі звідти.

IMPORTANT: Розділення Maildir залежить від сортування імен файлів для виведення патчів у правильному порядку.

ОПЦІЇ
-----
<mbox>::
	Mbox-файл для розділення. Якщо не вказано, mbox зчитується зі стандартного вводу.

<Maildir>::
	Кореневий каталог поштової директорії, яку потрібно розділити. Цей каталог має містити піддиректорії cur, tmp та new.

-o<directory>::
	Каталог, в якому розміщувати окремі повідомлення.

-b::
	Якщо будь-який файл не починається з рядка «Від», вважайте, що це окреме поштове повідомлення, а не сигналізуйте про помилку.

-d<prec>::
	Замість стандартних 4 цифр з початковими нулями, для згенерованих імен файлів можна вказати іншу точність.

-f<nn>::
	Пропустити перші <nn> цифри, наприклад, якщо вказано -f3, нумерація починається з 0004.

--keep-cr::
	Не видаляйте `\r` з рядків, що закінчуються на `\r\n`.

--mboxrd::
	Вхідні дані мають формат "mboxrd", а екранування рядка "^>+From" виконується у зворотному порядку.

GIT
---
Частина набору linkgit:git[1]
