git-log(1)
==========

НАЗВА
-----
git-log  — Перегляд журналів комітів


СИНОПСИС
--------
[synopsis]
git log [<options>] [<revision-range>] [[--] <path>...]

ОПИС
----
Показує журнали комітів.

:git-log: 1
include::rev-list-description.adoc[]

Команда використовує опції, що застосовуються до команди linkgit:git-rev-list[1], для керування тим, що і як відображається, а також опції, що застосовуються до команди linkgit:git-diff[1], для керування тим, як відображаються зміни, внесені кожним комітом.


ОПЦІЇ
-----

`--follow`::
	Продовжити перегляд історії файлу, незважаючи на зміни імені (працює лише для одного файлу).

`--no-decorate`::
`--decorate[=(short|full|auto|no)]`::
	Виводити назви посилань усіх показаних комітів. Можливі значення:
+
----
`short`;; префікси імен посилань `refs/heads/`, `refs/tags/` та
	`refs/remotes/` не відображаються.
`full`;; повне імʼя посилання (включаючи префікс) відображається.
`auto`:: якщо вивід йде в термінал, імена посилань
	відображаються так, ніби вказано `short`, інакше імена посилань
	не відображаються.
----
+
Опція `--decorate` є скороченим варіантом для `--decorate=short`. Типово використовується значення параметра `log.decorate`, якщо налаштовано, інакше `auto`.

`--decorate-refs=<pattern>`::
`--decorate-refs-exclude=<pattern>`::
	Не використовуйте для оформлення кожного потенційного посилання, якщо воно відповідає будь-якому з параметрів _<pattern>_, вказаних для `--decorate-refs-exclude`, або якщо воно не відповідає жодному з параметрів _<pattern>_, вказаних для `--decorate-refs`. Параметр конфігурації `log.excludeDecoration` дозволяє виключити посилання з оформлення, але явно вказаний шаблон `--decorate-refs` матиме пріоритет над збігом у `log.excludeDecoration`.
+
Якщо жоден із цих параметрів або налаштувань конфігурації не вказано, то посилання використовуються як декоративні елементи, якщо вони відповідають `HEAD`, `refs/heads/`, `refs/remotes/`, `refs/stash/` або `refs/tags/`.

`--clear-decorations`::
	Якщо вказано, ця опція скасовує всі попередні налаштування `--decorate-refs` або `--decorate-refs-exclude` та розширює стандартний фільтр декорування, щоб включити всі посилання. Ця опція вважається встановленою, якщо значення конфігурації `log.initialDecorationSet` встановлено на `all`.

`--source`::
	Вивести імʼя посилання, вказане в командному рядку, за допомогою якого було досягнуто кожного коміту.

`--mailmap`::
`--no-mailmap`::
`--use-mailmap`::
`--no-use-mailmap`::
	За допомогою файлу mailmap виконувати зіставлення імен авторів та авторів комітів, а також їхніх електронних адрес із канонічними справжніми іменами та електронними адресами. Див. linkgit:git-shortlog[1].

`--full-diff`::
	Без цього прапорця команда `git log -p <шлях>...` показує коміти, які зачіпають вказані шляхи, та відмінності щодо тих самих вказаних шляхів. З цим прапорцем для комітів, які зачіпають вказані шляхи, показується повний список відмінностей; це означає, що "`<шлях>...`" обмежує лише коміти, але не обмежує список відмінностей для цих комітів.
+
Зверніть увагу, що це впливає на всі типи виводу на основі diff, наприклад, ті, що створюються за допомогою `--stat` тощо.

`--log-size`::
	Включити рядок `log size <число>` у вивід для кожного коміту, де _<число>_ — це довжина повідомлення цього коміту в байтах. Призначено для пришвидшення роботи інструментів, які зчитують повідомлення журналу з виводу `git log`, надаючи їм можливість заздалегідь виділити необхідний простір.

include::line-range-options.adoc[]

_<revision-range>_::
	Показувати лише коміти у вказаному діапазоні версій. Якщо не вказано _<revision-range>_, зазвичай використовується значення `HEAD` (тобто вся історія, що веде до поточного коміту). `origin..HEAD` вказує всі коміти, доступні з поточного коміту (тобто `HEAD`), але не з `origin`. Повний список способів написання _<revision-range>_ див. у розділі «Визначення діапазонів» у linkgit:gitrevisions[7].

`[--] <path>...`::
	Показувати лише ті коміти, яких достатньо для пояснення того, як виникли файли, що відповідають зазначеним шляхам. Дивіться розділ «Спрощення історії» нижче для отримання детальної інформації та інших режимів спрощення.
+
Шляхи можуть потребувати префікса `--`, щоб відокремити їх від опцій або діапазону версій, у разі виникнення плутанини.

include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

ФОРМАТУВАННЯ DIFF
-----------------

Зазвичай, `git log` не генерує жодного виводу diff. Наведені нижче опції можна використовувати для відображення змін, внесених кожним комітом.

Зверніть увагу, що якщо явно не вказано один із варіантів `--diff-merges` (включаючи короткі опції `-m`, `-c`, `--cc` та `--dd`), коміти злиття не відображатимуть diff, навіть якщо вибрано формат різниці, такий як `--patch`, а також не відповідатимуть опціям пошуку, таким як `-S`. Винятком є випадок, коли використовується `--first-parent`, і в цьому випадку `first-parent` є стандартним форматом для комітів злиття.

:git-log: 1
:diff-merges-default: `off`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]

ПРИКЛАДИ
--------
`git log --no-merges`::

	Показати всю історію комітів, але пропустити будь-які злиття

`git log v2.6.12.. include/scsi drivers/scsi`::

	Показати всі коміти, починаючи з версії 'v2.6.12', які змінили будь-який файл у субтеках `include/scsi` або `drivers/scsi`

`git log --since="2 weeks ago" -- gitk`::

	Показати зміни за останні два тижні у файлі `gitk`. `--` необхідний, щоб уникнути плутанини з *гілкою* з назвою `gitk`

`git log --name-status release..test`::

	Показати коміти, що знаходяться у гілці "`test`", але ще не у гілці "`release`", разом зі списком шляхів, які змінює кожен коміт.

`git log --follow builtin/rev-list.c`::

	Показує коміти, що змінили `builtin/rev-list.c`, включаючи ті коміти, які відбулися до того, як файлу було надано його поточну назву.

`git log --branches --not --remotes=origin`::

	Показує всі коміти, що знаходяться в будь-якій з локальних гілок, але не в жодній з гілок віддаленого відстеження для `origin` (те, що у вас є, цього origin не відображає).

`git log master --not --remotes=*/master`::

	Показує всі коміти, які є в локальній гілці master, але відсутні в гілках master будь-якого віддаленого репозиторію.

`git log -p -m --first-parent`::

	Показує історію, включаючи порівняння змін, але лише з позиції «основної гілки», пропускаючи коміти, що походять із злитих гілок, та показуючи повні diff у результаті злиття. Це доцільно лише в разі дотримання суворої політики злиття всіх тематичних гілок при роботі в рамках єдиної гілки інтеграції.

`git log -L '/int main/',/^}/:main.c`::

	Показує, як функція `main()` у файлі `main.c` розвивалася з часом.

`git log -3`::

	Обмежує кількість комітів для відображення до 3.

ОБГОВОРЕННЯ
-----------

include::i18n.adoc[]

КОНФІГУРАЦІЯ
------------

Дивіться linkgit:git-config[1] для основних змінних та linkgit:git-diff[1] для налаштувань, повʼязаних з генерацією diff.

`format.pretty`::
	Стандартне значення для параметра `--format`. (Див. розділ «Гарні формати» вище.) Стандартне значення — `medium`.

`i18n.logOutputEncoding`::
	Кодування, яке використовуватиметься під час відображення журналів. (Див. розділ «Обговорення» вище.) Зазвичай використовується значення `i18n.commitEncoding`, якщо встановлено, та UTF-8 в іншому випадку.

include::includes/cmd-config-section-rest.adoc[]

include::config/log.adoc[]

include::config/notes.adoc[]

GIT
---
Частина набору linkgit:git[1]
