git-ls-remote(1)
================

НАЗВА
-----
git-ls-remote — Вивід переліку посилань у віддаленому репозиторії


СИНОПСИС
--------
[verse]
'git ls-remote' [--branches] [--tags] [--refs] [--upload-pack=<exec>]
	      [-q | --quiet] [--exit-code] [--get-url] [--sort=<key>]
	      [--symref] [<repository> [<patterns>...]]

ОПИС
----
Показує посилання, доступні у віддаленому репозиторії, разом із відповідними ідентифікаторами комітів.


ОПЦІЇ
-----
-b::
--branches::
-t::
--tags::
	Обмежитись лише локальними гілками та локальними тегами відповідно. Ці параметри _не_ є взаємовиключними; якщо вказати обидва, будуть показані посилання, що зберігаються в refs/heads та refs/tags. Зверніть увагу, що `--heads` та `-h` є застарілими синонімами для `--branches` та `-b` і можуть бути видалені в майбутньому. Також зверніть увагу, що `git ls-remote -h`, використаний без будь-яких інших параметрів у командному рядку, надає довідку, як і інші субкоманди git.

--refs::
	Не показувати очищені теги або псевдопосилання, такі як `HEAD`, у виводі.

-q::
--quiet::
	Не виводити віддалену URL-адресу в stderr.

--upload-pack=<exec>::
	Вкажіть повний шлях до файлу 'git-upload-pack' на віддаленому хості. Це дозволить вивести список посилань із репозиторіїв, доступ до яких здійснюється через SSH, у випадках, коли демон SSH не використовує шлях PATH, налаштований користувачем.

--exit-code::
	Вихід зі статусом "2", якщо у віддаленому репозиторії не знайдено відповідних посилань. Зазвичай команда завершується зі статусом "0", що вказує на успішне встановлення звʼязку з віддаленим репозиторієм, чи знайдено відповідні посилання.

--get-url::
	Розгорнути URL-адресу вказаного віддаленого репозиторію з урахуванням будь-яких налаштувань конфігурації типу «url.<base>.insteadOf» (див. linkgit:git-config[1]) і завершити роботу без зв’язку з віддаленим сервером.

--symref::
	Під час показу символічного посилання, крім об’єкта, на який воно вказує, слід також показувати базове посилання, на яке воно вказує. Наразі upload-pack показує лише HEAD символічного посилання, тому ls-remote також показуватиме лише його.

--sort=<key>::
	Сортування за вказаним ключем. Додайте префікс `-`, щоб сортувати значення у спадному порядку. Підтримуються формати «version:refname» або «v:refname» (імена тегів розглядаються як версії). На порядок сортування «version:refname» також може впливати змінна конфігурації «versionsort.suffix». Дивіться linkgit:git-for-each-ref[1] для додаткових опцій сортування, але майте на увазі, що ключі, такі як `committerdate`, які вимагають доступу до самих об’єктів, не працюватимуть для посилань, об’єкти яких ще не були завантажені з віддаленого сервера, і видаватимуть помилку `missing object`.

-o <опція>::
--server-option=<опція>::
	Передавати вказаний рядок на сервер під час зв’язку за допомогою протоколу версії 2. Вказаний рядок не повинен містити символів NUL або LF. Якщо вказано кілька параметрів `--server-option=<опція>`, вони всі надсилаються на інший бік у порядку, вказаному в командному рядку. Якщо в командному рядку не вказано жодного параметра `--server-option=<опція>`, замість них використовуються значення змінної конфігурації `remote.<назва>.serverOption`.

<repository>::
	«Віддалений» репозиторій, до якого потрібно виконати запит. Цей параметр може бути або URL-адресою, або іменем віддаленого репозиторію (див. розділи «GIT URLS» та «REMOTES» у документації linkgit:git-fetch[1]).

<patterns>...::
	Якщо параметр не вказано, показуються всі посилання після фільтрації за допомогою опцій --heads та --tags. Якщо вказано <patterns>..., показуються лише посилання, що відповідають одному або кільком із заданих шаблонів. Кожен шаблон інтерпретується як глоб (див. `glob` у linkgit:gitglossary[7]), який порівнюється з «хвостом» посилання, починаючи або з початку посилання (тобто збігається повне ім’я, таке як `refs/heads/foo`), або з розділювача у вигляді скісної риски (тобто `bar` збігається з `refs/heads/bar`, але не з `refs/heads/foobar`).

ВИВІД
-----

Вивід має формат:

------------
<oid> TAB <ref> LF
------------

Під час показцу анотованого тегу, якщо не вказано `--refs`, виводяться два такі рядки: один з назвою посилання для самого тегу як `<ref>`, а інший з `<ref>`, за яким йде `^{}`. `<oid>` в останньому рядку показує назву обʼєкта, на який вказує тег.

ПРИКЛАДИ
--------

* Виводить всі посилання (включно з символічними та псевдопосиланнями), видаливши теги:
+
----
$ git ls-remote
27d43aaaf50ef0ae014b88bba294f93658016a2e	HEAD
950264636c68591989456e3ba0a5442f93152c1a	refs/heads/main
d9ab777d41f92a8c1684c91cfb02053d7dd1046b	refs/heads/next
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

* Виводить усі посилання, що відповідають заданим шаблонам:
+
----
$ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740	refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061	refs/heads/seen
----

* Виводить лише теги, що відповідають заданому шаблону з символами-замінниками:
+
----
$ git ls-remote --tags http://www.kernel.org/pub/scm/git/git.git v\*
485a869c64a68cc5795dd99689797c5900f4716d	refs/tags/v2.39.2
cbf04937d5b9fcf0a76c28f69e6294e9e3ecd7e6	refs/tags/v2.39.2^{}
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

ДИВ. ТАКОЖ
----------
linkgit:git-check-ref-format[1].

GIT
---
Частина набору linkgit:git[1]
