git-bugreport(1)
================

НАЗВА
-----
git-bugreport - Збирати інформацію для користувача, щоб він міг подавати звіт про помилку

СИНОПСИС
--------
[verse]
'git bugreport' [(-o | --output-directory) <path>]
		[(-s | --suffix) <format> | --no-suffix]
		[--diagnose[=<mode>]]

ОПИС
----
Збирає інформацію про машину користувача, клієнта Git та стан репозиторію, а також форму запиту інформації про поведінку, яку спостерігав користувач, та зберігає її в одному текстовому файлі, яким користувач потім може поділитися, наприклад, зі списком розсилки Git, щоб повідомити про виявлену помилку.

У користувача запитується наступна інформація:

 - Етапи розмноження
 - Очікувана поведінка
 - Фактична поведінка

Наступна інформація фіксується автоматично:

 - 'git version --build-options'
 - uname рядки sysname, release, version та machine
 - Специфічний для компілятора інформаційний рядок
 - Список увімкнених хуків
 - $SHELL

Додаткову інформацію можна зібрати в окремий zip-архів за допомогою опції `--diagnose`, а також додати до документа зі звітом про помилку, щоб надати читачам додатковий контекст.

Цей інструмент викликається через типовий процес налаштування Git, а це означає, що в деяких випадках він може не запуститися, наприклад, якщо відповідний файл конфігурації нечитабельний. У такому випадку може бути корисним вручну зібрати перелічену вище інформацію, коли ви вручну звертаєтесь за допомогою.

ОПЦІЇ
-----
-o <path>::
--output-directory <path>::
	Помістіть отриманий файл звіту про помилку в `<шлях>` замість поточного каталогу.

-s <format>::
--suffix <format>::
--no-suffix::
	Вкажіть альтернативний суфікс для назви звіту про помилку, щоб створити файл з назвою 'git-bugreport-<formatted-suffix>'. Він має мати форму рядка формату strftime(3); буде використано поточний місцевий час. `--no-suffix` вимикає суфікс, і файл буде називатися просто `git-bugreport` без будь-яких заходів узгодження.

--no-diagnose::
--diagnose[=<mode>]::
	Створіть zip-архів додаткової інформації про комп’ютер користувача, клієнт Git та стан репозиторію. Архів записується в той самий вихідний каталог, що й звіт про помилку, і має назву «git-diagnostics-<форматований-суфікс>».
+
Якщо не вказано `mode`, діагностичний архів міститиме набір статистики за замовчуванням, що повідомляється `git diagnose`. Можна вказати необов'язкове значення `mode`, щоб змінити, яка інформація включається до архіву. Див. linkgit:git-diagnose[1] для списку допустимих значень для `mode` та деталей щодо їх використання.

GIT
---
Частина набору linkgit:git[1]
