git-pull(1)
===========

НАЗВА
-----
git-pull - Отримання даних з іншого репозиторію або локальної гілки та інтеграція з ними


СИНОПСИС
--------
[synopsis]
git pull [<options>] [<repository> [<refspec>...]]


ОПИС
----

Інтегрувати зміни з віддаленого репозиторію в поточну гілку.

Спочатку `git pull` запускає `git fetch` з тими ж аргументами (за винятком опцій злиття) для отримання віддалених гілок. Потім він вирішує, яку віддалену гілку інтегрувати: якщо ви запустите `git pull` без аргументів, це за замовчуванням використовуватиме <<UPSTREAM-BRANCHES,upstream>> для поточної гілки. Потім він інтегрує цю гілку в поточну гілку.

Існує 4 основні варіанти інтеграції віддаленої філії:

1. `git pull --ff-only` виконуватиме лише оновлення "вперед": це не вдасться, якщо ваша локальна гілка відійшла від віддаленої гілки. Це значення за замовчуванням.
2. `git pull --rebase` запускає `git rebase`
3. `git pull --no-rebase` запускає `git merge`.
4. `git pull --squash` запускає `git merge --squash`

Ви також можете встановити параметри конфігурації `pull.rebase`, `pull.squash` або `pull.ff` з бажаною поведінкою.

Якщо під час злиття або перебазування виник конфлікт злиття, який ви не хочете обробляти, ви можете безпечно перервати його за допомогою `git merge --abort` або `git --rebase abort`.

ОПЦІЇ
-----

_<репозиторій>_::
	«Віддалене» сховище для вилучення. Це може бути або URL-адреса (див. розділ <<URLS, GIT URLs>> нижче), або назва віддаленого сховища (див. розділ <<REMOTES,REMOTES>> нижче).
+
За замовчуванням використовується налаштований вихідний ланцюжок для поточної гілки або `origin`. Див. <<UPSTREAM-BRANCHES,UPSTREAM BRANCHES>> нижче для отримання додаткової інформації про налаштування вихідних ланцюжків.

_<refspec>_::
	Яку гілку або інші посилання отримати та інтегрувати в поточну гілку, наприклад `main` у `git pull origin main`. За замовчуванням використовується налаштований upstream для поточної гілки.
+
Це може бути гілка, тег або інша колекція посилань. Повний синтаксис див. у <<fetch-refspec,_<refspec>_>> нижче в розділі "Параметри, пов'язані з вибіркою", а також у <<DEFAULT-BEHAVIOUR,DEFAULT BEHAVIOUR>> нижче, щоб дізнатися, як `git pull` використовує цей аргумент для визначення віддаленої гілки для інтеграції.

`-q`::
`--quiet`::
	Це передається як базовому git-fetch для приглушення звітів під час передачі, так і базовому git-merge для приглушення виводу під час злиття.

`-v`::
`--verbose`::
	Передайте `--verbose` до git-fetch та git-merge.

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	Цей параметр контролює, чи слід отримувати нові коміти заповнених підмодулів, а також чи слід оновлювати робочі дерева активних підмодулів (див. linkgit:git-fetch[1], linkgit:git-config[1] та linkgit:gitmodules[5]).
+
Якщо отримання виконується через перебазування, локальні коміти підмодулів також перебазуються.
+
Якщо оновлення виконується через злиття, конфлікти підмодулів вирішуються та перевіряються.

Варіанти, пов'язані з об'єднанням
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; перебазувати поточну гілку поверх гілки вище за течією після отримання даних. Якщо існує гілка віддаленого відстеження, що відповідає гілці вище за течією, і гілка вище за течією була перебазована з моменту останньої отримання даних, перебазування використовує цю інформацію, щоб уникнути перебазування нелокальних змін. Це значення за замовчуванням.

`merges`;; перебазувати за допомогою `git rebase --rebase-merges`, щоб локальні коміти злиття були включені до перебазування (див. linkgit:git-rebase[1] для деталей).
`false`;; об'єднати гілку вище за течією з поточною гілкою.
`interactive`;; увімкнути інтерактивний режим перебазування.

+
Дивіться `pull.rebase`, `branch.<name>.rebase` та `branch.autoSetupRebase` у linkgit:git-config[1], якщо ви хочете, щоб `git pull` завжди використовував `--rebase` замість злиття.
+
[NOTE]
Це потенційно _небезпечний_ режим роботи. Він переписує історію, що не віщує нічого доброго, враховуючи, що ви вже опублікували цю історію. *Не* використовуйте цю опцію, якщо ви уважно не прочитали linkgit:git-rebase[1].

`--no-rebase`::
	Це скорочено для `--rebase=false`.

Параметри, пов'язані з вилученням
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
ПОВЕДІНКА ЗА ЗАМОВЧАННЯМ
------------------------

Часто люди використовують `git pull` без надання жодних параметрів. Традиційно це було еквівалентно використанню `git pull origin`. Однак, коли конфігурація `branch.<name>.remote` присутня на гілці `<name>`, це значення використовується замість `origin`.

Щоб визначити, з якої URL-адреси отримувати дані, використовується значення конфігурації `remote.<origin>.url`, і якщо такої змінної немає, використовується значення з рядка `URL:` у `$GIT_DIR/remotes/<origin>`.

Щоб визначити, які віддалені гілки потрібно отримати (і, за бажанням, зберегти у гілках віддаленого відстеження), коли команда виконується без будь-яких параметрів refspec у командному рядку, перевіряються значення змінної конфігурації `remote.<origin>.fetch`, а якщо таких немає, перевіряється `$GIT_DIR/remotes/<origin>` та використовуються її рядки `Pull:`. На додаток до форматів refspec, описаних у розділі OPTIONS, ви можете мати глобальну refspec, яка виглядає так:

------------
refs/heads/*:refs/remotes/origin/*
------------

Глобальна специфікація посилань повинна мати непорожній правий зріз (тобто повинна зберігати дані, отримані у гілках віддаленого відстеження), а його лівий зріз та правий зріз повинні закінчуватися на `/*`. Вищезазначене вказує, що всі віддалені гілки відстежуються за допомогою гілок віддаленого відстеження в ієрархії `refs/remotes/origin/` під однаковою назвою.

Правило визначення віддаленої гілки для об'єднання після отримання даних дещо складне, щоб не порушувати зворотну сумісність.

Якщо в командному рядку `git pull` було задано явні специфікації посилань, усі вони об'єднуються.

Якщо в командному рядку не було вказано специфікацію посилання (refspec), тоді `git pull` використовує специфікацію посилання з конфігурації або `$GIT_DIR/remotes/<origin>`. У таких випадках застосовуються такі правила:

. Якщо конфігурація `branch.<name>.merge` для поточної гілки `<name>` існує, це назва гілки на віддаленому сайті, яка об'єднується.

. Якщо специфікація посилань є глобальною, нічого не об'єднується.

. В іншому випадку віддалена гілка першої специфікації посилань об'єднується.


ПРИКЛАДИ
--------

* Оновіть гілки віддаленого відстеження для репозиторію, з якого ви клонували, а потім об'єднайте одну з них з вашою поточною гілкою:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
Зазвичай гілка, в яку здійснюється об'єднання, є HEAD віддаленого репозиторію, але вибір визначається опціями branch.<name>.remote та branch.<name>.merge; див. linkgit:git-config[1] для отримання детальної інформації.

* Об'єднати з поточною гілкою віддалену гілку `next`:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
Це тимчасово залишає копію `next` у FETCH_HEAD та оновлює гілку віддаленого відстеження `origin/next`. Те саме можна зробити, викликавши fetch та merge:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


Якщо ви спробували витягнути дані, що призвело до складних конфліктів, і хочете почати спочатку, ви можете відновити їх за допомогою 'git reset'.


include::transfer-data-leaks.adoc[]

ПОМИЛКИ
-------
Використання --recurse-submodules може отримувати нові коміти лише у вже отриманих підмодулях на даний момент. Наприклад, коли основний розробник додає новий підмодуль у щойно отримані коміти суперпроекту, сам підмодуль не може бути отриманий, що унеможливлює отримання цього підмодуля пізніше без необхідності повторного виконання отримання. Очікується, що це буде виправлено в майбутній версії Git.

ДИВ. ТАКОЖ
----------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
Частина набору linkgit:git[1]
