git-diff(1)
===========

НАЗВА
-----
git-diff — Показує зміни між комітами, комітом та робочим деревом тощо


СИНОПСИС
--------
[synopsis]
git diff [<options>] [<commit>] [--] [<path>...]
git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]
git diff [<options>] [--merge-base] <commit> [<commit>...] <commit> [--] [<path>...]
git diff [<options>] <commit>...<commit> [--] [<path>...]
git diff [<options>] <blob> <blob>
git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]

ОПИС
----
Показує зміни між робочим деревом та індексом або деревом, зміни між індексом та деревом, зміни між двома деревами, зміни, що виникли в результаті злиття, зміни між двома об’єктами blob або зміни між двома файлами на диску.

`git diff [<options>] [--] [<path>...]`::

	Ця форма призначена для перегляду змін, які ви внесли відносно індексу (область проміжного зберігання для наступного коміту). Іншими словами, відмінності — це те, що ви _могли б_ сказати Git додати до індексу, але досі цього не зробили. Ви можете додати ці зміни до stage, використовуючи linkgit:git-add[1].

`git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]`::

	Ця форма призначена для порівняння двох заданих шляхів у файловій системі. Ви можете пропустити опцію `--no-index`, якщо ви виконуєте команду в робочому дереві, контрольованому Git, і принаймні один зі шляхів вказує за межі робочого дерева, або якщо ви виконуєте команду за межами робочого дерева, контрольованого Git. Ця форма передбачає `--exit-code`. Якщо обидва шляхи вказують на теки, можна надати додаткові специфікації шляхів. Вони обмежать файли, що входять до diff. Усі такі специфікації шляхів мають бути відносними, оскільки вони застосовуються до обох сторін diff.

`git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]`::

	Ця форма призначена для перегляду змін, які ви проіндексували для наступного коміту відносно вказаного _<commit>_. Зазвичай вам потрібно порівняти їх з останнім комітом, тому, якщо ви не вкажете _<commit>_, зазвичай використовується значення `HEAD`. Якщо `HEAD` не існує (наприклад, ненароджені гілки) і _<commit>_ не вказано, буде показано всі проіндексовані зміни. `--staged` є синонімом `--cached`.
+
Якщо вказано `--merge-base`, замість _<commit>_ використовується база злиття _<commit>_ та `HEAD`. `git diff --cached --merge-base A` еквівалентно `git diff --cached $(git merge-base A HEAD)`.

`git diff [<options>] [--merge-base] <commit> [--] [<path>...]`::

	Ця форма призначена для перегляду змін у вашому робочому дереві відносно вказаного _<commit>_. Ви можете використовувати `HEAD` для порівняння його з останнім комітом або назву гілки для порівняння з вершиною іншої гілки.
+
Якщо вказано `--merge-base`, замість _<commit>_ використовується база злиття _<commit>_ та `HEAD`. `git diff --merge-base A` еквівалентно `git diff $(git merge-base A HEAD)`.

`git diff [<options>] [--merge-base] <commit> <commit> [--] [<path>...]`::

	Використовується для перегляду змін між двома довільними _<commit>_.
+
Якщо вказано `--merge-base`, використовується база злиття двох комітів для сторони "до". `git diff --merge-base A B` еквівалентно `git diff $(git merge-base A B) B`.

`git diff [<options>] <commit> <commit>...<commit> [--] [<path>...]`::

	Ця форма призначена для перегляду результатів коміту злиття. Перший у списку _<commit>_ має бути самим комітом злиття; решта два або більше комітів повинні бути його батьківськими. Зручними способами створення бажаного набору ревізій є використання суфіксів `@` та `^!`. Якщо `A` є комітом злиття, то `git diff A A^@`, `git diff A^!` та `git show A` дають однакові обʼєднані відмінності.

`git diff [<options>] <commit>..<commit> [--] [<path>...]`::

	Є синонім попередньої форми (без `..`) для перегляду змін між двома довільними _<commit>_. Якщо _<commit>_ з одного боку пропустити, це матиме той самий ефект, що й використання `HEAD` замість цього.

`git diff [<options>] <commit>...<commit> [--] [<path>...]`::

	Ця форма призначена для перегляду змін у гілці, що містить _<commit>_ і аж до другого _<commit>_, починаючи зі спільного предка обох _<commit>_. `git diff A...B` еквівалентно `git diff $(git merge-base A B) B`. Ви можете пропустити будь-який з _<commit>_, що матиме той самий ефект, що й використання `HEAD`.

Якщо ви робите щось екзотичне, слід зазначити, що всі _<commit>_ у наведеному вище описі, за винятком випадку `--merge-base` та двох останніх форм, які використовують нотації `..`, можуть бути будь-якими _<tree>_. Дерево, що нас цікавить, це те, на яке вказує посилання з назвою `AUTO_MERGE`, яке записується стратегією злиття `ort` після виникнення конфліктів злиття (див. linkgit:git-merge[1]). Порівняння робочого дерева з `AUTO_MERGE` показує зміни, які ви внесли до цього часу для вирішення текстових конфліктів (див. приклади нижче).

Для отримання повнішого списку способів написання _<commit>_ див. розділ "ВИЗНАЧЕННЯ РЕВІЗІЙ" у linkgit:gitrevisions[7]. Однак, `diff` стосується порівняння двох _кінцевих точок_, а не діапазонів, а позначення діапазонів (`<commit>..<commit>` та `<commit>...<commit>`) не означають діапазон, як визначено в розділі "ВИЗНАЧЕННЯ ДІАПАЗОНІВ" у linkgit:gitrevisions[7].

`git diff [<options>] <blob> <blob>`::

	Ця форма призначена для перегляду відмінностей між необробленим вмістом двох blob-обʼєктів.

ОПЦІЇ
-----
:git-diff: 1
include::diff-options.adoc[]

`-1`::
`--base`::
`-2`::
`--ours`::
`-3`::
`--theirs`::
	Порівняння робочого дерева з
+
--
 * "базовою" версією (stage #1) при використанні `-1` або `--base`,
 * "нашою гілкою" (stage #2) при використанні `-2` або `--ours`, або
 * "їх гілкою" (stage #3) при використанні `-3` або `--theirs`.
--
+
Індекс містить ці етапи лише для необʼєднаних записів, тобто під час вирішення конфліктів. Див. розділ linkgit:git-read-tree[1] "3-стороннє обʼєднання" для отримання детальної інформації.

`-0`::
	Оминути вивід diff для необʼєднаних записів та показати лише "Не обʼєднано". Можна використовувати лише під час порівняння робочого дерева з індексом.

`<шлях>...`::
	Параметри _<шлях>_, якщо їх задано, використовуються для обмеження відмінностей (diff) до вказаних шляхів (ви можете вказати імена тек та отримати відмінності для всіх файлів у них).


include::diff-format.adoc[]

ПРИКЛАДИ
--------

Різні способи перевірки робочого дерева::
+
------------
$ git diff            <1>
$ git diff --cached   <2>
$ git diff HEAD       <3>
$ git diff AUTO_MERGE <4>
------------
+
<1> Зміни в робочому дереві ще не підготовлені для наступного коміту.
<2> Зміни між індексом та вашим останнім комітом; що ви б зафіксували, якби запустили `git commit` без опції `-a`.
<3> Зміни в робочому дереві з моменту вашого останнього коміту; що ви б зафіксували, якби запустили `git commit -a`
<4> Зміни в робочому дереві, які ви внесли для вирішення текстових конфліктів на даний момент.

Порівняння з довільними коммітами::
+
------------
$ git diff test            <1>
$ git diff HEAD -- ./test  <2>
$ git diff HEAD^ HEAD      <3>
------------
+
<1> Замість використання вершини поточної гілки, порівняння з вершиною гілки «test».
<2> Замість порівняння з вершиною гілки "test", порівняння з вершиною поточної гілки, але тільки для файлу "test".
<3> Порівняння версії перед останнім комітом та останнім комітом.

Порівняння гілок::
+
------------
$ git diff topic master    <1>
$ git diff topic..master   <2>
$ git diff topic...master  <3>
------------
+
<1> Зміни між вершинами гілок topic та master.
<2> Те саме, що й вище.
<3> Зміни, що відбулися в гілці master з моменту відгалуження гілки topic.

Обмеження виводу diff::
+
------------
$ git diff --diff-filter=MRC            <1>
$ git diff --name-status                <2>
$ git diff arch/i386 include/asm-i386   <3>
------------
+
<1> Показує лише модифікацію, перейменування та копіювання, але не додавання чи видалення.
<2> Показує лише назви та природу змін, але не фактичний вивід diff.
<3> Обмежує вивід diff вказаними субдеревами.

Обробка виводу diff::
+
------------
$ git diff --find-copies-harder -B -C  <1>
$ git diff -R                          <2>
------------
+
<1> Витрачати додаткові цикли на пошук перейменованих файлів, копій та повністю переписаних файлів (це дуже витратно по ресурсах).
<2> Виводить diff у зворотньому порядку.

КОНФІГУРАЦІЯ
------------

include::includes/cmd-config-section-all.adoc[]

:git-diff: 1
include::config/diff.adoc[]

ДИВ. ТАКОЖ
----------
`diff`(1), linkgit:git-difftool[1], linkgit:git-log[1], linkgit:gitdiffcore[7], linkgit:git-format-patch[1], linkgit:git-apply[1], linkgit:git-show[1]

GIT
---
Частина набору linkgit:git[1]
