git-web{litdd}browse(1)
=======================

НАЗВА
-----
git-web--browse - Допоміжний скрипт Git для запуску веббраузера

СИНОПСИС
--------
[verse]
'git web{litdd}browse' [<options>] (<URL>|<file>)...

ОПИС
----

Цей скрипт намагається, наскільки це можливо, відображати URL-адреси та ФАЙЛИ, що передаються як аргументи, у вигляді HTML-сторінок у нових вкладках уже відкритого веб-браузера.

Наразі підтримуються такі браузери (або команди):

* firefox (це налаштування за замовчуванням у X Window, коли KDE не використовується)
* крижана ласка
* морська мавпа
* льодяна мавпа
* chromium (також підтримується як chromium-browser)
* google-chrome (також підтримується як chrome)
* konqueror (це стандартна версія в KDE, див. «Примітка щодо konqueror» нижче)
* опера
* w3m (це зовнішнє графічне середовище за замовчуванням)
* посилання
* посилання
* рись
* dillo
* відкрити (це налаштування за замовчуванням у графічному інтерфейсі Mac OS X)
* початок (це значення за замовчуванням у MinGW)
* cygstart (це значення за замовчуванням у Cygwin)
* xdg-open

Також можна вказати власні команди.

ОПЦІЇ
-----
-b <browser>::
--browser=<browser>::
	Використовуйте вказаний браузер. Він має бути у списку підтримуваних браузерів.

-t <browser>::
--tool=<browser>::
	Те саме, що й вище.

-c <conf.var>::
--config=<conf.var>::
	CONF.VAR шукається у конфігураційних файлах Git. Якщо його встановлено, то його значення вказує на браузер, який слід використовувати.

ЗМІННІ КОНФІГУРАЦІЇ
-------------------

CONF.VAR (з опції -c) та web.browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Веббраузер можна вказати за допомогою змінної конфігурації, що передається з параметром командного рядка -c (або --config), або змінної конфігурації `web.browser`, якщо перша не використовується.

browser.<tool>.path
~~~~~~~~~~~~~~~~~~~

Ви можете явно вказати повний шлях до потрібного вам браузера, встановивши змінну конфігурації `browser.<tool>.path`. Наприклад, ви можете налаштувати абсолютний шлях до Firefox, встановивши 'browser.firefox.path'. В іншому випадку, 'git web{litdd}browse' припускатиме, що інструмент доступний у PATH.

browser.<tool>.cmd
~~~~~~~~~~~~~~~~~~

Якщо браузер, вказаний опціями або змінними конфігурації, не входить до числа підтримуваних, тоді буде виконано пошук у відповідній змінній конфігурації `browser.<tool>.cmd`. Якщо ця змінна існує, то 'git web{litdd}browse' трактуватиме вказаний інструмент як користувацьку команду та використовуватиме shell eval для виконання команди з URL-адресами, переданими як аргументи.

ПРИМІТКА ПРО KONQUEROR
----------------------

Коли «konqueror» вказано параметром командного рядка або змінною конфігурації, ми запускаємо «kfmclient», щоб спробувати відкрити сторінку довідки HTML у вже відкритому konqueror у новій вкладці, якщо це можливо.

Для узгодженості ми також пробуємо такий трюк, якщо для 'browser.konqueror.path' встановлено значення на кшталт `A_PATH_TO/konqueror`. Це означає, що ми спробуємо запустити `A_PATH_TO/kfmclient`.

Якщо ви дійсно хочете використовувати «konqueror», то можете використати щось на кшталт наступного:

------------------------------------------------
	[web]
		browser = konq

	[browser "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

Примітка про git-config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Зверніть увагу, що ці змінні конфігурації, ймовірно, слід встановити за допомогою прапорця `--global`, наприклад, ось так:

------------------------------------------------
$ git config --global web.browser firefox
------------------------------------------------

оскільки вони, ймовірно, більше залежать від користувача, ніж від репозиторію. Див. linkgit:git-config[1] для отримання додаткової інформації про це.

GIT
---
Частина набору linkgit:git[1]
