git-symbolic-ref(1)
===================

НАЗВА
-----
git-symbolic-ref - Читання, зміна та видалення символічних посилань

СИНОПСИС
--------
[verse]
'git symbolic-ref' [-m <reason>] <name> <ref>
'git symbolic-ref' [-q] [--short] [--no-recurse] <name>
'git symbolic-ref' --delete [-q] <name>

ОПИС
----
За наявності одного аргументу зчитує, на яку гілку посилається задане символічне посилання, та виводить її шлях відносно каталогу `.git/`. Зазвичай, щоб побачити, на якій гілці знаходиться ваше робоче дерево, потрібно вказати `HEAD`.

За наявності двох аргументів створює або оновлює символічне посилання <name>, щоб воно вказувало на задану гілку <ref>.

Враховуючи `--delete` та додатковий аргумент, видаляє задане символічне посилання.

Символічне посилання — це звичайний файл, який зберігає рядок, що починається з `ref: refs/`. Наприклад, ваш `.git/HEAD` — це звичайний файл, вміст якого — `ref: refs/heads/master`.

ОПЦІЇ
-----

-d::
--delete::
	Видалити символічне посилання <назва>.

-q::
--quiet::
	Не видавати повідомлення про помилку, якщо <name> не є символічним посиланням, а є відокремленим HEAD; натомість вийдіть із ненульовим статусом без жодних зусиль.

--short::
	Під час відображення значення <name> як символічного посилання, спробуйте скоротити його, наприклад, з `refs/heads/master` на `master`.

--recurse::
--no-recurse::
	Під час відображення значення <name> як символічного посилання, якщо <name> посилається на інше символічне посилання, слід дотримуватися такого ланцюжка символічних посилань, доки результат більше не вказуватиме на символічне посилання (`--recurse`, що є значенням за замовчуванням). `--no-recurse` зупиняється після розіменування лише одного рівня символічного посилання.

-m::
	Оновіть журнал посилань для <назва> за допомогою <причина>. Це дійсне лише під час створення або оновлення символічного посилання.

НОТАТКИ
-------
У минулому `.git/HEAD` було символічним посиланням, що вказувало на `refs/heads/master`. Коли ми хотіли перейти до іншої гілки, ми виконували `ln -sf refs/heads/newbranch .git/HEAD`, а коли ми хотіли дізнатися, на якій гілці ми знаходимося, ми виконували `readlink .git/HEAD`. Але символічні посилання не є повністю портативними, тому зараз вони застарілі, і символічні посилання (як описано вище) використовуються за замовчуванням.

'git symbolic-ref' завершиться зі статусом 0, якщо вміст символічного посилання було виведено правильно, зі статусом 1, якщо запитуване ім'я не є символічним посиланням, або 128, якщо виникла інша помилка.

ДИВ. ТАКОЖ
----------
linkgit:git-update-ref[1]

GIT
---
Частина набору linkgit:git[1]
