git-prune(1)
============

НАЗВА
-----
git-prune — Очищення всіх недоступних обʼєктів з бази даних обʼєктів


СИНОПСИС
--------
[verse]
'git prune' [-n] [-v] [--progress] [--expire <time>] [--] [<head>...]

ОПИС
----

NOTE: У більшості випадків користувачам слід виконати 'git gc', що викликає 'git prune'. Див. розділ «ПРИМІТКИ» нижче.

Ця команда виконує 'git fsck --unreachable', використовуючи всі посилання, доступні в `refs/`, за бажанням з додатковим набором обʼєктів, зазначеним у командному рядку, та видаляє всі незапаковані обʼєкти, недоступні для будь-якого з цих головних обʼєктів з бази даних обʼєктів. Крім того, вона видаляє незапаковані обʼєкти, які також знаходяться в пакунках, за допомогою команди 'git prune-packed'. Вона також видаляє записи з .git/shallow, які недоступні для жодного посилання.

Зверніть увагу, що недоступні, упаковані обʼєкти залишаться. Якщо це небажано, див. linkgit:git-repack[1].

ОПЦІЇ
-----

-n::
--dry-run::
	Нічого не видаляє; лише показує те що буде видалено.

-v::
--verbose::
	Повідомити про всі видалені обʼєкти.

--progress::
	Показувати прогрес.

--expire <time>::
	Видаляти лише неупорядковані об’єкти, вік яких перевищує <time>.

\--::
	Не інтерпретує жодних додаткових аргументів як опції.

<head>...::
	Окрім обʼєктів, досяжних з будь-якого з наших посилань, зберегти обʼєкти, досяжні з перелічених <head>.

ПРИКЛАДИ
--------

Щоб видалити обʼєкти, які не використовуються вашим репозиторієм або іншим, що запозичує дані з вашого репозиторію через його `.git/objects/info/alternates`:

------------
$ git prune $(cd ../another && git rev-parse --all)
------------

ПРИМІТКИ
--------

У більшості випадків користувачам не потрібно буде викликати 'git prune' безпосередньо, а натомість варто викликати команду 'git gc', що виконує очищення разом з багатьма іншими завданнями з обслуговування.

Опис обʼєктів, які розглядаються для очищення, дивіться у параметрі --unreachable у 'git fsck'.

ДИВ. ТАКОЖ
----------

linkgit:git-fsck[1], linkgit:git-gc[1], linkgit:git-reflog[1]

GIT
---
Частина набору linkgit:git[1]
