git-fetch(1)
============

НАЗВА
-----
git-fetch — Завантаження обʼєктів та посилань з іншого репозиторію


СИНОПСИС
--------
[synopsis]
git fetch [<options>] [<repository> [<refspec>...]]
git fetch [<options>] <group>
git fetch --multiple [<options>] [(<repository>|<group>)...]
git fetch --all [<options>]


ОПИС
----
Завантажує гілки та/або теги (разом — «refs») з одного або декількох інших репозиторіїв разом з об’єктами, необхідними для відновлення їхньої історії. Гілки з віддаленим відстеженням оновлюються (щодо способів керування цією поведінкою див. опис _<refspec>_ нижче).

Як правило, будь-який тег, що вказує на гілки, які завантажуються, також завантажується; це дозволяє завантажити теги, що вказують на гілки, які вас цікавлять. Цю стандартну поведінку можна змінити за допомогою опцій `--tags` або `--no-tags` або шляхом налаштування параметра `remote.<name>.tagOpt`. Використовуючи refspec, який явно завантажує теги, ви також можете завантажити теги, що не вказують на гілки, які вас цікавлять.

Команда `git fetch` може завантажувати дані як з одного репозиторію, вказаного за назвою або URL-адресою, так і з декількох репозиторіїв одночасно, якщо вказано _<group>_ і у файлі конфігурації є запис `remotes.<group>`. (Див. linkgit:git-config[1]).

Якщо не вказано жодного віддаленого репозиторію, як правило, буде використовуватися віддалений репозиторій `origin`, за винятком випадків, коли для поточної гілки налаштована гілка upstream.

Імена ref, які було завантажено, разом з іменами об’єктів, на які вони вказують, записуються у файл `.git/FETCH_HEAD`. Ця інформація може використовуватися скриптами або іншими командами Git, такими як linkgit:git-pull[1].

ОПЦІЇ
-----
include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

`--stdin`::
	Окрім аргументів, що передаються у командному рядку, зчитує refspecs по одному в кожному рядку зі стандартного вводу. Формат «tag _<name>_» не підтримується.

include::urls-remotes.adoc[]

[[CRTB]]
НАЛАШТОВАНІ ГІЛКИ ВІДДАЛЕНОГО ВІДСТЕЖЕННЯ
-----------------------------------------

Ви часто взаємодієте з одним і тим самим віддаленим репозиторієм, регулярно та неодноразово завантажуючи з нього дані. Щоб відстежувати стан такого віддаленого репозиторію, команда `git fetch` дозволяє налаштувати змінні конфігурації `remote.<repository>.fetch`.

Зазвичай така змінна може виглядати так:

------------------------------------------------
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
------------------------------------------------

Ця конфігурація використовується двома способами:

* Коли команда `git fetch` виконується без зазначення гілок та/або тегів для завантаження в командному рядку, наприклад `git fetch origin` або `git fetch`, як refspecs використовуються значення `remote.<repository>.fetch` — вони визначають, які посилання завантажувати та які локальні посилання оновлювати. У наведеному вище прикладі будуть завантажені всі гілки, що існують в `origin` (тобто будь-які ref, що відповідають лівій частині значення, `refs/heads/*`) та оновлені відповідні гілки віддаленого відстеження в ієрархії `refs/remotes/origin/*`.

* Коли команда `git fetch` виконується з явно вказаними гілками та/або тегами для завантаження в командному рядку, наприклад `git fetch origin master`, то саме _<refspec>_, вказані в командному рядку, визначають, що саме потрібно завантажити (наприклад, `master` у прикладі, що є скороченим варіантом `master:`, що своєю чергою, означає «завантажити гілку `master`, але я явно не вказую, яку гілку віддаленого відстеження оновлювати нею з командного рядка»), і команда з прикладу завантажить _лише_ гілку `master`. Значення `remote.<repository>.fetch` визначають, яка гілка віддаленого відстеження, якщо така є, оновлюється. При такому використанні значення `remote.<repository>.fetch` не впливають на рішення, _що_ завантажується (тобто ці значення не використовуються як refspecs, коли командний рядок перелічує refspecs); вони використовуються лише для визначення, _де_ зберігаються завантажені refs, діючи як зіставлення.

Останнє використання значень `remote.<repository>.fetch` можна перевизначити, надавши параметр(и) `--refmap=<refspec>` у командному рядку.

ОЧИЩЕННЯ
--------

Git має стандартну настройку, згідно з якою дані зберігаються, якщо їх явно не видалити; це стосується також збереження локальних посилань на гілки на віддалених серверах, які самі вже видалили ці гілки.

Якщо дозволити цим застарілим посиланням накопичуватися, вони можуть погіршити продуктивність великих і активних репозиторіїв, де відбувається часта зміна гілок, і, наприклад, зробити вивід команд на кшталт `git branch -a --contains <commit>` надмірно розлогим, а також вплинути на будь-які інші процеси, що працюють із повним набором відомих посилань.

Ці посилання на віддалене відстеження можна одноразово видалити за допомогою одного з цих способів:

------------------------------------------------
# Під час завантаження
$ git fetch --prune <name>

# Тільки очистити, не завантажувати
$ git remote prune <name>
------------------------------------------------

Щоб очищати посилання в рамках звичайного робочого процесу, не турбуючись про те, щоб не забути запустити цю операцію, вкажіть у конфігурації глобальний параметр `fetch.prune` або параметр `remote.<name>.prune` для кожного віддаленого екземпляра. Див. linkgit:git-config[1].

Тут справа стає дещо складнішою та конкретнішою. Функція очищення насправді не звертає уваги на гілки, натомість вона очищає локальні <--> віддалені посилання відповідно до refspec віддаленого екземпляра (див. `<refspec>` та <<CRTB, НАЛАШТОВАНІ ГІЛКИ ВІДДАЛЕНОГО ВІДСТЕЖЕННЯ>> вище).

Отже, якщо refspec для віддаленого репозиторію містить, наприклад, `refs/tags/*:refs/tags/*`, або ви вручну запускаєте, наприклад, `git fetch --prune <name> "refs/tags/*:refs/tags/*"`, то видалятися будуть не застарілі гілки віддаленого репозиторію, а будь-які локальні теги, яких немає у віддаленому репозиторії.

Можливо, це не зовсім те, чого ви очікуєте: ви хочете очистити віддалений репозиторій _<name>_, але при цьому явно завантажити з нього теги, тому під час завантаження ви видалите всі свої локальні теги, більшість з яких, можливо, і не походила з віддаленого репозиторію _<name>_.

Тому будьте обережні, використовуючи це з таким refspec, як `refs/tags/*:refs/tags/*`, або з будь-яким іншим refspec, який може зіставляти посилання з декількох віддалених репозиторіїв з одним і тим самим локальним простором імен.

Оскільки синхронізація гілок і тегів на віддаленому сервері є типовим випадком використання, можна вказати опцію `--prune-tags` разом з `--prune`, щоб видалити локальні теги, яких немає у віддаленому екземплярі, та примусово оновити ті теги, що відрізняються. Очищення тегів також можна увімкнути за допомогою `fetch.pruneTags` або `remote.<name>.pruneTags` у конфігурації. Див. linkgit:git-config[1].

Параметр `--prune-tags` еквівалентний тому, що в refspecs віддаленого репозиторію вказано `refs/tags/*:refs/tags/*`. Це може призвести до деяких, на перший погляд, дивних взаємодій:

------------------------------------------------
# Ці обидві команди завантажують теги
$ git fetch --no-tags origin 'refs/tags/*:refs/tags/*'
$ git fetch --no-tags --prune-tags origin
------------------------------------------------

Причина, через яку система не видає помилку при запуску без параметра `--prune` або відповідних версій конфігурації, полягає у гнучкості налаштованих версій, а також у необхідності збереження співвідношення «1:1» між функціями параметрів командного рядка та функціями версій конфігурації.

Доцільно, наприклад, встановити параметр `fetch.pruneTags=true` у файлі `~/.gitconfig`, щоб теги очищалися при виконанні команди `git fetch --prune`, при цьому не викликаючи помилку при кожному запуску команди `git fetch` без параметра `--prune`.

Очищення тегів за допомогою `--prune-tags` також працює при завантаженні URL-адреси замість віддаленого репозиторію за його назвою. Усі ці дії призведуть до видалення тегів, яких немає на сервері origin:

------------------------------------------------
$ git fetch origin --prune --prune-tags
$ git fetch origin --prune 'refs/tags/*:refs/tags/*'
$ git fetch <url-of-origin> --prune --prune-tags
$ git fetch <url-of-origin> --prune 'refs/tags/*:refs/tags/*'
------------------------------------------------

ВИВІД
-----

Вивід команди «git fetch» залежить від використовуваного методу передачі даних; у цьому розділі описано вивід при завантаженні даних за протоколом Git (як локально, так і через SSH) та за протоколом Smart HTTP.

Статус запиту виводиться у вигляді таблиці, де кожен рядок показує статус окремого посилання. Кожен рядок має такий вигляд:

-------------------------------
 <flag> <summary> <from> -> <to> [<reason>]
-------------------------------

При використанні опції `--porcelain` формат виводу розрахований на машинний аналіз. На відміну від форматів виводу, призначених для читання людиною, він виводиться у стандартний вивід, а не у стандартний потік виводу помилок. Кожен рядок має такий вигляд:

-------------------------------
<flag> <old-object-id> <new-object-id> <local-reference>
-------------------------------

Статус актуальних посилань показується лише за наявності опції `--verbose`.

У режимі компактного виведення, що задається змінною конфігурації fetch.output, якщо в іншому рядку знайдено весь рядок _<from>_ або _<to>_, він замінюється символом `*`. Наприклад, `master -> origin/master` перетворюється на `master -> origin/*`.

flag (прапорець)::
	Один символ, що вказує на статус посилання:
(пробіл);; для успішно отриманого швидкого перемотування вперед (fast-forward);
`+`;; для успішного примусового оновлення;
`-`;; для успішного очищення посилання;
`t`;; для успішного оновлення тегу;
`*`;; для успішно отриманого нового посилання;
`!`;; для посилання, яке було відхилено або не вдалося оновити; та
`=`;; для актуального посилання, яке не потребувало отримання.

summary (підсумки)::
	У разі успішно отриманого посилання у підсумку відображаються старе та нове значення посилання у форматі, придатному для використання у вигляді аргументу команди `git log` (у більшості випадків це `<old>..<new>`, а для примусових оновлень, що не є fast-forward, — `<old>...<new>`).

з (from)::
	Імʼя віддаленого посилання, з якого здійснюється отримування, без префікса `refs/<type>/`. У разі видалення ім’я віддаленого посилання — «(none)».

до (to)::
	Назва локального посилання, що оновлюється, мінус його префікс `refs/<тип>/`.

причина (reason)::
	Пояснення, зрозуміле для людини. У випадку успішно отриманих посилань пояснення не потрібні. Для невдалого посилання описується причина невдачі.

ПРИКЛАДИ
--------

* Оновлення гілки віддаленого відстеження:
+
------------------------------------------------
$ git fetch origin
------------------------------------------------
+
Зазначена вище команда копіює всі гілки з віддаленого простору імен `refs/heads/` і зберігає їх у локальному просторі імен `refs/remotes/origin/`, якщо тільки для вказання нестандартного refspec не використовується опція `remote.<repository>.fetch`.

* Явне використання refspecs:
+
------------------------------------------------
$ git fetch origin +seen:seen maint:tmp
------------------------------------------------
+
Ця команда оновлює (або, за необхідності, створює) гілки `seen` та `tmp` у локальному репозиторії, завантажуючи дані з гілок (відповідно) `seen` та `maint` із віддаленого репозиторію.
+
Гілка `seen` буде оновлена, навіть якщо вона не перемотується вперед, оскільки перед нею стоїть знак плюс; гілка `tmp` цього не робитиме.

* Переглянути гілку віддаленого репозиторію, без налаштування віддаленого репозиторію у вашому локальному репозиторії:
+
------------------------------------------------
$ git fetch git://git.kernel.org/pub/scm/git/git.git maint
$ git log FETCH_HEAD
------------------------------------------------
+
Перша команда отримує гілку `maint` з репозиторію за адресою `git://git.kernel.org/pub/scm/git/git.git`, а друга команда використовує `FETCH_HEAD` для перевірки гілки за допомогою linkgit:git-log[1]. Завантажені об’єкти з часом будуть видалені вбудованою функцією очищення git (див. linkgit:git-gc[1]).

include::transfer-data-leaks.adoc[]

КОНФІГУРАЦІЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/fetch.adoc[]

ПОМИЛКИ
-------
Використання параметра `--recurse-submodules` дозволяє завантажувати нові коміти лише з тих субмодулів, які вже існують локально, наприклад, у теці `$GIT_DIR/modules/`. Якщо у висхідному репозиторії додано новий субмодуль, його неможливо завантажити, доки його не буде клоновано, наприклад, за допомогою команди `git submodule update`. Очікується, що ця проблема буде виправлена в майбутніх версіях Git.

ДИВ. ТАКОЖ
----------
linkgit:git-pull[1]

GIT
---
Частина набору linkgit:git[1]
