git-help(1)
===========

НАЗВА
-----
git-help - Відображення довідкової інформації про Git

СИНОПСИС
--------
[verse]
'git help' [-a|--all] [--[no-]verbose] [--[no-]external-commands] [--[no-]aliases]
'git help' [[-i|--info] [-m|--man] [-w|--web]] [<command>|<doc>]
'git help' [-g|--guides]
'git help' [-c|--config]
'git help' [--user-interfaces]
'git help' [--developer-interfaces]

ОПИС
----

Без параметрів та без заданих '<command>' або '<doc>', короткий опис команди 'git' та список найчастіше використовуваних команд Git виводяться на стандартний вивід.

Якщо вказано опцію `--all` або `-a`, усі доступні команди виводяться на стандартний вивід.

Якщо вказано опцію `--guides` або `-g`, список концептуальних посібників Git також виводиться на стандартний вивід.

Якщо вказано команду або іншу документацію, буде відкрито відповідну сторінку довідника. За замовчуванням для цієї мети використовується програма «man», але її можна перевизначити іншими опціями або змінними конфігурації.

Якщо вказано псевдонім, git показує визначення псевдоніма у стандартному виводі. Щоб отримати сторінку довідки для команди з псевдонімом, використовуйте `git <команда> --help`.

Зверніть увагу, що `git --help ...` ідентичне `git help ...`, оскільки перше внутрішньо перетворюється на друге.

Щоб відобразити сторінку довідки linkgit:git[1], скористайтеся командою `git help git`.

Цю сторінку можна відобразити за допомогою 'git help help' або `git help --help`.

ОПЦІЇ
-----
-a::
--all::
	Вивести всі доступні команди на стандартний вивід.

--no-external-commands::
	При використанні з `--all` виключає список зовнішніх команд "git-*", що знаходяться в `$PATH`.

--no-aliases::
	При використанні з `--all` виключати список налаштованих псевдонімів.

--verbose::
	При використанні з `--all` виводити опис для всіх розпізнаних команд. Це значення за замовчуванням.

-c::
--config::
	Перелічіть усі доступні змінні конфігурації. Це короткий виклад списку в linkgit:git-config[1].

-g::
--guides::
	Вивести список посібників з концепції Git на стандартний вивід.

--user-interfaces::
	Вивести список документації щодо репозиторію, команд та файлових інтерфейсів на стандартний вивід.
+
Інтерфейси файлів в репозиторії, такі як `.git/info/exclude`, задокументовані тут (див. linkgit:gitrepository-layout[5]), а також конфігурація в дереві, така як `.mailmap` (див. linkgit:gitmailmap[5]).
+
Цей розділ документації також охоплює загальні або поширені конвенції користувацького інтерфейсу (наприклад, linkgit:gitcli[7]) та псевдоконфігурацію, таку як файловий інтерфейс `.git/hooks/*`, описаний у linkgit:githooks[5].

--developer-interfaces::
	Вивести список форматів файлів, протоколів та іншої документації інтерфейсів розробника на стандартний вивід.

-i::
--info::
	Відобразити сторінку довідки для команди у форматі 'info'. Для цієї мети буде використана програма 'info'.

-m::
--man::
	Відображати сторінку довідки для команди у форматі 'man'. Цей параметр можна використовувати для перевизначення значення, встановленого у змінній конфігурації `help.format`.
+
За замовчуванням для відображення сторінки довідки використовуватиметься програма 'man', але змінну конфігурації `man.viewer` можна використовувати для вибору інших програм відображення (див. нижче).

-w::
--web::
	Відобразити сторінку довідки для команди у форматі «web» (HTML). Для цієї мети буде використано веббраузер.
+
Веббраузер можна вказати за допомогою змінної конфігурації `help.browser` або `web.browser`, якщо перша не встановлена. Якщо жодна з цих змінних конфігурації не встановлена, допоміжний скрипт 'git web{litdd}browse' (який викликається 'git help') вибере відповідну змінну за замовчуванням. Див. linkgit:git-web{litdd}browse[1] для отримання додаткової інформації про це.

ЗМІННІ КОНФІГУРАЦІЇ
-------------------

help.format
~~~~~~~~~~~

Якщо не передано параметр командного рядка, буде перевірено змінну конфігурації `help.format`. Для цієї змінної підтримуються такі значення; вони змушують 'git help' поводитися як відповідний параметр командного рядка:

* "man" corresponds to '-m|--man',
* "info" corresponds to '-i|--info',
* "web" or "html" відповідають '-w|--web'.

help.browser, web.browser та browser.<інструмент>.шлях
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`help.browser`, `web.browser` та `browser.<tool>.path` також будуть перевірені, якщо вибрано формат 'web' (або за допомогою параметра командного рядка, або за допомогою змінної конфігурації). Див. '-w|--web' у розділі ПАРАМЕТРІВ вище та linkgit:git-web{litdd}browse[1].

man.viewer
~~~~~~~~~~

Змінна конфігурації `man.viewer` буде перевірена, якщо вибрано формат 'man'. Наразі підтримуються такі значення:

* "man": використовувати програму 'man' як завжди,
* "woman": використовуйте 'emacsclient' для запуску режиму "woman" в emacs (це працює лише починаючи з emacsclient версії 22),
* "konqueror": використовуйте 'kfmclient', щоб відкрити сторінку довідки у новій вкладці konqueror (див. 'Примітка про konqueror' нижче).

Значення для інших інструментів можна використовувати, якщо є відповідний запис конфігурації `man.<tool>.cmd` (див. нижче).

Змінній конфігурації `man.viewer` можна задати кілька значень. Відповідні програми будуть випробувані в порядку, зазначеному у файлі конфігурації.

Наприклад, ця конфігурація:

------------------------------------------------
	[man]
		viewer = konqueror
		viewer = woman
------------------------------------------------

спочатку спробує використати konqueror. Але це може не вийти (наприклад, якщо DISPLAY не встановлено), і в такому разі буде використано жіночий режим emacs.

Якщо нічого не вдається, або якщо переглядач не налаштовано, буде спробовано переглядач, зазначений у змінній середовища `GIT_MAN_VIEWER`. Якщо це також не вдається, буде спробовано програму 'man' у будь-якому разі.

man.<tool>.path
~~~~~~~~~~~~~~~

Ви можете явно вказати повний шлях до потрібного вам переглядача man, встановивши змінну конфігурації `man.<tool>.path`. Наприклад, ви можете налаштувати абсолютний шлях до konqueror, встановивши 'man.konqueror.path'. В іншому випадку 'git help' вважатиме, що інструмент доступний у PATH.

man.<tool>.cmd
~~~~~~~~~~~~~~

Якщо засіб перегляду man, заданий змінними конфігурації `man.viewer`, не входить до числа підтримуваних, тоді буде виконано пошук у відповідній змінній конфігурації `man.<tool>.cmd`. Якщо ця змінна існує, тоді вказаний інструмент буде розглядатися як користувацька команда, і для виконання команди буде використано оціночну команду оболонки з переданою сторінкою man як аргументами.

Примітка щодо Konqueror
~~~~~~~~~~~~~~~~~~~~~~~

Коли в конфігураційній змінній `man.viewer` вказано 'konqueror', ми запускаємо 'kfmclient', щоб спробувати відкрити сторінку довідки у вже відкритому konqueror у новій вкладці, якщо це можливо.

Для узгодженості ми також пробуємо такий трюк, якщо для 'man.konqueror.path' встановлено значення на кшталт `A_PATH_TO/konqueror`. Це означає, що ми спробуємо запустити `A_PATH_TO/kfmclient`.

Якщо ви дійсно хочете використовувати «konqueror», то можете використати щось на кшталт наступного:

------------------------------------------------
	[man]
		viewer = konq

	[man "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

Примітка щодо git config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Зверніть увагу, що всі ці змінні конфігурації, ймовірно, слід встановити за допомогою прапорця `--global`, наприклад, ось так:

------------------------------------------------
$ git config --global help.format web
$ git config --global web.browser firefox
------------------------------------------------

оскільки вони, ймовірно, більше залежать від користувача, ніж від репозиторію. Див. linkgit:git-config[1] для отримання додаткової інформації про це.

GIT
---
Частина набору linkgit:git[1]
