git-web{litdd}browse(1)
=======================

НАЗВА
-----
git-web--browse — Допоміжний скрипт Git для запуску вебоглядача

СИНОПСИС
--------
[verse]
'git web{litdd}browse' [<options>] (<URL>|<file>)...

ОПИС
----

Цей скрипт намагається, наскільки це можливо, показувати URL-адреси та ФАЙЛИ, що передаються як аргументи, у вигляді HTML-сторінок у нових вкладках уже відкритого вебоглядача.

Наразі підтримуються такі оглядачі (або команди):

* firefox (це стандартний оглядач у середовищі X Window, якщо не використовується KDE)
* iceweasel
* seamonkey
* iceape
* chromium (також підтримується як chromium-browser)
* google-chrome (також підтримується як chrome)
* konqueror (це стандартна версія в KDE, див. «Примітка щодо konqueror» нижче)
* opera
* w3m (це стандартне зовнішнє графічне середовище)
* elinks
* links
* lynx
* dillo
* open (це стандартна команда у графічному інтерфейсі Mac OS X)
* start (це стандартне значення у MinGW)
* cygstart (це стандартне значення у Cygwin)
* xdg-open

Також можна вказати власні команди.

ОПЦІЇ
-----
-b <browser>::
--browser=<browser>::
	Використовуйте вказаний оглядач. Він має бути у списку підтримуваних оглядачів.

-t <browser>::
--tool=<browser>::
	Те саме, що й вище.

-c <conf.var>::
--config=<conf.var>::
	CONF.VAR шукається у конфігураційних файлах Git. Якщо встановлено, то значення вказує на оглядач, який слід використовувати.

ЗМІННІ КОНФІГУРАЦІЇ
-------------------

CONF.VAR (з опції -c) та web.browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Вебоглядач можна вказати за допомогою змінної конфігурації, що передається з параметром командного рядка -c (або --config), або змінної конфігурації `web.browser`, якщо перша не використовується.

browser.<tool>.path
~~~~~~~~~~~~~~~~~~~

Ви можете явно вказати повний шлях до потрібного вам оглядача, встановивши змінну конфігурації `browser.<tool>.path`. Наприклад, ви можете налаштувати абсолютний шлях до Firefox, встановивши 'browser.firefox.path'. В іншому випадку, 'git web{litdd}browse' припускатиме, що інструмент доступний у PATH.

browser.<tool>.cmd
~~~~~~~~~~~~~~~~~~

Якщо оглядач, вказаний опціями або змінними конфігурації, не входить до числа підтримуваних, тоді буде виконано пошук у відповідній змінній конфігурації `browser.<tool>.cmd`. Якщо ця змінна існує, то 'git web{litdd}browse' трактуватиме вказаний інструмент як команду користувача та використовуватиме shell eval для виконання команди з URL-адресами, переданими як аргументи.

ПРИМІТКА ПРО KONQUEROR
----------------------

Коли «konqueror» вказано параметром командного рядка або змінною конфігурації, ми запускаємо «kfmclient», щоб спробувати відкрити сторінку довідки HTML у вже відкритому konqueror у новій вкладці, якщо це можливо.

Для узгодженості ми також пробуємо такий трюк, якщо для 'browser.konqueror.path' встановлено значення на кшталт `A_PATH_TO/konqueror`. Це означає, що ми спробуємо запустити `A_PATH_TO/kfmclient`.

Якщо ви дійсно хочете використовувати 'konqueror', то можете використати щось на кшталт наступного:

------------------------------------------------
	[web]
		browser = konq

	[browser "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

Примітка про git-config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Зверніть увагу, що ці змінні конфігурації, ймовірно, слід встановити за допомогою прапорця `--global`, наприклад, ось так:

------------------------------------------------
$ git config --global web.browser firefox
------------------------------------------------

оскільки вони, ймовірно, більше стосуються конкретного користувача, ніж конкретного репозиторію. Докладнішу інформацію з цього приводу див. за посиланням linkgit:git-config[1].

GIT
---
Частина набору linkgit:git[1]
