git-quiltimport(1)
==================

НАЗВА
-----
git-quiltimport - Застосовує набір латок для квілтингу до поточної гілки


СИНОПСИС
--------
[verse]
'git quiltimport' [--dry-run | -n] [--author <author>] [--patches <dir>]
		[--series <file>] [--keep-non-patch]


ОПИС
----
Застосовує набір патчів для квілту до поточної гілки Git, зберігаючи межі патчів, порядок патчів та описи патчів, присутні в наборі патчів для квілту.

Для кожного патча код намагається витягти автора з опису патча. Якщо це не вдається, код повертається до автора, вказаного за допомогою --author. Якщо прапорець --author не було вказано, відображається опис патча, і користувачеві пропонується інтерактивно ввести автора патча.

Якщо тема не знайдена в описі патча, назва патча зберігається як тема в один рядок в описі Git.

ОПЦІЇ
-----

-n::
--dry-run::
	Пройдіться патчами серії та попередьте, якщо ми не можемо знайти всю необхідну інформацію для створення патча. На момент написання цієї статті попереджено лише про відсутню інформацію про автора.

--author 'Ім'я автора <Електронна адреса автора>::
	Ім'я автора та адреса електронної пошти, які використовуються, коли в описі патча не вдається знайти інформацію про автора.

--patches <dir>::
	Каталог для пошуку латок для ковдр.
+
Значенням каталогу патчів за замовчуванням є «patches» або значення змінної середовища `$QUILT_PATCHES`.

--series <file>::
	Файл серії ковдр.
+
Значення файлу серії за замовчуванням — <patches>/series або значення змінної середовища `$QUILT_SERIES`.

--keep-non-patch::
	Pass `-b` flag to 'git mailinfo' (див. linkgit:git-mailinfo[1]).

GIT
---
Частина набору linkgit:git[1]
