git-mergetool{litdd}lib(1)
==========================

НАЗВА
-----
git-mergetool--lib - Загальні скриптлети оболонки інструментів злиття Git

СИНОПСИС
--------
[verse]
'TOOL_MODE=(diff|merge) . "$(git --exec-path)/git-mergetool{litdd}lib"'

ОПИС
----

Цю команду кінцевий користувач не захоче виконувати. Ніколи. Ця документація призначена для людей, які вивчають скрипти типу Porcelain та/або пишуть нові.

Скриптлет 'git-mergetool{litdd}lib' розроблений для використання іншими скриптами оболонки (використанням `.`) для налаштування функцій для роботи з інструментами злиття Git.

Перед отриманням 'git-mergetool{litdd}lib', ваш скрипт повинен встановити `TOOL_MODE`, щоб визначити режим роботи для функцій, перелічених нижче. 'diff' та 'merge' є допустимими значеннями.

ФУНКЦІЇ
-------
get_merge_tool::
	Повертає інструмент злиття. Код повернення — 1, якщо ми повернули вгаданий інструмент злиття, інакше — 0. '$GIT_MERGETOOL_GUI' можна встановити на 'true' для пошуку відповідного інструменту злиття.

get_merge_tool_cmd::
	Повертає власну команду для інструмента об'єднання.

get_merge_tool_path::
	Повертає власний шлях для інструмента об'єднання.

initialize_merge_tool::
	Вносить специфічні функції інструмента злиття в область видимості, щоб їх можна було використовувати або перевизначати.

run_merge_tool::
	Запускає інструмент об'єднання, враховуючи назву інструмента та прапорець true/false, щоб вказати, чи присутня база об'єднання. Для використання інструментом об'єднання необхідно визначити '$MERGED', '$LOCAL', '$REMOTE' та '$BASE'.

GIT
---
Частина набору linkgit:git[1]
