git-stripspace(1)
=================

НАЗВА
-----
git-stripspace — Видалення зайвих пробілів


СИНОПСИС
--------
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

ОПИС
----

Читає текст, наприклад повідомлення про коміти, примітки, теги та описи гілок, зі стандартного вводу та очищає його відповідно до стандартів Git.

Без аргументів це буде так:

- видаляє пробіли в кінці всіх рядків
- згортає кілька послідовних порожніх рядків в один порожній рядок
- видаляє порожні рядки на початку та в кінці вхідних даних
- за потреби додайте відсутній символ '\n' до останнього рядка.

У випадку, якщо вхідні дані повністю складаються з пробільних символів, вивід не буде створено.

*ПРИМІТКА*: Це призначено для очищення метаданих. Для виправлення пробілів у латках або файлах у репозиторії надавайте перевагу режиму `--whitespace=fix` у linkgit:git-apply[1].

ОПЦІЇ
-----
-s::
--strip-comments::
	Пропустити та видалити всі рядки, що починаються з символу коментаря (`core.commentChar`, зазвичай `#`).

-c::
--comment-lines::
	Додавати символ коментаря та пробіл до кожного рядка. Рядки автоматично завершуватимуться символом нового рядка. У порожніх рядках буде додано лише символ коментаря.

ПРИКЛАДИ
--------

Розглянемо такий зашумлений вхідний текст, де символ '$' позначає кінець рядка:

---------
|A brief introduction   $
|   $
|$
|A new paragraph$
|# with a commented-out line    $
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out. $
|      $
|The end.$
|  $
---------

Використайте 'git stripspace' без аргументів, щоб отримати:

---------
|A brief introduction$
|$
|A new paragraph$
|# with a commented-out line$
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out.$
|$
|The end.$
---------

Використайте 'git stripspace --strip-comments', щоб отримати:

---------
|A brief introduction$
|$
|A new paragraph$
|explaining lots of stuff.$
|$
|The end.$
---------

GIT
---
Частина набору linkgit:git[1]
