git-http-push(1)
================

НАЗВА
-----
git-http-push — Надсилання обʼєктів через HTTP/DAV до іншого репозиторію


СИНОПСИС
--------
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ref> [<ref>...]

ОПИС
----
Надсилає відсутні обʼєкти до віддаленого репозиторію та оновлює віддалену гілку.

*ПРИМІТКА*: Ця команда є тимчасово вимкненою, якщо ваша бібліотека libcurl старіша за 7.16, оскільки повідомлялося, що ця комбінація не працює та іноді пошкоджує репозиторій.

ОПЦІЇ
-----
--all::
	Не слід вважати, що віддалений репозиторій у його поточному стані є повним; переконатись, що всі об’єкти з усієї історії локального посилання існують у віддаленому репозиторії.

--force::
	Зазвичай команда відмовляється оновлювати віддалене посилання, яке не є предком локального посилання, що використовується для його перезапису. Цей прапорець вимикає перевірку. Це означає, що віддалений репозиторій може втратити коміти; використовуйте його обережністю.

--dry-run::
	Зробити усе, крім надсилання оновлень.

--verbose::
	Виводить список об’єктів, які обробляються локально, та список об’єктів, успішно надісланих до віддаленого сховища.

-d::
-D::
	Видалити <ref> з віддаленого репозиторію. Вказана гілка не може бути віддаленою HEAD. Якщо вказано -d, також мають бути виконані такі інші умови:

	- Віддалений HEAD повинен вказувати на об’єкт, який існує локально
	- Зазначена гілка веде до обʼєкта, який існує локально
	- Вказана гілка є предком віддаленого HEAD

<ref>...::
	Віддалені посилання для оновлення.


ВКАЗАННЯ ПОСИЛАНЬ
-----------------

Специфікація '<ref>' може бути або окремим шаблоном, або парою таких шаблонів, розділених двокрапкою ":" (це означає, що назва посилання не може містити двокрапку). Окремий шаблон '<name>' — це просто скорочення від '<name>:<name>'.

Кожна пара шаблонів '<src>:<dst>' складається з джерела (до двокрапки) та місця призначення (після двокрапки). Посилання, яке потрібно додати, визначається шляхом пошуку збігу, що відповідає джерелу, а місце його додавання визначається за допомогою місця призначення.

 - Якщо '<src>' не відповідає точно одному з локальних посилань, це вважається помилкою.

 - Якщо '<dst>' не відповідає жодному віддаленому посиланню,

   * воно має починатися з "refs/"; у цьому випадку <dst> використовується як пункт призначення буквально.

   * <src> == <dst>, а посилання, яке збіглося з <src>, не повинно існувати в наборі віддалених посилань; посилання, яке локально збіглося з <src>, використовується як назва призначення.

Без `--force`, посилання <src> зберігається на віддаленому сервері лише якщо <dst> не існує або <dst> є належною підмножиною (тобто предком) <src>. Ця перевірка, відома як "перевірка швидкого перезапису", виконується, щоб уникнути випадкового перезапису віддаленого посилання та втрати комітів інших користувачів звідти.

З параметром `--force` перевірка швидкого перемотування вперед вимикається для всіх посилань.

За бажанням, параметр <ref> може мати префікс із знаком «+», щоб вимкнути перемотку лише для цього посилання.

GIT
---
Частина набору linkgit:git[1]
