git-quiltimport(1)
==================

НАЗВА
-----
git-quiltimport — Застосування набору латок Quilt до поточної гілки


СИНОПСИС
--------
[verse]
'git quiltimport' [--dry-run | -n] [--author <author>] [--patches <dir>]
		[--series <file>] [--keep-non-patch]


ОПИС
----
Застосовує набір латок Quilt до поточної гілки Git, зберігаючи межі латок, їхній порядок та описи, що містяться в наборі латок Quilt.

Для кожної латки код намагається витягти імʼя автора з опису латки. Якщо це не вдається, використовується імʼя автора, вказане за допомогою параметра --author. Якщо параметр --author не вказано, на екрані показується опис латки, і користувачеві пропонується ввести ім’я автора латки вручну.

Якщо тема не знайдена в описі латки, назва латки зберігається як тема в один рядок в описі Git.

ОПЦІЇ
-----

-n::
--dry-run::
	Перегляньте латки в серії та видайте попередження, якщо не вдається знайти всю необхідну інформацію для фіксації латки. На момент написання попередження видається лише у разі відсутності інформації про автора.

--author 'Імʼя автора <Електронна адреса автора>'::
	Імʼя автора та адреса електронної пошти, які використовуються, коли в описі латки не вдається знайти інформацію про автора.

--patches <dir>::
	Тека для пошуку латок quilt.
+
Стандартним значенням для теки латок є 'patches' або значення змінної середовища `$QUILT_PATCHES`.

--series <file>::
	Файл серії quilt.
+
Стандартним для файлу серії є <patches>/series або значення змінної середовища `$QUILT_SERIES`.

--keep-non-patch::
	Передає прапорець `-b` до 'git mailinfo' (див. linkgit:git-mailinfo[1]).

GIT
---
Частина набору linkgit:git[1]
