git-check-attr(1)
=================

НАЗВА
-----
git-check-attr — Перегляд інформації про gitattributes


СИНОПСИС
--------
[verse]
'git check-attr' [--source <tree-ish>] [-a | --all | <attr>...] [--] <pathname>...
'git check-attr' --stdin [-z] [--source <tree-ish>] [-a | --all | <attr>...]

ОПИС
----
Для кожного імені шляху ця команда покаже, чи є кожен атрибут 'unspecified', 'set' чи 'unset' як gitattribute для цього імені шляху.

ОПЦІЇ
-----
-a::
--all::
	Вивести перелік всіх атрибутів, повʼязаних із вказаними шляхами. Якщо використовувати цю опцію, атрибути з позначкою 'unspecified' не будуть включені до результату.

--cached::
	Використовувати `.gitattributes` лише в індексі, ігноруючи робоче дерево.

--stdin::
	Зчитувати імена шляхів зі стандартного вводу, по одному на рядок, а не з командного рядка.

-z::
	Формат виводу змінено для машинного аналізу. Якщо також задано параметр `--stdin`, вхідні шляхи розділяються символом NUL замість символу переведення рядка.

--source=<tree-ish>::
	Порівняти атрибути з вказаною структурою. Зазвичай джерело вказують, вказавши імʼя коміту, гілки або тегу, повʼязаного з ним.

\--::
	Інтерпретувати всі попередні аргументи як атрибути, а всі наступні аргументи як імена шляхів.

Якщо жоден з параметрів `--stdin`, `--all` або `--` не використовується, перший аргумент буде розглядатися як атрибут, а решта аргументів — як шляхи.

ВИВІД
-----

Вивід має вигляд: <шлях> COLON SP <атрибут> COLON SP <інформація> LF

якщо тільки не діє `-z`, у цьому випадку як роздільник використовується NUL: <шлях> NUL <атрибут> NUL <інформація> NUL


<шлях> — це шлях до файлу, що запитується, <атрибут> — це атрибут, що запитується, а <інформація> може бути одним із таких значень:

'unspecified';; коли атрибут не визначено для шляху.
'unset';;	коли атрибут визначено як false.
'set';;		коли атрибут визначено як true.
<значення>;;	коли атрибуту було присвоєно значення.

Буферизація відбувається відповідно до опису в розділі про опцію `GIT_FLUSH` у документації linkgit:git[1]. Виконавець повинен запобігати виникненню взаємних блокувань, спричинених переповненням вхідного буфера або спробою зчитування з порожнього вихідного буфера.

ПРИКЛАДИ
--------

У прикладах використовується наступний файл '.gitattributes':

---------------
*.java diff=java -crlf myAttr
NoMyAttr.java !myAttr
README caveat=unspecified
---------------

* Вивід одного атрибута:
+
---------------
$ git check-attr diff org/example/MyClass.java
org/example/MyClass.java: diff: java
---------------

* Вивід кількох атрибутів для файлу:
+
---------------
$ git check-attr crlf diff myAttr -- org/example/MyClass.java
org/example/MyClass.java: crlf: unset
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Вивід усіх атрибутів файлу:
+
---------------
$ git check-attr --all -- org/example/MyClass.java
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Вивід атрибутів для кількох файлів:
+
---------------
$ git check-attr myAttr -- org/example/MyClass.java org/example/NoMyAttr.java
org/example/MyClass.java: myAttr: set
org/example/NoMyAttr.java: myAttr: unspecified
---------------

* Не всі значення є однаково однозначними:
+
---------------
$ git check-attr caveat README
README: caveat: unspecified
---------------

ДИВ. ТАКОЖ
----------
linkgit:gitattributes[5].

GIT
---
Частина набору linkgit:git[1]
