git-diff(1)
===========

НАЗВА
-----
git-diff - Показати зміни між коммітами, комітом та робочим деревом тощо


СИНОПСИС
--------
[synopsis]
git diff [<options>] [<commit>] [--] [<path>...]
git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]
git diff [<options>] [--merge-base] <commit> [<commit>...] <commit> [--] [<path>...]
git diff [<options>] <commit>...<commit> [--] [<path>...]
git diff [<options>] <blob> <blob>
git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]

ОПИС
----
Відображати зміни між робочим деревом та індексом або деревом, зміни між індексом та деревом, зміни між двома деревами, зміни, що виникають в результаті злиття, зміни між двома blob-об'єктами або зміни між двома файлами на диску.

`git diff [<options>] [--] [<path>...]`::

	Ця форма призначена для перегляду змін, які ви внесли відносно індексу (область проміжного зберігання для наступного коміту). Іншими словами, відмінності – це те, що ви _могли_ б_ сказати Git додати до індексу, але досі цього не зробили. Ви можете проміжним способом додати ці зміни, використовуючи linkgit:git-add[1].

`git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]`::

	Ця форма призначена для порівняння двох заданих шляхів у файловій системі. Ви можете пропустити опцію `--no-index`, якщо ви виконуєте команду в робочому дереві, контрольованому Git, і принаймні один зі шляхів вказує за межі робочого дерева, або якщо ви виконуєте команду за межами робочого дерева, контрольованого Git. Ця форма передбачає `--exit-code`. Якщо обидва шляхи вказують на каталоги, можна надати додаткові специфікації шляхів. Вони обмежать файли, що входять до різниці. Усі такі специфікації шляхів мають бути відносними, оскільки вони застосовуються до обох сторін різниці.

`git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]`::

	Ця форма призначена для перегляду змін, які ви проіндексували для наступного коміту відносно названого _<commit>_. Зазвичай вам потрібно порівняти їх з останнім комітом, тому, якщо ви не вкажете _<commit>_, за замовчуванням використовується значення `HEAD`. Якщо `HEAD` не існує (наприклад, ненароджені гілки) і _<commit>_ не вказано, буде показано всі проіндексовані зміни. `--staged` є синонімом `--cached`.
+
Якщо вказано `--merge-base`, замість використання _<commit>_ використовується база злиття _<commit>_ та `HEAD`. `git diff --cached --merge-base A` еквівалентно `git diff --cached $(git merge-base A HEAD)`.

`git diff [<options>] [--merge-base] <commit> [--] [<path>...]`::

	Ця форма призначена для перегляду змін у вашому робочому дереві відносно названого _<commit>_. Ви можете використовувати `HEAD` для порівняння його з останнім комітом або назву гілки для порівняння з кінчиком іншої гілки.
+
Якщо вказано `--merge-base`, замість використання _<commit>_ використовується база злиття _<commit>_ та `HEAD`. `git diff --merge-base A` еквівалентно `git diff $(git merge-base A HEAD)`.

`git diff [<options>] [--merge-base] <commit> <commit> [--] [<path>...]`::

	Це для перегляду змін між двома довільними _<commit>_.
+
Якщо вказано `--merge-base`, використовувати базу злиття двох комітів для сторони "до". `git diff --merge-base A B` еквівалентно `git diff $(git merge-base A B) B`.

`git diff [<options>] <commit> <commit>...<commit> [--] [<path>...]`::

	Ця форма призначена для перегляду результатів коміту злиття. Перший у списку _<commit>_ має бути самим комітом злиття; решта два або більше комітів повинні бути його батьківськими. Зручними способами створення бажаного набору ревізій є використання суфіксів `@` та `^!`. Якщо `A` є комітом злиття, то `git diff A A^@`, `git diff A^!` та `git show A` дають однакову комбіновану різницю.

`git diff [<options>] <commit>..<commit> [--] [<path>...]`::

	Це синонім попередньої форми (без `..`) для перегляду змін між двома довільними _<commit>_. Якщо _<commit>_ з одного боку пропустити, це матиме той самий ефект, що й використання `HEAD` замість цього.

`git diff [<options>] <commit>...<commit> [--] [<path>...]`::

	Ця форма призначена для перегляду змін у гілці, що містить _<commit>_ і аж до другого _<commit>_, починаючи зі спільного предка обох _<commit>_. `git diff A...B` еквівалентно `git diff $(git merge-base A B) B`. Ви можете пропустити будь-який з _<commit>_, що матиме той самий ефект, що й використання `HEAD`.

Якщо ви робите щось екзотичне, слід зазначити, що всі _<commit>_ у наведеному вище описі, за винятком випадку `--merge-base` та двох останніх форм, які використовують нотації `..`, можуть бути будь-якими _<tree>_. Дерево, що нас цікавить, це те, на яке вказує посилання з назвою `AUTO_MERGE`, яке записується стратегією злиття `ort` після виникнення конфліктів злиття (див. linkgit:git-merge[1]). Порівняння робочого дерева з `AUTO_MERGE` показує зміни, які ви внесли до цього часу для вирішення текстових конфліктів (див. приклади нижче).

Для отримання повнішого списку способів написання _<commit>_ див. розділ "ВИЗНАЧЕННЯ РЕВІЗІЙ" у linkgit:gitrevisions[7]. Однак, `diff` стосується порівняння двох _кінцевих точок_, а не діапазонів, а позначення діапазонів (`<commit>..<commit>` та `<commit>...<commit>`) не означають діапазон, як визначено в розділі "ВИЗНАЧЕННЯ ДІАПАЗОНІВ" у linkgit:gitrevisions[7].

`git diff [<options>] <blob> <blob>`::

	Ця форма призначена для перегляду відмінностей між необробленим вмістом двох blob-об'єктів.

ОПЦІЇ
-----
:git-diff: 1
include::diff-options.adoc[]

`-1`::
`--base`::
`-2`::
`--ours`::
`-3`::
`--theirs`::
	Порівняйте робоче дерево з
+
--
 * "базова" версія (етап №1) при використанні `-1` або `--base`,
 * "наша гілка" (етап №2) при використанні `-2` або `--ours`, або
 * "їхня гілка" (етап №3) при використанні `-3` або `--theirs`.
--
+
Індекс містить ці етапи лише для необ'єднаних записів, тобто під час вирішення конфліктів. Див. розділ linkgit:git-read-tree[1] "3-стороннє об'єднання" для отримання детальної інформації.

`-0`::
	Пропустити вивід diff для необ'єднаних записів та показати лише "Не об'єднано". Можна використовувати лише під час порівняння робочого дерева з індексом.

`<шлях>...`::
	Параметри _<шлях>_, якщо їх задано, використовуються для обмеження різниці (різниця) до іменованих шляхів (ви можете вказати імена каталогів та отримати різницю для всіх файлів у них).


include::diff-format.adoc[]

ПРИКЛАДИ
--------

Різні способи перевірки робочого дерева::
+
------------
$ git diff            <1>
$ git diff --cached   <2>
$ git diff HEAD       <3>
$ git diff AUTO_MERGE <4>
------------
+
<1> Зміни в робочому дереві ще не підготовлені для наступного коміту.
<2> Зміни між індексом та вашим останнім комітом; що ви б закомітили, якби запустили `git commit` без опції `-a`.
<3> Зміни в робочому дереві з моменту вашого останнього коміту; що ви б закомітили, якби запустили `git commit -a`
<4> Зміни в робочому дереві, які ви внесли для вирішення текстових конфліктів на даний момент.

Порівняння з довільними коммітами::
+
------------
$ git diff test            <1>
$ git diff HEAD -- ./test  <2>
$ git diff HEAD^ HEAD      <3>
------------
+
<1> Замість використання кінчика поточної гілки, порівняйте з кінчиком "тестової" гілки.
<2> Замість порівняння з кінчиком гілки "test", порівняйте з кінчиком поточної гілки, але обмежте порівняння файлом "test".
<3> Порівняйте версію перед останнім комітом та останній коміт.

Порівняння гілок::
+
------------
$ git diff topic master    <1>
$ git diff topic..master   <2>
$ git diff topic...master  <3>
------------
+
<1> Зміни між порадами теми та головними гілками.
<2> Те саме, що й вище.
<3> Зміни, що відбулися в головній гілці з моменту запуску тематичної гілки.

Обмеження виводу різниці::
+
------------
$ git diff --diff-filter=MRC            <1>
$ git diff --name-status                <2>
$ git diff arch/i386 include/asm-i386   <3>
------------
+
<1> Показувати лише модифікацію, перейменування та копіювання, але не додавання чи видалення.
<2> Показувати лише назви та характер змін, але не фактичний вивід різниці.
<3> Обмежити вивід diff іменованими піддеревами.

Обробка виводу diff::
+
------------
$ git diff --find-copies-harder -B -C  <1>
$ git diff -R                          <2>
------------
+
<1> Витрачати додаткові цикли на пошук перейменувань, копій та повних перезаписів (дуже дорого).
<2> Вихідний диференціал у зворотному напрямку.

КОНФІГУРАЦІЯ
------------

include::includes/cmd-config-section-all.adoc[]

:git-diff: 1
include::config/diff.adoc[]

ДИВ. ТАКОЖ
----------
`diff`(1), linkgit:git-difftool[1], linkgit:git-log[1], linkgit:gitdiffcore[7], linkgit:git-format-patch[1], linkgit:git-apply[1], linkgit:git-show[1]

GIT
---
Частина набору linkgit:git[1]
