git-mailsplit(1)
================

НАЗВА
-----
git-mailsplit — Проста програма для розділення файлів UNIX mbox

СИНОПСИС
--------
[verse]
'git mailsplit' [-b] [-f<nn>] [-d<prec>] [--keep-cr] [--mboxrd]
		-o<directory> [--] [(<mbox>|<Maildir>)...]

ОПИС
----
Розділяє файл mbox або Maildir на список файлів: "0001" "0002" .. у вказаній теці, щоб ви могли обробити їх далі звідти.

IMPORTANT: Розділення Maildir залежить від сортування імен файлів для виведення латок у правильному порядку.

ОПЦІЇ
-----
<mbox>::
	Mbox-файл для розділення. Якщо не вказано, mbox зчитується зі стандартного вводу.

<Maildir>::
	Коренева тека Maildir, яку потрібно розділити. Ця тека повинна містити субтеки cur, tmp та new.

-o<directory>::
	Тека, в якій розміщувати окремі повідомлення.

-b::
	Якщо якийсь файл не починається з рядка «From», вважати, що це окреме повідомлення електронної пошти, а не сигнал про помилку.

-d<prec>::
	Замість стандартних 4 цифр з початковими нулями, для згенерованих імен файлів можна вказати іншу точність.

-f<nn>::
	Пропускати перші <nn> цифри, наприклад, якщо вказано -f3, нумерація починається з 0004.

--keep-cr::
	Не видаляти `\r` з рядків, що закінчуються на `\r\n`.

--mboxrd::
	Вхідні дані мають формат "mboxrd", а екранування рядка "^>+From" виконується у зворотному порядку.

GIT
---
Частина набору linkgit:git[1]
