git-var(1)
==========

НАЗВА
-----
git-var - Показати логічну змінну Git


СИНОПСИС
--------
[synopsis]
git var (-l | <variable>)

ОПИС
----
Виводить логічну змінну Git. Виходить з кодом 1, якщо змінна не має значення.

ОПЦІЇ
-----
`-l`::
	Відобразити логічні змінні. Крім того, також перераховано всі змінні конфігураційного файлу Git .git/config. (Однак, функція переліку змінних конфігурації застаріла на користь `git config -l`.)

ПРИКЛАДИ
--------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


ЗМІННІ
------
`GIT_AUTHOR_IDENT`::
    Автор фрагмента коду.

`GIT_COMMITTER_IDENT`::
    Людина, яка вставила фрагмент коду в Git.

`GIT_EDITOR`::
    Текстовий редактор для використання командами Git. Значення призначене для інтерпретації оболонкою під час його використання. Приклади: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. Порядок пріоритету такий: `$GIT_EDITOR`, потім значення конфігурації `core.editor`, потім `$VISUAL`, потім `$EDITOR`, і нарешті значення за замовчуванням, вибране під час компіляції, яке зазвичай є 'vi'.
ifdef::git-default-editor[]
    Збірка, яку ви використовуєте, обрала '{git-default-editor}' як налаштування за замовчуванням.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Текстовий редактор, який використовується для редагування файлу «todo» під час виконання команди `git rebase -i`. Як і у випадку з `GIT_EDITOR`, значення має інтерпретуватися оболонкою під час його використання. Порядок пріоритетності такий: `$GIT_SEQUENCE_EDITOR`, потім значення конфігурації `sequence.editor`, а потім значення `git var GIT_EDITOR`.

`GIT_PAGER`::
    Текстовий переглядач для використання командами Git (наприклад, 'less'). Значення призначене для інтерпретації оболонкою. Порядок пріоритету такий: `$GIT_PAGER`, потім значення конфігурації `core.pager`, потім `$PAGER`, і нарешті значення за замовчуванням, вибране під час компіляції (зазвичай `less`).
ifdef::git-default-pager[]
    Збірка, яку ви використовуєте, вибрала '{git-default-pager}' як збірку за замовчуванням.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    Назва першої гілки, створеної у щойно ініціалізованих репозиторіях.

`GIT_SHELL_PATH`::
    Шлях до бінарного файлу, що забезпечує оболонку POSIX для команд, що використовують цю оболонку.

`GIT_ATTR_SYSTEM`::
    Шлях до системного файлу linkgit:gitattributes[5], якщо такий увімкнено.

`GIT_ATTR_GLOBAL`::
    Шлях до глобального (для кожного користувача) файлу linkgit:gitattributes[5].

`GIT_CONFIG_SYSTEM`::
    Шлях до файлу конфігурації системи, якщо він увімкнено.

`GIT_CONFIG_GLOBAL`::
    Шлях до глобальних (для кожного користувача) файлів конфігурації, якщо такі є.

Більшість значень шляху містять лише одне значення. Однак деякі можуть містити кілька значень, які розділяються символами нового рядка та перелічені в порядку від найвищого до найнижчого пріоритету. Викликаючі сторони повинні бути готові до того, що будь-яке таке значення шляху містить кілька елементів.

Зверніть увагу, що шляхи виводяться, навіть якщо вони не існують, але не якщо вони вимкнені іншими змінними середовища.

ДИВ. ТАКОЖ
----------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
Частина набору linkgit:git[1]
