git-count-objects(1)
====================

НАЗВА
-----
git-count-objects - Підрахунок кількості розпакованих об'єктів та їхнього використання на диску

СИНОПСИС
--------
[verse]
'git count-objects' [-v] [-H | --human-readable]

ОПИС
----
Підраховує кількість розпакованих об'єктних файлів та зайнятий ними дисковий простір, щоб допомогти вам вирішити, коли настав час для повторного пакування.


ОПЦІЇ
-----
-v::
--verbose::
	Надайте більш детальні звіти:
+
кількість: кількість незакріплених предметів
+
розмір: дисковий простір, що займається вільними об'єктами, у КіБ (якщо не вказано -H)
+
in-pack: кількість об'єктів in-pack
+
size-pack: дисковий простір, що займається пакетами, у КіБ (якщо не вказано -H)
+
prune-packable: кількість вільних об'єктів, які також присутні в пакетах. Ці об'єкти можна видалити за допомогою `git prune-packed`.
+
сміття: кількість файлів у базі даних об'єктів, які не є ні дійсними вільними об'єктами, ні дійсними пакетами
+
size-garbage: дисковий простір, що займається файлами сміття, у КіБ (якщо не вказано -H)
+
alternate: абсолютний шлях до альтернативних баз даних об'єктів; може зустрічатися кілька разів, один рядок на шлях. Зверніть увагу, що якщо шлях містить недруковані символи, він може бути взято в подвійні лапки та містити escape-послідовності зі зворотною скісну рискою у стилі C.

-H::
--human-readable::

Розміри друку у форматі, що читається людиною

GIT
---
Частина набору linkgit:git[1]
