git-verify-pack(1)
==================

НАЗВА
-----
git-verify-pack - Перевірити упаковані файли архіву Git


СИНОПСИС
--------
[synopsis]
git verify-pack [-v | --verbose] [-s | --stat-only] [--] <pack>.idx...


ОПИС
----
Прочитайте кожен idx-файл для упакованого архіву Git, вказаний у командному рядку, та перевірте idx-файл і відповідний pack-файл.

ОПЦІЇ
-----
`-v`::
`--verbose`::
	Після перевірки пакету, покажіть список об'єктів, що містяться в пакеті, та гістограму довжини дельта-ланцюга.

`-s`::
`--stat-only`::
	Не перевіряти вміст пакета; лише показувати гістограму довжини дельта-ланцюга. З параметром `--verbose` також відображається список об'єктів.

`--`::
	Не інтерпретуйте жодних додаткових аргументів як варіанти.

ВИХІДНИЙ ФОРМАТ
---------------
При вказівці опції `-v` використовується такий формат:

	ім'я-об'єкта тип розмір розмір-в-пакетному-файлі зсув-в-пакетному-файлі

для об'єктів, які не дельтифіковані в пакеті, та

	ім'я-об'єкта тип розмір розмір-в-пакетному-файлі зсув-в-пакетному-файлі глибина ім'я-базового-об'єкта

для об'єктів, що мають дельтифікацію.

GIT
---
Частина набору linkgit:git[1]
