git-sh-setup(1)
===============

НАЗВА
-----
git-sh-setup - Код налаштування поширеного скрипта оболонки Git

СИНОПСИС
--------
[verse]
'. "$(git --exec-path)/git-sh-setup"'

ОПИС
----

Цю команду кінцевий користувач не захоче виконувати. Ніколи. Ця документація призначена для людей, які вивчають скрипти типу Porcelain та/або пишуть нові.

Скриптлет 'git sh-setup' розроблений для використання (використанням `.`) іншими скриптами оболонки для налаштування деяких змінних, що вказують на звичайні каталоги Git, та кількох допоміжних функцій оболонки.

Перш ніж отримувати його, ваш скрипт повинен налаштувати кілька змінних; `USAGE` (та `LONG_USAGE`, якщо такі є) використовується для визначення повідомлення, яке видається функцією оболонки `usage()`. `SUBDIRECTORY_OK` можна встановити, якщо скрипт може запускатися з підкаталогу робочого дерева (деякі команди цього не роблять).

Скриптлет встановлює змінні оболонки `GIT_DIR` та `GIT_OBJECT_DIRECTORY`, але *не* експортує їх у середовище.

ФУНКЦІЇ
-------

die::
	вихід після видачі наданого повідомлення про помилку до стандартного потоку помилок.

usage::
	померти разом із повідомленням про використання.

set_reflog_action::
	Встановіть для середовища `GIT_REFLOG_ACTION` заданий рядок (зазвичай назва програми), якщо він ще не встановлений. Щоразу, коли скрипт виконує команду `git`, яка оновлює посилання, запис у журналі посилань створюється з використанням значення цього рядка, щоб залишити запис про те, яка команда оновила посилання.

git_editor::
	запускає редактор на вибір користувача (GIT_EDITOR, core.editor, VISUAL або EDITOR) для заданого файлу, але виводить помилку, якщо редактор не вказано, а термінал не працює належним чином.

is_bare_repository::
	виводить `true` або `false` у стандартний потік виводу, щоб вказати, чи є репозиторій голим репозиторієм (тобто без пов'язаного робочого дерева).

cd_to_toplevel::
	запускає chdir на верхній рівень робочого дерева.

require_work_tree::
	перевіряє, чи поточний каталог знаходиться в робочому дереві репозиторію, в іншому випадку завершує роботу.

require_work_tree_exists::
	перевіряє, чи існує робоче дерево, пов'язане з репозиторієм, і в іншому випадку завершує роботу. Часто це робиться перед викликом cd_to_toplevel, що неможливо зробити, якщо немає робочого дерева.

require_clean_work_tree <action> [<hint>]::
	перевіряє, чи робоче дерево та індекс, пов'язані з репозиторієм, не мають незафіксованих змін у відстежуваних файлах. В іншому випадку програма видає повідомлення про помилку у форматі `Неможливо <дія>: <причина>. <підказка>` та завершує роботу. Приклад:
+
----------------
require_clean_work_tree rebase "Будь ласка, зафіксуйте або збережіть їх."
----------------

get_author_ident_from_commit::
	виводить код для використання з eval для встановлення змінних GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL та GIT_AUTHOR_DATE для заданого коміту.

create_virtual_base::
	змінює перший файл таким чином, що залишаються лише рядки, спільні з другим файлом. Якщо спільного матеріалу недостатньо, то перший файл залишається порожнім. Результат підходить як віртуальна база вхідних даних для 3-стороннього злиття.

GIT
---
Частина набору linkgit:git[1]
