git-rev-list(1)
===============

НАЗВА
-----
git-rev-list - Перелічує об'єкти комітів у зворотному хронологічному порядку


СИНОПСИС
--------
[verse]
'git rev-list' [<options>] <commit>... [--] [<path>...]

ОПИС
----

:git-rev-list: 1
include::rev-list-description.adoc[]

«rev-list» — це важлива команда Git, оскільки вона надає можливість створювати та переглядати графи предків комітів. З цієї причини вона має багато різних опцій, які дозволяють використовувати її такими різними командами, як «git bisect» та «git repack».

ОПЦІЇ
-----

:git-rev-list: 1
include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

ПРИКЛАДИ
--------

* Вивести список комітів, доступних з поточної гілки.
+
----------
git rev-list HEAD
----------

* Вивести список комітів у цій гілці, але тих, що відсутні у гілці upstream.
+
----------
git rev-list @{upstream}..HEAD
----------

* Форматуйте коміти з їхнім автором та повідомленням коміта (див. також посилання на linkgit:git-log[1]).
+
----------
git rev-list --format=medium HEAD
----------

* Форматувати коміти разом з їхніми різницями (див. також porcelain linkgit:git-log[1], який може зробити це за один процес).
+
----------
git rev-list HEAD |
git diff-tree --stdin --format=medium -p
----------

* Вивести список комітів у поточній гілці, які торкнулися будь-якого файлу в каталозі `Documentation`.
+
----------
git rev-list HEAD -- Документація/
----------

* Виведіть список комітів, створених вами за минулий рік, на будь-якій гілці, тегу чи іншому посиланні.
+
----------
git rev-list --author=you@example.com --since=1.year.ago --all
----------

* Вивести список об'єктів, досяжних з поточної гілки (тобто всі коміти та блоби й дерева, які вони містять).
+
----------
git rev-list --objects HEAD
----------

* Порівняйте розмір диска всіх доступних об'єктів з тими, що доступні з reflogs, та загальний розмір упакованого файлу. Це може показати вам, чи може виконання команди `git repack -ad` зменшити розмір репозиторію (шляхом видалення недоступних об'єктів), і чи можуть допомогти reflogs, термін дії яких закінчується.
+
----------
# reachable objects
git rev-list --disk-usage --objects --all
# plus reflogs
git rev-list --disk-usage --objects --all --reflog
# total disk size used
du -c .git/objects/pack/*.pack .git/objects/??/*
# alternative to du: add up "size" and "size-pack" fields
git count-objects -v
----------

* Повідомляти про розмір диска кожної гілки, не враховуючи об'єкти, що використовуються поточною гілкою. Це може виявити викиди, які сприяють роздуттю розміру репозиторію (наприклад, через те, що хтось випадково закомітив великі артефакти збірки).
+
----------
git for-each-ref --format='%(refname)' |
while read branch
do
	size=$(git rev-list --disk-usage --objects HEAD..$branch)
	echo "$size $branch"
done |
sort -n
----------

* Порівняйте розмір гілок на диску в одній групі посилань, виключаючи іншу. Якщо ви змішуєте об'єкти з кількох віддалених серверів в одному репозиторії, це може показати, які віддалені сервери сприяють розміру репозиторію (беручи розмір `origin` за базовий).
+
----------
git rev-list --disk-usage --objects --remotes=$suspect --not --remotes=origin
----------

GIT
---
Частина набору linkgit:git[1]
