git-credential-cache(1)
=======================

НАЗВА
-----
git-credential-cache — Помічник для тимчасового зберігання паролів у памʼяті

СИНОПСИС
--------
-----------------------------
git config credential.helper 'cache [<options>]'
-----------------------------

ОПИС
----

Ця команда кешує облікові дані для використання майбутніми програмами Git. Збережені облікові дані зберігаються в памʼяті процесу cache-daemon (замість запису у файл) і забуваються після налаштованого тайм-ауту. Облікові дані забуваються швидше, якщо cache-daemon завершує роботу, наприклад, під час перезавантаження системи. Кеш доступний через сокет домену Unix, обмежений поточним користувачем правами файлової системи.

Скоріш за все, вам не треба викликати цю команду безпосередньо; вона призначена для використання як допоміжний засіб для роботи з обліковими даними іншими частинами Git. Див. linkgit:gitcredentials[7] або `ПРИКЛАДИ` нижче.

ОПЦІЇ
-----

--timeout <seconds>::

	Кількість секунд для кешування облікових даних (стандартно: 900).

--socket <path>::

	Використовуйте `<path>` для зв’язку з запущеним демоном кешу (або для запуску нового демона кешу, якщо він ще не запущений). Зазвичай використовується `$XDG_CACHE_HOME/git/credential/socket`, якщо не існує `~/.git-credential-cache/`, у цьому випадку замість нього використовується `~/.git-credential-cache/socket`. Якщо ваша домашня тека знаходиться у файловій системі, підключеній через мережу, можливо, вам доведеться змінити це на локальну файлову систему. Ви повинні вказати абсолютний шлях.

КЕРУВАННЯ ДЕМОНОМ
-----------------

Якщо ви хочете, щоб демон завершив роботу раніше, забуваючи всі кешовані облікові дані до закінчення терміну їхньої дії, ви можете виконати дію `exit`:

--------------------------------------
git credential-cache exit
--------------------------------------

ПРИКЛАДИ
--------

Мета цього помічника — зменшити кількість випадків, коли вам доводиться вводити ім’я користувача або пароль. Наприклад:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

[work for 5 more minutes]
$ git push http://example.com/repo.git
[your credentials are used automatically]
------------------------------------

Ви можете надати параметри через змінну конфігурації credential.helper (у цьому прикладі час кешування збільшується до 1 години):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

ОСОБИСТІ ТОКЕНИ ДОСТУПУ
-----------------------

Деякі віддалені системи приймають особисті токени доступу, які генеруються випадковим чином і які важко запамʼятати. Зазвичай термін їх дії становить кілька тижнів або місяців.

git-credential-cache за своєю суттю непридатний для постійного зберігання особистих токенів доступу. Облікові дані будуть забуті після закінчення часу очікування кешу. Навіть якщо ви налаштуєте тривалий час очікування, облікові дані будуть забуті, якщо демон завершить роботу.

Щоб уникнути частого повторного створення особистих токенів доступу, налаштуйте допоміжний засіб облікових даних із постійним сховищем. Або ж налаштуйте допоміжний засіб облікових даних OAuth для автоматичної генерації облікових даних. Див. linkgit:gitcredentials[7], розділи «Доступні допоміжні засоби» та «OAuth».

GIT
---
Частина набору linkgit:git[1]
