git-commit-tree(1)
==================

НАЗВА
-----
git-commit-tree - Створіть новий об'єкт коміту


СИНОПСИС
--------
[verse]
'git commit-tree' <tree> [(-p <parent>)...]
'git commit-tree' [(-p <parent>)...] [-S[<keyid>]] [(-m <message>)...]
		  [(-F <file>)...] <tree>


ОПИС
----
Зазвичай кінцевий користувач не хоче запускати це безпосередньо. Натомість дивіться linkgit:git-commit[1].

Створює новий об'єкт коміту на основі наданого об'єкта дерева та виводить новий ідентифікатор об'єкта коміту на стандартний вивід. Повідомлення журналу зчитується зі стандартного вводу, якщо не задано опції `-m` або `-F`.

Опції `-m` та `-F` можна вводити будь-яку кількість разів у будь-якому порядку. Повідомлення журналу комітів буде складено в порядку вказівки опцій.

Об'єкт коміту може мати будь-яку кількість батьків. Якщо батьківський елемент рівно один, це звичайний коміт. Наявність кількох батьківських елементів робить коміт злиттям кількох рядків історії. Початкові (кореневі) коміти не мають батьківських елементів.

Хоча дерево представляє певний стан робочого каталогу, коміт представляє цей стан у "часі" та пояснює, як туди потрапити.

Зазвичай коміт визначає новий стан "HEAD", і хоча Git не хвилює, де ви зберігаєте примітку про цей стан, на практиці ми схильні просто записувати результат у файл, на який вказує `.git/HEAD`, щоб ми завжди могли бачити, яким був останній закомітований стан.

ОПЦІЇ
-----
<tree>::
	Існуючий об'єкт дерева.

-p <parent>::
	Кожен `-p` вказує ідентифікатор батьківського об'єкта коміту.

-m <message>::
	Абзац у повідомленні журналу комітів. Його можна вказати більше одного разу, і кожне <повідомлення> стає окремим абзацом.

-F <file>::
	Зчитати повідомлення журналу комітів з заданого файлу. Використовуйте `-` для читання зі стандартного вводу. Це можна вказати більше одного разу, і вміст кожного файлу стає окремим абзацом.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	Коміти з підписом GPG. Аргумент `keyid` є необов'язковим і за замовчуванням використовує ідентифікатор комітера; якщо його вказано, він має бути прив'язаний до опції без пробілу. `--no-gpg-sign` корисний для скасування опції `--gpg-sign`, заданої раніше в командному рядку.

Інформація про коміти
---------------------

Коміт інкапсулює:

- всі ідентифікатори батьківських об'єктів
- ім'я автора, електронна адреса та дата
- ім'я та електронна адреса комітера, а також час коміту.

Коментар до коміту зчитується зі stdin. Якщо запис журналу змін не надано через перенаправлення "<", 'git commit-tree' просто чекатиме на його введення та завершиться символом ^D.

include::date-formats.adoc[]

Обговорення
-----------

include::i18n.adoc[]

ФАЙЛИ
-----
/etc/mailname

ДИВ. ТАКОЖ
----------
linkgit:git-write-tree[1] linkgit:git-commit[1]

GIT
---
Частина набору linkgit:git[1]
