git-whatchanged(1)
==================

НАЗВА
-----
git-whatchanged — Показ журналів з відмінностями, що вносяться кожним комітом


СИНОПСИС
--------
[synopsis]
git whatchanged <option>...

ПОПЕРЕДЖЕННЯ
------------
Команд `git whatchanged` застаріла і запланована до видалення в майбутній версії Git, оскільки це просто `git log` з іншими стандартними значеннями.

ОПИС
----

Показує журнали комітів та вивід різниці, що вносяться кожним комітом.

Новим користувачам рекомендується використовувати linkgit:git-log[1]. Команда `whatchanged` по суті така ж, як linkgit:git-log[1], але зазвичай відображає необроблений формат виводу diff та пропускає злиття:

----
git log --raw --no-merges
----

Команда збережена переважно з історичних причин; пальці багатьох людей, які вивчили Git задовго до винаходу `git log`, читаючи список розсилки ядра Linux, навчені її друкувати.


Приклади
--------
`git whatchanged -p v2.6.12.. include/scsi drivers/scsi`::

	Показати у вигляді латок коміти, починаючи з версії 'v2.6.12', які внесли зміни до будь-якого файлу у вкладених теках include/scsi або drivers/scsi

`git whatchanged --since="2 weeks ago" -- gitk`::

	Показати зміни за останні два тижні у файлі 'gitk'. Символ "--" необхідний, щоб уникнути плутанини з *гілкою* з назвою 'gitk'

GIT
---
Частина набору linkgit:git[1]
