git-check-mailmap(1)
====================

НАЗВА
-----
git-check-mailmap — Показ канонічних імен та адреси електронної пошти контактів


СИНОПСИС
--------
[verse]
'git check-mailmap' [<options>] <contact>...


ОПИС
----

Для кожного ``Name $$<user@host>$$'', ``$$<user@host>$$'' або ``$$user@host$$'' з командного рядка або стандартного вводу (при використанні `--stdin`) знаходить канонічне імʼя та адресу електронної пошти особи (див. "Зіставлення авторів" нижче). Якщо знайдено, виведе їх; інакше виводить вхідні дані як є.


ОПЦІЇ
-----
--stdin::
	Зчитувати контакти (по одному в рядку) зі стандартного вводу після вичерпання списку контактів, вказаних у командному рядку.

--mailmap-file=<файл>::
	Окрім будь-яких налаштованих файлів mailmap, зчитати вказаний файл mailmap. Записи в цьому файлі мають пріоритет над записами у стандартному файлі mailmap або в будь-якому налаштованому файлі mailmap.

--mailmap-blob=<blob>::
	Подібно до `--mailmap-file`, але значення слід розглядати як посилання на blob у репозиторії. Якщо вказано обидва параметри `--mailmap-file` та `--mailmap-blob`, записи у `--mailmap-file` матимуть пріоритет.

ВИВІД
-----

Для кожного контакту виводиться окремий рядок, що закінчується символом нового рядка. Якщо імʼя вказано або відоме 'mailmap', виводиться ``Name $$<user@host>$$''; інакше тільки ``$$<user@host>$$''.


КОНФІГУРАЦІЯ
------------

Дивіться `mailmap.file` та `mailmap.blob` у linkgit:git-config[1], щоб дізнатися, як вказати власний цільовий файл або обʼєкт `.mailmap`.


СПИСОК АВТОРІВ
--------------

Див. linkgit:gitmailmap[5].


GIT
---
Частина набору linkgit:git[1]
