git-name-rev(1)
===============

НАЗВА
-----
git-name-rev - Знайдіть символічні назви для заданих обертів


СИНОПСИС
--------
[verse]
'git name-rev' [--tags] [--refs=<pattern>]
	       ( --all | --annotate-stdin | <commit-ish>... )

ОПИС
----
Знаходить символічні імена, придатні для обробки людиною, для версій, заданих у будь-якому форматі, який можна проаналізувати за допомогою 'git rev-parse'.


ОПЦІЇ
-----

--tags::
	Не використовуйте назви гілок, а лише теги для найменування комітів

--refs=<pattern>::
	Використовуйте лише посилання, імена яких відповідають заданому шаблону оболонки. Шаблон може бути назвою гілки, назвою тегу або повною назвою посилання. Якщо задано кілька разів, використовуйте посилання, імена яких відповідають будь-якому з заданих шаблонів оболонки. Використовуйте `--no-refs`, щоб очистити будь-які попередньо задані шаблони посилань.

--exclude=<pattern>::
	Не використовуйте посилання, ім'я якого відповідає заданому шаблону оболонки. Шаблоном може бути назва гілки, назва тегу або повна назва посилання. Якщо вказано кілька разів, посилання буде виключено, якщо воно відповідає будь-якому з заданих шаблонів. При використанні разом з --refs, посилання буде використано як збіг лише тоді, коли воно відповідає принаймні одному шаблону --refs і не відповідає жодному шаблону --exclude. Використовуйте `--no-exclude`, щоб очистити список шаблонів виключення.

--all::
	Перерахувати всі коміти, доступні з усіх посилань

--annotate-stdin::
	Перетворити stdin, замінивши всі 40-символьні шістнадцяткові числа SHA-1 (наприклад, $hex) на "$hex ($rev_name)". При використанні з --name-only, замінити на "$rev_name", повністю пропускаючи $hex. Ця опція називалася `--stdin` у старіших версіях Git.
+
Наприклад:
+
-----------
$ cat sample.txt

Скорочена версія 2ae0a9cb82 не буде замінена.
Повна назва після заміни — 2ae0a9cb8298185a94e5998086f380a355dd8907,
а її об'єкт дерева — 70d105cc79e63b81cfdcb08a15297c23e60b07ad.

$ git name-rev --annotate-stdin <sample.txt

Скорочена версія 2ae0a9cb82 не буде замінена.
Повна назва після заміни — 2ae0a9cb8298185a94e5998086f380a355dd8907 (головна),
а її об'єкт дерева — 70d105cc79e63b81cfdcb08a15297c23e60b07ad.

$ git name-rev --name-only --annotate-stdin <sample.txt

Скорочена версія 2ae0a9cb82 не буде замінена.
Повна назва після заміни — master,
а її об'єкт дерева — 70d105cc79e63b81cfdcb08a15297c23e60b07ad
-----------

--name-only::
	Замість виведення SHA-1 та назви, виведіть лише назву. Якщо задано з --tags, звичайний префікс тегу "tags/" також опускається з назви, що ближче відповідає виводу `git-describe`.

--no-undefined::
	Виводити код помилки != 0, коли посилання не визначене, замість виведення `undefined`.

--always::
	Показувати унікально скорочений об'єкт коміту як резервний варіант.

ПРИКЛАДИ
--------

Враховуючи коміт, знайдіть його розташування відносно локальних посилань. Скажімо, хтось написав вам про той чудовий коміт 33db5f4d9027a10e477ccf054b2c1ab94f74c85a. Звичайно, ви дивитеся в коміт, але це показує лише те, що сталося, але не контекст.

Введіть 'git name-rev':

------------
% git name-rev 33db5f4d9027a10e477ccf054b2c1ab94f74c85a
33db5f4d9027a10e477ccf054b2c1ab94f74c85a tags/v0.99~940
------------

Тепер ви мудріші, бо знаєте, що це сталося за 940 ревізій до версії 0.99.

Ще одна приємна річ, яку ви можете зробити, це:

------------
% git log | git name-rev --annotate-stdin
------------

GIT
---
Частина набору linkgit:git[1]
