git-instaweb(1)
===============

НАЗВА
-----
git-instaweb - Миттєво переглядайте свій робочий репозиторій у gitweb

СИНОПСИС
--------
[verse]
'git instaweb' [--local] [--httpd=<httpd>] [--port=<port>]
               [--browser=<browser>]
'git instaweb' [--start] [--stop] [--restart]

ОПИС
----
Простий скрипт для налаштування `gitweb` та веб-сервера для перегляду локального репозиторію.

ОПЦІЇ
-----

-l::
--local::
	Прив’язуйте веб-сервер лише до локальної IP-адреси (127.0.0.1).

-d::
--httpd::
	Командний рядок демона HTTP, який буде виконано. Тут можна вказати параметри командного рядка, а файл конфігурації буде додано в кінці командного рядка. Наразі підтримуються apache2, lighttpd, mongoose, plackup, python та webrick. (За замовчуванням: lighttpd)

-m::
--module-path::
	Шлях до модуля (потрібен лише якщо httpd — це Apache). (За замовчуванням: /usr/lib/apache2/modules)

-p::
--port::
	Номер порту для прив'язки httpd. (За замовчуванням: 1234)

-b::
--browser::
	Веббраузер, який слід використовувати для перегляду сторінки gitweb. Його буде передано допоміжному скрипту 'git web{litdd}browse' разом з URL-адресою екземпляра gitweb. Див. linkgit:git-web{litdd}browse[1] для отримання додаткової інформації про це. Якщо скрипт завершиться невдачею, URL-адреса буде виведена на стандартний вивід.

старт::
--start::
	Запустіть екземпляр httpd та вийдіть з нього. За потреби згенеруйте файли конфігурації для створення нового екземпляра.

стоп::
--stop::
	Зупинити екземпляр httpd та вийти. Це не генерує жодних файлів конфігурації для створення нового екземпляра, а також не закриває браузер.

рестарт::
--restart::
	Перезапустіть екземпляр httpd та вийдіть. За потреби згенеруйте файли конфігурації для створення нового екземпляра.

КОНФІГУРАЦІЯ
------------

Ви можете вказати конфігурацію у вашому .git/config

-----------------------------------------------------------------------
[instaweb]
	local = true
	httpd = apache2 -f
	port = 4321
	browser = konqueror
	modulePath = /usr/lib/apache2/modules

-----------------------------------------------------------------------

Якщо змінна конфігурації `instaweb.browser` не встановлена, замість неї буде використано `web.browser`, якщо вона визначена. Див. linkgit:git-web{litdd}browse[1] для отримання додаткової інформації про це.

ДИВ. ТАКОЖ
----------
linkgit:gitweb[1]

GIT
---
Частина набору linkgit:git[1]
