git-log(1)
==========

НАЗВА
-----
git-log - Показати журнали комітів


СИНОПСИС
--------
[synopsis]
git log [<options>] [<revision-range>] [[--] <path>...]

ОПИС
----
Показує журнали комітів.

:git-log: 1
include::rev-list-description.adoc[]

Команда приймає опції, що застосовуються до команди linkgit:git-rev-list[1], щоб контролювати, що і як відображається, та опції, що застосовуються до команди linkgit:git-diff[1], щоб контролювати, як відображаються зміни, внесені кожним комітом.


ОПЦІЇ
-----

`--follow`::
	Продовжити перерахування історії файлу після перейменування (працює лише для одного файлу).

`--no-decorate`::
`--decorate[=(short|full|auto|no)]`::
	Виведіть назви посилань на будь-які показані коміти. Можливі значення:
+
----
`short`;; the ref name prefixes `refs/heads/`, `refs/tags/` and
	`refs/remotes/` are not printed.
`full`;; the full ref name (including prefix) is printed.
`auto`:: if the output is going to a terminal, the ref names
	are shown as if `short` were given, otherwise no ref names are
	shown.
----
+
Опція `--decorate` є скороченим варіантом для `--decorate=short`. За замовчуванням використовується значення конфігурації `log.decorate`, якщо налаштовано, інакше `auto`.

`--decorate-refs=<pattern>`::
`--decorate-refs-exclude=<pattern>`::
	Для кожного кандидата на посилання не використовуйте його для декорування, якщо воно відповідає будь-якому з параметрів _<pattern>_, заданих для `--decorate-refs-exclude`, або якщо воно не відповідає жодному з параметрів _<pattern>_, заданих для `--decorate-refs`. Параметр конфігурації `log.excludeDecoration` дозволяє виключати посилання з декорування, але явний шаблон `--decorate-refs` замінить збіг у `log.excludeDecoration`.
+
Якщо жодна з цих опцій або налаштувань конфігурації не вказана, то посилання використовуються як декоративні, якщо вони відповідають `HEAD`, `refs/heads/`, `refs/remotes/`, `refs/stash/` або `refs/tags/`.

`--clear-decorations`::
	Якщо вказано цей параметр, він очищає всі попередні параметри `--decorate-refs` або `--decorate-refs-exclude` та послаблює фільтр декорування за замовчуванням, щоб включити всі посилання. Цей параметр передбачається, якщо значення конфігурації `log.initialDecorationSet` встановлено на `all`.

`--source`::
	Виведіть ім'я посилання, вказане в командному рядку, за допомогою якого було досягнуто кожного коміту.

`--[no-]mailmap`::
`--[no-]use-mailmap`::
	Використовуйте файл mailmap для зіставлення імен авторів та комітерів, а також адрес електронної пошти з канонічними справжніми іменами та адресами електронної пошти. Див. linkgit:git-shortlog[1].

`--full-diff`::
	Без цього прапорця, `git log -p <шлях>...` показує коміти, що стосуються вказаних шляхів, та різниці щодо тих самих вказаних шляхів. З цим прапорцем, повна різниця відображається для комітів, що стосуються вказаних шляхів; це означає, що "`<шлях>...`" обмежує лише коміти та не обмежує різниці для цих комітів.
+
Зверніть увагу, що це впливає на всі типи виводу на основі diff, наприклад, ті, що створюються за допомогою `--stat` тощо.

`--log-size`::
	Включити рядок `log size <число`' у вивід для кожного коміту, де _<число>_ — це довжина повідомлення цього коміту в байтах. Призначено для пришвидшення роботи інструментів, які зчитують повідомлення журналу з виводу `git log`, дозволяючи їм заздалегідь виділяти місце.

include::line-range-options.adoc[]

_<revision-range>_::
	Показувати лише коміти у вказаному діапазоні версій. Якщо не вказано _<revision-range>_, за замовчуванням використовується значення `HEAD` (тобто вся історія, що веде до поточного коміту). `origin..HEAD` вказує всі коміти, доступні з поточного коміту (тобто `HEAD`), але не з `origin`. Повний список способів написання _<revision-range>_ див. у розділі «Визначення діапазонів» у linkgit:gitrevisions[7].

`[--] <path>...`::
	Показувати лише ті коміти, яких достатньо для пояснення того, як виникли файли, що відповідають зазначеним шляхам. Дивіться розділ «Спрощення історії» нижче для отримання детальної інформації та інших режимів спрощення.
+
Шляхи можуть потребувати префікса `--`, щоб відокремити їх від опцій або діапазону версій, у разі виникнення плутанини.

include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

ФОРМАТУВАННЯ РІЗНИЦЬ
--------------------

За замовчуванням, `git log` не генерує жодного виводу diff. Наведені нижче опції можна використовувати для відображення змін, внесених кожним комітом.

Зверніть увагу, що якщо явно не вказано один із варіантів `--diff-merges` (включаючи короткі опції `-m`, `-c`, `--cc` та `--dd`), коміти злиття не відображатимуть різницю, навіть якщо вибрано формат різниці, такий як `--patch`, а також не відповідатимуть опціям пошуку, таким як `-S`. Винятком є випадок, коли використовується `--first-parent`, і в цьому випадку `first-parent` є форматом за замовчуванням для комітів злиття.

:git-log: 1
:diff-merges-default: `off`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]

ПРИКЛАДИ
--------
`git log --no-merges`::

	Показати всю історію комітів, але пропустити будь-які злиття

`git log v2.6.12.. include/scsi drivers/scsi`::

	Показати всі коміти, починаючи з версії 'v2.6.12', які змінили будь-який файл у підкаталогах `include/scsi` або `drivers/scsi`

`git log --since="2 weeks ago" -- gitk`::

	Показати зміни за останні два тижні у файлі `gitk`. `--` необхідний, щоб уникнути плутанини з *гілкою* під назвою `gitk`

`git log --name-status release..test`::

	Показати коміти, що знаходяться у гілці "`test`", але ще не у гілці "`release`", разом зі списком шляхів, які змінює кожен коміт.

`git log --follow builtin/rev-list.c`::

	Показує коміти, що змінили `builtin/rev-list.c`, включаючи ті коміти, які відбулися до того, як файлу було надано його поточну назву.

`git log --branches --not --remotes=origin`::

	Показує всі коміти, що знаходяться в будь-якій з локальних гілок, але не в жодній з гілок віддаленого відстеження для `origin` (те, що у вас є, цього origin не відображає).

`git log master --not --remotes=*/master`::

	Показує всі коміти, що знаходяться в локальній головній гілці, але не в жодній з головних гілок віддаленого репозиторію.

`git log -p -m --first-parent`::

	Показує історію, включаючи відмінності змін, але лише з точки зору «головної гілки», пропускаючи коміти, що походять з об'єднаних гілок, та показуючи повні відмінності змін, внесених злиттями. Це має сенс лише за умови дотримання суворої політики об'єднання всіх тематичних гілок при залишанні на одній гілці інтеграції.

`git log -L '/int main/',/^}/:main.c`::

	Показує, як функція `main()` у файлі `main.c` розвивалася з часом.

`git log -3`::

	Обмежує кількість комітів для відображення до 3.

ОБГОВОРЕННЯ
-----------

include::i18n.adoc[]

КОНФІГУРАЦІЯ
------------

Дивіться linkgit:git-config[1] для основних змінних та linkgit:git-diff[1] для налаштувань, пов'язаних з генерацією різниці.

`format.pretty`::
	Значення за замовчуванням для опції `--format`. (Див. «Гарні формати» вище.) За замовчуванням `medium`.

`i18n.logOutputEncoding`::
	Кодування, яке використовуватиметься під час відображення журналів. (Див. розділ «Обговорення» вище.) За замовчуванням використовується значення `i18n.commitEncoding`, якщо встановлено, та UTF-8 в іншому випадку.

include::includes/cmd-config-section-rest.adoc[]

include::config/log.adoc[]

include::config/notes.adoc[]

GIT
---
Частина набору linkgit:git[1]
