git-shortlog(1)
===============

НАЗВА
-----
git-shortlog - Підсумувати вивід «git log»

СИНОПСИС
--------
[verse]
'git shortlog' [<options>] [<revision-range>] [[--] <path>...]
git log --pretty=short | 'git shortlog' [<options>]

ОПИС
----
Підсумовує вивід «git log» у форматі, придатному для включення до оголошень про реліз. Кожен коміт буде згруповано за автором та назвою.

Крім того, "[PATCH]" буде видалено з опису коміту.

Якщо в командному рядку не передаються жодні версії, і стандартний ввід не є терміналом, або поточної гілки немає, 'git shortlog' виведе зведений журнал, прочитаний зі стандартного вводу, без посилання на поточний репозиторій.

ОПЦІЇ
-----

-n::
--numbered::
	Сортувати вивід за кількістю комітів на автора, а не за алфавітом авторів.

-s::
--summary::
	Приховати опис комітів та надати лише зведення кількості комітів.

-e::
--email::
	Показати адресу електронної пошти кожного автора.

--format[=<format>]::
	Замість теми коміту використовуйте іншу інформацію для опису кожного коміту. '<format>' може бути будь-яким рядком, що приймається опцією `--format` 'git log', наприклад, '* [%h] %s'. (Див. розділ "PRETTY FORMATS" у linkgit:git-log[1].)
+
Кожен гарно надрукований коміт буде перегорнутий перед показом.

--date=<format>::
	Показувати дати, відформатовані відповідно до заданого рядка дати. (Див. опцію `--date` у розділі "Форматування комітів" у linkgit:git-log[1]). Корисно з `--group=format:<формат>`.

--group=<type>::
	Групування комітів на основі `<type>`. Якщо не вказано опцію `--group`, значенням за замовчуванням є `author`. `<type>` є одним із:
+
--
 - `author`, Коміти групуються за автором
 - `committer`, коміти групуються за комітером (так само, як `-c`)
 - `trailer:<field>`, `<field>` інтерпретується як трейлер повідомлення коміту без урахування регістру (див. linkgit:git-interpret-trailers[1]). Наприклад, якщо ваш проект використовує трейлери `Reviewed-by`, ви можете захотіти побачити, хто рецензував, за допомогою `git shortlog -ns --group=trailer:reviewed-by`.
 - `format:<формат>`, будь-який рядок, що приймається опцією `--format` команді 'git log'. (Див. розділ "PRETTY FORMATS" у linkgit:git-log[1].)
+
Зверніть увагу, що коміти, які не містять трейлера, не будуть враховані. Аналогічно, коміти з кількома трейлерами (наприклад, кілька підписань) можуть бути враховані більше одного разу (але лише один раз для кожного унікального значення трейлера в цьому коміті).
+
Shortlog спробує розібрати кожне значення трейлера як ідентифікатор `name <email>`. У разі успіху застосовується карта пошти, а електронна адреса пропускається, якщо не вказано опцію `--email`. Якщо значення не може бути розібране як ідентифікатор, воно буде сприйнято буквально та повністю.
--
+
Якщо `--group` вказано кілька разів, коміти враховуються для кожного значення (але знову ж таки, лише один раз для кожного унікального значення в цьому коміті). Наприклад, `git shortlog --group=author --group=trailer:co-authored-by` враховує як авторів, так і співавторів.

-c::
--committer::
	Це псевдонім для `--group=committer`.

-w[<width>[,<indent1>[,<indent2>]]]::
	Переносити рядки на інший рядок, використовуючи тег `width`. Перший рядок кожного запису має відступ на `indent1`, а другий та наступні рядки – на `indent2`. `width`, `indent1` та `indent2` за замовчуванням мають значення 76, 6 та 9 відповідно.
+
Якщо ширина дорівнює `0` (нулю), тоді зробіть відступ рядків виводу без їх перенесення.

<revision-range>::
	Показувати лише коміти у вказаному діапазоні версій. Якщо не вказано <revision-range>, за замовчуванням використовується значення `HEAD` (тобто вся історія, що веде до поточного коміту). `origin..HEAD` вказує всі коміти, доступні з поточного коміту (тобто `HEAD`), але не з `origin`. Повний список способів написання <revision-range> див. у розділі "Визначення діапазонів" у linkgit:gitrevisions[7].

[--] <path>...::
	Розгляньте лише ті коміти, яких достатньо для пояснення того, як виникли файли, що відповідають зазначеним шляхам.
+
Шляхи можуть потребувати префікса `--`, щоб відокремити їх від опцій або діапазону версій, у разі виникнення плутанини.

:git-shortlog: 1
include::rev-list-options.adoc[]

АВТОРИ КАРТОГРАФІЇ
------------------

Див. linkgit:gitmailmap[5].

Зверніть увагу, що якщо `git shortlog` запускається поза репозиторієм (для обробки вмісту журналу на стандартному вводі), він шукатиме файл `.mailmap` у поточному каталозі.

GIT
---
Частина набору linkgit:git[1]
