git-mv(1)
=========

НАЗВА
-----
git-mv - Переміщення або перейменування файлу, каталогу або символічного посилання


СИНОПСИС
--------

[synopsis]
git mv [-v] [-f] [-n] [-k] <source> <destination>
git mv [-v] [-f] [-n] [-k] <source>... <destination-directory>

ОПИС
----
Перемістити або перейменувати файл, каталог або символічне посилання.

У першій формі _<джерело>_, яке має існувати та бути файлом, символічним посиланням або каталогом, перейменовується на _<каталог-призначення>_. У другій формі _<каталог-призначення>_ має бути існуючим каталогом; вказані джерела будуть переміщені до цього каталогу.

Індекс оновлюється після успішного завершення, але зміни все одно необхідно зафіксувати.

ОПЦІЇ
-----
`-f`::
`--force`::
	Примусово перейменувати або перемістити файл, навіть якщо <призначення> існує.
`-k`::
	Пропустити дії переміщення або перейменування, які можуть призвести до помилки. Помилка виникає, коли джерело не існує та не контролюється Git, або коли воно перезаписує існуючий файл, якщо не вказано `-f`.
`-n`::
`--dry-run`::
	Нічого не робити; лише показати, що станеться

`-v`::
`--verbose`::
	Повідомляти імена файлів під час їх переміщення.

ПІДМОДУЛІ
---------
Переміщення підмодуля за допомогою gitfile (що означає, що вони були клоновані за допомогою Git версії 1.7.8 або новішої) оновить налаштування gitfile та core.worktree, щоб підмодуль працював у новому місці. Також буде зроблено спробу оновити налаштування `submodule.<name>.path` у файлі linkgit:gitmodules[5] та розмістити цей файл (якщо не використовується `-n`).

ПОМИЛКИ
-------
Щоразу, коли оновлення суперпроекту переміщує заповнений підмодуль (наприклад, під час перемикання між комітами до та після переміщення), застаріле отримання підмодуля залишатиметься у старому місці, а в новому місці з'явиться порожній каталог. Щоб знову заповнити підмодуль у новому місці, користувачеві доведеться виконати команду "git submodule update". Видалення старого каталогу безпечне лише тоді, коли він використовує git-файл, оскільки інакше історія підмодуля також буде видалена. Обидва кроки будуть застарілими після реалізації рекурсивного оновлення підмодуля.

GIT
---
Частина набору linkgit:git[1]
