git-stripspace(1)
=================

НАЗВА
-----
git-stripspace - Видаліть непотрібні пробіли


СИНОПСИС
--------
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

ОПИС
----

Зчитувати текст, такий як повідомлення комітів, нотатки, теги та описи гілок, зі стандартного вводу та очищати його так, як це використовується Git.

Без аргументів це буде так:

- видалити пробіли в кінці всіх рядків
- згорнути кілька послідовних порожніх рядків в один порожній рядок
- видалити порожні рядки з початку та кінця вхідних даних
- за потреби додайте відсутній символ '\n' до останнього рядка.

У випадку, якщо вхідні дані повністю складаються з пробільних символів, вивід не буде створено.

*ПРИМІТКА*: Це призначено для очищення метаданих. Для виправлення пробілів у патчах або файлах у репозиторії надайте перевагу режиму `--whitespace=fix` у linkgit:git-apply[1].

ОПЦІЇ
-----
-s::
--strip-comments::
	Пропустити та видалити всі рядки, що починаються з символу коментаря (`core.commentChar`, за замовчуванням `#`).

-c::
--comment-lines::
	Додайте символ коментаря та пробіл до кожного рядка. Рядки автоматично завершуватимуться символом нового рядка. У порожніх рядках буде додано лише символ коментаря.

ПРИКЛАДИ
--------

Враховуючи наступний шумний вхідний код, де '$' вказує на кінець рядка:

---------
|A brief introduction   $
|   $
|$
|A new paragraph$
|# with a commented-out line    $
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out. $
|      $
|The end.$
|  $
---------

Використайте 'git stripspace' без аргументів, щоб отримати:

---------
|A brief introduction$
|$
|A new paragraph$
|# with a commented-out line$
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out.$
|$
|The end.$
---------

Використайте 'git stripspace --strip-comments', щоб отримати:

---------
|A brief introduction$
|$
|A new paragraph$
|explaining lots of stuff.$
|$
|The end.$
---------

GIT
---
Частина набору linkgit:git[1]
