git-check-ignore(1)
===================

НАЗВА
-----
git-check-ignore - Налагодження файлів gitignore / виключення


СИНОПСИС
--------
[verse]
'git check-ignore' [<options>] <pathname>...
'git check-ignore' [<options>] --stdin

ОПИС
----

Для кожного шляху, заданого через командний рядок або з файлу через `--stdin`, перевірити, чи файл виключено .gitignore (або іншими вхідними файлами для механізму виключення), та вивести шлях, якщо він виключений.

За замовчуванням відстежувані файли взагалі не відображаються, оскільки вони не підпадають під правила виключення; але див. `--no-index'.

ОПЦІЇ
-----
-q::
--quiet::
	Нічого не виводити, просто встановити статус виходу. Це дійсне лише з одним шляхом.

-v::
--verbose::
	Замість того, щоб виводити виключені шляхи, для кожного шляху, який відповідає шаблону виключення, виведіть шаблон виключення разом зі шляхом. (Збіг зі шаблоном виключення зазвичай означає, що шлях виключено, але якщо шаблон починається з "`!", то це заперечений шаблон, і збіг з ним означає, що шлях НЕ виключено.)
+
Щодо правил пріоритету всередині та між виключеними джерелами, див. linkgit:gitignore[5].

--stdin::
	Зчитувати імена шляхів зі стандартного вводу, по одному на рядок, замість того, щоб читати їх з командного рядка.

-z::
	Формат виводу змінено для машинного аналізу (див. нижче). Якщо також задано `--stdin`, вхідні шляхи розділяються символом NUL замість символу переведення рядка.

-n::
--non-matching::
	Показати задані шляхи, які не відповідають жодному шаблону. Це має сенс лише тоді, коли ввімкнено `--verbose`, інакше неможливо було б розрізнити шляхи, що відповідають шаблону, від тих, що ні.

--no-index::
	Не дивіться в індекс під час виконання перевірок. Це можна використовувати для налагодження, чому шлях став відстежуватися, наприклад, за допомогою `git add .`, і не був ігнорований правилами, як очікував користувач, або під час розробки шаблонів, що включають заперечення, для відповідності шляху, попередньо доданому за допомогою `git add -f`.

ВИХІД
-----

За замовчуванням буде виведено будь-який із заданих шляхів, що відповідає шаблону ігнорування, по одному на рядок. Якщо жоден шаблон не відповідає заданому шляху, для цього шляху нічого не буде виведено; це означає, що шлях не буде ігноровано.

Якщо вказано `--verbose`, вивід буде послідовністю рядків такого вигляду:

<source> <COLON> <linenum> <COLON> <pattern> <HT> <pathname>

<pathname> – це шлях до файлу, до якого запитується запит, <pattern> – це відповідний шаблон, <source> – це вихідний файл шаблону, а <linenum> – це номер рядка шаблону в цьому джерелі. Якщо шаблон містив префікс "`!`" або суфікс "`/`", він буде збережений у виводі. <source> буде абсолютним шляхом при посиланні на файл, налаштований за допомогою `core.excludesFile`, або відносним до кореневого каталогу репозиторію при посиланні на `.git/info/exclude` або файл виключень для кожного каталогу.

Якщо вказано `-z`, шляхи у виводі розділяються нульовим символом; якщо також вказано `--verbose`, то замість двокрапок та жорсткої табуляції також використовуються нульові символи:

<source> <NULL> <linenum> <NULL> <pattern> <NULL> <pathname> <NULL>

Якщо вказано `-n` або `--non-matching`, також будуть виведені невідповідні шляхи, і в цьому випадку всі поля в кожному вихідному записі, крім <pathname>, будуть порожніми. Це може бути корисним під час неінтерактивного виконання, щоб файли можна було поступово передавати на STDIN тривалого процесу перевірки-ігнорування, і для кожного з цих файлів STDOUT вказуватиме, чи відповідає цей файл шаблону чи ні. (Без цієї опції було б неможливо визначити, чи означає відсутність виводу для даного файлу, що він не відповідає жодному шаблону, чи що вивід ще не був згенерований.)

Буферизація відбувається, як описано в опції `GIT_FLUSH` у linkgit:git[1]. Викликаюча сторона відповідає за уникнення блокувань, спричинених переповненням вхідного буфера або читанням з порожнього вихідного буфера.

СТАТУС ВИХОДУ
-------------

0::
	Один або декілька наданих шляхів ігноруються.

1::
	Жоден із наданих шляхів не ігнорується.

128::
	Сталася фатальна помилка.

ДИВ. ТАКОЖ
----------
linkgit:gitignore[5] linkgit:git-config[1] linkgit:git-ls-files[1]

GIT
---
Частина набору linkgit:git[1]
