git-archimport(1)
=================

НАЗВА
-----
git-archimport — Імпорт репозиторію GNU Arch у Git


СИНОПСИС
--------
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <depth>] [-t <tempdir>]
	       <archive>/<branch>[:<git-branch>]...

ОПИС
----
Імпортує проєкт з одного або декількох репозиторіїв GNU Arch. Буде слідувати гілкам та репозиторіям у просторах імен, визначених за допомогою наданих параметрів <archive>/<branch>. Якщо не вдасться знайти віддалену гілку, з якої походить злиття, проєкт просто імпортується як звичайний коміт. Якщо ж гілку вдасться знайти, вона буде позначена як злиття, коли це можливо (див. пояснення нижче).

Скрипт очікує, що ви вкажете кореневі теки, з яких він зможе розпочати імпорт з коміту Arch типу «initial import» або «tag». Він буде відстежувати та імпортувати нові гілки в межах вказаних коренів.

Інструмент розрахований на роботу лише з одним проєктом. Якщо він виявить гілки з різними коренями, він відмовиться працювати. У такому випадку відредагуйте параметри <archive>/<branch>, щоб чітко визначити область імпорту.

'git archimport' активно використовує `tla` у фоновому режимі для доступу до репозиторію Arch. Переконайтеся, що у вас є остання версія `tla`, доступна у шляху. `tla` повинен знати про репозиторії, які ви передаєте до 'git archimport'.

Під час початкового імпорту команда «git archimport» очікує, що вона знаходиться в порожній теці. Щоб стежити за розвитком проєкту, який використовує Arch, запустіть команду «git archimport» знову з тими самими параметрами, що й під час початкового імпорту, щоб виконати інкрементний імпорт.

Хоча «git archimport» намагатиметься створити зрозумілі назви гілок для архівів, які він імпортує, також можна вказати назви гілок Git вручну. Для цього вкажіть назву гілки Git після кожного параметра <archive>/<branch>, відділивши її двокрапкою. Таким чином, ви можете скоротити назви гілок Arch та перетворити жаргон Arch на жаргон Git, наприклад, зіставивши гілку "PROJECT{litdd}devo{litdd}VERSION" з "master".

Можна пов’язати кілька гілок Arch з однією гілкою Git; такий підхід буде доцільним лише в тому випадку, якщо після створення другої гілки в першу гілку не буде внесено жодних комітів. Проте це корисно для перетворення репозиторіїв Arch, які періодично оновлювалися.


ОБʼЄДНАННЯ
----------
Дані про злиття латок з Arch використовуються також для позначення злиття в Git. Git не приділяє великої уваги відстеженню латок і вважає злиттям лише той випадок, коли гілка включає всі коміти, зроблені з моменту її відгалуження. У результаті Git отримує чітке уявлення про те, наскільки гілки розійшлися. Отже, під час імпортування втрачається частина метаданих про обмін латками.

На щастя, коли ви намагаєтеся об’єднати гілки, імпортовані з Arch, Git знайде оптимальну базу для злиття і, швидше за все, виявить латки, які були перенесені між гілками у неправильній послідовності.

ОПЦІЇ
-----

-h::
	Показати довідку з використання.

-v::
	Докладний вивід.

-T::
	Багато тегів. Створить тег для кожного коміту, що відображає назву коміту в репозиторії Arch.

-f::
	Використовувати стратегію швидкого імпорту набору латок. Це може бути значно швидше для великих дерев, але не дозволяє обробляти перейменування тек або зміни прав доступу. Стандартна стратегія є повільною, але безпечною.

-o::
	Використовуйте цю опцію для забезпечення сумісності зі старими іменами гілок, які використовувалися в попередніх версіях 'git archimport'. Старі імена гілок мали вигляд category{litdd}branch, тоді як нові імена гілок мають вигляд archive,category{litdd}branch{litdd}version. В обох випадках імена, вказані в командному рядку, замінять автоматично згенеровані.

-D <depth>::
	Слідувати за обʼєднаним предком і спробувати імпортувати дерева, з яких було здійснено об’єднання. Вкажіть глибину, більшу за 1, якщо журнали змін були очищені.

-a::
	Спробувати автоматично зареєструвати архіви за адресою `http://mirrors.sourcecontrol.net`. Це особливо корисно при використанні опції -D.

-t <tmpdir>::
	Перевизначити стандартну теку tempdir.


<archive>/<branch>::
	Ідентифікатор <archive>/<branch> у форматі, який розуміє `tla log`.


GIT
---
Частина набору linkgit:git[1]
