git-prune(1)
============

НАЗВА
-----
git-prune - Видалити всі недоступні об'єкти з бази даних об'єктів


СИНОПСИС
--------
[verse]
'git prune' [-n] [-v] [--progress] [--expire <time>] [--] [<head>...]

ОПИС
----

NOTE: У більшості випадків користувачам слід виконати «git gc», що викликає «git prune». Див. розділ «ПРИМІТКИ» нижче.

Ця команда виконує 'git fsck --unreachable', використовуючи всі посилання, доступні в `refs/`, за бажанням з додатковим набором об'єктів, зазначеним у командному рядку, та видаляє всі розпаковані об'єкти, недоступні для будь-якого з цих головних об'єктів з бази даних об'єктів. Крім того, вона видаляє розпаковані об'єкти, які також знаходяться в пакетах, за допомогою команди 'git prune-packed'. Вона також видаляє записи з .git/shallow, які недоступні для жодного посилання.

Зверніть увагу, що недоступні, упаковані об'єкти залишаться. Якщо це небажано, див. linkgit:git-repack[1].

ОПЦІЇ
-----

-n::
--dry-run::
	Не видаляйте нічого; просто повідомте, що це призведе до видалення.

-v::
--verbose::
	Повідомте про всі видалені об'єкти.

--progress::
	Показати прогрес.

--expire <time>::
	Закінчується термін дії лише для вільних об'єктів, старших за <time>.

\--::
	Не інтерпретуйте жодних додаткових аргументів як варіанти.

<head>...::
	Окрім об’єктів, досяжних з будь-якого з наших посилань, збережіть об’єкти, досяжні з перелічених <head>.

ПРИКЛАДИ
--------

Щоб видалити об'єкти, які не використовуються вашим репозиторієм або іншим, що запозичує дані з вашого репозиторію через його `.git/objects/info/alternates`:

------------
$ git prune $(cd ../another && git rev-parse --all)
------------

НОТАТКИ
-------

У більшості випадків користувачам не потрібно буде викликати «git prune» безпосередньо, а натомість слід викликати «git gc», який обробляє скорочення разом з багатьма іншими завданнями з обслуговування.

Опис об'єктів, які розглядаються для скорочення, дивіться у параметрі --unreachable у 'git fsck'.

ДИВ. ТАКОЖ
----------

linkgit:git-fsck[1], linkgit:git-gc[1], linkgit:git-reflog[1]

GIT
---
Частина набору linkgit:git[1]
