git-http-push(1)
================

НАЗВА
-----
git-http-push - Пересилання об'єктів через HTTP/DAV до іншого репозиторію


СИНОПСИС
--------
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ref> [<ref>...]

ОПИС
----
Надсилає відсутні об'єкти до віддаленого репозиторію та оновлює віддалену гілку.

*ПРИМІТКА*: Ця команда тимчасово вимкнена, якщо ваша libcurl старіша за 7.16, оскільки повідомлялося, що ця комбінація не працює та іноді пошкоджує репозиторій.

ОПЦІЇ
-----
--all::
	Не вважайте, що віддалений репозиторій завершений у своєму поточному стані, і перевірте, чи всі об'єкти в історії всієї локальної бази даних існують у віддаленому репозиторії.

--force::
	Зазвичай команда відмовляється оновлювати віддалене посилання, яке не є предком локального посилання, що використовується для його перезапису. Цей прапорець вимикає перевірку. Це означає, що віддалений репозиторій може втратити коміти; використовуйте його обережністю.

--dry-run::
	Зробіть усе, крім надсилання оновлень.

--verbose::
	Повідомити список об'єктів, що обробляються локально, та список об'єктів, успішно надісланих до віддаленого репозиторію.

-d::
-D::
	Видалити <ref> з віддаленого репозиторію. Вказана гілка не може бути віддаленою HEAD. Якщо вказано -d, також мають бути виконані такі інші умови:

	- Віддалений HEAD має визначати об'єкт, який існує локально
	- Зазначена гілка веде до об'єкта, який існує локально
	- Вказана гілка є предком віддаленої HEAD

<ref>...::
	Віддалені посилання для оновлення.


ВКАЗАННЯ ПОСИЛАНЬ
-----------------

Специфікація '<ref>' може бути або окремим шаблоном, або парою таких шаблонів, розділених двокрапкою ":" (це означає, що назва посилання не може містити двокрапку). Окремий шаблон '<name>' – це просто скорочення від '<name>:<name>'.

Кожна пара шаблонів '<src>:<dst>' складається з вихідної сторони (до двокрапки) та цільової сторони (після двокрапки). Посилання, яке потрібно вставити, визначається шляхом пошуку відповідності, що відповідає вихідній стороні, а місце, куди воно буде вставлено, визначається за допомогою цільової сторони.

 - Це помилка, якщо '<src>' не відповідає точно одному з локальних посилань.

 - Якщо '<dst>' не відповідає жодному віддаленому посиланню,

   * воно має починатися з "refs/"; у цьому випадку <dst> використовується як пункт призначення буквально.

   * <src> == <dst>, а посилання, яке збіглося з <src>, не повинно існувати в наборі віддалених посилань; посилання, яке локально збіглося з <src>, використовується як назва призначення.

Без `--force`, посилання <src> зберігається на віддаленому сервері лише якщо <dst> не існує або <dst> є належною підмножиною (тобто предком) <src>. Ця перевірка, відома як "перевірка швидкого перезапису", виконується, щоб уникнути випадкового перезапису віддаленого посилання та втрати комітів інших користувачів звідти.

З параметром `--force` перевірка швидкого перемотування вперед вимикається для всіх посилань.

За бажанням, параметр <ref> може мати префікс із знаком «+», щоб вимкнути перемотку лише для цього посилання.

GIT
---
Частина набору linkgit:git[1]
