git-check-mailmap(1)
====================

НАЗВА
-----
git-check-mailmap - Показувати канонічні імена та адреси електронної пошти контактів


СИНОПСИС
--------
[verse]
'git check-mailmap' [<options>] <contact>...


ОПИС
----

Для кожного ``Name $$<user@host>$$'', ``$$<user@host>$$'' або ``$$user@host$$'' з командного рядка або стандартного вводу (при використанні `--stdin`) знайдіть канонічне ім'я та адресу електронної пошти особи (див. "Відображення авторів" нижче). Якщо знайдено, виведіть їх; інакше виведіть вхідні дані як є.


ОПЦІЇ
-----
--stdin::
	Зчитує контакти, по одному на рядок, зі стандартного вводу після вичерпання контактів, наданих у командному рядку.

--mailmap-file=<файл>::
	Окрім будь-яких налаштованих файлів mailmap, зчитати вказаний файл mailmap. Записи в цьому файлі мають пріоритет над записами у файлі mailmap за замовчуванням або в будь-якому налаштованому файлі mailmap.

--mailmap-blob=<blob>::
	Подібно до `--mailmap-file`, але значення слід розглядати як посилання на blob у репозиторії. Якщо вказано обидва параметри `--mailmap-file` та `--mailmap-blob`, записи у `--mailmap-file` матимуть пріоритет.

ВИХІД
-----

Для кожного контакту виводиться окремий рядок, що закінчується символом нового рядка. Якщо ім'я вказано або відоме «mailmap», друкується ``Name $$<user@host>$$''; інакше друкується лише ``$$<user@host>$$''.


КОНФІГУРАЦІЯ
------------

Дивіться `mailmap.file` та `mailmap.blob` у linkgit:git-config[1], щоб дізнатися, як вказати власний цільовий файл або об'єкт `.mailmap`.


АВТОРИ КАРТОГРАФІЇ
------------------

Див. linkgit:gitmailmap[5].


GIT
---
Частина набору linkgit:git[1]
