git-gui(1)
==========

НАЗВА
-----
git-gui - Портативний графічний інтерфейс для Git

СИНОПСИС
--------
[verse]
'git gui' [<command>] [<arguments>]

ОПИС
----
Графічний інтерфейс користувача для Git на основі Tcl/Tk. «git gui» дозволяє користувачам вносити зміни до свого репозиторію, створюючи нові коміти, вносячи зміни до існуючих, створюючи гілки, виконуючи локальні злиття та вибірку/надсилання до віддалених репозиторіїв.

На відміну від «gitk», «git gui» зосереджений на генерації комітів та анотації окремих файлів і не показує історію проєкту. Однак він пропонує пункти меню для запуску сеансу «gitk» з «git gui».

Відомо, що «git gui» працює на всіх популярних системах UNIX, Mac OS X та Windows (як під Cygwin, так і під MSYS). Наскільки це можливо, дотримуються правил користувацького інтерфейсу, специфічних для кожної ОС, що робить «git gui» досить нативним інтерфейсом для користувачів.

КОМАНДИ
-------
blame::
	Запустити програму перегляду звинувачень для вказаного файлу у вказаній версії (або робочому каталозі, якщо не вказано).

браузер::
	Запустити деревоподібний оглядач, що відображає всі файли у вказаному коміті. Файли, вибрані через оглядач, відкриваються у переглядачі звинувачень.

інструмент::
	Запустіть «git gui» та налаштуйте створення рівно одного коміту перед виходом та поверненням до оболонки. Інтерфейс обмежений лише діями комітів, що дещо зменшує час запуску програми та спрощує панель меню.

версія::
	Відобразити поточну версію «git gui».


Приклади
--------
`Як звинувачувати Makefile у git gui`::

	Показати вміст файлу «Makefile» у поточному робочому каталозі та надати анотації як для оригінального автора кожного рядка, так і для того, хто перемістив рядок у його поточне місцезнаходження. Незафіксований файл анотується, а незафіксовані зміни (якщо такі є) явно відносяться до «Ще не зафіксовано».

`git gui blame v0.99.8 Makefile`::

	Показати вміст «Makefile» у редакції «v0.99.8» та надати анотації для кожного рядка. На відміну від наведеного вище прикладу, файл зчитується з бази даних об'єктів, а не з робочого каталогу.

`git gui blame --line=100 Makefile`::

	Завантажує анотації, як описано вище, та автоматично прокручує вигляд до центру рядка «100».

`git gui citool`::

	Зробити один коміт і повернутися до оболонки після його завершення. Ця команда повертає ненульовий код виходу, якщо вікно було закрито будь-яким способом, окрім створення коміту.

`git gui citool --amend`::

	Автоматично перейти в режим інтерфейсу «Змінити останній коміт».

`git gui citool --nocommit`::

	Поводиться як звичайний citool, але замість створення коміту просто завершується з нульовим кодом виходу. Він все ще перевіряє, чи індекс не містить жодних необ'єднаних записів, тому ви можете використовувати його як графічну версію linkgit:git-mergetool[1]

`git citool`::

	Те саме, що `git gui citool` (above).

`git gui browser maint`::

	Показати браузер для дерева гілки 'maint'. Файли, вибрані в браузері, можна переглянути за допомогою вбудованого переглядача звинувачень.

ДИВ. ТАКОЖ
----------
linkgit:gitk[1]::
	Оглядач репозиторію Git. Показує гілки, історію комітів та відмінності між файлами. gitk — це утиліта, яка запускається діями Repository Visualize у «git gui».

Інше
----
«git gui» насправді підтримується як незалежний проект, але стабільні версії розповсюджуються як частина пакету Git для зручності кінцевих користувачів.

Офіційний репозиторій проєкту «git gui» можна знайти за адресою:

  https://github.com/j6t/git-gui

GIT
---
Частина набору linkgit:git[1]
