git-fmt-merge-msg(1)
====================

НАЗВА
-----
git-fmt-merge-msg— Створення повідомлень комітів злиття


СИНОПСИС
--------
[verse]
'git fmt-merge-msg' [-m <message>] [--into-name <branch>] [--log[=<n>] | --no-log]
'git fmt-merge-msg' [-m <message>] [--log[=<n>] | --no-log] -F <file>

ОПИС
----
Приймає список обʼєднаних обʼєктів зі стандартного вводу та формує відповідне повідомлення про коміт, яке буде використано для коміту злиття; зазвичай воно передається як аргумент '<merge-message>' команди 'git merge'.

Ця команда призначена здебільшого для внутрішнього використання скриптами, які автоматично викликають 'git merge'.

ОПЦІЇ
-----

--log[=<n>]::
	Окрім назв гілок, у повідомлення журналу додавати однорядкові описи з фактичних комітів, які об’єднуються. Буде використано не більше <n> комітів з кожного батьківського коміту злиття (20, якщо <n> не вказано). Це замінює значення змінної конфігурації `merge.log`.

--no-log::
	Не виводити однорядкові описи з самих комітів, що обʼєднуються.

--summary::
--no-summary::
	Синоніми до --log та --no-log; вони застарілі та будуть видалені в майбутньому.

-m <message>::
--message <message>::
	Використовуйте <message> замість назв гілок для першого рядка повідомлення журналу. Для використання з `--log`.

--into-name <branch>::
	Підготуйте повідомлення про злиття так, ніби злиття здійснюється з гілкою `<branch>`, замість назви реальної гілки, з якою виконується злиття.

-F <file>::
--file <file>::
	Використовувати список обʼєктів, які потрібно обʼєднати, із файлу <file> замість stdin.

КОНФІГУРАЦІЯ
------------
include::config/fmt-merge-msg.adoc[]

merge.summary::
	Синонім до `merge.log`; це застаріло та буде видалено в майбутньому.

ПРИКЛАДИ
--------

---------
$ git fetch origin master
$ git fmt-merge-msg --log <$GIT_DIR/FETCH_HEAD
---------

Виводить повідомлення журналу, що описує злиття гілки "master" з віддаленого сервера "origin".


ДИВ. ТАКОЖ
----------
linkgit:git-merge[1]

GIT
---
Частина набору linkgit:git[1]
