git-fsck(1)
===========

НАЗВА
-----
git-fsck - Перевіряє зв'язність та достовірність об'єктів у базі даних


СИНОПСИС
--------
[verse]
'git fsck' [--tags] [--root] [--unreachable] [--cache] [--no-reflogs]
	 [--[no-]full] [--strict] [--verbose] [--lost-found]
	 [--[no-]dangling] [--[no-]progress] [--connectivity-only]
	 [--[no-]name-objects] [--[no-]references] [<object>...]

ОПИС
----
Перевіряє зв'язність та достовірність об'єктів у базі даних.

ОПЦІЇ
-----
<object>::
	Об'єкт, який слід розглядати як початок трасування недосяжності.
+
Якщо об'єкти не вказано, 'git fsck' за замовчуванням використовує індексний файл, усі посилання SHA-1 у просторі імен `refs` та всі reflogs (якщо не вказано --no-reflogs) як заголовки.

--unreachable::
	Вивести об'єкти, які існують, але недоступні з жодного з опорних вузлів.

--dangling::
--no-dangling::
	Вивести об'єкти, які існують, але ніколи не використовуються «безпосередньо» (за замовчуванням). `--no-dangling` можна використовувати, щоб виключити цю інформацію з виводу.

--root::
	Звітувати про кореневі вузли.

--tags::
	Теги звітів.

--cache::
	Розгляньте будь-який об'єкт, записаний в індексі, також як головний вузол для трасування недосяжності.

--no-reflogs::
	Не вважайте коміти, на які посилається лише запис у рефлозі, досяжними. Ця опція призначена лише для пошуку комітів, які раніше були в посиланні, але тепер там немає, але все ще знаходяться у відповідному рефлозі.

--full::
	Перевіряти не лише об'єкти в GIT_OBJECT_DIRECTORY ($GIT_DIR/objects), але й ті, що знаходяться в альтернативних пулах об'єктів, перелічених у GIT_ALTERNATE_OBJECT_DIRECTORIES або $GIT_DIR/objects/info/alternates, а також в упакованих архівах Git, що знаходяться в $GIT_DIR/objects/pack та відповідних підкаталогах пакетів в альтернативних пулах об'єктів. Тепер це налаштування за замовчуванням; ви можете вимкнути його за допомогою --no-full.

--connectivity-only::
	Перевіряйте лише зв'язок досяжних об'єктів, переконавшись, що всі об'єкти, на які посилається досяжний тег, коміт або дерево, присутні. Це пришвидшує операцію, повністю уникаючи зчитування блобів (хоча все одно перевіряється наявність блобів, на які посилаються). Це виявить пошкодження в коммітах та деревах, але не виконає жодних семантичних перевірок (наприклад, на помилки форматування). Пошкодження в блоб-об'єктах взагалі не буде виявлено.
+
Також буде доступно недоступні теги, коміти та дерева для пошуку кінчиків залишків історії. Використовуйте `--no-dangling`, якщо вам не потрібен цей вивід і ви хочете ще більше пришвидшити його.

--strict::
	Увімкнути більш сувору перевірку, а саме перехопити режим файлу, записаний з встановленим бітом g+w, який був створений старими версіями Git. Існуючі репозиторії, включаючи ядро Linux, сам Git та розріджений репозиторій, мають старі об'єкти, які запускають цю перевірку, але рекомендується перевіряти нові проекти з цим прапорцем.

--verbose::
	Будьте балакучим.

--lost-found::
	Записуйте висячі об'єкти в .git/lost-found/commit/ або .git/lost-found/other/, залежно від типу. Якщо об'єкт є блоб-об'єктом, у файл записується його вміст, а не назва об'єкта.

--name-objects::
	Під час відображення імен досяжних об'єктів, окрім SHA-1, також відображати ім'я, яке описує, *як* вони досяжні, сумісно з linkgit:git-rev-parse[1], наприклад, `HEAD@{1234567890}~25^2:src/`.

--progress::
--no-progress::
	Стан виконання за замовчуванням повідомляється у стандартному потоці помилок, коли він підключений до терміналу, якщо не вказано --no-progress або --verbose. --progress примусово повідомляє про стан виконання, навіть якщо стандартний потік помилок не спрямовано до терміналу.

--references::
--no-references::
	Контролюйте, чи перевіряти узгодженість бази даних посилань за допомогою «git refs verify». Див. linkgit:git-refs[1] для отримання детальної інформації. За замовчуванням перевіряється база даних посилань.

КОНФІГУРАЦІЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/fsck.adoc[]

ОБГОВОРЕННЯ
-----------

git-fsck тестує SHA-1 та загальну справність об'єктів, а також повністю відстежує результуючу досяжність та все інше. Він виводить будь-які знайдені пошкодження (відсутні або пошкоджені об'єкти), а якщо ви використовуєте прапорець `--unreachable`, він також виводить об'єкти, які існують, але недоступні з жодного із зазначених головних вузлів (або набору за замовчуванням, як згадувалося вище).

Будь-які пошкоджені об'єкти, які вам доведеться знайти в резервних копіях або інших архівах (тобто ви можете просто видалити їх та виконати «rsync» з якимось іншим сайтом у надії, що хтось інший має пошкоджений вами об'єкт).

Якщо core.commitGraph має значення true, файл commit-graph також буде перевірено за допомогою 'git commit-graph verify'. Див. linkgit:git-commit-graph[1].

Витягнута діагностика
---------------------

недосяжний <type> <object>::
	На об'єкт <type> <object> фактично немає прямого чи опосередкованого посилання в жодному з виявлених дерев чи комітів. Це може означати, що є інший кореневий вузол, який ви не вказуєте, або що дерево пошкоджене. Якщо ви не пропустили кореневий вузол, то ви можете видалити недоступні вузли, оскільки їх не можна використовувати.

відсутній <type> <object>::
	На об'єкт <type> <object> є посилання, але він відсутній у базі даних.

звисаючий <type> <object>::
	Об'єкт <type> <object> присутній у базі даних, але ніколи не використовується «безпосередньо». Висячий коміт може бути кореневим вузлом.

невідповідність хешу <object>::
	База даних містить об'єкт, хеш якого не відповідає значенню об'єкта бази даних. Це вказує на серйозну проблему цілісності даних.


ПОВІДОМЛЕННЯ FSCK
-----------------

Нижче наведено типи помилок, які виявляє `git fsck`, та їх значення, а також рівень серйозності за замовчуванням. Серйозність помилки, окрім тих, що позначені як "(FATAL)", можна налаштувати, встановивши відповідну змінну конфігурації `fsck.<msg-id>`.

include::fsck-msgids.adoc[]


Змінні середовища
-----------------

GIT_OBJECT_DIRECTORY::
	використовується для визначення кореневого каталогу бази даних об'єктів (зазвичай $GIT_DIR/objects)

GIT_INDEX_FILE::
	використовується для визначення індексного файлу індексу

GIT_ALTERNATE_OBJECT_DIRECTORIES::
	використовується для визначення додаткових коренів бази даних об'єктів (зазвичай не встановлені)

GIT
---
Частина набору linkgit:git[1]
