git-mergetool{litdd}lib(1)
==========================

НАЗВА
-----
git-mergetool--lib — Набір скриптів оболонки для загального інструменту злиття Git

СИНОПСИС
--------
[verse]
'TOOL_MODE=(diff|merge) . "$(git --exec-path)/git-mergetool{litdd}lib"'

ОПИС
----

Це не та команда, яку кінцевий користувач хотів би запускати. Ніколи. Ця документація призначена для тих, хто вивчає скрипти на зразок Porcelain та/або пише нові.

Скрипт 'git-mergetool{litdd}lib' розроблений для використання іншими скриптами оболонки (використанням `.`) для налаштування функцій для роботи з інструментами злиття Git.

Перед отриманням 'git-mergetool{litdd}lib', ваш скрипт повинен встановити `TOOL_MODE`, щоб визначити режим роботи для функцій, перелічених нижче. 'diff' та 'merge' є допустимими значеннями.

ФУНКЦІЇ
-------
get_merge_tool::
	Повертає інструмент злиття. Код повернення — 1, якщо ми повернули вгаданий інструмент злиття, інакше — 0. '$GIT_MERGETOOL_GUI' можна встановити на 'true' для пошуку відповідного інструменту злиття.

get_merge_tool_cmd::
	Повертає власну команду для інструмента обʼєднання.

get_merge_tool_path::
	Повертає власний шлях для інструмента обʼєднання.

initialize_merge_tool::
	Вносить специфічні функції інструмента злиття в область видимості, щоб їх можна було використовувати або перевизначати.

run_merge_tool::
	Запускає інструмент обʼєднання, враховуючи назву інструмента та прапорець true/false, щоб вказати, чи присутня база обʼєднання. Для використання інструментом обʼєднання необхідно визначити '$MERGED', '$LOCAL', '$REMOTE' та '$BASE'.

GIT
---
Частина набору linkgit:git[1]
