git-whatchanged(1)
==================

НАЗВА
-----
git-whatchanged - Показати журнали з відмінностями, які вводить кожен коміт


СИНОПСИС
--------
[synopsis]
git whatchanged <option>...

ПОПЕРЕДЖЕННЯ
------------
`git whatchanged` застарів і заплановано до видалення в майбутній версії Git, оскільки це просто `git log` з іншими значеннями за замовчуванням.

ОПИС
----

Показує журнали комітів та вивід різниці, що вводяться кожним комітом.

Новим користувачам рекомендується використовувати linkgit:git-log[1]. Команда `whatchanged` по суті така ж, як linkgit:git-log[1], але за замовчуванням відображає необроблений формат виводу diff та пропускає злиття:

----
git log --raw --no-merges
----

Команда збережена переважно з історичних причин; пальці багатьох людей, які вивчили Git задовго до винаходу `git log`, читаючи список розсилки ядра Linux, навчені її друкувати.


Приклади
--------
`git whatchanged -p v2.6.12.. include/scsi drivers/scsi`::

	Показувати як патчі коміти, починаючи з версії 'v2.6.12', які змінили будь-який файл у підкаталогах include/scsi або drivers/scsi

`git whatchanged --since="2 тижнів тому" -- gitk`::

	Показати зміни за останні два тижні у файлі 'gitk'. Символ "--" необхідний, щоб уникнути плутанини з *гілкою* під назвою 'gitk'

GIT
---
Частина набору linkgit:git[1]
