git-request-pull(1)
===================

НАЗВА
-----
git-request-pull - Генерує зведення змін, що очікують на внесення

СИНОПСИС
--------
[verse]
'git request-pull' [-p] <start> <URL> [<end>]

ОПИС
----

Згенеруйте запит, який просить ваш проект, що розробляється, витягнути зміни до свого дерева. Запит, що виводиться на стандартний вивід, починається з опису гілки, підсумовує зміни та вказує, звідки їх можна витягнути.

Очікується, що проєкт, що розгортається, матиме коміт з назвою `<start>`, а вивід просить його інтегрувати зміни, внесені з моменту цього коміту, аж до коміту з назвою `<end>`, відвідавши репозиторій з назвою `<URL>`.


ОПЦІЇ
-----
-p::
	Включити текст патча у вивід.

<start>::
	Коміт, з якого потрібно почати. Це ім'я коміту, який вже є в історії основної версією.

<URL>::
	URL-адреса репозиторію, з якого буде витягнуто дані.

<end>::
	Закінчити коміт у (за замовчуванням HEAD). Це ім'я коміту на початку історії, яку ви просите витягнути.
+
Коли репозиторій з назвою `<URL>` має коміт на кінчику посилання, яке відрізняється від локального посилання, ви можете використовувати синтаксис `<local>:<remote>`, щоб отримати його локальну назву, двокрапку `:` та його віддалену назву.


ПРИКЛАДИ
--------

Уявіть, що ви зібрали свою роботу на гілці `master` поверх релізу `v1.0` і хочете інтегрувати її в проєкт. Спочатку ви надсилаєте цю зміну до свого публічного репозиторію, щоб інші могли її побачити:

	git push https://git.ko.xz/project master

Потім ви виконуєте цю команду:

	git request-pull v1.0 https://git.ko.xz/project master

що створить запит до основного репозиторію, підсумовуючи зміни між випуском `v1.0` та вашим `master`, щоб витягнути його з вашого публічного репозиторію.

Якщо ви відправили зміни до гілки, назва якої відрізняється від тієї, що у вас локально, наприклад.

	git push https://git.ko.xz/project master:for-linus

тоді ви можете попросити, щоб це витягнули

	git request-pull v1.0 https://git.ko.xz/project master:for-linus


GIT
---
Частина набору linkgit:git[1]
