git-diff-index(1)
=================

НАЗВА
-----
git-diff-index - Порівняти дерево з робочим деревом або індексом


СИНОПСИС
--------
[verse]
'git diff-index' [-m] [--cached] [--merge-base] [<common-diff-options>] <tree-ish> [<path>...]

ОПИС
----
Порівняйте вміст і режим блобів, знайдених в об'єкті дерева, з відповідними відстежуваними файлами в робочому дереві або з відповідними шляхами в індексі. Якщо присутні аргументи <шлях>, порівнюйте лише шляхи, що відповідають цим шаблонам. В іншому випадку порівнюються всі відстежувані файли.

ОПЦІЇ
-----
include::diff-options.adoc[]

<tree-ish>::
	Ідентифікатор об'єкта дерева, з яким потрібно порівняти.

--cached::
	Не враховуйте файл на диску взагалі.

--merge-base::
	Замість безпосереднього порівняння <tree-ish>, використовуйте базу злиття між <tree-ish> та HEAD. <tree-ish> має бути комітом.

-m::
	За замовчуванням файли, записані в індексі, але не витягнуті з реєстру, повідомляються як видалені. Цей прапорець змушує 'git diff-index' повідомляти, що всі невитягнуті файли є оновленими.

include::diff-format.adoc[]

РЕЖИМИ РОБОТИ
-------------
Ви можете вибрати, чи повністю довіряти індексному файлу (використовуючи прапорець `--cached`), чи попросити логіку diff показувати будь-які файли, які не відповідають стану stat, як "попередньо змінені". Обидві ці операції справді дуже корисні.

КЕШОВАНИЙ РЕЖИМ
---------------
Якщо вказано `--cached`, це дозволяє запитувати:

	покажіть мені відмінності між HEAD та поточним індексом
	вміст (той, який я б написав за допомогою 'git write-tree')

Наприклад, припустимо, що ви попрацювали над своїм робочим каталогом, оновили деякі файли в індексі та готові до коміту. Ви хочете точно побачити, *що* ви збираєтеся комітити, без необхідності писати новий об'єкт дерева та порівнювати його таким чином, і для цього ви просто робите

	git diff-index --cached HEAD

Приклад: скажімо, я перейменував `commit.c` на `git-commit.c` та виконав `update-index`, щоб це вплинуло на файл індексу. `git diff-files` взагалі нічого не покаже, оскільки файл індексу відповідає моєму робочому каталогу. Але виконання `git diff-index` призведе до:

  torvalds@ppc970:~/git> git diff-index --cached HEAD
  :100644 000000 4161aecc6700a2eb579e842af0b7f22b98443f74 0000000000000000000000000000000000000000 D	commit.c
  :000000 100644 0000000000000000000000000000000000000000 4161aecc6700a2eb579e842af0b7f22b98443f74 A	git-commit.c

Ви можете легко побачити, що вищезгадане є перейменуванням.

Фактично, `git diff-index --cached` *має* завжди бути повністю еквівалентним фактичному виконанню 'git write-tree' та його порівнянню. За винятком того, що цей варіант набагато зручніший для випадку, коли ви просто хочете перевірити, де ви знаходитесь.

Отже, виконання команди `git diff-index --cached` дуже корисне, коли ви запитуєте себе: «що я вже позначив для коміту, і яка різниця з попереднім деревом».

НЕКЕШОВАНИЙ РЕЖИМ
-----------------
Режим «без кешування» використовує інший підхід і потенційно є кориснішим з
двох, оскільки його дії не можна емулювати за допомогою «git write-tree» +
«git diff-tree». Таким чином, це режим за замовчуванням. Версія без
кешування ставить таке питання:

  Покажіть мені відмінності між HEAD та поточним взяттям
  дерево - вміст індексу _та_ файли, які не оновлені

що, очевидно, також дуже корисне питання, оскільки воно говорить вам про те, що ви *можете* закомітити. Знову ж таки, вивід точно відповідає виводу 'git diff-tree -r', але з невеликою родзинкою.

Різниця полягає в тому, що якщо якийсь файл не відповідає індексу, у нас немає резервного сховища для нього, і ми використовуємо магічний sha1 з "все-нульовим" кодом, щоб це показати. Отже, припустимо, що ви відредагували `kernel/sched.c`, але ще не виконали для нього 'git update-index' — з новим станом не пов'язано жодного "об'єкта", і ви отримуєте:

  torvalds@ppc970:~/v2.6/linux> git diff-index --abbrev HEAD
  :100644 100644 7476bb5ba 000000000 M	kernel/sched.c

тобто, це показує, що дерево змінилося, і що `kernel/sched.c` не оновлений і може містити нові дані. Нульовий sha1 означає, що для отримання справжньої різниці потрібно безпосередньо переглянути об'єкт у робочому каталозі, а не виконувати різницю між об'єктами.

NOTE: Як і інші команди цього типу, 'git diff-index' насправді взагалі не переглядає вміст файлу. Тож, можливо, `kernel/sched.c` насправді не змінився, а просто ви його торкнулися. У будь-якому випадку, варто зазначити, що вам потрібно виконати 'git update-index', щоб синхронізувати індекс.

NOTE: Ви можете мати різні файли, що відображаються одночасно як «оновлено» та «все ще пошкоджено в робочому каталозі». Ви завжди можете визначити, який файл у якому стані, оскільки файли зі статусом «оновлено» показують дійсний sha1, а файли зі статусом «не синхронізовано з індексом» завжди матимуть спеціальний sha1 з усіма нулями.

GIT
---
Частина набору linkgit:git[1]
