git-mergetool(1)
================

НАЗВА
-----
git-mergetool — Запуск інструментів розвʼязання конфліктів злиття для їх усунення

СИНОПСИС
--------
[synopsis]
git mergetool [--tool=<tool>] [-y | --[no-]prompt] [<file>...]

ОПИС
----

Використовуйте `git mergetool` для запуску однієї з кількох утиліт злиття для розвʼязання конфліктів злиття. Зазвичай запускають після `git merge`.

Якщо вказано один або кілька параметрів <file>, буде запущено програму-інструмент злиття для усунення розбіжностей у кожному файлі (файли без конфліктів пропускаються). Якщо вказано теку, до обробки будуть включені всі нерозвʼязані файли в цьому шляху. Якщо імена файлів _<file>_ не вказано, `git mergetool` запустить програму-інструмент злиття для кожного файлу, що містить конфлікти злиття.

ОПЦІЇ
-----
`-t <tool>`::
`--tool=<tool>`::
	Використовувати програму для розвʼязання конфліктів злиття, вказану в параметрі _<tool>_. Допустимі значення: `emerge`, `gvimdiff`, `kdiff3`, `meld`, `vimdiff` та `tortoisemerge`. Щоб переглянути список допустимих значень для параметра _<tool>_, виконайте команду `git mergetool --tool-help`.
+
Якщо програму для розвʼязання злиття не вказано, `git mergetool` використовуватиме змінну конфігурації `merge.tool`. Якщо змінна конфігурації `merge.tool` не встановлена, `git mergetool` вибере відповідне стандартне значення.
+
Ви можете явно вказати повний шлях до інструменту, встановивши змінну конфігурації `mergetool.<tool>.path`. Наприклад, ви можете налаштувати абсолютний шлях до kdiff3, встановивши `mergetool.kdiff3.path`. В іншому випадку, `git mergetool` припускає, що інструмент доступний у `$PATH`.
+
Замість запуску однієї з відомих програм для злиття, `git mergetool` можна налаштувати на запуск іншої програми, вказавши командний рядок для її виклику у конфігураційній змінній `mergetool.<tool>.cmd`.
+
Коли `git mergetool` викликається за допомогою цього інструменту (через опцію `-t` або `--tool`, або змінну конфігурації `merge.tool`), налаштований командний рядок буде викликано з `BASE`, встановленим на імʼя тимчасового файлу, що містить загальну базу для злиття, якщо така є; `LOCAL`, встановленим на імʼя тимчасового файлу, що містить вміст файлу в поточній гілці; `REMOTE`, встановленим на імʼя тимчасового файлу, що містить вміст файлу, який потрібно обʼєднати, та `MERGED`, встановленим на імʼя файлу, в який інструмент злиття має записати результат розвʼязання злиття.
+
Якщо власний інструмент злиття за допомогою коду завершення правильно вказує на успішне вирішення конфлікту, то для змінної конфігурації `mergetool.<tool>.trustExitCode` можна встановити значення `true`. В іншому випадку `git mergetool` запропонує користувачеві підтвердити успішність розвʼязання конфлікту після завершення роботи власного інструменту користувача.

`--tool-help`::
	Вивести список інструментів обʼєднання, які можна використовувати з `--tool`.

`-y`::
`--no-prompt`::
	Не запитувати перед кожним викликом програми вирішення злиття. Це стандартне значення якщо програму розвʼязання злиття явно вказано за допомогою опції `--tool` або за допомогою змінної конфігурації `merge.tool`.

`--prompt`::
	Запитувати перед кожним викликом програми розвʼязання злиття, щоб дати користувачеві можливість пропустити шлях.

`-g`::
`--gui`::
	Коли `git-mergetool` викликається з опцією `-g` або `--gui`, інструмент стандартний злиття буде зчитуватися з налаштованої змінної `merge.guitool` замість `merge.tool`. Якщо `merge.guitool` не встановлено, ми повернемося до інструменту, налаштованого в `merge.tool`. Його можна вибрати автоматично за допомогою змінної конфігурації `mergetool.guiDefault`.

`--no-gui`::
	Цей параметр перевизначає попереднє налаштування `-g` або `--gui` або конфігурацію `mergetool.guiDefault` та зчитує стандартний інструмент злиття з налаштованої змінної `merge.tool`.

`-O<файл-порядку>`::
	Файли обробляються у порядку, вказаному у файлі _<orderfile>_, у якому в кожному рядку міститься один шаблон оболонки. Замінює значення змінної конфігурації `diff.orderFile` (див. linkgit:git-config[1]). Щоб скасувати дію `diff.orderFile`, використовуйте `-O/dev/null`.

КОНФІГУРАЦІЯ
------------
:git-mergetool: 1

include::includes/cmd-config-section-all.adoc[]

include::config/mergetool.adoc[]

ТИМЧАСОВІ ФАЙЛИ
---------------
`git mergetool` створює резервні копії файлів `*.orig` під час розвʼязання злиття. Їх можна безпечно видалити після обʼєднання файлу та завершення його сеансу `git mergetool`.

Встановлення змінної конфігурації `mergetool.keepBackup` на `false` призведе до того, що `git mergetool` автоматично видалятиме файли резервних копій після успішного обʼєднання файлів.

ПОРАДИ, ЩО СТОСУЮТЬСЯ БЕКЕНДУ
-----------------------------

vimdiff
~~~~~~~
include::mergetools/vimdiff.adoc[]

GIT
---
Частина набору linkgit:git[1]
