git-check-attr(1)
=================

НАЗВА
-----
git-check-attr - Відображення інформації про gitattributes


СИНОПСИС
--------
[verse]
'git check-attr' [--source <tree-ish>] [-a | --all | <attr>...] [--] <pathname>...
'git check-attr' --stdin [-z] [--source <tree-ish>] [-a | --all | <attr>...]

ОПИС
----
Для кожного шляху ця команда перерахує, чи кожен атрибут має значення «unspecified», «set» або «unset» як атрибут gitattribute для цього шляху.

ОПЦІЇ
-----
-a::
--all::
	Перелічіть усі атрибути, пов'язані із зазначеними шляхами. Якщо використовується ця опція, то «невизначені» атрибути не будуть включені до виводу.

--cached::
	Розгляньте `.gitattributes` лише в індексі, ігноруючи робоче дерево.

--stdin::
	Зчитувати імена шляхів зі стандартного вводу, по одному на рядок, а не з командного рядка.

-z::
	Формат виводу змінено для машинного аналізу. Якщо також задано параметр `--stdin`, вхідні шляхи розділяються символом NUL замість символу переведення рядка.

--source=<tree-ish>::
	Перевірити атрибути щодо зазначеного дерева. Зазвичай дерево вихідного коду вказують, називаючи коміт, гілку або тег, пов'язаний з ним.

\--::
	Інтерпретуйте всі попередні аргументи як атрибути, а всі наступні аргументи як імена шляхів.

Якщо жоден з параметрів `--stdin`, `--all` або `--` не використовується, перший аргумент буде розглядатися як атрибут, а решта аргументів — як шляхи.

ВИХІД
-----

Вивід має вигляд: <шлях> COLON SP <атрибут> COLON SP <інформація> LF

якщо тільки не діє `-z`, у цьому випадку як роздільник використовується NUL: <шлях> NUL <атрибут> NUL <інформація> NUL


<path> – це шлях до файлу, що запитується, <attribute> – це атрибут, що запитується, а <info> може бути одним із таких значень:

'unspecified';; коли атрибут не визначено для шляху.
'unset';;	коли атрибут визначено як хибний.
'set';;		коли атрибут визначено як істина.
<value>;;	коли атрибуту було присвоєно значення.

Буферизація відбувається, як описано в опції `GIT_FLUSH` у linkgit:git[1]. Викликаюча сторона відповідає за уникнення блокувань, спричинених переповненням вхідного буфера або читанням з порожнього вихідного буфера.

ПРИКЛАДИ
--------

У прикладах використовується наступний файл '.gitattributes':

---------------
*.java diff=java -crlf myAttr
NoMyAttr.java !myAttr
README caveat=unspecified
---------------

* Перелік одного атрибута:
+
---------------
$ git check-attr diff org/example/MyClass.java
org/example/MyClass.java: diff: java
---------------

* Перелік кількох атрибутів для файлу:
+
---------------
$ git check-attr crlf diff myAttr -- org/example/MyClass.java
org/example/MyClass.java: crlf: unset
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Перелік усіх атрибутів файлу:
+
---------------
$ git check-attr --all -- org/example/MyClass.java
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Перерахування атрибутів для кількох файлів:
+
---------------
$ git check-attr myAttr -- org/example/MyClass.java org/example/NoMyAttr.java
org/example/MyClass.java: myAttr: set
org/example/NoMyAttr.java: myAttr: unspecified
---------------

* Не всі значення однаково однозначні:
+
---------------
$ git check-attr caveat README
README: caveat: unspecified
---------------

ДИВ. ТАКОЖ
----------
linkgit:gitattributes[5].

GIT
---
Частина набору linkgit:git[1]
