git-fetch-pack(1)
=================

НАЗВА
-----
git-fetch-pack - Отримання відсутніх об'єктів з іншого репозиторію


СИНОПСИС
--------
[verse]
'git fetch-pack' [--all] [--quiet|-q] [--keep|-k] [--thin] [--include-tag]
	[--upload-pack=<git-upload-pack>]
	[--depth=<n>] [--no-progress]
	[-v] <repository> [<refs>...]

ОПИС
----
Зазвичай вам варто використовувати 'git fetch', що є обгорткою вищого рівня для цієї команди.

Викликає 'git-upload-pack' на можливо віддаленому репозиторії та запитує його надіслати об'єкти, відсутні в цьому репозиторії, для оновлення іменованих заголовків. Список комітів, доступних локально, виявляється шляхом сканування локальної ієрархії refs/ та надсилається до 'git-upload-pack', що працює на іншому кінці.

Ця команда дегенерує, завантажуючи все необхідне для виконання запитуваних посилань з віддаленої сторони, коли локальна сторона не має спільного предка-коміту.


ОПЦІЇ
-----
--all::
	Отримати всі віддалені референси.

--stdin::
	Взяти список посилань зі stdin, по одному на рядок. Якщо в командному рядку, окрім цього параметра, є посилання, вказані в stdin, тоді посилання зі stdin обробляються після тих, що в командному рядку.
+
Якщо разом із цією опцією вказано `--stateless-rpc`, то список посилань має бути у форматі пакета (pkt-line). Кожне посилання має бути в окремому пакеті, а список має закінчуватися пакетом flush.

-q::
--quiet::
	Передайте прапорець `-q` команді 'git unpack-objects'; це зробить процес клонування менш детальним.

-k::
--keep::
	Не викликати «git unpack-objects» для отриманих даних, а створити з них окремий файл packfile та зберегти його в базі даних об'єктів. Якщо параметр вказано двічі, то перепакування блокується.

--thin::
	Отримати "тонкий" пакет, який записує об'єкти у дельтифікованому вигляді на основі об'єктів, що не входять до пакету, для зменшення мережевого трафіку.

--include-tag::
	Якщо віддалена сторона підтримує це, об'єкти з анотаціями тегів будуть завантажені через те саме з'єднання, що й інші об'єкти, якщо завантажено об'єкт, на який посилається тег. В іншому випадку, викликаюча сторона повинна визначити теги, які ця опція зробила доступними.

--upload-pack=<git-upload-pack>::
	Використовуйте це, щоб вказати шлях до 'git-upload-pack' на віддаленому боці, якщо його немає у вашому $PATH. Встановлення sshd ігнорує скрипти налаштування середовища користувача для оболонок входу (наприклад, .bash_profile), і ваш приватно встановлений git може бути не знайдений у системному $PATH за замовчуванням. Іншим запропонованим способом вирішення є налаштування вашого $PATH у ".bashrc", але цей прапорець призначений для тих, хто не хоче платити за неінтерактивні оболонки, маючи простий файл .bashrc (вони налаштовують більшість речей у .bash_profile).

--exec=<git-upload-pack>::
	Те саме, що --upload-pack=<git-upload-pack>.

--depth=<n>::
	Обмежити вибірку ланцюжками предків довжиною не більше n. 'git-upload-pack' трактує спеціальну глибину 2147483647 як нескінченну, навіть якщо існує ланцюжок предків такої довжини.

--shallow-since=<дата>::
	Поглибити або скоротити історію поверхневого репозиторію, щоб включити всі доступні коміти після <дата>.

--shallow-exclude=<посилання>::
	Поглибити або скоротити історію поверхневого репозиторію, щоб виключити коміти, доступні з вказаної віддаленої гілки або тегу. Цей параметр можна вказати кілька разів.

--deepen-relative::
	Аргумент --depth визначає кількість комітів з поточної неглибокої межі, а не з кінця історії кожної віддаленої гілки.

--refetch::
	Пропускає узгодження комітів із сервером для отримання всіх відповідних об'єктів. Використовується для повторного застосування нового фільтра часткового клонування блобів/дерева.

--no-progress::
	Не показуйте прогрес.

--check-self-contained-and-connected::
	Виведіть "connectivity-ok", якщо отриманий пакет є автономним та підключеним.

-v::
	Виконуйте багатослівно.

<repository>::
	URL-адреса віддаленого репозиторію.

<refs>...::
	Віддалені заголовки, з яких потрібно оновлювати. Це значення залежить від $GIT_DIR (наприклад, "HEAD", "refs/heads/master"). Якщо не вказано, оновлювати з усіх заголовків, що є на віддаленій стороні.
+
Якщо на пульті дистанційного керування ввімкнено опції `uploadpack.allowTipSHA1InWant`, `uploadpack.allowReachableSHA1InWant` або `uploadpack.allowAnySHA1InWant`, вони можуть бути як 40-шістнадцяткові sha1, присутні на пульті дистанційного керування.

ДИВ. ТАКОЖ
----------
linkgit:git-fetch[1]

GIT
---
Частина набору linkgit:git[1]
