git-http-fetch(1)
=================

НАЗВА
-----
git-http-fetch — Завантаження з віддаленого репозиторію Git через HTTP


СИНОПСИС
--------
[verse]
'git http-fetch' [-c] [-t] [-a] [-d] [-v] [-w <filename>] [--recover] [--stdin | --packfile=<hash> | <commit>] <URL>

ОПИС
----
Завантажує віддалений репозиторій Git через HTTP.

Ця команда завжди отримує всі обʼєкти. Історично існувало три опції `-a`, `-c` та `-t` для вибору обʼєктів для завантаження. Зараз вони мовчки ігноруються.

ОПЦІЇ
-----
commit-id::
        Або хеш, або імʼя файлу в [URL]/refs/ для отримання.

-a::
-c::
-t::
	Ці опції ігноруються з історичних причин.

-v::
	Повідомити про те, що було завантажено.

-w <filename>::
Записує commit-id у вказаний файл у $GIT_DIR/refs/<filename> на локальному кінці після завершення передачі.

--stdin::
	Замість ідентифікатора коміта в командному рядку (що в цьому випадку не очікується), 'git http-fetch' очікує рядки на stdin у форматі

		<commit-id>['\t'<filename-as-in--w>]

--packfile=<hash>::
	Тільки для внутрішнього використання. Замість ідентифікатора коміта в командному рядку (що в цьому випадку не очікується), 'git http-fetch' отримує packfile безпосередньо за вказаною URL-адресою та використовує index-pack для генерації відповідних файлів .idx та .keep. Хеш використовується для визначення назви тимчасового файлу та є довільним. Вивід index-pack виводиться в stdout. Потрібно --index-pack-args.

--index-pack-args=<args>::
	Тільки для внутрішнього використання. Команда для виконання з вмістом завантаженого пакунка. Аргументи закодовані за URL-адресою та розділені пробілами.

--recover::
	Перевіряє, чи отримано все, що доступно з цілі. Використовується після переривання попередньої вибірки.

GIT
---
Частина набору linkgit:git[1]
