git-remote-ext(1)
=================

НАЗВА
-----
git-remote-ext - З'єднує розумний транспорт із зовнішньою командою.

СИНОПСИС
--------
[verse]
git remote add <nick> "ext::<command>[ <arguments>...]"

ОПИС
----
Цей віддалений помічник використовує вказану '<команда>' для підключення до віддаленого сервера Git.

Дані, записані на stdin зазначеної '<command>', вважаються надісланими на сервер git://, git-upload-pack, git-receive-pack або git-upload-archive (залежно від ситуації), а дані, зчитані зі stdout <command>, вважаються отриманими з того ж сервісу.

Команда та аргументи розділяються неекранованим пробілом.

Наступні послідовності мають особливе значення:

'% '::
	Літеральний пробіл у команді або аргументі.

'%%'::
	Буквальний знак відсотка.

'%s'::
	Замінюється назвою (receive-pack, upload-pack або upload-archive) служби, яку Git хоче викликати.

'%S'::
	Замінено довгою назвою (git-receive-pack, git-upload-pack або git-upload-archive) служби, яку Git хоче викликати.

'%G' (має бути першим символом аргументу)::
	Цей аргумент не буде передано до '<command>'. Натомість, він призведе до того, що допоміжна програма почне надсилати запити на обслуговування git:// віддаленій стороні, встановивши поле обслуговування на відповідне значення, а поле репозиторію — на решту аргументу. За замовчуванням такий запит не надсилати.
+
Це корисно, якщо до віддаленого сервера git:// звертаються через певний тунель.

'%V' (має бути першим символом аргументу)::
	Цей аргумент не буде передано до '<command>'. Натомість він встановлює поле vhost у запиті на сервіс git:// (для решти аргументу). За замовчуванням vhost у такому запиті (якщо його надіслано) не надсилається.

ЗМІННІ СЕРЕДОВИЩА
-----------------

GIT_TRANSLOOP_DEBUG::
	Якщо встановлено, виводить інформацію про налагодження різних операцій читання/запису.

ЗМІННІ СЕРЕДОВИЩА, ЩО ПЕРЕДАЮТЬСЯ ДО КОМАНДИ
--------------------------------------------

GIT_EXT_SERVICE::
	Встановіть довгу назву (git-upload-pack тощо) помічника сервісу, який потрібно викликати.

GIT_EXT_SERVICE_NOPREFIX::
	Встановіть довгу назву (upload-pack тощо) помічника служби, який потрібно викликати.


ПРИКЛАДИ
--------
Цей віддалений помічник прозоро використовується Git, коли ви використовуєте такі команди, як "git fetch <URL>", "git clone <URL>", , "git push <URL>" або "git remote add <нік> <URL>", де <URL> починається з `ext::`. Приклади:

"ext::ssh -i /home/foo/.ssh/somekey user&#64;host.example %S 'foo/repo'"::
	Як host.example:foo/repo, але використовуйте /home/foo/.ssh/somekey як пару ключів та user як користувача на віддаленому боці. Це дозволяє уникнути необхідності редагування .ssh/config.

"ext::socat -t3600 - ABSTRACT-CONNECT:/git-server %G/somerepo"::
	Представляє репозиторій зі шляхом /somerepo, доступним через протокол git за адресою абстрактного простору імен /git-server.

"ext::git-server-alias foo %G/repo"::
	Представляє репозиторій зі шляхом /repo, доступ до якого здійснюється за допомогою допоміжної програми "git-server-alias foo". Шлях до репозиторію та тип запиту не передаються в командному рядку, а як частина потоку протоколу, як зазвичай у випадку з протоколом git://.

"ext::git-server-alias foo %G/repo %Vfoo"::
	Представляє репозиторій зі шляхом /repo, доступ до якого здійснюється за допомогою допоміжної програми "git-server-alias foo". Ім'я хоста для віддаленого сервера, переданого в потоці протоколу, буде "foo" (це дозволяє кільком віртуальним серверам Git спільно використовувати адресу рівня каналу).

"ext::git-server-alias foo %G/repo% with% spaces %Vfoo"::
	Представляє репозиторій зі шляхом `/repo з пробілами`, доступ до якого здійснюється за допомогою допоміжної програми "git-server-alias foo". Ім'я хоста для віддаленого сервера, переданого в потоці протоколу, буде "foo" (це дозволяє кільком віртуальним серверам Git спільно використовувати адресу рівня каналу).

"ext::git-ssl foo.example /bar"::
	Представляє репозиторій, доступ до якого здійснюється за допомогою допоміжної програми "git-ssl foo.example /bar". Тип запиту може бути визначений допоміжною програмою за допомогою змінних середовища (див. вище).

ДИВ. ТАКОЖ
----------
linkgit:gitremote-helpers[7]

GIT
---
Частина набору linkgit:git[1]
