Git певною мірою не залежить від кодування символів.

 - Вміст блоб-об'єктів — це неінтерпретовані послідовності байтів. На рівні ядра немає перетворення кодування.

 - Імена шляхів закодовано у формі нормалізації UTF-8 C. Це стосується об'єктів дерева, індексного файлу, імен посилань, а також імен шляхів в аргументах командного рядка, змінних середовища та конфігураційних файлах (`.git/config` (див. linkgit:git-config[1]), linkgit:gitignore[5], linkgit:gitattributes[5] та linkgit:gitmodules[5]).
+
Зверніть увагу, що Git на рівні ядра трактує шляхи просто як послідовності байтів, відмінних від NUL, немає перетворень кодування шляхів (за винятком Mac та Windows). Тому використання шляхів, відмінних від ASCII, здебільшого працюватиме навіть на платформах та файлових системах, які використовують застарілі розширені кодування ASCII. Однак репозиторії, створені на таких системах, не працюватимуть належним чином на системах на основі UTF-8 (наприклад, Linux, Mac, Windows) і навпаки. Крім того, багато інструментів на основі Git просто вважають шляхи UTF-8 і не відображатимуть інші кодування належним чином.

 - Повідомлення журналу комітів зазвичай кодуються в UTF-8, але також підтримуються інші розширені кодування ASCII. Це включає ISO-8859-x, CP125x та багато інших, але _не_ UTF-16/32, EBCDIC та багатобайтові кодування CJK (GBK, Shift-JIS, Big5, EUC-x, CP9xx тощо).

Хоча ми рекомендуємо використовувати кодування повідомлень журналу комітів в UTF-8, як ядро, так і Git Porcelain розроблені таким чином, щоб не нав'язувати UTF-8 проектам. Якщо всі учасники певного проекту вважають зручнішим використовувати застарілі кодування, Git цього не забороняє. Однак, є кілька речей, які слід пам'ятати.

. `git commit` та `git commit-tree` видають попередження, якщо повідомлення журналу комітів, надане їм, не виглядає як коректний рядок UTF-8, окрім випадків, коли ви явно вкажете, що ваш проект використовує застаріле кодування. Це можна зробити, додавши `i18n.commitEncoding` у файл `.git/config`, ось так:
+
------------
[i18n]
	commitEncoding = ISO-8859-1
------------
+
Об'єкти комітів, створені з використанням вищевказаного налаштування, записують значення `i18n.commitEncoding` у свій заголовок `encoding`. Це зроблено для того, щоб допомогти іншим користувачам, які переглядатимуть їх пізніше. Відсутність цього заголовка означає, що повідомлення журналу комітів закодоване в UTF-8.

. `git log`, `git show`, `git blame` та інші команди переглядають заголовок `encoding` об'єкта коміту та намагаються перекодувати повідомлення журналу в UTF-8, якщо не вказано інше. Ви можете вказати потрібне кодування виводу за допомогою `i18n.logOutputEncoding` у файлі `.git/config`, ось так:
+
------------
[i18n]
	logOutputEncoding = ISO-8859-1
------------
+
Якщо у вас немає цієї змінної конфігурації, замість неї використовується значення `i18n.commitEncoding`.

Зверніть увагу, що ми навмисно вирішили не перекодувати повідомлення журналу комітів, коли коміт робиться для примусового використання UTF-8 на рівні об'єкта коміту, оскільки перекодування в UTF-8 не обов'язково є оборотною операцією.
