СТРАТЕГІЇ ЗЛИТТЯ
----------------

Механізм злиття (команди `git merge` та `git pull`) дозволяє вибирати бекенд-«стратегії злиття» за допомогою опції `-s`. Деякі стратегії також можуть приймати власні опції, які можна передати, надаючи аргументи `-X<опція>` командам `git merge` та/або `git pull`.

`ort`::
	Це стандартна стратегія злиття при витягуванні або злитті однієї гілки. Ця стратегія дозволяє об’єднати лише дві вершини за допомогою алгоритму тристороннього злиття. Коли існує більше ніж один спільний предок, який можна використати для тристороннього злиття, вона створює злите дерево спільних предків і використовує його як дерево-орієнтир для тристороннього злиття. За результатами тестів, проведених на реальних комітах злиття, взятих з історії розробки ядра Linux 2.6, це призводить до меншої кількості конфліктів злиття без створення помилкових злиттів. Крім того, ця стратегія може виявляти та обробляти злиття, що містять перейменування. Вона не використовуватиме виявлені копії. Назва цього алгоритму є акронімом («Ostensibly Recursive's Twin») і походить від того, що він був написаний як заміна попереднього стандартного алгоритму, `recursive`.
+
Якщо шлях вказує на субмодуль, і коміт субмодуля, який використовується в одній частині злиття, є нащадком коміту субмодуля, що використовується в іншій частині злиття, Git намагається виконати швидкий перехід до цього нащадка. В іншому випадку Git розглядає цю ситуацію як конфлікт і пропонує в якості розвʼязання коміт субмодуля, який є нащадком комітів, що конфліктують, якщо такий існує.
+
Стратегія `ort` може приймати такі варіанти:

`ours`;;
	Ця опція змушує систему автоматично розвʼязувати конфлікти між фрагментами коду, надаючи перевагу «нашій» версії. Зміни з іншого дерева, які не суперечать нашій версії, враховуються в результаті злиття. У випадку з бінарним файлом весь вміст береться з нашої версії.
+
Це не слід плутати зі стратегією злиття `ours`, яка взагалі не враховує вміст іншого дерева. Вона відкидає всі зміни, внесені в іншому дереві, і вважає, що «наша» історія містить усе, що там відбувалося.

`theirs`;;
	Це протилежність параметру `ours`; зверніть увагу, що, на відміну від `ours`, не існує стратегії злиття `theirs`, з якою можна було б сплутати цей параметр злиття.

`ignore-space-change`;;
`ignore-all-space`;;
`ignore-space-at-eol`;;
`ignore-cr-at-eol`;;
	Для цілей тристороннього злиття рядки, що містять вказаний тип змін пробілів, розглядаються як незмінені. Зміни пробілів, що поєднуються з іншими змінами в рядку, не ігноруються. Див. також linkgit:git-diff[1] `-b`, `-w`, `--ignore-space-at-eol` та `--ignore-cr-at-eol`.
+
* Якщо «їхня» версія передбачає лише зміну пробілів у рядку, використовується «наша» версія;
* Якщо «наша» версія містить зміни пробілів, але «їхня» версія містить суттєві зміни, використовується «їхня» версія;
* В іншому випадку обʼєднання відбувається у звичайному порядку.

`renormalize`;;
	Ця опція виконує перевірку та реєстрацію всіх трьох стадій будь-якого файлу, який потребує тристороннього злиття. Цю опцію слід використовувати під час злиття гілок із різними фільтрами очищення або правилами нормалізації кінців рядків. Детальніше див. розділ «Злиття гілок із різними атрибутами checkin/checkout» у статті linkgit:gitattributes[5].

`no-renormalize`;;
	Вимикає опцію `renormalize`. Це замінює змінну конфігурації `merge.renormalize`.

`find-renames[=<n>]`;;
	Вимкає виявлення перейменувань, за бажанням встановивши поріг схожості. Це значення є типовим. Воно має пріоритет над змінною конфігурації `merge.renames`. Див. також linkgit:git-diff[1] `--find-renames`.

`rename-threshold=<n>`;;
	Застарілий синонім до `find-renames=<n>`.

`no-renames`;;
	Вимикає виявлення перейменування. Перевизнає змінну конфігурації `merge.renames`. Див. також linkgit:git-diff[1] `--no-renames`.

`histogram`;;
	Застарілий синонім до `diff-algorithm=histogram`.

`patience`;;
	Застарілий синонім до `diff-algorithm=patience`.

`diff-algorithm=(histogram|minimal|myers|patience)`;;
	Під час злиття використовувати інший алгоритм порівняння, що допоможе уникнути помилкових злиттів, які виникають через неважливі збіги рядків (наприклад, дужки з різних функцій). Див. також linkgit:git-diff[1] `--diff-algorithm`. Зверніть увагу, що для `ort` стандартним значенням є `diff-algorithm=histogram`, тоді як для звичайних порівнянь наразі використовується значення параметра конфігурації `diff.algorithm`.

`subtree[=<path>]`;;
	Цей варіант є вдосконаленою формою стратегії 'subtree', за якої стратегія робить припущення щодо того, як слід змістити два дерева, щоб вони збігалися під час об’єднання. Натомість до вказаного шляху додається префікс (або з його початку видаляється частина), щоб форми двох дерев збігалися.

`recursive`::
	Тепер це синонім до `ort`. Це стратегія була альтернативною реалізацією до версії 2.49.0, але була перенаправлена на `ort` у версії 2.50.0. Попередня рекурсивна стратегія була стандартною стратегією для розвʼязання для двох вершин з Git версії 0.99.9k до версії 2.33.0.

`resolve`::
	Може розвʼязувати лише дві гілки (тобто поточну гілку та іншу гілку, з якої було виконано злиття) за допомогою алгоритму тристороннього злиття. Намагається ретельно виявляти неоднозначності, пов’язані з перехресним злиттям. Не підтримує перейменування.

`octopus`::
	Ця стратегія розвʼязує випадки, коли є більше двох вершин, але відмовляється виконувати складне злиття, яке потребує ручного втручання. Вона призначена насамперед для обʼєднання вершин гілок тем. Це стратегія злиття є стандартною під час злиття або об’єднання кількох гілок.

`ours`::
	Ця стратегія дозволяє обʼєднати будь-яку кількість вершин, але отримане в результаті злиття дерево завжди відповідає вершині поточної гілки, фактично ігноруючи всі зміни з усіх інших гілок. Вона призначена для заміни старої історії розробки бічних гілок. Зверніть увагу, що вона відрізняється від опції `-Xours` стратегії злиття `ort`.

`subtree`::
	Це модифікована стратегія `ort`. Під час обʼєднання дерев A та B, якщо B відповідає піддереву A, B спочатку коригується відповідно до структури дерева A, замість того, щоб зчитувати дерева на одному рівні. Це коригування також виконується для дерева спільного предка.

У стратегіях, що використовують тристороннє злиття (включно зі стандартною стратегією `ort`), якщо зміна була внесена в обох гілках, але згодом скасована в одній із них, ця зміна все одно буде присутня в результаті злиття; деякі користувачі вважають таку поведінку заплутаною. Це відбувається тому, що під час злиття враховуються лише кінцеві точки гілок та базова точка злиття, а не окремі коміти. Тому алгоритм злиття розглядає скасовану зміну як відсутність будь-якої зміни взагалі і замінює її зміненою версією.
