Перерахувати коміти, доступні за посиланнями `barent` з заданого(их) коміту(ів), але виключити коміти, доступні з того(их), що вказані з символом '{caret}' перед ними. За замовчуванням результат виводиться у зворотному хронологічному порядку.

Ви можете розглядати це як операцію з набором. Коміти, досяжні з будь-якого з комітів, заданих у командному рядку, формують набір, а потім коміти, досяжні з будь-якого з тих, що задані з '{caret}' попереду, віднімаються з цього набору. Решта комітів - це те, що виводиться у виводі команди. Різні інші опції та параметри шляхів можна використовувати для подальшого обмеження результату.

Таким чином, наступна команда:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list foo bar ^baz
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log foo bar ^baz
-----------------------------------------------------------------------
endif::git-log[]

означає «перерахувати всі коміти, які доступні з 'foo' або 'bar', але не з 'baz'».

Спеціальне позначення "`<commit1>..<commit2>`" може використовуватися як скорочений запис для "`^<commit1> <commit2>`". Наприклад, будь-який з наступних варіантів може використовуватися як взаємозамінний:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list origin..HEAD
$ git rev-list HEAD ^origin
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log origin..HEAD
$ git log HEAD ^origin
-----------------------------------------------------------------------
endif::git-log[]

Ще одне спеціальне позначення — "`<commit1>...<commit2>`", яке корисне для злиття. Результуючий набір комітів — це симетрична різниця між двома операндами. Наступні дві команди еквівалентні:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list A B --not $(git merge-base --all A B)
$ git rev-list A...B
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log A B --not $(git merge-base --all A B)
$ git log A...B
-----------------------------------------------------------------------
endif::git-log[]
