ВИЗНАЧЕННЯ РЕВІЗІЙ
------------------

Параметр версії '<rev>' зазвичай, хоча й не обов’язково, позначає об’єкт коміту. Він використовує так званий синтаксис 'розширеного SHA-1'. Нижче наведено різні варіанти написання імен об’єктів. Ті, що вказані в кінці цього списку, позначають дерева та блоби, що містяться в коміті.

NOTE: У цьому документі показано "сирий" синтаксис, як його бачить git. Оболонка та інші інтерфейси можуть вимагати додаткових лапок для екранування спеціальних символів та уникнення розбиття слів.

'<sha1>', напр. 'dae86e1950b1277e545cee180551750029cfe735', 'dae86e'::
  Повне імʼя обʼєкта у форматі SHA-1 (16-бітовий шістнадцятковий рядок) або початкова частина рядка, яка є унікальною в межах репозиторію. Наприклад, dae86e1950b1277e545cee180551750029cfe735 і dae86e позначають один і той самий об’єкт коміту, якщо у вашому репозиторії немає іншого об’єкта, ім’я якого починається з dae86e.

'<describeOutput>', напр. 'v1.7.4.2-679-g3bee7fb'::
  Вивід з `git describe`; тобто найближчий тег, за яким необовʼязково слідує дефіс та кількість комітів, а потім дефіс, 'g' та скорочена назва обʼєкта.

'<refname>', напр. 'master', 'heads/master', 'refs/heads/master'::
  Символічне імʼя посилання. Наприклад, 'master' зазвичай означає обʼєкт коміту, на який посилається 'refs/heads/master'. Якщо у вас є як 'heads/master', так і 'tags/master', ви можете явно вказати 'heads/master', щоб пояснити Git, який саме обʼєкт ви маєте на увазі. У разі неоднозначності '<refname>' розшифровується шляхом вибору першого збігу за такими правилами:
+
  . Якщо '$GIT_DIR/<refname>' існує, саме це ви маєте на увазі (зазвичай це корисно лише для `HEAD`, `FETCH_HEAD`, `ORIG_HEAD`, `MERGE_HEAD`, `REBASE_HEAD`, `REVERT_HEAD`, `CHERRY_PICK_HEAD`, `BISECT_HEAD` та `AUTO_MERGE`);

  . інакше, 'refs/<refname>', якщо існує;

  . інакше, 'refs/tags/<refname>', якщо існує;

  . інакше, 'refs/heads/<refname>', якщо існує;

  . інакше, 'refs/remotes/<refname>', якщо існує;

  . інакше, 'refs/remotes/<refname>/HEAD', якщо існує.

+
  `HEAD`:::
    вказує коміт, на якому базуються зміни у робочому дереві.
  `FETCH_HEAD`:::
    записує гілку, яку ви отримали з віддаленого репозиторію 
    під час вашого останнього виклику `git fetch`.
  `ORIG_HEAD`:::
    створюється командами, які різко змінюють положення `HEAD` (`git
    am`, `git merge`, `git rebase`, `git reset`), щоб зафіксувати положення
    `HEAD` до виконання цих операцій, завдяки чому ви зможете легко повернути
    кінець гілки до стану, що існував до їх виконання.
  `MERGE_HEAD`:::
    записує коміти, які ви зливаєте у свою гілку, коли ви
    запускаєте `git merge`.
  `REBASE_HEAD`:::
    під час перебазування, записує коміт, на якому операція
    наразі зупинена — чи то через конфлікти, чи то через команду `edit` у
    інтерактивному перебазуванні.
  `REVERT_HEAD`:::
    записує коміт, який ви скасовуєте під час виконання команди `git revert`.
  `CHERRY_PICK_HEAD`:::
    записує коміт, який ви вибираєте, коли запускаєте `git
    cherry-pick`.
  `BISECT_HEAD`:::
    записує поточний коміт для перевірки під час запуску `git bisect
    --no-checkout`.
  `AUTO_MERGE`:::
    записує об’єкт дерева, що відповідає стану, який
    стратегія злиття «ort» записала у робоче дерево, коли операція злиття
    призвела до конфліктів.

+
Зверніть увагу, що будь-який із наведених вище випадків 'refs/*' може походити або з теки `$GIT_DIR/refs`, або з файлу `$GIT_DIR/packed-refs`. Хоча кодування назв посилань не вказано, перевага надається UTF-8, оскільки деякі процеси обробки виводу можуть передбачати назви посилань у форматі UTF-8.

'@'::
  Сам по собі символ '@' є скороченням для `HEAD`.

'[<refname>]@{<date>}', напр. 'master@\{yesterday\}', 'HEAD@{5 minutes ago}'::
  Посилання, за яким іде суфікс '@' із зазначенням дати в дужках (наприклад, '\{yesterday\}', '{1 month 2 weeks 3 days 1 hour 1 second ago}' або '{1979-02-26 18:30:00}'), вказує на значення посилання в попередній момент часу. Цей суфікс можна використовувати лише безпосередньо після імені посилання, і посилання повинно мати наявний журнал ('$GIT_DIR/logs/<ref>'). Зверніть увагу, що це дозволяє перевірити стан вашого *локального* посилання на певний момент часу; наприклад, що було у вашій локальній гілці «master» минулого тижня. Якщо ви хочете переглянути коміти, зроблені протягом певного періоду, дивіться `--since` та `--until`.

'<refname>@{<n>}', напр. 'master@\{1\}'::
  Посилання, за яким стоїть суфікс '@' з порядковим номером в дужках (наприклад, '\{1\}', '\{15\}'), вказує n-те попереднє значення цього посилання. Наприклад, 'master@\{1\}' — це безпосереднє попереднє значення 'master', тоді як 'master@\{5\}' — це 5-те попереднє значення 'master'. Цей суфікс можна використовувати лише безпосередньо після назви посилання, і посилання повинно мати наявний журнал ('$GIT_DIR/logs/<refname>').

'@{<n>}', напр. '@\{1\}'::
  Ви можете використовувати конструкцію '@' з порожньою частиною ref, щоб отримати запис reflog поточної гілки. Наприклад, якщо ви знаходитесь на гілці 'blabla', то '@\{1\}' означає те саме, що й 'blabla@\{1\}'.

'@{-<n>}', напр. '@{-1}'::
  Конструкція '@{-<n>}' означає, що <n>-та гілка/коміт була активною перед поточною.

'[<branchname>]@\{upstream\}', напр. 'master@\{upstream\}', '@\{u\}'::
  Гілку B можна налаштувати для створення поверх гілки X (налаштованої за допомогою `branch.<name>.merge`) на віддаленому R (налаштованому за допомогою `branch.<name>.remote`). B@{u} посилається на гілку віддаленого відстеження для гілки X, взятої з віддаленого R, яка зазвичай знаходиться за адресою `refs/remotes/R/X`.

'[<branchname>]@\{push\}', напр. 'master@\{push\}', '@\{push\}'::
  Суфікс '@\{push}' вказує гілку, "куди ми надішлемо зміни", якщо `git push` було виконано під час переходу на `branchname` (або поточний `HEAD`, якщо branchname не вказано). Як і для '@\{upstream\}', ми повідомляємо гілку віддаленого відстеження, яка відповідає цій гілці на віддаленому сервері.
+
Ось приклад, щоб було зрозуміліше:
+
------------------------------
$ git config push.default current
$ git config remote.pushdefault myfork
$ git switch -c mybranch origin/master

$ git rev-parse --symbolic-full-name @{upstream}
refs/remotes/origin/master

$ git rev-parse --symbolic-full-name @{push}
refs/remotes/myfork/mybranch
------------------------------
+
Зверніть увагу, що в прикладі ми налаштували трикутний робочий процес, де ми витягуємо дані з одного місця та надсилаємо їх до іншого. У нетрикутному робочому процесі '@\{push}' те саме, що й '@\{upstream}', і в цьому немає потреби.
+
Цей суфікс також приймається, коли введення робиться великими літерами, і означає те саме незалежно від регістру.

'<rev>{caret}[<n>]', напр. 'HEAD{caret}, v1.5.1{caret}0'::
  Суфікс '{caret}' до параметра ревізії означає першого батька цього обʼєкта коміту. '{caret}<n>' означає <n>-го батька (тобто '<rev>{caret}' еквівалентно '<rev>{caret}1'). Як спеціальне правило, '<rev>{caret}0' означає сам коміт і використовується, коли '<rev>' є назвою обʼєкта тегу, який посилається на обʼєкт коміту.

'<rev>{tilde}[<n>]', напр. 'HEAD{tilde}, master{tilde}3'::
  Суфікс '{tilde}' у параметрі ревізії означає першого предка цього об’єкта коміту. Суфікс '{tilde}<n>' у параметрі ревізії означає об’єкт коміту, який є <n>-м поколінням предка вказаного об’єкта коміту, враховуючи лише перших предків. Тобто '<rev>{tilde}3' еквівалентно '<rev>{caret}{caret}{caret}', що еквівалентно '<rev>{caret}1{caret}1{caret}1'. Дивіться нижче ілюстрацію використання цієї форми.

'<rev>{caret}{<type>}', напр. 'v0.99.8{caret}\{commit\}'::
  Суфікс '{caret}', за яким іде назва типу об’єкта в дужках, означає рекурсивне розгортання об’єкта в '<rev>' доти, доки не буде знайдено об’єкт типу '<type>' або розгортання об’єкта стане неможливим (у цьому випадку — barf) . Наприклад, якщо '<rev>' є об’єктом типу 'commit', '<rev>{caret}\{commit\}' описує відповідний об’єкт коміту. Аналогічно, якщо '<rev>' є обʼєктом типу дерева, '<rev>{caret}\{tree\}' описує відповідний обʼєкт дерева. '<rev>{caret}0' є скороченим записом для '<rev>{caret}\{commit\}'.
+
'<rev>{caret}\{object\}' можна використовувати, щоб переконатися, що '<rev>' вказує на наявних обʼєкт, без необхідності, щоб '<rev>' був тегом, і без розгортання '<rev>'; оскільки тег вже є обʼєктом, його не потрібно розгортати жодного разу, щоб дістатися до обʼєкта.
+
'<rev>{caret}\{tag\}' можна використовувати, щоб переконатися, що '<rev>' ідентифікує наявний обʼєкт тегу.

'<rev>{caret}{}', напр. 'v0.99.8{caret}{}'::
  Суфікс '{caret}', за яким йде порожня пара дужок, означає, що обʼєкт може бути тегом, і тег може бути розгортнутий рекурсивно, доки не буде знайдено обʼєкт, який не є тегом.

'<rev>{caret}{/<text>}', напр. 'HEAD^{/fix nasty bug}'::
  Суфікс '{caret}' до параметра ревізії, за яким йде пара фігурних дужок, що містить текст, що починається зі скісної риски, такий самий, як і синтаксис ':/fix nasty bug' нижче, за винятком того, що він повертає наймолодший відповідний коміт, який можна досягти з '<rev>' перед '{caret}'.

':/<text>', напр. ':/fix nasty bug'::
  Двокрапка, за якою йде скісна риска, а потім текст, позначає коміт, повідомлення якого відповідає вказаному регулярному виразу. Ця назва повертає найновіший коміт, що відповідає критеріям пошуку, до якого можна дістатися з будь-якого посилання, включаючи HEAD. Регулярний вираз може відповідати будь-якій частині повідомлення коміту. Щоб знайти повідомлення, що починаються з певного рядка, можна використати, наприклад, ':/^foo'. Спеціальна послідовність ':/!' зарезервована для модифікаторів результату пошуку. ':/!-foo' виконує негативний пошук, тоді як “:/!!foo” знаходить символ '!' у прямому значенні, за яким йде 'foo'. Будь-яка інша послідовність, що починається з ':/!', наразі зарезервована. Залежно від вказаного тексту, правила розбиття слів оболонки можуть вимагати додаткового використання лапок.

'<rev>:<path>', напр. 'HEAD:README', 'master:./README'::
  Суфікс ':', за яким іде шлях, позначає об’єкт blob або дерево за вказаним шляхом у об’єкті типу 'дерево', назва якого вказано в частині перед двокрапкою. Шлях, що починається з './' або '../', є відносним до поточної робочої теки. Зазначений шлях буде перетворено на відносний до кореневої теки робочого дерева. Це найбільш корисно для звернення до блобу або дерева з коміту або дерева, що має таку саму структуру, як і робоче дерево.

':[<n>:]<path>', напр. ':0:README', ':README'::
  Двокрапка, за якою може йти номер stage (від 0 до 3) та ще одна двокрапка, а потім шлях, позначає об’єкт blob в індексі за вказаним шляхом. Відсутність номера stage (та двокрапки, що йде за ним) позначає запис stage 0. Під час злиття stage 1 є спільним предком, stage 2 — версією цільової гілки (зазвичай поточної гілки), а stage 3 — версією з гілки, що зливається.

Ось ілюстрація Джона Лоелігера. Обидва вузли комітів B та C є батьківськими для вузла коміта A. Батьківські коміти впорядковані зліва направо.

........................................
G   H   I   J
 \ /     \ /
  D   E   F
   \  |  / \
    \ | /   |
     \|/    |
      B     C
       \   /
        \ /
         A
........................................

    A =      = A^0
    B = A^   = A^1     = A~1
    C =      = A^2
    D = A^^  = A^1^1   = A~2
    E = B^2  = A^^2
    F = B^3  = A^^3
    G = A^^^ = A^1^1^1 = A~3
    H = D^2  = B^^2    = A^^^2  = A~2^2
    I = F^   = B^3^    = A^^3^
    J = F^2  = B^3^2   = A^^3^2


ВИЗНАЧЕННЯ ДІАПАЗОНІВ
---------------------

Команди для перегляду історії, такі як `git log`, працюють з набором комітів, а не з окремим комітом.

Для цих команд вказання однієї ревізії за допомогою нотації, описаної в попередньому розділі, означає набір комітів, до яких можна «дістатися» з даного коміту.

Вказівка кількох ревізій означає набір комітів, досяжних з будь-якого з заданих комітів.

Доступний набір коміту — це сам коміт та коміти в його ланцюжку попередників.

Існує кілька позначень для позначення набору повʼязаних комітів (так званого "діапазону редакцій"), проілюстрованих нижче.


Винятки комітів
~~~~~~~~~~~~~~~

Нотація з кареткою '{caret}<rev>'::
 Щоб виключити коміти, до яких можна дістатися з певного коміту, використовується префікс '{caret}'. Наприклад, '{caret}r1 r2' означає коміти, до яких можна дістатися з 'r2', але виключає ті, до яких можна дістатися з 'r1' (тобто 'r1' та його попередників).

Позначення діапазонів крапками
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Нотація діапазону '..' (двокрапка)::
 Операція з набором '{caret}r1 r2' зустрічається настільки часто, що для неї існує скорочена форма. Якщо у вас є два коміти 'r1' і 'r2' (позначені відповідно до синтаксису, описаного вище у розділі ВИЗНАЧЕННЯ РЕВІЗІЙ, ви можете запитати коміти, доступні з r2, виключаючи ті, що доступні з r1, за допомогою '{caret}r1 r2', і це можна записати як 'r1..r2'.

Симетрична різниця '\...' (три крапки)::
 Подібне позначення 'r1\...r2' називається симетричною різницею 'r1' та 'r2' та визначається як 'r1 r2 --not $(git merge-base --all r1 r2)'. Це набір комітів, які доступні з одного з 'r1' (ліва сторона) або 'r2' (права сторона), але не з обох.

У цих двох скорочених записах можна пропустити один кінець і дозволити йому використовувати HEAD. Наприклад, 'origin..' — це скорочення від 'origin..HEAD' і запитує: "Що я зробив після того, як зроби відгалуження від гілки origin?". Аналогічно, '..origin' — це скорочення від 'HEAD..origin' і запитує: "Що зробила гілка origin після того, як я зробив відгалуження від неї?". Зверніть увагу, що '..' означатиме 'HEAD..HEAD', який є порожнім діапазоном, досяжним і недосяжним з HEAD.

Команди, спеціально розроблені для використання двох різних діапазонів (наприклад, "git range-diff R1 R2" для порівняння двох діапазонів), існують, але вони є винятками. Якщо не зазначено інше, усі команди "git", які працюють з набором комітів, працюють з одним діапазоном версій. Іншими словами, запис двох "двокрапкових позначень діапазону" поруч один з одним, наприклад.

    $ git log A..B C..D

*не* визначає два діапазони версій для більшості команд. Натомість він вкаже єдину зв’язану сукупність комітів, тобто тих, до яких можна дістатися з B або D, але не з A чи C. У такій лінійній історії:

    ---A---B---o---o---C---D

Оскільки A та B досяжні з C, діапазон версій, визначений цими двома крапковими діапазонами, є одним комітом D.


Інші скорочені позначення батьківських елементів через <rev>{caret}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Існують ще три скорочення, які особливо корисні при злитті комітів для позначення набору, що складається з коміту та його батьківських комітів.

Нотація 'r1{caret}@' означає всіх батьківських елементів 'r1'.

Запис 'r1{caret}!' включає коміт 'r1', але виключає всі його батьківські коміти. Сам по собі цей запис означає єдиний коміт 'r1'.

Запис '<rev>{caret}-[<n>]' включає '<rev>', але виключає <n>-й батьківський елемент (тобто скорочення для '<rev>{caret}<n>..<rev>'), де '<n>' = 1, якщо не вказано. Зазвичай це корисно для комітів злиття, де ви можете просто передати '<commit>{caret}-', щоб отримати всі коміти у гілці, яка була обʼєднана в коміті злиття '<commit>' (включаючи сам '<commit>').

Хоча '<rev>{caret}<n>' стосувалося визначення одного батьківського елемента коміта, ці три позначення також враховують його батьківські елементи. Наприклад, ви можете сказати 'HEAD{caret}2{caret}@', проте ви не можете сказати 'HEAD{caret}@{caret}2'.

Короткий огляд діапазону ревізії
--------------------------------

'<rev>'::
	Включити коміти, доступні з <rev> (тобто <rev> та його предків).

'{caret}<rev>'::
	Виключити коміти, досяжні з <rev> (тобто <rev> та його предків).

'<rev1>..<rev2>'::
	Включити коміти, доступні з <rev2>, але виключити ті, доступні з <rev1>. Якщо <rev1> або <rev2> пропущено, зазвичай використовується значення `HEAD`.

'<rev1>\...<rev2>'::
	Включити коміти, доступні з <rev1> або <rev2>, але виключити ті, доступні з обох. Якщо <rev1> або <rev2> пропущено, зазвичай використовується значення `HEAD`.

'<rev>{caret}@', напр. 'HEAD{caret}@'::
  Суфікс '{caret}', після якого стоїть знак at, те саме, що й перелік усіх батьківських обʼєктів '<rev>' (тобто, включено все, що доступно з батьківських обʼєктів, але не сам коміт).

'<rev>{caret}!', напр. 'HEAD{caret}!'::
  Суфікс '{caret}', за яким стоїть знак оклику, те саме, що додати коміт '<rev>' та всі його батьківські елементи з префіксом '{caret}', щоб виключити їх (та їхніх предків).

'<rev>{caret}-<n>', напр. 'HEAD{caret}-, HEAD{caret}-2'::
	Еквівалентно '<rev>{caret}<n>..<rev>', де '<n>' = 1, якщо не вказано.

Ось кілька прикладів з використанням наведеної вище ілюстрації Лелігера, де кожен крок у розгортанні та виборі нотації ретельно прописаний:

....
   Аргументи  Розширені аргументи  Вибрані коміти
   D                            G H D
   D F                          G H I J D F
   ^G D                         H D
   ^D B                         E I J F B
   ^D B C                       E I J F B C
   C                            I J F C
   B..C   = ^B C                C
   B...C  = B ^F C              G H D E B C
   B^-    = B^..B
	  = ^B^1 B              E I J F B
   C^@    = C^1
	  = F                   I J F
   B^@    = B^1 B^2 B^3
	  = D E F               D G H E F I J
   C^!    = C ^C^@
	  = C ^C^1
	  = C ^F                C
   B^!    = B ^B^@
	  = B ^B^1 ^B^2 ^B^3
	  = B ^D ^E ^F          B
   F^! D  = F ^I ^J D           G H D F
....
