include::urls.adoc[]

ПУЛЬТИ КЕРУВАННЯ[[REMOTES]]
---------------------------

Замість URL-адреси як аргумент _<репозиторій>_ можна використовувати назву одного з наступних:

* віддалений сервер у файлі конфігурації Git: `$GIT_DIR/config`,
* файл у каталозі `$GIT_DIR/remotes`, або
* файл у каталозі `$GIT_DIR/branches`.

Усі вони також дозволяють вам пропустити refspec з командного рядка, оскільки кожен з них містить refspec, який git використовуватиме за замовчуванням.

Назва віддаленого пристрою у файлі конфігурації
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати назву віддаленого сервера, який ви раніше налаштували за допомогою linkgit:git-remote[1], linkgit:git-config[1] або навіть вручну редагуючи файл `$GIT_DIR/config`. URL-адреса цього віддаленого сервера буде використана для доступу до репозиторію. Специфікація посилань цього віддаленого сервера буде використовуватися за замовчуванням, якщо ви не вкажете специфікацію посилань у командному рядку. Запис у файлі конфігурації виглядатиме так:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

_<pushurl>_ використовується лише для надсилання змін. Він необов'язковий і за замовчуванням має значення _<URL>_. Надсилання змін на віддалений сервер впливає на всі визначені адреси pushurl або всі визначені URL-адреси, якщо жодної адреси pushurl не визначено. Однак Fetch буде отримувати дані лише з першої визначеної URL-адреси, якщо визначено кілька URL-адрес.

Іменований файл у `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати назву файлу в `$GIT_DIR/remotes`. URL-адреса з цього файлу буде використана для доступу до репозиторію. Специфікація посилань у цьому файлі буде використовуватися за замовчуванням, якщо ви не вкажете специфікацію посилань у командному рядку. Цей файл повинен мати такий формат:

------------
	URL: один із наведених вище форматів URL-адрес
	Push: <refspec>
	Pull: <refspec>

------------

Рядки `Push:` використовуються командами `git push`, а рядки `Pull:` використовуються командами `git pull` та `git fetch`. Для додаткових зіставлень гілок можна вказати кілька рядків `Push:` та `Pull:`.

Іменований файл у `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати назву файлу в `$GIT_DIR/branches`. URL-адреса з цього файлу буде використана для доступу до репозиторію. Цей файл повинен мати такий формат:


------------
	<URL>#<head>
------------

_<URL>_ обов'язковий; `#<head>` необов'язковий.

Залежно від операції, git використовуватиме одну з наступних специфікацій refspecs, якщо ви не вкажете її в командному рядку. _<branch> – це назва цього файлу в `$GIT_DIR/branches`, а _<head>_ за замовчуванням має значення `master`.

git fetch uses:

------------
	refs/heads/<head>:refs/heads/<branch>
------------

git push uses:

------------
	HEAD:refs/heads/<head>
------------


[[UPSTREAM-BRANCHES]]
ВИГЛЯДНІ ФІЛІЇ
--------------

Гілки в Git можуть за бажанням мати віддалену гілку, що знаходиться вище за тегом. Git за замовчуванням використовує гілку, що знаходиться вище за тегом, для віддалених операцій, наприклад:

* Це значення за замовчуванням для `git pull` або `git fetch` без аргументів.
* Це значення за замовчуванням для `git push` без аргументів, за деякими винятками. Наприклад, ви можете використовувати опцію `branch.<name>.pushRemote` для надсилання даних на інший віддалений сервер, ніж той, з якого ви отримуєте дані, і за замовчуванням з `push.default=simple` гілка, яку ви налаштовуєте, повинна мати таку саму назву.
* Різні команди, зокрема `git checkout` та `git status`, покажуть вам, скільки комітів було додано до вашої поточної гілки та основної гілки з моменту відгалуження від неї, наприклад, «Ваша гілка та 'origin/main' розійшлися та мають 2 та 3 різні коміти відповідно».

Дані про вихідний код зберігаються у файлі `.git/config`, у полях "remote" та "merge". Наприклад, якщо вихідним кодом `main` є `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Ви можете явно встановити гілку upstream за допомогою `git push --set-upstream <віддалена> <гілка>`, але Git часто автоматично встановить її за вас, наприклад:

* Коли ви клонуєте репозиторій, Git автоматично встановить основний напрямок (upstream) для гілки за замовчуванням.
* Якщо у вас встановлено опцію конфігурації `push.autoSetupRemote`, `git push` автоматично встановить розгортання під час першого надсилання гілки.
* Перевірка гілки віддаленого відстеження за допомогою `git checkout <branch>` автоматично створить локальну гілку з цією назвою та встановить основний хід (upstream) на віддалену гілку.

[NOTE]
Гілки вище за течією іноді називають «інформацією відстеження», наприклад, «встановити інформацію відстеження гілки».
