include::urls.adoc[]

ВІДДАЛЕНІ ЕКЗЕМПЛЯРИ[[REMOTES]]
-------------------------------

Замість URL-адреси як аргументу _<repository>_ можна вказати одне з наступних:

* віддалений сервер у файлі конфігурації Git: `$GIT_DIR/config`,
* файл у теці `$GIT_DIR/remotes`, або
* файл у теці `$GIT_DIR/branches`.

Усі ці команди також дозволяють не вказувати refspec у командному рядку, оскільки кожна з них містить refspec, який git використовуватиме стандартно.

Назва віддаленого репозиторію в файлі конфігурації
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати ім’я віддаленого репозиторію, яке раніше було налаштоване за допомогою команд `linkgit:git-remote[1]`, `linkgit:git-config[1]` або навіть шляхом ручного редагування файлу `$GIT_DIR/config`. URL-адреса цього віддаленого репозиторію буде використовуватися для доступу до репозиторію. Refspec цього віддаленого репозиторію буде використовуватися як стандартний, якщо ви не вкажете refspec у командному рядку. Запис у файлі конфігурації матиме такий вигляд:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

_<pushurl>_ використовується виключно для надсилання. Цей параметр є необов’язковим, а стандартним значенням є _<URL>_. Надсилання на віддалений сервер впливає на всі визначені pushurl або на всі визначені url, якщо pushurl не визначено. Натомість, якщо визначено кілька url, завантаження відбуватиметься лише з першого визначеного url.

Іменований файл у `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати ім’я файлу в теці `$GIT_DIR/remotes`. URL-адреса, вказана в цьому файлі, буде використовуватися для доступу до репозиторію. Refspec у цьому файлі буде використовуватися як стандартний, якщо ви не вкажете refspec у командному рядку. Цей файл повинен мати такий формат:

------------
	URL: один із наведених вище форматів URL-адрес
	Push: <refspec>
	Pull: <refspec>

------------

Рядки `Push:` використовуються командою `git push`, а рядки `Pull:` — командами `git pull` та `git fetch`. Для додаткових зіставлень гілок можна вказати кілька рядків `Push:` та `Pull:`.

Іменований файл у `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ви можете вказати назву файлу в `$GIT_DIR/branches`. URL-адреса з цього файлу буде використана для доступу до репозиторію. Цей файл повинен мати такий формат:


------------
	<URL>#<head>
------------

_<URL>_ —обовʼязково; `#<head>` —необовʼязково.

Залежно від операції, git використовуватиме один із наведених нижче refspecs, якщо ви не вкажете його в командному рядку. _<branch>_ — це назва відповідного файлу в теці `$GIT_DIR/branches`, а _<head>_ має стандартне значення `master`.

git fetch використовує:

------------
	refs/heads/<head>:refs/heads/<branch>
------------

git push використовує:

------------
	HEAD:refs/heads/<head>
------------


[[UPSTREAM-BRANCHES]]
ВИСХІДНІ ГІЛКИ
--------------

Гілки в Git можуть, за бажанням, мати висхідну віддалену гілку. Зазвичай Git використовує висхідну (upstream) гілку для віддалених операцій, наприклад:

* Вона є стандартною для `git pull` або `git fetch` без аргументів.
* Вона є стандартною для `git push` без аргументів, за деякими винятками. Наприклад, ви можете використати опцію `branch.<name>.pushRemote`, щоб надіслати дані до іншого віддаленого репозиторію, ніж той, з якого ви завантажуєте, і відповідно до стандартного значення `push.default=simple` гілка, яку ви налаштовуєте, повинна мати таку саму назву.
* Різні команди, зокрема `git checkout` та `git status`, покажуть вам, скільки комітів було додано до вашої поточної гілки та висхідної (upstream) гілки з моменту відгалуження від неї, наприклад, «Ваша гілка та 'origin/main' розійшлися та мають 2 та 3 різні коміти відповідно».

Дані upstream зберігаються у файлі `.git/config`, у полях "`remote`" та "`merge`". Наприклад, якщо upstream для `main` є `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Ви можете явно встановити гілку upstream за допомогою `git push --set-upstream <remote> <branch>`, але Git часто автоматично встановить її за вас, наприклад:

* Під час клонування репозиторію Git автоматично встановить upstream для стандартної гілки.
* Якщо у вас встановлено параметр конфігурації `push.autoSetupRemote`, команда `git push` автоматично налаштує upstream під час першого надсилання гілки.
* Перевірка гілки віддаленого відстеження за допомогою `git checkout <branch>` автоматично створить локальну гілку з цією назвою та встановить посилання на джерело (upstream) на віддалену гілку.

[NOTE]
Висхідні гілки іноді називають «інформацією відстеження», наприклад, «встановити інформацію відстеження гілки».
