FORMATE DE DATE
---------------

Variabilele de mediu `GIT_AUTHOR_DATE` și `GIT_COMMITTER_DATE` acceptă următoarele formate de date:

Formatul intern Git::
	It is `<unix-timestamp> <time-zone-offset>`, where `<unix-timestamp>` is the number of seconds since the UNIX epoch. `<time-zone-offset>` is a positive or negative offset from UTC. For example CET (which is 1 hour ahead of UTC) is `+0100`.

RFC 2822::
	The standard date format as described by RFC 2822, for example `Thu, 07 Apr 2005 22:13:13 +0200`.

ISO 8601::
	Ora și data specificate de standardul ISO 8601, de exemplu `2005-04-07T22:13:13`. Analizatorul acceptă, de asemenea, un spațiu în locul caracterului `T`. Părțile fracționare de secundă vor fi ignorate, de exemplu `2005-04-07T22:13:13:13.019` va fi tratat ca `2005-04-07T22:13:13:13`.
+
NOTE: În plus, partea referitoare la dată este acceptată în următoarele formate: `YYYY.MM.DD`, `MM/DD/YYYYYY` și `DD.MM.YYYY`.

ifdef::git-commit[]
În plus față de recunoașterea tuturor formatelor de date de mai sus, opțiunea `--date` va încerca, de asemenea, să înțeleagă și alte formate de date, mai centrate pe om, cum ar fi datele relative precum "ieri" sau "vinerea trecută la prânz".
endif::git-commit[]
