ARQUIVO DE CONFIGURAÇÃO
-----------------------

O arquivo de configuração do Git contém várias variáveis que afetam o comportamento dos comandos do Git. Os arquivos `.git/config` e opcionalmente `config.worktree` (consulte a seção "ARQUIVO DE CONFIGURAÇÃO" do linkgit:git-worktree[1]) em cada repositório são utilizados para armazenar a configuração para aquele repositório e o `$HOME/.gitconfig` é utilizado para armazenar uma configuração por usuário como valores alternativos para o arquivo `.git/config`. O arquivo `/etc/gitconfig` pode ser utilizado para armazenar a predefinição de uma configuração em todo o sistema.

As variáveis de configuração são usadas pelos comandos Git 'plumbing' e 'porcelain'. As variáveis são divididas em seções, sendo que o nome na variável totalmente qualificada da própria variável é o último segmento separado por pontos e o nome da seção é tudo o que vem antes do último ponto. Os nomes das variáveis não diferenciam maiúsculas de minúsculas, permitem apenas caracteres alfanuméricos e `-`, devem começar com um caractere alfabético. Algumas variáveis podem aparecer diversas vezes; dizemos então que a variável é multivalorada.

Sintaxe
~~~~~~~

The syntax is fairly flexible and permissive. Whitespace characters, which in this context are the space character (SP) and the horizontal tabulation (HT), are mostly ignored. The '#' and ';' characters begin comments to the end of line. Blank lines are ignored.

O arquivo consiste em seções e variáveis. Uma seção começa com o nome da seção entre colchetes e continua até o início da próxima seção. Os nomes das seções não diferenciam maiúsculas de minúsculas. Apenas caracteres alfanuméricos, `-` e `.` são permitidos nos nomes das seções. Cana variável deve pertencer a alguma seção, o que significa que deve haver um cabeçalho da seção antes da primeira configuração de uma variável.

As seções podem ser divididas em subseções. Para iniciar uma subseção, coloque seu nome entre aspas duplas, separado pelo espaço do nome da seção no cabeçalho da seção, como mostra o exemplo abaixo:

--------
	[seção "subseção"]

--------

Os nomes da subseção diferem maiúsculas de minúsculas e podem conter qualquer caractere, exceto o caracter de nova linha e byte nulo. Aspas duplas `"` e a barra invertida podem ser incluídas escapando-as como `\\"` e `\\`, respectivamente. As barras invertidas que precedam outros caracteres, são eliminadas durante a leitura; por exemplo, `t` e `\0` são lidos como `0`. Os cabeçalhos da seção não podem abranger diversas linhas. As variáveis podem pertencer diretamente a uma seção ou a uma determinada subseção. Você pode ter `[seção]` se tiver `[seção "subseção"]`, mas não é necessário.

Também existe uma sintaxe obsoleta `[section.subsection]`. Com esta sintaxe o nome da subseção é convertido em minúsculas e também é comparado com distinção entre maiúsculas e minúsculas. Estes nomes de subseções seguem as mesmas restrições que os nomes de seção.

Todas as outras linhas (e o restante da linha após o cabeçalho da seção) são reconhecidas como variáveis de definição, no formulário 'name = valor' (ou apenas 'name', que é um atalho para dizer que a variável é um booleano "true"). Os nomes das variáveis não diferenciam maiúsculas de minúsculas, permitem apenas caracteres alfanuméricos e `-`, devem começar com um caractere alfabético.

Whitespace characters surrounding `name`, `=` and `value` are discarded. Internal whitespace characters within 'value' are retained verbatim. Comments starting with either `#` or `;` and extending to the end of line are discarded. A line that defines a value can be continued to the next line by ending it with a backslash (`\`); the backslash and the end-of-line characters are discarded.

If `value` needs to contain leading or trailing whitespace characters, it must be enclosed in double quotation marks (`"`). Inside double quotation marks, double quote (`"`) and backslash (`\`) characters must be escaped: use `\"` for `"` and `\\` for `\`.

As seguintes sequências com caracteres de escape (além de `\"` e `\\`) são reconhecidas: `\n` para caractere de nova linha (NL), `\t` para tabulação horizontal (HT, TAB) e `\b` para backspace (BS). Outras seqüências com caracteres de escape (incluindo sequências de fuga octal) são inválidas.


Inclui
~~~~~~

As seções `include` e `includeIf` permitem que você inclua diretivas da configuração de outra fonte. Estas seções se comportam de forma idêntica, com exceção das seções `includeIf` que podem ser ignorados se a sua condição não for avaliada como verdadeira; consulte "Inclusão condicional" abaixo.

Você pode incluir um arquivo da configuração de outro configurando a variável especial `include.path` (ou `includeIf.*.path`) como o nome do arquivo a ser incluído. A variável assume um nome do caminho como seu valor e está sujeita à expansão do til. Estas variáveis podem ser utilizadas várias vezes.

O conteúdo do arquivo incluído é inserido imediatamente como se tivessem sido encontrados no local da diretiva incluir. Se o valor na variável for um caminho relativo, o caminho será considerado relativo ao arquivo de configuração onde a diretiva include foi encontrada. Veja os exemplos abaixo.

Inclusão condicional
~~~~~~~~~~~~~~~~~~~~

Você pode condicionalmente incluir um arquivo da configuração de um outro condicionalmente definindo uma variável `includeIf.<condição>.path` para o nome do arquivo que será incluído.

A condição começa com uma palavra-chave seguida de dois pontos e alguns dados cujo formato e significado dependem da palavra-chave. As palavras-chave compatíveis são:

`gitdir`::
	The data that follows the keyword `gitdir` and a colon is used as a glob pattern. If the location of the .git directory matches the pattern, the include condition is met.
+
O local .git pode ser descoberto automaticamente ou vir da variável de ambiente `$GIT_DIR`. Caso o repositório seja descoberto automaticamente por meio de um arquivo .git (de submódulos ou uma árvore de trabalho vinculada por exemplo), o local .git será o local final onde está o diretório .git, e não onde o arquivo git está.
+
O padrão pode conter curingas de mascaramento padrão e dois adicionais, `**/` e `/**`, que podem coincidir com diversos componentes do caminho. Para mais detalhes, consulte o linkgit:gitignore[5] para detalhes. Por conveniência:

 * Caso o padrão comece com `~/`, `~` será substituído com o conteúdo da variável de ambiente `HOME`.

 * Caso o padrão comece com `./`, é substituído com o diretório contendo o arquivo da configuração atual.

 * Caso o padrão não comece com com nenhum `~/`, `./` ou `/`, `**/` será anexado automaticamente. O padrão `foo/bar` se torna `**/foo/bar` e coincidirá com `/qualquer/caminho/para/foo/bar` por exemplo.

 * Caso o padrão termine com `/`, `**` será adicionado automaticamente. O padrão `foo/` se torna `foo/**` por exemplo. Em outras palavras, ele combina "foo" e tudo dentro, recursivamente.

`gitdir/i`::
	É o mesmo que `gitdir` exceto que a coincidência é feita sem distinguir as maiúsculas das minusculas (em sistemas onde seja indiferente o sistema de arquivos não se importa com maiúsculas de minusculas)

`onbranch`::
	The data that follows the keyword `onbranch` and a colon is taken to be a pattern with standard globbing wildcards and two additional ones, `**/` and `/**`, that can match multiple path components. If we are in a worktree where the name of the branch that is currently checked out matches the pattern, the include condition is met.
+
Caso o padrão termine com `/`, `**` será adicionado automaticamente. O padrão `foo/` se torna `foo/**` por exemplo. Em outras palavras, ele coincide com todos os ramos que começam com `foo/`. Isso é útil pois caso as suas ramificações estejam organizadas hierarquicamente e você queira aplicar uma configuração em todas as ramificações nesta hierarquia.

`hasconfig:remote.*.url`::
	The data that follows this keyword and a colon is taken to be a pattern with standard globbing wildcards and two additional ones, `**/` and `/**`, that can match multiple components. The first time this keyword is seen, the rest of the config files will be scanned for remote URLs (without applying any values). If there exists at least one remote URL that matches this pattern, the include condition is met.
+
Os arquivos inclusos por esta opção (direta ou indiretamente) não podem conter URLs remotas.
+
Note que, ao contrário de outras condições, resolver essa condição depende de informações que ainda não são conhecidas no momento da leitura da condição. Um caso de uso típico é que essa opção está presente como uma configuração a nível de sistema ou uma configuração de global, a URL remota está em uma configuração de nível local; daí a necessidade de digitalizar à frente ao resolver essa condição. A fim de evitar conflitos onde os arquivos incluídos podem afetar se tais arquivos estão potencialmente inclusos, o Git quebra o ciclo, proibindo estes arquivos de afetar a resolução destas condições (assim, proibindo-os de declarar URLs remotas).
+
Quanto a nomenclatura dessa palavra-chave, ela é compatível com um esquema de nomenclatura compatível com mais condições de inclusão com base em variáveis, mas, atualmente o Git suporta apenas a palavra-chave exata descrita acima.

Algumas poucas anotações sobre coincidir através de `gitdir` e `gitdir/i`:

 * Os "symlinks" (links simbólicos) em `$GIT_DIR` não são resolvidos antes que sejam coincididos.

 * Ambas as versões do "symlink" (links simbólico) e do "realpath" (caminho real) dos caminhos serão coincididos fora do `$GIT_DIR`. Por exemplo, caso `~/git` seja um link simbólico para /mnt/storage/git, ambos os `gitdir:~/git` e `gitdir:/mnt/storage/git` coincidirão.
+
Este não foi o caso no lançamento inicial desse recurso na versão v2.13.0, que coincidia apenas à versão do caminho real. A configuração que queira ser compatível com o lançamento inicial deste recurso precisa definir apenas a versão do caminho real ou das duas versões.

 * Note que "../" não é especial e não irá coincidir literalmente, o que não é o que você quer.

Exemplo
~~~~~~~

----
# Principais variáveis
[core]
	; Não confie nos modos dos arquivos
	filemode = false

# Nosso algoritmo diff
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

[ramo "devel"]
	remote = origin
	merge = refs/heads/devel

# Configurações de proxy
[core]
	gitProxy="ssh" for "kernel.org"
	gitProxy=default-proxy ; for the rest

[include]
	path = /path/to/foo.inc ; incluído através de um caminho absoluto
	path = foo.inc ; find "foo.inc" relativo ao arquivo atual
	path = ~/foo.inc ; find "foo.inc" no seu diretório `$HOME`

; inclua caso $GIT_DIR seja /path/to/foo/.git
[includeIf "gitdir:/path/to/foo/.git"]
	path = /path/to/foo.inc

; inclua em todos os repositórios dentro do /path/to/group
[includeIf "gitdir:/path/to/group/"]
	path = /path/to/foo.inc

; inclua em todos os repositórios dentro do $HOME/to/group
[includeIf "gitdir:~/to/group/"]
	path = /path/to/foo.inc

; os caminhos relativos são sempre relativos à inclusão
; do arquivo (caso a condição seja verdadeira); a sua localização não é
; afetada pela condição
[includeIf "gitdir:/path/to/group/"]
	path = foo.inc

; inclua apenas caso estejamos em uma árvore de trabalho
; onde "foo-branch" seja verificado
[includeIf "onbranch:foo-branch"]
	path = foo.inc

; inclua apenas caso exista um ramo remoto com a URL fornecida (observe
; que tal URL pode ser fornecida posteriormente num arquivo ou num
; arquivo lido após este arquivo ser lido, como visto neste exemplo)
[includeIf "hasconfig:remote.*.url:https://example.com/**"]
	path = foo.inc
[remote "origin"]
	url = https://example.com/git
----

Valores
~~~~~~~

Os Valores das várias variáveis são tratadas como uma cadeia de caracteres simples, porém existem variáveis que pegam os valores de tipos específicos e existem regras de como soletrá-los.

booleano::

       Quando uma variável pega um valor booleano, muitos sinônimos são aceitos para 'true' e 'false', estes são todos insensíveis as mudanças de maiúsculas e minusculas.

	verdadeiro;; Os valores válidos para verdadeiro num literal booleano são `yes`, `on`, `true` e `1`. Além disso, uma variável definida sem um valor `= <valor>` é considerado como verdadeiro.

	falso;; Os falsos literais booleanos são `no`, `off`, `false`, `0` e a string vazia.
+
Quando converter um valor para a sua forma canônica utilizando o `--type=bool`, tipo de especificação 'git config' se assegurará que a saída seja 'true' ou 'false' (em minusculas).

inteiro::
       O valor das muitas variáveis que determinam os vários tamanhos podem ter como sufixo `k`, `M`,... que significa "escale o número por 1024", "por 1024x1024", etc.

color::
       O valor de uma variável que pega uma cor de uma lista de cores (ao menos duas, uma para o primeiro plano e outra para o plano de fundo) e os atributos (quantos queira), separados por espaços.
+
São aceitas as seguintes cores básicas `normal`, `black`, `red`, `green`, `yellow`, `blue`, `magenta`, `cyan`, `white` e `default`. A primeira cor informada é o primeiro plano; a segunda é o plano de fundo. Todas as cores básicas, exceto `normal` e `default`, têm uma variação brilhante que pode ser especificada prefixando a cor com `bright`, como `brightred`.
+
A cor `normal` não faz qualquer alteração na cor. É o mesmo que uma string vazia mas pode ser usada como a cor do primeiro plano ao definir apenas uma cor de fundo ("normal red" por exemplo).
+
A cor `default` repõe explicitamente a cor predefinida do terminal, por exemplo, para definir um fundo sem cor. Embora varie entre os terminais, isso normalmente não é o mesmo que definir para "white black" (branco preto).
+
Colors may also be given as numbers between 0 and 255; these use ANSI 256-color mode (but note that not all terminals may support this). If your terminal supports it, you may also specify 24-bit RGB values as hex, like `#ff0ab3`, or 12-bit RGB values like `#f1b`, which is equivalent to the 24-bit color `#ff11bb`.
+
Os atributos aceitos são `bold`, `dim`, `ul`, `blink`, `reverse`, `italic` e `strike` (para letras tachadas ou "strikethrough"). É indiferente a posição de qualquer atributo com relação às cores (antes, depois ou no meio). Atributos específicos podem ser desativados prefixando-os com `no` ou `no-` (por exemplo, `noreverse`, `no-ul` etc.).
+
O pseudo-atributo `reset` redefine todas as cores e os atributos antes de aplicar a cor definida. Por exemplo, o `reset green` resultará em um primeiro plano verde e o fundo padrão sem qualquer atributo ativo.
+
Uma sequência de cores vazias não produz nenhum efeito de cor. Isso pode ser utilizado para evitar colorir elementos específicos sem desabilitar totalmente a cor.
+
Para os espaços de cor predefinidos do git, os atributos devem ser redefinidos no início de cada item da saída colorida. Portanto, a configuração de `color.decorate.branch` como `black` pintará o nome da ramificação como `black`, mesmo que o item anterior na mesma linha de saída (abrir parênteses antes da lista de nomes de ramificações na saída `log --decorate` por exemplo) esteja configurado para ser pintado com `bold` ou algum outro atributo. No entanto, os formatos de registro personalizados podem fazer uma coloração mais complicada e em camadas, nesse caso, as formas negadas podem ser úteis.

caminho do diretório::
	Uma variável que recebe um valor para o nome do caminho pode receber uma cadeia de caracteres que começa com "`~/`" ou "`~user/`", a expansão usual do til acontece com essa cadeia de caracteres: `~/` é expandida para o valor `$HOME`, e `~user/` para o diretório inicial do usuário que foi definido.
+
Caso um caminho comece com `%(prefixo)/`, o restante será interpretado como um caminho em relação ao "prefixo de tempo de execução" do Git, ou seja, em relação ao local onde o próprio Git foi instalado. Por exemplo, `%(prefixo)/bin/` refere-se ao diretório onde o próprio executável Git está. Se o Git for compilado sem suporte ao "runtime prefix support" (prefixo de tempo de execução), o prefixo compilado será substituído. No caso improvável de que um caminho literal precise ser especificado e que não_ deva_ser expandido, ele precisa ser prefixado por `./`, assim: `./%(prefixo)/bin`.
+
If prefixed with `:(optional)`, the configuration variable is treated as if it does not exist, if the named path does not exist.

Variáveis
~~~~~~~~~

Observe que essa lista não é abrangente e não está necessariamente completa. Para variáveis específicas de comando, você encontrará uma descrição mais detalhada na página apropriada do manual.

Outras ferramentas relacionadas ao git podem usar e usam as suas próprias variáveis. Ao inventar novas variáveis para uso em sua própria ferramenta, certifique-se que seus nomes não entrem em conflito com aqueles usados pelo próprio Git e por outras ferramentas populares, descreva-os em sua própria documentação.

include::config/add.adoc[]

include::config/advice.adoc[]

include::config/alias.adoc[]

include::config/am.adoc[]

include::config/apply.adoc[]

include::config/attr.adoc[]

include::config/bitmap-pseudo-merge.adoc[]

include::config/blame.adoc[]

include::config/branch.adoc[]

include::config/browser.adoc[]

include::config/bundle.adoc[]

include::config/checkout.adoc[]

include::config/clean.adoc[]

include::config/clone.adoc[]

include::config/color.adoc[]

include::config/column.adoc[]

include::config/commit.adoc[]

include::config/commitgraph.adoc[]

include::config/completion.adoc[]

include::config/core.adoc[]

include::config/credential.adoc[]

include::config/diff.adoc[]

include::config/difftool.adoc[]

include::config/extensions.adoc[]

include::config/fastimport.adoc[]

include::config/feature.adoc[]

include::config/fetch.adoc[]

include::config/filter.adoc[]

include::config/format.adoc[]

include::config/fsck.adoc[]

include::config/fsmonitor--daemon.adoc[]

include::config/gc.adoc[]

include::config/gitcvs.adoc[]

include::config/gitweb.adoc[]

include::config/gpg.adoc[]

include::config/grep.adoc[]

include::config/gui.adoc[]

include::config/guitool.adoc[]

include::config/help.adoc[]

include::config/http.adoc[]

include::config/i18n.adoc[]

include::config/imap.adoc[]

include::config/includeif.adoc[]

include::config/index.adoc[]

include::config/init.adoc[]

include::config/instaweb.adoc[]

include::config/interactive.adoc[]

include::config/log.adoc[]

include::config/lsrefs.adoc[]

include::config/mailinfo.adoc[]

include::config/mailmap.adoc[]

include::config/maintenance.adoc[]

include::config/man.adoc[]

include::config/merge.adoc[]

include::config/mergetool.adoc[]

include::config/notes.adoc[]

include::config/pack.adoc[]

include::config/pager.adoc[]

include::config/pretty.adoc[]

include::config/promisor.adoc[]

include::config/protocol.adoc[]

include::config/pull.adoc[]

include::config/push.adoc[]

include::config/rebase.adoc[]

include::config/receive.adoc[]

include::config/reftable.adoc[]

include::config/remote.adoc[]

include::config/remotes.adoc[]

include::config/repack.adoc[]

include::config/rerere.adoc[]

include::config/revert.adoc[]

include::config/safe.adoc[]

include::config/sendemail.adoc[]

include::config/sequencer.adoc[]

include::config/showbranch.adoc[]

include::config/sparse.adoc[]

include::config/splitindex.adoc[]

include::config/ssh.adoc[]

include::config/stash.adoc[]

include::config/status.adoc[]

include::config/submodule.adoc[]

include::config/tag.adoc[]

include::config/tar.adoc[]

include::config/trace2.adoc[]

include::config/trailer.adoc[]

include::config/transfer.adoc[]

include::config/uploadarchive.adoc[]

include::config/uploadpack.adoc[]

include::config/url.adoc[]

include::config/user.adoc[]

include::config/versionsort.adoc[]

include::config/web.adoc[]

include::config/worktree.adoc[]
