git-rebase(1)
=============

NOME
----
git-rebase - Reaplique os commits em cima do topo de outra base

RESUMO
------
[verse]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>]
	[--onto <newbase> | --keep-base] [<upstream> [<branch>]]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>] [--onto <newbase>]
	--root [<branch>]
'git rebase' (--continue|--skip|--abort|--quit|--edit-todo|--show-current-patch)

DESCRIĂĂO
---------
Transplant a series of commits onto a different starting point. You can also use `git rebase` to reorder or combine commits: see INTERACTIVE MODE below for how to do that.

For example, imagine that you have been working on the `topic` branch in this history, and you want to "catch up" to the work done on the `master` branch.

------------
          A---B---C topic
         /
    D---E---F---G master
------------

You want to transplant the commits you made on `topic` since it diverged from `master` (i.e. A, B, and C), on top of the current `master`. You can do this by running `git rebase master` while the `topic` branch is checked out. If you want to rebase `topic` while on another branch, `git rebase master topic` is a shortcut for `git checkout topic && git rebase master`.

------------
                  A'--B'--C' topic
                 /
    D---E---F---G master
------------


If there is a merge conflict during this process, `git rebase` will stop at the first problematic commit and leave conflict markers. If this happens, you can do one of these things:

1. Resolve the conflict. You can use `git diff` to find the markers (<<<<<<) and make edits to resolve the conflict. For each file you edit, you need to tell Git that the conflict has been resolved. You can mark the conflict as resolved with `git add <filename>`. After resolving all of the conflicts, you can continue the rebasing process with

   git rebase --continue

2. Stop the `git rebase` and return your branch to its original state with

   git rebase --abort

3. Skip the commit that caused the merge conflict with

   git rebase --skip

If you don't specify an `<upstream>` to rebase onto, the upstream configured in `branch.<name>.remote` and `branch.<name>.merge` options will be used (see linkgit:git-config[1] for details) and the `--fork-point` option is assumed. If you are currently not on any branch or if the current branch does not have a configured upstream, the rebase will abort.

Here is a simplified description of what `git rebase <upstream>` does:

1. Make a list of all commits on your current branch since it branched off from `<upstream>` that do not have an equivalent commit in `<upstream>`.
2. Check out `<upstream>` with the equivalent of `git checkout --detach <upstream>`.
3. Replay the commits, one by one, in order. This is similar to running `git cherry-pick <commit>` for each commit. See REBASING MERGES for how merges are handled.
4. Update your branch to point to the final commit with the equivalent of `git checkout -B <branch>`.

[NOTE]
When starting the rebase, `ORIG_HEAD` is set to point to the commit at the tip of the to-be-rebased branch. However, `ORIG_HEAD` is not guaranteed to still point to that commit at the end of the rebase if other commands that change `ORIG_HEAD` (like `git reset`) are used during the rebase. The previous branch tip, however, is accessible using the reflog of the current branch (i.e. `@{1}`, see linkgit:gitrevisions[7]).

TRANSPLANTING A TOPIC BRANCH WITH --ONTO
----------------------------------------

Aqui estĂĄ como vocĂȘ transplantaria um ramo do tĂłpico com base num ramo para outro, para fingir que vocĂȘ bifurcou o ramo do tĂłpico deste Ășltimo ramo, utilizando `rebase --onto`.

Primeiro, vamos supor que seu 'tĂłpico' tenha como base o ramo 'next'. Por exemplo, um recurso desenvolvido no 'tĂłpico' depende de alguma funcionalidade encontrada em 'next'.

------------
    o---o---o---o---o  master
         \
          o---o---o---o---o  next
                           \
                            o---o---o  topic
------------

Queremos criar um 'tĂłpico' bifurcado no ramo 'master'; porque a funcionalidade da qual o 'tĂłpico' depende foi mesclado na ramificaĂ§ĂŁo 'master' mais estĂĄvel. Queremos que a nossa ĂĄrvore fique assim:

------------
    o---o---o---o---o  master
        |            \
        |             o'--o'--o'  topic
         \
          o---o---o---o---o  next
------------

Podemos conseguir isso utilizando o seguinte comando:

    git rebase --onto master next topic


Outro exemplo da opĂ§ĂŁo `--onto` Ă© fazer o rebase de uma parte de um ramo. Se tivermos a seguinte situaĂ§ĂŁo:

------------
                            H---I---J topicB
                           /
                  E---F---G  topicA
                 /
    A---B---C---D  master
------------

entĂŁo o comando

    git rebase --onto master topicA topicB

resultaria em:

------------
                 H'--I'--J'  topicB
                /
                | E---F---G  topicA
                |/
    A---B---C---D  master
------------

Ă Ăștil quando o 'topicB' nĂŁo depender do 'topicA'.

Uma sĂ©rie de commits tambĂ©m pode ser removida com o rebase. Se tivermos a seguinte situaĂ§ĂŁo:

------------
    E---F---G---H---I---J  topicA
------------

entĂŁo o comando

    git rebase --onto topicA~5 topicA~3 topicA

resultaria na remoĂ§ĂŁo dos commits 'F' e 'G':

------------
    E---H'---I'---J'  topicA
------------

Isso Ă© Ăștil se F e G tiverem alguma falha ou nĂŁo devam fazer parte do "topicA". Observe que o argumento para a opĂ§ĂŁo `--onto` e o parĂąmetro `<upstream>` podem ser qualquer tipo vĂĄlido de commit.

MAIS OPĂĂES
-----------

As opĂ§Ă”es nesta seĂ§ĂŁo, nĂŁo podem ser usadas com nenhuma outra opĂ§ĂŁo, inclusive entre si:

--continue::
	Reinicie o processo de reformulaĂ§ĂŁo apĂłs resolver um conflito de mesclagem.

--skip::
	Reinicie o processo de reconstruĂ§ĂŁo da fundaĂ§ĂŁo ignorando o patch atual.

--abort::
	Interrompa a operaĂ§ĂŁo de reconstruĂ§ĂŁo da fundaĂ§ĂŁo e redefina o `HEAD` para o ramo original. Caso `<ramo>` seja informado quando a operaĂ§ĂŁo de reconstruĂ§ĂŁo da fundaĂ§ĂŁo seja iniciada, o `HEAD` serĂĄ redefinido para `<ramo>`. Caso contrĂĄrio, o `HEAD` serĂĄ redefinido para onde estava quando a operaĂ§ĂŁo de reconstruĂ§ĂŁo foi iniciada.

--quit::
	Interrompa a operaĂ§ĂŁo de reconstruĂ§ĂŁo, porĂ©m o `HEAD` nĂŁo serĂĄ redefinido para o ramo original. Como resultado, o Ă­ndice e a ĂĄrvore de trabalho tambĂ©m permanecem inalterados. Caso uma entrada temporĂĄria "stash" seja criada utilizando `--autostash`, ela serĂĄ salva na lista "stash".

--edit-todo::
	Edite a lista de tarefas durante uma nova reconstruĂ§ĂŁo interativa.

--show-current-patch::
	Exiba o patch atual numa nova recuperaĂ§ĂŁo interativa ou quando a nova recuperaĂ§ĂŁo for interrompida por causa de conflitos. Ă o equivalente ao `git show REBASE_HEAD`.

OPĂĂES
------
--onto <nova-base>::
	Ponto de partida para a criaĂ§ĂŁo de novos commits. Se a opĂ§ĂŁo `--onto` nĂŁo for usada, o ponto de partida serĂĄ `<upstream>`. Pode ser qualquer commit vĂĄlido, e nĂŁo apenas um nome jĂĄ existente do ramo.
+
Como um caso especial, vocĂȘ pode utilizar "A\...B" como um atalho para a base de mesclagem 'A' e 'B' caso haja exatamente uma base para mesclagem. VocĂȘ pode deixar de fora no mĂĄximo um de 'A' e 'B'; nesse caso, a predefiniĂ§ĂŁo retorna para `HEAD`.

See TRANSPLANTING A TOPIC BRANCH WITH --ONTO above for examples.

--keep-base::
	Defina o ponto de partida para criar os novos commits para a mesclagem base do `<upstream>` e `<ramo>`. Executando o comando `git rebase --keep-base <upstream> <ramo>` Ă© o mesmo que executar o comando `git rebase --reapply-cherry-picks --no-fork-point --onto <upstream>...<ramo> <upstream> <ramo>`.
+
Esta opĂ§ĂŁo Ă© Ăștil no caso onde se estĂĄ desenvolvendo um recurso em cima de um ramo 'upstream'. Enquanto o recurso estĂĄ sendo trabalhado, o ramo 'upstream' pode avanĂ§ar e talvez nĂŁo seja a melhor ideia continuar reconstruindo no topo do 'upstream', porĂ©m manter a base do commit como estĂĄ. Como a base do commit permanece inalterado, esta opĂ§ĂŁo implica no uso da opĂ§ĂŁo `--reapply-cherry-picks` para evitar a perda dos commits.
+
Embora esta opĂ§ĂŁo e o `--fork-point` encontrem a base da mesclagem entre `<upstream>` e `<ramo>`, esta opĂ§ĂŁo utiliza a base da mesclagem como o _ponto inicial_ onde os novos commits serĂŁo criados, enquanto `--fork-point` utiliza a mesclagem da base para determinar o _conjunto dos commits_ que serĂŁo reconstruĂ­dos.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

<upstream>::
	O ramo upstream para fazer comparaĂ§ĂŁo. Pode ser qualquer commit vĂĄlido, e nĂŁo apenas um nome jĂĄ existente do ramo. A predefiniĂ§ĂŁo retorna ao upstream configurado para a ramificaĂ§ĂŁo atual.

<ramo>::
	Ramo de trabalho; A predefiniĂ§ĂŁo retorna para `HEAD`.

--apply::
	Use estratĂ©gias de aplicaĂ§ĂŁo para fazer o rebase (invocando o comando `git-am` internamente). Esta opĂ§ĂŁo pode se tornar inĂștil no futuro, uma vez que o backend da mesclagem lida com tudo o que o backend de aplicaĂ§ĂŁo faz.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--empty=(drop|keep|stop)::
	Como lidar com commits que nĂŁo estĂŁo vazios no inĂ­cio e nĂŁo sĂŁo cherry-picks limpos de nenhum commit do upstream, mas tornam-se vazios apĂłs a reconstruĂ§ĂŁo (pois contĂ©m um subconjunto de alteraĂ§Ă”es da upstream):
+
--
`drop`;;
	The commit will be dropped. This is the default behavior.
`keep`;;
	The commit will be kept. This option is implied when `--exec` is specified unless `-i`/`--interactive` is also specified.
`stop`;;
`ask`;;
	The rebase will halt when the commit is applied, allowing you to choose whether to drop it, edit files more, or just commit the empty changes. This option is implied when `-i`/`--interactive` is specified. `ask` is a deprecated synonym of `stop`.
--
+
Observe que, os commits que comeĂ§am vazios sĂŁo mantidos (a menos que a opĂ§ĂŁo `--no-keep-empty` seja utilizado) e os commits que sĂŁo escolhas limpas (conforme determinado pelo comando `git log --cherry-mark ...`) sĂŁo detectados e descartados como uma etapa preliminar (a menos que a opĂ§ĂŁo `--reapply-cherry-picks` ou `--keep-base` seja utilizado).
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--no-keep-empty::
--keep-empty::
	NĂŁo mantenha os commits que comeĂ§am vazios antes do rebase (ou seja, que nĂŁo alteram nada em relaĂ§ĂŁo ao commit principal) no resultado. A predefiniĂ§ĂŁo Ă© manter os commits que comeĂ§am vazios, uma vez que a criaĂ§ĂŁo de tais commits requer o uso da opĂ§ĂŁo de substituiĂ§ĂŁo `--allow-empty` para o comando `git commit`, o que significa que um usuĂĄrio estĂĄ intencionalmente criando tal commit e, portanto, deseja mantĂȘ-lo.
+
O uso desta opĂ§ĂŁo Ă© provavelmente raro, uma vez que vocĂȘ pode se livrar dos commits que comeĂ§am vazios simplesmente iniciando um rebase interativo e removendo as linhas correspondentes aos commits que nĂŁo deseja. Esta opĂ§ĂŁo existe como um atalho conveniente, como nos casos onde as ferramentas externas geram muitos commits vazios e vocĂȘ deseja que todos sejam removidos.
+
Para os commits que nĂŁo comeĂ§am vazios, mas ficam vazios apĂłs o 'rebase', consulte a opĂ§ĂŁo `--empty`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--reapply-cherry-picks::
--no-reapply-cherry-picks::
	Reaplique todas as escolhas seletivas que estejam limpas de qualquer commit "upstream" em vez inviabilizĂĄ-los por completo. (EntĂŁo, caso estes commits se tornem vazios depois da reconstruĂ§ĂŁo, por conter um subconjunto de alteraĂ§Ă”es da "upstream", o comportamento em direĂ§ĂŁo Ă  eles Ă© controlado atravĂ©s da opĂ§ĂŁo `--empty`.)
+
Na ausĂȘncia da opĂ§ĂŁo `--keep-base` (ou se `--no-reapply-cherry-picks` for usado), estes commits serĂŁo automaticamente descartados. Como isso exige a leitura de todos os commits "upstream", pode acabar saindo caro em repositĂłrios com uma grande quantidade de commits "upstream" que precisam ser lidos. Ao usar o backend 'merge', serĂŁo emitidos avisos para cada commit descartado (a menos que a opĂ§ĂŁo `--quiet` seja usada). O aviso tambĂ©m serĂĄ emitido a menos que `advice.skippedCherryPicks` esteja definido como falso (consulte linkgit:git-config[1]).
+
A opĂ§ĂŁo `--reapply-cherry-picks` permite que a reconstruĂ§ĂŁo anteceda a leitura de todos os commits "upstream", melhorando muito o desempenho.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--allow-empty-message::
	NĂŁo operacional (no-op). O rebase dos commits com uma mensagem vazia costumava falhar e esta opĂ§ĂŁo substituiria esse comportamento, permitindo o rebase dos commits com mensagens vazias. Agora, os commits com uma mensagem vazia nĂŁo causam a interrupĂ§ĂŁo do rebase.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

-m::
--merge::
	Usando estratĂ©gias de mesclagem para o rebase (padrĂŁo).
+
Observe que uma mesclagem rebase funciona reproduzindo cada commit do ramo de trabalho sobre o ramo `<upstream>`. Por esse motivo, quando ocorre um conflito de mesclagem, o lado relatado como "nosso" Ă© a sĂ©rie atĂ© entĂŁo refeita, comeĂ§ando com `<upstream>`, e o "deles" Ă© o ramo de trabalho. Em outras palavras, os lados sĂŁo trocados.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

-s <estratĂ©gia>::
--strategy=<estratĂ©gia>::
	Usa a estratĂ©gia de mesclagem fornecida, em vez da predefiniĂ§ĂŁo `ort`. Implica no uso da opĂ§ĂŁo `--merge`.
+
Como o `git rebase` repete cada commit do ramo de trabalho no cume do ramo <upstream> utilizando a estratĂ©gia informada, o uso da `nossa` estratĂ©gia simplesmente esvazia todos os patches do `<ramo>`, que faz pouco sentido.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

-X <opĂ§ĂŁo-da-estratĂ©gia>::
--strategy-option=<opĂ§ĂŁo-da-estratĂ©gia>::
	Encaminhe a <opĂ§ĂŁo-da-estratĂ©gia> para a estratĂ©gia de mesclagem. Implica no uso da opĂ§ĂŁo `--merge` e, se nenhuma estratĂ©gia tiver sido especificada, a predefiniĂ§ĂŁo Ă© `-s ort`. Observe a inversĂŁo de 'ours' (nosso) e 'theirs' (deles), conforme observado acima para a opĂ§ĂŁo `-m`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

include::rerere-options.adoc[]

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	Commits assinados com o GPG O argumento `keyid` Ă© opcional e a predefiniĂ§ĂŁo retorna para a identidade de quem fez o commit; caso seja utilizado, deve estar anexado a opĂ§ĂŁo e sem espaĂ§o. A opĂ§ĂŁo `--no-gpg-sign` Ă© Ăștil para revogar a variĂĄvel de configuraĂ§ĂŁo `commit.gpgSign` e a anterior `--gpg-sign`.

-q::
--quiet::
	Fique em silĂȘncio. Implica no uso da opĂ§ĂŁo `--no-stat`.

-v::
--verbose::
	Seja loquaz. Implica no uso de `--stat`.

--stat::
	Exiba uma descriĂ§ĂŁo do que mudou na upstream desde a Ășltima reconstruĂ§ĂŁo (rebase). O diffstat tambĂ©m Ă© controlado pela opĂ§ĂŁo de configuraĂ§ĂŁo `rebase.stat`.

-n::
--no-stat::
	NĂŁo mostre um "diffstat" como parte do processo de reconstruĂ§ĂŁo da fundaĂ§ĂŁo (rebase).

--no-verify::
	Essa opĂ§ĂŁo ignora o gancho rebase prĂ©vio. Consulte tambĂ©m linkgit:githooks[5].

--verify::
	Permite que o hook rebase prĂ©vio seja executado, que Ă© a predefiniĂ§ĂŁo. Essa opĂ§ĂŁo pode ser usada para substituir a opĂ§ĂŁo `--no-verify`. Consulte tambĂ©m linkgit:githooks[5].

-C<n>::
	Certifique-se de que pelo menos `<n>` linhas do contexto circundante correspondam antes e apĂłs cada alteraĂ§ĂŁo. Quando houver menos linhas de contexto ao redor, todas elas devem corresponder. Ă predefinido que nenhum contexto seja ignorado. Implica no uso da opĂ§ĂŁo `--apply`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--no-ff::
--force-rebase::
-f::
	Reproduz individualmente todos os commits refeitos em vez de avanĂ§ar rapidamente sobre os que estiverem inalterados. Isso garante que todo o histĂłrico da ramificaĂ§ĂŁo refeita atravĂ©s do "rebase" seja composto de novos commits.
+
Pode ser Ăștil apĂłs reverter uma mesclagem do ramo "topic", pois esta opĂ§ĂŁo recria o ramo "topic" com os novos commits, para que possa ser recuperado com ĂȘxito sem precisar "reverter a reversĂŁo" (para mais detalhes, consulte o link:howto/revert-a-faulty-merge.html[Como reverter uma falha da mesclagem]).

--fork-point::
--no-fork-point::
	Utilize reflog para encontrar um ancestral comum melhor entre a `<upstream>` e o `<ramo>` ao calcular quais os commits foram introduzidos pelo `<ramo>`.
+
Quando a opĂ§ĂŁo `--fork-point` estiver ativa, o 'fork_point' serĂĄ utilizado em vez do `<upstream>` para calcular o conjunto de commits que serĂŁo refeitos via "rebase", onde o 'fork_point' Ă© o resultado do comando `git merge-base --fork-point <upstream> <ramo>` (consulte linkgit:git-merge-base[1]). Se o 'fork_point' estiver vazio, o `<upstream>` serĂĄ usado como contingĂȘncia.
+
Caso a `<upstream>` ou a opĂ§ĂŁo `--keep-base` seja utilizada na linha de comando, a predefiniĂ§ĂŁo serĂĄ `--no-fork-point`, caso contrĂĄrio, a predefiniĂ§ĂŁo serĂĄ `--fork-point`. Consulte tambĂ©m `rebase.forkpoint` em linkgit:git-config[1].
+
Caso o seu ramo teve como base no `<upstream>`, porĂ©m `<upstream>` foi retrocedido e o seu ramo contĂ©m commits que foram eliminados, esta opĂ§ĂŁo pode ser utilizada com a opĂ§ĂŁo `--keep-base` para eliminar estes commits do seu ramo.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--ignore-whitespace::
	Ignore as diferenĂ§as dos espaĂ§os ao tentar reconciliar as diferenĂ§as. Atualmente, cada estrutura implementa uma aproximaĂ§ĂŁo deste comportamento:
+
aplica o "backend";;
	Ao aplicar um patch, ignore as alteraĂ§Ă”es no espaĂ§o das linhas do contexto. Infelizmente, isto significa que caso as linhas "antigas" sendo substituĂ­das pelo patch difiram apenas pelo espaĂ§o do arquivo existente haverĂĄ um conflito de integraĂ§ĂŁo em vez da aplicaĂ§ĂŁo bem sucedida do patch.
+
mescla o "backend";;
	Trate as linhas apenas com alteraĂ§Ă”es de espaĂ§o em branco como linhas inalteradas durante a mesclagem. Infelizmente, isso significa que todos os fragmentos das correĂ§Ă”es destinados a alterar os espaĂ§os em branco e nada mais serĂĄ descartado, ainda que o outro lado nĂŁo tenha feito alteraĂ§Ă”es conflitantes.

--whitespace=<opĂ§ĂŁo>::
	Esta opĂ§ĂŁo Ă© repassada para o comando `git apply` (consulte linkgit:git-apply[1]) que aplica a correĂ§ĂŁo. Implica no uso da opĂ§ĂŁo `--apply`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--committer-date-is-author-date::
	Em vez de usar a hora atual como a data de quem fez o commit, utilize a data do autor que fez o rebase do commit como a data do commit. Esta opĂ§ĂŁo implica no uso de `--force-rebase`.
+
WARNING: The history walking machinery assumes that commits have non-decreasing commit timestamps. You should consider if you really need to use this option. Then you should only use this option to override the committer date when rebasing commits on top of a base which commit is older (in terms of the commit date) than the oldest commit you are applying (in terms of the author date).

--ignore-date::
--reset-author-date::
	Em vez de usar a data do autor do commit original, use a hora atual como a data do autor do commit refeito via "rebase". Implica no uso da opĂ§ĂŁo `--force-rebase`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--signoff::
	Adicione uma resposta `Assinado-por` em todos os commits que tiveram a sua fundaĂ§ĂŁo reconstruĂ­da. Observe que caso a opĂ§ĂŁo `--interactive` seja utilizada, apenas os commit marcados para serem selecionados, editados ou reformulados terĂŁo um caracteres de resposta adicionado.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--trailer=<trailer>::
	Append the given trailer to every rebased commit message, processed via linkgit:git-interpret-trailers[1]. This option implies `--force-rebase`.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

-i::
--interactive::
	FaĂ§a uma lista dos commits que estĂŁo prestes a ser refeitos com o "rebase". Deixe o usuĂĄrio editar esta lista antes de realizar o "rebase". Esse modo tambĂ©m pode ser usado para dividir os commits (consulte 'DIVIDINDO OS COMMITS' abaixo).
+
O formato da lista dos commits pode ser alterado ao definir a configuraĂ§ĂŁo ÂŽrebase.instructionFormat`. Um formato de instruĂ§ĂŁo personalizado terĂĄ automaticamente o hash do commit anexado ao formato.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

-r::
--rebase-merges[=(rebase-cousins|no-rebase-cousins)]::
--no-rebase-merges::
	Ă predefinido que um "rebase" simplesmente eliminarĂĄ a mesclagem dos commits da lista de tarefas e colocarĂĄ os commits que foram refeitos num Ășnico ramo linear. Com `--rebase-merges`, a reconstruĂ§ĂŁo com o "rebase" tentarĂĄ preservar a estrutura da ramificaĂ§ĂŁo dentro dos commits que devem sofrer a reconstruĂ§ĂŁo, recriando a mesclagem dos commits. Quaisquer conflitos resolvidos na mesclagem ou nas emendas manuais destas mesclagens dos commits terĂŁo que ser resolvidos ou aplicados manualmente. A opĂ§ĂŁo `--no-rebase-merges` pode ser usada para anular a opĂ§ĂŁo de configuraĂ§ĂŁo `rebase.rebaseMerges` e um `--rebase-merges` anterior.
+
Ao refazer as mesclagens com o "rebase", existem dois modos: `rebase-cousins` e `no-rebase-cousins`. Se o modo nĂŁo for especificado, a predefiniĂ§ĂŁo serĂĄ `no-rebase-cousins`. No modo `no-rebase-cousins`, os commits que nĂŁo tĂȘm `<upstream>` como ancestral direto manterĂŁo o seu ponto de ramificaĂ§ĂŁo original, ou seja, os commits que seriam excluĂ­dos pela opĂ§ĂŁo `--ancestry-path` do linkgit:git-log[1] manterĂŁo a sua ancestralidade original automaticamente. No modo `rebase-cousins`, esses commits sĂŁo rebaseados em `<upstream>` (ou `<onto>`, se especificado).
+
Atualmente, sĂł Ă© possĂ­vel recriar a mesclagem dos commits utilizando a estratĂ©gia de mesclagem `ort`; diferentes estratĂ©gias de mesclagem podem ser utilizadas somente atravĂ©s dos comandos explĂ­citos como `exec git merge -s <strategy> [...]`.
+
Consulte tambĂ©m 'RECONSTRUINDO AS MESCLAGENS' e 'OPĂĂES INCOMPATĂVEIS' abaixo.

-x <cmd>::
--exec <cmd>::
	Anexe "exec <cmd>" apĂłs cada linha, criando um commit no final do histĂłrico. O `<cmd>` serĂĄ interpretado como um ou mais comandos do shell. Qualquer comando que falhar interromperĂĄ a reconstruĂ§ĂŁo da fundaĂ§ĂŁo, encerrando com o cĂłdigo 1.
+
Ă possĂ­vel executar vĂĄrios comandos utilizando uma instĂąncia da opĂ§ĂŁo `--exec` com vĂĄrios comandos:
+
	git rebase -i --exec "cmd1 && cmd2 && ..."
+
ou utilizando mais de um `--exec`:
+
	git rebase -i --exec "cmd1" --exec "cmd2" --exec ...
+
Caso a opĂ§ĂŁo `--autosquash` seja utilizado, as linhas `exec` nĂŁo serĂŁo anexadas aos commits intermediĂĄrios e aparecerĂŁo apenas no final de cada sĂ©rie de compressĂŁo/correĂ§ĂŁo.
+
Utiliza o mecanismo `--interactive` internamente, porĂ©m pode ser executado sem a opĂ§ĂŁo `--interactive` de forma explicita.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--root::
	RefaĂ§a com "rebase" todos os commits acessĂ­veis a partir do `<ramo>`, em vez de limitĂĄ-los com um `<upstream>`. Isso permite que vocĂȘ faĂ§a o rebase num ramo do(s) commit(s) raiz(es).
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--autosquash::
--no-autosquash::
	Automatically squash commits with specially formatted messages into previous commits being rebased. If a commit message starts with "squash! ", "fixup! " or "amend! ", the remainder of the title is taken as a commit specifier, which matches a previous commit if it matches the title or the hash of that commit. If no commit matches fully, matches of the specifier with the start of commit titles are considered.
+
Na lista de tarefas do rebase, as aĂ§Ă”es dos commits 'squash', 'fixup' e 'amend' sĂŁo alteradas de `pick` para `squash`, `fixup` ou `fixup -C`, respectivamente, e sĂŁo movidas logo apĂłs o commit que eles modificam. A opĂ§ĂŁo `--interactive` pode ser usada para revisar e editar a lista de tarefas antes de dar continuidade.
+
The recommended way to create commits with squash markers is by using the `--squash`, `--fixup`, `--fixup=amend:` or `--fixup=reword:` options of linkgit:git-commit[1], which take the target commit as an argument and automatically fill in the title of the new commit from that.
+
Setting configuration variable `rebase.autoSquash` to true enables auto-squashing by default for interactive rebase. The `--no-autosquash` option can be used to override that setting.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

--autostash::
--no-autostash::
	Crie automaticamente uma entrada de armazenamento temporĂĄrio antes do inĂ­cio da operaĂ§ĂŁo e aplique-a ao concluir a operaĂ§ĂŁo. Isso significa que vocĂȘ pode executar o "rebase" numa ĂĄrvore de trabalho suja. No entanto, use-o com cuidado: o aplicativo de armazenamento final apĂłs um"rebase" bem-sucedido pode resultar em conflitos nĂŁo triviais.

--reschedule-failed-exec::
--no-reschedule-failed-exec::
	Reagende automaticamente os comandos `exec` que falharam. Isso sĂł faz sentido no modo interativo (ou quando uma opĂ§ĂŁo `--exec` for utilizada).
+
Esta opĂ§ĂŁo se aplica quando um "rebase" for iniciado. Ele Ă© preservado com base para todo o "rebase", em ordem, na opĂ§ĂŁo de linha de comando usada para o `git rebase` inicial, a configuraĂ§ĂŁo `rebase.rescheduleFailedExec` (consulte linkgit:git-config[1] ou "CONFIGURAĂĂO" abaixo), ou a predefiniĂ§ĂŁo Ă© 'false'.
+
O registro desta opĂ§ĂŁo para todo o "rebase" Ă© um recurso conveniente. Caso contrĂĄrio, um `--no-reschedule-failed-exec` explĂ­cito no inĂ­cio seria substituĂ­do pela presenĂ§a de uma configuraĂ§ĂŁo `rebase.rescheduleFailedExec=true` quando o `git rebase --continue` fosse invocado. Atualmente, vocĂȘ nĂŁo pode passar `--[no-]reschedule-failed-exec` para o comando `git rebase --continue`.

--update-refs::
--no-update-refs::
	Atualize automaticamente todas as ramificaĂ§Ă”es que apontem para os commits onde os "rebases" estejam sendo feitos. Quaisquer ramificaĂ§Ă”es forem verificadas numa ĂĄrvore de trabalho nĂŁo sĂŁo atualizadas desta maneira.
+
Caso a variĂĄvel de configuraĂ§ĂŁo `rebase.updateRefs` esteja definida, entĂŁo esta opĂ§ĂŁo pode ser usada para substituir e desativar esta configuraĂ§ĂŁo.
+
Consulte tambĂ©m a seĂ§ĂŁo "OPĂĂES INCOMPATĂVEIS" logo abaixo.

OPĂĂES INCOMPATĂVEIS
--------------------

As seguintes opĂ§Ă”es:

 * --apply
 * --whitespace
 * -C

sĂŁo incompatĂ­veis com as seguintes opĂ§Ă”es:

 * --merge
 * --strategy
 * --strategy-option
 * --autosquash
 * --rebase-merges
 * --interactive
 * --exec
 * --no-keep-empty
 * --empty=
 * --[no-]reapply-cherry-picks quando utilizado com --keep-base
 * --update-refs
 * --root quando utilizado sem o --onto
 * --trailer

AlĂ©m disso, os seguintes pares de opĂ§Ă”es sĂŁo incompatĂ­veis:

 * --keep-base e --onto
 * --keep-base e --root
 * --fork-point e --root

DIFERENĂAS COMPORTAMENTAIS
--------------------------

O `git rebase` tem dois backends principais: 'apply' e 'merge'. (O backend 'apply' costumava ser conhecido como backend 'am', mas o nome gerou confusĂŁo, pois parece um verbo em vez de um substantivo. AlĂ©m disso, o backend 'merge' costumava ser conhecido como backend interativo, mas agora tambĂ©m Ă© usado para casos nĂŁo interativos. Ambos foram renomeados com base na funcionalidade de baixo nĂ­vel que sustentava cada um deles). HĂĄ algumas diferenĂ§as sutis na maneira de como estes dois backends se comportam:

Os commits vazios
~~~~~~~~~~~~~~~~~

Infelizmente, o backend 'apply' descarta os commits vazios intencionalmente, ou seja, os commits que comeĂ§aram vazios, embora isso seja raro na prĂĄtica. Ele tambĂ©m descarta os commits que ficam vazios e nĂŁo hĂĄ opĂ§ĂŁo para controlar este comportamento.

Ă predefinido que a estrutura 'merge' mantenha os commits intencionalmente vazios (com `-i` sĂŁo marcados como vazio no editor da lista de tarefas ou podem ser descartados automaticamente com a opĂ§ĂŁo `--no-keep-empty`).

Similar to the apply backend, by default the merge backend drops commits that become empty unless `-i`/`--interactive` is specified (in which case it stops and asks the user what to do). The merge backend also has an `--empty=(drop|keep|stop)` option for changing the behavior of handling commits that become empty.

DetecĂ§ĂŁo da renomeaĂ§ĂŁo do diretĂłrio
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Devido Ă  falta de informaĂ§Ă”es precisas sobre a ĂĄrvore (decorrente da construĂ§ĂŁo de ancestrais falsos com as informaĂ§Ă”es limitadas disponĂ­veis nas correĂ§Ă”es), a detecĂ§ĂŁo da renomeaĂ§ĂŁo do diretĂłrio estĂĄ desativada no backend 'apply'. A detecĂ§ĂŁo desativada da renomeaĂ§ĂŁo do diretĂłrio significa que, se um lado do histĂłrico renomear um diretĂłrio e o outro adicionar novos arquivos ao diretĂłrio antigo, os novos arquivos serĂŁo deixados para trĂĄs no diretĂłrio antigo sem nenhum aviso no momento do "rebase".

A detecĂ§ĂŁo da renomeaĂ§ĂŁo do diretĂłrio funciona com a estrutura 'merge', neste caso, fornecendo informaĂ§Ă”es para vocĂȘ.

Contexto
~~~~~~~~

The 'apply' backend works by creating a sequence of patches (by calling `format-patch` internally), and then applying the patches in sequence (calling `am` internally). Patches are composed of multiple hunks, each with line numbers, a context region, and the actual changes. The line numbers have to be taken with some offset, since the other side will likely have inserted or deleted lines earlier in the file. The context region is meant to help find how to adjust the line numbers in order to apply the changes to the right lines. However, if multiple areas of the code have the same surrounding lines of context, the wrong one can be picked. There are real-world cases where this has caused commits to be reapplied incorrectly with no conflicts reported. Setting `diff.context` to a larger value may prevent such types of problems, but increases the chance of spurious conflicts (since it will require more lines of matching context to apply).

A estrutura 'merge' trabalha com a cĂłpia completa de casa arquivo relevante isolando-os destes tipos de problemas.

A rotulagem dos marcadores de conflitos
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Quando hĂĄ conflitos no conteĂșdo, o mecanismo de mesclagem tenta anotar os marcadores de conflito de cada lado com os commits de onde o conteĂșdo veio. Como o backend 'apply' descarta as informaĂ§Ă”es originais sobre os commits refeitos com rebase e as suas origens (e, em vez disso, gera novos commits falsos com base em informaĂ§Ă”es limitadas nas correĂ§Ă”es geradas), estes commits nĂŁo podem ser identificados; em vez disso, Ă© necessĂĄrio recorrer a um resumo do commit. AlĂ©m disso, quando `merge.conflictStyle` for definido como `diff3` ou `zdiff3`, o backend 'apply' usarĂĄ "constructed merge base" para rotular o conteĂșdo da base de mesclagem e, portanto, nĂŁo fornecerĂĄ nenhuma informaĂ§ĂŁo sobre o commit da mesclagem da base.

A estrutura 'merge' funciona com commits completos nos dois lados do histĂłrico e portanto nĂŁo possuem tais limitaĂ§Ă”es.

Ganchos
~~~~~~~

Tradicionalmente, o backend 'apply' nĂŁo invoca o gancho pĂłs commit, enquanto o backend 'merge' invoca. Ambos invocam o gancho "pĂłs-checkout", embora o backend 'merge' tenha suprimido a sua criaĂ§ĂŁo. AlĂ©m disso, ambos os "backends" sĂł invocam o gancho "pĂłs-checkout" com o commit do ponto inicial do rebase, nĂŁo invoca nos commits intermediĂĄrios nem no commit final. Em cada caso, a invocaĂ§ĂŁo destes hooks ocorreu por acidente de implementaĂ§ĂŁo e nĂŁo por projeto (ambos os backends foram originalmente implementados como scripts de shell e invocaram outros comandos como `git checkout` ou `git commit` que invocariam os ganchos). Ambos os backends devem ter o mesmo comportamento, embora nĂŁo esteja totalmente claro qual deles estĂĄ correto, quando estiverem. Provavelmente faremos com que o rebase pare de invocar estes ganchos no futuro.

Interruptabilidade
~~~~~~~~~~~~~~~~~~

O backend 'apply' tem problemas de seguranĂ§a com uma interrupĂ§ĂŁo inoportuna; se o usuĂĄrio pressionar Ctrl-C no momento errado para tentar abortar o rebase, o rebase pode entrar num estado onde nĂŁo pode ser abortado apĂłs um `git rebase --abort`. O backend 'merge' nĂŁo parece sofrer da mesma deficiĂȘncia. (Consulte https://lore.kernel.org/git/20200207132152.GC2868@szeder.dev/ para obter mais detalhes.)

Reescrevendo os Commits
~~~~~~~~~~~~~~~~~~~~~~~

Quando ocorre um conflito durante o rebase, ele Ă© interrompido e o usuĂĄrio Ă© solicitado a resolver o problema. Como o usuĂĄrio talvez precise fazer alteraĂ§Ă”es importantes durante a resoluĂ§ĂŁo de conflitos, apĂłs a resoluĂŁo dos conflitos e o usuĂĄrio tiver executado o comando `git rebase --continue`, o rebase deverĂĄ abrir um editor e solicitar que o usuĂĄrio atualize a mensagem do commit. O backend 'merge' faz isso, enquanto o backend 'apply' aplica cegamente a mensagem original do commit.

DiferenĂ§as diversas
~~~~~~~~~~~~~~~~~~~

Existem mais algumas diferenĂ§as comportamentais que a maioria das pessoas considerariam fazer de forma inconsequente, porĂ©m sĂŁo mencionadas por questĂ”es de integridade:

* Reflog: As duas estruturas que utilizarĂŁo palavras diferentes durante a descriĂ§ĂŁo das alteraĂ§Ă”es feitas no reflog, embora ambos faĂ§am a utilizaĂ§ĂŁo da palavra "rebase".

* Mensagens de progresso, informativas e de erro: Os dois backends fornecem mensagens ligeiramente diferentes de progresso e informacionais. AlĂ©m disso, o backend 'apply' grava mensagens de erro (como "Seus arquivos seriam sobrescritos...") no stdout, enquanto o backend 'merge' as grava no stderr.

* DiretĂłrios de estado: As duas estruturas mantĂȘm a sua condiĂ§ĂŁo em diferentes diretĂłrios dentro do `.git/`

include::merge-strategies.adoc[]

OBSERVAĂĂES
-----------

VocĂȘ deve entender as implicaĂ§Ă”es de usar o comando `git rebase` num repositĂłrio que vocĂȘ compartilha. Consulte tambĂ©m SE RECUPERANDO DA RECONSTRUĂĂO DA FUNDAĂĂO INICIAL (UPSTREM REBASE) abaixo.

Quando o rebase for executado, ele primeiro executarĂĄ um gancho `pre-rebase`, caso exista um. VocĂȘ pode usar esse gancho para fazer verificaĂ§Ă”es de sanidade e rejeitar o rebase caso nĂŁo seja apropriado. Consulte o script modelo do gancho do `pre-rebase` para ver um exemplo.

ApĂłs a conclusĂŁo, o `<ramo>` serĂĄ o ramo atual.

MODO INTERATIVO
---------------

O rebase interativo significa que vocĂȘ tem a chance de editar os commits onde o rebase foi feito. VocĂȘ pode reordenar os commits e removĂȘ-los (eliminando correĂ§Ă”es ruins ou indesejados).

O modo interativo Ă© destinado para este tipo de fluxo de trabalho:

1. tenho uma ideia maravilhosa
2. hackear o cĂłdigo
3. preparar uma sĂ©rie para envio
4. enviar

onde o ponto 2. consiste em vĂĄrias instĂąncias do

a) uso regular

 1. termine algo digno de um commit
 2. commit

b) correĂ§ĂŁo independente

 1. perceber que algo nĂŁo funciona
 2. conserte isso
 3. faĂ§a o commit

Ăs vezes, o problema Ă© corrigido na versĂŁo b.2. NĂŁo pode ser emendado no commit parcialmente perfeito que ele corrige, porque este commit estĂĄ profundamente entranhado numa sĂ©rie de correĂ§Ă”es. Ă exatamente para isso que serve o rebase interativo: use-o apĂłs muitos "a" e "b", ao reorganizar e editar os commits e acumulando vĂĄrios commits num sĂł.

Inicie-o com o Ășltimo commit que vocĂȘ quer manter como estĂĄ:

	git rebase -i <apĂłs-este-commit>

Um editor serĂĄ acionado com todos os commits em seu ramo atual (ignorando a mesclagem dos commits), que vĂȘm apĂłs o commit informado. VocĂȘ pode reordenar os commits nesta lista como quiser e tambĂ©m Ă© possĂ­vel removĂȘ-los. A lista Ă© mais ou menos assim:

-------------------------------------------
pick deadbee Uma linha deste commit
pick fa1afe1 Uma linha do prĂłximo commit
...
-------------------------------------------

As descriĂ§Ă”es on-line sĂŁo puramente para o seu prazer; o comando 'git rebase' nĂŁo examinarĂĄ eles, porĂ©m os nomes dos commits ("deadbee" e "fa1afe1" neste exemplo), portanto, nĂŁo exclua ou edite os nomes.

Ao substituir o comando "pick" pelo comando "edit", Ă© possĂ­vel dizer ao comando `git rebase` para parar apĂłs aplicar este commit, para que seja possĂ­vel editar os arquivos e/ou a mensagem do commit, alterar o commit e continuar com a reconstruĂ§ĂŁo.

Para interromper um "rebase" (exatamente como um comando "edit" faria, mas sem fazer uma escolha seletiva de nenhum commit primeiro), use o comando "break".

Caso apenas queira editar a mensagem do commit para um commit, substitua o comando `pick` pelo comando `reword`.

Para eliminar um commit, substitua o comando "pick" por "drop" ou apenas exclua a linha coincidente.

Se vocĂȘ quiser juntar dois ou mais commits num sĂł, substitua o comando 'pick' para o segundo commit e os subsequentes com 'squash' ou 'fixup'. Se os commits tiverem autores diferentes, o commit agrupado serĂĄ atribuĂ­do ao autor do primeiro commit. A mensagem sugerida do commit para o commit agrupado Ă© a concatenaĂ§ĂŁo da mensagem do primeiro commit com aquelas identificadas pelos comandos 'squash', omitindo as mensagens dos commits identificados pelos comandos 'fixup', a menos que 'fixup -c' seja usado. Nesse caso, a mensagem sugerida do commit Ă© apenas a mensagem do commit 'fixup -c', e um editor Ă© aberto para que vocĂȘ possa editar a mensagem. O conteĂșdo (correĂ§ĂŁo) do commit 'fixup -c' ainda Ă© incorporado ao commit agrupado. Se houver mais de um commit 'fixup -c', serĂĄ usada a mensagem do Ășltimo commit. VocĂȘ tambĂ©m pode usar 'fixup -C' para obter o mesmo comportamento de 'fixup -c', mas sem abrir um editor.

O comando `git rebase` serĂĄ interrompido quando o "pick" for substituĂ­do por "edit" ou quando um comando falhar devido aos erros da mesclagem. Quando vocĂȘ terminar de editar e/ou resolver os conflitos, serĂĄ possĂ­vel continuar utilizando `git rebase --continue`.

Como por exemplo, caso vocĂȘ queira reordenar os Ășltimos 5 commits de maneira onde o que era `HEAD~4` se torne o novo `HEAD`. Para conseguir isso, vocĂȘ chamaria o comando `git rebase` assim:

----------------------
$ git rebase -i HEAD~5
----------------------

E mova o primeiro patch para o ramo da lista.

ConvĂ©m recriar a mesclagem dos commits, por exemplo, caso tenha um histĂłrico como este:

------------------
           X
            \
         A---M---B
        /
---o---O---P---Q
------------------

Suponha que queira reconstruir o lado do ramo ao lado comeĂ§ando em "A" para "Q". Verifique se o `HEAD` atual Ă© "B" e chame

-----------------------------
$ git rebase -i -r --onto Q O
-----------------------------

A reordenaĂ§ĂŁo e a ediĂ§ĂŁo dos commits geralmente criam etapas intermediĂĄrias nĂŁo testadas. Talvez vocĂȘ queira verificar se a ediĂ§ĂŁo do histĂłrico nĂŁo quebrou nada executando um teste ou, pelo menos, recompilando em pontos intermediĂĄrios do histĂłrico usando o comando 'exec' (o atalho Ă© 'x'). VocĂȘ pode fazer isso criando uma lista de tarefas como esta:

-------------------------------------------
pick deadbee Implement feature XXX
fixup f1a5c00 Fix to feature XXX
exec make
pick c0ffeee The oneline of the next commit
edit deadbab The oneline of the commit after
exec cd subdir; make test
...
-------------------------------------------

A reconstruĂ§ĂŁo interativa serĂĄ interrompida quando um comando falhar (ou seja, encerra com uma condiĂ§ĂŁo diferente de 0) oferecendo uma oportunidade para a correĂ§ĂŁo do problema. VocĂȘ pode continuar com o comando `git rebase --continue`.

O comando 'exec' inicia o comando num shell (a ÂŽpredefiniĂ§ĂŁo, geralmente Ă© /bin/sh), para que vocĂȘ possa usar os recursos do shell (como 'cd', '>', ';' ...). O comando Ă© executado a partir da raiz da ĂĄrvore de trabalho.

----------------------------------
$ git rebase -i --exec "make test"
----------------------------------

Esse comando permite que vocĂȘ verifique se os commits intermediĂĄrios sĂŁo compilĂĄveis. A lista de tarefas fica assim:

--------------------
pick 5928aea one
exec make test
pick 04d0fda two
exec make test
pick ba46169 three
exec make test
pick f4593f9 four
exec make test
--------------------

DIVIDINDO OS COMMITS	
---------------------

No modo interativo, vocĂȘ pode marcar commits com a aĂ§ĂŁo 'edit' (editar). No entanto, isso nĂŁo significa necessariamente que o comando `git rebase` espera que o resultado desta ediĂ§ĂŁo seja exatamente um commit. De fato, vocĂȘ pode desfazer o commit ou adicionar outros commits. Isso pode ser usado para dividir um commit em dois:

- Inicie um rebase interativo com `git rebase -i <commit>^`, onde `<commit>` Ă© o commit que vocĂȘ deseja dividir. Na verdade, qualquer intervalo do commit serve, desde que contenha este commit.

- Marque o commit que deseja dividir com a aĂ§ĂŁo "edit".

- Quando for necessĂĄrio editar esse commit, execute o comando `git reset HEAD^`. O efeito Ă© que o `HEAD` Ă© rebobinado num, e o Ă­ndice segue o mesmo caminho. No entanto, a ĂĄrvore de trabalho permanece a mesma.

- Agora, adicione as alteraĂ§Ă”es ao Ă­ndice onde vocĂȘ deseja ter no primeiro commit. VocĂȘ pode usar o comando `git add` (possivelmente de forma interativa) ou o comando `git gui` (ou ambos) para fazer isso.

- FaĂ§a o commit do Ă­ndice agora atual com qualquer mensagem do commit que seja apropriada.

- Repita as duas Ășltimas etapas atĂ© que a sua ĂĄrvore de trabalho esteja limpa.

- Continue a reconstruĂ§ĂŁo com `git rebase --continue`.

Caso nĂŁo tenha certeza absoluta que as revisĂ”es intermediĂĄrias sĂŁo consistentes (elas compilam, passam no conjunto de testes, etc.), vocĂȘ deve usar o `git stash` para armazenar o commit das alteraĂ§Ă”es que ainda nĂŁo foram feitas apĂłs cada commit, teste e corrija o commit caso correĂ§Ă”es sejam necessĂĄrias.


SE RECUPERANDO DA RECONSTRUĂĂO DA FUNDAĂĂO INICIAL (UPSTREM REBASE)
-------------------------------------------------------------------

Fazer o rebase (ou qualquer outra forma de reescrita) de uma ramificaĂ§ĂŁo onde outras pessoas trabalharam Ă© uma mĂĄ ideia: qualquer pessoa que esteja a posteriori dela Ă© forĂ§ada a corrigir seu histĂłrico manualmente. Esta seĂ§ĂŁo explica como fazer a correĂ§ĂŁo do ponto de vista de quem fez depois. A verdadeira correĂ§ĂŁo, no entanto, seria evitar o rebase da ponta em primeiro lugar.

Para ilustrar, imagine que vocĂȘ esteja numa situaĂ§ĂŁo onde alguĂ©m desenvolve um 'subsystem' no ramo e vocĂȘ estĂĄ trabalhando num 'topic' que depende deste 'subsystem'. VocĂȘ pode acabar com um histĂłrico como este:

------------
    o---o---o---o---o---o---o---o  master
	 \
	  o---o---o---o---o  subsystem
			   \
			    *---*---*  topic
------------

Caso a reconstruĂ§ĂŁo da fundaĂ§ĂŁo do 'subsystem' seja realizada contra o 'master', o seguinte acontece:

------------
    o---o---o---o---o---o---o---o  master
	 \			 \
	  o---o---o---o---o	  o'--o'--o'--o'--o'  subsystem
			   \
			    *---*---*  topic
------------

Caso agora continue o desenvolvimento normalmente e eventualmente mescle o 'topic' para 'subsystem', os commits do 'subsystem' permanecerĂŁo duplicados para sempre:

------------
    o---o---o---o---o---o---o---o  master
	 \			 \
	  o---o---o---o---o	  o'--o'--o'--o'--o'--M	 subsystem
			   \			     /
			    *---*---*-..........-*--*  topic
------------

Estas duplicatas sĂŁo geralmente desaprovadas, pois desorganizam o histĂłrico, tornando-o mais difĂ­cil de acompanhar. Para limpar as coisas, vocĂȘ precisa transplantar os commits em 'topic' para o novo topo 'subsystem', ou seja, rebase 'topic'. Isso se torna um efeito cascata: qualquer pessoa que esteja apĂłs 'topic' Ă© forĂ§ada a refazer a base tambĂ©m, e assim por diante!

Existem dois tipos de correĂ§Ă”es, discutidos nas seguintes subseĂ§Ă”es:

Caso fĂĄcil: as alteraĂ§Ă”es sĂŁo literalmente as mesmas.::

	Isso acontece caso a reconstruĂ§ĂŁo do 'subsystem' foi uma reconstruĂ§ĂŁo simples e nĂŁo houve conflitos.

Caso difĂ­cil: as alteraĂ§Ă”es nĂŁo sĂŁo as mesmas.::

	Isso acontece caso a reconstruĂ§ĂŁo da fundaĂ§ĂŁo (rebase) do 'subsistema' tiver conflitos ou utilizar o `--interactive` para omitir, editar, esmagar ou consertar consertos; ou se a inicial utilizou um dos comandos `commit --amend`, `reset` ou um histĂłrico completo da reescrita como https://github.com/newren/git-filter-repo[`filter-repo`].


O caso fĂĄcil
~~~~~~~~~~~~

Funciona apenas se as alteraĂ§Ă”es (IDs do patch com base no conteĂșdo do diff) no 'subsystem' que forem literalmente as mesmas antes e depois da reconstruĂ§ĂŁo do 'subsystem'.

Nesse caso, a correĂ§ĂŁo Ă© fĂĄcil porque o comando 'git rebase' sabe ignorar as alteraĂ§Ă”es que jĂĄ estĂŁo presentes no novo 'upstream' (a menos que `--reapply-cherry-picks` seja utilizada). EntĂŁo, se vocĂȘ diz (supondo que vocĂȘ esteja no 'topic')

------------
    $ git rebase subsystem
------------
vocĂȘ vai acabar com o histĂłrico fixo

------------
    o---o---o---o---o---o---o---o  master
				 \
				  o'--o'--o'--o'--o'  subsystem
						   \
						    *---*---*  topic
------------


O caso difĂ­cil
~~~~~~~~~~~~~~

As coisas ficam mais complicadas caso as alteraĂ§Ă”es do "subsistema" nĂŁo coincidam de forma exata aquelas antes da reconstruĂ§ĂŁo.

NOTE: Embora uma "recuperaĂ§ĂŁo fĂĄcil dos casos" Ă s vezes pareĂ§a ser bem-sucedida
      mesmo no caso difĂ­cil, pode haver consequĂȘncias nĂŁo intencionais.  Para
      Por exemplo, um commit que foi removido atravĂ©s do comando `git rebase
      --interactive` serĂĄ **ressuscitado**!

A ideia Ă© informar manualmente ao comando `git rebase` "onde o antigo 'subsystem' terminou e o seu 'topic' comeĂ§ou", ou seja, qual era a antiga mesclagem de base entre eles. VocĂȘ terĂĄ que encontrar uma maneira de nomear o Ășltimo commit do antigo 'subsystem', por exemplo:

* Com o reflog do 'subsystem': apĂłs o comando `git fetch`, a ponta antiga do 'subsystem' estĂĄ em `subsystem@{1}`. As buscas seguintes aumentarĂŁo o nĂșmero. (Consulte linkgit:git-reflog[1].)

* Em relaĂ§ĂŁo ao cume do 'topic': sabendo que o seu 'topic' tem trĂȘs commits, o cume antigo do 'subsystem' deve ser `topic~3`.

VocĂȘ pode entĂŁo transplantar o antigo `subsystem..topic` para o novo cume dizendo (para o caso do reflog e supondo que vocĂȘ jĂĄ esteja no 'topic'):

------------
    $ git rebase --onto subsystem subsystem@{1}
------------

O efeito cascata de uma recuperaĂ§ĂŁo "difĂ­cil" (hard case) Ă© especialmente ruim: 'todos' baixaram do 'topic' e agora terĂŁo que executar tambĂ©m uma reconstruĂ§ĂŁo "difĂ­cil"!

RECONSTRUINDO AS MESCLAGENS
---------------------------

O comando de reconstruĂ§ĂŁo interativa foi originalmente projetado para lidar com sĂ©ries de patches individuais. Como tal, faz sentido excluir a mesclagem dos commits da lista de tarefas, pois o desenvolvedor pode ter mesclado o `master` atual enquanto trabalhava no ramo, apenas para redefinir todos os commits para `master` eventualmente (ignorando a mesclagem dos commits).

No entanto, existem razĂ”es legĂ­timas pelas quais um desenvolvedor pode querer recriar as mesclagens dos commits: para manter a estrutura do ramo (ou a "topologia do commit") ao trabalhar em diversos ramos inter-relacionadas.

No exemplo a seguir, o desenvolvedor trabalha em um tĂłpico no ramo que refatora a maneira como os botĂ”es sĂŁo definidos, em outro tĂłpico do ramo que utilize esta refatoraĂ§ĂŁo para implementar um botĂŁo "Relatar um bug". A saĂ­da do `git log --graph --format=%s -5` pode ficar assim:

------------
*   Mescla o ramo 'report-a-bug'
|\
| * Adiciona o botĂŁo de feedback
* | Mescla o ramo 'refactor-button'
|\ \
| |/
| * Utiliza a classe do BotĂŁo para todos os botĂ”es
| * Extrai o botĂŁo genĂ©rico do DownloadButton
------------

O desenvolvedor pode querer redefinir estes commits para um novo `master` enquanto mantĂ©m a topologia da ramificaĂ§ĂŁo. Quando se espera que o primeiro tĂłpico do ramo que seja integrado ao` master` muito antes do segundo por exemplo. Para resolver os conflitos da mesclagem com as alteraĂ§Ă”es para a classe `DownloadButton` que a transformou em `master` por exemplo.

Esse rebase pode ser realizado com a opĂ§ĂŁo `--rebase-merges`. Ele gerarĂĄ uma lista de tarefas semelhante a esta:

------------
rotular para

# Branch: refactor-button
reset onto
pick 123456 Extrai o botĂŁo genĂ©rico do DownloadButton
pick 654321 Utiliza a classe do BotĂŁo para todos os botĂ”es
label refactor-button

# Branch: report-a-bug
reset refactor-button # Utiliza a classe do BotĂŁo para todos os botĂ”es
pick abcdef Adiciona o botĂŁo de feedback
label report-a-bug

reset onto
merge -C a1b2c3 refactor-button # Mescla o 'refactor-button'
merge -C 6f5e4d report-a-bug # Mescla o 'report-a-bug'
------------

Ao contrĂĄrio de uma reconstruĂ§ĂŁo interativa regular, existem os comandos `label`, `reset` e `merge` alĂ©m dos comandos `pick`.

O comando `label` associa um rĂłtulo ao `HEAD` atual quando este comando for executado. Estes rĂłtulos sĂŁo criados como refs locais da ĂĄrvore de trabalho (`refs/rewritten/<label>`) que serĂŁo excluĂ­dos quando a reconstruĂ§ĂŁo terminar. Dessa forma, as operaĂ§Ă”es da reconstruĂ§ĂŁo em vĂĄrias ĂĄrvores de trabalho vinculadas ao mesmo repositĂłrio nĂŁo interferem entre si. Caso o comando `label` falhe, este Ă© imediatamente reagendado, com uma mensagem Ăștil sobre como proceder.

O comando `reset` redefine o `HEAD`, o Ă­ndice e a ĂĄrvore de trabalho para a revisĂŁo especĂ­fica. Ă semelhante a um comando `exec git reset --hard <label>`, porĂ©m se recusa a sobrescrever os arquivos que nĂŁo sejam monitorados. Se o comando `reset` falhar, ele serĂĄ imediatamente reagendado, com uma mensagem Ăștil sobre como editar a lista de tarefas (normalmente acontece quando um comando `reset` foi inserido manualmente na lista de tarefas e contĂ©m um erro de digitaĂ§ĂŁo).

O comando `merge` mesclarĂĄ revisĂ”es usadas no que seja `HEAD` naquele momento. Com `-C <original-commit>`, a mensagem do commit de um determinada mesclagem serĂĄ usada. Quando o `-C` Ă© alterado para minĂșsculo `-c`, a mensagem serĂĄ aberta num editor apĂłs uma mesclagem bem-sucedida, para que o usuĂĄrio possa editĂĄ-la.

Se um comando `merge` falhar por qualquer motivo que nĂŁo seja conflitos de mesclagem (ou seja, quando a operaĂ§ĂŁo de mesclagem nem sequer foi iniciada), ele serĂĄ reagendado imediatamente.

Ă predefinido que o comando `merge` use a estratĂ©gia de mesclagem `ort` para mesclagens regulares e `octopus` para mesclagens "octopus". Ă possĂ­vel especificar uma estratĂ©gia predefinida para todas as mesclagens usando o a opĂ§ĂŁo `--strategy` ao invocar o rebase, ou substituir mesclagens especĂ­ficas na lista interativa de comandos usando um comando `exec` para invocar o comando `git merge` explicitamente com a opĂ§ĂŁo `--strategy`. Observe que, ao invocar explicitamente o comando `git merge` dessa maneira, vocĂȘ pode usar o fato de que as etiquetas sĂŁo referĂȘncias locais da ĂĄrvore de trabalho (a referĂȘncia `refs/rewritten/onto` corresponderia a etiqueta `onto`, por exemplo) para se referir Ă s ramificaĂ§Ă”es que deseja mesclar.

ObservaĂ§ĂŁo: o primeiro comando (`label onto`) rotula a revisĂŁo onde os commits sĂŁo refeitos; O nome `onto` Ă© apenas uma convenĂ§ĂŁo, como um aceno para a opĂ§ĂŁo `--onto`.

TambĂ©m Ă© possĂ­vel introduzir commits para mesclagem completamente novos, adicionando um comando no formato `merge <merge-head>`. Este formulĂĄrio gera uma mensagem de commit provisĂłria e sempre abre um editor para permitir que o usuĂĄrio a edite. Pode ser Ăștil quando por exemplo, um ramo de um tĂłpico acaba resolvendo mais de um problema e quer ser dividido em dois ou mais ramos de tĂłpico. Considere esta lista de tarefas:

------------
pick 192837 Alterna do GNU Makefiles para o CMake
pick 5a6c7e Documente a alteraĂ§ĂŁo para o CMake
pick 918273 Corrija a detecĂ§ĂŁo do OpenSSL no CMake
pick afbecd http: adicione a compatibilidade com o TLS v1.3
pick fdbaec Corrija a detecĂ§ĂŁo da cURL no CMake no Windows
------------

O Ășnico commit nesta lista que nĂŁo estĂĄ relacionado ao CMake pode muito bem ter sido motivado ao trabalhar na correĂ§ĂŁo de todos os erros introduzidos durante a mudanĂ§a para o CMake, porĂ©m ele lida com um interesse diferente. Para dividir esse ramo em dois tĂłpicos, a lista de tarefas pode ser editada desta maneira:

------------
rotular para

escolha afbecd http: adicione a compatibilidade para o TLS v1.3
label tlsv1.3

redefinir para
pick 192837 Alterna do GNU Makefiles para o CMake
pick 918273 Corrija a detecĂ§ĂŁo do OpenSSL no CMake
pick fdbaec Corrija a detecĂ§ĂŁo da cURL no CMake no Windows
pick 5a6c7e Documente a alteraĂ§ĂŁo para o CMake
label cmake

reset onto
merge tlsv1.3
merge cmake
------------

CONFIGURAĂĂO
------------

include::includes/cmd-config-section-all.adoc[]

include::config/rebase.adoc[]
include::config/sequencer.adoc[]

GIT
---
Parte do conjunto linkgit:git[1]
