git-show(1)
===========

NOME
----
git-show - Exibe vários tipos de objetos


RESUMO
------
[verse]
'git show' [<opções>] [<objeto>...]

DESCRIÇÃO
---------
Exibe um ou mais objetos (bolhas, árvores, tags e commits).

Para commits, exibe a mensagem do registro log e a diferença textual. Ele também apresenta o commit de mesclagem em um formato especial, produzido por 'git diff-tree --cc'.

Para tags, ele exibe a mensagem da tag e os objetos referenciados.

Para árvores, ele exibe os nomes (equivalente a `git ls-tree` com --name-only).

Para bolhas simples, exibe o conteúdo simples.

Algumas opções que o comando 'git log' entende podem ser utilizadas para controlar como as alterações introduzidas pelo commit são mostradas.

Esta página do manual descreve apenas as opções utilizadas com mais frequência.


OPÇÕES
------
<objeto>...::
	Os nomes dos objetos que será mostrados (o padrão é `HEAD`). Para obter uma lista mais completa de maneiras de soletrar nomes de objetos, consulte a seção "ESPECIFICANDO AS REVISÕES" do comando linkgit:gitrevisions[7].

include::pretty-options.adoc[]


include::pretty-formats.adoc[]


FORMATAÇÃO DIFF
---------------
As opções abaixo podem ser usadas para alterar a maneira como o comando `git show` gera o diff.

:git-log: 1
:diff-merges-default: `dense-combined`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]


EXEMPLOS
--------

`git show v1.0.0`::
	Exibe a tag `v1.0.0` junto com o objeto que a tag apontar.

`git show v1.0.0^{tree}`::
	Exibe a árvore apontada pela tag `v1.0.0`.

`git show -s --format=%s v1.0.0^{commit}`::
	Exiba o assunto do commit apontado pela tag `v1.0.0`.

`git show next~10:Documentation/README`::
	Exibe o conteúdo do arquivo `Documentation/README` como eles estavam atualmente no décimo último commit do ramo `next`.

`git show master:Makefile master:t/Makefile`::
	Concatena o conteúdo dos referidos Makefiles no `HEAD` do ramo `master`.

DISCUSSÃO
---------

include::i18n.adoc[]

GIT
---
Parte do conjunto linkgit:git[1]
