git-rev-parse(1)
================

NOME
----
git-rev-parse - Escolha e trabalhe os parâmetros


RESUMO
------
[verse]
'git rev-parse' [<options>] <arg>...

DESCRIÇÃO
---------

Many Git porcelainish commands take a mixture of flags (i.e. parameters that begin with a dash '-') and parameters meant for the underlying 'git rev-list' command they use internally and flags and parameters for the other commands they use downstream of 'git rev-list'. The primary purpose of this command is to allow calling programs to distinguish between them. There are a few other operation modes that have nothing to do with the above "help parse command line options".

Unless otherwise specified, most of the options and operation modes require you to run this command inside a git repository or a working tree that is under the control of a git repository, and will give you a fatal error otherwise.


OPÇÕES
------

Modos de Operação
~~~~~~~~~~~~~~~~~

Cada uma destas opções deve aparecer primeiro na linha de comando.

--parseopt::
	Use 'git rev-parse' in option parsing mode (see PARSEOPT section below). The command in this mode can be used outside a repository or a working tree controlled by a repository.

--sq-quote::
	Use 'git rev-parse' in shell quoting mode (see SQ-QUOTE section below). In contrast to the `--sq` option below, this mode only does quoting. Nothing else is done to command input. The command in this mode can be used outside a repository or a working tree controlled by a repository.

As opções para `--parseopt`
~~~~~~~~~~~~~~~~~~~~~~~~~~~

--keep-dashdash::
	Apenas faz sentido no modo `--parseopt`. Informa ao analisador das opções para ecoar o primeiro `--` encontrado em vez de ignorá-lo.

--stop-at-non-option::
	Apenas faz sentido no modo `--parseopt`. Permite que o analisador de opções pare no primeiro argumento que não seja uma opção. Isto pode ser utilizado para analisar os subcomandos que recebem as opções.

--stuck-long::
	Apenas faz sentido no modo `--parseopt`. Gere as opções em sua forma longa, caso estejam disponíveis, e com os seus argumentos bloqueados.

Opções para a filtragem
~~~~~~~~~~~~~~~~~~~~~~~

--revs-only::
	Não produza opções e parâmetros não destinados ao comando 'git rev-list'.

--no-revs::
	Não produza opções e parâmetros destinados ao comando 'git rev-list'.

--flags::
	Não produza parâmetros que não sejam opções.

--no-flags::
	Não gere parâmetros para opções.

Opções para a Saída
~~~~~~~~~~~~~~~~~~~

--default <arg>::
	Caso não haja nenhum parâmetro informado pelo usuário, em vez disso utilize `<arg>`.

--prefix <arg>::
	Comporta-se como se o comando `git rev-parse` fosse invocado a partir do subdiretório `<arg>` da árvore de trabalho. Quaisquer nomes de arquivos relativos são resolvidos como se fossem prefixados pelo `<arg>` e serão impressos desta maneira.
+
Isso pode ser usado para converter argumentos num comando executado num subdiretório, de modo que eles ainda possam ser utilizados após a alteração para o nível mais alto do repositório. Por exemplo:
+
----
prefix=$(git rev-parse --show-prefix)
cd "$(git rev-parse --show-toplevel)"
# rev-parse provides the -- needed for 'set'
eval "set $(git rev-parse --sq --prefix "$prefix" -- "$@")"
----

--verify::
	Verifique que exatamente um parâmetro seja informado e se pode ser transformado num SHA-1 com 20 bytes brutos, que possa ser utilizado para acessar o banco de dados do objeto. Em caso positivo, emita-o para a saída padrão; caso contrário, gere um erro.
+
Caso queira ter certeza que o resultado realmente nomeia um objeto em seu banco de dados de objetos e/ou pode ser usado como um tipo específico e necessário do objeto, você pode adicionar o operador `^{type}` ao parâmetro. Por exemplo, comando `git rev-parse "$VAR^{commit}"` garantirá que `$VAR` nomeie um objeto já existente que seja um "commit-ish" (ou seja, um commit ou uma etiqueta anotada que aponte para um commit). Para garantir que `$VAR` nomeie um objeto existente de qualquer tipo, é possível usar o comando `git rev-parse "$VAR^{object}"`.
+
Note que se você estiver verificando um nome de uma fonte não confiável, é prudente usar a opção `--end-of-options` para que o argumento relacionado ao nome não seja confundido com uma outra opção.

-q::
--quiet::
	Apenas faz sentido no modo `--verify`. Não emita uma mensagem de erro se o primeiro argumento não for um nome de objeto válido; em vez disso, saia silenciosamente com status diferente de zero. O SHA-1 para nomes válidos dos objetos são impressos no stdout quando for bem-sucedido.

--sq::
	Normalmente, a saída é feita numa linha por opção e por parâmetro. Esta opção torna a saída numa única linha, devidamente citada para uso do shell. Útil quando você espera que o seu parâmetro tenha espaços em branco e novas linhas (por exemplo, ao usar o pickaxe `-S` com o comando 'git diff-{asterisk}'). Em contraste com a opção `--sq-quote`, a entrada do comando ainda é interpretada como de costume.

--short[=<length>]::
	O mesmo que `--verify` porém encurta o nome do objeto para um prefixo único com pelo menos um`comprimento` determinado de caracteres. A quantidade mínima é de 4 caracteres, o valor é predefinido na variável de configuração `core.abbrev` (consulte linkgit:git-config[1]).

--not::
	Ao exibir os nomes dos objetos, prefixe-os com '{caret}' e retire o prefixo '{caret}' dos nomes dos objetos que já possuam um.

--abbrev-ref[=(strict|loose)]::
	Um nome curto não ambíguo do nome do objeto. A opção `core.warnAmbiguousRefs` é usada para selecionar o modo de abreviação estrita.

--symbolic::
	Normalmente, os nomes dos objetos são emitidos em formato SHA-1 (com possível prefixo '{caret}'); essa opção faz com que eles sejam impressos o mais próximo possíveis da entrada original.

--symbolic-full-name::
	É semelhante ao `--symbolic`, porém omite a entrada que não seja uma refs (por exemplo, os nomes dos ramos ou tags; ou de uma forma explicitamente desambiguante "heads/master", quando você quer nomear a o ramo "master" quando houver uma tag com o nome "master") e mostre-os como "refnames" completos (por exemplo, "refs/heads/master").

--output-object-format=(sha1|sha256|storage)::

	Allow oids to be input from any object format that the current repository supports.

	Specifying "sha1" translates if necessary and returns a sha1 oid.

	Specifying "sha256" translates if necessary and returns a sha256 oid.

	Specifying "storage" translates if necessary and returns an oid in encoded in the storage hash algorithm.

Opções para os Objetos
~~~~~~~~~~~~~~~~~~~~~~

--all::
	Exibe todas as refs encontradas em `refs/`.

--branches[=<padrão>]::
--tags[=<padrão>]::
--remotes[=<padrão>]::
	Exibe todos as ramificações, tags ou ramificações monitoradas remotamente, respectivamente (ou seja, as refs encontradas respectivamente em `refs/heads`, `refs/tags` ou `refs/remotes`).
+
Se um `pattern` for fornecido, somente as refs que correspondam a bolha do shell informado serão exibidos. Se o padrão não possuir um caractere de globbing (`?`, `*` ou `[`), ele será transformado numa correspondência do prefixo com a adição de `/*`.

--glob=<pattern>::
	Mostra todas as refs que correspondem ao padrão da bolha do shell `pattern`. Se o padrão não começar com `refs/`, ele será automaticamente anexado. Se o padrão não possuir um caractere de globbing (`?`, `*` ou `[`), ele será transformado numa correspondência do prefixo com a adição de `/*`.

--exclude=<glob-pattern>::
	Não inclua as refs que coincidam com `<glob-pattern>` em que as próximas opções `--all`, `--branches`, `--tags`, `--remotes` ou `--glob` considerariam de outra forma. As repetições destas opções acumulam padrões de exclusão até a próxima opção `--all`, `--branches`, `--tags`, `--remotes` ou `--glob` (outras opções ou argumentos não limpam os padrões acumulados).
+
Os padrões informados não devem começar com `refs/heads`, `refs/tags`, ou `refs/remotes` quando aplicadas as opções `--branches`, `--tags`, ou `--remotes` respectivamente, e devem começar com `refs/` quando for aplicado ao `--glob` ou `--all`. Se a intenção for um delimitador '/{asterisk}', este deve ser utilizado de forma explicita.

--exclude-hidden=(fetch|receive|uploadpack)::
	Não inclua refs que seriam ocultados por `git-fetch`, `git-receive-pack` ou `git-upload-pack` durante a consulta da configuração apropriada de `fetch.hideRefs`, `receive.hideRefs` ou `uploadpack.hideRefs` junto com `transfer.hideRefs` (consulte linkgit:git-config[1]). Esta opção afeta a próxima opção pseudo-ref `--all` ou `--glob` e é zerada após o processamento.

--disambiguate=<prefixo>::
	Mostra todos os objetos cujo nome começa com o prefixo informado. O <prefixo> deve ter pelo menos 4 dígitos hexadecimais para evitar a listagem de todos os objetos do repositório por engano.

Opções para os Arquivos
~~~~~~~~~~~~~~~~~~~~~~~

--local-env-vars::
	Liste as variáveis de ambiente GIT_* que são locais para o repositório (por exemplo, `GIT_DIR` ou `GIT_WORK_TREE`, mas não `GIT_EDITOR`). Somente os nomes das variáveis são listados, não seus valores, ainda que estejam definidos.

--path-format=(absolute|relative)::
	Controla o comportamento de algumas outras opções. Se usado como absoluto, os caminhos impressos por estas opções serão absolutos e canônicos. Se usado como relativo, os caminhos serão relativos ao diretório de trabalho atual, quando isso for possível. A predefinição é específica da opção.
+
Esta opção pode ser usada várias vezes e afeta apenas os argumentos seguintes na linha de comando, seja no final da linha de comando ou na próxima instância desta opção.

As seguintes opções são modificadas pela opção `--path-format`:

--git-dir::
	Exibe o `$GIT_DIR` caso seja definido. Caso contrário, exibe o caminho para o diretório .git. O caminho exibido, quando relativo, é relativo ao diretório de trabalho atual.
+
Caso o `$GIT_DIR` não esteja definido e o diretório atual não for detectado como estando num repositório Git ou na árvore de trabalho, imprima uma mensagem para stderr e encere com uma condição diferente de zero.

--git-common-dir::
	Exibe o `$GIT_COMMON_DIR` caso seja definido, senão `$GIT_DIR`.

--resolve-git-dir <caminho>::
	Verifica se o <caminho> é um repositório válido ou um arquivo git que aponte para um repositório válido e imprima o local do repositório. Quando o <caminho> for um arquivo git, o caminho resolvido para o repositório real será impresso.

--git-path <caminho>::
	Resolva "$GIT_DIR/<caminho>" e leve em consideração as outras variáveis de realocação do caminho, como `$GIT_OBJECT_DIRECTORY`, `$GIT_INDEX_FILE`, etc. Caso `$GIT_OBJECT_DIRECTORY` seja definido para '/foo/bar' por exemplo, então o comando "git rev-parse --git-path objects/abc" returna '/foo/bar/abc'.

--show-toplevel::
	Mostra o caminho (absoluto) do cume do diretório da árvore de trabalho. Caso não haja uma árvore de trabalho, relate um erro.

--show-superproject-working-tree::
	Mostra o caminho absoluto da raiz da árvore de trabalho do superprojeto (quando houver) que use o repositório atual como seu submódulo. Não produz nada se o repositório atual não for usado como um submódulo por nenhum projeto.

--shared-index-path::
	Exibe o caminho para o arquivo do índice compartilhado no modo de índice dividido ou vazio caso não esteja no modo do índice dividido.

As seguintes opções não são afetadas pela opção `--path-format`:

--absolute-git-dir::
	Como `--git-dir`, porém sua saída é sempre o caminho absoluto canonizado.

--is-inside-git-dir::
	Quando o diretório de trabalho atual estiver abaixo do diretório do repositório, imprima 'true', caso contrário, 'false'.

--is-inside-work-tree::
	Quando o diretório de trabalho atual estiver dentro da árvore de trabalho do repositório, imprima 'true', caso contrário, 'false'.

--is-bare-repository::
	Quando o repositório for simples imprima 'true', caso contrário 'false'.

--is-shallow-repository::
	Quando o repositório é raso, imprima 'true', caso contrário, 'false'.

--show-cdup::
	Quando o comando é chamado a partir de um subdiretório, exiba o caminho do diretório do nível mais alto em relação ao diretório atual (geralmente uma sequência de "../" ou uma sequência vazia).

--show-prefix::
	Quando o comando é invocado a partir de um subdiretório, exiba o caminho do diretório atual em relação ao nível mais alto do diretório.

--show-object-format[=(storage|input|output)]::
	Mostra o formato do objeto (algoritmo de hash) usado para o repositório para armazenamento dentro do diretório `.git`, entrada ou saída. Para a entrada, os vários algoritmos podem ser impressos, separados por espaço. Se não for especificado, a predefinição será `storage`.

--show-ref-format::
	Mostra o formato da referência de armazenamento usado para o repositório.


Outras Opções
~~~~~~~~~~~~~

--since=<datestring>::
--after=<datestring>::
	Analise a cadeia de caracteres da data e exiba o parâmetro --max-age= correspondente para 'git rev-list'.

--until=<datestring>::
--before=<datestring>::
	Analise a cadeia de caracteres da data e exiba o parâmetro --min-age= que corresponda para o 'git rev-list'.

<arg>...::
	As opções e os parâmetros que serão analisados.


include::revisions.adoc[]

PARSEOPT
--------

No modo `--parseopt`, o comando 'git rev-parse' ajuda no processamento das opções trazendo aos scripts shell as mesmas facilidades integradas que o 'C' possuí. Funciona como um normalizador das opções (por exemplo, divide trocas únicas com valores agregados), quase como o que o `getopt(1)` faz.

Ele recebe na entrada predefinida a especificação das opções que serão analisadas, compreendidas e mostra na saída predefinida uma string `sh(1)` `eval` adequada para substituir os argumentos por argumentos normalizados. Em caso de erro, ele mostra como usar na saída de erro predefinida e encerra com o código 129.

Observação: Certifique-se de colocar o resultado entre aspas ao passá-lo para `eval`. Veja um exemplo abaixo.

Formato de Entrada
~~~~~~~~~~~~~~~~~~

O formato de entrada `git rev-parse --parseopt` é totalmente baseado em texto. Possuí duas partes, são separadas por uma linha que contém apenas `--`. As linhas antes do separador (deve ser uma ou mais) são usadas. As linhas após o separador descrevem as opções.

As opções de cada linha possui este formato:

------------
<opt-spec><flags>*<arg-hint>? SP+ help LF
------------

`<opt-spec>`::
	O seu formato é o caractere curto da opção, em seguida, o nome longo da opção separado por vírgula. Ambas as partes não são obrigatórias, embora pelo menos uma seja necessária. Não pode conter nenhum dos caracteres `<flags>`. O `h,help`, `dry-run` e `f` são exemplos de `<opt-spec>` corretos.

`<flags>`::
	`<flags>` são do `*`, `=`, `?` ou `!`.
	* Utilize `=` caso a opção receba um argumento.

	* Utilize `?` para dar sentido que a opção aceita um argumento opcional. Você provavelmente quer utilzar o modo `--stuck-long` para poder analisar de forma inequívoca o argumento opcional.

	* Utilize `*` para indicar que esta opção não deve ser listada no uso gerado para a opção `-h`. É exibido para `--help-all` conforme documentado em linkgit:gitcli[7].

	* Utilize `!` para não fazer com que a opção longa que foi negada esteja disponível.

`<arg-hint>`::
	Quando o `<arg-hint>` é especificado, é utilizado como um nome do argumento na saída da ajuda para as opções que recebem argumentos. O `<arg-hint>` é encerrado pelo primeiro espaço em branco. É comum usar um travessão para separar palavras numa dica de argumento com várias palavras.

O restante da linha, depois dos espaços removidos, é usado como ajuda associada à opção.

As linhas em branco são ignoradas e as linhas que não coincidam com esta especificação são utilizadas como cabeçalhos dos grupos das opções (inicie a linha com um espaço para criar essas linhas de propósito).

Exemplo
~~~~~~~

------------
OPTS_SPEC="\
algum-comando [<opções>] <args>...

algum-comando faz 'foo' e 'bar'!
--
h,help! Mostra a ajuda

foo alguma opção bacana `--foo bar=` alguma opção bacana `--bar` com um argumento `baz=arg` outra opção bacana `--baz` com um argumento mencionado `qux?path qux` pode receber um argumento de caminho, mas tem significado por si só

  Um cabeçalho do grupo de opções
C?        opção 'C' com um argumento opcional"

eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
------------


Texto de uso
~~~~~~~~~~~~

Quando `"$@"` is `-h` ou `--help` no exemplo acima, o seguinte texto de utilização será exibido:

------------
utilização: algum-comando [<opções>] <args>...

    algum-comando faz 'foo' e 'bar'!

    -h, --help            exibe a ajuda
    --[no-]foo                 alguma opção bacana --foo
    --[no-]bar ...        alguma opção legal --bar com um argumento
    --[no-]baz <arg>      outra opção legal --baz com um determinado argumento
    --[no-]qux[=<caminho>]   o qux pode utilizar um argumento para o caminho mas significa ele mesmo

Um cabeçalho do grupo de opções
    -C[...]               opção C com um argumento opcional
------------

SQ-QUOTE
--------

No modo `--sq-quote`, o comando 'git rev-parse' ecoa na saída padrão uma única linha adequada para `sh (1)` `eval`. Esta linha é feita normalizando os argumentos após a opção `--sq-quote`. Nada mais é feito além de citar os argumentos.

Caso queira que o comando de entrada ainda seja interpretada como de costume pelo comando `git rev-parse` antes da saída ser citada pela shell, consulte a opção `--sq`.

Exemplo
~~~~~~~

------------
$ cat >your-git-script.sh <<\EOF
#!/bin/sh
args=$(git rev-parse --sq-quote "$@")   # cita os argumentos utilizados pelo usuário
command="git frotz -n24 $args"          # e utilize-o dentro de uma
					# linha de comando artesanal
eval "$command"
EOF

$ sh your-git-script.sh "a b'c"
------------

EXEMPLOS
--------

* Imprima o nome do objeto do commit atual:
+
------------
$ git rev-parse --verify HEAD
------------

* Imprima o nome do objeto do commit a partir da revisão na variável shell '$REV':
+
------------
$ git rev-parse --verify --end-of-options $REV^{commit}
------------
+
Isso causará um erro caso '$REV' esteja vazio ou não seja uma revisão válida.

* Semelhante ao acima:
+
------------
$ git rev-parse --default master --verify --end-of-options $REV
------------
+
porém caso '$REV' esteja vazia, o nome do objeto do commit vindo do "master" será impresso.

GIT
---
Parte do conjunto linkgit:git[1]
