git-var(1)
==========

NOME
----
git-var - Exibe a variável lógica do Git


RESUMO
------
[synopsis]
git var (-l | <variable>)

DESCRIÇÃO
---------
Exibe uma variável lógica do Git. Encerra com código 1 caso a variável esteja vazia.

OPÇÕES
------
`-l`::
	Mostre as variáveis lógicas. Além disso, todas as variáveis do arquivo de configuração do Git '.git/config' também sejam listadas. (No entanto, as variáveis de configuração que listam a funcionalidade, estão obsoletas em favor do `git config -l`.)

EXEMPLOS
--------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


VARIÁVEIS
---------
`GIT_AUTHOR_IDENT`::
    O autor de um pedaço de código.

`GIT_COMMITTER_IDENT`::
    A pessoa que inseriu um código no Git.

`GIT_EDITOR`::
    Text editor for use by Git commands. The value is meant to be interpreted by the shell when it is used. Examples: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. The order of preference is `$GIT_EDITOR`, then `core.editor` configuration value, then `$VISUAL`, then `$EDITOR`, and then the default chosen at compile time, which is usually 'vi'.
ifdef::git-default-editor[]
    A construção que você está utilizando escolheu '{git-default-editor}' como o predefinido.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Text editor used to edit the 'todo' file while running `git rebase -i`. Like `GIT_EDITOR`, the value is meant to be interpreted by the shell when it is used. The order of preference is `$GIT_SEQUENCE_EDITOR`, then `sequence.editor` configuration value, and then the value of `git var GIT_EDITOR`.

`GIT_PAGER`::
    Text viewer for use by Git commands (e.g., 'less'). The value is meant to be interpreted by the shell. The order of preference is `$GIT_PAGER`, then the value of `core.pager` configuration, then `$PAGER`, and then the default chosen at compile time (usually `less`).
ifdef::git-default-pager[]
    A construção que você está usando escolheu '{git-default-pager}' como a sua predefinição.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    O nome do primeiro ramo criado nos repositórios que foram recentemente inicializados.

`GIT_SHELL_PATH`::
    O caminho do binário que fornece o shell POSIX para comandos que usam o shell.

`GIT_ATTR_SYSTEM`::
    O caminho para o arquivo do sistema linkgit:gitattributes[5], caso um esteja ativado.

`GIT_ATTR_GLOBAL`::
    O caminho para o arquivo global (por usuário) linkgit:gitattributes[5].

`GIT_CONFIG_SYSTEM`::
    O caminho para o arquivo de configuração do sistema, caso um esteja ativado.

`GIT_CONFIG_GLOBAL`::
    O caminho para os arquivos de configuração globais (por usuário), se houver.

A maioria dos valores de caminho contém apenas um valor. No entanto, alguns podem conter vários valores, que são separados por novas linhas, e são listados na ordem da prioridade mais alta para a mais baixa. Os invocadores devem estar preparados para que qualquer valor de caminho desse tipo contenha vários itens.

Observe que os caminhos são impressos mesmo que não existam, mas não se estiverem desativados por outras variáveis de ambiente.

VEJA TAMBÉM
-----------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
Parte do conjunto linkgit:git[1]
