// Please don't remove this comment as asciidoc behaves badly when
// the first non-empty line is ifdef/ifndef. The symptom is that
// without this comment the <git-diff-core> attribute conditionally
// defined below ends up being defined unconditionally.
// Last checked with asciidoc 7.0.2.

ifndef::git-format-patch[]
ifndef::git-diff[]
ifndef::git-log[]
:git-diff-core: 1
endif::git-log[]
endif::git-diff[]
endif::git-format-patch[]

ifdef::git-format-patch[]
-p::
--no-stat::
	General parches planos sin estadísticas de diff.
endif::git-format-patch[]

ifndef::git-format-patch[]
`-p`::
`-u`::
`--patch`::
	Genera parche (ver <<generate_patch_text_with_p>>).
ifdef::git-diff[]
	Este es el predeterminado
endif::git-diff[]

`-s`::
`--no-patch`::
	Suprime toda la salida del mecanismo de diff. Útil para planchar la salida de comandos como `git show` que muestra predeterminadamente el parche, o para cancelar antes en la línea de comandos en un alias el efecto de opciones como `--patch`, `--stat`.

endif::git-format-patch[]

ifdef::git-log[]
-m::
	Muestra diffs para confirmaciones de fusión en el formato predeterminado. Es similar a `--diff-merges=on`, excepto `-m` no producirá salida a menos que se dé también `-p`.

-c::
	Produce salida de diff combinada para confirmaciones de fusión. Atajo para `--diff-merges=combined -p`.

--cc::
	Produce salida de diff densa combinada para confirmaciones de fusión. Atajo para `--diff-merges=dense-combined -p`.

--dd::
	Produce diff con respecto al primer padre tanto para confirmaciones normales como de fusión. Atajo para `--diff-merges=first-parent -p`.

--remerge-diff::
	Produce salida de diff de re-fusión para confirmaciones de fusión. Atajo para `--diff-merges=remerge -p`.

--no-diff-merges::
	Sinónimo de `--diff-merges=off`.

--diff-merges=<formato>::
	Especifica el formato de diff a usar para commits de fusión. El predeterminado es {diff-merges-default} a menos que se use `--first-parent`, en tal caso `first-parent` es el predeterminado.
+
Los siguientes formatos están soportados:
+
--
off, none::
	Deshabilita la salida de diff para commits de fusión. Útil para sobreescribir el valor implicado.

on, m::
	Hace que se muestre la salida de diff en el formato predeterminado para confirmaciones de fusión. Se puede cambiar el formato predeterminado usando la variable de configuración `log.diffMerges`, cuyo valor predeterminado es `separate`.

first-parent, 1::
	Mostrar diff completo con respecto a su primer padre. Es el mismo formato que produce `--patch` para confirmaciones de no-fusión.

separate::
	Muestra el diff completo con respecto a cada uno de los padres. Para cada padre por separado se generan entrada en la bitácora y diff.

combined, c::
	Muestra simultáneamente las diferencias entre todos -y cada uno de- los padres y el resultado de la fusión, en lugar de mostrar diferencias por pares entre un padre y el resultado, uno a la vez. Mas allá, lista sólo los ficheros que fueron modificados de todos los padres.

dense-combined, cc::
	Compresión posterior de salida producida por `--diff-merges=combined` al omitir fragmentos no-interesantes cuyo contenido en los padres sólo tienen dos variantes y la fusión resulta elegir una de ellas sin modificación.

remerge, r::
	Refusiona confirmaciones de fusión de dos padres para crear un objeto árbol temporal --potencialmente conteniendo ficheros con marcadores de conflicto y similares. Entonces se muestra un diff entre ese árbol temporal y la confirmación de fusión actual.
+
La salida emitida cuando se usa esta opción es sujeta a cambios, y también lo es su interacción con otras opciones (a menos que esté explícitamente documentado).
--

--combined-all-paths::
	Causa diffs combinados (usados para commits de fusión) para listar el nombre del fichero de todos los padres. Por lo tanto sólo tiene efecto cuando se usa `--diff-merges=[dense-]combined`, y es probable que sólo sea útil si se detectan cambios de nombre de fichero (ej. cuando se ha solicitado detección ya sea de renombre o de copia).
endif::git-log[]

`-U<n>`::
`--unified=<n>`::
	Genera diffs con _<n>_ líneas de contexto en lugar de las 3 usuales.
ifndef::git-format-patch[]
	Implica `--patch`.
endif::git-format-patch[]

`--output=<fichero>`::
	Salida a un fichero en específico en lugar de la salida estándar.

`--output-indicator-new=<caracter>`::
`--output-indicator-old=<caracter>`::
`--output-indicator-context=<caracter>`::
	Especifica el caracter usado para indicar líneas nuevas, antiguas o de contexto en el parche generado. Normalmente son `+`, `-` y ' ' respectivamente.

ifndef::git-format-patch[]
`--raw`::
ifndef::git-log[]
	Generar las diferencias en formato bruto.
ifdef::git-diff-core[]
	Este es el predeterminado
endif::git-diff-core[]
endif::git-log[]
ifdef::git-log[]
	Para cada commit, muestra un resumen de cambios usando el formato
	diff bruto. Ver la sección de "FORMATO DE SALIDA BRUTO" de
	linkgit:git-diff[1]. Esto es distinto de mostrar la bitácora misma
	en formato bruto, lo cual puedes conseguir con
	`--format=raw`.
endif::git-log[]
endif::git-format-patch[]

ifndef::git-format-patch[]
`--patch-with-raw`::
	Sinónimo de `-p --raw`.
endif::git-format-patch[]

ifdef::git-log[]
`-t`::
	Mostrar los objetos del árbol en el resultado de las diferencias.
endif::git-log[]

`--indent-heuristic`::
	Habilita la heurística que aumenta los límites de fragmentos de diff para hacer los parches mas fáciles de leer. Este es el predeterminado.

`--no-indent-heuristic`::
	Deshabilita la heurística de indentación.

`--minimal`::
	Ocupa tiempo extra para asegurarse que se produce el diff más pequeño posible.

`--patience`::
	Generar diferencias mediante el algoritmo "patience diff".

`--histogram`::
	Generar diferencias mediante el algoritmo "histogram diff".

`--anchored=<texto>`::
	Generar diferencias mediante el algoritmo "anchored diff".
+
Esta opción puede ser especificada más de una vez.
+
Si una línea existe tanto en fuente como en destino, existe sólo una vez, y comienza con _<texto>_, éste algoritmo intenta prevenir que aparezca en la salida como un borrado o adición. Usa internamente el algoritmo "diff paciente".

`--diff-algorithm=(patience|minimal|histogram|myers)`::
	Elige un algoritmo de diff. La variantes son las siguientes:
+
--
   `default`;;
   `myers`;;
	El algoritmo diff básico avaro. Actualmente, éste es el predeterminado.
   `minimal`;;
	Ocupa tiempo extra para asegurarse que se produce el diff más pequeño posible.
   `patience`;;
	Usa el algoritmo "diff paciente" al generar parches.
   `histogram`;;
	Este algoritmo extiende el algoritmo paciente para "soportar elementos comunes de baja ocurrencia".
--
+
Por lo tanto, si configuraste la variable `diff.algorithm` a un valor no predeterminado y quieres usar el predeterminado, entonces tienes que usar la opción `--diff-algorithm=default`.

`--stat[=<anchura>[,<anchura-nombre>[,<recuento>]]]`::
	Generate a diffstat. By default, as much space as necessary will be used for the filename part, and the rest for the graph part. Maximum width defaults to terminal width, or 80 columns if not connected to a terminal, and can be overridden by _<width>_. The width of the filename part can be limited by giving another width _<name-width>_ after a comma or by setting `diff.statNameWidth=<name-width>`. The width of the graph part can be limited by using `--stat-graph-width=<graph-width>` or by setting `diff.statGraphWidth=<graph-width>`. Using `--stat` or `--stat-graph-width` affects all commands generating a stat graph, while setting `diff.statNameWidth` or `diff.statGraphWidth` does not affect `git format-patch`. By giving a third parameter _<count>_, you can limit the output to the first _<count>_ lines, followed by `...` if there are more.
+
Estos parámetros también se puedes asignar individualmente con `--stat-width=<ancho>`, `--stat-name-width=<nombre-ancho>` y `--stat-count=<conteo>`.

`--compact-summary`::
	Da salida en el diffstat a un resumen condensado de información de encabezado extendido, como creaciones o eliminaciones de ficheros ("new" or "gone", opcionalmente `+l` si es un enlace simbólico) y cambios de modo (`+x` o `-x` para añadir o quitar el bit de ejecución respectivamente). La información se coloca entre la parte del nombre del fichero y la parte del grafo. Implica `--stat`.

`--numstat`::
	Similar a `--stat`, pero muestra el número de líneas añadidas y borradas en notación decimal y el nombre de ruta sin abreviación, para hacerlo más amigable a la máquina. Para ficheros binarios, saca dos `-` en lugar de decir `00`.

`--shortstat`::
	Da salida sólo a la última línea del formato `--stat` conteniendo el número total de ficheros modificados, así como el número de líneas añadidas y borradas.

`-X [<parámetro>,...]`::
`--dirstat[=<parámetro>,...]`::
	Da salida a la distribución de la cantidad relativa de cambios por cada sub-directorio. El comportamiento de `--dirstat` puede ser personalizado pasando una lista de parámetros separados por coma. Los predeterminados se controlan con la variable de configuración `diff.dirstat` (ver linkgit:git-config[1]). Están disponibles los parámetros siguientes:
+
--
`changes`;;
	Calcula los números de dirstat contando las líneas que han sido eliminadas del origen, o agregadas en el destino. Esto ignora la cantidad de movimientos de código puro dentro del fichero. En otras palabras, el reacomodo de líneas en un fichero no cuenta tanto como otros cambios. Este es el comportamiento predeterminado cuando no se dan parámetros.
`lines`;;
	Calcula los números de dirstat haciendo el análisis de diferencias regular basado en líneas, y sumando los conteos de líneas quitadas/agregadas. (Para ficheros binarios, cuenta en cambio pedazos de 64 bytes, ya que los ficheros binarios no tienen el concepto natural de líneas). Este es un funcionamiento de `--dirstat` mas costoso que `changes`, pero el re-acomodo de líneas dentro de un fichero cuenta tanto como otros cambios. La salida resultante es consistente con lo que obtienes de las otras opciones `--*stat`.
`files`;;
	Calcula los números de dirstat contando el número de ficheros modificados. Cada fichero modificado cuenta igualmente en el análisis de dirstat. Este es el funcionamiento `--dirstat` computacionalmente más barato, ya que no tiene que mirar el contenido del fichero en absoluto.
`cumulative`;;
	Cuenta cambios en un directorio hijo también para el directorio padre. Nota que cuando se usa `cumulative`, la suma de los porcentajes reportados puede exceder 100%. El comportamiento predeterminado (no-acumulativo) se puede especificar con el parámetro `noncumulative`.
_<límite>_;;
	Un parámetro entero especifica un porcentaje de corte (predeterminado a 3%). Directorios que contribuyan menos que éste porcentaje de cambios no se muestran en la salida.
--
+
Ejemplo: El siguiente contará ficheros modificados, ignorando directorios con menos del 10% de la cantidad total de ficheros modificados, y acumulando conteos en directorios hijo en los directorios padre: `--dirstat=files,10,cumulative`.

`--cumulative`::
	Sinónimo de `--dirstat=cumulative`.

`--dirstat-by-file[=<parámetro>,...]`::
	Sinónimo de `--dirstat=files,<parámetro>,...`.

`--summary`::
	Muestra un resumen condensado de información de encabezado extendido como creaciones, renombrados y cambios de modo.

ifndef::git-format-patch[]
`--patch-with-stat`::
	Sinónimo de `-p --stat`.
endif::git-format-patch[]

ifndef::git-format-patch[]

`-z`::
ifdef::git-log[]
	Separa las confirmaciones con __NUL__s en lugar de saltos de línea.
+
Además, cuando se da `--raw` o `--numstat`, no manipula los nombres de ruta y usa __NUL__s como salida de terminadores de campo.
endif::git-log[]
ifndef::git-log[]
	Cuando se da `--raw`, `--numstat`, `--name-only` o `--name-status`,
	no manipula los nombres de ruta y usa NULs como salida de terminadores de campo.
endif::git-log[]
+
Sin esta opción, los nombres de ruta con caracteres "inusuales" son entrecomillados como se explica para la variable de configuración `core.quotePath` (ver linkgit:git-config[1]).

`--name-only`::
	Muestra sólo el nombre de cada fichero modificado en el árbol post-imagen. Los nombres de ficheros suelen codificarse con UTF-8. Para mas información ver la discusión sobre codificación en la página del manual de linkgit:git-log[1].

`--name-status`::
	Muestra sólo nombre(s) y estatus de cada fichero modificado. Ver la descripción de la opción `--diff-filter` donde se explica el significado de las letras de estatus. Así como `--name-only` los nombres de fichero se suelen codificar en UTF-8.

`--submodule[=<formato>]`::
	Especifica cómo se muestran las diferencias en submódulos. Cuando se especifica `--submodule=short` se usa el formato `short`. Este formato sólo muestra nombres de los commits al principio y al fin del rango. Cuando se especifica `--submodule` o `--submodule=log` se usa el formato `log`. Este formato lista los commits en el rango como lo hace linkgit:git-submodule[1] `summary`. Cuando se especifica `--submodule=diff` se usa el formato `diff`. Este formato muestra un diff en-linea de los cambios en el contenido del submódulo entre el rango del commit. Se predetermina a `diff.submodule` o al formato `short` si la opción de configuración no es asignada.

`--color[=<cuando>]`::
	Muestra diff coloreado. `--color` (ej. sin `=<cuando>`) es lo mismo que `--color=always`. _<cuando>_ puede ser uno de `always`, `never` o `auto`.
ifdef::git-diff[]
	Puede se modificado por las configuraciones `color.ui` y 
	`color.diff`.
endif::git-diff[]

`--no-color`::
	Desactiva diff coloreado.
ifdef::git-diff[]
	Puede ser usado para sobre-escribir configuraciones.
endif::git-diff[]
	Es lo mismo que `--color=never`.

`--color-moved[=<modo>]`::
	Los renglones de código trasladados se señalan con un color distinto.
ifdef::git-diff[]
	Puede ser modificado por la configuración `diff.colorMoved`.
endif::git-diff[]
	El _<modo>_ se predetermina a `no` si no se da la opción
	y a `zebra` si se da la opción sin modo.
	El modo debe ser uno de:
+
--
`no`::
	Lineas movidas no son resaltadas.
`default`::
	Es un sinónimo para `zebra`. Esto puede cambiar a un modo mas sensible en el futuro.
`plain`::
	Cualquier linea añadida en una ubicación y que haya sido removida en otra ubicación será coloreada con `color.diff.newMoved`. Similarmente `color.diff.oldMoved` será usado para líneas removidas que fueron añadidas en algún otro lado en el diff. Este modo toma cualquier línea movida, pero no es muy útil en un revisión para determinar si un bloque de código fue movido sin permutación.
`blocks`::
	Bloques de texto movido de al menos 20 caracteres alfanuméricos se detectan codiciosamente. Los bloques detectados se pintan usando cualquier color `color.diff.(old|new)Moved`. No se pueden distinguir bloques adyacentes.
`zebra`::
	Los bloques de texto movido se detectan como en el modo `blocks`. Los bloques se colorean con cualquier color `color.diff.(old|new)Moved` o `color.diff.(old|new)MovedAlternative`. El cambio entre los dos colores indica que fue detectado un bloque nuevo.
`dimmed-zebra`::
	Similar a `zebra`, pero se hace un oscurecimiento adicional de partes no-interesantes de código movido. Las líneas limitantes de dos bloques adyacentes se consideran interesantes, el resto es no-interesante. `dimmed_zebra` es un sinónimo obsoleto.
--

`--no-color-moved`::
	Apaga la detección de movimiento. Puede ser usada para sobre-escribir configuraciones. Es lo mismo que `--color-moved=no`.

`--color-moved-ws=<modo>,...`::
	Este configura como el espacio en blanco es ignorado cuando se hace la detección de movimiento para `--color-moved`.
ifdef::git-diff[]
	Puede ser asignado por la configuración `diff.colorMovedWS`.
endif::git-diff[]
	Estos modos pueden se dados como una lista separada por comas:
+
--
`no`::
	No ignora espacio en blanco cuando se hace detección de movimiento.
`ignore-space-at-eol`::
	Ignorar cambios de espacios en blanco al finalizar renglón.
`ignore-space-change`::
	Ignora cambios en la cantidad de espacios en blanco. Esto ignora espacio en blanco al final de la línea, y considera todas las otras secuencias de uno o mas caracteres de espacio en blanco como equivalentes.
`ignore-all-space`::
	Ignora espacios en blanco al comparar líneas. Esto ignora diferencias incluso si una línea tiene espacio en blanco donde la otra no tiene alguno.
`allow-indentation-change`::
	Inicialmente ignora cualquier espacio en blanco en la detección de movimiento, y luego agrupa los bloques de código movido sólo en un bloque si el cambio en espacios en blanco es el mismo por línea. Esto es incompatible con los otros modos.
--

`--no-color-moved-ws`::
	No ignorar espacio en blanco durante detección de movimiento. Esto puede usarse para anular ajustes de configuración. Es lo mismo que `--color-moved-ws=no`.

`--word-diff[=<modo>]`::
	De manera predeterminada, las palabras se delimitan por espacios; consulte `--word-diff-regex` más abajo. El _<modo>_ predeterminado es `plain`, y debe ser uno de:
+
--
`color`::
	Resaltar palabras modificadas usando sólo colores. Implica `--color`.
`plain`::
	Mostrar palabras como ++[-removed-]++ y ++{+added+}++. No intenta escapar delimitadores si aparecen en la entrada, entonces la salida puede ser ambigua.
`porcelain`::
	Usa un formato especial basado en líneas intencionado para consumo de scripts. Las acciones añadir/eliminar/sin-modificar se imprimen en el formato usual diff unificado, comenzando con un caracter `+`/`-`/` ` al principio de la línea y extendiendo al final de la línea. Nuevas líneas se representan con una tilde `~` en una línea misma.
`none`::
	Desactiva de nuevo las diferencias entre palabras.
--
+
Nota que a pesar del nombre del primer modo, el color -si esta habilitado- se usa para resaltar las partes cambiadas en todos los modos.

`--word-diff-regex=<expresión-regular>`::
	Usa _<expresión-regular>_ para decidir qué es una palabra, en lugar de considerar no-espacios en blanco seguidos como una palabra. También implica `--word-diff` a menos que ya haya sido habilitado.
+
Cada coincidencia sin traslape de _<expresión-regular>_ se considera una palabra. Lo que esté entre esas coincidencias se considera espacio en blanco y es ignorado(!) para propósito de encontrar diferencias. Querrás agregar `|[^[:space:]]` a tu expresión regular para asegurarte que coincida todos lo caracteres que no son espacio en blanco. Una coincidencia que contenga salto de línea es silenciosamente truncada(!) en el salto de línea.
+
Por ejemplo, `--word-diff-regex=.` tratará cada carácter como si fuese una palabra y, por tanto, mostrará las diferencias carácter por carácter.
+
La expresión regular también puede asignarse por un controlador de diff u opción de configuración, ver linkgit:gitattributes[5] o linkgit:git-config[1]. Dándolo explícitamente anula cualquier controlador de diff u opción de configuración. Los controladores de diff anulan ajustes de configuración.

`--color-words[=<expresión-regular>]`::
	Equivalente a `--word-diff=color` mas (si se especificó una expresión regular) `--word-diff-regex=<expresión-regular>`.
endif::git-format-patch[]

`--no-renames`::
	Apaga la detección de renombramiento, incluso cuando el fichero de configuración predetermina hacerlo.

`--[no-]rename-empty`::
	Si usar blobs vacíos como fuente de renombramiento.

ifndef::git-format-patch[]
`--check`::
	Advierte si los cambios introducidos conflictúan marcadores o errores de espacio en blanco. Lo que es considerado error de espacio en blanco es controlado por la configuración `core.whitespace`. Predeterminadamente, espacios en blanco al final (incluyendo líneas que consisten únicamente en espacios en blanco) y un caracter espacio que es inmediatamente seguido por una caracter tabulador dentro del indentado inicial de una línea, son considerados errores de espacio en blanco. Sale con un estatus no-cero si se encuentran problemas. No compatible con `--exit-code`.

`--ws-error-highlight=<tipo>`::
	Resalta errores de espacio en blanco en las líneas `context`, `old ` o `new` del diff. Valores múltiples se separan con coma, `none` restablece valores previos, `default` restablece la lista a `new` y `all` es una forma corta de `old,new,context`. Cuando no se da esta opción y no se asigna la variable de configuración `diff.wsErrorHighlight`, sólo se resaltan errores de espacio en blanco en líneas `new`. Los errores de espacio en blanco se colorean con `color.diff.whitespace`.

endif::git-format-patch[]

`--full-index`::
	En lugar del primer puñado de caracteres, muestra los nombres completos pre- y post-imágen de objeto blob en la línea del índice cuando se genera la salida del formato de parche.

`--binary`::
	Además de `--full-index`, saca un diff binario que puede ser aplicado con `git-apply`.
ifndef::git-format-patch[]
	Implica `--patch`.
endif::git-format-patch[]

`--abbrev[=<n>]`::
	En lugar de mostrar el nombre de objeto completo en 40 bytes hexadecimal en la salida del formato diff-raw y en las líneas de encabezado de diff-tree, muestra el prefijo más corto que es de por lo menos _<n>_ dígitos hexadecimales de largo que refiere únicamente al objeto. En el formato diff-patch, `--full-index` toma mayor precedencia, ej. si se especifica `--full-index`, se mostrarán los nombres completos de blob sin importar `--abbrev`. Un número no-predeterminado de dígitos puede especificarse con `--abbrev=<n>`.

`-B[<n>][/<m>]`::
`--break-rewrites[=[<n>][/<m>]]`::
	Rompe cambios de reescritura completa en pares de borrado y creado. Esto sirve para dos propósitos:
+
Afecta la manera en que un cambio suma al total de reescrituras de un fichero, no como una serie de borrados e inserciones mezcladas con unas cuantas líneas que resultan coincidir textualmente con el contexto, sino como un sólo borrado de todo lo anterior seguido por una sola inserción de todo lo nuevo, y el número <m> controla éste aspecto de la opción `-B` (predeterminado a 60%). `-B/70%` especifica que menos del 30% del original debe permanecer en el resultado para que Git lo considere una reescritura total (ej. de lo contrario el parche resultante sería una serie de borrados e inserciones mezclada con líneas de contexto).
+
Cuando se usa con `-M`, un fichero totalmente reescrito se considera la fuente de un cambio de nombre (usualmente `-M` sólo considera un fichero que desaparece como fuente de un cambio de nombre), y el número <n> controla éste aspecto de la opción `-B` (predeterminado a 50%). `-B20%` especifica que un cambio con adición y eliminación comparado con el 20% o mas del tamaño de fichero es elegible para ser seleccionado como una posible fuente de cambio de nombre a otro fichero.

`-M[<n>]`::
`--find-renames[=<n>]`::
ifndef::git-log[]
	Detectar cambios de nombre.
endif::git-log[]
ifdef::git-log[]
	Si se generan diffs, detecta y reporta cambios de nombre por cada commit
	Para seguir ficheros a través de los cambios de nombre en el historial, ver
	`--follow`.
endif::git-log[]
	Si se especifica _<n>_, es un límite sobre el índice de semejanza
	(ej. la cantidad de adiciones/eliminaciones comparadas con
	el tamaño del fichero). Por ejemplo, `-M90%` significa que Git
	debe considerar un par eliminación/adición como un renombramiento
	si mas del 90% del fichero no ha cambiado. Sin el signo `%`, el número
	se leerá como una fraccion, con un punto decimal antes de él. Ej., `-M5`
	será 0.5, que por lo tanto es lo mismo que `-M50%`. Similarmente, `-M05` es
	lo mismo que `-M5%`. Para limitar la detección a renombramientos exactos,
	use `-M100%`. El índice de semejanza predeterminado es 50%.

`-C[<n>]`::
`--find-copies[=<n>]`::
	Detecta tanto copias como renombramientos. Ver también `--find-copies-harder`. Si se especifica _<n>_, tiene el mismo significado que `-M<n>`.

`--find-copies-harder`::
	Por razones de desempeño, predeterminadamente, la opción `-C` busca copias sólo si el fichero original de la copia fue modificado en el mismo conjunto de cambios. Esta bandera hace que el comando inspeccione ficheros sin modificar como candidatos a fuente de copia. Esta es una operación muy costosa para proyectos grandes, así que usarla con precaución. Dar más de una opción `-C` tiene el mismo efecto.

`-D`::
`--irreversible-delete`::
	Omit the preimage for deletes, i.e. print only the header but not the diff between the preimage and `/dev/null`. The resulting patch is not meant to be applied with `patch` or `git apply`; this is solely for people who want to just concentrate on reviewing the text after the change. In addition, the output obviously lacks enough information to apply such a patch in reverse, even manually, hence the name of the option.
+
Cuando se usa junto con `-B`, omite también la preimagen en la parte de borrado de un par borrar/crear.

`-l<número>`::
	Las opciones `-M`y `-C` involucran algunos pasos preliminares que pueden detectar subconjuntos de renombramientos/copias económicamente, seguido de una porción exhaustiva de iteraciones que compara todos los destinos remanentes sin pareja con todos los orígenes relevantes. (Para renombramientos, sólo los orígenes remanentes sin pareja son relevantes; para copias, todos los orígenes son relevantes). Para N orígenes y destinos, esta verificación exhaustiva es O(N^2). Esta opción previene la ejecución de la porción exhaustiva de detección de renombramiento/copia si el número de ficheros orígenes/destino involucrado excede el número especificado. Es predeterminado a `diff.renameLimit`. Nota que un valor de 0 es tratado como ilimitado.

ifndef::git-format-patch[]
`--diff-filter=[(A|C|D|M|R|T|U|X|B)...[*]]`::
	Selecciona sólo los ficheros que son Agregados(`A`), Copiados (`C`), eliminados (`D`), Modificados (`M`), Renombrados (`R`), tienen su tipo (ej. fichero regular, enlace simbólico, submódulo, ...) cambiado (`T`), están sin fusionar (`U`), son desconocidos (`X`), o tienen su pareja rota (`B`). Se puede usar cualquier combinación de los caracteres filtro (incluyendo ninguno). Cuando se agrega `*`(todo-o-nada) a la combinación, todas las rutas son seleccionadas si hay algún fichero que cumpla otro criterio en la comparación; si no hay fichero que cumpla otro criterio, nada es seleccionado.
+
También, estas letras en mayúsculas pueden ser en minúscula para excluir. Ej. `--diff-filter=ad` excluye rutas añadidas y eliminadas.
+
Nota que no todos los diffs pueden presentar todos los tipos. Por lo tanto, entradas copiadas y renombradas no pueden aparecer si la detección para esos tipos está deshabilitada.

`-S<cadena>`::
	Busca diferencias que cambian el número de ocurrencias de la _<cadena>_ especificada (ej. adición/eliminación) en un fichero. Destinada para el uso de creadores de scripts.
+
Es útil cuando buscas un bloque exacto de código (como un struct), y quieres conocer el historial de ese bloque desde la primera vez que entró en existencia: use la característica iterativamente para alimentar el bloque de interés de vuelta a la preimagen `-S`, y seguir hasta que obtengas la primera versión del bloque.
+
También se buscan ficheros binarios.

`-G<expresión-regular>`::
	Busca diferencias cuyo texto de parche contenga líneas agregadas/quitadas que coincidan _<expresión-regular>_.
+
Para ilustrar la diferencia entre `-S<expresión-regular>` `--pickaxe-regex` y `-G<expresión-regular>`, considere una confirmación con el diff siguiente en el mismo fichero:
+
----
+    return frotz(nitfol, two->ptr, 1, 0);
...
-    hit = frotz(nitfol, mf2.ptr, 1, 0);
----
+
Mientras `git log -G"frotz\(nitfol"` mostrará éste commit, `git log -S"frotz\(nitfol" --pickaxe-regex` no lo hará (porque el número de ocurrencias de esa cadena no cambió).
+
A menos que se proporcione `--text`, parches de ficheros binarios sin un filtro de conversión de texto serán ignorados.
+
Ver la entrada 'pickaxe' en linkgit:gitdiffcore[7] para mas información.

`--find-object=<id-de-objeto>`::
	Busca diferencias que cambien el número de ocurrencias del objeto especificado. Similar a `-S`, solo que el argumento es diferente en que no busca una cadena específica, sino un identificador de objeto específico.
+
El objeto puede ser un blob o un commit de submódulo. Implica la opción `-t` en `git-log` para también buscar árboles.

`--pickaxe-all`::
	Cuando `-S` o `-G` encuentra un cambio, muestra todos los cambios en ese conjunto de cambios, no sólo los ficheros que contienen el cambio en _<cadena>_.

`--pickaxe-regex`::
	Trata la _<cadena>_ dada en `-S` como una expresión regular extendida de POSIX para coincidir.

endif::git-format-patch[]

`-O<fichero-de-ordenamiento>`::
	Controla el orden en el que aparecen los ficheros en la salida. Esto anula la variable de configuración `diff.orderFile` (ver linkgit:git-config[1]). Para cancelar `diff.orderFile`, use `-O/dev/null`.
+
El orden de salida es determinado por el orden de patrones glob en _<fichero-de-ordenamiento>_. Todos los ficheros con nombres de ruta que coincidan el primer patrón salen primero, todos los ficheros con nombres de ruta que coincidan el segundo patrón (pero no el primero) salen después, y así sucesivamente. Todos los ficheros con nombres de ruta que no coincidan con algún patrón salen al último, como si hubiera implícito un patrón coincide-todo al final del fichero. Si varios nombres de ruta tienen el mismo rango (coinciden en el mismo patrón pero no en patrones anteriores), su orden de salida respecto al otro es el orden normal.
+
_<fichero-de-ordenamiento>_ es analizado como sigue:
+
--
 - Líneas en blanco son ignoradas, que se pueden usar como separadores por legibilidad.

 - Líneas que comiencen con hash ("`#`") son ignoradas, que se pueden usar para comentarios. Agregue una diagonal invertida ("`\`") al inicio del patrón si comienza con un hash.

 - Cada línea contiene un solo patrón.
--
+
Los patrones tienen la misma sintaxis y semántica que los patrones usados para `fnmatch`(3) sin la bandera `FNM_PATHNAME`, excepto que un nombre de ruta también coincida con un patrón si se le quita cualquier cantidad de componentes de ruta al final. Por ejemplo, el patrón "`foo*bar`" coincide "`fooasdbar`" y "`foo/bar/baz/asdf`" pero no "`foobarx`".

`--skip-to=<fichero>`::
`--rotate-to=<fichero>`::
	Descarta de la salida los ficheros que están antes que el _<fichero>_ nombrado (ej. 'skipt to'), o los mueve al final de la salida (ej. 'rotate to'). Estas opciones se inventaron primordialmente para uso del comando `git difftool`, y pueden no ser útiles de otra forma.

ifndef::git-format-patch[]
`-R`::
	Intercambia dos entradas; esto es, muestra diferencias entre el índice o fichero en disco y el contenido del árbol.
endif::git-format-patch[]

`--relative[=<ruta>]`::
`--no-relative`::
	Cuando se ejecuta desde un subdirectorio del proyecto, se puede decir que se excluyan cambios fuera del directorio y mostrar los nombres de ruta relativos a él con ésta opción. Cuando no estas en un subdirectorio (ej. en un repositorio básico), puedes decir a cuál subdirectorio hacer relativa la salida dando una _<ruta>_ como argumento. Se puede usar `--no-relative` para contrarrestar ambas opciones de configuración `diff.relative` y `--relative` previo.

`-a`::
`--text`::
	Tratar todos los ficheros como si fueran de texto.

`--ignore-cr-at-eol`::
	Ignora retornos de carro al final de la línea al comparar.

`--ignore-space-at-eol`::
	Ignorar cambios de espacios en blanco al finalizar renglón.

`-b`::
`--ignore-space-change`::
	Ignora cambios en la cantidad de espacios en blanco. Esto ignora espacio en blanco al final de la línea, y considera todas las otras secuencias de uno o mas caracteres de espacio en blanco como equivalentes.

`-w`::
`--ignore-all-space`::
	Ignora espacios en blanco al comparar líneas. Esto ignora diferencias incluso si una línea tiene espacio en blanco donde la otra no tiene alguno.

`--ignore-blank-lines`::
	Ignorar cambios cuyos renglones están todos vacíos.


`-l<expresión-regular>`::
`--ignore-matching-lines=<expresión-regular>`::
	Ignora cambios donde todas las líneas coincidan _<expresión-regular>_. Esta opción puede especificarse mas de una vez.

`--inter-hunk-context=<número>`::
	Muestra el contexto entre pedazos de diferencia, hasta el _<número>_ especificado de líneas, a modo de fusionar pedazos cercanos. Predeterminado a `diff.interHunkContext`o 0 si no se configura la opción.

`-W`::
`--function-context`::
	Mostrar la función completa como líneas de contexto para cada cambio. Los nombres de función se determinan de la misma manera que `git diff` maneja encabezados de pedazos de parche (ver "Definiendo un encabezado de pedazo personalizado" en linkgit:gitattributes[5]).

ifndef::git-format-patch[]
ifndef::git-log[]
`--exit-code`::
	Hace al programa salir con códigos similares a `diff`(1). Esto es, sale con 1 si hubo diferencias y 0 significa sin diferencias.

`--quiet`::
	Disable all output of the program. Implies `--exit-code`. Disables execution of external diff helpers whose exit code is not trusted, i.e. their respective configuration option `diff.trustExitCode` or ++diff.++__<driver>__++.trustExitCode++ or environment variable `GIT_EXTERNAL_DIFF_TRUST_EXIT_CODE` is false.
endif::git-log[]
endif::git-format-patch[]

`--ext-diff`::
	Permite la ejecución de un diff auxiliar externo. Si configuras un controlador de diff externo con linkgit:gitattributes[5], necesitas usar esta opción con linkgit:git-log[1] y compañía.

`--no-ext-diff`::
	Rechaza controladores de diff externos.

`--textconv`::
`--no-textconv`::
	Permite (o rechaza) que se ejecuten filtros de conversión de texto externos cuando se comparan ficheros binarios. Ver linkgit:gitattributes[5] para detalles. Dado que filtros conversores de texto son típicamente unidireccionales, la diferencia resultante es adecuada para consumo humano, pero no puede ser aplicada. Por esta razón, filtros textconv se habilitan predeterminadamente sólo para linkgit:git-diff[1] and linkgit:git-log[1], pero no para linkgit:git-format-patch[1] o comandos de plomería de diff.


`--ignore-submodules[=(none|untracked|dirty|all)]`::
	Ignore changes to submodules in the diff generation. `all` is the default. Using `none` will consider the submodule modified when it either contains untracked or modified files or its `HEAD` differs from the commit recorded in the superproject and can be used to override any settings of the `ignore` option in linkgit:git-config[1] or linkgit:gitmodules[5]. When `untracked` is used submodules are not considered dirty when they only contain untracked content (but they are still scanned for modified content). Using `dirty` ignores all changes to the work tree of submodules, only changes to the commits stored in the superproject are shown (this was the behavior until 1.7.0). Using `all` hides all changes to submodules.

`--src-prefix=<prefijo>`::
	Mostrar el _<prefijo>_ de origen indicado en lugar de "a/".

`--dst-prefix=<prefijo>`::
	Mostrar el _<prefijo>_ de destino indicado en lugar de "b/".

`--no-prefix`::
	No mostrar ningún prefijo de origen o de destino.

`--default-prefix`::
	Usa los prefijos predeterminados de origen y destino ("a/" y "b/"). Esto anula variables de configuración como `diff.noprefix`, `diff.srcPrefix`, `diff.dstPrefix` y `diff.mnemonicPrefix` (ver linkgit:git-config[1]).

`--line-prefix=<prefijo>`::
	Anteponer un _<prefijo>_ adicional a cada línea de salida.

`--ita-invisible-in-index`::
	Predeterminadamente las entradas agregadas por `git add -N` aparecen como un fichero vacío existente en `git diff` y como un fichero nuevo en `git diff --cached`. Esta opción hace que la entrada aparezca como fichero nuevo en `git diff` y como inexistente en `git diff --cached`. Esta opción puede revertirse con `--ita-visible-in-index`. Ambas opciones son experimentales y pueden ser removidas en el futuro.

Para una explicación mas detallada sobre estas opciones comunes ver también linkgit:gitdiffcore[7].
