git-mv(1)
=========

NOMBRE
------
git-mv - Mueve o renombra un fichero, un directorio o un enlace simbólico


SINOPSIS
--------

[synopsis]
git mv [-v] [-f] [-n] [-k] <orígen> <destino>
git mv [-v] [-f] [-n] [-k] <orígen>... <directorio-destino>

DESCRIPCIÓN
-----------
Mueve o renombra un fichero, directorio o enlace simbólico.

En la primer forma, renombra _<orígen>_ -el cual debe existir y ser ya sea un fichero, un enlace simbólico o un directorio- a _<destino>_. En la segunda forma, _<directorio-destino>_ tiene que ser un directorio existente; los orígenes dados se moverán a este directorio.

El índice se actualiza después de terminar exitosamente, pero el cambio aún debe ser confirmado.

OPCIONES
--------
`-f`::
`--force`::
	Forza cambio de nombre o movimiento de un fichero incluso si el <destino> existe.
`-k`::
	Salta acciones de movimiento o cambio de nombre que pudieran conducir a una condición de error. Un error ocurre cuando el orígen no existe o no es controlado por Git, o cuando puede sobre escribir un fichero existente a menos que se de `-f`.
`-n`::
`--dry-run`::
	Hace nada; solo muestra lo que podría suceder

`-v`::
`--verbose`::
	Reporta los nombres de ficheros como son movidos.

SUBMÓDULOS
----------
Al mover un submódulo usando un fichero git (lo que significa que fueron clonados con una versión de Git 1.7.8 o superior) se actualizará el fichero git y la configuración `core.worktree` para hacer que el submódulo funcione en la nueva ubicación. También intentará actualizar la configuración `submodule.<nombre>.path` en el fichero linkgit:gitmodules[5] y presentarlo (a menos que se use `-n`).

DEFECTOS
--------
Cada vez que una actualización de superproyecto mueve un submódulo poblado (ej. cuando se alterna entre confirmaciones antes y después del movimiento) permanecerá un checkout de submódulo viciado en la ubicación anterior y aparecerá un directorio vacío en la ubicación nueva. Para poblar nuevamente el submódulo en la ubicación nueva el usuario tendrá que ejecutar después "git submodule update". Eliminar el directorio anterior es seguro solo cuando usa un fichero git, ya que de lo contrario el historial del submódulo también se eliminará. Ambos pasos serán obsoletos cuando se haya implementado actualización recursiva de submódulos.

GIT
---
Parte de la suite de linkgit:git[1]
