`push.autoSetupRemote`::
	Если установлено в `true`, подразумевать `--set-upstream` при отправке по умолчанию, когда для текущей ветки не существует вышестоящего (upstream) отслеживания; этот параметр действует с опциями `push.default` `simple`, `upstream` и `current`. Это полезно, если по умолчанию вы хотите, чтобы новые ветки отправлялись во внешний репозиторий по умолчанию (как поведение `push.default=current`) и вы также хотите, чтобы было установлено вышестоящее отслеживание. Наиболее вероятные рабочие процессы, которые выиграют от этого параметра, — это `simple` централизованные рабочие процессы, где ожидается, что все ветки будут иметь одинаковые имена во внешнем репозитории.

`push.default`::
	Определяет действие, которое должно выполняться `git push`, если не указан спецификатор ссылки (будь то из командной строки, конфигурации или другого места). Разные значения хорошо подходят для конкретных рабочих процессов; например, в чисто централизованном рабочем процессе (т.е. источник получения равен цели отправки), `upstream`, вероятно, то, что вам нужно. Возможные значения:
+
--
`nothing`;;
не отправлять ничего (завершиться с ошибкой), если не указан спецификатор ссылки. Это в первую очередь предназначено для людей, которые хотят избежать ошибок, всегда действуя явно.

`current`;;
отправить текущую ветку для обновления ветки с тем же именем на принимающей стороне. Работает как в централизованных, так и в нецентрализованных рабочих процессах.

`upstream`;;
отправить текущую ветку обратно в ветку, чьи изменения обычно интегрируются в текущую ветку (которая называется `@{upstream}`). Этот режим имеет смысл только в том случае, если вы отправляете в тот же репозиторий, из которого обычно извлекаете (pull) (т.е. централизованный рабочий процесс).

`tracking`;;
это устаревший синоним для `upstream`.

`simple`;;
отправить текущую ветку с тем же именем во внешний репозиторий.
+
Если вы работаете по централизованному рабочему процессу (отправляете в тот же репозиторий, из которого извлекаете, обычно это `origin`), то вам нужно настроить вышестоящую ветку с тем же именем.
+
Этот режим используется по умолчанию, начиная с Git 2.0, и является самым безопасным вариантом, подходящим для новичков.

`matching`;;
отправить все ветки, имеющие одинаковые имена на обоих концах. Это заставляет репозиторий, в который вы отправляете, запомнить набор веток, которые будут отправлены (например, если вы всегда отправляете туда `maint` и `master` и никакие другие ветки, репозиторий, в который вы отправляете, будет иметь эти две ветки, и ваши локальные `maint` и `master` будут туда отправлены).
+
Чтобы эффективно использовать этот режим, вы должны убедиться, что _все_ ветки, которые вы собираетесь отправить, готовы к отправке перед запуском `git push`, поскольку весь смысл этого режима в том, чтобы позволить вам отправить все ветки за один раз. Если вы обычно заканчиваете работу только над одной веткой и отправляете результат, в то время как другие ветки не закончены, этот режим не для вас. Кроме того, этот режим не подходит для отправки в общий центральный репозиторий, так как другие люди могут добавлять там новые ветки или обновлять верхушки существующих веток вне вашего контроля.
+
Раньше это было значение по умолчанию, но не начиная с Git 2.0 (`simple` — новое значение по умолчанию).

--

`push.followTags`::
	Если установлено в true, включить опцию `--follow-tags` по умолчанию. Вы можете переопределить эту конфигурацию во время отправки, указав `--no-follow-tags`.

`push.gpgSign`::
	Может быть установлен в логическое значение или в строку `if-asked`. Значение true заставляет все отправки подписываться с помощью GPG, как если бы `--signed` был передан в linkgit:git-push[1]. Строка `if-asked` заставляет отправки подписываться, если сервер это поддерживает, как если бы `--signed=if-asked` был передан в `git push`. Значение false может переопределить значение из конфигурационного файла с более низким приоритетом. Явный флаг командной строки всегда переопределяет этот параметр конфигурации.

`push.pushOption`::
	Если аргумент `--push-option=<параметр>` не задан в командной строке, `git push` ведёт себя так, как если бы каждый _<параметр>_ этой переменной был задан как `--push-option=<параметр>`.
+
Это многозначная переменная, и пустое значение может быть использовано в конфигурационном файле с более высоким приоритетом (например, `.git/config` в репозитории) для очистки значений, унаследованных из конфигурационных файлов с более низким приоритетом (например, `$HOME/.gitconfig`).
+
----

Пример:

/etc/gitconfig
  push.pushoption = a
  push.pushoption = b

~/.gitconfig
  push.pushoption = c

repo/.git/config
  push.pushoption =
  push.pushoption = b

В результате останется только b (a и c будут очищены).

----

`push.recurseSubmodules`::
	Может быть `check`, `on-demand`, `only` или `no`, с тем же поведением, что и у `push --recurse-submodules`. Если не установлено, по умолчанию используется `no`, если только не установлен `submodule.recurse` (в этом случае значение `true` означает `on-demand`).

`push.useForceIfIncludes`::
	Если установлено в `true`, это эквивалентно указанию `--force-if-includes` в качестве параметра для linkgit:git-push[1] в командной строке. Добавление `--no-force-if-includes` во время отправки переопределяет этот параметр конфигурации.

`push.negotiate`::
	Если установлено в `true`, пытаться уменьшить размер отправляемого pack-файла с помощью раундов согласования, в которых клиент и сервер пытаются найти общие коммиты. Если `false`, Git будет полагаться исключительно на объявление ссылок сервера для поиска общих коммитов.

`push.useBitmaps`::
	Если установлено в `false`, отключить использование битовых карт для `git push`, даже если `pack.useBitmaps` имеет значение `true`, не препятствуя использованию битовых карт другими операциями git. По умолчанию `true`.
