rebase.backend::
	Внутренний механизм по умолчанию для перемещения (rebase). Возможные варианты: 'apply' или 'merge'. В будущем, если внутренний механизм слияния (merge backend) получит все оставшиеся возможности внутреннего механизма наложения (apply backend), этот параметр может перестать использоваться.

rebase.stat::
	Показывать ли diffstat того, что изменилось выше по течению (upstream) с момента последнего перемещения. По умолчанию false.

rebase.autoSquash::
	Если установлено в true, включить параметр `--autosquash` команды linkgit:git-rebase[1] по умолчанию для интерактивного режима. Это можно переопределить с помощью параметра `--no-autosquash`.

rebase.autoStash::
	Если установлено в true, автоматически создаёт временную запись в тайнике (stash) перед началом операции и применяет её после завершения операции. Это означает, что вы можете выполнять перемещение на грязном рабочем каталоге. Однако используйте с осторожностью: финальное применение тайника после успешного перемещения может привести к нетривиальным конфликтам. Этот параметр может быть переопределён параметрами `--no-autostash` и `--autostash` команды linkgit:git-rebase[1]. По умолчанию false.

rebase.updateRefs::
	Если установлено в true, включить параметр `--update-refs` по умолчанию.

rebase.missingCommitsCheck::
	Если установлено в «warn», git rebase -i выведет предупреждение, если некоторые коммиты удалены (например, строка была удалена), однако перемещение всё равно продолжится. Если установлено в «error», он выведет предыдущее предупреждение и остановит перемещение; затем можно использовать 'git rebase --edit-todo' для исправления ошибки. Если установлено в «ignore», никакая проверка не выполняется. Чтобы отбросить коммит без предупреждения или ошибки, используйте команду `drop` в списке задач. По умолчанию «ignore».

rebase.instructionFormat::
	Строка формата, как указано в linkgit:git-log[1], используемая для списка задач во время интерактивного перемещения. К формату автоматически будет добавлен хеш коммита в начале.

rebase.abbreviateCommands::
	Если установлено в true, `git rebase` будет использовать сокращённые имена команд в списке задач, что приведёт к чему-то вроде этого:
+
-------------------------------------------
	p deadbee Однострочное описание коммита
	p fa1afe1 Однострочное описание следующего коммита
	...
-------------------------------------------
+
вместо:
+
-------------------------------------------
	pick deadbee Однострочное описание коммита
	pick fa1afe1 Однострочное описание следующего коммита
	...
-------------------------------------------
+
По умолчанию false.

rebase.rescheduleFailedExec::
	Автоматически перепланировать команды `exec`, которые завершились сбоем. Это имеет смысл только в интерактивном режиме (или когда была предоставлена опция `--exec`). Это то же самое, что и указание опции `--reschedule-failed-exec`.

rebase.forkPoint::
	Если установлено в false, установить опцию `--no-fork-point` по умолчанию.

rebase.rebaseMerges::
	Следует ли и как устанавливать опцию `--rebase-merges` по умолчанию. Может быть `rebase-cousins`, `no-rebase-cousins` или логическим значением. Установка в true или в `no-rebase-cousins` эквивалентна `--rebase-merges=no-rebase-cousins`, установка в `rebase-cousins` эквивалентна `--rebase-merges=rebase-cousins`, а установка в false эквивалентна `--no-rebase-merges`. Передача `--rebase-merges` в командной строке, с аргументом или без, переопределяет любую конфигурацию `rebase.rebaseMerges`.

rebase.maxLabelLength::
	При создании имён меток из тем коммитов усекать имена до этой длины. По умолчанию имена усекаются до значения немного меньшего, чем `NAME_MAX` (чтобы разрешить, например, запись файлов `.lock` для соответствующих непакованных (loose) ссылок).
