`push.autoSetupRemote`::
	Om satt till `true` antas `--set-upstream` vara standard push när ingen uppströmsspårning finns för den aktuella grenen; detta alternativ träder i kraft med `push.default`-alternativen `simple`, `upstream` och `current`. Det är användbart om du som standard vill att nya grenar ska pushas till standardfjärren (som beteendet hos `push.default=current`) och du också vill att uppströmsspårningen ska vara inställd. Arbetsflöden som sannolikt kommer att dra nytta av detta alternativ är `enkla` centrala arbetsflöden där alla grenar förväntas ha samma namn på fjärren.

`push.default`::
	Definierar åtgärden `git push` ska utföra om ingen refspec anges (vare sig från kommandoraden, konfigurationen eller någon annanstans). Olika värden är väl lämpade för specifika arbetsflöden; till exempel, i ett rent centralt arbetsflöde (dvs. hämtningskällan är lika med push-destinationen) är `upstream` förmodligen vad du vill ha. Möjliga värden är:
+
--
`nothing`;;
do not push anything (error out) unless a refspec is given. This is primarily meant for people who want to avoid mistakes by always being explicit.

`current`;;
skicka (push) den aktuella grenen för att uppdatera en gren med samma namn i mottagaränden. Fungerar i både centrala och icke-centrala arbetsflöden.

`upstream`;;
skicka (push) den aktuella grenen tillbaka till den gren vars ändringar vanligtvis är integrerade i den aktuella grenen (som kallas `@{upstream}`). Det här läget är bara meningsfullt om du skickar till samma arkiv som du normalt skulle hämta från (dvs. centralt arbetsflöde).

`tracking`;;
this is a deprecated synonym for `upstream`.

`simple`;;
push the current branch with the same name on the remote.
+
Om du arbetar med ett centraliserat arbetsflöde (push:ar till samma förvar som du hämtar från, vilket vanligtvis är `origin`), måste du konfigurera en uppströmsgren med samma namn.
+
Det här läget är standardläget sedan Git 2.0 och är det säkraste alternativet som passar nybörjare.

`matching`;;
skicka (push) alla grenar med samma namn i båda ändar. Detta gör att arkivet du skickar kommer ihåg uppsättningen grenar som kommer att skickas ut (t.ex. om du alltid skickar `maint` och `master` där och inga andra grenar, kommer arkivet du skickar till att ha dessa två grenar, och dina lokala `maint` och `master` kommer att skickas dit).
+
För att använda det här läget effektivt måste du se till att _alla_ grenar du vill skicka ut är redo att skickas ut innan du kör `git push`, eftersom hela poängen med det här läget är att låta dig skicka alla grenar på en gång. Om du vanligtvis bara avslutar arbetet på en gren och skickar ut resultatet, medan andra grenar är oavslutade, är det här läget inte för dig. Det här läget är inte heller lämpligt för att skicka till ett delat centralt arkiv, eftersom andra personer kan lägga till nya grenar där, eller uppdatera toppen på befintliga grenar utanför din kontroll.
+
Detta brukade vara standardinställningen, men inte sedan Git 2.0 (`simple` är den nya standardinställningen).

--

`push.followTags`::
	Om den är satt till sant, aktivera alternativet `--follow-tags` som standard. Du kan åsidosätta denna konfiguration vid skicka-tillfället (push) genom att ange `--no-follow-tags`.

`push.gpgSign`::
	Kan sättas till ett booleskt värde, eller strängen `if-asked`. Ett sant värde gör att alla sändningar (push) GPG-signeras, som om `--signed` skickas till linkgit:git-push[1]. Strängen `if-asked` gör att push-filer signeras om servern stöder det, som om `--signed=if-asked` skickas till `git push`. Ett falskt värde kan åsidosätta ett värde från en konfigurationsfil med lägre prioritet. En explicit kommandoradsflagga åsidosätter alltid detta konfigurationsalternativ.

`push.pushOption`::
	När inget `--push-option=<alternativ>`-argument anges från kommandoraden, beter sig `git push` som om varje _<alternativ>_ i denna variabel anges som `--push-option=<alternativ>`.
+
Detta är en variabel med flera värden, och ett tomt värde kan användas i en konfigurationsfil med högre prioritet (t.ex. `.git/config` i ett förvar) för att rensa värden som ärvts från konfigurationsfiler med lägre prioritet (t.ex. `$HOME/.gitconfig`).
+
----

Exempel:

/etc/gitconfig
  push.pushoption = a
  push.pushoption = b

~/.gitconfig
  push.pushoption = c

repo/.git/config
  push.pushoption =
  push.pushoption = b

Detta kommer att resultera i att endast b (a och c är nollställda).

----

`push.recurseSubmodules`::
	Kan vara `check`, `on-demand`, `only` eller `no`, med samma beteende som `push --recurse-submodules`. Om inte angivet används `no` som standard, såvida inte `submodule.recurse` är angivet (i vilket fall ett `true`-värde betyder `on-demand`).

`push.useForceIfIncludes`::
	Om den är satt till `true` motsvarar det att ange `--force-if-includes` som ett alternativ till linkgit:git-push[1] i kommandoraden. Att lägga till `--no-force-if-includes` vid tidpunkten för push åsidosätter denna konfigurations-inställning.

`push.negotiate`::
	Om värdet är satt till `true`, försök att minska storleken på packfilen som skickas genom förhandlingsrundor där klienten och servern försöker hitta gemensamma incheckningar. Om `false` kommer Git att förlita sig enbart på serverns referensannonsering för att hitta gemensamma incheckningar.

`push.useBitmaps`::
	Om satt till `false`, inaktiveras användningen av bitmappar för `git push` även om `pack.useBitmaps` är `true`, utan att förhindra att andra git-operationer använder bitmappar. Standardvärdet är `true`.
