rebase.backend::
	Standard-bakända att använda för ombasering. Möjliga val är 'apply' (tillämpa) eller 'merge' (sammanslå). Om sammanfognings-bakändan i framtiden får alla återstående funktioner från tillämpa-bakändan , kan den här inställningen bli oanvänd.

rebase.stat::
	Whether to show a diffstat of what changed upstream since the last rebase. False by default.

rebase.autoSquash::
	Om satt till sant, aktivera alternativet `--autosquash` i linkgit:git-rebase[1] som standard för interaktivt läge. Detta kan åsidosättas med alternativet `--no-autosquash`.

rebase.autoStash::
	När den är satt till sant, skapas automatiskt en tillfällig gömma-post innan operationen börjar, och tillämpas efter att operationen är avslutad. Detta innebär att du kan köra rebase på ett smutsigt arbetsträd. Använd dock försiktigt: den slutliga gömma-applikationen efter en lyckad ombasering kan resultera i icke-triviala konflikter. Detta alternativ kan åsidosättas av alternativen `--no-autostash` och `--autostash` i linkgit:git-rebase[1]. Standardvärdet är falskt.

rebase.updateRefs::
	Om satt till sant aktiveras alternativet `--update-refs` som standard.

rebase.missingCommitsCheck::
	Om satt till "warn" (varna), kommer git rebase -i att skriva ut en varning om vissa incheckningar tas bort (t.ex. om en rad raderades), men ombaseringen kommer fortfarande att fortsätta. Om satt till "error" kommer den att skriva ut den föregående varningen och stoppa ombaseringen. 'git rebase --edit-todo' kan sedan användas för att korrigera felet. Om satt till "ignore" görs ingen kontroll. För att ta bort en incheckning utan varning eller fel, använd kommandot `drop` i att-göra-listan. Standardinställningen är "ignore".

rebase.instructionFormat::
	En formatsträng, som specificerad i linkgit:git-log[1], som ska användas för att-göra-listan under en interaktiv ombasering. Formatet kommer automatiskt att ha inchecknings-hashen till formatet.

rebase.abbreviateCommands::
	Om satt till sant, kommer `git rebase` att använda förkortade kommandonamn i att-göra-listan vilket resulterar i något liknande:
+
-------------------------------------------
	p deadbee The oneline of the commit
	p fa1afe1 The oneline of the next commit
	...
-------------------------------------------
+
i stället för:
+
-------------------------------------------
	pick deadbee The oneline of the commit
	pick fa1afe1 The oneline of the next commit
	...
-------------------------------------------
+
Standardvärdet är falskt.

rebase.rescheduleFailedExec::
	Schemalägg automatiskt `exec`-kommandon som misslyckades. Detta är bara logiskt i interaktivt läge (eller när ett `--exec`-alternativ angavs). Detta är samma sak som att ange `--reschedule-failed-exec`-alternativet.

rebase.forkPoint::
	Om den är satt till falskt, sätt alternativet `--no-fork-point` som standard.

rebase.rebaseMerges::
	Om och hur alternativet `--rebase-merges` ska ställas in som standard. Kan vara `rebase-cousins`, `no-rebase-cousins` eller ett booleskt värde. Att sätta till true eller `no-rebase-cousins` motsvarar `--rebase-merges=no-rebase-cousins`, att sätta till `rebase-cousins` motsvarar `--rebase-merges=rebase-cousins`, och att sätta till `false`(falsk) motsvarar `--no-rebase-merges`. Att skicka `--rebase-merges` på kommandoraden, med eller utan ett argument, åsidosätter alla `rebase.rebaseMerges`-konfigurationer.

rebase.maxLabelLength::
	Vid generering av etikettnamn från inlämningsrubriker, korta av namnen till denna längd. Som standard kortas namnen av till något mindre än `NAME_MAX` (för att tillåta att exempelvis .lock-filer kan skrivas för motsvarande lösa referenser).
