rebase.backend::
	Standardbakände för ombasering. Möjliga val är 'apply' (tillämpa) eller 'merge' (sammanslå). Om sammanslagningsbakänden i framtiden får alla återstående funktioner från tillämpabakänden, kan inställningen bli oanvänd.

rebase.stat::
	Visa en diffstat över vad som har ändrats uppströms sedan den senaste ombaseringen. Diffstat styrs också av konfigurationsalternativet rebase.stat.

rebase.autoSquash::
	Om satt till sant, aktivera alternativet `--autosquash` i linkgit:git-rebase[1] som standard för interaktivt läge. Detta kan åsidosättas med alternativet `--no-autosquash`.

rebase.autoStash::
	När den sätts till `true` skapas automatiskt en tillfällig gömd post innan operationen börjar, och den tillämpas efter att operationen avslutas. Det innebär att ombasering kan köras på ett smutsigt arbetsträd. Använd dock med försiktighet: den sista tillämpningen av gömman efter en lyckad ombasering kan ge icke-triviala konflikter. Inställningen kan åsidosättas med `--no-autostash` och `--autostash` i linkgit:git-rebase[1]. Standardvärdet är `false`.

rebase.updateRefs::
	Om satt till sant aktiveras alternativet `--update-refs` som standard.

rebase.missingCommitsCheck::
	Om satt till "warn" (varna), kommer git rebase -i att skriva ut en varning om vissa incheckningar tas bort (t.ex. om en rad raderades), men ombaseringen kommer fortfarande att fortsätta. Om satt till "error" kommer den att skriva ut den föregående varningen och stoppa ombaseringen. 'git rebase --edit-todo' kan sedan användas för att korrigera felet. Om satt till "ignore" görs ingen kontroll. För att ta bort en incheckning utan varning eller fel, använd kommandot `drop` i att-göra-listan. Standardinställningen är "ignore".

rebase.instructionFormat::
	En formatsträng, enligt specifikationen i linkgit:git-log[1], som används för todo-listan vid interaktiv ombasering. Incheckningshashen läggs automatiskt till i början av formatet.

rebase.abbreviateCommands::
	Om satt till sant, kommer `git rebase` att använda förkortade kommandonamn i att-göra-listan vilket resulterar i något liknande:
+
-------------------------------------------
pick deadbee Enrad i denna incheckning
pick fa1afe1 Enrad i nästa incheckning
...
-------------------------------------------
+
i stället för:
+
-------------------------------------------
pick deadbee Enrad i denna incheckning
pick fa1afe1 Enrad i nästa incheckning
...
-------------------------------------------
+
Standardvärdet är falskt.

rebase.rescheduleFailedExec::
	Schemalägg automatiskt om `exec`-kommandon som misslyckades. Detta är bara meningsfullt i interaktivt läge (eller när alternativet `--exec` har angivits). Detta motsvarar att ange alternativet `--reschedule-failed-exec`.

rebase.forkPoint::
	Om den är satt till falskt, sätt alternativet `--no-fork-point` som standard.

rebase.rebaseMerges::
	Om och hur alternativet `--rebase-merges` ska ställas in som standard. Kan vara `rebase-cousins`, `no-rebase-cousins` eller ett booleskt värde. Att sätta till `true` eller `no-rebase-cousins` motsvarar `--rebase-merges=no-rebase-cousins`, att sätta till `rebase-cousins` motsvarar `--rebase-merges=rebase-cousins`, och att sätta till `false` motsvarar `--no-rebase-merges`. Att skicka `--rebase-merges` på kommandoraden, med eller utan ett argument, åsidosätter alla `rebase.rebaseMerges`-konfigurationer.

rebase.maxLabelLength::
	Vid generering av etikettnamn från inlämningsrubriker, korta av namnen till denna längd. Som standard kortas namnen av till något mindre än `NAME_MAX` (för att tillåta att exempelvis .lock-filer kan skrivas för motsvarande lösa referenser).
