git-commit-tree(1)
==================

NOM
---
git-commit-tree - Crée un nouvel objet commit


SYNOPSIS
--------
[verse]
'git commit-tree' <arbre> [(-p <parent>)...]
'git commit-tree' [(-p <parent>)...] [-S[<id-clé>]] [(-m <message>)...]
		  [(-F <fichier>)...] <arbre>


DESCRIPTION
-----------
Ce n'est généralement pas ce qu'un utilisateur final veut exécuter directement. Voir linkgit:git-commit[1] à la place.

Crée un nouvel objet commit basé sur l'objet arbre fourni et émet l'identifiant du nouvel objet commit sur stdout. Le message de journal est lu depuis l'entrée standard, à moins que les options `-m` ou `-F` soient données.

Les options `-m` et `-F` peuvent être données plus d'une fois, dans n'importe quel ordre. Le message du journal de livraison sera composé dans l'ordre dans lequel les options sont données.

Un objet commit peut avoir un nombre quelconque de parents. Avec exactement un parent, c'est un commit ordinaire. Avoir plus d'un parent fait du commit une fusion entre plusieurs lignes d'historique. Les commits initiaux (racine) n'ont pas de parents.

Alors qu'un arbre représente un état particulier d'un répertoire de travail, un commit représente cet état dans le "temps", et explique comment y arriver.

Normalement, un commit devrait identifier un nouvel état "HEAD", et bien que Git ne se soucie pas de l'endroit où vous enregistrez la note sur cet état, en pratique nous avons tendance à simplement écrire le résultat dans le fichier qui est pointé par `.git/HEAD`, de sorte que nous pouvons toujours voir quel était le dernier état validé.

OPTIONS
-------
<arbre>::
	Un objet d'arbre existant.

-p <parent>::
	Chaque `-p` indique l'id d'un objet commit parent.

-m <message>::
	Un paragraphe dans le message du journal de validation. Ceci peut être donné plus d'une fois et chaque <message> devient son propre paragraphe.

-F <fichier>::
	Lire le message de validation depuis le fichier indiqué. Utilisez '-' pour lire le message depuis l'entrée standard. Ceci peut être indiqué plusieurs fois et le contenu de chaque fichier devient un paragraphe différent.

-S[<idclé>]::
--gpg-sign[=<idclé>]::
--no-gpg-sign::
	Signer les commits avec GPG. L'argument `idclé` est optionnel avec par défaut l'identité du validateur ; si spécifiée, elle doit être collée à l'option sans aucun espace. `--no-gpg-sign` est utile pour annuler l'effet de tout `--gpg-sign` précédent sur la ligne de commande.

Information de validation
-------------------------

Un commit encapsule :

- tous les identifiants des objets parents
- nom de l'auteur, courriel et date
- le nom et l'adresse électronique du validateur et la date du commit.

Un commentaire de validation est lu à partir de stdin. Si une entrée de changelog n’est pas fournie via la redirection « < », 'git commit-tree' attendra simplement qu’une entrée soit entrée et terminée par ^D.

include::date-formats.adoc[]

Discussion
----------

include::i18n.adoc[]

FICHIERS
--------
/etc/mailname

VOIR AUSSI
----------
linkgit:git-write-tree[1] linkgit:git-commit[1]

GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
