git-check-mailmap(1)
====================

NOM
---
git-check-mailmap - Affiche les noms canoniques et les adresses de courriel des contacts


SYNOPSIS
--------
[verse]
'git check-mailmap' [<options>] <contact>...


DESCRIPTION
-----------

For each ``Name $$<user@host>$$'', ``$$<user@host>$$'', or ``$$user@host$$'' from the command-line or standard input (when using `--stdin`), look up the person's canonical name and email address (see "Mapping Authors" below). If found, print them; otherwise print the input as-is.


OPTIONS
-------
--stdin::
	Lire les contacts, un par ligne, à partir de l'entrée standard après avoir épuisé les contacts fournis sur la ligne de commande.

--mailmap-file=<fichier>::
	En plus de tous les fichiers configurés, lire le fichier mailmap spécifié. Les entrées dans ce fichier ont préséance sur les entrées dans le fichier mailmap par défaut ou tout fichier mailmap configuré.

--mailmap-blob=<blob>::
	Comme `--mailmap-file`, mais considérer la valeur comme une référence vers un blob dans le dépôt. Si `--mailmap-file` et `--mailmap-blob` sont spécifiés tous les deux, les entrées dans `--mailmap-file` auront priorité.

SORTIE
------

Pour chaque contact, une seule ligne est sortie, terminée par un saut de ligne. Si le nom est fourni ou connu de la 'mailmap', "Nom $$<utilisateur@hote>$$" est affiché ; sinon, seul "$$<utilisateur@hote>$$" est affiché.


CONFIGURATION
-------------

Voir `mailmap.file` et `mailmap.blob` dans linkgit:git-config[1] pour savoir comment spécifier un fichier ou un objet cible `.mailmap` personnalisé.


TRANSFORMER LES AUTEURS
-----------------------

Voir linkgit:gitmailmap[5].


GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
