git-stripspace(1)
=================

NOM
---
git-stripspace - Supprimer les espaces blancs inutiles


SYNOPSIS
--------
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

DESCRIPTION
-----------

Lire le texte, comme les messages de validation, les notes, les étiquettes et les descriptions de branche, de l'entrée standard et le nettoyer de la manière utilisée par Git.

Sans argument, ceci :

- retirer les espaces de toutes les lignes
- réduire plusieurs lignes vides consécutives en une ligne vide
- supprimer les lignes vides au début et à la fin de l'entrée
- ajoutera un '\n' manquant à la dernière ligne si nécessaire.

Dans le cas où l'entrée se compose entièrement de caractères d'espace blanc, aucune sortie ne sera produite.

*NOTE* : Ceci est destiné au nettoyage des métadonnées. Préférez le mode `--whitespace=fix` de linkgit:git-apply[1] pour corriger l'espace blanc des rustines ou des fichiers dans le dépôt.

OPTIONS
-------
-s::
--strip-comments::
	Sauter et supprimer toutes les lignes commençant par un caractère de commentaire (`core.commentChar`, par défaut `#`).

-c::
--comment-lines::
	Préfixer chaque ligne par le caractère de commentaire et un espace vierge. Les lignes se termineront automatiquement avec une nouvelle ligne. Sur les lignes vides, seul le caractère de commentaire sera ajouté.

EXEMPLES
--------

Avec l'entrée bruyante suivante avec '$' indiquant la fin d'une ligne :

---------
|A brief introduction   $
|   $
|$
|A new paragraph$
|# with a commented-out line    $
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out. $
|      $
|The end.$
|  $
---------

Utilisez 'git stripspace' sans argument pour obtenir :

---------
|A brief introduction$
|$
|A new paragraph$
|# with a commented-out line$
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out.$
|$
|The end.$
---------

Utilisez 'git stripspace --strip-comments' pour obtenir :

---------
|A brief introduction$
|$
|A new paragraph$
|explaining lots of stuff.$
|$
|The end.$
---------

GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
