git-config(1)
=============

NOM
---
git-config - Lire et écrire les options du dépôt et les options globales


SYNOPSIS
--------
[verse]
'git config list' [<option-de-fichier>] [<option-d-affichage>] [--includes]
'git config get' [<option-de-fichier>] [<option-d-affichage>] [--includes] [--all] [--regexp] [--value=<valeur>] [--fixed-value] [--default=<default>] <nom>
'git config set' [<option-de-fichier>] [--type=<type>] [--all] [--value=<valeur>] [--fixed-value] <nom> <valeur>
'git config unset' [<option-de-fichier>] [--all] [--value=<valeur>] [--fixed-value] <nom>
'git config rename-section' [<option-de-fichier>] <ancien-name> <nouveau-name>
'git config remove-section' [<option-de-fichier>] <nom>
'git config edit' [<option-de-fichier>]
'git config' [<option-de-fichier>] --get-colorbool <nom> [<stdout-est-tty>]

DESCRIPTION
-----------
Vous pouvez interroger/définir/remplacer/annuler les options avec cette commande. Le nom est en fait la section et la clé séparées par un point, et la valeur sera échappée.

Plusieurs lignes peuvent être ajoutées à une option en utilisant l'option `--append`. Si vous voulez mettre à jour ou annuler une option qui peut se trouver sur plusieurs lignes, un "motif-de-valeur" (qui est une expression régulière étendue, à moins que l'option "--fixed-value" soit donnée) doit être donné. Seules les valeurs existantes qui correspondent au motif sont mises à jour ou annulées. Si vous voulez gérer les lignes qui ne correspondent *pas* au motif, ajoutez simplement un point d'exclamation devant (voir aussi <<EXAMPLES>>), mais notez que cela ne fonctionne que lorsque l'option `--fixed-value` n'est pas utilisée.

L'option `--type=<type>` indique à 'git config' de s'assurer que les valeurs entrantes et sortantes peuvent être canonisées sous le <type> donné. Si aucun `--type=<type>` n'est donné, aucune canonisation ne sera effectuée. Les appelants peuvent annuler un spécificateur `--type` existant avec `--no-type`.

Lors de la lecture, les valeurs sont lues par défaut à partir des fichiers de configuration du système, du globaux à l'utilisateur et locaux au dépôt, et les options `--system`, `--global`, `--local`, `--worktree` et `--file <nom-de-fichier>` peuvent être utilisées pour indiquer à la commande de lire uniquement à partir de chaque emplacement (voir <<FILES>>).

Lors de l'écriture, la nouvelle valeur est écrite dans le fichier de configuration local du dépôt par défaut, et les options `--system`, `--global`, `--worktree`, `--file <fichier>` peuvent être utilisées pour dire à la commande d'écrire à cet endroit (vous pouvez dire `--local` mais c'est la valeur par défaut).

Cette commande échouera avec un statut non nul en cas d'erreur. Certains codes de sortie sont :

- La section ou la clé n'est pas valide (ret=1),
- aucune section ou nom n'a été fourni (ret=2),
- le fichier de configuration est invalide (ret=3),
- le fichier de configuration ne peut pas être écrit (ret=4),
- vous essayez d'annuler une option qui n'existe pas (ret=5),
- vous essayez de désactiver/définir une option pour laquelle plusieurs lignes correspondent (ret=5), ou
- vous essayez d'utiliser une expression rationnelle non valide (ret=6).

En cas de succès, la commande renvoie le code de sortie 0.

Une liste de toutes les variables de configuration disponibles peut être obtenue en utilisant la commande `git help --config`.

COMMANDES
---------

list::
	Lister toutes les variables définies dans le fichier de configuration, avec leurs valeurs.

get::
	Émet la valeur de la clé spécifiée. Si la clé est présente plusieurs fois dans la configuration, émet la dernière valeur. Si `--all` est spécifié, émet toutes les valeurs associées à la clé. Retourne le code d'erreur 1 si la clé n'est pas présente.

set::
	Définir la valeur pour une ou plusieurs options de configuration. Par défaut, cette commande refuse d'écrire des options de configuration multi-valeur. Passer `--all` remplacera toutes les options de configuration multi-valeur avec la nouvelle valeur, alors que `--value=` remplacera toutes les options de configuration dont les valeurs correspondent au modèle donné.

unset::
	Valeur désinitialisée pour une ou plusieurs options de configuration. Par défaut, cette commande refuse de désactiver les clés multi-valeurs. Passer `--all` dé-enregistrera toutes les options de configuration multi-valeur, alors que `--value` dé-enregistrera toutes les options de configuration dont les valeurs correspondent au modèle donné.

rename-section::
	Renommer la section donnée avec un nouveau nom.

remove-section::
	Supprimer la section indiquée du fichier de configuration.

edit::
	Ouvrir un éditeur pour modifier le fichier de configuration spécifié ; soit `--system`, `--global`, `--local` (par défaut), `--worktree`ou `--file <fichier-config>`.

[[OPTIONS]]
OPTIONS
-------

--replace-all::
	Le comportement par défaut est de remplacer au maximum une ligne. Ceci remplace toutes les lignes correspondant à la clé (et optionnellement au `motif-de-valeur`).

--append::
	Ajoute une nouvelle ligne à l'option sans modifier les valeurs existantes. C'est la même chose que de fournir `--value=^$` à `set`.

--comment <message>::
	Ajouter un commentaire à la fin des lignes nouvelles ou modifiées.

	Si _<message>_ commence avec un ou plusieurs espaces blancs suivis par "#", il est utilisé tel quel. S'il commence par "#", un espace est préfixé avant qu'il ne soit utilisé. Sinon, une chaîne " # " (un espace suivi d'un dièse suivi d'un espace) est préfixée à elle. Et la chaîne résultante est placée immédiatement après la valeur définie pour la variable. Le _ <message>_ ne doit pas contenir de caractères retour-chariot (les commentaires multi-lignes ne sont pas permis).

--all::
	Avec `get`, renvoyer toutes les valeurs pour une clé à valeurs multiples.

--regexp::
	avec `get`, interpréter le nom comme une expression régulière. La correspondance des expressions régulières est actuellement sensible à la casse et se fait par rapport à une version canonisée de la clé dans laquelle les noms de sections et de variables sont en minuscules, mais pas les noms de sous-sections.

--url=<URL>::
	Lorsqu'un <nom> en deux parties <section>.<clé> est donné, la valeur de <section>.<URL>.<clé> dont la partie <URL> correspond le mieux à l'URL donnée est retournée (si une telle clé n'existe pas, la valeur de <section>.<clé> est utilisée comme solution de repli). Lorsqu'on donne juste la section comme nom, le faire pour toutes les clés de la <section> et les lister. Renvoie le code d'erreur 1 si aucune valeur n'est trouvée.

--global::
	Pour l'écriture des options : écrire dans le fichier global `~/.gitconfig` plutôt que dans le `.git/config` du dépôt, écrire dans le fichier `$XDG_CONFIG_HOME/git/config` si ce fichier existe et que le fichier `~/.gitconfig` n'existe pas.
+
Pour les options de lecture : lire uniquement depuis le `~/.gitconfig` global et depuis `$XDG_CONFIG_HOME/git/config` plutôt que depuis tous les fichiers disponibles.
+
Voir aussi <<FILES>>.

--system::
	Pour l'écriture des options : écrire dans le `$(prefix)/etc/gitconfig` niveau système plutôt que dans le `.git/config` du dépôt.
+
Pour la lecture des options : lire seulement à partir de `$(prefix)/etc/gitconfig` niveau système plutôt qu'à partir de tous les fichiers disponibles.
+
Voir aussi <<FILES>>.

--local::
	Pour l'écriture des options : écrire dans le fichier `.git/config` du dépôt. C'est le comportement par défaut.
+
Pour la lecture des options : lire uniquement depuis le `.git/config` du dépôt plutôt que depuis tous les fichiers disponibles.
+
Voir aussi <<FILES>>.

--worktree::
	Similaire à `--local` sauf que `$GIT_DIR/config.worktree` est lu ou écrit si `extensions.worktreeConfig` est activé. Sinon, c'est la même chose que `--local`. Notez que `$GIT_DIR` est égal à `$GIT_COMMON_DIR` pour l'arbre-de-travail principal, mais est de la forme `$GIT_DIR/worktrees/<id>/` pour les autres arbres-de-travail. Voir linkgit:git-worktree[1] pour savoir comment activer `extensions.worktreeConfig`.

-f <fichier-de-config>::
--file <fichier-de-config>::
	Pour l'écriture des options : écrire dans le fichier spécifié plutôt que dans le `.git/config` du dépôt.
+
Pour la lecture des options : lire uniquement à partir du fichier spécifié plutôt qu'à partir de tous les fichiers disponibles.
+
Voir aussi <<FILES>>.

--blob <blob>::
	Similaire à `--file` mais utiliser le blob donné au lieu d'un fichier. Par exemple, vous pouvez utiliser 'master:.gitmodules' pour lire les valeurs du fichier '.gitmodules' dans la branche master. Voir la section "SPECIFICATION DE REVISIONS" dans linkgit:gitrevisions[7] pour une liste plus complète des façons d'épeler les noms de blob.

--fixed-value::
	Lorsqu’utilisé avec l’argument 'value-pattern', traiter 'motif-de-valeur' comme une chaîne exacte au lieu d’une expression régulière. Cela limitera les paires nom/valeur qui sont trouvées à celles dont la valeur est exactement égale au `motif-de-valeur`.

--type <type>::
  'git config' s'assurera que toute entrée ou sortie est valide sous la ou les contraintes de type fournies, et canonisera les valeurs sortantes dans la forme canonique de `<type>`.
+
Les « <type> » valides comprennent :
+
- 'bool' : canonicaliser les valeurs `true`, `yes`,`on`, et les nombres positifs comme `true`, et les valeurs `false`, `no`, `off` et `0` comme `false`.
- 'int' : canoniser les valeurs sous forme de nombres décimaux simples. Un suffixe facultatif de 'k', 'm' ou 'g' entraînera la multiplication de la valeur par 1024, 1048576 ou 1073741824 lors de la lecture.
- 'bool-ou-int' : canoniser selon 'bool' ou 'int', comme décrit ci-dessus.
- 'path' : canonise en ajoutant un `~` à la valeur de `$HOME` et `~user` au répertoire personnel de l'utilisateur spécifié. Ce spécificateur n'a aucun effet lors de la définition de la valeur (mais vous pouvez utiliser `git config section.variable ~/` depuis la ligne de commande pour laisser votre shell faire l'expansion).
- expiry-date' : canonisation en convertissant une chaîne de date fixe ou relative en un horodatage. Ce spécificateur n'a aucun effet lors de la définition de la valeur.
- 'color' : Lors de l'obtention d'une valeur, la canoniser en la convertissant en une séquence d'échappement de couleur ANSI. Lors de la définition d'une valeur, un contrôle de sanité est effectué pour s'assurer que la valeur donnée peut être canonisée en tant que couleur ANSI, mais elle est écrite telle quelle.
+

--bool::
--int::
--bool-or-int::
--path::
--expiry-date::
  Options historiques pour la sélection d'un spécificateur de type. Préférez plutôt `--type` (voir ci-dessus).

--no-type::
  Défait le spécificateur de type précédemment défini (s'il y en avait un). Cette option demande à 'git config' de ne pas canoniser la variable récupérée. `--no-type` n'a aucun effet sans `--type=<type>` ou `--<type>`.

-z::
--null::
	Pour toutes les options qui produisent des valeurs et/ou des clés, terminer toujours les valeurs par le caractère nul (au lieu d'une nouvelle ligne). Utiliser plutôt le saut de ligne comme délimiteur entre la clé et la valeur. Cela permet une analyse sûre de la sortie sans être confondu, par exemple, avec des valeurs qui contiennent des sauts de ligne.

--name-only::
	Afficher seulement les noms des variables de configuration pour `list` ou `get`.

--show-origin::
	Augmenter la sortie de toutes les options de configuration interrogées avec le type d'origine (fichier, entrée standard, blob, ligne de commande) et l'origine réelle (chemin du fichier de configuration, ref, ou identifiant du blob si applicable).

--show-scope::
	Similaire à `--show-origin` en ce qu'il augmente la sortie de toutes les options de configuration interrogées avec la portée de cette valeur (arbre-de-travail, locale, globale, système, commande).

--get-colorbool <nom> [<stdout-est-tty>]::

	Trouver le paramètre de couleur pour `<nom>` (par exemple, `color.diff`) et affiche "true" ou "false". `<stdout-est-tty>` devrait être soit "true" soit "false", et est pris en compte lorsque la configuration est "auto". Si `<stdout-est-tty>` est absent, alors vérifier la sortie standard de la commande elle-même, et sortir avec le statut 0 si la couleur doit être utilisée, ou sortir avec le statut 1 sinon. Lorsque le paramètre de couleur pour `<nom>` est indéfini, la commande utilise `color.ui` comme solution de repli.

--[no-]includes::
	Respecter les directives `include.*` dans les fichiers de configuration lors de la recherche de valeurs. La valeur par défaut est `off` lorsqu'un fichier spécifique est donné (par exemple, en utilisant `--file`, `--global`, etc) et `on` lorsqu'on cherche dans tous les fichiers de configuration.

--default <valeur>::
  Lors de l'utilisation de `get`, et que la variable demandée n'est pas trouvée, se comporter comme si _<valeur>_ était la valeur assignée à cette variable.

MODES OBSOLÈTES
---------------

Les modes suivants ont été dépréciés en faveur des sous-commandes. Il est recommandé de migrer vers la nouvelle syntaxe.

'git config <nom>'::
	Remplacé par `git config get <nom>`.

'git config <nom> [<motif-de-valeur>]'::
	Remplacé par `git config set [--value=<motif>] <nom> <valeur>`.

-l::
--list::
	Remplacé par`git config list`.

--get <nom> [<motif-de-valeur>]::
	Remplacé par `git config get [--value= <motif>] <nom>`.

--get-all <nom> [<motif-de-valeur>]::
	Remplacé par `git config get [--value=<motif>] --all <nom>`.

--get-regexp <regexp-de-nom>::
	Remplacé par `git config get --all --show-names --regexp <regexp-de-nom>`.

--get-urlmatch <nom> <URL>::
	Remplacé par `git config get --all --show-names --url= <URL> <nom>`.

--get-color <nom> [<défaut>]::
	Remplacé par `git config get --type=color [--default= <défaut>] <nom>`.

--add <nom> <valeur>::
	Remplacé par `git config set --append <nom> <valeur>`.

--unset <nom> [<motif-de-valeur>]::
	Remplacé par `git config unset [--value= <motif>] <nom>`.

--unset-all <nom> [<motif-de-valeur>]::
	Remplacé par `git config unset [--value=<motif>] --all <nom>`.

--rename-section <ancien-nom> <nouveau-nom>::
	Remplacé par `git config rename-section <ancien-nom> <nouveau-nom>`.

--remove-section <nom>::
	Remplacé par `git config remove-section <nom>`.

-e::
--edit::
	Remplacé par `git config edit`.

CONFIGURATION
-------------
`pager.config` n'est respecté que lors de l'énumération de la configuration, c'est-à-dire lors de l'utilisation de `list` ou de l'un des `get` qui peuvent retourner plusieurs résultats. Le défaut est d'utiliser un pager.

[[FILES]]
FICHIERS
--------

Par défaut, 'git config' lira les options de configuration à partir de plusieurs fichiers :

$(prefix)/etc/gitconfig::
	Fichier de configuration au niveau système.

$XDG_CONFIG_HOME/git/config::
~/.gitconfig::
	Fichiers de configuration spécifiques à l'utilisateur. Lorsque la variable d'environnement XDG_CONFIG_HOME n'est pas définie ou est vide, $HOME/.config/ est utilisé comme $XDG_CONFIG_HOME.
+
Ces fichiers sont également appelés fichiers de configuration "globaux". Si les deux fichiers existent, ils sont lus dans l'ordre donné ci-dessus.

$GIT_DIR/config::
	Fichier de configuration spécifique au dépôt.

$GIT_DIR/config.worktree::
	Ceci est optionnel et n'est recherché que si `extensions.worktreeConfig` est présent dans $GIT_DIR/config.

Vous pouvez aussi fournir des paramètres de configuration additionnels lorsque vous exécutez une commande git en utilisant l'option `-c`. Voir linkgit:git[1] pour plus de détails.

Les options seront lues depuis tous ces fichiers lorsqu'ils sont disponibles. Si le fichier de configuration global ou le fichier de configuration du système sont manquants ou illisibles, ils seront ignorés. Si le fichier de configuration du dépôt est manquant ou illisible, 'git config' se terminera avec un code d'erreur non nul. Un message d'erreur sera produit si le fichier n'est pas lisible, mais pas s'il est manquant.

Les fichiers sont lus dans l'ordre indiqué ci-dessus, la dernière valeur trouvée étant prioritaire sur les valeurs lues précédemment. Lorsque plusieurs valeurs peuvent être concaténées, toutes les valeurs d'une clé dans tous les fichiers seront utilisées.

Par défaut, les options sont seulement écrites dans le fichier de configuration spécifique au dépôt. Notez que cela affecte également les options comme `set` et `unset`. *'git config' ne modifiera jamais qu'un seul fichier à la fois*.

Vous pouvez limiter les sources de configuration qui sont lues ou écrites en spécifiant le chemin d'un fichier avec l'option `--file`, ou en spécifiant une portée de configuration avec `--system`, `--global`, `--local`, ou `--worktree`. Pour en savoir plus, voir <<OPTIONS>> ci-dessus.

[[SCOPES]]
PORTÉES
-------

Chaque source de configuration relève d'une portée de configuration. Les portées sont les suivantes :

Système::
	$(prefix)/etc/gitconfig

global::
	$XDG_CONFIG_HOME/git/config
+
~/.gitconfig

local::
	$GIT_DIR/config

arbre-de-travail::
	$GIT_DIR/config.worktree

commande::
	variables d'environnement GIT_CONFIG_{COUNT,KEY,VALUE} (voir <<ENVIRONMENT>> ci-dessous)
+
l'option `-c`

À l'exception de 'commande', chaque portée correspond à une option de ligne de commande : `--system`, `--global`, `--local`, `--worktree`.

Lors de la lecture d'options, la spécification d'une portée ne lira que les options des fichiers de cette portée. Lors de l'écriture d'options, la spécification d'une portée écrira dans les fichiers de cette portée (au lieu du fichier de configuration spécifique au dépôt). Voir <<OPTIONS>> ci-dessus pour une description complète.

La plupart des options de configuration sont respectées quelle que soit la portée dans laquelle elles sont définies, mais certaines options ne sont respectées que dans certaines portées. Consultez la documentation de l'option concernée pour plus de détails.

Configuration protégée
~~~~~~~~~~~~~~~~~~~~~~

La configuration protégée fait référence aux portées 'système', 'global' et 'commande'. Pour des raisons de sécurité, certaines options ne sont respectées que lorsqu'elles sont spécifiées en configuration protégée, et ignorées dans le cas contraire.

Git traite ces portées comme si elles étaient contrôlées par l'utilisateur ou un administrateur de confiance. Ceci est dû au fait qu'un attaquant qui contrôle ces portées peut causer des dommages substantiels sans utiliser Git, il est donc supposé que l'environnement de l'utilisateur protège ces portées contre les attaquants.

[[ENVIRONMENT]]
ENVIRONNEMENT
-------------

GIT_CONFIG_GLOBAL::
GIT_CONFIG_SYSTEM::
	Prendre la configuration à partir des fichiers donnés au lieu de la configuration globale ou au niveau du système. Voir linkgit:git[1] pour plus de détails.

GIT_CONFIG_NOSYSTEM::
	Si l'on veut éviter de lire les paramètres du fichier $(prefix)/etc/gitconfig du système. Voir linkgit:git[1] pour plus de détails.

Voir aussi <<FILES>>.

GIT_CONFIG_COUNT::
GIT_CONFIG_KEY_<n>::
GIT_CONFIG_VALUE_<n>::
	Si GIT_CONFIG_COUNT est défini comme un nombre positif, toutes les paires d'environnement GIT_CONFIG_KEY_<n> et GIT_CONFIG_VALUE_<n> jusqu'à ce nombre seront ajoutées à la configuration d'exécution du processus. Les paires de configurations sont indexées à zéro. Toute clé ou valeur manquante est traitée comme une erreur. Un GIT_CONFIG_COUNT vide est traité de la même manière que GIT_CONFIG_COUNT=0, c'est-à-dire qu'aucune paire n'est traitée. Ces variables d'environnement remplaceront les valeurs dans les fichiers de configuration, mais seront remplacées par toute option explicite passée via `git -c`.
+
C'est utile dans les cas où vous voulez lancer plusieurs commandes git avec une configuration commune mais ne pouvez pas dépendre d'un fichier de configuration, par exemple lorsque vous écrivez des scripts.

GIT_CONFIG::
	Si aucune option `--file` n'est fournie à `git config`, utiliser le fichier donné par `GIT_CONFIG` comme s'il était fourni via `--file`. Cette variable n'a aucun effet sur les autres commandes Git, et est surtout destinée à assurer une compatibilité historique ; il n'y a généralement aucune raison de l'utiliser à la place de l'option `--file`.

[[EXAMPLES]]
EXEMPLES
--------

Avec un .git/config comme ceci :

------------
#
# C'est le fichier de configuration, et
# un caractère '#' ou ';' indique
# un commentaire
#

; variables de base
[core]
	; ne pas faire confiance au mode des fichiers
	filemode = false

; Notre algorithme de diff
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

; paramètres du proxy
[core]
	gitproxy=proxy-command for kernel.org
	gitproxy=default-proxy ; pour tout le reste

; HTTP
[http]
	sslVerify
[http "https://weak.example.com"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
------------

vous pouvez mettre le filemode à true avec

------------
% git config set core.filemode true
------------

Les entrées hypothétiques de la commande proxy ont en fait un postfix pour discerner l'URL à laquelle elles s'appliquent. Voici comment changer l'entrée pour kernel.org en "ssh".

------------
% git config set --value='for kernel.org$' core.gitproxy '"ssh" for kernel.org'
------------

Cela permet de s'assurer que seule la paire clé/valeur de kernel.org est remplacée.

Pour supprimer l'entrée pour les renommages, faites

------------
% git config unset diff.renames
------------

Si vous voulez supprimer une entrée pour un multivar (comme core.gitproxy ci-dessus), vous devez fournir une regex correspondant à la valeur d'exactement une ligne.

Pour demander la valeur d'une clef donnée, faites

------------
% git config get core.filemode
------------

ou, pour interroger un multivar :

------------
% git config get --value="for kernel.org$" core.gitproxy
------------

Si vous voulez connaître toutes les valeurs d’un multivar, faites :

------------
% git config get --all --show-names core.gitproxy
------------

Si vous aimez vivre dangereusement, vous pouvez remplacer *tout* core.gitproxy par une nouvelle valeur avec

------------
% git config set --all core.gitproxy ssh
------------

Cependant, si vous voulez seulement remplacer la ligne pour le proxy par défaut, c'est-à-dire celui sans postfixe "for ...", faites quelque chose comme ceci :

------------
% git config set --value='! for ' core.gitproxy ssh
------------

Pour ne faire correspondre que les valeurs comportant un point d'exclamation, vous devez

------------
% git config set --value='[!]' section.key value
------------

Pour ajouter un nouveau proxy, sans modifier aucun des proxy existants, utilisez

------------
% git config set --append core.gitproxy '"proxy-command" for exemple.com'
------------

Un exemple d'utilisation de la couleur personnalisée de la configuration dans votre script :

------------
#!/bin/sh
WS=$(git config get --type=color --default="blue reverse" color.diff.whitespace)
RESET=$(git config get --type=color --default="reset" "")
echo "${WS}votre color d'espace et bleu sont échangées${RESET}"
------------

Pour les URLs dans `https://weak.example.com`, `http.sslVerify` est mis à false, alors qu'il est mis à `true` pour toutes les autres :

------------
% git config get --type=bool --url=https://bon.exemple.com http.sslverify
true
% git config get --type=bool --url=https://faible.exemple.com http.sslverify
false
% git config get --url=https://weak.example.com http
http.cookieFile /tmp/cookie.txt
http.sslverify false
------------

include::config.adoc[]

BOGUES
------
Lors de l'utilisation de la syntaxe dépréciée `[section.sous-section]`, la modification d'une valeur entraînera l'ajout d'une clé multi-lignes au lieu d'une modification, si la sous-section est donnée avec au moins un caractère majuscule. Par exemple, lorsque la configuration ressemble à

--------
  [section.sous-section]
    clé = valeur1
--------

et l'exécution de `git config section.sous-section.clé valeur2` donnera comme résultat

--------
  [section.sous-section]
    clé = valeur1
    clé = valeur2
--------


GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
