git-sh-setup(1)
===============

NOM
---
git-sh-setup - Le code d'initialisation commun aux scripts shell Git

SYNOPSIS
--------
[verse]
'. "$(git --exec-path)/git-sh-setup"'

DESCRIPTION
-----------

Ce n'est pas une commande que l'utilisateur final voudrait exécuter. Jamais. Cette documentation est destinée aux personnes qui étudient les scripts porcelaine et/ou en écrivent de nouveaux.

Le script 'git sh-setup' est conçu pour être sourcé (en utilisant `.`) par d'autres scripts shell pour configurer quelques variables pointant sur les répertoires Git normaux et quelques fonctions auxiliaires de shell.

Avant de le sourcer, votre script devrait configurer quelques variables ; `USAGE` (et `LONG_USAGE`, le cas échéant) est utilisé pour définir le message donné par la fonction shell `usage()`. `SUBDIRECTORY_OK` peut être défini si le script peut fonctionner à partir d'un sous-répertoire de l'arbre de travail (certaines commandes ne le peuvent pas).

Le scriptlet définit les variables shell `GIT_DIR` et `GIT_OBJECT_DIRECTORY`, mais ne les exporte *pas* dans l'environnement.

FONCTIONS
---------

die::
	sortir après l'émission du message d'erreur fourni au flux d'erreur standard.

usage::
	mourir avec le message d'utilisation.

set_reflog_action::
	Définir l'environnement `GIT_REFLOG_ACTION' à une chaîne donnée (généralement le nom du programme) à moins qu'il ne soit déjà défini. Chaque fois que le script exécute une commande `git` qui met à jour des réfs, une entrée de reflog est créée en utilisant la valeur de cette chaîne pour laisser une trace de la commande qui a mis à jour la réf.

git_editor::
	exécute un éditeur du choix de l'utilisateur (`GIT_EDITOR`, `core.editor`, `VISUAL` ou `EDITOR`) sur un fichier donné, mais sort en erreur si aucun éditeur n'est spécifié et que le terminal est simple.

is_bare_repository::
	affiche `true` ou `false` vers le flux de sortie standard pour indiquer si le dépôt est un dépôt nu (c.-à-d. sans arbre de travail associé).

cd_to_toplevel::
	se placer dans le répertoire à la racine de l'arbre de travail.

require_work_tree::
	vérifie si le répertoire actuel se trouve dans l'arbre de travail du dépôt et meurt sinon.

require_work_tree_exists::
	vérifie si l'arbre de travail associé au dépôt existe et termine autrement. Fait souvent avant d'appeler cd_to_toplevel, ce qui est impossible à faire s'il n'y a pas d'arbre de travail.

require_clean_work_tree <action> [<indice>]::
	vérifie que l'arbre de travail et l'index associés au dépôt n'ont pas de modifications de fichiers suivis non validées . Sinon, il émet un message d'erreur de la forme `Impossible <action> :<raison>. <indice>`, et termine. Exemple :
+
----------------
require_clean_work_tree rebase "S'il vous plaît, validez-les ou remisez-les."
----------------

get_author_ident_from_commit::
	sort avec un code pour utilisation avec eval pour définir les variables GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL et GIT_AUTHOR_DATE pour un commit donné.

create_virtual_base::
	modifie le premier fichier de sorte que seules les lignes en commun avec le deuxième fichier restent. S'il n'y a pas assez de matériau commun, le premier fichier est laissé vide. Le résultat est utilisable comme une entrée de base virtuelle pour une fusion à 3 voies.

GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
