git-merge(1)
============

NOM
---
git-merge - Fusionne deux ou plusieurs historiques de développement ensemble


SYNOPSIS
--------
[synopsis]
git merge [-n] [--stat] [--compact-summary] [--no-commit] [--squash] [--[no-]edit]
	[--no-verify] [-s <strategy>] [-X <strategy-option>] [-S[<keyid>]]
	[--[no-]allow-unrelated-histories]
	[--[no-]rerere-autoupdate] [-m <msg>] [-F <file>]
	[--into-name <branch>] [<commit>...]
git merge (--continue | --abort | --quit)

DESCRIPTION
-----------
Intègre les modifications des commits nommés (depuis le moment où leur historique a divergé de la branche actuelle) dans la branche actuelle. Cette commande est utilisée par 'git pull' pour incorporer les modifications d'un autre dépôt et peut être utilisée à la main pour fusionner les modifications d'une branche dans une autre.

Supposons que l'historique suivant existe et que la branche actuelle est `master` :

------------
          A---B---C sujet
         /
    D---E---F---G master
------------

Then `git merge topic` will replay the changes made on the `topic` branch since it diverged from `master` (i.e., `E`) until its current commit (`C`) on top of `master`, and record the result in a new commit along with the names of the two parent commits and a log message from the user describing the changes. Before the operation, `ORIG_HEAD` is set to the tip of the current branch (`G`).

------------
          A---B---C topic
         /         \
    D---E---F---G---H master
------------

Une fusion s'arrête s'il y a un conflit qui ne peut être résolu automatiquement ou si `--no-commit` a été fourni lors de l'amorce de la fusion. À ce moment vous pouvez lancer `git merge --abort` ou `git merge --continue`.

`git merge --abort` annulera le processus de fusion et tentera de reconstruire l'état antérieur à la fusion. Cependant, s'il y a eu des changements non validés au début de la fusion (et surtout si ces changements ont été modifiés après le début de la fusion), 'git merge --abort' sera dans certains cas incapable de reconstruire les modifications originales (avant la fusion). Par conséquent :

WARNING: Running `git merge` with non-trivial uncommitted changes is discouraged: while possible, it may leave you in a state that is hard to back out of in the case of a conflict.

OPTIONS
-------
:git-merge: 1

include::merge-options.adoc[]

`-m <msg>`::
	Définir le message de commit à utiliser pour le commit de fusion (dans le cas où un commit est créé).
+
Si `--log` est spécifié, un journal court des commits en cours de fusion sera ajouté au message spécifié.
+
La commande `git fmt-merge-msg` peut être utilisée pour donner une bonne valeur par défaut pour les invocations automatisées de `git merge`. Le message automatisé peut inclure la description de la branche.

`--into-name <branch>`::
	Prepare the default merge message as if merging to the branch _<branch>_, instead of the name of the real branch to which the merge is made.

`-F <fichier>`::
`--file=<fichier>`::
	Lire le message de commit à utiliser pour le commit de fusion (dans le cas où un commit est créé).
+
Si `--log` est spécifié, un journal court des commits en cours de fusion sera ajouté au message spécifié.

include::rerere-options.adoc[]

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	Écraser silencieusement les fichiers ignorés du résultat de la fusion. C'est le comportement par défaut. Utilisez `--no-overwrite-ignore` pour abandonner.

`--abort`::
	Abandonner le processus actuel de résolution des conflits, et essayer de reconstruire l'état antérieur à la fusion. Si une entrée de remisage automatique est présente, l'appliquer à l'arbre de travail.
+
S'il y avait des modifications non validées dans l'arbre de travail lorsque la fusion a commencé, `git merge --abort` sera dans certains cas incapable de reconstruire ces changements. Il est donc recommandé de toujours valider ou remiser vos modifications avant de lancer `git merge`.
+
`git merge --abort` est équivalent à `git reset --merge` quand `MERGE_HEAD` est présent à moins que `MERGE_AUTOSTASH` soit également présent, auquel cas `git merge --abort` applique l'entrée de la remisage à l'arbre de travail alors que `git reset --merge` sauvegardera les changements remisés dans la liste de remisage.

`--quit`::
	Oublier la fusion en cours. Laisser l'index et l'arbre de travail en l'ếtat. Si `MERGE_AUTOSTASH` est présent, l'entrée de la remisage sera sauvegardée dans la liste des remisages.

`--continue`::
	Après l'arrêt d'un `git merge` en raison de conflits, vous pouvez conclure la fusion en lançant `git merge --continue` (voir la section "COMMENT RÉSOUDRE LES CONFLITS" ci-dessous).

`<commit>...`::
	Les commits, généralement les sommets des autres branches, à fusionner avec notre branche. En spécifiant plus d'un commit, on crée une fusion avec plus de deux parents (affectueusement appelée fusion Octopus).
+
Si aucun commit n'est donné sur la ligne de commande, fusionner les branches de suivi à distance que la branche actuelle est configurée pour utiliser comme sa branche amont. Voir aussi la section configuration de cette page de manuel.
+
Lorsque `FETCH_HEAD` (et aucun autre commit) est spécifié, les branches enregistrées dans le fichier `.git/FETCH_HEAD` par l'invocation précédente de `git fetch` pour la fusion sont fusionnées à la branche courante.


VÉRIFICATIONS AVANT LA FUSION
-----------------------------

Avant d'appliquer des modifications extérieures, vous devez faire en sorte que votre propre travail soit en bon état et validé localement, afin qu'il ne soit pas écrasé en cas de conflits. Voir aussi linkgit:git-stash[1]. `git pull` et `git merge` s'arrêteront sans rien faire lorsque des modifications locales non validées chevaucheront des fichiers que `git pull`/`git merge` devront mettre à jour.

To avoid recording unrelated changes in the merge commit, `git pull` and `git merge` will also abort if there are any changes registered in the index relative to the `HEAD` commit. (Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match `HEAD`.)

Si tous les commit nommés sont déjà des ancêtres de `HEAD`, `git merge` sortira plus tôt avec le message « Déjà à jour ».

FUSION EN AVANCE RAPIDE
-----------------------

Souvent, le sommet de la branche actuelle est un ancêtre du commit nommé. C'est le cas le plus courant, surtout lorsqu'il est invoqué depuis `git pull` : vous suivez un dépôt amont, vous n'avez pas validé de modifications locales, et vous voulez maintenant mettre à jour vers une révision amont plus récente. Dans ce cas, un nouveau commit n'est pas nécessaire pour stocker l'historique combiné ; à la place, la `HEAD` (avec l'index) est mise à jour pour pointer vers le commit nommé, sans créer un commit de fusion supplémentaire.

Ce comportement peut être supprimé avec l'option `--no-ff`.

VÉRITABLE FUSION
----------------

Sauf dans le cas d'une fusion en avance rapide (voir ci-dessus), les branches à fusionner doivent être liées par un commit de fusion qui a pour parents les deux branches.

Une version fusionnée réconciliant les changements de toutes les branches à fusionner est validées, et votre `HEAD`, votre index et votre arbre de travail sont mis à jour en conséquence. Il est possible d'avoir des modifications dans l'arbre de travail tant qu'elles ne se chevauchent pas ; la mise à jour les préservera.

Lorsqu'il n'est pas évident de réconcilier les modifications, voici ce qui se passe :

1. Le pointeur `HEAD` reste le même.
2. La référence `MERGE_HEAD` est définie pour pointer vers l'autre tête de branche.
3. Les chemins qui ont été fusionnés proprement sont mis à jour à la fois dans le fichier d'index et dans votre arbre de travail.
4. For conflicting paths, the index file records up to three versions: stage 1 stores the version from the common ancestor, stage 2 from `HEAD`, and stage 3 from `MERGE_HEAD` (you can inspect the stages with `git ls-files -u`). The working tree files contain the result of the merge operation; i.e. 3-way merge results with familiar conflict markers +<<<+ `===` +>>>+.
5. A ref named `AUTO_MERGE` is written, pointing to a tree corresponding to the current content of the working tree (including conflict markers for textual conflicts). Note that this ref is only written when the `ort` merge strategy is used (the default).
6. Aucune autre modification n'est apportée. En particulier, les modifications locales que vous aviez avant de commencer la fusion resteront les mêmes et les entrées de l'index qui les concernent resteront telles quelles, c'est-à-dire correspondant à `HEAD`.

Si vous avez essayé une fusion qui a donné lieu à des conflits complexes et que vous voulez recommencer, vous pouvez vous remettre à zéro avec `git merge --abort`.

LA FUSION D'ÉTIQUETTE
---------------------

Lors de la fusion d'une étiquette annotée (et éventuellement signée), Git crée toujours un commit de fusion même si une fusion en avance rapide est possible, et le modèle de message de validation est préparé avec le message de l'étiquette. De plus, si l'étiquette est signée, la vérification de la signature est signalée sous forme de commentaire dans le modèle de message. Voir aussi linkgit:git-tag[1].

Lorsque vous souhaitez simplement intégrer le travail menant au commit qui se trouve être étiqueté, par exemple lors de la synchronisation avec un point de publication en amont, vous ne voudrez peut-être pas faire un commit de fusion inutile.

Dans ce cas, vous pouvez "déballer" l'étiquette vous-même avant de la donner à `git merge`, ou passer `--ff-only` lorsque vous n'avez pas de travail à faire vous-même par exemple

----
git fetch origin
git merge v1.2.3^0
git merge --ff-only v1.2.3
----

COMMENT LES CONFLITS SONT PRÉSENTÉS
-----------------------------------

Lors d'une fusion, les fichiers de l'arbre de travail sont mis à jour pour refléter le résultat de la fusion. Parmi les modifications apportées à la version de l'ancêtre commun, celles qui ne se chevauchent pas (c'est-à-dire que vous avez modifié une zone du fichier alors que l'autre côté a laissé cette zone intacte, ou vice versa) sont incorporées directement dans le résultat final. Cependant, lorsque les deux côtés ont apporté des modifications à la même zone, Git ne peut pas choisir au hasard un côté par rapport à l'autre, et vous demande de résoudre le problème en laissant ce que les deux côtés ont fait à cette zone.

Par défaut, Git utilise le même style que celui utilisé par le programme "merge" de la suite RCS pour présenter une telle section conflictuelle, comme ceci :

------------
Voici des lignes qui sont soit inchangées par rapport à l'ancêtre
commun, ou résolues proprement parce qu'un seul côté a changé,
ou parce que les deux côtés ont changé de la même manière.
<<<<<<< yours : exemple.txt
La résolution des conflits est difficile ;
allons faire du shopping.
=======
Git facilite la résolution des conflits.
>>>>>>> theirs : exemple.txt
Et voici une autre ligne qui est résolue proprement ou non modifiée.
------------

The area where a pair of conflicting changes happened is marked with markers +<<<<<<<+, `=======`, and +>>>>>>>+. The part before the `=======` is typically your side, and the part afterwards is typically their side.

Le format par défaut ne montre pas ce que l'original a dit dans la zone de conflit. Vous ne pouvez pas savoir combien de lignes sont supprimées et remplacées par la remarque de Barbie à votre côté. La seule chose que vous pouvez dire, c'est que votre côté veut dire que c'est difficile et que vous préférez faire du shopping, alors que l'autre côté veut prétendre que c'est facile.

An alternative style can be used by setting the `merge.conflictStyle` configuration variable to either `diff3` or `zdiff3`. In `diff3` style, the above conflict may look like this:

------------
Voici les lignes qui sont soit inchangées par rapport à l'ancêtre
commun, ou proprement résolues parce qu'un seul côté a changé,
<<<<<<<< yours:exemple.txt
ou parce que les deux côtés ont changé de la même façon.
La résolution des conflits est difficile ;
Allons faire du shopping.
||||||| base:sample.txt
ou parce que les deux côtés ont changé de la même façon.
La résolution des conflits est difficile.
=======
ou parce que les deux côtés ont changé de la même façon.
Git facilite la résolution des conflits.
>>>>>>> theirs:exemple.txt
Et voici une autre ligne qui est proprement résolue ou non modifiée.
------------

while in `zdiff3` style, it may look like this:

------------
Voici les lignes qui sont soit inchangées par rapport à l'ancêtre
commun, ou proprement résolu parce qu'un seul côté a changé,
ou parce que les deux côtés ont changé de la même manière.
<<<<<<<< yours:exemple.txt
La résolution des conflits est difficile ;
Allons faire du shopping.
||||||| base:sample.txt
ou parce que les deux côtés ont changé de la même manière.
La résolution des conflits est difficile.
=======
Git facilite la résolution des conflits.
>>>>>>> theirs:exemple.txt
Et voici une autre ligne qui est proprement résolue ou non modifiée.
------------

In addition to the +<<<<<<<+, `=======`, and +>>>>>>>+ markers, it uses another +|||||||+ marker that is followed by the original text. You can tell that the original just stated a fact, and your side simply gave in to that statement and gave up, while the other side tried to have a more positive attitude. You can sometimes come up with a better resolution by viewing the original.


COMMENT RÉSOUDRE LES CONFLITS
-----------------------------

Après avoir vu un conflit, vous pouvez faire deux choses :

 * Décider de ne pas fusionner. Les seuls nettoyages dont vous avez besoin sont de réinitialiser le fichier index au commit `HEAD` à inverser 2. et pour nettoyer les modification d’arbre de travail effectuées par 2. et 3.  ; `git merge --abort` peut être utilisé pour cela.

 * Résoudre les conflits. Git marquera les conflits dans l’arbre de travail. Modifier les fichiers en forme et les `git add` à l’index. Utiliser `git commit` ou `git merge --continue` pour sceller l’affaire. Cette dernière commande vérifie s’il y a une fusion (interrompue) en cours avant d’appeler `git commit`.

Vous pouvez résoudre le conflit à l'aide d'un certain nombre d'outils :

 * Utiliser un mergetool. `git mergetool` pour lancer un outil de fusion graphique qui vous permettra de travailler sur la fusion.

 * Regarder les différences. ` git diff` affichera une différence à trois points, en mettant en évidence les modifications apportées par les versions `HEAD` et `MERGE_HEAD`. `git diff AUTO_MERGE` va afficher quelles modifications vous avez réalisées jusqu'ici pour résoudre les conflits textuels.

 * Regarder les différences de chaque branche. `git log --merge -p <chemin>` montrera les différences d'abord pour la version `HEAD` et ensuite pour la version `MERGE_HEAD`.

 * Regarder les originaux. `git show :1:nom-de-fichier` montre l'ancêtre commun, `git show :2:nom-de-fichier` montre la version `HEAD`, et `git show :3:nom-de-fichier` montre la version `MERGE_HEAD`.


EXEMPLES
--------

* Fusionner les branches `corrections` et "améliorations` par dessus la branche actuelle, en faisant une fusion octopus :
+
------------------------------------------------
$ git merge corrections améliorations
------------------------------------------------

* Fusionner la branche `obsolète` dans la branche actuelle, en utilisant la stratégie de fusion `ours` :
+
------------------------------------------------
$ git merge -s ours obsolète
------------------------------------------------

* Fusionner la branche `maint` dans la branche actuelle, mais ne pas faire un nouveau commit automatiquement :
+
------------------------------------------------
$ git merge --no-commit maint
------------------------------------------------
+
Ceci peut être utilisé lorsque vous souhaitez inclure d'autres modifications à la fusion ou lorsque vous souhaitez rédiger votre propre message de validation de la fusion.
+
Vous devriez vous abstenir d'abuser de cette possibilité pour introduire en douce des modifications substantielles dans un commit de fusion. De petites corrections comme le remplacement du nom de la version ou de la livraison seraient acceptables.


include::merge-strategies.adoc[]

CONFIGURATION
-------------

`branch.<name>.mergeOptions`::
	Sets default options for merging into branch _<name>_. The syntax and supported options are the same as those of `git merge`, but option values containing whitespace characters are currently not supported.

include::includes/cmd-config-section-rest.adoc[]

include::config/merge.adoc[]

VOIR AUSSI
----------
linkgit:git-fmt-merge-msg[1], linkgit:git-pull[1], linkgit:gitattributes[5], linkgit:git-reset[1], linkgit:git-diff[1], linkgit:git-ls-files[1], linkgit:git-add[1], linkgit:git-rm[1], linkgit:git-mergetool[1]

GIT
---
Fait partie de la suite linkgit:git[1]

TRADUCTION
----------
Cette  page de manuel a été traduite par Jean-Noël Avila <jn.avila AT free DOT fr> et les membres du projet git-manpages-l10n. Veuillez signaler toute erreur de traduction par un rapport de bogue sur le site https://github.com/jnavila/git-manpages-l10n .
