SPÉCIFICATION DE RÉVISIONS
--------------------------

Un paramètre de révision _<rév>_, mais pas nécessairement, nomme un objet commit. Il utilise ce qu'on appelle une syntaxe 'extended SHA-1'. Voici différentes façons de faire des noms d'objets. Ceux énumérés près de la fin de cette liste nomment les arbres et les blobs contenus dans un commit.

NOTE: Ce document montre la syntaxe "raw" comme vue par git. Le shell et d'autres UIs pourraient nécessiter une citation supplémentaire pour protéger les caractères spéciaux et éviter le découpage des mots.

'<sha1>', pa ex. 'dae86e1950b1277e545cee180551750029cfe735', 'dae86e'::
  Le nom complet SHA-1 de l'objet (chaîne hexadécimale de 40 octets), ou un sous-chaîne d'entête unique dans le dépôt. par ex. dae86e1950b1277e545cee180551750029cfe735 et dae86e nomment le même objet de commit s'il n'y a pas d'autre objet dans votre dépôt dont le nom d'objet commence par dae86e.

'<sortieDécrite>', par ex. 'v1.7.4.2-679-g3bee7fb'::
  Sortie de `git describe` ; c.-à-d. une étiquette la plus proche, éventuellement suivie d'un tiret et d'un nombre de commits, suivi d'un tiret, d'un 'g' et d'un nom d'objet abrégé.

'<nom-de-réf>', c-à-d. 'master', 'heads/master', 'refs/heads/master'::
  Un nom symbolique. Par exemple, 'master' signifie généralement l'objet de commit référencé par 'refs/heads/master'. Si vous avez à la fois 'heads/master' et 'tags/master', vous pouvez explicitement dire 'heads/master' pour dire à Git auquel vous faîtes référence. Dans l'ambiguïté, un '<nom-de-réf>' est sélectionné en prenant la première correspondance avec les règles suivantes :
+
  . Si '$GIT_DIR/<refname>' existe, c'est ce que vous voulez dire (cela n'est généralement utile que pour `HEAD`, `FETCH_HEAD`, `ORIG_HEAD`, `MERGE_HEAD`, `REBASE_HEAD`, `REVERT_HEAD`, `CHERRY_PICK_HEAD`, `BISECT_HEAD` et `AUTO_MERGE`) ;

  . sinon, 'refs/<refname>' si cela existe ;

  . sinon, 'refs/tags/<refname>' si cela existe ;

  . sinon, 'refs/heads/<refname>' si cela existe ;

  . sinon, 'refs/remotes/<refname>' si cela existe ;

  . sinon, 'refs/remotes/<refname>/HEAD' si cela existe.

+
  `HEAD`:::
    nomme le commit sur lequel vous avez basé les changements dans l'arbre de travail.
  `FETCH_HEAD`:::
    enregistre la branche que vous avez récupérée depuis un dépôt distant avec
    votre dernière invocation de `git fetch`.
  `ORIG_HEAD`:::
    est créé par les commandes qui déplacent votre `HEAD` de façon radicale (`git
    am`, `git merge`, `git rebase`, `git reset`), pour enregistrer la position
    de `HEAD` avant leur opération, afin que vous puissiez facilement ramener
    le sommet de la branche à l'état avant de les avoir exécutées.
  `MERGE_HEAD`:::
    enregistre la ou les commits que vous fusionnez dans votre branche quand
    vous exécutez `git merge`.
  `REBASE_HEAD`:::
    pendant un rebasage, enregistre le commit à laquelle l'opération est
    currently arrêtée, soit à cause de conflits ou d'une commande `edit` dans
    un rebasage interactif.
  `REVERT_HEAD`:::
    enregistre le commit que vous annulez quand vous exécutez `git revert`.
  `CHERRY_PICK_HEAD`:::
    enregistre le commit que vous picorez quand vous exécutez `git
    cherry-pick`.
  `BISECT_HEAD`:::
    enregistre le commit courant à tester quand vous exécutez `git bisect
    --no-checkout`.
  `AUTO_MERGE`:::
    enregistre un objet arbre correspondant à l'état que la
    stratégie de fusion 'ort' a écrit dans l'arbre de travail quand une opération
    de fusion a résulté en des conflits.

+
Notez que n'importe lequel des cas 'refs/*' ci-dessus peut provenir soit du répertoire `$GIT_DIR/refs` soit du fichier `$GIT_DIR/packed-refs`. Bien que l'encodage du nom de référence ne soit pas spécifié, UTF-8 est préféré car certains traitements de sortie peuvent supposer que les noms de référence sont en UTF-8.

'@'::
  '@' seul est un raccourci pour `HEAD`.

'[<refname>]@{<date>}', p. ex. 'master@\{yesterday\}', 'HEAD@{5 minutes ago}'::
  Une référence suivie du suffixe '@' avec une spécification de date entre accolades (p. ex. '\{yesterday\}', '{1 month 2 weeks 3 days 1 hour 1 second ago}' ou '{1979-02-26 18:30:00}') spécifie la valeur de la référence à un moment antérieur. Ce suffixe ne peut être utilisé qu'immédiatement après un nom de référence et la référence doit avoir un journal existant ('$GIT_DIR/logs/<ref>'). Notez que cela recherche l'état de votre référence *locale* à un moment donné ; p. ex., ce qui était dans votre branche locale 'master' la semaine dernière. Si vous voulez examiner les commits effectuées à certaines périodes, voir `--since` et `--until`.

'<refname>@{<n>}', p. ex. 'master@\{1\}'::
  Une référence suivie du suffixe '@' avec une spécification ordinale entre accolades (p. ex. '\{1\}', '\{15\}') spécifie la n-ième valeur antérieure de cette référence. Par exemple 'master@\{1\}' est la valeur antérieure immédiate de 'master' tandis que 'master@\{5\}' est la 5ème valeur antérieure de 'master'. Ce suffixe ne peut être utilisé qu'immédiatement après un nom de référence et la référence doit avoir un journal existant ('$GIT_DIR/logs/<refname>').

'@{<n>}', p. ex. '@\{1\}'::
  Vous pouvez utiliser la construction '@' avec une partie référence vide pour accéder à une entrée du reflog de la branche courante. Par exemple, si vous êtes sur la branche 'blabla', alors '@\{1\}' signifie la même chose que 'blabla@\{1\}'.

'@{-<n>}', p. ex. '@{-1}'::
  La construction '@{-<n>}' désigne la <n>-ième branche/commit extrait avant la courante.

'[<nom-de-branche>]@\{upstream\}', p. ex. 'master@\{upstream\}', '@\{u\}'::
  Une branche B peut être configurée pour se construire par-dessus une branche X (configurée avec `branch.<name>.merge`) sur un distant R (configuré avec `branch.<name>.remote`). B@{u} fait référence à la branche de suivi distant pour la branche X prise depuis le distant R, généralement trouvée à `refs/remotes/R/X`.

'[<branche>]@\{push\}', par ex. 'master@\{push\}', '@\{push\}'::
  Le suffixe '@\{push}' indique la branche « où nous pousserions » si `git push` était exécuté pendant que `branche` est extraite (ou le `HEAD` courant si aucune branche n'est spécifiée). Comme pour '@\{upstream\}', nous signalons la branche de suivi distante qui correspond à cette branche sur le dépôt distant.
+
Voici un exemple pour clarifier :
+
------------------------------
$ git config push.default current
$ git config remote.pushdefault myfork
$ git switch -c mybranch origin/master

$ git rev-parse --symbolic-full-name @{upstream}
refs/remotes/origin/master

$ git rev-parse --symbolic-full-name @{push}
refs/remotes/myfork/mybranch
------------------------------
+
Notez dans l'exemple que nous avons mis en place un flux de travail triangulaire, où nous tirons depuis un emplacement et poussons vers un autre. Dans un flux de travail non triangulaire, '@\{push}' est identique à '@\{upstream}', et il n'est pas nécessaire.
+
Ce suffixe est également accepté en majuscules, et signifie la même chose quelle que soit la casse.

'<rev>{caret}[<n>]', par ex. 'HEAD{caret}, v1.5.1{caret}0'::
  Un suffixe '{caret}' après un paramètre de révision signifie le premier parent de cet objet commit. '{caret}<n>' signifie le <n>e parent (c.-à-d. '<rev>{caret}' est équivalent à '<rev>{caret}1'). Comme règle spéciale, '<rev>{caret}0' signifie le commit lui-même et est utilisé lorsque '<rev>' est le nom d'objet d'une étiquette qui pointe vers un objet commit.

'<rev>{tilde}[<n>]', par ex. 'HEAD{tilde}, master{tilde}3'::
  Un suffixe '{tilde}' après un paramètre de révision signifie le premier parent de cet objet commit. Un suffixe '{tilde}<n>' après un paramètre de révision signifie l'objet commit qui est l'ancêtre à la <n>e génération de l'objet commit nommé, en suivant uniquement les premiers parents. C.-à-d. '<rev>{tilde}3' est équivalent à '<rev>{caret}{caret}{caret}' qui est équivalent à '<rev>{caret}1{caret}1{caret}1'. Voir ci-dessous pour une illustration de l'utilisation de cette forme.

'<rev>{caret}{<type>}', par ex. 'v0.99.8{caret}\{commit\}'::
  Un suffixe '{caret}' suivi d'un nom de type d'objet encadré par des accolades signifie déréférencer l'objet à '<rev>' récursivement jusqu'à ce qu'un objet de type '<type>' soit trouvé ou que l'objet ne puisse plus être déréférencé (auquel cas, erreur). Par exemple, si '<rev>' est un commit-esque, '<rev>{caret}\{commit\}' décrit l'objet commit correspondant. De même, si '<rev>' est un arbre-esque, '<rev>{caret}\{tree\}' décrit l'objet arbre correspondant. '<rev>{caret}0' est un raccourci pour '<rev>{caret}\{commit\}'.
+
'<rev>{caret}\{object\}' peut être utilisé pour s'assurer que '<rev>' nomme un objet existant, sans exiger que '<rev>' soit une étiquette, et sans déréférencer '<rev>' ; car une étiquette est déjà un objet, elle n'a pas besoin d'être déréférencée même une fois pour obtenir un objet.
+
'<rev>{caret}\{tag\}' peut être utilisé pour s'assurer que '<rev>' identifie une étiquette existante.

'<rev>{caret}{}', par ex. 'v0.99.8{caret}{}'::
  Un suffixe '{caret}' suivi d'une paire d'accolades vide signifie que l'objet pourrait être une étiquette, et déréférencer l'étiquette récursivement jusqu'à ce qu'un objet non-étiquette soit trouvé.

'<rev>{caret}{/<texte>}', par ex. 'HEAD^{/fix nasty bug}'::
  Un suffixe '{caret}' après un paramètre de révision, suivi d'une paire d'accolades contenant un texte précédé d'une barre oblique, est identique à la syntaxe ':/fix nasty bug' ci-dessous sauf qu'il retourne le commit correspondant le plus récent qui est atteignable depuis le '<rev>' avant '{caret}'.

':/<texte>', par ex. ':/fix nasty bug'::
  Deux-points, suivi d'une barre oblique, suivi d'un texte, nomme un commit dont le message de validation correspond à l'expression régulière spécifiée. Ce nom retourne le commit correspondant le plus récent qui est atteignable depuis n'importe quelle référence, y compris HEAD. L'expression régulière peut correspondre à n'importe quelle partie du message de validation. Pour correspondre aux messages commençant par une chaîne, on peut utiliser par ex. ':/^foo'. La séquence spéciale ':/!' est réservée aux modificateurs de la correspondance. ':/!-foo' effectue une correspondance négative, tandis que ':/!!foo' correspond au caractère littéral '!' suivi de 'foo'. Toute autre séquence commençant par ':/!' est réservée pour le moment. Selon le texte donné, les règles de séparation de mots du shell peuvent nécessiter des guillemets supplémentaires.

'<rev>:<chemin>', par ex. 'HEAD:README', 'master:./README'::
  Un suffixe ':' suivi d'un chemin nomme le blob ou l'arbre au chemin donné dans l'objet arbre-esque nommé par la partie avant les deux-points. Un chemin commençant par './' ou '../' est relatif au répertoire de travail courant. Le chemin donné sera converti pour être relatif au répertoire racine de l'arbre de travail. C'est principalement utile pour adresser un blob ou un arbre depuis un commit ou un arbre qui a la même structure d'arbre que l'arbre de travail.

':[<n>:]<chemin>', par ex. ':0:README', ':README'::
  Deux-points, optionnellement suivis d'un numéro d'étape (0 à 3) et deux-points, suivis d'un chemin, nomme un objet blob dans l'index au chemin donné. Un numéro d'étape manquant (et les deux-points qui le suivent) nomme une entrée d'étape 0. Pendant une fusion, l'étape 1 est l'ancêtre commun, l'étape 2 est la version de la branche cible (généralement la branche courante), et l'étape 3 est la version de la branche en cours de fusion.

Voici une illustration de Jon Loeliger. Les deux nœuds de commit B et C sont des parents du nœud de commit A. Les commits parents sont ordonnés de gauche à droite.

........................................
G   H   I   J
 \ /     \ /
  D   E   F
   \  |  / \
    \ | /   |
     \|/    |
      B     C
       \   /
        \ /
         A
........................................

    A =      = A^0
    B = A^   = A^1     = A~1
    C =      = A^2
    D = A^^  = A^1^1   = A~2
    E = B^2  = A^^2
    F = B^3  = A^^3
    G = A^^^ = A^1^1^1 = A~3
    H = D^2  = B^^2    = A^^^2  = A~2^2
    I = F^   = B^3^    = A^^3^
    J = F^2  = B^3^2   = A^^3^2


SPÉCIFICATION DE PLAGES
-----------------------

Les commandes de parcours d'historique telles que `git log` opèrent sur un ensemble de commits, pas sur un seul commit.

Pour ces commandes, spécifier une seule révision, en utilisant la notation décrite dans la section précédente, signifie l'ensemble des commits `atteignables` depuis le commit donné.

Spécifier plusieurs révisions signifie l'ensemble de commits accessibles à partir de l'un des commits donnés.

L'ensemble atteignable d'un commit est le commit lui-même et les commits dans sa chaîne d'ascendance.

Il existe plusieurs notations pour spécifier un ensemble de commits connectés (appelé « intervalle de révisions »), illustrées ci-dessous.


Exclusions de commits
~~~~~~~~~~~~~~~~~~~~~

Notation '{caret}<rev>' (accent circonflexe)::
 Pour exclure les commits atteignables depuis un commit, une notation préfixe '{caret}' est utilisée. Par ex. '{caret}r1 r2' signifie les commits atteignables depuis 'r2' mais excluant ceux atteignables depuis 'r1' (c.-à-d. 'r1' et ses ancêtres).

Notations d'intervalles pointillés
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

La notation d'intervalle '..' (deux points)::
 L'opération d'ensemble '{caret}r1 r2' apparaît si souvent qu'il existe un raccourci. Lorsque vous avez deux commits 'r1' et 'r2' (nommés selon la syntaxe expliquée dans SPÉCIFICATION DES RÉVISIONS ci-dessus), vous pouvez demander les commits atteignables depuis r2 en excluant ceux atteignables depuis r1 avec '{caret}r1 r2' et cela peut s'écrire 'r1..r2'.

La notation de différence symétrique '\...' (trois points)::
 Une notation similaire 'r1\...r2' est appelée différence symétrique de 'r1' et 'r2' et est définie comme 'r1 r2 --not $(git merge-base --all r1 r2)'. C'est l'ensemble des commits atteignables depuis l'un des deux 'r1' (côté gauche) ou 'r2' (côté droit) mais pas depuis les deux.

Dans ces deux notations abrégées, vous pouvez omettre une extrémité et la laisser par défaut à HEAD. Par exemple, 'origin..' est un raccourci pour 'origin..HEAD' et demande « Qu'ai-je fait depuis que j'ai forké depuis la branche origin ? ». De même, '..origin' est un raccourci pour 'HEAD..origin' et demande « Qu'a fait l'origine depuis que j'ai forké depuis eux ? ». Notez que '..' signifierait 'HEAD..HEAD' qui est un intervalle vide à la fois atteignable et inatteignable depuis HEAD.

Les commandes spécifiquement conçues pour prendre deux intervalles distincts (par ex. « git range-diff R1 R2 » pour comparer deux intervalles) existent, mais ce sont des exceptions. Sauf indication contraire, toutes les commandes « git » qui opèrent sur un ensemble de commits fonctionnent sur un seul intervalle de révisions. En d'autres mots, écrire deux « notations d'intervalle à deux points » côte à côte, par ex.

    $ git log A..B C..D

ne spécifie *pas* deux intervalles de révisions pour la plupart des commandes. Au lieu de cela, il nommera un seul ensemble connecté de commits, c.-à-d. ceux qui sont atteignables depuis B ou D mais qui ne sont atteignables ni depuis A ni depuis C. Dans un historique linéaire comme celui-ci :

    ---A---B---o---o---C---D

car A et B sont atteignables depuis C, l'intervalle de révisions spécifié par ces deux intervalles pointillés est un seul commit D.


Autres notations abrégées <rev>{caret} Parent
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Trois autres raccourcis existent, particulièrement utiles pour les commits de fusion, pour nommer un ensemble formé par un commit et ses commits parents.

La notation 'r1{caret}@' signifie tous les parents de 'r1'.

La notation 'r1{caret}!' inclut le commit 'r1' mais exclut tous ses parents. À elle seule, cette notation désigne le commit unique 'r1'.

La notation '<rev>{caret}-[<n>]' inclut '<rev>' mais exclut le <n>e parent (c.-à-d. un raccourci pour '<rev>{caret}<n>..<rev>'), avec '<n>' = 1 si non spécifié. C'est typiquement utile pour les commits de fusion où vous pouvez simplement passer '<commit>{caret}-' pour obtenir tous les commits de la branche qui a été fusionnée dans le commit de fusion '<commit>' (y compris '<commit>' lui-même).

Alors que '<rev>{caret}<n>' concernait la spécification d'un seul commit parent, ces trois notations considèrent également ses parents. Par exemple, vous pouvez dire 'HEAD{caret}2{caret}@', cependant vous ne pouvez pas dire 'HEAD{caret}@{caret}2'.

Résumé des intervalles de révisions
-----------------------------------

'<rev>'::
	Inclure les commits atteignables depuis <rev> (c.-à-d. <rev> et ses ancêtres).

'{caret}<rev>'::
	Exclure les commits atteignables depuis <rev> (c.-à-d. <rev> et ses ancêtres).

<rév1>..<rév2>::
	Inclure les commits atteignables depuis <rev2> mais exclure ceux atteignables depuis <rev1>. Lorsque <rev1> ou <rev2> est omis, la valeur par défaut est `HEAD`.

<rév1>\...<rév2>::
	Inclure les commits atteignables depuis <rev1> ou <rev2> mais exclure ceux atteignables depuis les deux. Lorsque <rev1> ou <rev2> est omis, la valeur par défaut est `HEAD`.

'<rev>{caret}@', par ex. 'HEAD{caret}@'::
  Un suffixe '{caret}' suivi d'un arobase est identique à lister tous les parents de '<rev>' (c.-à-d. inclure tout ce qui est atteignable depuis ses parents, mais pas le commit lui-même).

'<rev>{caret}!', par ex. 'HEAD{caret}!'::
  Un suffixe '{caret}' suivi d'un point d'exclamation est identique à donner le commit '<rev>' et tous ses parents préfixés avec '{caret}' pour les exclure (et leurs ancêtres).

'<rev>{caret}-<n>', par ex. 'HEAD{caret}-, HEAD{caret}-2'::
	Équivalent à '<rev>{caret}<n>..<rev>', avec '<n>' = 1 si non spécifié.

Voici quelques exemples utilisant l'illustration de Loeliger ci-dessus, avec chaque étape de l'expansion et de la sélection de la notation soigneusement détaillée :

....
   Args   Expanded arguments    Selected commits
   D                            G H D
   D F                          G H I J D F
   ^G D                         H D
   ^D B                         E I J F B
   ^D B C                       E I J F B C
   C                            I J F C
   B..C   = ^B C                C
   B...C  = B ^F C              G H D E B C
   B^-    = B^..B
	  = ^B^1 B              E I J F B
   C^@    = C^1
	  = F                   I J F
   B^@    = B^1 B^2 B^3
	  = D E F               D G H E F I J
   C^!    = C ^C^@
	  = C ^C^1
	  = C ^F                C
   B^!    = B ^B^@
	  = B ^B^1 ^B^2 ^B^3
	  = B ^D ^E ^F          B
   F^! D  = F ^I ^J D           G H D F
....
