include::urls.adoc[]

DISTANTS[[REMOTES]]
-------------------

Le nom de l'un des éléments suivants peut être utilisé à la place d'une URL en tant qu'argument _<dépôt>_ :

* un distant dans le fichier de configuration Git : `$GIT_DIR/config`,
* un fichier dans le répertoire `$GIT_DIR/remotes`, ou
* un fichier dans le répertoire `$GIT_DIR/branches`.

Toutes ces options vous permettent également d'omettre le spécificateur de référence de la ligne de commande car elles contiennent chacune un spécificateur de référence que git utilisera par défaut.

distant nommé dans le fichier de configuration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vous pouvez choisir de fournir le nom d'un distant que vous aviez précédemment configuré en utilisant linkgit:git-remote[1], linkgit:git-config[1] ou même par une modification manuelle du fichier `$GIT_DIR/config`. L'URL de ce distant sera utilisée pour accéder au dépôt. Le spécificateur de référence de ce distant sera utilisé par défaut lorsque vous ne fournissez pas de spécificateur de référence sur la ligne de commande. L'entrée dans le fichier de configuration apparaîtra comme ceci :

------------
	[remote "<nom>"]
		url = <URL>
		pushurl = <url-poussée>
		push = <spéc-de-réf>
		fetch = <spéc-de-réf>
------------

L' _<url-de-poussée>_ est utilisé uniquement pour les poussées. Il est optionnel et sa valeur par défaut est _<URL>_. Pousser vers un distant affecte tous les urls-de-poussés définis ou tous les urls définis si aucun url-de-poussée n'est défini. Fetch, cependant, ne récupérera que le premier url défini si plusieurs urls sont définis.

Fichier nommé dans `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vous pouvez choisir de fournir le nom d'un fichier dans `$GIT_DIR/remotes`. L'URL dans ce fichier sera utilisée pour accéder au dépôt. Le spécificateur de référence dans ce fichier sera utilisé par défaut lorsque vous ne fournissez pas de spécificateur de référence sur la ligne de commande. Ce fichier doit avoir le format suivant :

------------
	URL: un des format d'URL ci-dessus
	Push: <spéc-de-réf>
	Pull: <spéc-de-réf>

------------

Les lignes `Push:`" sont utilisées par `git push` et les lignes `Pull:` sont utilisées par `git pull` et `git fetch`. Des lignes `Push:` et `Pull:` multiples peuvent être spécifiées pour des mappages supplémentaires de branches.

Fichier nommé dans `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vous pouvez choisir de fournir le nom d'un fichier dans `$GIT_DIR/branches`. L'URL de ce fichier sera utilisée pour accéder au dépôt. Ce fichier doit avoir le format suivant :


------------
	<URL>#<tête>
------------

_<URL>_ est obligatoire ; `#<tête>` est facultatif.

En fonction de l'opération, git utilisera l'un des spécificateurs de référence suivants, si vous n'en fournissez pas un en ligne de commande. _<branche>_ est le nom de ce fichier dans `$GIT_DIR/branches` et _<tête>_ vaut par défaut `master`.

git fetch utilise :

------------
	refs/heads/<tête>:refs/heads/<branche>
------------

git push utilise :

------------
	HEAD:refs/heads/<tête>
------------


[[UPSTREAM-BRANCHES]]
BRANCHES AMONT
--------------

Les branches de Git peuvent en option avoir une branche distante en amont. Git par défaut d'utiliser la branche amont pour les opérations à distance, par exemple :

* C'est le comportement par défaut pour `git pull` ou `git fetch` sans argument.
* C'est le comportement par défaut pour `git push` sans argument, à quelques exceptions près. Par exemple, vous pouvez utiliser l'option `branch. <nom>.pushRemote` pour pousser vers une autre télécommande que vous tirez, et par défaut avec `push.default=simple` la branche amont que vous configurez doit avoir le même nom.
* Différentes commandes, y compris `git checkout` et le statut `git status` vous montreront combien de commits ont été ajoutés à votre branche actuelle et l'amont depuis que vous en avez divergé, par exemple «Votre branche et 'origin/main' ont divergé, et ont respectivement 2 et 3 commits différents».

L'amont est stocké dans `.git/config`, dans les champs `remote` et `merge`. Par exemple, si le `main` de l'amont est `origin/main` :

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Vous pouvez configurer une branche amont explicitement avec `git push --set-upstream <distant> < branche>` mais Git configurera souvent automatiquement l'amont pour vous, par exemple :

* Lorsque vous clonez un dépôt, Git configurera automatiquement l'amont de la branche par défaut.
* Si vous activez la configuration `push.autoSetupRemote`, `git push` va automatiquement configurer l'amont la première fois que vous poussez une branche.
* Extraire une branche de suivi à distance avec `git checkout <branche>` créera automatiquement une branche locale avec ce nom et configurera l'amont vers la branche distante.

[NOTE]
Les branches amont sont parfois appelées « information de suivi «, comme dans « indiquer l'information de suivi de la branche ».
