rebase.backend::
	Le backend par défaut à utiliser pour le rebasage. Les choix possibles sont 'apply' ou 'merge'. À l'avenir, si le backend de fusion gagne toutes les capacités restantes du backend, ce paramètre peut devenir inutilisé.

rebase.stat::
	S'il faut afficher un diffstat de ce qui a changé en amont depuis le dernier rebasage. Par défaut à false.

rebase.autoSquash::
	Si réglé à true, activer l'option `--autosquash` de linkgit:git-rebase[1] par défaut pour le mode interactif. Cela peut être surchargé par l'option `--no-autosquash`.

rebase.autoStash::
	Lorsque réglé sur `true`, créer automatiquement une entrée temporaire de remisage avant le début de l'opération, et l'appliquer après la fin de l'opération. Cela signifie que vous pouvez rebaser sur un arbre de travail sale. Cependant, à utiliser avec précaution : l'application finale du remisage après un rebasage peut entraîner des conflits non négligeables. Cette option peut être remplacée par les options `--no-autostash` et `--autostash` de linkgit:git-rebase[1]. La valeur par défaut est `false`.

rebase.updateRefs::
	Si défini à true, active l'option `--update-refs` par défaut.

rebase.missingCommitsCheck::
	Si réglé à "warn", git rebase -i affichera un avertissement si certains commits sont supprimés (par exemple une ligne a été supprimée), cependant le rebasage va continuer. S'il est défini à "error", il affichera l'avertissement précédent et arrêtera le rebasage, 'git rebase --edit-todo' peut ensuite être utilisé pour corriger l'erreur. S'il est défini à "ignore", aucun contrôle n'est fait. Pour abandonner un commit sans avertissement ni erreur, utilisez la commande `drop` dans la liste de todo. Par défaut à "ignore".

rebase.instructionFormat::
	Une chaîne de format, comme spécifié dans linkgit:git-log[1], à utiliser pour la liste de todo lors d'un rebasage interactif. Le format aura automatiquement l'empreinte de commit préfixé au format.

rebase.abbreviateCommands::
	Si réglé à true, `git rebase` utilisera des noms de commande abrégés dans la liste de todo qui en résultent :
+
-------------------------------------------
	p deadbee Le titre de ce commit
p fa1afe1 Le titre du commit suivant
...
-------------------------------------------
+
au lieu de :
+
-------------------------------------------
	pick deadbee Le titre de ce commit
	pick fa1afe1 Le titre du commit suivant
	...
-------------------------------------------
+
Vaut par défaut `false`.

rebase.rescheduleFailedExec::
	Reprogrammer automatiquement les commandes `exec` qui ont échoué. Cela n'a de sens qu'en mode interactif (ou lorsqu'une option `--exec` a été fournie). C'est la même chose que de spécifier l'option `--reschedule-failed-exec`.

rebase.forkPoint::
	Si défini à false, régler l'option `--no-fork-point` par défaut.

rebase.rebaseMerges::
	Si et comment définir l'option `--rebase-merges` par défaut. Peut être `rebase-cousins`, `non-rebase-cousins`, ou un booléen. La régler à true ou à `no-rebase-cousins` est équivalent à `--rebase-merges=no-rebase-cousins`, la régler à `rebase-cousins` est équivalent à `--rebase-merges=rebase-cousins`, et la régler à false est équivalent à `--no-rebase-merges`. Passer `--rebase-merges` sur la ligne de commande, avec ou sans argument, annule toute configuration `rebase.rebaseMerges`.

rebase.maxLabelLength::
	Lors de la génération de noms à partir de sujets de commit, tronquer les noms à cette longueur. Par défaut, les noms sont tronqués à un peu moins que `NAME_MAX` (pour permettre par exemple d'écrire des fichiers `.lock` pour les réfs esseulées correspondantes).
