DATUMFORMAT
-----------

Miljövariablerna `GIT_AUTHOR_DATE` och `GIT_COMMITTER_DATE` stöder följande datumformat:

Git internt format::
	Det är `<unix-timestamp> <time-zone-offset>`, där `<unix-timestamp>` är antalet sekunder sedan UNIX-epoken. `<time-zone-offset>` är en positiv eller negativ förskjutning från UTC. Till exempel är CET (som är 1 timme före UTC) `+0100`.

RFC 2822::
	Standarddatumformatet som beskrivs av RFC 2822, till exempel `Tor, 07 Apr 2005 22:13:13 +0200`.

ISO 8601::
	Tid och datum som anges av ISO 8601-standarden, till exempel `2005-04-07T22:13:13`. Parsern accepterar även ett mellanslag istället för tecknet `T`. Bråkdelar av en sekund kommer att ignoreras, till exempel `2005-04-07T22:13:13.019` kommer att behandlas som `2005-04-07T22:13:13`.
+
NOTE: Dessutom accepteras datumdelen i följande format: `ÅÅÅÅ.MM.DD`, `MM/DD/ÅÅÅÅ` och `DD.MM.ÅÅÅÅ`.

ifdef::git-commit[]
Förutom att känna igen alla datumformat ovan, kommer alternativet `--date` också att försöka förstå andra, mer människocentrerade datumformat, såsom relativa datum som "yesterday" (igår) eller "yesterday" (förra fredagen vid middagstid).
endif::git-commit[]
