git-web{litdd}browse(1)
=======================

NAMN
----
git-web--browse - Git-hjälpskript för att starta en webbläsare

SYNOPSIS
--------
[verse]
'git web{litdd}browse' [<flaggor>] (<URL>|<fil>)...

BESKRIVNING
-----------

Det här skriptet försöker, så mycket som möjligt, visa URL:er och FILER som skickas som argument, som HTML-sidor i nya flikar i en redan öppen webbläsare.

Följande webbläsare (eller kommandon) stöds för närvarande:

* firefox (detta är standardinställningen i X Window när KDE inte används)
* iceweasel
* seamonkey
* iceape
* chromium (stöds även som chromium-browser)
* Google Chrome (stöds även som Chrome)
* konqueror (detta är standardinställningen i KDE, se 'Anmärkning om konqueror' nedan)
* opera
* w3m (detta är standardinställningen utanför grafiska miljöer)
* elinks
* links
* lynx
* dillo
* open (detta är standardinställningen i Mac OS X GUI)
* start (detta är standardinställningen under MinGW)
* cygstart (detta är standardinställningen under Cygwin)
* xdg-open

Anpassade kommandon kan också anges.

ALTERNATIV
----------
-b <webläsare>::
--browser=<webläsare>::
	Använd den angivna webbläsaren. Den måste finnas med i listan över webbläsare som stöds.

-t <webbläsare>::
--tool=<webbläsare>::
	Samma som ovan.

-c <conf.var>::
--config=<conf.var>::
	CONF.VAR söks upp i Git-konfigurationsfilerna. Om det är angivet anger dess värde vilken webbläsare som ska användas.

KONFIGURATIONSVARIABLER
-----------------------

CONF.VAR (från alternativet -c) och web.browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Webbläsaren kan anges med hjälp av en konfigurationsvariabel som skickas med kommandoradsalternativet -c (eller --config), eller konfigurationsvariabeln `web.browser` om den förra inte används.

browser.<verktyg>.path
~~~~~~~~~~~~~~~~~~~~~~

Du kan explicit ange en fullständig sökväg till din föredragna webbläsare genom att ställa in konfigurationsvariabeln `browser.<verktyg>.path`. Du kan till exempel konfigurera den absoluta sökvägen till Firefox genom att ställa in 'browser.firefox.path'. Annars antar 'git web{litdd}browse' att verktyget är tillgängligt i PATH.

browser.<verktyg>.cmd
~~~~~~~~~~~~~~~~~~~~~

När webbläsaren, som anges av alternativ eller konfigurationsvariabler, inte finns bland de som stöds, kommer motsvarande konfigurationsvariabel `browser.<verktyg>.cmd` att sökas upp. Om variabeln finns kommer 'git web{litdd}browse' att behandla det angivna verktyget som ett anpassat kommando och använda skaltolkning för att köra kommandot med URL:erna som skickas som argument.

OBS OM KONQUEROR
----------------

När 'konqueror' anges av ett kommandoradsalternativ eller en konfigurationsvariabel, startar vi 'kfmclient' för att försöka öppna HTML-manualsidan på en redan öppen Konqueror i en ny flik om möjligt.

För konsekvensens skull provar vi också ett sådant knep om 'browser.konqueror.path' är satt till något i stil med `EN_SÖKVÄG_TILL/konqueror`. Det betyder att vi kommer att försöka starta `EN_SÖKVÄG_TILL/kfmclient` i stället.

Om du verkligen vill använda 'konqueror' kan du använda något i stil med följande:

------------------------------------------------
	[web]
		browser = konq

	[browser "konq"]
		cmd = EN_SÖKVÄG_TILL/konqueror
------------------------------------------------

Anmärkning om git-config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Observera att dessa konfigurationsvariabler förmodligen bör ställas in med flaggan `--global`, till exempel så här:

------------------------------------------------
$ git config --global web.browser firefox
------------------------------------------------

eftersom de förmodligen är mer användarspecifika än kodförrådsspecifika. Se linkgit:git-config[1] för mer information om detta.

GIT
---
En del av linkgit:git[1]-sviten
