git-cvsexportcommit(1)
======================

NAMN
----
git-cvsexportcommit - Exportera en enda incheckning till en CVS-utcheckning


SYNOPSIS
--------
[verse]
'git cvsexportcommit' [-h] [-u] [-v] [-c] [-P] [-p] [-a] [-d <cvsrot>]
	[-w <cvs-workdir>] [-W] [-f] [-m <meddprefix>] [<förälder-incheckning>] <inchecknings-id>


BESKRIVNING
-----------
Exporterar en incheckning från Git till en CVS-utcheckning, vilket gör det enklare att sammanfoga patchar från ett Git-kodförråd till ett CVS-kodförråd.

Ange namnet på en CVS-utcheckning med hjälp av -w-växeln eller kör den från roten av CVS-arbetskopian. I det senare fallet måste GIT_DIR definieras. Se exempel nedan.

Den gör sitt bästa för att göra det säkra, den kommer att kontrollera att filerna är oförändrade och uppdaterade i CVS-utcheckningen, och den kommer inte göra auto-inchecking som standard.

Stöder filtillägg, borttagningar och incheckningar som påverkar binära filer.

Om incheckningen är en sammanslagings-incheckning måste du ange för 'git cvsexportcommit' vilken förälder som ändringsset ska göras mot.

ALTERNATIV
----------

-c::
	Automatisk incheckning om patchen applicerades korrekt. Den kommer inte att checka-in om några stycken inte applicerades eller om det uppstod andra problem.

-p::
	Var pedantisk (paranoid) när du applicerar patchar. Anropar patch med --fuzz=0

-a::
	Lägger till författarinformation. Lägger till författarrad och incheckare (om annan än författaren) i meddelandet.

-d::
	Ställ in en alternativ CVSROOT att använda. Detta motsvarar parametern CVS -d. Vanligtvis vill användare inte ställa in detta, förutom om de använder CVS på ett asymmetriskt sätt.

-f::
	Tvinga fram sammanslagningen även om filerna inte är uppdaterade.

-P::
	Tvinga förälder incheckningen, även om det inte är en direkt förälder.

-m::
	Lägg till det angivna prefixet före inchecknings-meddelandet. Användbart för patch-serier och liknande.

-u::
	Uppdatera berörda filer från CVS-arkivet innan du försöker exportera.

-k::
	Omvänd CVS-nyckelordsexpansion (t.ex. $Revision: 1.2.3.4$ blir $Revision$) i fungerande CVS-utcheckning innan patchen appliceras.

-w::
	Ange platsen för CVS-utcheckningen som ska användas för exporten. Det här alternativet kräver inte att GIT_DIR anges före körning om den aktuella katalogen finns i ett Git-arkiv. Standardvärdet är 'cvsexportcommit.cvsdir'.

-W::
	Berätta för cvsexportcommit att den aktuella arbetskatalogen inte bara är en Git-utcheckning, utan även en CVS-utcheckning. Därför kommer Git att återställa arbetskatalogen till den överordnade incheckningen innan den fortsätter.

-v::
	Pratsam.

KONFIGURATION
-------------
cvsexportcommit.cvsdir::
	Standardplatsen för CVS-utcheckningen som ska användas för exporten.

EXEMPEL
-------

Sammanslå en patch i CVS::
+
------------
$ export GIT_DIR=~/projekt/.git
$ cd ~/projekt_cvs_utchecking
$ git cvsexportcommit -v <inchecknings-sha1>
$ cvs commit -F .msg <filer>
------------

Sammanfoga en patch i CVS (alternativen -c och -w). Arbetskatalogen finns i Git-kodförrådet::
+
------------
	$ git cvsexportcommit -v -c -w ~/project_cvs_checkout <incheckningsssss-sha1>
------------

Sammanfoga väntande patchar till CVS automatiskt -- bara om du verkligen vet vad du gör::
+
------------
$ export GIT_DIR=~/projekt/.git
$ cd ~/projekt_cvs_untchecking
$ git cherry cvshead mitthuvud | sed -n 's/^+ //p' | xargs -l1 git cvsexportcommit -c -p -v
------------

GIT
---
En del av linkgit:git[1]-sviten
