git-request-pull(1)
===================

NAMN
----
git-request-pull - Genererar en sammanfattning av väntande ändringar

SYNOPSIS
--------
[verse]
'git request-pull' [-p] <start> <URL> [<slut>]

BESKRIVNING
-----------

Generera en begäran som ber ditt uppströmsprojekt att hämta ändringar till sitt träd. Begäran, som skrivs ut som standardutdata, börjar med grenbeskrivningen, sammanfattar ändringarna och anger varifrån de kan hämtas.

Uppströmsprojektet förväntas ha incheckningen namngiven `<start>` och utdata ber det att integrera de ändringar du gjort sedan den incheckningen, upp till incheckningen namngiven `<slut>`, genom att besöka kodförrådet namngivet `<URL>`.


ALTERNATIV
----------
-p::
	Inkludera patchtext i utdata.

<start>::
	Incheckning att börja med. Detta namnger en incheckning som redan finns i uppströmshistoriken.

<URL>::
	URL:en för kodförrådet som ska hämtas från.

<slut>::
	Incheckning att sluta vid (standardinställningen är HEAD). Detta namnger incheckningen i slutet av historiken som du begär ska hämtas.
+
När kodförrådet som namnges av `<URL>` har incheckningen i toppen för en referens som skiljer sig från den referens du har lokalt, kan du använda syntaxen `<lokal>:<fjärr>` för att få dess lokala namn, ett kolon `:` och dess fjärrnamn.


EXEMPEL
-------

Tänk dig att du byggde ditt arbete på din `master`-gren ovanpå `v1.0`-utgåvan och vill att den ska integreras i projektet. Först publicerar du den ändringen till ditt publika kodförråd så att andra kan se den:

	git push https://git.ko.xz/projekt master

Sedan kör du det här kommandot:

	git request-pull v1.0 https://git.ko.xz/projekt master

vilket kommer att generera en begäran till uppströmsen, som sammanfattar ändringarna mellan `v1.0`-utgåvan och din `master`, att hämta den från ditt publika kodförråd.

Om du skickade din ändring till en gren vars namn skiljer sig från det du har lokalt, t.ex.

	git push https://git.ko.xz/projekt master:for-linus

då kan du be att det tas bort med

	git request-pull v1.0 https://git.ko.xz/projekt master:for-linus


GIT
---
En del av linkgit:git[1]-sviten
