git-mailsplit(1)
================

NAMN
----
git-mailsplit - Enkelt UNIX mbox-delningsprogram

SYNOPSIS
--------
[verse]
'git mailsplit' [-b] [-f<nn>] [-d<prec>] [--keep-cr] [--mboxrd]
		-o<katalog> [--] [(<mbox>|<Maildir>)...]

BESKRIVNING
-----------
Delar upp en mbox-fil eller en Maildir i en lista med filer: "0001" "0002" .. i den angivna katalogen så att du kan bearbeta dem vidare därifrån.

IMPORTANT: Maildir-delning är beroende av att filnamn sorteras för att mata ut patchar i rätt ordning.

ALTERNATIV
----------
<mbox>::
	Mbox-fil att dela. Om ingen given fil anges läses mbox-filen från standardindata.

<Maildir>::
	Rotkatalogen för den e-postkatalog som ska delas. Den här katalogen ska innehålla underkatalogerna cur, tmp och new.

-o<katalog>::
	Katalog där de enskilda meddelandena ska placeras.

-b::
	Om någon fil inte börjar med en Från-rad, anta att det är ett enda e-postmeddelande istället för att signalera ett fel.

-d<prec>::
	Istället för standardvärdet 4 siffror med inledande nollor kan olika precision anges för de genererade filnamnen.

-f<nn>::
	Hoppa över de första <nn> siffrorna, till exempel om -f3 anges, börja numreringen med 0004.

--keep-cr::
	Ta inte bort `\r` från rader som slutar med `\r\n`.

--mboxrd::
	Inmatningen är i formatet "mboxrd" och radkoderna "^>+From" är omvända.

GIT
---
En del av linkgit:git[1]-sviten
