git-fetch-pack(1)
=================

NAMN
----
git-fetch-pack - Ta emot saknade objekt från ett annat kodförråd


SYNOPSIS
--------
[verse]
'git fetch-pack' [--all] [--quiet|-q] [--keep|-k] [--thin] [--include-tag]
	[--upload-pack=<git-upload-pack>]
	[--depth=<n>] [--no-progress]
	[-v] <repository> [<refs>...]

BESKRIVNING
-----------
Vanligtvis används i stället 'git fetch', som är ett högnivåomslag för kommandot.

Anropar 'git-upload-pack' på ett eventuellt fjärrkodförråd och ber den att skicka objekt som saknas i detta kodförråd för att uppdatera de namngivna huvudena. Listan över incheckningar som är tillgängliga lokalt tas fram genom att skanna den lokala refs/hierarkin och skickas till 'git-upload-pack' som körs i andra änden.

Kommandot övergår i praktiken till att hämta allt som krävs för att komplettera de begärda referenserna från fjärrsidan när den lokala sidan saknar en gemensam förfaderincheckning.


ALTERNATIV
----------
--all::
	Hämta alla fjärrreferenser.

--stdin::
	Ta listan med referenser från stdin, en per rad. Om det finns referenser angivna på kommandoraden utöver detta alternativ, bearbetas referenserna från stdin efter de på kommandoraden.
+
Om `--stateless-rpc` anges tillsammans med detta alternativ måste listan över referenser vara i paketformat (pkt-line). Varje referens måste finnas i ett separat paket, och listan måste avslutas med ett tömningspaket.

-q::
--quiet::
	Skicka flaggan `-q` till 'git unpack-objects'; detta gör kloningsprocessen mindre utförlig.

-k::
--keep::
	Anropa inte 'git unpack-objects' på mottagen data, utan skapa i stället en enda packfil av den och lagra den i objektdatabasen. Om den anges två gånger är paketet låst mot ompackning.

--thin::
	Hämta ett "tunt" paket, som registrerar objekt i deltakodad form baserat på objekt som inte ingår i paketet för att minska nätverkstrafiken.

--include-tag::
	Om fjärrsidan stöder det, kommer annoterade taggobjekt att laddas ner på samma anslutning som de andra objekten om objektet som taggen refererar till laddas ner. Anroparen måste annars bestämma vilka taggar som detta alternativ gjorde tillgängliga.

--upload-pack=<git-upload-pack>::
	Använd detta för att ange sökvägen till 'git-upload-pack' på fjärrsidan, om den inte hittas på din $PATH. Installationer av sshd ignorerar användarens miljöskript för inloggningsshell (t.ex. .bash_profile) och din privat installerade git kanske inte hittas på systemets standard $PATH. En annan föreslagen lösning är att konfigurera din $PATH i ".bashrc", men den här flaggan är för personer som inte vill betala omkostnaderna för icke-interaktiva skal genom att ha en smal .bashrc-fil (de konfigurerar det mesta i .bash_profile).

--exec=<git-upload-pack>::
	Same as --upload-pack=<git-upload-pack>.

--depth=<n>::
	Begränsa hämtning till förfaderkedjor som inte är längre än n. 'git-upload-pack' behandlar det speciella djupet 2147483647 som oändligt även om det finns en förfaderkedja som är så lång.

--shallow-since=<datum>::
	Fördjupa eller förkorta historiken för ett ytligt kodförråd för att inkludera alla nåbara incheckningar efter <datum>.

--shallow-exclude=<ref>::
	Fördjupa eller förkorta historiken för ett ytligt kodförråd för att exkludera incheckningar som är åtkomliga från en specifik fjärrgren eller tagg. Det här alternativet kan anges flera gånger.

--deepen-relative::
	Argumentet --depth anger antalet incheckningar från den aktuella ytliga gränsen i stället för från toppen av varje fjärrgrenhistorik.

--refetch::
	Hoppar över förhandlingar om incheckningar med servern för att hämta alla matchande objekt. Används för att återanvända ett nytt partiellt klon-blob/trädfilter.

--no-progress::
	Visa inte framstegen.

--check-self-contained-and-connected::
	Utdata "anslutning-ok" om det mottagna paketet är sluten och anslutet.

-v::
	Kör utförligt.

<kodförråd>::
	URL:en till fjärrkodförråd.

<refs>...::
	Fjärrhuvuden att uppdatera från. Detta är relativt till $GIT_DIR (t.ex. "HEAD", "refs/heads/master"). Om inget anges uppdateras från alla huvuden som fjärrsidan har.
+
Om fjärrsidan har aktiverat alternativen `uploadpack.allowTipSHA1InWant`, `uploadpack.allowReachableSHA1InWant` eller `uploadpack.allowAnySHA1InWant`, kan de alternativt vara 40-hex sha1-värden som finns på fjärrsidan.

SE ÄVEN
-------
linkgit:git-fetch[1]

GIT
---
En del av linkgit:git[1]-sviten
