git-gui(1)
==========

NAMN
----
git-gui - Ett portabelt grafiskt gränssnitt för Git

SYNOPSIS
--------
[verse]
'git gui' [<kommando>] [<argument>]

BESKRIVNING
-----------
Ett Tcl/Tk-baserat grafiskt användargränssnitt till Git. 'git gui' fokuserar på att låta användare göra ändringar i sitt kodförråd genom att göra nya incheckningar, ändra befintliga, skapa grenar, utföra lokala sammanslagningar och hämta/skicka till fjärrkodförråd.

Till skillnad från 'gitk' fokuserar 'git gui' på incheckning-generering och annotering av enskilda filer och visar inte projekthistorik. Den tillhandahåller dock menyåtgärder för att starta en 'gitk'-session inifrån 'git gui'.

'git gui' är känt för att fungera på alla populära UNIX-system, Mac OS X och Windows (under både Cygwin och MSYS). Genom att så långt som möjligt följa operativsystemens riktlinjer för användargränssnitt, upplevs 'git gui' som ett relativt naturligt gränssnitt för användarna.

KOMMANDON
---------
skyldig::
	Starta en klandervisare för den angivna filen i den angivna versionen (eller arbetsträdet om ingen version anges).

browser::
	Starta en trädvisare som visar alla filer i den angivna incheckningen. Filer som väljs i trädvisaren öppnas i klandervisaren.

citool::
	Starta 'git gui' och ordna så att exakt en incheckning görs innan programmet avslutar och återgår till skalet. Gränssnittet är begränsat till enbart incheckningsåtgärder, vilket minskar programmets starttid något och förenklar menyraden.

version::
	Visa den version av 'git gui' som körs för närvarande.


Exempel
-------
`git gui blame Makefile`::

	Visa innehållet i filen 'Makefile' i den aktuella arbetskatalogen och tillhandahåll annoteringar för både den ursprungliga författaren till varje rad och vem som flyttade raden till dess nuvarande plats. Den oincheckade filen annoteras, och obekräftade ändringar (om några) tillskrivs explicit till 'Inte incheckad ännu '.

`git gui blame v0.99.8 Makefile`::

	Visa innehållet i 'Makefile' i version 'v0.99.8' och tillhandahåll annoteringar för varje rad. Till skillnad från exemplet ovan läses filen från objektdatabasen och inte från arbetskatalogen.

`git gui blame --line=100 Makefile`::

	Laddar anteckningar enligt beskrivningen ovan och rullar automatiskt vyn till centreringen på rad '100'.

`git gui citool`::

	Gör en incheckning och återgå till skalet när det är klart. Detta kommando returnerar en avslutningskod som inte är noll om fönstret stängdes på något annat sätt än genom att göra en incheckning.

`git gui citool --amend`::

	Gå automatiskt in i gränssnittets läge 'Ändra senaste incheckningen'.

`git gui citool --nocommit`::

	Bete sig som vanligt citool, men i stället för att göra en incheckning helt enkelt avsluta med en noll exit-kod. Den kontrollerar fortfarande att indexet inte innehåller några ej sammanslagna poster, så det kan användas som en GUI-version av linkgit:git-mergetool[1]

`git citool`::

	Samma som `git gui citool` (ovan).

`git gui browser maint`::

	Visa en läsare för trädet för 'maint' grenen. Filer som valts i läsaren kan visas med den interna skydligvisaren.

SE ÄVEN
-------
linkgit:gitk[1]::
	Git-kodförråd läsare. Visar grenar, incheckningshistorik och filskillnader. gitk är verktyget som startas av 'git gui's Kodförråd Visualisera-åtgärder.

Andra
-----
'git gui' underhålls faktiskt som ett oberoende projekt, men stabila versioner distribueras som en del av Git-sviten för slutanvändarnas bekvämlighet.

Det officiella kodförrådet för projektet 'git gui' finns på:

  https://github.com/j6t/git-gui

GIT
---
En del av linkgit:git[1]-sviten
