git-show(1)
===========

NAMN
----
git-show - Visa olika typer av objekt


SYNOPSIS
--------
[verse]
'git show' [<flaggor>] <objekt>...

BESKRIVNING
-----------
Visar ett eller flera objekt (blobbar, träd, taggar och incheckningar).

För incheckningar visas loggmeddelandet och den textuella differensen. Den presenterar också sammanslagings-incheckningen i ett speciellt format som produceras av 'git diff-tree --cc'.

För taggar, visar den taggmeddelandet och de refererade objekten.

För träd, visar den namnen (motsvarande 'git ls-tree' med --name-only).

För vanliga blobbar, visar den det vanliga innehållet.

Vissa alternativ som kommandot 'git log' förstår kan användas för att styra hur ändringarna som incheckning introducerar visas.

Den här manualsidan beskriver endast de mest använda alternativen.


ALTERNATIV
----------
<objekt>...::
	Namnen på objekt som ska visas (standardinställningen är 'HEAD'). För en mer komplett lista över hur objektnamn stavas, se avsnittet "SPECIFICERING AV REVISIONER" i linkgit:gitrevisions[7].

include::pretty-options.adoc[]


include::pretty-formats.adoc[]


DIFF-FORMATERING
----------------
Alternativen nedan kan användas för att ändra hur `git show` genererar diff-utdata.

:git-log: 1
:diff-merges-default: `dense-combined`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]


EXEMPEL
-------

`git show v1.0.0`::
	Visar taggen `v1.0.0`, tillsammans med objektet som taggen pekar på.

`git show v1.0.0^{tree}`::
	Visar trädet som pekas på av taggen `v1.0.0`.

`git show -s --format=%s v1.0.0^{commit}`::
	Visar ämnet för den incheckning som pekas på av taggen `v1.0.0`.

`git show next~10:Documentation/README`::
	Visar innehållet i filen `Dokumentation/README` som det var aktuellt vid den tionde sista incheckningen av grenen `next`.

`git show master:Makefile master:t/Makefile`::
	Sammanfogar innehållet i nämnda Makefiles i huvudet på grenen `master`.

DISKUSSION
----------

include::i18n.adoc[]

GIT
---
En del av linkgit:git[1]-sviten
