git-symbolic-ref(1)
===================

NAMN
----
git-symbolic-ref - Läs, ändra och ta bort symboliska referenser

SYNOPSIS
--------
[verse]
'git symbolic-ref' [-m <anledning>] <namn> <ref>
'git symbolic-ref' [-q] [--short] [--no-recurse] <namn>
'git symbolic-ref' --delete [-q] <namn>

BESKRIVNING
-----------
Givet ett argument, läser vilket grenhuvud den givna symboliska referensen refererar till och matar ut dess sökväg, relativt till `.git/`-katalogen. Vanligtvis skulle du ange `HEAD` som <namn>-argument för att se vilken gren ditt arbetsträd finns på.

Skapar eller uppdaterar, givet två argument, en symbolisk ref <namn> som pekar på den givna grenen <ref>.

Givet `--delete` och ett ytterligare argument, raderas den givna symboliska referensen.

En symbolisk ref är en vanlig fil som lagrar en sträng som börjar med `ref: refs/`. Till exempel är din `.git/HEAD` en vanlig fil vars innehåll är `ref: refs/heads/master`.

ALTERNATIV
----------

-d::
--delete::
	Ta bort den symboliska referensen <namn>.

-q::
--quiet::
	Ge inte ett felmeddelande om <namn> inte är en symbolisk referens utan en frikopplad HEAD; avsluta i stället tyst med en status som inte är noll.

--short::
	När du visar värdet för <namn> som en symbolisk referens, försök att förkorta värdet, t.ex. från `refs/heads/master` till `master`.

--recurse::
--no-recurse::
	När värdet för <namn> visas som en symbolisk referens, om <namn> refererar till en annan symbolisk referens, följ en sådan kedja av symboliska referenser tills resultatet inte längre pekar på en symbolisk referens (`--recurse`, vilket är standardvärdet). `--no-recurse` stoppar efter att endast en enda nivå av symbolisk referens har avrefererats.

-m::
	Uppdatera refloggen för <namn> med <orsak>. Detta gäller endast när man skapar eller uppdaterar en symbolisk referens.

NOTERINGAR
----------
Förr i tiden var `.git/HEAD` en symbolisk länk som pekade på `refs/heads/master`. När vi ville byta till en annan gren gjorde vi `ln -sf refs/heads/newbranch .git/HEAD`, och när vi ville ta reda på vilken gren vi är på gjorde vi `readlink .git/HEAD`. Men symboliska länkar är inte helt portabla, så de är nu föråldrade och symboliska referenser (som beskrivs ovan) används som standard.

'git symbolic-ref' avslutas med status 0 om innehållet i den symboliska referensen skrevs ut korrekt, med status 1 om det begärda namnet inte är en symbolisk referens, eller 128 om ett annat fel uppstår.

SE ÄVEN
-------
linkgit:git-update-ref[1]

GIT
---
En del av linkgit:git[1]-sviten
