git-check-ignore(1)
===================

NAMN
----
git-check-ignore - Felsöka gitignore / exkludera filer


SYNOPSIS
--------
[verse]
'git check-ignore' [<flaggor>] <sökvägsnamn>...
'git check-ignore' [<flaggor>] --stdin

BESKRIVNING
-----------

För varje sökvägsnamn som anges via kommandoraden eller från en fil via `--stdin`, kontrollera om filen är exkluderad av .gitignore (eller andra indatafiler till exkluderingsmekanismen) och mata ut sökvägen om den är exkluderad.

Som standard visas inte spårade filer alls eftersom de inte omfattas av exkluderingsregler; men se `--no-index'.

ALTERNATIV
----------
-q::
--quiet::
	Skriv inte ut något, ange bara utgångsstatus. Detta är bara giltigt med ett enda sökvägsnamn.

-v::
--verbose::
	I stället för att skriva ut de sökvägar som är exkluderade, skriv ut exkluderingsmönstret tillsammans med sökvägen för varje sökväg som matchar ett exkluderingsmönster. (Att matcha ett exkluderingsmönster innebär vanligtvis att sökvägen är exkluderad, men om mönstret börjar med "`!"" är det ett negerat mönster och att matcha det innebär att sökvägen INTE är exkluderad.)
+
För prioriteringsregler inom och mellan uteslutningskällor, se linkgit:gitignore[5].

--stdin::
	Läs sökvägar från standardinmatningen, en per rad, i stället för från kommandoraden.

-z::
	Utdataformatet är modifierat för att vara maskinparsbart (se nedan). Om `--stdin` också anges, separeras indatavägarna med ett NUL-tecken i stället för ett radmatningstecken.

-n::
--non-matching::
	Visa givna sökvägar som inte matchar något mönster. Detta är bara meningsfullt när `--verbose` är aktiverat, annars skulle det inte vara möjligt att skilja mellan sökvägar som matchar ett mönster och de som inte gör det.

--no-index::
	Titta inte i indexet när du utför kontrollerna. Detta kan användas för att felsöka varför en sökväg spårades av t.ex. `git add .` och inte ignorerades av reglerna som förväntat av användaren, eller när man utvecklar mönster som inkluderar negation för att matcha en sökväg som tidigare lagts till med `git add -f`.

UTMATNING
---------

Som standard matas alla givna sökvägar som matchar ett ignoreringsmönster ut, en per rad. Om inget mönster matchar en given sökväg matas ingenting ut för den sökvägen; det betyder att sökvägen inte ignoreras.

Om `--verbose` anges, är utdata en serie rader av formen:

<källa> <COLON> <radnumret> <COLON> <mönster> <HT> <sökvägsnamn>

<sökvägsnamn> är sökvägen till en fil som efterfrågas, <mönster> är det matchande mönstret, <källa> är mönstrets källfil och <radnumret> är radnumret för mönstret i den källkoden. Om mönstret innehöll ett "`!`"-prefix eller "`/`"-suffix kommer det att bevaras i utdata. <källa> kommer att vara en absolut sökväg när det refereras till filen som konfigurerats av `core.excludesFile`, eller relativ till kodförråds-roten när det refereras till `.git/info/exclude` eller en exkluderingsfil per katalog.

Om `-z` anges avgränsas sökvägarna i utdata av null-tecknet; om `--verbose` också anges används även null-tecken i stället för kolon och tabbtecken:

<källa> <NULL> <radnummer> <NULL> <mönster> <NULL> <sökvägsnamn> <NULL>

Om `-n` eller `--non-matching` anges, kommer även icke-matchande sökvägar att matas ut, i vilket fall alla fält i varje utdatapost förutom <sökvägsnamn> kommer att vara tomma. Detta kan vara användbart vid icke-interaktiv körning, så att filer kan strömmas stegvis till STDIN för en långvarig check-ignore-process, och för var och en av dessa filer kommer STDOUT att indikera om filen matchade ett mönster eller inte. (Utan detta alternativ skulle det vara omöjligt att avgöra om avsaknaden av utdata för en given fil innebar att den inte matchade något mönster, eller att utdata ännu inte hade genererats.)

Buffring sker enligt beskrivningen under `GIT_FLUSH`-alternativet i linkgit:git[1]. Anroparen ansvarar för att undvika dödlägen orsakade av överfyllning av en inbuffert eller läsning från en tom utbuffert.

UTGÅNGSSTATUS
-------------

0::
	En eller flera av de angivna sökvägarna ignoreras.

1::
	Ingen av de angivna sökvägarna ignoreras.

128::
	Ett allvarligt fel uppstod.

SE ÄVEN
-------
linkgit:gitignore[5] linkgit:git-config[1] linkgit:git-ls-files[1]

GIT
---
En del av linkgit:git[1]-sviten
