git-quiltimport(1)
==================

NAMN
----
git-quiltimport - Tillämpar en quilt-patchset på den aktuella grenen


SYNOPSIS
--------
[verse]
'git quiltimport' [--dry-run | -n] [--author <författare>] [--patches <kat>]
		[--series <fil>] [--keep-non-patch]


BESKRIVNING
-----------
Tillämpar en quilt-patchuppsättning på den aktuella Git-grenen, och bevarar patchgränserna, patchordningen, och patchbeskrivningarna som finns i quilt-patchuppsättningen.

För varje patch försöker koden extrahera författaren från patchbeskrivningen. Om det misslyckas återgår den till författaren som angavs med --author. Om flaggan --author inte angavs visas patchbeskrivningen och användaren ombeds att interaktivt ange patchens författare.

Om ett ämne inte hittas i patchbeskrivningen bevaras patchnamnet som det enradiga ämnet i Git-beskrivningen.

ALTERNATIV
----------

-n::
--dry-run::
	Gå igenom patcharna i serien och varna om vi inte hittar all nödvändig information för att checka-in en patch. I skrivande stund varnas endast för saknad författarinformation.

--author 'Författar Namn <Författar E-post>'::
	Författarnamnet och e-postadressen som ska användas när ingen författarinformation finns i patchbeskrivningen.

--patches <kat>::
	Katalogen för att hitta quilt-patcharna.
+
Standardvärdet för patch-katalogen är 'patches' eller värdet för miljövariabeln `$QUILT_PATCHES`.

--series <fil>::
	Filen för quiltserien.
+
Standardvärdet för seriefilen är <patches>/series eller värdet för miljövariabeln `$QUILT_SERIES`.

--keep-non-patch::
	Skicka `-b`-flaggan till 'git mailinfo' (se linkgit:git-mailinfo[1]).

GIT
---
En del av linkgit:git[1]-sviten
