git-upload-pack(1)
==================

NAMN
----
git-upload-pack - Skicka objekt packade tillbaka till git-fetch-pack


SYNOPSIS
--------
[verse]
'git-upload-pack' [--[no-]strict] [--timeout=<n>] [--stateless-rpc]
		  [--advertise-refs] <katalog>

BESKRIVNING
-----------
Anropas av 'git fetch-pack', lär sig vilka objekt den andra sidan saknar och skickar dem efter packning.

Det här kommandot anropas vanligtvis inte direkt av slutanvändaren. Användargränssnittet för protokollet finns på sidan 'git fetch-pack', och programparet är avsett att användas för att hämta (pull) uppdateringar från ett fjärrkodförråd. För sänd-åtgärder (push), se 'git send-pack'.

ALTERNATIV
----------

--strict::
--no-strict::
	Försök inte <katalog>/.git/ om <katalog> inte är en Git-katalog.

--timeout=<n>::
	Avbryt överföringen efter <n> sekunders inaktivitet.

--stateless-rpc::
	Utför endast en enda läs- och skrivcykel med stdin och stdout. Detta passar HTTP POST-förfrågningsmodellen där ett program kan läsa begäran, skriva ett svar och måste avsluta.

--http-backend-info-refs::
	Används av linkgit:git-http-backend[1] för att hantera `$GIT_URL/info/refs?service=git-upload-pack`-förfrågningar. Se "Smarta klienter" i linkgit:gitprotocol-http[5] och "HTTP Transport" i linkgit:gitprotocol-v2[5]-dokumentationen. Förstås även av linkgit:git-receive-pack[1].

<katalog>::
	Förvaret att synkronisera från.

MILJÖ
-----

`GIT_PROTOCOL`::
	Intern variabel som används för handskakning av wire-protokollet. Serveradministratörer kan behöva konfigurera vissa transporter för att tillåta att denna variabel skickas. Se diskussionen i linkgit:git[1].

`GIT_NO_LAZY_FETCH`::
	Vid kloning eller hämtning från ett partiellt arkiv (dvs. ett som själv klonats med `--filter`) kan `upload-pack` på serversidan behöva hämta extra objekt från sin uppströms för att slutföra begäran. Som standard vägrar `upload-pack` att utföra en sådan lat hämtning, eftersom `git fetch` kan köra godtyckliga kommandon som anges i konfigurationen och hakarna för källkodförrådet (och `upload-pack` försöker vara säker att köra även i otillförlitliga `.git`-kataloger).
+
Detta implementeras genom att `upload-pack` internt sätter variabeln `GIT_NO_LAZY_FETCH` till `1`. Om du vill åsidosätta den (eftersom du hämtar från en partiell klon och du är säker på att du litar på den) kan du explicit sätta `GIT_NO_LAZY_FETCH` till `0`.

SÄKERHET
--------

De flesta Git-kommandon bör inte köras i en opålitlig `.git`-katalog (se avsnittet `SÄKERHET` i linkgit:git[1]). `upload-pack` försöker undvika farliga konfigurationsalternativ eller krokar från det kodförrådet det hanterar, vilket gör det säkert att klona en opålitlig katalog och köra kommandon på den resulterande klonen.

För en extra säkerhetsnivå kan du eventuellt köra `upload-pack` som en alternativ användare. Detaljerna beror på plattformen, men på många system kan du köra:

    git clone --no-local --upload-pack='sudo -u nobody git-upload-pack' ...

SE ÄVEN
-------
linkgit:gitnamespaces[7]

GIT
---
En del av linkgit:git[1]-sviten
