git-merge-index(1)
==================

NAMN
----
git-merge-index - Kör en sammanslagning för filer som behöver sammanfogas


SYNOPSIS
--------
[verse]
'git merge-index' [-o] [-q] <sammanslagnings-program> (-a | ( [--] <fil>...) )

BESKRIVNING
-----------
Det här söker upp <fil>(filerna) i indexet och, om det finns några sammanslagningsposter, skickas SHA-1-hashen för dessa filer som argument 1, 2, 3 (tomt argument om ingen fil finns) och <fil> som argument 4. Fillägen för de tre filerna skickas som argument 5, 6 och 7.

ALTERNATIV
----------
\--::
	Tolka inte fler argument som alternativ.

-a::
	Kör sammanslagning mot alla filer i indexet som behöver sammanfogas.

-o::
	I stället för att stanna vid den första misslyckade sammanslagningen, gör alla i ett försök – fortsätt med sammanslagningen även om tidigare sammanslagningar returnerade fel, och returnera bara felkoden efter alla sammanslagningar.

-q::
	Klaga inte på ett misslyckat sammanslagningsprogram (ett misslyckande med sammanslagningen indikerar vanligtvis konflikter under sammanslagningen). Detta är för högnivåkommandon som kan vilja skriva egna meddelanden.

Om 'git merge-index' anropas med flera <fil>s (eller -a) så bearbetar den dem i tur och ordning och stoppar bara om sammanslagning returnerar en avslutningskod som inte är noll.

Vanligtvis körs detta med ett skript som anropar Gits imitation av kommandot 'merge' från RCS-paketet.

Ett exempelskript som heter 'git merge-one-file' ingår i distributionen.

VARNING VARNING VARNING! Git-systemets "merge object order" skiljer sig från RCS 'merge'-programmets sammanslagnings-ordning. I ordningen ovan kommer originalet först. Men argumentordningen till det trevägssammanslagningsprogrammet "merge" är att originalet ska vara i mitten. Fråga mig inte varför.

Exempel:

----
torvalds@ppc970:~/merge-test> git merge-index cat MM
Detta är MM från det ursprungliga trädet.		# original
Detta är modifierad MM i gren A.		# merge1
Detta är modifierad MM i gren B.		# merge2
Detta är modifierad MM i gren B.		# aktuellt innehåll
----

eller

----
torvalds@ppc970:~/merge-test> git merge-index cat AA MM
cat: : Ingen sådan fil eller katalog
Detta läggs till AA i gren A.
Detta läggs till AA i gren B.
Detta läggs till AA i gren B.
fatalt: sammanslagningsprogrammet misslyckades
----

där det senare exemplet visar hur 'git merge-index' slutar försöka sammanfoga när något har returnerat ett fel (dvs. 'cat' returnerade ett fel för AA-filen, eftersom den inte fanns i originalet, och därmed försökte 'git merge-index' inte ens sammanfoga MM-grejen).

GIT
---
En del av linkgit:git[1]-sviten
