git-stripspace(1)
=================

NAMN
----
git-stripspace - Ta bort onödiga blanktecken


SYNOPSIS
--------
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

BESKRIVNING
-----------

Läs text, såsom incheckning-meddelanden, anteckningar, taggar och grenbeskrivningar, från standardindata och rensa den på det sätt som används av Git.

Utan argument, kommer detta att:

- ta bort efterföljande blanksteg från alla rader
- kompaktera flera tomma rader i rad till en tom rad
- ta bort tomma rader från början och slutet av inmatningen
- Lägg till ett saknat '\n' på sista raden om det behövs.

I det fallet där indata består helt av blanktecken kommer ingen utdata att produceras.

*OBS*: Detta är avsett för att rensa metadata. Föredra `--whitespace=fix`-läget i linkgit:git-apply[1] för att korrigera blanksteg i patchar eller filer i kodförrådet.

ALTERNATIV
----------
-s::
--strip-comments::
	Hoppa över och ta bort alla rader som börjar med ett kommentartecken (`core.commentChar`, standard `#`).

-c::
--comment-lines::
	Lägg till kommentartecknet och ett mellanslag före varje rad. Raderna avslutas automatiskt med en nyrad. På tomma rader läggs endast kommentartecknet till.

EXEMPEL
-------

Givet följande brusiga inmatning med '$' som indikerar slutet på en rad:

---------
|En kort introduktion $
|   $
|$
|Ett nytt stycke$
|# med en kommenterad rad $
|som förklarar en massa saker.$
|$
|# Ett gammalt stycke, också kommenterat. $
|      $
|Slutet.$
|  $
---------

Använd 'git stripspace' utan argument för att få:

---------
|En kort introduktion$
|$
|Ett nytt stycke$
|# med en kommenterad rad$
|som förklarar en massa saker.$
|$
|# Ett gammalt stycke, också kommenterat.$
|$
|Slutet.$
---------

Använd 'git stripspace --strip-comments' för att få:

---------
|En kort introduktion$
|$
|Ett nytt stycke$
|som förklarar en massa saker.$
|$
|Slutet.$
---------

GIT
---
En del av linkgit:git[1]-sviten
