git-credential-cache(1)
=======================

NAMN
----
git-credential-cache - Hjälpprogram för att tillfälligt lagra lösenord i minnet

SYNOPSIS
--------
-----------------------------
git config credential.helper 'cache [<flaggor>]'
-----------------------------

BESKRIVNING
-----------

Det här kommandot cachar legitimationsinformation för användning av framtida Git-program. De lagrade legitimationsinformationen sparas i cache-daemon-processens minne (istället för att skrivas till en fil) och glöms bort efter en konfigurerbar timeout. Legitimationsinformationen glöms bort tidigare om cache-daemonen dör, till exempel om systemet startas om. Cachen är åtkomlig via en Unix-domänsocket, begränsad till den aktuella användaren av filsystembehörigheter.

Du vill förmodligen inte anropa det här kommandot direkt; det är tänkt att användas som en hjälp för legitimationsinformation av andra delar av Git. Se linkgit:gitcredentials[7] eller `EXEMPEL` nedan.

ALTERNATIV
----------

--timeout <sekunder>::

	Antal sekunder för att cacha legitimationsinformation (standard: 900).

--socket <sökväg>::

	Använd `<sökväg>` för att kontakta en aktiv cache-daemon (eller starta en ny cache-daemon om en inte har startats). Standardvärdet är `$XDG_CACHE_HOME/git/credential/socket` om inte `~/.git-credential-cache/` finns, i vilket fall `~/.git-credential-cache/socket` används istället. Om din hemkatalog finns på ett nätverksmonterat filsystem kan du behöva ändra detta till ett lokalt filsystem. Du måste ange en absolut sökväg.

KONTROLLERA DEMONEN
-------------------

If you would like the daemon to exit early, forgetting all cached credentials before their timeout, you can issue an `exit` action:

--------------------------------------
git credential-cache exit
--------------------------------------

EXEMPEL
-------

Poängen med den här hjälpprogramet är att minska antalet gånger du måste skriva in ditt användarnamn eller lösenord. Till exempel:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <skriv ditt användarnamn>
Password: <skriv ditt lösenord>

[jobba i 5 minuter till]
$ git push http://example.com/repo.git
[dina legitimationsinformation används automatiskt]
------------------------------------

Du kan ange alternativ via konfigurationsvariabeln credential.helper (detta exempel ökar cachetiden till 1 timme):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

PERSONLIGA ÅTKOMSTTOKEN
-----------------------

Vissa fjärrar accepterar personliga åtkomsttokens, vilka genereras slumpmässigt och är svåra att memorera. De har vanligtvis en livslängd på veckor eller månader.

git-credential-cache är i sig olämpligt för permanent lagring av personliga åtkomsttokens. Autentiseringsuppgifterna kommer att glömmas bort efter cache-timeouten. Även om du konfigurerar en lång timeout kommer legitimationsinformationen att glömmas bort om daemonen dör.

För att undvika att ofta generera om personliga åtkomsttokens, konfigurera en autentiseringshjälp med permanent lagring. Alternativt kan du konfigurera en OAuth-autentiseringshjälp för att generera autentiseringsuppgifter automatiskt. Se linkgit:gitcredentials[7], avsnitten "Tillgängliga hjälpfunktioner" och "OAuth".

GIT
---
En del av linkgit:git[1]-sviten
