git-whatchanged(1)
==================

NAMN
----
git-whatchanged - Visar loggar med skillnader som varje incheckning introducerar


SYNOPSIS
--------
[synopsis]
git whatchanged <alternativ>...

VARNING
-------
`git whatchanged` har föråldrats och är planerad att tas bort i en framtida version av Git, eftersom det bara är `git log` med andra standardvärden.

BESKRIVNING
-----------

Visar incheckning-loggar och skillnaden mellan utdata och varje incheckning.

Nya användare uppmuntras att använda linkgit:git-log[1] istället. Kommandot `whatchanged` är i huvudsak detsamma som linkgit:git-log[1] men visar som standard diff-utdata i råformat och hoppar över sammanslagningar:

----
git log --raw --no-merges
----

Kommandot behålls främst av historiska skäl; fingrarna på många personer som lärde sig Git långt innan `git log` uppfanns genom att läsa Linuxkärnans e-postlista tränas att skriva det.


Exempel
-------
`git whatchanged -p v2.6.12.. include/scsi drivers/scsi`::

	Visa som patchar de incheckningar sedan version 'v2.6.12' som ändrade någon fil i underkatalogerna include/scsi eller drivers/scsi

`git whatchanged --since="2 weeks ago" -- gitk`::

	Visa ändringarna under de senaste två veckorna i filen 'gitk'. "--" är nödvändigt för att undvika förväxling med *grenen* som heter 'gitk'

GIT
---
En del av linkgit:git[1]-sviten
