git-range-diff(1)
=================

NAMN
----
git-range-diff - Jรคmfรถr tvรฅ incheckningsintervall (dvs. tvรฅ versioner av en gren)

SYNOPSIS
--------
[verse]
'git range-diff' [--color=[<nรคr>]] [--no-color] [<diff-flaggor>]
	[--no-dual-color] [--creation-factor=<faktor>]
	[--left-only | --right-only] [--diff-merges=<format>]
	[--remerge-diff]
	( <range1> <range2> | <rev1>...<rev2> | <base> <rev1> <rev2> )
	[[--] <sรถkvรคg>...]

BESKRIVNING
-----------

Det hรคr kommandot visar skillnaderna mellan tvรฅ versioner av en patchserieer, eller mer generellt, tvรฅ inchecknings-intervall (ignorerar sammanslagnings-incheckningar).

Om `<sรถkvรคg>`-argument finns begrรคnsas dessa inchecknings-intervall i enlighet dรคrmed.

Fรถr detta รคndamรฅl, hittar den fรถrst par av incheckningar frรฅn bรฅda inchecknings-intervallen som motsvarar varandra. Tvรฅ incheckningar sรคgs รถverensstรคmma nรคr skillnaden mellan deras patchar (dvs. fรถrfattarinformationen, inchecknings-meddelandet och inchecknings-differensen) รคr rimligt liten jรคmfรถrt med patcharnas storlek. Se ``Algoritm`` nedan fรถr detaljer.

Slutligen, visas listan รถver matchande incheckningar i ordningen fรถr det andra inchecknings-intervallet, dรคr omatchade incheckningar infogas precis efter att alla deras fรถregรฅngare har visats.

Det finns tre sรคtt att ange inchecknings-intervallen:

- `<intervall1> <intervall2>`: Endera inchecknings-intervallet kan ha formen `<bas>..<rev>`, `<rev>^!` eller `<rev>^-<n>`. Se `SPECIFIERING AV INTERVALL` i linkgit:gitrevisions[7] fรถr mer information.

- `<rev1>...<rev2>`. Detta motsvarar `<rev2>..<rev1> <rev1>..<rev2>`.

- `<bas> <rev1> <rev2>`: Detta motsvarar `<bas>..<rev1> <bas>..<rev2>`.

ALTERNATIV
----------
--no-dual-color::
	Nรคr inchecknings-differenserna skiljer sig รฅt รฅterskapar `git range-diff` de ursprungliga differnas fรคrg och lรคgger till yttre -/+ diff-markรถrer med *bakgrunden* rรถd/grรถn fรถr att gรถra det lรคttare att se t.ex. nรคr det skedde en รคndring i exakt vilka rader som lades till.
+
Dessutom, visas inchecknings diff-raderna som bara finns i det fรถrsta inchecknings-intervallet "nedtonade" (detta kan รฅsidosรคttas med konfigurationsinstรคllningen `color.diff.<fack>` dรคr `<fack>` รคr en av `contextDimmed`, `oldDimmed` och `newDimmed`), och inchecknings diff-raderna som bara finns i det andra inchecknings-intervallet visas i fetstil (vilket kan รฅsidosรคttas med konfigurationsinstรคllningarna `color.diff.<fack>` dรคr `<fack>` รคr en av `contextBold`, `oldBold` eller `newBold`).
+
Detta kallas `range-diff` fรถr "dubbel fรคrgning". Anvรคnd `--no-dual-color` fรถr att รฅtergรฅ till att fรคrga alla linjer enligt de yttre diff-markรถrerna (och helt ignorera den inre diff-markรถren nรคr det gรคller fรคrg).

--creation-factor=<procent>::
	Sรคtt kostnadsfudgefaktorn fรถr skapande/borttagning till `<procent>`. Standardvรคrdet รคr 60. Fรถrsรถk med ett stรถrre vรคrde om `git range-diff` felaktigt betraktar en stor รคndring som en total omskrivning (borttagning av en incheckning och tillรคgg av en annan), och ett mindre vรคrde i det omvรคnda fallet. Se avsnittet ``Algoritm`` nedan fรถr en fรถrklaring av varfรถr detta behรถvs.

--left-only::
	Undertryck incheckningar som saknas i det fรถrsta angivna omrรฅdet (eller det "vรคnstra omrรฅdet" nรคr formatet `<rev1>...<rev2>` anvรคnds).

--right-only::
	Undertryck incheckningar som saknas i det andra angivna intervallet (eller "hรถger intervall" nรคr formatet `<rev1>...<rev2>` anvรคnds).

--diff-merges=<format>::
	Istรคllet fรถr att ignorera sammanslagnings-incheckningar, generera diffs fรถr dem med hjรคlp av motsvarande `--diff-merges=<format>`-alternativ i linkgit:git-log[1], och inkludera dem i jรคmfรถrelsen.
+
Obs: I vanliga fall รคr `remerge`-lรคget det mest naturliga att anvรคnda, eftersom det bara visar skillnaden utรถver vad Gits sammanslagnings-maskineri skulle ha producerat. Med andra ord, om en sammanslagnings-incheckning รคr resultatet av en icke-konfliktfylld `git merge`, kommer `remerge`-lรคget att representera det med en tom skillnad.

--remerge-diff::
	Bekvรคmlighetsalternativ, motsvarande `--diff-merges=remerge`.

--notes[=<ref>]::
--no-notes::
	Denna flagga skickas till `git log`-programmet (se linkgit:git-log[1]) som genererar patcharna.

<intervall1> <intervall2>::
	Jรคmfรถr de incheckningar som anges av de tvรฅ intervallen, dรคr `<intervall1>` anses vara en รคldre version av `<intervall2>`.

<rev1>...<rev2>::
	Motsvarar att skicka `<rev2>..<rev1>` och `<rev1>..<rev2>`.

<bas> <rev1> <rev2>::
	Motsvarar att skicka `<bas>..<rev1>` och `<bas>..<rev2>`. Observera att `<bas>` inte behรถver vara den exakta fรถrgreningspunkten fรถr grenarna. Exempel: efter att ha ombaserat en gren `mitt-รคmne`, skulle `git range-diff mitt-รคmne@{u} mitt-รคmne@{1} mitt-รคmne` visa skillnaderna som introduceras av ombaseringen.

`git range-diff` accepterar รคven de vanliga diff-alternativen (se linkgit:git-diff[1]), framfรถr allt alternativen `--color=[<nรคr>]` och `--no-color`. Dessa alternativ anvรคnds nรคr man genererar "differensen mellan patchar", dvs. fรถr att jรคmfรถra fรถrfattaren, inchecknings-meddelandet och diff-vรคrdet fรถr motsvarande gamla/nya incheckningar. Det finns fรถr nรคrvarande inget sรคtt att justera de flesta av diff-alternativen som skickas till `git log` nรคr man genererar dessa patchar.

UTMATNINGSSTABILITET
--------------------

Utdata frรฅn kommandot `range-diff` kan komma att รคndras. Det รคr avsett att vara mรคnniskolรคsbart porslinsutdata, inte nรฅgot som kan anvรคndas i olika versioner av Git fรถr att fรฅ en textmรคssigt stabil `range-diff` (i motsats till nรฅgot som `--stable`-alternativet till linkgit:git-patch-id[1]). Det finns inte heller nรฅgon motsvarighet till linkgit:git-apply[1] fรถr `range-diff`, utdata รคr inte avsett att vara maskinlรคsbart.

Detta gรคller sรคrskilt nรคr man skickar in diff-alternativ. Fรถr nรคrvarande kan vissa alternativ som `--stat`, som en framvรคxande effekt, producera utdata som รคr ganska vรคrdelรถsa i samband med `range-diff`. Framtida versioner av `range-diff` kan lรคra sig att tolka sรฅdana alternativ pรฅ ett sรคtt som รคr specifikt fรถr `range-diff` (t.ex. fรถr `--stat` som producerar mรคnniskolรคsbart utdata som sammanfattar hur diffstaten รคndradats).

KONFIGURATION
-------------
Det hรคr kommandot anvรคnder instรคllningarna `diff.color.*` och `pager.range-diff` (den senare รคr aktiverad som standard). Se linkgit:git-config[1].


EXEMPEL
-------

Nรคr en ombasering krรคver att sammanslagningskonflikter lรถses, jรคmfรถr รคndringarna som introducerats av ombaseringen direkt efterรฅt med hjรคlp av:

------------
$ git range-diff @{u} @{1} @
------------


En typisk utdata frรฅn `git range-diff` skulle se ut sรฅ hรคr:

------------
-:  ------- > 1:  0ddba11 Fรถrbered dig pรฅ det oundvikliga!
1:  c0debee = 2:  cab005e Lรคgg till ett anvรคndbart meddelande i bรถrjan
2:  f00dbal ! 3:  decafe1 Beskriv en bugg
    @@ -1,3 +1,3 @@
     Author: A U Thor <author@example.com>

    -TODO: Beskriv en bugg
    +Beskriv en bugg
    @@ -324,5 +324,6
      Detta รคr fรถrvรคntat.

    -+Det ovรคntade รคr att den ocksรฅ kommer att krascha.
    ++Ovรคntat kraschar den ocksรฅ. Detta รคr en bugg, och juryn รคr'
    ++fortfarande ute efter hur man bรคst รฅtgรคrdar den. Se รคrende #314 fรถr mer information.

      Contact
3:  bedead < -:  ------- TO-UNDO
------------

I det hรคr exemplet, finns det 3 gamla och 3 nya incheckningar, dรคr utvecklaren tog bort den tredje, lade till en ny fรถre de tvรฅ fรถrsta och modifierade inchecknings-meddelandet fรถr den andra incheckningen sรฅvรคl som dess diff.

Nรคr utdata skickas till en terminal, รคr den fรคrgkodad som standard, precis som vanlig `git diff` utdata. Dessutom รคr den fรถrsta raden (som lรคgger till en incheckning) grรถn, den sista raden (som tar bort en incheckning) รคr rรถd, den andra raden (med perfekt matchning) รคr gul som inchecknings-huvudet i `git show` utdata, och den tredje raden fรคrgar den gamla incheckningen rรถd, den nya grรถn och resten som `git show`s inchecknings-huvuder.

En naiv fรคrgkodad diff av diffs รคr faktiskt lite svรฅr att lรคsa, eftersom den fรคrgar hela raderna rรถda eller grรถna. Raden som lade till "Vad รคr ovรคntat" i den gamla incheckningen รคr till exempel helt rรถd, รคven om avsikten med den gamla cincheckningen var att lรคgga till nรฅgot.

Fรถr att underlรคtta detta anvรคnder `range` lรคget `--dual-color` som standard. I det hรคr lรคget behรฅller diff-vรคrdena de ursprungliga fรคrgerna och prefixerar raderna med -/+ markรถrer som har sin *bakgrund* rรถd eller grรถn, fรถr att gรถra det tydligare att de beskriver hur sjรคlva diffen รคndrades.


Algoritm
--------

Den allmรคnna idรฉn รคr denna: vi genererar en kostnadsmatris mellan incheckningar i bรฅda inchecknings-intervallen, och lรถser sedan den lรคgsta kostnadstilldelningen.

Kostnadsmatrisen fylls i sรฅ hรคr: fรถr varje par av incheckningar genereras bรฅda differna och "diffen av differ" genereras, med 3 kontextrader, sedan anvรคnds antalet rader i den diffen som kostnad.

Fรถr att undvika falska positiva resultat (t.ex. nรคr en patch har tagits bort och en orelaterad patch har lagts till mellan tvรฅ iterationer av samma patchserie), utรถkas kostnadsmatrisen fรถr att mรถjliggรถra detta, genom att lรคgga till fasta kostnadsposter fรถr grossistborttagningar/tillรคgg.

Exempel: Lรฅt incheckningar `1--2` vara den fรถrsta iterationen i en patchserie och `A--C` den andra iterationen. Lรฅt oss anta att `A` รคr ett urval av `2` och `C` รคr ett urval av `1` men med en liten modifiering (t.ex. ett rรคttat stavfel). Visualisera incheckningar som en tvรฅdelad graf:

------------
    1            A

    2            B

		 C
------------

Vi letar efter en "bรคsta" fรถrklaring av den nya serien i termer av den gamla. Vi kan representera en "fรถrklaring" som en kant i grafen:


------------
    1            A
	       /
    2 --------'  B

		 C
------------

Denna fรถrklaring kommer "gratis" eftersom det inte skedde nรฅgon fรถrรคndring. Pรฅ liknande sรคtt skulle `C` kunna fรถrklaras med `1`, men det har en viss kostnad c>0 pรฅ grund av modifieringen:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
	  |
	  `----- C
	  c>0
------------

Matematiskt sett letar vi efter nรฅgon form av tvรฅdelad matchning med minimal kostnad; `1` matchas mot `C` till en viss kostnad, etc. Den underliggande grafen รคr i sjรคlva verket en komplett tvรฅdelad graf; kostnaden vi associerar med varje kant รคr storleken pรฅ skillnaden mellan de tvรฅ incheckningarnas patchar. Fรถr att รคven fรถrklara nya incheckningar introducerar vi attrapp-noder pรฅ bรฅda sidor:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
	  |
    o     `----- C
	  c>0
    o            o

    o            o
------------

Kostnaden fรถr en kant `o--C` รคr storleken pรฅ `C`s diff, modifierad med en fudgefaktor som bรถr vara mindre รคn 100%. Kostnaden fรถr en kant `o--o` รคr gratis. Fudgefaktorn รคr nรถdvรคndig eftersom รคven om `1` och `C` inte har nรฅgot gemensamt, kan de fortfarande dela nรฅgra tomma rader och liknande, vilket mรถjligen gรถr tilldelningen `1--C`, `o--o` nรฅgot billigare รคn `1--o`, `o--C` รคven om `1` och `C` inte har nรฅgot gemensamt. Med fudgefaktorn krรคver vi en mycket stรถrre gemensam del fรถr att betrakta patchar som motsvarande.

Den totala tiden som behรถvs fรถr att berรคkna denna algoritm รคr den tid som behรถvs fรถr att berรคkna n+m inchecknings-differenser och sedan n*m differenser av patchar, plus den tid som behรถvs fรถr att berรคkna den lรคgsta kostnadstilldelningen mellan n och m differenser. Git anvรคnder en implementering av Jonker-Volgenant-algoritmen fรถr att lรถsa tilldelningsproblemet, som har kubisk runtime-komplexitet. Matchningen som hittas i detta fall kommer att se ut sรฅ hรคr:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
       .--+-----'
    o -'  `----- C
	  c>0
    o ---------- o

    o ---------- o
------------


SE รVEN
-------
linkgit:git-log[1]

GIT
---
En del av linkgit:git[1]-sviten
