git-format-patch(1)
===================

NAMN
----
git-format-patch - Förbered patchar för att skickas via e-post


SYNOPSIS
--------
[verse]
'git format-patch' [-k] [(-o|--output-directory) <kat> | --stdout]
		   [--no-thread | --thread[=<stil>]]
		   [(--attach|--inline)[=<gräns>] | --no-attach]
		   [-s | --signoff]
		   [--signature=<signature> | --no-signature]
		   [--signature-file=<fil>]
		   [-n | --numbered | -N | --no-numbered]
		   [--start-number <n>] [--numbered-files]
		   [--in-reply-to=<meddelande-id>] [--suffix=.<sfx>]
		   [--ignore-if-in-upstream] [--always]
		   [--cover-from-description=<läge>]
		   [--rfc[=<rfc>]] [--subject-prefix=<ärende-prefix>]
		   [(--reroll-count|-v) <n>]
		   [--to=<mejl>] [--cc=<mejl>]
		   [--[no-]cover-letter] [--quiet]
		   [--[no-]encode-email-headers]
		   [--no-notes | --notes[=<ref>]]
		   [--interdiff=<föregående>]
		   [--range-diff=<föregående> [--creation-factor=<procent>]]
		   [--filename-max-length=<n>]
		   [--progress]
		   [<common-diff-options>]
		   [ <sedan> | <revision-intervall> ]

BESKRIVNING
-----------

Förbered varje incheckning som inte är en sammanslagning med sin "patch" i ett "meddelande" per incheckning, formaterat så att det liknar en UNIX-brevlåda. Utdata från kommandot är praktiskt för e-postutskick eller för användning med 'git am'.

Ett "meddelande" som genereras av kommandot består av tre delar:

* En kort metadatarubrik som börjar med `From <commit>` med en fast `Mon Sep 17 00:00:00 2001` datumstämpel för att hjälpa program som "file(1)" att känna igen att filen är ett resultat av detta kommando, fält som registrerar författaridentiteten, författardatumet och titeln på ändringen (hämtad från första stycket i incheckningsloggmeddelandet).

* Det andra och efterföljande styckena i incheckningsloggmeddelandet.

* "Patchen", som är utdatan "diff -p --stat" (se linkgit:git-diff[1]) mellan incheckningen och dess förälder.

Loggmeddelandet och patchen skiljs åt av en rad med tre bindestreck (---).

Det finns två sätt att ange vilka incheckningar som ska behandlas.

1. En enda incheckning, <sedan>, anger att de incheckningar som leder till toppen av den aktuella grenen men som inte finns i historiken som leder till <sedan> ska matas ut.

2. Generiskt <revisionsintervall>-uttryck (se avsnittet "SPECIFICERING AV REVISIONER" i linkgit:gitrevisions[7]) avser incheckningar inom det angivna intervallet.

Den första regeln har företräde vid en enskild <incheckning>. För att tillämpa den andra regeln, dvs. formatera allt från historikens början fram till <incheckning>, använd `--root`: `git format-patch --root <incheckning>`. Om du bara vill formatera själva <incheckning> kan du göra det med `git format-patch -1 <incheckning>`.

Som standard numreras varje utdatafil sekventiellt från 1 och använder den första raden i incheckningsmeddelandet (anpassad för sökvägssäkerhet) som filnamn. Med `--numbered-files` blir utdatafilernas namn bara siffror, utan att första raden i incheckningsmeddelandet läggs till. Namnen på utdatafilerna skrivs ut till standardut, om inte `--stdout` anges.

Om `-o` anges, skapas utdatafiler i <kat>. Annars skapas de i den aktuella arbetskatalogen. Standardsökvägen kan ställas in med konfigurationsalternativet `format.outputDirectory`. Alternativet `-o` har företräde framför `format.outputDirectory`. För att lagra patchar i den aktuella arbetskatalogen även när `format.outputDirectory` pekar någon annanstans, använd `-o .`. Alla katalogkomponenter kommer att skapas.

Som standard är ämnet för en enskild patch "[PATCH]" följt av en sammanslagning av rader från incheckningsmeddelandet fram till första tomma raden (se avsnittet DISCUSSION i linkgit:git-commit[1]).

När flera patchar skrivs ut blir ämnesprefixet i stället "[PATCH n/m]". För att tvinga fram 1/1 för en enskild patch, använd `-n`. För att utelämna patchnummer i ämnet, använd `-N`.

Om `--thread` anges, kommer `git-format-patch` att generera huvudena `In-Reply-To` och `References` för att få det andra och efterföljande patch-meddelandena att visas som svar på det första meddelandet; detta genererar också en `Message-ID`-rubrik att referera till.

ALTERNATIV
----------
:git-format-patch: 1
include::diff-options.adoc[]

-<n>::
	Förbered patchar från de senaste <n> incheckningarna.

-o <kat>::
--output-directory <kat>::
	Använd <kat> för att lagra de resulterande filerna, i stället för den aktuella arbetskatalogen.

-n::
--numbered::
	Namnge utdata i formatet '[PATCH n/m]', även med en enda patch.

-N::
--no-numbered::
	Namnge utdata i formatet '[PATCH]'.

--start-number <n>::
	Börja numrera patcherna vid <n> i stället för 1.

--numbered-files::
	Utdatafilernas namn blir en enkel nummersekvens utan den normala första raden från incheckningsmeddelandet.

-k::
--keep-subject::
	Ta inte bort/lägg inte till '[PATCH]' i första raden av incheckningsloggmeddelandet.

-s::
--signoff::
	Lägg till en `Signed-off-by`-slutrad till incheckningsmeddelandet, med din egen incheckare-identitet. Se signoff-alternativet i linkgit:git-commit[1] för mer information.

--stdout::
	Skriv ut alla incheckningar till standardutdata i mbox-format, i stället för att skapa en fil för varje enskild incheckning.

--attach[=<gräns>]::
	Skapa en multipart/mixed-bilaga där första delen är incheckningsmeddelandet och patchen själv ligger i andra delen, med `Content-Disposition: attachment`.

--no-attach::
	Inaktivera skapandet av en bilaga, vilket åsidosätter konfigurationsinställningen.

--inline[=<gräns>]::
	Skapa en multipart/mixed-bilaga där första delen är incheckningsmeddelandet och patchen själv ligger i andra delen, med `Content-Disposition: inline`.

--thread[=<stil>]::
--no-thread::
	Styr tillägg av rubrikerna `In-Reply-To` och `References` för att få det andra och efterföljande e-postmeddelandena att visas som svar på det första. Styr också genereringen av rubriken `Message-ID` att referera till.
+
Det valfria argumentet <stil> kan vara antingen `shallow` eller `deep`. 'Shallow'-trådning gör varje e-postmeddelande till ett svar på seriens rubrik, där rubriken väljs från följebrevet, `--in-reply-to` och det första patch-mejlet, i denna ordning. 'Deep'-trådning gör varje e-postmeddelande till ett svar på det föregående.
+
Standardvärdet är `--no-thread`, såvida inte konfigurationen `format.thread` är angiven. `--thread` utan ett argument motsvarar `--thread=shallow`.
+
Observera att standardinställningen för 'git send-email' är att själv tråda e-postmeddelanden. Om du vill att `git format-patch` ska ta hand om trådningen, bör du se till att trådning är inaktiverad för `git send-email`.

--in-reply-to=<meddelande-id>::
	Få det första mejlet (eller alla mejl med `--no-thread`) att visas som ett svar på det angivna <meddelande-id>, vilket undviker att trådar bryts för att tillhandahålla en ny patchserie.

--ignore-if-in-upstream::
	Inkludera inte en patch som matchar en incheckning i <tills>..<sedan>. Detta kommer att undersöka alla patchar som är åtkomliga från <sedan> men inte från <tills> och jämföra dem med de patchar som genereras, och alla patchar som matchar ignoreras.

--always::
	Inkludera patchar för incheckningar som inte introducerar några ändringar, vilka utelämnas som standard.

--cover-from-description=<läge>::
	Styr vilka delar av följebrevet som fylls i automatiskt med hjälp av grenens beskrivning.
+
Om `<läge>` är `message` eller `default` kommer ämnet för följebrevet att fyllas med platshållartext. Huvuddelen av följebrevet kommer att fyllas med grenens beskrivning. Detta är standardläget när ingen konfiguration eller kommandoradsalternativ har angetts.
+
Om `<läge>` är `subject` kommer det första stycket i grenbeskrivningen att fylla i ämnet för följebrevet. Resten av beskrivningen kommer att fylla i brödtexten i följebrevet.
+
Om `<läge>` är `auto`, och det första stycket i grenbeskrivningen är större än 100 byte, blir läget `message`, annars används `subject`.
+
Om `<läge>` är `none` kommer både ämnet och brödtexten i följebrevet att fyllas med platshållartext.

--description-file=<fil>::
	Använd innehållet i <fil> i stället för grenens beskrivning för att generera följebrevet.

--subject-prefix=<ämnesprefix>::
	I stället för standardprefixet '[PATCH]' i ämnesraden, använd i stället '[<ämnesprefix>]'. Detta kan användas för att namnge en patchserie och kan kombineras med alternativet `--numbered`.
+
Konfigurationsvariabeln `format.subjectPrefix` kan också användas för att ange ett ämnesprefix som ska gälla för alla patchar i ett visst kodförråd. Det är ofta användbart på e-postlistor som tar emot patchar för flera kodförråd och kan användas för att skilja patcharna åt (med ett värde som till exempel "PATCH mitt-projekt").

--filename-max-length=<n>::
	I stället för standardvärdet 64 byte kapas de genererade utdatafilnamnen till ungefär '<n>' byte (ett för kort värde höjs tyst till en rimlig längd). Standardvärdet är värdet i konfigurationsvariabeln `format.filenameMaxLength`, eller 64 om den inte är satt.

--rfc[=<rfc>]::
	Lägger till strängen _<rfc>_ (standardinställningen är "RFC") framför ämnesprefixet. Eftersom ämnesprefixet är standardinställt på "PATCH" får du "RFC PATCH" som standard.
+
RFC står för "Request For Comments"; använd detta när du skickar en experimentell patch för diskussion snarare än för direkt användning. "--rfc=WIP" kan också vara ett bra sätt att visa att en patch ännu inte är färdig ("WIP" står för "Work In Progress").
+
Om konventionen i den mottagande gemenskapen för en viss extra sträng är att den ska stå _efter_ ämnesprefixet, kan strängen _<rfc>_ inledas med ett bindestreck ("`-`") för att signalera att resten av _<rfc>_-strängen ska läggas till efter ämnesprefixet i stället, till exempel ger `--rfc='-(WIP)'` "PATCH (WIP)".

-v <n>::
--reroll-count=<n>::
	Markera serien som den <n>:te iterationen av ämnet. Utdatafilnamnen får prefixet `v<n>`, och ämnesprefixet ("PATCH" som standard, men konfigurerbart med alternativet `--subject-prefix`) får tillägget ` v<n>`. Till exempel kan `--reroll-count=4` skapa filen `v4-0001-add-makefile.patch`, som innehåller "Subject: [PATCH v4 1/20] Add makefile". `<n>` behöver inte vara ett heltal (till exempel tillåts "--reroll-count=4.4" eller "--reroll-count=4rev2"), men nackdelen med ett sådant värde är att range-diff/interdiff mot föregående version inte exakt anger vilken version den nya iterationen jämförs med.

--to=<mejl>::
	Lägg till en `To:`-huvudrad i e-posthuvudena. Detta läggs ovanpå eventuella konfigurerade huvudrader och kan användas flera gånger. Den negerade formen `--no-to` kastar bort alla `To:`-huvudrader som lagts till hittills (från konfiguration eller kommandorad).

--cc=<mejl>::
	Lägg till en `Cc:`-huvudrad i e-posthuvudena. Detta läggs ovanpå eventuella konfigurerade huvudrader och kan användas flera gånger. Den negerade formen `--no-cc` kastar bort alla `Cc:`-huvudrader som lagts till hittills (från konfiguration eller kommandorad).

--from::
--from=<ident>::
	Använd `ident` i `From:`-huvudraden i varje incheckningsmejl. Om författaridentiteten för incheckningen inte textuellt matchar angiven `ident`, lägg en `From:`-huvudrad i meddelandets brödtext med den ursprungliga författaren. Om ingen `ident` anges används incheckarens identitet.
+
Observera att det här alternativet bara är användbart om du faktiskt skickar e-postmeddelandena och vill identifiera dig som avsändare men behålla den ursprungliga författaren (och `git am` läser då korrekt in huvudet i brödtexten). Observera också att `git send-email` redan hanterar den här omvandlingen åt dig, och att det här alternativet inte bör användas om du skickar resultatet till `git send-email`.

--force-in-body-from::
--no-force-in-body-from::
	När e-postavsändaren anges via alternativet `--from` läggs som standard en in-body-`From:` högst upp i incheckningsloggmeddelandet för att identifiera den verkliga författaren, om avsändaren skiljer sig från författaren. Med det här alternativet läggs in-body-`From:` till även när avsändaren och författaren har samma namn och adress, vilket kan hjälpa om e-postlistans programvara förvanskar avsändaridentiteten. Standardvärdet hämtas från konfigurationsvariabeln `format.forceInBodyFrom`.

--add-header=<huvudrad>::
	Lägg till en godtycklig huvudrad i e-posthuvudena. Detta läggs ovanpå eventuella konfigurerade huvudrader och kan användas flera gånger. Till exempel `--add-header="Organization: git-foo"`. Den negerade formen `--no-add-header` kastar bort *alla* (`To:`, `Cc:` och anpassade) huvudrader som hittills lagts till från konfiguration eller kommandorad.

--cover-letter::
--no-cover-letter::
	Generera, utöver patcharna, en följebrevsfil som innehåller grenbeskrivningen, shortlog och den övergripande diffstat. Du kan fylla i en beskrivning i filen innan du skickar den.

--encode-email-headers::
--no-encode-email-headers::
	Koda e-posthuvuden som innehåller icke-ASCII-tecken med "Q-encoding" (beskrivet i RFC 2047), i stället för att skriva ut huvudraderna ordagrant. Standardvärdet hämtas från konfigurationsvariabeln `format.encodeEmailHeaders`.

--interdiff=<föregående>::
	Som hjälp för granskare kan du infoga en interdiff i följebrevet, eller som kommentar till den enda patchen i en 1-patchserie, som visar skillnaderna mellan den tidigare versionen av patchserien och serien som formateras nu. `föregående` är en enskild revision som anger toppen för den föregående serien, vilken delar en gemensam bas med serien som formateras (till exempel `git format-patch --cover-letter --interdiff=feature/v1 -3 feature/v2`).

--range-diff=<föregående>::
	Som hjälp för granskare kan du infoga en range-diff (se linkgit:git-range-diff[1]) i följebrevet, eller som kommentar till den enda patchen i en 1-patchserie, som visar skillnaderna mellan den tidigare versionen av patchserien och serien som formateras nu. `föregående` kan vara en enskild revision som anger toppen för den tidigare serien om den delar en gemensam bas med serien som formateras (till exempel `git format-patch --cover-letter --range-diff=feature/v1 -3 feature/v2`), eller ett revisionsintervall om de två versionerna av serien är åtskilda (till exempel `git format-patch --cover-letter --range-diff=feature/v1~3..feature/v1 -3 feature/v2`).
+
Observera att diff-alternativ som skickas till kommandot påverkar hur huvudresultatet från `format-patch` genereras, och de skickas inte vidare till den underliggande `range-diff`-mekanismen som används för att skapa följebrevsinnehållet (detta kan ändras i framtiden).

--creation-factor=<procent>::
	Använd tillsammans med `--range-diff` för att justera heuristiken som matchar incheckningar mellan den föregående och den aktuella patchserien genom att ändra justeringsfaktorn för kostnad vid skapande/borttagning. Se linkgit:git-range-diff[1] för detaljer.
+
Standardvärdet är 999 (linkgit:git-range-diff[1] använder 60), eftersom användningsfallet är att jämföra med en äldre iteration av samma ämne och verktyget då bör hitta fler motsvarigheter mellan de två patchuppsättningarna.

--notes[=<ref>]::
--no-notes::
	Lägg till anteckningarna (se linkgit:git-notes[1]) för incheckningen efter raden med tre bindestreck.
+
Det avsedda användningsfallet är att skriva kompletterande förklaring till en incheckning som inte hör hemma i själva incheckningsloggmeddelandet, och ta med den i patchinskicket. Man kan förstås skriva sådana förklaringar efter att `format-patch` har körts men före utskick, men om de sparas som Git-anteckningar kan de underhållas mellan olika versioner av patchserien (se diskussionen om konfigurationsalternativen `notes.rewrite` i linkgit:git-notes[1] för detta arbetsflöde).
+
Standardvärdet är `--no-notes`, såvida inte konfigurationen `format.notes` är inställd.

--signature=<signatur>::
--no-signature::
	Lägg till en signatur i varje meddelande som skapas. Enligt RFC 3676 separeras signaturen från brödtexten med en rad som innehåller '-- '. Om signaturalternativet utelämnas används Git-versionsnumret som standardsignatur.

--signature-file=<fil>::
	Fungerar precis som `--signature`, förutom att signaturen läses från en fil.

--suffix=.<sfx>::
	I stället för att använda `.patch` som suffix för genererade filnamn, använd det angivna suffixet. Ett vanligt alternativ är `--suffix=.txt`. Om du lämnar detta tomt tas suffixet `.patch` bort.
+
Observera att inledande tecken inte behöver vara en punkt; du kan till exempel använda `--suffix=-patch` för att få `0001-beskrivning-av-min-ändringspatch`.

-q::
--quiet::
	Skriv inte ut namnen på de genererade filerna till standardutdata.

--no-binary::
	Visa inte innehållet i ändringarna i binära filer, utan visa i stället ett meddelande om att filerna har ändrats. Patchar som genereras med det här alternativet kan inte tillämpas korrekt, men de är fortfarande användbara för kodgranskning.

--zero-commit::
  Skriv ut en hash med enbart nollor i varje patchs `From:`-huvud i stället för incheckningens hash.

--no-base::
--base[=<incheckning>]::
	Registrera basträdinformationen för att identifiera det tillstånd som patchserien gäller för. Se avsnittet BASTRÄDINFORMATION nedan för mer information. Om <incheckning> är "auto" väljs en basincheckning automatiskt. Alternativet `--no-base` åsidosätter en `format.useAutoBase`-konfiguration.

--root::
	Behandla revisionsargumentet som ett <revisionsintervall>, även om det bara är en enda incheckning (som normalt skulle behandlas som en <sedan>). Observera att rotincheckningar som ingår i det angivna intervallet alltid formateras som skapandepatchar, oberoende av denna flagga.

--progress::
	Visa förloppsrapporter på stderr när patchar genereras.

KONFIGURATION
-------------
Du kan med konfigurationsvariabler ange extra e-posthuvudrader som ska läggas till i varje meddelande, standardvärden för ämnesprefix och filsuffix, numrering av patchar när fler än en patch skrivs ut, `To:`- eller `Cc:`-huvudrader, bilagor, utdatakatalog för patchar samt signoff för patchar.

------------
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <email>
	cc = <email>
	attach [ = mime-boundary-string ]
	signOff = true
	outputDirectory = <directory>
	coverLetter = auto
	coverFromDescription = auto
------------


DISKUSSION
----------

Patchen som produceras av 'git format-patch' är i UNIX-brevlådaformat, med en fast "magisk" tidsstämpel som indikerar att filen matas ut från format-patch snarare än en riktig brevlåda, så här:

------------
arch/arm-konfigurationsfiler bantades ner med hjälp av ett python-skript
(Se kommentaren i incheckning c2330e286f68f1c408b4aa6515ba49d57f05beae)

arch/arm config files were slimmed down using a python script
(See commit c2330e286f68f1c408b4aa6515ba49d57f05beae comment)

Gör samma sak för ia64 så att vi kan få ett elegant och prydligt utseende
...
------------

Vanligtvis placeras den i en MUA:s utkastmapp, redigeras för att lägga till aktuell kommentar som inte ska in i ändringsloggen efter de tre strecken, och skickas sedan som ett meddelande vars brödtext i vårt exempel börjar med "arch/arm config files were...". Hos mottagaren kan läsare spara intressanta patchar i en UNIX-brevlåda och applicera dem med linkgit:git-am[1].

När en patch är del av en pågående diskussion kan patchen som genereras av 'git format-patch' justeras för att dra nytta av funktionen 'git am --scissors'. Efter ditt svar i diskussionen kommer en rad som enbart består av "`-- >8 --`" (sax och perforering), följd av patchen med onödiga huvudrader borttagna:

------------
...
> Så vi borde göra si och så.

Det låter rimligt för mig. Hur är det med den här patchen?

-- >8 --
Subject: [IA64] Lägg till ia64-konfigurationsfiler på Uwe Kleine-König-dieten

arch/arm-konfigurationsfiler bantades ner med hjälp av ett python-skript
...
------------

När du skickar en patch på det här sättet, skickar du oftast din egen patch, så utöver markören "`From $SHA1 $magic_timestamp`" bör du utelämna raderna `From:` och `Date:` från patchfilen. Patchtiteln kommer sannolikt att skilja sig från ämnet för den diskussion som patchen svarar på, så det är troligt att du vill behålla raden Ämne:, som i exemplet ovan.

Kontrollerar om patchkorruption uppstår
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Många e-postklienter korrumperar blanktecken om de inte är rätt konfigurerade. Här är två vanliga typer av korruption:

* Tomma kontextrader som inte har _något_ blanksteg.

* Icke-tomma kontextrader som har ett extra blanksteg i början.

Ett sätt att testa om din MUA är korrekt konfigurerad är:

* Skicka patchen till dig själv, exakt som du annars skulle göra, men med `To:`- och `Cc:`-rader som inte innehåller listans och underhållarens adresser.

* Spara den där patchen till en fil i UNIX-brevlådans format. Kalla den a.patch, till exempel.

* Applicera den:

    $ git fetch <projekt> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

Om den inte går att applicera korrekt kan det bero på flera saker.

* Själva patchen appliceras inte ordentligt. Det är _dåligt_ men har inte mycket att göra med din MUA. I det här fallet kanske du vill ombasera patchen med linkgit:git-rebase[1] innan du genererar den på nytt.

* MUA:n korrumperade din patch; `am` kommer då att klaga på att patchen inte går att applicera. Titta i underkatalogen `.git/rebase-apply/`, se vad filen `patch` innehåller och kontrollera efter de vanliga korruptionsmönster som nämns ovan.

* När du ändå är igång, kontrollera även filerna `info` och `final-commit`. Om innehållet i `final-commit` inte är exakt det du vill se i incheckningsloggmeddelandet är det mycket troligt att mottagaren behöver handredigera loggmeddelandet när patchen appliceras. Saker som "Hi, this is my first patch.\n" i patchmejlet ska komma efter raden med tre bindestreck som markerar slutet på incheckningsmeddelandet.

MUA-SPECIFIKA TIPS
------------------
Här är några tips för hur du skickar in patchar inline på ett fungerande sätt med olika e-postklienter.

GMail
~~~~~
Gmail har inget sätt att stänga av radbrytning i webbgränssnittet, så det kommer att manipulera alla e-postmeddelanden du skickar. Du kan dock använda "git send-email" och skicka dina patchar via Gmails SMTP-server, eller använda valfri IMAP-e-postklient för att ansluta till Googles IMAP-server och vidarebefordra e-postmeddelandena via den.

För tips om hur man använder 'git send-email' för att skicka patchar via Gmails SMTP-server, se EXEMPEL-avsnittet i linkgit:git-send-email[1].

För tips om hur man skickar med IMAP-gränssnittet, se EXEMPEL-avsnittet i linkgit:git-imap-send[1].

Thunderbird
~~~~~~~~~~~
Som standard radbryter Thunderbird både e-postmeddelanden och märker dem som 'format=flowed', vilket gör det resulterande mejlet oanvändbart för Git.

Det finns tre olika sätt: använd ett tillägg för att stänga av radbrytning, konfigurera Thunderbird så att det inte förvanskar patchar, eller använd en extern redigerare för att hindra Thunderbird från att förvanska patcharna.

Metod #1 (tillägg)
^^^^^^^^^^^^^^^^^^

Installera tillägget Toggle Line Wrap som finns tillgängligt från https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap. Det lägger till en knapp "Line Wrap" i verktygsfältet för skrivandet som du kan bocka av. Nu kan du skriva meddelandet som du annars gör (klipp ut + klistra in, 'git format-patch' | 'git imap-send', etc.), men du måste infoga radbrytningar manuellt i all text du skriver.

Som bonus kan tillägget upptäcka patchtext i redigeringsfönstret och varna när radbrytning ännu inte har stängts av.

Tillägget kräver några justeringar av den avancerade konfigurationen (about:config). Dessa listas på nedladdningssidan.

Metod #2 (konfiguration)
^^^^^^^^^^^^^^^^^^^^^^^^
Tre steg:

1. Konfigurera meddelandeskrivning för kontot som vanlig text: Redigera...Kontoinställningar...Sammansättning och adressering, avmarkera "Skriv meddelanden i HTML".

2. Konfigurera ditt allmänna kompositionsfönster så att det inte radbryts.
+
I Thunderbird 2: Redigera..Inställningar..Komposition, radbryt vanliga textmeddelanden vid 0
+
I Thunderbird 3: Redigera..Inställningar..Avancerat..Konfigurationsredigerare. Sök efter "mail.wrap_long_lines". Växla den så att den är inställd på `false`. Sök också efter "mailnews.wraplength" och sätt värdet till 0.

3. Inaktivera användningen av format=flowed: Redigera..Inställningar..Avancerad..Konfigurationsredigerare. Sök efter "mailnews.send_plaintext_flowed". Växla tills den är inställd på `false`.

När detta är gjort bör du kunna skriva e-post som vanligt (klipp + klistra, 'git format-patch' | 'git imap-send', etc.), och patcharna förvanskas inte.

Metod #3 (extern redigerare)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Följande Thunderbird-tillägg behövs: AboutConfig från https://mjg.github.io/AboutConfig/ och External Editor från https://globs.org/articles.php?lng=en&pg=8

1. Förbered patchen som en textfil med hjälp av din valda metod.

2. Innan du öppnar ett skrivfönster, använd Redigera->Kontoinställningar för att avmarkera inställningen "Skriv meddelanden i HTML-format" i panelen "Sammansättning och adressering" för kontot som ska användas för att skicka patchen.

3. I huvudfönstret i Thunderbird, innan du öppnar skrivfönstret för patchen, använd Verktyg->om:config för att ställa in följande till de angivna värdena:
+
----------
	mailnews.send_plaintext_flowed  => false
	mailnews.wraplength             => 0
----------

4. Öppna ett skrivfönster och klicka på ikonen för den externa redigeraren.

5. I det externa redigeringsfönstret läser du in patchfilen och avslutar redigeraren normalt.

Sidoanteckning: det kan vara möjligt att göra steg 2 med about:config och följande inställningar, men ingen har provat det än.

----------
	mail.html_compose                       => false
	mail.identity.default.compose_html      => false
	mail.identity.id?.compose_html          => false
----------

Det finns ett skript i contrib/thunderbird-patch-inline som kan hjälpa dig att lägga till patchar med Thunderbird på ett enkelt sätt. För att använda det, följ stegen ovan och använd sedan skriptet som extern redigerare.

KMail
~~~~~
Det här bör hjälpa dig att skicka in patchar inline med KMail.

1. Förbered patchen som en textfil.

2. Klicka på Nytt meddelande.

3. Gå till "Alternativ" i skrivfönstret och se till att "Word wrap" inte är aktiverat.

4. Använd Meddelande -> Infoga fil... och infoga patchen.

5. Tillbaka i skrivfönstret: lägg till önskad annan text i meddelandet, fyll i adress- och ämnesfälten och tryck på skicka.

BASTRÄDSINFORMATION
-------------------

Informationsblocket för basträdet används så att underhållare eller testare från tredje part ska veta exakt vilket tillstånd patchserien gäller för. Det består av en "base commit", vilket är en välkänd incheckning i den stabila delen av projekthistoriken som andra arbetar utifrån, och noll eller flera "prerequisite patches", det vill säga välkända patchar under arbete som ännu inte ingår i "base commit" och som måste appliceras ovanpå "base commit" i topologisk ordning innan patcharna kan appliceras.

'Base commit' visas som "base-commit: " följt av incheckningsobjektnamnets 40-hex. En 'prerequisite patch' visas som "prerequisite-patch-id: " följt av 40-hex-"patch id", som kan fås genom att köra patchen genom kommandot `git patch-id --stable`.

Tänk dig att du, ovanpå den publika incheckningen P, applicerade välkända patchar X, Y och Z från någon annan och sedan byggde din patchserie med tre patchar: A, B, C. Historiken skulle då se ut så här:

................................................
---P---X---Y---Z---A---B---C
................................................

Med `git format-patch --base=P -3 C` (eller varianter av det, till exempel med `--cover-letter` eller med `Z..C` i stället för `-3 C` för att ange intervallet) visas informationsblocket för basträdet i slutet av det första meddelande som kommandot skriver ut (antingen den första patchen eller följebrevet), så här:

------------
base-commit: P
prerequisite-patch-id: X
prerequisite-patch-id: Y
prerequisite-patch-id: Z
------------

För icke-linjär topologi, som

................................................
---P---X---A---M---C
    \         /
     Y---Z---B
................................................

Du kan också använda `git format-patch --base=P -3 C` för att generera patchar för A, B och C, och identifierarna för P, X, Y, Z läggs till i slutet av det första meddelandet.

Om `--base=auto` anges på kommandoraden beräknas `base commit` automatiskt som merge-bas mellan toppincheckningen för fjärrspårade grenen och revisionsintervallet som anges på kommandoraden. För en lokal gren behöver du först låta den spåra en fjärrgren med `git branch --set-upstream-to` innan du använder detta alternativ.

EXEMPEL
-------

* Extrahera incheckningar mellan revisionerna R1 och R2, och applicera dem ovanpå den aktuella grenen med 'git am' för att cherry-picka dem:
+
------------
$ git format-patch -k --stdout R1..R2 | git am -3 -k
------------

* Extrahera alla incheckningar som finns i den aktuella grenen men inte i grenen origin:
+
------------
$ git format-patch origin
------------
+
För varje incheckning skapas en separat fil i den aktuella katalogen.

* Extrahera alla incheckningar som leder till 'origin' sedan projektets start:
+
------------
$ git format-patch --root origin
------------

* Samma som den föregående:
+
------------
$ git format-patch -M -B origin
------------
+
Dessutom upptäcker och hanterar den namnbyten och fullständiga omskrivningar på ett intelligent sätt för att skapa en namnbytespatch. En namnbytespatch minskar mängden text som skrivs ut och gör det oftast enklare att granska. Observera att icke-Git-"patch"-program inte förstår namnbytespatchar, så använd detta bara när du vet att mottagaren använder Git för att applicera patchen.

* Extrahera de tre senaste incheckningarna från den aktuella grenen och formatera dem som patchar för e-post:
+
------------
$ git format-patch -3
------------

FÖRBEHÅLL
---------

Observera att `format-patch` utelämnar sammanslagningsincheckningar från utdata, även om de ingår i det begärda intervallet. En enkel "patch" innehåller inte tillräckligt med information för att mottagaren ska kunna återskapa samma sammanslagningsincheckning.

SE ÄVEN
-------
linkgit:git-am[1], linkgit:git-send-email[1]

GIT
---
En del av linkgit:git[1]-sviten
