git-http-push(1)
================

NAMN
----
git-http-push - Skicka objekt över HTTP/DAV till ett annat kodförråd


SYNOPSIS
--------
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ref> [<ref>...]

BESKRIVNING
-----------
Skickar saknade objekt till fjärrkodförrådet och uppdaterar fjärrgrenen.

*OBS*: Det här kommandot är tillfälligt inaktiverat om din libcurl är äldre än 7.16, eftersom kombinationen har rapporterats inte fungera och ibland korrumperar kodförrådet.

ALTERNATIV
----------
--all::
	Anta inte att fjärrkodförrådet är komplett i sitt nuvarande tillstånd, och verifiera att alla objekt i hela den lokala referensens historik finns i fjärrkodförrådet.

--force::
	Vanligtvis, vägrar kommandot att uppdatera en fjärrreferens som inte är en förfader till den lokala referens som användes för att skriva över den. Flaggan inaktiverar kontrollen. Det betyder att fjärrkodförrådet kan förlora incheckningar; använd den med försiktighet.

--dry-run::
	Gör allt utom att faktiskt skicka uppdateringarna.

--verbose::
	Rapportera listan över objekt som genomgås lokalt och listan över objekt som har skickats till fjärrkodförrådet.

-d::
-D::
	Ta bort <ref> från fjärrkodförrådet. Den angivna grenen kan inte vara fjärr-HEAD. Om -d anges måste följande andra villkor också vara uppfyllda:

	- Fjärr HEAD måste tolkas som ett objekt som finns lokalt
	- En angiven gren matchar ett objekt som finns lokalt
	- Den angivna grenen är en förfader till den fjärr HEAD

<ref>...::
	Fjärrreferenserna att uppdatera.


SPECIFIERING AV REFERENSERNA
----------------------------

En '<ref>'-specifikation kan antingen vara ett enda mönster eller ett par sådana mönster separerade med ett kolon ":" (detta betyder att ett referensnamn inte kan innehålla ett kolon). Ett enda mönster '<namn>' är bara en förkortning för '<namn>:<namn>'.

Varje mönsterpar '<src>:<dst>' består av källsidan (före kolon) och destinationssidan (efter kolon). Referensen som ska skickas bestäms genom att hitta en matchning som matchar källsidan, och var den skickas bestäms med hjälp av destinationssidan.

 - Det är ett fel om '<src>' inte exakt matchar en av de lokala referenserna.

 - Om '<dst>' inte matchar någon fjärrreferens, antingen

   * den måste börja med "refs/"; <dst> används bokstavligen som destination i det här fallet.

   * <src> == <dst> och referensen som matchade <src> får inte finnas i uppsättningen fjärrreferenser; referensen som matchade <src> lokalt används som namn på destinationen.

Utan `--force` lagras <src>-referensen på fjärren endast om <dst> inte finns, eller om <dst> är en korrekt delmängd (d.v.s. en förfader) till <src>. Kontrollen, kallad "snabbspolningskontroll", görs för att undvika att av misstag skriva över fjärrreferensen och förlora andra personers incheckningar därifrån.

Med `--force` inaktiveras snabbspolning för alla referenser.

Valfritt, kan en <ref>-parameter prefixas med ett plustecken '+' för att inaktivera snabbspolning endast på den referensen.

GIT
---
En del av linkgit:git[1]-sviten
