git-sh-setup(1)
===============

NAMN
----
git-sh-setup - Vanlig installationskod för Git-shellskript

SYNOPSIS
--------
[verse]
'. "$(git --exec-path)/git-sh-setup"'

BESKRIVNING
-----------

Detta är inte ett kommando som slutanvändaren någonsin skulle vilja köra. Den här dokumentationen är avsedd för personer som studerar Porslinsliknande skript och/eller skriver nya.

Skriptleten 'git sh-setup' är utformad för att hämtas (med `.`) från andra shell-skript för att ställa in vissa variabler som pekar mot de vanliga Git-katalogerna och några få hjälpfunktioner i shell-skriptet.

Innan du skapar sourcade-funktioner bör ditt skript ställa in några variabler; `USAGE` (och `LONG_USAGE`, om sådan finns) används för att definiera meddelandet som ges av skalfunktionen `usage()`. `SUBDIRECTORY_OK` kan ställas in om skriptet kan köras från en underkatalog i arbetskatalogen (vissa kommandon gör det inte).

Skriptleten anger skalvariablerna `GIT_DIR` och `GIT_OBJECT_DIRECTORY`, men exporterar dem *inte* till miljön.

FUNKTIONER
----------

die::
	avsluta efter att ha skickat det angivna felmeddelandet till standardfelströmmen.

usage::
	dö med användningsmeddelandet.

set_reflog_action::
	Sätt `GIT_REFLOG_ACTION`-miljön till en given sträng (vanligtvis programmets namn) om den inte redan är angiven. Närhelst skriptet kör ett `git`-kommando som uppdaterar referenser skapas en reflog-post med värdet på denna sträng för att lämna posten över vilket kommando som uppdaterade referensen.

git_editor::
	kör en editor som användaren väljer (GIT_EDITOR, core.editor, VISUAL eller EDITOR) på en given fil, men ger ett felmeddelande om ingen editor anges och terminalen är dum.

is_bare_repository::
	matar ut `sant` eller `false` till standardutdataströmmen för att indikera om kodförrådet är ett bart förråd (dvs. utan ett associerad arbetskatalog).

cd_to_toplevel::
	Kör chdir till den översta nivån i arbetskatalogen.

require_work_tree::
	kontrollerar om den aktuella katalogen finns inom kodförrådets arbetskatalog, och dör annars.

require_work_tree_exists::
	kontrollerar om arbetskatalog som är associerat med kodförrådet existerar, och dör annars. Görs ofta innan cd_to_toplevel anropas, vilket är omöjligt att göra om det inte finns någon arbetskatalog.

require_clean_work_tree <handling> [<ledtråd>]::
	kontrollerar att arbetskatalog och indexet som är associerat med arkivet inte har några obekräftade ändringar i spårade filer. Annars visas ett felmeddelande av typen `Kan inte <åtgärd>: <orsak>. <ledtråd>` och programmet dör. Exempel:
+
----------------
require_clean_work_tree rebase "Var god och checka-in eller göm dem."
----------------

get_author_ident_from_commit::
	matar ut kod för användning med eval för att ställa in variablerna GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL och GIT_AUTHOR_DATE för en given incheckning.

create_virtual_base::
	ändrar den första filen så att endast rader som är gemensamma med den andra filen återstår. Om det inte finns tillräckligt med gemensamt material lämnas den första filen tom. Resultatet är lämpligt som en virtuell basindata för en 3-vägs sammanslagning.

GIT
---
En del av linkgit:git[1]-sviten
