git-patch-id(1)
===============

NAMN
----
git-patch-id - Beräkna unikt ID för en patch

SYNOPSIS
--------
[synopsis]
git patch-id [--stable | --unstable | --verbatim]

BESKRIVNING
-----------
Läs en patch från standard-in och beräkna patch-ID:t för den.

Ett "patch-ID" är inget annat än en summa av SHA-1 för fildifferenserna som är associerade med en patch, med radnummer ignorerade. Som sådan är det "rimligt stabilt", men samtidigt också rimligt unikt, d.v.s. två patchar som har samma "patch-ID" är nästan garanterat samma sak.

Det huvudsakliga användningsområdet för det här kommandot är att leta efter sannolika dubbletter av incheckningar.

När man hanterar `git diff-tree`-utdata utnyttjar den det faktum att patchen har prefixet med incheckningens objektnamn och matar ut två 40-byte hexadecimala strängar. Den första strängen är patch-ID:t och den andra strängen är inchecknings-ID:t. Detta kan användas för att göra en mappning från patch-ID till inchecknings-ID.

ALTERNATIV
----------

`--verbatim`::
	Beräkna patch-id för indata som det ges, ta inte bort något blanksteg.
+
Detta är standardvärdet om `patchid.verbatim` är `true`.

`--stable`::
	Använd en "stabil" summa av hashvärden som patch-ID. Med det här alternativet:
+
--
- Att ändra ordning på fildifferenser som utgör en patch påverkar inte ID:t. I synnerhet resulterar två patchar som produceras genom att jämföra samma två träd med två olika inställningar för `-O<orderfile>` i samma patch-ID-signatur, vilket gör att det beräknade resultatet kan användas som en nyckel för att indexera viss metainformation om förändringen mellan de två träden;

- Resultatet skiljer sig från värdet som produceras av git 1.9 och äldre eller produceras när en "instabil" hash (se `--unstable` nedan) konfigureras - även när den används på en diff-utdata som tas utan användning av `-O<orderfile>`, vilket gör befintliga databaser som lagrar sådana "instabila" eller historiska patch-id:n oanvändbara.

- Allt blanktecken i patchen ignoreras och påverkar inte id:t.
--
+
Detta är standardvärdet om `patchid.stable` är satt till `true`.

`--unstable`::
	Använd en "instabil" hash som patch-ID. Med det här alternativet är resultatet kompatibelt med patch-id-värdet som produceras av git 1.9 och äldre, och blanksteg ignoreras. Användare med befintliga databaser som lagrar patch-id:n som produceras av git 1.9 och äldre (som inte hanterar omordnade patchar) kanske vill använda det här alternativet.
+
Detta är standardvärdet.

GIT
---
En del av linkgit:git[1]-sviten
