git-bugreport(1)
================

NAMN
----
git-bugreport - Samla in information för att användaren ska kunna göra en felrapport

SYNOPSIS
--------
[verse]
'git bugreport' [(-o | --output-directory) <sökväg>]
		[(-s | --suffix) <format> | --no-suffix]
		[--diagnose[=<läge>]]

BESKRIVNING
-----------
Samlar in information om användarens maskin, Git-klient och kodförrådets tillstånd, utöver ett formulär som begär information om det beteende som användaren observerat, och lagrar det i en enda textfil som användaren sedan kan dela, till exempel till Git-mejllistan, för att rapportera en observerad programfel.

Följande information begärs från användaren:

 - Reproduktionssteg
 - Förväntat beteende
 - Faktiskt beteende

Följande information samlas in automatiskt:

 - 'git version --build-options'
 - uname sysnamn, release, version och maskinsträngar
 - Kompilatorspecifik informationssträng
 - En lista över aktiverade krokar
 - $SHELL

Ytterligare information kan samlas in i ett separat zip-arkiv med hjälp av alternativet `--diagnose` och kan bifogas tillsammans med felrapporteringsdokumentet för att ge läsarna ytterligare kontext.

Det här verktyget anropas via den typiska Git-installationsprocessen, vilket innebär att det i vissa fall kanske inte kan startas - till exempel om en relevant konfigurationsfil är oläslig. I den här typen av scenario kan det vara bra att manuellt samla in den typ av information som anges ovan när man manuellt ber om hjälp.

ALTERNATIV
----------
-o <sökväg>::
--output-directory <sökväg>::
	Placera den resulterande felrapportfilen i `<sökväg>` i stället för den aktuella katalogen.

-s <format>::
--suffix <format>::
--no-suffix::
	Ange ett alternativt suffix för felrapportens namn för att skapa en fil med namnet 'git-bugreport-<formaterat-suffix>'. Detta bör ha formen av en strftime(3)-formatsträng; den aktuella lokala tiden kommer att användas. `--no-suffix` inaktiverar suffixet och filen heter bara `git-bugreport` utan någon särskiljnings-åtgärd.

--no-diagnose::
--diagnose[=<läge>]::
	Skapa ett zip-arkiv med kompletterande information om användarens maskin, Git-klient och kodförrådets tillstånd. Arkivet skrivs till samma utdatakatalog som felrapporten och heter 'git-diagnostics-<formaterat-suffix>'.
+
Utan att `läge` anges kommer det diagnostiska kodförrådet att innehålla standarduppsättningen statistik som rapporteras av `git diagnose`. Ett valfritt `läge`-värde kan anges för att ändra vilken information som inkluderas i kodförrådet. Se linkgit:git-diagnose[1] för en lista över giltiga värden för `läge` och detaljer om deras användning.

GIT
---
En del av linkgit:git[1]-sviten
