git-count-objects(1)
====================

NAMN
----
git-count-objects - Räkna antalet uppackade objekt och deras diskförbrukning

SYNOPSIS
--------
[verse]
'git count-objects' [-v] [-H | --human-readable]

BESKRIVNING
-----------
Räknar antalet upppackade objektfiler och det diskutrymme som förbrukas av dem, för att hjälpa dig att avgöra när det är en bra tidpunkt att packa om.


ALTERNATIV
----------
-v::
--verbose::
	Ge mer detaljerade rapporter:
+
antal: antalet lösa objekt
+
storlek: diskutrymme som förbrukas av lösa objekt, i KiB (om inte -H anges)
+
in-pack: antalet objekt i packetet
+
paket: antalet paketfiler
+
size-pack: diskutrymme som förbrukas av paketen, i KiB (om inte -H anges)
+
prune-packable: antalet lösa objekt som också finns i paketen. Dessa objekt kan beskäras med hjälp av `git prune-packed`.
+
garbage: antalet filer i objektdatabasen som varken är giltiga lösa objekt eller giltiga paket
+
size-garbage: diskutrymme som förbrukas av skräpfiler, i KiB (om inte -H anges)
+
alternativ: absolut sökväg för alternativa objektdatabaser; kan förekomma flera gånger, en rad per sökväg. Observera att om sökvägen innehåller tecken som inte kan skrivas ut kan den omges av dubbla citattecken och innehålla bakåtsnedstreck escape-sekvenser i C-stil.

-H::
--human-readable::

Utskriftsstorlekar i människoläsbart format

GIT
---
En del av linkgit:git[1]-sviten
