git-mergetool{litdd}lib(1)
==========================

NAMN
----
git-mergetool--lib - Vanliga Git-sammanslagningsverktyg skal skriptlets

SYNOPSIS
--------
[verse]
'TOOL_MODE=(diff|merge) . "$(git --exec-path)/git-mergetool{litdd}lib"'

BESKRIVNING
-----------

Detta är inte ett kommando som slutanvändaren någonsin skulle vilja köra. Den här dokumentationen är avsedd för personer som studerar Porslinsliknande skript och/eller skriver nya.

Skriptleten 'git-mergetool{litdd}lib' är utformad för att source:as (med hjälp av `.`) från andra skalskript för att konfigurera funktioner för att arbeta med Git-sammanslagningsverktyg.

Innan du hämtar sourcade-värdet 'git-mergetool{litdd}lib' måste ditt skript ställa in `TOOL_MODE` för att definiera operationsläget för funktionerna som listas nedan. 'diff' och 'merge' är giltiga värden.

FUNKTIONER
----------
get_merge_tool::
	Returnerar ett sammanslagningsverktyg. Returkoden är 1 om vi returnerade ett gissat sammanslagningsverktyg, annars 0. '$GIT_MERGETOOL_GUI' kan sättas till 'true' för att söka efter lämpligt grafiskt verktyg.

get_merge_tool_cmd::
	Returnerar det anpassade kommandot för ett sammanslagningsverktyg.

get_merge_tool_path::
	Returnerar den anpassade sökvägen för ett sammanslagningsverktyg.

initialize_merge_tool::
	Tar specifika funktioner för sammanslagningsverktyget med i omfånget så att de kan användas eller åsidosättas.

run_merge_tool::
	Startar ett sammanslagningsverktyg med verktygsnamnet och en sant/falskt-flagga som indikerar om en sammanslagningsbas finns. '$MERGED', '$LOCAL', '$REMOTE' och '$BASE' måste definieras för att användas av sammanslagningsverktyget.

GIT
---
En del av linkgit:git[1]-sviten
