git-hash-object(1)
==================

NAMN
----
git-hash-object - Beräkna objekt-ID och möjligen skapa ett objekt från en fil


SYNOPSIS
--------
[verse]
'git hash-object' [-t <typ>] [-w] [--path=<fil> | --no-filters]
		[--stdin [--literally]] [--] <fil>...
'git hash-object' [-t <typ>] [-w] --stdin-paths [--no-filters]

BESKRIVNING
-----------
Beräknar objekt-ID-värdet för ett objekt med angiven typ med innehållet i den namngivna filen (som kan finnas utanför arbetsträdet) och skriver eventuellt det resulterande objektet till objektdatabasen. Rapporterar dess objekt-ID till standardutdata. När <typ> inte anges används som standard "blob".

ALTERNATIV
----------

-t <typ>::
	Ange vilken typ av objekt som ska skapas (standard: "blob"). Möjliga värden är `commit`, `tree`, `blob` och `tag`.

-w::
	Skriv faktiskt objektet in i objektdatabasen.

--stdin::
	Läs objektet från standardindata i stället för från en fil.

--stdin-paths::
	Läs filnamn från standardinmatningen, ett per rad, i stället för från kommandoraden.

--path::
	Hasha objektet som om det vore placerat på den givna sökvägen. Filens plats påverkar inte direkt hashvärdet, men sökvägen används för att avgöra vilka Git-filter som ska tillämpas på objektet innan det kan placeras i objektdatabasen. Som ett resultat av att filter tillämpas kan den faktiska blobben som placeras i objektdatabasen skilja sig från den givna filen. Det här alternativet är främst användbart för att hasha temporära filer som finns utanför arbetskatalogen eller filer som läses från stdin.

--no-filters::
	Hasha innehållet som det är, och ignorera eventuella inmatningsfilter som skulle ha valts av attributmekanismen, inklusive konverteringen vid radslut. Om filen läses från standardindata är detta alltid underförstått, såvida inte alternativet `--path` anges.

--literally::
	Tillåter `--stdin` att hasha skräp till ett löst objekt som annars kanske inte skulle klara standardobjektparsning eller git-fsck-kontroller. Användbart för att stresstesta Git självt eller för att reproducera egenskaper hos korrupta eller falska objekt som påträffas i fritt tillstånd.

GIT
---
En del av linkgit:git[1]-sviten
