git-remote-ext(1)
=================

NAMN
----
git-remote-ext - Brygga smart transport till externt kommando.

SYNOPSIS
--------
[verse]
git remote add <smek> "ext::<kommando>[ <argument>...]"

BESKRIVNING
-----------
Denna fjärr-hjälpprogram använder det angivna '<kommandot>' för att ansluta till en fjärransluten Git-server.

Data som skrivs till stdin för det angivna '<kommando>' antas skickas till en git://-server, git-upload-pack, git-receive-pack eller git-upload-archive (beroende på situationen), och data som läses från stdout för <kommando> antas tas emot från samma tjänst.

Kommando och argument separeras med ett icke-escapat mellanslag.

Följande sekvenser har en speciell betydelse:

'% '::
	Bokstavligt mellanslag i kommando eller argument.

'%%'::
	Procenttecken.

'%s'::
	Ersatt med namnet (receive-pack, upload-pack eller upload-archive) på den tjänst som Git vill anropa.

'%S'::
	Ersatt med det långa namnet (git-receive-pack, git-upload-pack eller git-upload-archive) på tjänsten som Git vill anropa.

'%G' (måste vara de första tecknen i ett argument)::
	Detta argument kommer inte att skickas till '<kommando>'. Istället kommer det att få hjälpen att börja med att skicka git://-tjänstförfrågningar till fjärrsidan med servicefältet inställt på ett lämpligt värde och kodförråd-fältet inställt på resten av argumentet. Standardinställningen är att inte skicka en sådan begäran.
+
Detta är användbart om fjärrsidan är git://-servern som nås via någon tunnel.

'%V' (måste vara de första tecknen i argumentet)::
	Detta argument kommer inte att skickas till '<kommando>'. Istället sätter det vhost-fältet i git://-tjänstförfrågan (till resten av argumentet). Standardinställningen är att inte skicka vhost i en sådan förfrågan (om den skickas).

MILJÖVARIABLER
--------------

GIT_TRANSLOOP_DEBUG::
	Om angivet skrivs felsökningsinformation om olika läsningar/skrivningar ut.

MILJÖVARIABLER SKICKAS TILL KOMMANDO
------------------------------------

GIT_EXT_SERVICE::
	Sätt till långt namn (git-upload-pack, etc...) på den tjänst-hjälpprogram som behöver anropas.

GIT_EXT_SERVICE_NOPREFIX::
	Ställ in det långa namnet (upload-pack, etc...) på den tjänst-hjälpprogram som behöver anropas.


EXEMPEL
-------
Denna fjärrhjälp används transparent av Git när du använder kommandon som "git fetch <URL>", "git clone <URL>", , "git push <URL>" eller "git remote add <nick> <URL>", där <URL> börjar med `ext::`. Exempel:

"ext::ssh -i /home/foo/.ssh/somekey user&#64;host.example %S 'foo/repo'"::
	Som host.example:foo/repo, men använd /home/foo/.ssh/någonnyckel som nyckelpar och user som användare på fjärrsidan. Detta undviker behovet av att redigera .ssh/config.

"ext::socat -t3600 - ABSTRACT-CONNECT:/git-server %G/somerepo"::
	Representerar repot med sökvägen /somerepo åtkomlig via git-protokollet vid den abstrakta namnrymdsadressen /git-server.

"ext::git-server-alias foo %G/repo"::
	Representerar ett kodförråd med sökvägen /repo som nås med hjälpprogrammet "git-server-alias foo". Sökvägen till repository och typen av begäran skickas inte på kommandoraden utan som en del av protokollströmmen, som vanligt med git://-protokollet.

"ext::git-server-alias foo %G/repo %Vfoo"::
	Representerar ett kodförråd med sökvägen /repo som nås med hjälp av hjälpprogrammet "git-server-alias foo". Värdnamnet för fjärrservern som skickas i protokollströmmen blir "foo" (detta tillåter flera virtuella Git-servrar att dela en länknivåadress).

"ext::git-server-alias foo %G/repo% with% spaces %Vfoo"::
	Representerar ett kodförråd med sökvägen `/repo with spaces` som nås med hjälp av hjälpprogrammet "git-server-alias foo". Värdnamnet för fjärrservern som skickas i protokollströmmen kommer att vara "foo" (detta tillåter flera virtuella Git-servrar att dela en länknivåadress).

"ext::git-ssl foo.example /bar"::
	Representerar ett kodförråd som nås med hjälpprogrammet "git-ssl foo.example /bar". Typen av begäran kan bestämmas av hjälpprogrammet med hjälp av miljövariabler (se ovan).

SE ÄVEN
-------
linkgit:gitremote-helpers[7]

GIT
---
En del av linkgit:git[1]-sviten
