git-ls-remote(1)
================

NAMN
----
git-ls-remote - Lista referenser i ett fjärrkodförråd


SYNOPSIS
--------
[verse]
<exec><exec><exec>'git ls-remote' [--branches] [--tags] [--refs] [--upload-pack=<exec>]
	      [-q | --quiet] [--exit-code] [--get-url] [--sort=<nyckel>]
	      [--symref] [<kodförråd> [<mönster>...]]

BESKRIVNING
-----------
Visar referenser som är tillgängliga i ett fjärrkodförråd tillsammans med tillhörande inchecknings-ID:n.


ALTERNATIV
----------
-b::
--branches::
-t::
--tags::
	Begränsa till endast lokala grenar respektive lokala taggar. Dessa alternativ utesluter _inte_ varandra; när båda anges visas referenser lagrade i refs/heads och refs/tags. Observera att `--heads` och `-h` är föråldrade synonymer för `--branches` och `-b` och kan komma att tas bort i framtiden. Observera också att `git ls-remote -h` som används utan något annat på kommandoraden ger hjälp, i linje med andra git-underkommandon.

--refs::
	Visa inte avskalade taggar eller pseudorefs som `HEAD` i utdata.

-q::
--quiet::
	Skriv inte ut fjärr-URL till stderr.

--upload-pack=<exec>::
	Ange den fullständiga sökvägen för 'git-upload-pack' på fjärrvärden. Detta gör det möjligt att lista referenser från kodförråd som nås via SSH och där SSH-daemonen inte använder den PATH som konfigurerats av användaren.

--exit-code::
	Avsluta med status "2" när inga matchande referenser hittas i fjärrkodförrådet. Vanligtvis avslutas kommandot med status "0" för att indikera att det har kommunicerat med fjärrkodförrådet och om det hittat några matchande referenser.

--get-url::
	Expandera URL:en för det givna fjärrkodförrådet med hänsyn till eventuella konfigurationsinställningar för "url.<bas>.insteadOf" (se linkgit:git-config[1]) och avsluta utan att prata med fjärren.

--symref::
	Förutom objektet som den pekar på, visa den underliggande referensen som den pekar på när en symbolisk referens visas. För närvarande visar upload-pack bara symref HEAD, så det kommer att vara den enda som visas av ls-remote.

--sort=<nyckel>::
	Sortera baserat på den angivna nyckeln. Prefixet `-` för att sortera i fallande ordning efter värdet. Stöder "version:refnamn" eller "v:refname" (taggnamn behandlas som versioner). Sorteringsordningen "version:refnamn" kan också påverkas av konfigurationsvariabeln "versionsort.suffix". Se linkgit:git-for-each-ref[1] för fler sorteringsalternativ, men var medveten om att nycklar som `incheckingsdatum` som kräver åtkomst till själva objekten inte fungerar för referenser vars objekt ännu inte har hämtats från fjärren och kommer att ge ett `missing object`-fel.

-o <alternativ>::
--server-option=<alternativ>::
	Skicka den givna strängen till servern vid kommunikation med protokollversion 2. Den givna strängen får inte innehålla ett NUL- eller LF-tecken. När flera `--server-option=<alternativ>` anges skickas de alla till den andra sidan i den ordning som anges på kommandoraden. När ingen `--server-option=<alternativ>` anges från kommandoraden används värdena för konfigurationsvariabeln `remote.<namn>.serverOption` istället.

<kodförråd>::
	"Fjärr"-kodförrådet som ska frågas. Denna parameter kan antingen vara en URL eller namnet på en fjärransluten enhet (se avsnitten GIT URLS och FJÄRR i linkgit:git-fetch[1]).

<mönster>...::
	När de inte anges, visas alla referenser, efter filtrering gjord med --heads och --tags. När <mönster>... anges visas endast referenser som matchar ett eller flera av de givna mönstren. Varje mönster tolkas som en glob (se `glob` i linkgit:gitglossary[7]) som matchas mot "svansen" av en referens, med början antingen från början av referensen (så ett fullständigt namn som `refs/heads/foo` matchar) eller från ett snedstreckavgränsare (så `bar` matchar `refs/heads/bar` men inte `refs/heads/foobar`).

UTMATNING
---------

Utdata är i formatet:

------------
<oid> TAB <ref> LF
------------

När en kommenterad tagg visas, såvida inte `--refs` anges, visas två sådana rader: en med själva taggens refnamn som `<ref>`, och en annan med `<ref>` följt av `^{}`. `<oid>` på den senare raden visar namnet på objektet som taggen pekar på.

EXEMPEL
-------

* Lista alla referenser (inklusive symboler och pseudorefs), avskalnings-taggar:
+
----
$ git ls-remote
27d43aaaf50ef0ae014b88bba294f93658016a2e	HEAD
950264636c68591989456e3ba0a5442f93152c1a	refs/heads/main
d9ab777d41f92a8c1684c91cfb02053d7dd1046b	refs/heads/next
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

* Lista alla referenser som matchar givna mönster:
+
----
$ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740	refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061	refs/heads/seen
----

* Lista endast taggar som matchar ett givet jokerteckenmönster:
+
----
$ git ls-remote --tags http://www.kernel.org/pub/scm/git/git.git v\*
485a869c64a68cc5795dd99689797c5900f4716d	refs/tags/v2.39.2
cbf04937d5b9fcf0a76c28f69e6294e9e3ecd7e6	refs/tags/v2.39.2^{}
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

SE ÄVEN
-------
linkgit:git-check-ref-format[1].

GIT
---
En del av linkgit:git[1]-sviten
