git-pull(1)
===========

NAMN
----
git-pull - Hämta från och integrera med annat kodförråd eller en lokal gren


SYNOPSIS
--------
[synopsis]
git pull [<flaggor>] [<kodförråd> [<refspec>...]]


BESKRIVNING
-----------

Integrera ändringar från ett fjärrkodförråd i den aktuella grenen.

Först kör `git pull` `git fetch` med samma argument (exklusive sammanslagningsalternativ) för att hämta fjärrgren(ar). Sedan bestämmer den vilken fjärrgren som ska integreras: om du kör `git pull` utan argument används som standard <<UPSTREAM-BRANCHES,upstream>> för den aktuella grenen. Sedan integreras den grenen i den aktuella grenen.

Det finns fyra huvudalternativ för att integrera fjärrgrenen:

1. `git pull --ff-only` gör endast snabbspolningsuppdateringar: det misslyckas om din lokala gren har divergerat från fjärrgrenen. Detta är standard.
2. `git pull --rebase` kör `git rebase`
3. `git pull --no-rebase` kör `git merge`.
4. `git pull --squash` kör `git merge --squash`

Du kan också ställa in konfigurationsalternativen `pull.rebase`, `pull.squash` eller `pull.ff` med ditt föredragna beteende.

Om det uppstår en sammanslagningskonflikt under sammanslagningen eller ombasering som du inte vill hantera, kan du säkert avbryta den med `git merge --abort` eller `git rebase --abort`.

ALTERNATIV
----------

_<repository>_::
	"Fjärr"-kodförrådet att hämta från. Detta kan antingen vara en URL (se avsnittet <<URLS,GIT URLS>> nedan) eller namnet på en fjärr (se avsnittet <<REMOTES,FJÄRRAR>> nedan).
+
Standardinställningen är den konfigurerade uppströmsfilen för den aktuella grenen, eller `origin`. Se <<UPSTREAM-BRANCHES,UPPSTRÖMS-GRENAR>> nedan för mer information om hur man konfigurerar uppströmsfilar.

_<refspec>_::
	Vilken gren eller annan referens(er) som ska hämtas och integreras i den aktuella grenen, till exempel `main` i `git pull origin main`. Standardinställningen är den konfigurerade uppström för den aktuella grenen.
+
Det kan vara en gren, tagg eller annan samling av referenser. Se <<fetch-refspec,_<refspec>_>> nedan under "Alternativ relaterade till hämtning" för den fullständiga syntaxen, och <<DEFAULT-BEHAVIOUR,STANDARDBETEENDE>> nedan för hur `git pull` använder detta argument för att avgöra vilken fjärrgren som ska integreras.

`-q`::
`--quiet`::
	Detta skickas både till underliggande git-fetch för att tysta rapporteringen under överföring och till underliggande git-merge för att tysta utdata under sammanslagning.

`-v`::
`--verbose`::
	Skicka `--verbose` till git-fetch och git-merge.

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	Alternativet styr om nya incheckningar för ifyllda undermoduler ska hämtas, och om de fungerande träden för aktiva undermoduler också ska uppdateras (se linkgit:git-fetch[1], linkgit:git-config[1] och linkgit:gitmodules[5]).
+
Om utcheckningen görs via ombasering, ombaseras även lokala undermodul-incheckningar.
+
Om uppdateringen görs via sammanslagning, löses undermodulkonflikterna och de checkas ut.

Alternativ gällande sammanslagning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; Ombasera den aktuella grenen ovanpå den uppströms grenen efter hämtning. Om det finns en fjärrspårad gren som motsvarar den uppströms grenen och den uppströms grenen har ombaserats sedan den senaste hämtningen, använder ombasen den informationen för att undvika ombasering av icke-lokala ändringar. Detta är standardinställningen.

`merges`;; ombasering med `git rebase --rebase-merges` så att de lokala sammanslagningsincheckningar inkluderas i rebasen (se linkgit:git-rebase[1] för detaljer).
`false`;; sammanfoga den uppströms grenen med den nuvarande grenen.
`interactive`;; aktivera det interaktiva läget för ombasering.

+
Se `pull.rebase`, `branch.<name>.rebase` och `branch.autoSetupRebase` i linkgit:git-config[1] om du vill att `git pull` alltid ska använda `--rebase` i stället för sammanslagning.
+
[NOTE]
Det är ett potentiellt _farligt_ driftläge. Det skriver om historiken, vilket inte bådar gott när du redan har publicerat den historiken. Använd *inte* det här alternativet om du inte har läst linkgit:git-rebase[1] noggrant.

`--no-rebase`::
	Detta är en förkortning för `--rebase=false`.

Alternativ gällande hämtningar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
STANDARDBETEENDE
----------------

Ofta använder man `git pull` utan att ange någon parameter. Traditionellt har detta motsvarat att säga `git pull origin`. Men när konfigurationen `branch.<namn>.remote` finns på grenen `<namn>`, används det värdet i stället för `origin`.

För att avgöra vilken URL som ska användas för att hämta från, konsulteras värdet för konfigurationen `remote.<fjärr>.url` och om det inte finns någon sådan variabel används värdet på raden `URL:` i `$GIT_DIR/remotes/<fjärr>`.

För att avgöra vilka fjärrgrenar som ska hämtas (och eventuellt lagras i fjärrspårade grenar) när kommandot körs utan några refspecsparametrar på kommandoraden, används värdena i konfigurationsvariabeln `remote.<fjärr>.fetch`. Om inga finns används i stället `$GIT_DIR/remotes/<fjärr>` och dess `Pull:`-rader. Utöver refspecsformaten som beskrivs i avsnittet OPTIONS kan du använda en globbande refspec som ser ut så här:

------------
refs/heads/*:refs/remotes/origin/*
------------

En globbande refspec måste ha en icke-tom RHS (d.v.s. måste lagra det som hämtades i fjärrspårade grenar), och dess LHS och RHS måste sluta med `/*`. Ovanstående anger att alla fjärrgrenar spåras med hjälp av fjärrspårade grenar i `refs/remotes/origin/`-hierarkin under samma namn.

Regeln för att avgöra vilken fjärrgren som ska sammanfogas efter hämtning är lite invecklad för att inte bryta bakåtkompatibiliteten.

Om explicita referensspecifikationer angavs på kommandoraden för `git pull`, slås de alla samman.

När ingen referensspecifikation angavs på kommandoraden använder `git pull` refspec från konfigurationen eller `$GIT_DIR/remotes/<fjärr>`. I sådana fall gäller följande regler:

. Om konfigurationen `branch.<name>.merge` finns för den aktuella grenen _<name>_, är det namnet på grenen på fjärrsidan som sammanfogas.

. Om referensspecifikationifikationen är en globbing-specifikation slås ingenting samman.

. Annars slås den fjärrgrenen av den första referensspecifikationifikationen samman.


EXEMPEL
-------

* Uppdatera grenarna för fjärrspårning för det kodförrådet du klonade från, och sammanfoga sedan en av dem med din nuvarande gren:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
Normalt är den gren som sammanfogas in fjärrkodförrådets `HEAD`, men valet avgörs av alternativen `branch.<name>.remote` och `branch.<name>.merge`; se linkgit:git-config[1] för detaljer.

* Sammanfoga den fjärrstyrda grenen `next` med den aktuella grenen:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
Det lämnar en kopia av `next` tillfälligt i `FETCH_HEAD` och uppdaterar fjärrspårade grenen `origin/next`. Detsamma kan göras genom att anropa fetch och merge:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


If you tried a pull which resulted in complex conflicts and would want to start over, you can recover with `git reset`.


include::transfer-data-leaks.adoc[]

BUGGAR
------
Att använda `--recurse-submodules` kan bara hämta nya incheckningar i redan utcheckade undermoduler just nu. När t.ex. upstream lägger till en ny undermodul i de just hämtade incheckningar i superprojektet kan inte själva undermodulen hämtas, vilket gör det omöjligt att checka ut den undermodulen senare utan att behöva göra en hämtning (fetch) igen. Detta förväntas bli åtgärdat i en framtida Git-version.

SE ÄVEN
-------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
En del av linkgit:git[1]-sviten
