git-upload-archive(1)
=====================

NAMN
----
git-upload-archive - Skicka arkivet tillbaka till git-archive


SYNOPSIS
--------
[verse]
'git upload-archive' <kodförråd>

BESKRIVNING
-----------
Anropas av 'git archive --remote' och skickar ett genererat arkiv till den andra änden via Git-protokollet.

Detta kommando anropas vanligtvis inte direkt av slutanvändaren. Användargränssnittet för protokollet finns på sidan "git archive", och programparet är avsett att användas för att hämta ett arkiv från ett fjärr-kodförråd.

SÄKERHET
--------

För att skydda integriteten för objekt som har tagits bort från historiken men kanske ännu inte har beskurits, undviker `git-upload-archive` att visa arkiv för incheckningar och träd som inte är nåbara från kodförrådets referenser. Men eftersom det är beräkningsmässigt dyrt att beräkna objektnåbarhet implementerar `git-upload-archive` en striktare men lättare att kontrollera uppsättning regler:

  1. Klienter kan begära en incheckning eller ett träd som pekas direkt till av en referens. T.ex. `git archive --remote=origin v1.0`.

  2. Klienter kan begära ett underträd inom en incheckning eller ett träd med hjälp av syntaxen `ref:path`. T.ex. `git archive --remote=origin v1.0:Documentation`.

  3. Klienter får _inte_ använda andra sha1-uttryck, även om slutresultatet är nåbart. T.ex. är varken en relativ incheckning som `master^` eller en literal sha1 som `abcd1234` är tillåten, även om resultatet är nåbart från referenserna.

Observera att regel 3 inte tillåter många fall som inte har några integritetskonsekvenser. Dessa regler kan komma att ändras i framtida versioner av git, och servern som nås av `git archive --remote` kan följa dessa exakta regler, men behöver inte följa dem.

Om konfigurationsalternativet `uploadArchive.allowUnreachable` är sant ignoreras dessa regler och klienter kan använda godtyckliga sha1-uttryck. Detta är användbart om du inte bryr dig om integriteten för oåtkomliga objekt, eller om din objektdatabas redan är offentligt tillgänglig för åtkomst via icke-smart-http.

ALTERNATIV
----------
<kodförråd>::
	Förvar att hämta ett tar-arkiv från.

GIT
---
En del av linkgit:git[1]-sviten
