git-mv(1)
=========

NAMN
----
git-mv - Flytta eller byt namn på en fil, katalog eller symbolisk länk


SYNOPSIS
--------

[synopsis]
git mv [-v] [-f] [-n] [-k] <källa> <destination>
git mv [-v] [-f] [-n] [-k] <källa>... <destinations-katalog>

BESKRIVNING
-----------
Flytta eller byt namn på en fil, katalog eller symbolisk länk.

I den första formen byter den namn på _<källa>_, som måste existera och vara antingen en fil, symlänk eller katalog, till _<destination>_. I den andra formen måste _<destinations-katalog>_ vara en befintlig katalog; de angivna källorna kommer att flyttas till denna katalog.

Indexet uppdateras efter att det har slutförts, men ändringen måste fortfarande genomföras.

ALTERNATIV
----------
`-f`::
`--force`::
	Tvinga fram namnbyte eller flytt av en fil även om <destination> finns.
`-k`::
	Hoppa över åtgärder för att flytta eller byta namn, vilket skulle leda till ett feltillstånd. Ett fel uppstår när en källan varken finns eller kontrolleras av Git, eller när den skulle skriva över en befintlig fil om inte `-f` anges.
`-n`::
`--dry-run`::
	Gör ingenting, visa bara vad som skulle hända

`-v`::
`--verbose`::
	Rapportera namnen på filer allt eftersom de flyttas.

UNDERMODULER
------------
Att flytta en undermodul med hjälp av en gitfile (vilket innebär att de klonades med en Git-version 1.7.8 eller senare) kommer att uppdatera gitfile- och core.worktree-inställningarna för att få undermodulen att fungera på den nya platsen. Den kommer också att försöka uppdatera inställningen `submodule.<namn>.path` i filen linkgit:gitmodules[5] och köaa den filen (såvida inte `-n` används).

BUGGAR
------
Varje gång en superprojektuppdatering flyttar en ifylld undermodul (t.ex. när man växlar mellan incheckningar före och efter flytten) kommer en inaktuell utcheckning av undermodulen att finnas kvar på den gamla platsen och en tom katalog kommer att visas på den nya platsen. För att fylla undermodulen igen på den nya platsen måste användaren köra "git submodule update" efteråt. Att ta bort den gamla katalogen är bara säkert när den använder en gitfile, eftersom annars även undermodulens historik kommer att raderas. Båda stegen kommer att vara föråldrade när rekursiv undermoduluppdatering har implementerats.

GIT
---
En del av linkgit:git[1]-sviten
