git-instaweb(1)
===============

NAMN
----
git-instaweb - Bläddra i ditt kodförråd direkt med gitweb

SYNOPSIS
--------
[verse]
'git instaweb' [--local] [--httpd=<httpd>] [--port=<port>]
               [--browser=<webbläsare>]
'git instaweb' [--start] [--stop] [--restart]

BESKRIVNING
-----------
Ett enkelt skript för att konfigurera `gitweb` och en webbserver för att navigera i det lokala kodförrådet.

ALTERNATIV
----------

-l::
--local::
	Koppla endast webbservern till den lokala IP-adressen (127.0.0.1).

-d::
--httpd::
	HTTP-daemonens kommandorad som kommer att köras. Kommandoradsalternativ kan anges här, och konfigurationsfilen kommer att läggas till i slutet av kommandoraden. För närvarande stöds apache2, lighttpd, mongoose, plackup, python och webrick. (Standard: lighttpd)

-m::
--module-path::
	Modulens sökväg (behövs endast om httpd är Apache). (Standard: /usr/lib/apache2/modules)

-p::
--port::
	Portnumret att binda httpd till. (Standard: 1234)

-b::
--browser::
	Webbläsaren som ska användas för att visa gitweb-sidan. Detta skickas till hjälpskriptet 'git web{litdd}browse' tillsammans med URL:en för gitweb-instansen. Se linkgit:git-web{litdd}browse[1] för mer information om detta. Om skriptet misslyckas kommer URL:en att skrivas ut till stdout.

start::
--start::
	Starta httpd-instansen och avsluta. Regenerera konfigurationsfiler efter behov för att skapa en ny instans.

stop::
--stop::
	Stoppa httpd-instansen och avsluta. Detta genererar inga konfigurationsfiler för att skapa en ny instans, och stänger inte heller webbläsaren.

restart::
--restart::
	Starta om httpd-instansen och avsluta. Regenerera konfigurationsfiler efter behov för att skapa en ny instans.

KONFIGURATION
-------------

Du kan ange konfigurationen i din .git/config

-----------------------------------------------------------------------
[instaweb]
	local = true
	httpd = apache2 -f
	port = 4321
	browser = konqueror
	modulePath = /usr/lib/apache2/modules

-----------------------------------------------------------------------

Om konfigurationsvariabeln `instaweb.browser` inte är angiven, kommer `web.browser` att användas i stället om den är definierad. Se linkgit:git-web{litdd}browse[1] för mer information om detta.

SE ÄVEN
-------
linkgit:gitweb[1]

GIT
---
En del av linkgit:git[1]-sviten
