git-name-rev(1)
===============

NAMN
----
git-name-rev - Hitta symboliska namn för givna revs


SYNOPSIS
--------
[verse]
'git name-rev' [--tags] [--refs=<mönster>]
	       ( --all | --annotate-stdin | <incheckningslik>... )

BESKRIVNING
-----------
Hittar symboliska namn lämpliga för mänsklig smältning av revisioner givna i valfritt format som kan analyseras av 'git rev-parse'.


ALTERNATIV
----------

--tags::
	Använd inte grennamn, utan endast taggar för att namnge incheckningar

--refs=<mönster>::
	Använd endast referenser vars namn matchar ett givet skalmönster. Mönstret kan vara ett grennamn, ett taggnamn eller ett fullständigt kvalificerat referensnamn. Om det anges flera gånger, använd referenser vars namn matchar något av de givna skalmönstren. Använd `--no-refs` för att rensa alla tidigare givna referensmönster.

--exclude=<mönster>::
	Använd inte någon referens vars namn matchar ett givet skalmönster. Mönstret kan vara antingen grennamn, taggnamn eller ett fullständigt kvalificerat referensnamn. Om det anges flera gånger kommer en referens att exkluderas när den matchar något av de givna mönstren. När den används tillsammans med --refs kommer en referens endast att användas som en matchning när den matchar minst ett --refs-mönster och inte matchar några --exclude-mönster. Använd `--no-exclude` för att rensa listan över exkluderingsmönster.

--all::
	Lista alla incheckningar nåbara från alla referenser

--annotate-stdin::
	Transformera stdin genom att ersätta alla 40-teckens SHA-1-hexar (t.ex. $hex) med "$hex ($rev_name)". När det används med --name-only, ersätt med "$rev_name", och uteslut $hex helt och hållet. Detta alternativ kallades `--stdin` i äldre versioner av Git.
+
Till exempel:
+
-----------
$ cat sample.txt

En förkortad version 2ae0a9cb82 kommer inte att ersättas.
Det fullständiga namnet efter substitutionen är 2ae0a9cb8298185a94e5998086f380a355dd8907,
medan dess trädobjekt är 70d105cc79e63b81cfdcb08a15297c23e60b07ad

$ git name-rev --annotate-stdin <sample.txt

En förkortad revision 2ae0a9cb82 kommer inte att ersättas.
Det fullständiga namnet efter substitutionen är 2ae0a9cb8298185a94e5998086f380a355dd8907 (master),
medan dess trädobjekt är 70d105cc79e63b81cfdcb08a15297c23e60b07ad

$ git name-rev --name-only --annotate-stdin <sample.txt

En förkortad revision 2ae0a9cb82 kommer inte att ersättas.
Det fullständiga namnet efter ersättning är master,
medan dess trädobjekt är 70d105cc79e63b81cfdcb08a15297c23e60b07ad
-----------

--name-only::
	I stället för att skriva ut både SHA-1 och namnet, skriv bara ut namnet. Om det anges med --tags utelämnas även det vanliga taggprefixet "tags/" från namnet, vilket matchar utdata från `git-describe` bättre.

--no-undefined::
	Avsluta med felkod != 0 när en referens är odefinierad, i stället för att skriva ut `undefined`.

--always::
	Visa unikt förkortade incheckningsobjekt som reserv.

EXEMPEL
-------

Givet en incheckning, ta reda på var den ligger i förhållande till de lokala referenserna. Säg att någon skrev till dig om den där fantastiska incheckningen 33db5f4d9027a10e477ccf054b2c1ab94f74c85a. Naturligtvis tittar du på incheckningen, men det berättar bara vad som hände, inte sammanhanget.

Skriva in 'git name-rev':

------------
% git name-rev 33db5f4d9027a10e477ccf054b2c1ab94f74c85a
33db5f4d9027a10e477ccf054b2c1ab94f74c85a tags/v0.99~940
------------

Nu är du klokare, eftersom du vet att det hände 940 revisioner före v0.99.

En annan trevlig sak du kan göra är:

------------
% git log | git name-rev --annotate-stdin
------------

GIT
---
En del av linkgit:git[1]-sviten
