git-reflog(1)
=============

NAMN
----
git-reflog - Hantera refloginformation


SYNOPSIS
--------
[synopsis]
git reflog [show] [<log-options>] [<ref>]
git reflog list
git reflog exists <ref>
git reflog write <ref> <old-oid> <new-oid> <meddelande>
git reflog delete [--rewrite] [--updateref]
	[--dry-run | -n] [--verbose] <ref>@{<specificerare>}...
git reflog drop [--all [--single-worktree] | <refs>...]
git reflog expire [--expire=<tid>] [--expire-unreachable=<tid>]
	[--rewrite] [--updateref] [--stale-fix]
	[--dry-run | -n] [--verbose] [--all [--single-worktree] | <refs>...]

BESKRIVNING
-----------
Det här kommandot hanterar informationen som registreras i refloggarna.

Referensloggar, eller "refloggar", registrerar när topparna för grenar och andra referenser uppdaterades i det lokala kodförrådet. Refloggar är användbara i olika Git-kommandon för att ange det gamla värdet för en referens. Till exempel betyder `HEAD@{2}` "där HEAD brukade vara för två förflyttningar sedan", `master@{one.week.ago}` betyder "där master brukade peka för en vecka sedan i detta lokala kodförråd", och så vidare. Se linkgit:gitrevisions[7] för mer information.

Kommandot tar olika underkommandon och olika alternativ beroende på underkommandot:

Underkommandot "show" (som också är standard, i avsaknad av några underkommandon) visar loggen för referensen som anges i kommandoraden (eller `HEAD`, som standard). Refloggen täcker alla senaste åtgärder, och dessutom registrerar `HEAD`-refloggen grenväxling. `git reflog show` är ett alias för `git log -g --abbrev-commit --pretty=oneline`; se linkgit:git-log[1] för mer information.

Underkommandot "list" listar alla referenser som har en motsvarande reflog.

Underkommandot "exists" kontrollerar om en reflogg har en reflogg. Den avslutas med status noll om refloggen existerar, och status som inte noll om den inte gör det.

Underkommandot "write" skriver en enda post till refloggen för en given referens. Denna nya post läggs till i refloggen och blir därmed den senaste posten. Referensnamnet måste vara fullständigt kvalificerat. Både det gamla och det nya objekt-ID:t får inte förkortas och måste peka på befintliga objekt. Refloggmeddelandet normaliseras.

Delkommandot "delete" tar bort enskilda poster från refloggen, men inte själva refloggen. Dess argument måste vara en _exact_-post (t.ex. "`git reflog delete master@{2}`"). Detta delkommando används vanligtvis inte heller direkt av slutanvändare.

Underkommandot "drop" tar bort refloggen helt för de angivna referenserna. Detta står i kontrast till "expire" och "delete", vilka båda kan användas för att ta bort refloggposter, men inte själva refloggen.

Underkommandot "expire" tar bort äldre refloggposter. Poster äldre än `expire`-tiden, eller poster äldre än `expire-unreachable`-tiden och inte nåbara från det aktuella tipset, tas bort från refloggen. Detta används vanligtvis inte direkt av slutanvändare -- se i stället linkgit:git-gc[1].

ALTERNATIV
----------

Alternativ för `show`
~~~~~~~~~~~~~~~~~~~~~

`git reflog show` accepterar alla alternativ som accepteras av `git log`.


Alternativ för `delete`
~~~~~~~~~~~~~~~~~~~~~~~

`git reflog delete` accepterar alternativen `--updateref`, `--rewrite`, `-n`, `--dry-run` och `--verbose`, med samma betydelser som när de används med `expire`.

Alternativ för `drop`
~~~~~~~~~~~~~~~~~~~~~

`--all`::
	Ta bort refloggarna för alla referenser från alla arbetsträd.

`--single-worktree`::
	Som standard när `--all` anges tas refloggar från alla arbetsträd bort. Det här alternativet begränsar bearbetningen till refloggar från det aktuella arbetsträdet.


Alternativ för `expire`
~~~~~~~~~~~~~~~~~~~~~~~

`--all`::
	Bearbeta referensloggar för alla referenser.

`--single-worktree`::
	Som standard när `--all` anges bearbetas refloggar från alla arbetsträd. Det här alternativet begränsar bearbetningen till refloggar från det aktuella arbetsträdet.

`--expire=<tid>`::
	Rensa bort poster som är äldre än den angivna tiden. Om det här alternativet inte anges hämtas utgångstiden från konfigurationsinställningen `gc.reflogExpire`, som i sin tur har en standardinställning på 90 dagar. `--expire=all` rengör poster oavsett deras ålder; `--expire=never` inaktiverar rensning av nåbara poster (men se `--expire-unreachable`).

`--expire-unreachable=<tid>`::
	Rensa bort poster äldre än `<tid>` som inte kan nås från grenens aktuella spets. Om det här alternativet inte anges hämtas utgångstiden från konfigurationsinställningen `gc.reflogExpireUnreachable`, som i sin tur har en standardinställning på 30 dagar. `--expire-unreachable=all` rensa bort oåtkomliga poster oavsett deras ålder; `--expire-unreachable=never` inaktiverar tidig rensning av oåtkomliga poster (men se `--expire`).

`--updateref`::
	Uppdatera referensen till värdet för den översta reflogposten (dvs. <ref>@\{0\}) om den föregående översta posten har rensats bort. (Detta alternativ ignoreras för symboliska referenser.)

`--rewrite`::
	Om en reflog-posts föregångare beskärs, justera dess "gamla" SHA-1 så att den är lika med det "nya" SHA-1-fältet för posten som nu föregår den.

`--stale-fix`::
	Rensa bort alla reflog-poster som pekar på "trasiga incheckningar". En trasig incheckning är en incheckning som inte kan nås från någon av referenstoparna och som direkt eller indirekt refererar till en saknad incheckning, ett träd eller ett blob-objekt.
+
Denna beräkning innebär att man går igenom alla nåbara objekt, d.v.s. den har samma kostnad som "git prune". Den är främst avsedd att åtgärda korruption orsakad av sophämtning med äldre versioner av Git, vilka inte skyddade objekt som refererades till av refloggar.

`-n`::
`--dry-run`::
	Beskär inte några poster; visa bara det som skulle ha beskurits.

`--verbose`::
	Skriv ut extra information på skärmen.


GIT
---
En del av linkgit:git[1]-sviten
