git-archimport(1)
=================

NAMN
----
git-archimport - Importera ett GNU Arch-kodförråd till Git


SYNOPSIS
--------
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <djup>] [-t <tempkat>]
	       <arkiv>/<gren>[:<git-gren>]...

BESKRIVNING
-----------
Importerar ett projekt från ett eller flera GNU Arch-arkiv. Den följer grenar och kodförråd inom namnrymderna som definieras av de angivna parametrarna <arkiv>/<gren>. Om den inte kan hitta den fjärrgren som en sammanslagning kommer ifrån kommer den bara att importera den som en vanlig incheckning. Om den kan hitta den kommer den att markeras som en sammanslagning när det är möjligt (se diskussionen nedan).

Skriptet förväntar sig att du anger nyckelrötter där det kan starta importen från en Arch-incheckning av typen 'initial import' eller 'tag'. Det kommer att följa och importera nya grenar inom de angivna rötterna.

Den förväntar sig att endast hantera ett projekt. Om den ser grenar som har olika rötter kommer den att vägra att köras. I så fall, redigera dina <arkiv>/<gren>-parametrar för att tydligt definiera importens omfattning.

'git archimport' använder `tla` i stor utsträckning i bakgrunden för att komma åt Arch-kodförråd. Se till att du har en aktuell version av `tla` tillgänglig i sökvägen. `tla` måste känna till de kodförråd du skickar till 'git archimport'.

För den initiala importen förväntas 'git archimport' befinna sig i en tom katalog. För att följa utvecklingen av ett projekt som använder Arch, kör 'git archimport' igen med samma parametrar som den initiala importen för att utföra stegvisa importer.

Medan 'git archimport' försöker skapa rimliga grennamn för de arkiv som importeras, är det också möjligt att ange Git-grennamn manuellt. För att göra det, skriv ett Git-grennamn efter varje <arkiv>/<gren>-parameter, separerade med ett kolon. På så sätt kan du förkorta Arch-grennamnen och konvertera Arch-jargong till Git-jargong, till exempel genom att mappa en "PROJECT{litdd}devo{litdd}VERSION"-gren till "master".

Att associera flera Arch-grenar till en Git-gren är möjligt; resultatet blir mest meningsfullt endast om inga incheckningar görs till den första grenen efter att den andra grenen har skapats. Detta är dock användbart för att konvertera Arch-kodförråd som har roterats regelbundet.


SAMMANSLAGNINGAR
----------------
Data om patchsammanslagningar från Arch används även för att markera sammanslagningar i Git. Git bryr sig inte så mycket om att spåra patchar och beaktar bara en sammanslagning när en gren införlivar alla incheckningar sedan den punkt de avgrenades. Slutresultatet är att Git kommer att ha en bra uppfattning om hur långt grenarna har divergerat. Så importprocessen förlorar en del metadata för patchhantering.

Som tur är, när du försöker slå samman grenar importerade från Arch, kommer Git att hitta en bra sammanslagningsbas, och det finns en god chans att identifiera patchar som har bytts ut i fel sekvens mellan grenarna.

ALTERNATIV
----------

-h::
	Uppvisnings användning.

-v::
	Utförlig utdata.

-T::
	Många taggar. Skapar en tagg för varje incheckning, som återspeglar incheckningsnamnet i Arch-kodförråd.

-f::
	Använd den snabba importstrategin för patchset. Detta kan vara betydligt snabbare för stora träd, men kan inte hantera katalognamn eller behörighetsändringar. Standardstrategin är långsam och säker.

-o::
	Använd detta för kompatibilitet med gammaldags grennamn som användes av tidigare versioner av 'git archimport'. Gammaldags grennamn var kategori{litdd}gen, medan nya grennamn är arkiv,kategori{litdd}gren{litdd}version. I båda fallen kommer namn som anges på kommandoraden att åsidosätta de automatiskt genererade.

-D <<djup>::
	Följ sammanslagnings-anor och försök att importera träd som har sammanfogats från. Ange ett djup större än 1 om patchloggar har beskärts.

-a::
	Försök att automatiskt registrera arkiv på `http://mirrors.sourcecontrol.net`. Detta är särskilt användbart med alternativet -D.

-t <tmpkat>::
	Åsidosätt standardtemporärkatalogen.


<arkiv>/<gren>::
	<arkiv>/<gren>-identifierare i ett format som `tla log` förstår.


GIT
---
En del av linkgit:git[1]-sviten
