git-credential-store(1)
=======================

NAMN
----
git-credential-store - Hjälpere för att lagra legitimationsinformation på disk

SYNOPSIS
--------
-------------------
git config credential.helper 'store [<flaggor>]'
-------------------

BESKRIVNING
-----------

NOTE: Genom att använda det här hjälpprogramet lagras dina lösenord okrypterade på disk, skyddade endast av filsystemsbehörigheter. Om detta inte är en acceptabel säkerhetsavvägning kan du prova linkgit:git-credential-cache[1], eller hitta entthjälpprogram som integreras med säker lagring som tillhandahålls av ditt operativsystem.

Det här kommandot lagrar legitimationsinformation på obestämd tid på disk för användning av framtida Git-program.

Du vill förmodligen inte anropa det här kommandot direkt; det är tänkt att användas som en hjälp för legitimationsinformation av andra delar av git. Se linkgit:gitcredentials[7] eller `EXEMPEL` nedan.

ALTERNATIV
----------

--file=<sökväg>::

	Använd `<sökväg>` för att slå upp och lagra inloggningsuppgifter. Filens filsystembehörigheter kommer att vara inställda för att förhindra att andra användare på systemet läser den, men den kommer inte att krypteras eller på annat sätt skyddas. Om inget anges kommer inloggningsuppgifter att sökas efter från `~/.git-credentials` och `$XDG_CONFIG_HOME/git/credentials`, och inloggningsuppgifter kommer att skrivas till `~/.git-credentials` om den finns, eller `$XDG_CONFIG_HOME/git/credentials` om den finns och den förra inte finns. Se även <<FILES>>.

[[FILES]]
FILER
-----

Om det inte uttryckligen anges med `--file`, finns det två filer där git-credential-store söker efter inloggningsuppgifter i prioritetsordning:

~/.git-credentials::
	Användarspecifik inloggningsuppgifts-fil.

$XDG_CONFIG_HOME/git/credentials::
	Andra användarspecifika inloggningsuppgifter. Om '$XDG_CONFIG_HOME' inte är angivet eller tomt, kommer `$HOME/.config/git/credentials` att användas. Inloggningsuppgifter som lagras i den här filen kommer inte att användas om `~/.git-credentials` också har en matchande inloggningsuppgifter väl. Det är en bra idé att inte skapa den här filen om du ibland använder äldre versioner av Git som inte stöder den.

Vid uppslagning av legitimationsinformation läses filerna i den ordning som anges ovan, där den första matchande autentiseringsuppgiften som hittas prioriteras framför autentiseringsuppgifter som finns i filer längre ner i listan.

Legitimationsinformations-lagringen skriver som standard till den första befintliga filen i listan. Om ingen av dessa filer finns skapas och skrivs till `~/.git-credentials`.

När du raderar inloggningsuppgifter kommer matchande legitimationsinformationen att raderas från alla filer.

EXEMPEL
-------

Poängen med den här hjälpprogramet är att minska antalet gånger du måste skriva in ditt användarnamn eller lösenord. Till exempel:

------------------------------------------
$ git config credential.helper store
$ git push http://example.com/repo.git
Username: <skriv ditt användarnamn>
Password: <skriv ditt lösenord>

[flera dagar senare]
$ git push http://example.com/repo.git
[dina inloggningsuppgifter används automatiskt]
------------------------------------------

LAGRINGSFORMAT
--------------

Filen `.git-credentials` lagras i klartext. Varje legitimationsinformation lagras på en egen rad som en URL, ungefär som:

------------------------------
https://user:pass@example.com
------------------------------

Inga andra typer av rader (t.ex. tomma rader eller kommentarsrader) är tillåtna i filen, även om vissa kan ignoreras tyst. Visa eller redigera inte filen med redigerare.

När Git behöver autentisering för en specifik URL-kontext, kommer legitimationsinformations-lagret att betrakta den kontexten som ett mönster som matchar varje post i legitimationsinformations-filen. Om protokollet, värdnamnet och användarnamnet (om vi redan har ett) matchar, returneras lösenordet till Git. Se diskussionen om konfiguration i linkgit:gitcredentials[7] för mer information.

GIT
---
En del av linkgit:git[1]-sviten
