git-help(1)
===========

NAMN
----
git-help - Visa hjälpinformation om Git

SYNOPSIS
--------
[verse]
'git help' [-a|--all] [--[no-]verbose] [--[no-]external-commands] [--[no-]aliases]
'git help' [[-i|--info] [-m|--man] [-w|--web]] [<kommando>|<dok>]
'git help' [-g|--guides]
'git help' [-c|--config]
'git help' [--user-interfaces]
'git help' [--developer-interfaces]

BESKRIVNING
-----------

Utan alternativ och utan '<kommando>' eller '<doc>' angivet skrivs en sammanfattning av 'git'-kommandot och en lista över de vanligaste Git-kommandona ut på standard ut.

Om alternativet `--all` eller `-a` anges skrivs alla tillgängliga kommandon ut på standardutdata.

Om alternativet `--guides` eller `-g` anges, skrivs även en lista över Git-konceptguider ut på standardutdata.

Om ett kommando eller annan dokumentation ges, kommer relevant manualsida att visas. Programmet 'man' används som standard för detta ändamål, men detta kan åsidosättas av andra alternativ eller konfigurationsvariabler.

Om ett alias anges visar git definitionen av aliaset i standardutdata. För att hämta manualsidan för det aliaserade kommandot, använd `git <kommando> --help`.

Observera att `git --help ...` är identiskt med `git help ...` eftersom den förra konverteras internt till den senare.

För att visa manualsidan för linkgit:git[1], använd `git help git`.

Den här sidan kan visas med 'git help help' eller `git help --help`.

ALTERNATIV
----------
-a::
--all::
	Skriv ut alla tillgängliga kommandon på standardutdata.

--no-external-commands::
	När det används med `--all`, exkluderas listan över externa "git-*"-kommandon som finns i `$PATH`.

--no-aliases::
	När det används med `--all`, exkluderas listan över konfigurerade alias.

--verbose::
	När det används med `--all`, skrivs en beskrivning ut för alla igenkända kommandon. Detta är standardinställningen.

-c::
--config::
	Lista alla tillgängliga konfigurationsvariabler. Detta är en kort sammanfattning av listan i linkgit:git-config[1].

-g::
--guides::
	Skriv ut en lista över Git-konceptguiderna på standardutdata.

--user-interfaces::
	Skriv ut en lista kodförrådet, kommandona och filgränssnittens dokumentationen på standardutdata.
+
Gränssnitt för filer i kodförrådet, såsom `.git/info/exclude`, dokumenteras här (se linkgit:gitrepository-layout[5]), såväl som konfiguration i trädet, såsom `.mailmap` (se linkgit:gitmailmap[5]).
+
Denna del av dokumentationen täcker även allmänna eller utbredda konventioner för användargränssnitt (t.ex. linkgit:gitcli[7]), och pseudokonfiguration såsom det filbaserade `.git/hooks/*`-gränssnittet som beskrivs i linkgit:githooks[5].

--developer-interfaces::
	Skriv ut en lista över filformat, protokoll och annan dokumentation för utvecklargränssnitt på standardutdata.

-i::
--info::
	Visa manualsidan för kommandot i formatet 'info'. Programmet 'info' kommer att användas för det ändamålet.

-m::
--man::
	Visa manualsidan för kommandot i formatet 'man'. Det här alternativet kan användas för att åsidosätta ett värde som anges i konfigurationsvariabeln 'help.format'.
+
Som standard används programmet 'man' för att visa manualsidan, men konfigurationsvariabeln `man.viewer` kan användas för att välja andra visningsprogram (se nedan).

-w::
--web::
	Visa manualsidan för kommandot i 'web'-format (HTML). En webbläsare kommer att användas för detta ändamål.
+
Webbläsaren kan anges med hjälp av konfigurationsvariabeln `help.browser`, eller `web.browser` om den förra inte är satt. Om ingen av dessa konfigurationsvariabler är satt, kommer hjälpskriptet 'git web{litdd}browse' (anropat av 'git help') att välja en lämplig standardinställning. Se linkgit:git-web{litdd}browse[1] för mer information om detta.

KONFIGURATIONSVARIABLER
-----------------------

help.format
~~~~~~~~~~~

Om inget kommandoradsalternativ skickas kommer konfigurationsvariabeln `help.format` att kontrolleras. Följande värden stöds för denna variabel; de gör att 'git help' beter sig som motsvarande kommandoradsalternativ:

* "man" motsvarar '-m|--man',
* "info" motsvarar '-i|--info',
* "web" eller "html" motsvarar '-w|--web'.

help.browser, web.browser och browser.<tool>.path
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`help.browser`, `web.browser` och `browser.<verktyg>.path` kommer också att kontrolleras om formatet 'web' är valt (antingen med kommandoradsalternativ eller konfigurationsvariabel). Se '-w|--web' i avsnittet ALTERNATIV ovan och linkgit:git-web{litdd}browse[1].

man.viewer
~~~~~~~~~~

Konfigurationsvariabeln `man.viewer` kommer att kontrolleras om formatet 'man' väljs. Följande värden stöds för närvarande:

* "man": använd programmet 'man' som vanligt,
* "woman": använd 'emacsclient' för att starta "woman"-läget i emacs (detta fungerar bara från och med emacsclient version 22),
* "konqueror": använd 'kfmclient' för att öppna manualsidan i en ny Konqueror-flik (se 'Anmärkning om Konqueror' nedan).

Värden för andra verktyg kan användas om det finns en motsvarande `man.<verktyg>.cmd`-konfigurationspost (se nedan).

Flera värden kan ges till konfigurationsvariabeln `man.viewer`. Motsvarande program kommer att testas i den ordning som anges i konfigurationsfilen.

Till exempel den här konfigurationen:

------------------------------------------------
	[man]
		viewer = konqueror
		viewer = woman
------------------------------------------------

kommer att försöka använda konqueror först. Men detta kan misslyckas (till exempel om DISPLAY inte är satt) och i så fall kommer emacs woman-läge att provas.

Om allt misslyckas, eller om ingen läsare är konfigurerad, kommer läsaren som anges i miljövariabeln `GIT_MAN_VIEWER` att testas. Om även den misslyckas kommer programmet 'man' att testas ändå.

man.<verktyg>.path
~~~~~~~~~~~~~~~~~~

Du kan explicit ange en fullständig sökväg till din föredragna man-visare genom att ställa in konfigurationsvariabeln `man.<verktyg>.path`. Du kan till exempel konfigurera den absoluta sökvägen till konqueror genom att ställa in 'man.konqueror.path'. Annars antar 'git help' att verktyget är tillgängligt i PATH.

man.<verktyg>.cmd
~~~~~~~~~~~~~~~~~

När manvisaren, som anges av konfigurationsvariabeln `man.viewer`, inte finns bland de som stöds, kommer motsvarande konfigurationsvariabel `man.<tool>.cmd` att sökas upp. Om denna variabel finns behandlas det angivna verktyget som ett anpassat kommando, och skaltolkning används för att köra kommandot med manualsidan som argument.

Anmärkning om Konqueror
~~~~~~~~~~~~~~~~~~~~~~~

När 'konqueror' anges i konfigurationsvariabeln `man.viewer` startar vi 'kfmclient' för att försöka öppna manualsidan på en redan öppen Konqueror i en ny flik om möjligt.

För konsekvensens skull provar vi också ett sådant knep om 'man.konqueror.path' är satt till något i stil med `EN_SÖKVÄG_TILL/konqueror`. Det betyder att vi kommer att försöka starta `EN_SÖKVÄG_TILL/kfmclient` i stället.

Om du verkligen vill använda 'konqueror' kan du använda något i stil med följande:

------------------------------------------------
	[man]
		viewer = konq

	[man "konq"]
		cmd = EN_SÖKVÄG_TILL/konqueror
------------------------------------------------

Anmärkning om git config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Observera att alla dessa konfigurationsvariabler förmodligen bör ställas in med flaggan `--global`, till exempel så här:

------------------------------------------------
$ git config --global help.format web
$ git config --global web.browser firefox
------------------------------------------------

eftersom de förmodligen är mer användarspecifika än kodförrådsspecifika. Se linkgit:git-config[1] för mer information om detta.

GIT
---
En del av linkgit:git[1]-sviten
