git-fmt-merge-msg(1)
====================

NAMN
----
git-fmt-merge-msg - Skapa ett sammanslagnings-inchecknings-meddelande


SYNOPSIS
--------
[verse]
'git fmt-merge-msg' [-m <meddelande>] [--into-name <gren>] [--log[=<n>] | --no-log]
'git fmt-merge-msg' [-m <meddelande>] [--log[=<n>] | --no-log] -F <fil>

BESKRIVNING
-----------
Tar listan över sammanfogade objekt på stdin och producerar ett lämpligt inchecknings-meddelande som ska användas för sammanslagings-incheckningen, vanligtvis att skickas som argumentet '<sammanslagings-meddelande>' för 'git merge'.

Det här kommandot är främst avsett för intern användning av skript som automatiskt anropar 'git merge'.

ALTERNATIV
----------

--log[=<n>]::
	Förutom grennamn, fyll i loggmeddelandet med enradsbeskrivningar från de faktiska incheckningar som sammanfogas. Högst <n> incheckningar från varje sammanfogningsförälder kommer att användas (20 om <n> utelämnas). Detta åsidosätter konfigurationsvariabeln `merge.log`.

--no-log::
	Lista inte enradiga beskrivningar från de faktiska incheckningar som sammanfogas.

--summary::
--no-summary::
	Synonymer till --log och --no-log; dessa är föråldrade och kommer att tas bort i framtiden.

-m <meddelande>::
--message <meddelande>::
	Använd <meddelande> istället för grennamnen för den första raden i loggmeddelandet. För användning med `--log`.

--into-name <gren>::
	Förbered sammanslagningsmeddelandet som om det skulle sammanfogas med grenen `<gren>`, istället för namnet på den riktiga grenen som sammanslagningen görs med.

-F <fil>::
--file <fil>::
	Hämta listan över sammanfogade objekt från <fil> istället för stdin.

KONFIGURATION
-------------
include::config/fmt-merge-msg.adoc[]

merge.summary::
	Synonym till `merge.log`; detta är föråldrat och kommer att tas bort i framtiden.

EXEMPEL
-------

---------
$ git fetch origin master
$ git fmt-merge-msg --log <$GIT_DIR/FETCH_HEAD
---------

Skriv ut ett loggmeddelande som beskriver en sammanslagning av "master"-grenen från "origin"-fjärr.


SE ÄVEN
-------
linkgit:git-merge[1]

GIT
---
En del av linkgit:git[1]-sviten
