git-diff(1)
===========

NAMN
----
git-diff - Visa ändringar mellan incheckningar, incheckning och arbetsträdet, osv


SYNOPSIS
--------
[synopsis]
git diff [<flaggor>] [<incheckning>] [--] [<path>...]
git diff [<flaggor>] --cached [--merge-base] [<incheckning>] [--] [<path>...]
git diff [<flaggor>] [--merge-base] <commit> [<incheckning>...] <incheckning> [--] [<path>...]
git diff [<flaggor>] <incheckning>...<incheckning> [--] [<sökväg>...]
git diff [<flaggor>] <blob> <blob>
git diff [<flaggor>] --no-index [--] <path> <path> [<sökvägsmönster>...]

BESKRIVNING
-----------
Visa ändringar mellan arbetsträdet och indexet eller ett träd, ändringar mellan indexet och ett träd, ändringar mellan två träd, ändringar som är resultatet av en sammanslagning, ändringar mellan två blobobjekt eller ändringar mellan två filer på disken.

`git diff [<flaggor>] [--] [<sökväg>...]`::

	Formen visar de ändringar som gjorts i förhållande till indexet (köområdet för nästa incheckning). Med andra ord är skillnaderna vad Git ytterligare _skulle kunna_ lägga till i indexet, men ännu inte har gjort. Dessa ändringar kan köas med linkgit:git-add[1].

`git diff [<flaggor>] --no-index [--] <sökväg> <sökväg> [<sökvägsmönster>...]`::

	Formen jämför de två angivna sökvägarna i filsystemet. Alternativet `--no-index` kan utelämnas när kommandot körs i ett arbetsträd som hanteras av Git och minst en av sökvägarna pekar utanför arbetsträdet, eller när kommandot körs utanför ett arbetsträd som hanteras av Git. Formen innebär `--exit-code`. Om båda sökvägarna pekar på kataloger kan ytterligare sökvägsmönster anges. Dessa begränsar vilka filer som ingår i skillnaden. Alla sådana sökvägsmönster måste vara relativa eftersom de gäller för båda sidor av diffen.

`git diff [<flaggor>] --cached [--merge-base] [<incheckning>] [--] [<sökväg>...]`::

	Formen visar de ändringar som har köats för nästa incheckning i förhållande till den namngivna _<incheckningen>_. Vanligtvis är det naturligt att jämföra med den senaste incheckningen, så om _<incheckning>_ inte anges används som standard `HEAD`. Om `HEAD` inte existerar (t.ex. ofödda grenar) och _<incheckning>_ inte anges, visas alla köade ändringar. `--staged` är en synonym för `--cached`.
+
Om `--merge-base` anges används sammanslagningsbasen för _<incheckning>_ och `HEAD` i stället för _<incheckning>_. `git diff --cached --merge-base A` motsvarar `git diff --cached $(git merge-base A HEAD)`.

`git diff [<flaggor>] [--merge-base] <incheckning> [--] [<sökväg>...]`::

	Formen visar de ändringar som finns i arbetsträdet i förhållande till den namngivna _<incheckningen>_. `HEAD` kan användas för att jämföra med den senaste incheckningen, eller ett grennamn för att jämföra med toppen av en annan gren.
+
Om `--merge-base` anges används sammanslagningsbasen för _<incheckning>_ och `HEAD` i stället för _<incheckning>_. `git diff --merge-base A` motsvarar `git diff $(git merge-base A HEAD)`.

`git diff [<flaggor>] [--merge-base] <incheckning> <incheckning> [--] [<sökväg>...]`::

	Visar ändringarna mellan två godtyckliga _<incheckningar>_.
+
Om `--merge-base` anges används sammanslagningsbasen för de två incheckningarna på "före"-sidan. `git diff --merge-base A B` motsvarar `git diff $(git merge-base A B) B`.

`git diff [<flaggor>] <incheckning> <incheckning>...<incheckning> [--] [<sökväg>...]`::

	Formen visar resultatet av en sammanslagningsincheckning. Den första listade _<incheckning>_ måste vara själva sammanslagningen; de återstående två eller fler incheckningarna ska vara dess föräldrar. Ett smidigt sätt att få fram önskad uppsättning revisioner är att använda suffixen `@` och `^!`. Om `A` är en sammanslagningsincheckning ger `git diff A A^@`, `git diff A^!` och `git show A` samma kombinerade diff.

`git diff [<flaggor>] <incheckning>..<incheckning> [--] [<sökväg>...]`::

	Detta är synonymt med den tidigare formen (utan `..`) för att visa ändringarna mellan två godtyckliga _<incheckningar>_. Om _<incheckning>_ på ena sidan utelämnas, har det samma effekt som att använda `HEAD` i stället.

`git diff [<flaggor>] <incheckning>..<incheckning> [--] [<sökväg>...]`::

	Formen visar ändringarna på grenen som innehåller och sträcker sig fram till den andra _<incheckningen>_, med början vid en gemensam förfader till båda _<incheckningarna>_. `git diff A...B` motsvarar `git diff $(git merge-base A B) B`. Man kan utelämna vilken som helst av _<incheckningarna>_, vilket har samma effekt som att använda `HEAD` i stället.

Om något mer ovanligt görs bör det noteras att alla _<incheckningar>_ i beskrivningen ovan, förutom i fallet `--merge-base` och i de två sista formerna som använder `..`-notationerna, kan vara vilket _<träd>_ som helst. Ett intressant träd är det som pekas ut av referensen med namnet `AUTO_MERGE`, som skrivs av `ort`-sammanslagningsstrategin vid sammanslagningskonflikter (se linkgit:git-merge[1]). Att jämföra arbetsträdet med `AUTO_MERGE` visar ändringar som hittills har gjorts för att lösa textkonflikter (se exemplen nedan).

För en mer fullständig lista över sätt att ange _<incheckning>_, se avsnittet "SPECIFYING REVISIONS" i linkgit:gitrevisions[7]. Observera dock att `diff` handlar om att jämföra två _slutpunkter_, inte intervall, och att intervallnotationerna (`<incheckning>..<incheckning>` och `<incheckning>...<incheckning>`) inte betyder ett intervall i den mening som definieras i avsnittet "SPECIFYING RANGES" i linkgit:gitrevisions[7].

`git diff [<flaggor>] <blob> <blob>`::

	Formen visar skillnaderna mellan det råa innehållet i två blob-objekt.

ALTERNATIV
----------
:git-diff: 1
include::diff-options.adoc[]

`-1`::
`--base`::
`-2`::
`--ours`::
`-3`::
`--theirs`::
	Jämför arbetsträdet med
+
--
 * "basversionen" (steg nr1) när `-1` eller `--base` används,
 * "vår gren" (steg nr 2) när `-2` eller `--ours` används, eller
 * "deras gren" (steg nr 3) när `-3` eller `--theirs` används.
--
+
Indexet innehåller dessa steg bara för osammanslagna poster, d.v.s. vid konfliktlösning. Se avsnittet "3-Way Merge" i linkgit:git-read-tree[1] för detaljerad information.

`-0`::
	Utelämna diff-utdata för ej sammanslagna poster och visa bara "Osammanslagen". Kan endast användas när arbetsträdet jämförs med indexet.

`<sökväg>...`::
	Parametrarna _<sökväg>_, när de är angivna, används för att begränsa differansen till de namngivna sökvägarna (du kan ange katalognamn och hämta diff-värden för alla filer under dem).


include::diff-format.adoc[]

EXEMPEL
-------

Olika sätt att kontrollera arbetsträdet::
+
------------
$ git diff            <1>
$ git diff --cached   <2>
$ git diff HEAD       <3>
$ git diff AUTO_MERGE <4>
------------
+
<1> Ändringar i arbetsträdet är ännu inte köade för nästa incheckning.
<2> Ändringar mellan indexet och den senaste incheckningen; vad som skulle checkas in om `git commit` körs utan `-a`-flaggan.
<3> Ändringar i arbetsträdet sedan den senaste incheckningen; vad som skulle checkas in om `git commit -a` körs
<4> Ändringar i arbetsträdet som hittills har gjorts för att lösa textkonflikter.

Jämförelse med godtyckliga incheckningar::
+
------------
$ git diff test            <1>
$ git diff HEAD -- ./test  <2>
$ git diff HEAD^ HEAD      <3>
------------
+
<1> I stället för att använda toppen på den aktuella grenen, jämför med toppen på "test"-grenen.
<2> I stället för att jämföra med toppen på grenen "test", jämför med toppen på den aktuella grenen, men begränsa jämförelsen till filen "test".
<3> Jämför versionen före den senaste incheckningen och den senaste incheckningen.

Jämföra grenar::
+
------------
$ git diff ärende master    <1>
$ git diff ärende..master   <2>
$ git diff ärende...master  <3>
------------
+
<1> Ändringar mellan ämnets toppar och huvudgrenarna.
<2> Samma som ovan.
<3> Ändringar som inträffat på huvudgrenen sedan när ämnesgrenen startades från den.

Begränsa diff-utmatning::
+
------------
$ git diff --diff-filter=MRC            <1>
$ git diff --name-status                <2>
$ git diff arch/i386 include/asm-i386   <3>
------------
+
<1> Visa endast ändring, namnbyte och kopiering, men inte tillägg eller borttagning.
<2> Visar endast namn och ändringens natur, men inte faktisk skillnadsutdata.
<3> Begränsa diff-utdata till namngivna underträd.

Omformning av diff-utdata::
+
------------
$ git diff --find-copies-harder -B -C  <1>
$ git diff -R                          <2>
------------
+
<1> Lägg extra cykler på att hitta namnbyten, kopior och fullständiga omskrivningar (väldigt dyrt).
<2> Utgångsskillnad i omvänd ordning.

KONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-diff: 1
include::config/diff.adoc[]

SE ÄVEN
-------
`diff`(1), linkgit:git-difftool[1], linkgit:git-log[1], linkgit:gitdiffcore[7], linkgit:git-format-patch[1], linkgit:git-apply[1], linkgit:git-show[1]

GIT
---
En del av linkgit:git[1]-sviten
