git-credential-cache(1)
=======================

NAMN
----
git-credential-cache - Hjälpprogram för att tillfälligt lagra lösenord i minnet

SYNOPSIS
--------
-----------------------------
git config credential.helper 'cache [<flaggor>]'
-----------------------------

BESKRIVNING
-----------

Det här kommandot cachelagrar autentiseringsuppgifter för användning av framtida Git-program. De lagrade autentiseringsuppgifterna sparas i cache-daemon-processens minne (i stället för att skrivas till en fil) och glöms bort efter en konfigurerbar timeout. Autentiseringsuppgifterna glöms bort tidigare om cache-daemonen dör, till exempel om systemet startas om. Cachen är åtkomlig via en Unix-domänsocket, begränsad till den aktuella användaren av filsystembehörigheter.

Du vill förmodligen inte anropa det här kommandot direkt; det är tänkt att användas som ett hjälpverktyg för autentiseringsuppgifter i andra delar av Git. Se linkgit:gitcredentials[7] eller `EXEMPEL` nedan.

ALTERNATIV
----------

--timeout <sekunder>::

	Antal sekunder för att cachelagra autentiseringsuppgifter (standard: 900).

--socket <sökväg>::

	Använd `<sökväg>` för att kontakta en aktiv cache-daemon (eller starta en ny cache-daemon om en inte har startats). Standardvärdet är `$XDG_CACHE_HOME/git/credential/socket` om inte `~/.git-credential-cache/` finns, i vilket fall `~/.git-credential-cache/socket` används i stället. Om din hemkatalog finns på ett nätverksmonterat filsystem kan du behöva ändra detta till ett lokalt filsystem. Du måste ange en absolut sökväg.

KONTROLLERA DEMONEN
-------------------

Om du vill att daemonen ska avslutas tidigt, och glömma alla cachade autentiseringsuppgifter innan timeout, kan du utföra en `exit`-åtgärd:

--------------------------------------
git credential-cache exit
--------------------------------------

EXEMPEL
-------

Poängen med det här hjälpprogrammet är att minska antalet gånger du måste skriva in ditt användarnamn eller lösenord. Till exempel:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <skriv ditt användarnamn>
Password: <skriv ditt lösenord>

[jobba i 5 minuter till]
$ git push http://example.com/repo.git
[dina autentiseringsuppgifter används automatiskt]
------------------------------------

Du kan ange alternativ via konfigurationsvariabeln credential.helper (detta exempel ökar cachetiden till 1 timme):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

PERSONLIGA ÅTKOMSTTOKEN
-----------------------

Vissa fjärrar accepterar personliga åtkomsttokens, vilka genereras slumpmässigt och är svåra att memorera. De har vanligtvis en livslängd på veckor eller månader.

git-credential-cache är i sig olämpligt för permanent lagring av personliga åtkomsttokens. Autentiseringsuppgifterna kommer att glömmas bort efter cache-timeouten. Även om du konfigurerar en lång timeout kommer autentiseringsuppgifterna att glömmas bort om daemonen dör.

För att undvika att ofta generera om personliga åtkomsttokens, konfigurera en autentiseringshjälp med permanent lagring. Alternativt kan du konfigurera en OAuth-autentiseringshjälp för att generera autentiseringsuppgifter automatiskt. Se linkgit:gitcredentials[7], avsnitten "Tillgängliga hjälpfunktioner" och "OAuth".

GIT
---
En del av linkgit:git[1]-sviten
