git-check-mailmap(1)
====================

NAMN
----
git-check-mailmap - Visar kanoniska namn och e-postadresser för kontakter


SYNOPSIS
--------
[verse]
'git check-mailmap' [<flaggor>] <kontakt>...


BESKRIVNING
-----------

För varje ``Namn $$<user@host>$$'', ``$$<user@host>$$'' eller ``$$user@host$$'' från kommandoraden eller standardinmatningen (vid användning av `--stdin`) slås personens kanoniska namn och e-postadress upp (se "Mapping Authors" nedan). Om de hittas skrivs de ut, annars skrivs indata ut oförändrat.


ALTERNATIV
----------
--stdin::
	Läs kontakter, en per rad, från standardinmatningen efter att ha uttömt kontakterna som anges på kommandoraden.

--mailmap-file=<fil>::
	Utöver alla konfigurerade e-postmappfiler, läs den angivna e-postmappfilen. Poster i den här filen har företräde framför poster i antingen standard-e-postmappfilen eller någon konfigurerad e-postmappfil.

--mailmap-blob=<blob>::
	Som `--mailmap-file`, men betrakta värdet som en referens till en blob i kodförrådet. Om både `--mailmap-file` och `--mailmap-blob` anges, kommer poster i `--mailmap-file` att prioriteras.

UTMATNING
---------

För varje kontakt skrivs en enda rad ut, avslutad med en ny rad. Om namnet anges eller är känt för 'e-postmappen' skrivs ``Namn $$<användare@värd>$$'' ut; annars skrivs endast ``$$<användare@värd>$$'' ut.


KONFIGURATION
-------------

Se `mailmap.file` och `mailmap.blob` i linkgit:git-config[1] för hur man anger en anpassad `.mailmap` målfil eller ett objekt.


KARTLÄGG FÖRFATTARE
-------------------

Se linkgit:gitmailmap[5].


GIT
---
En del av linkgit:git[1]-sviten
