git-http-fetch(1)
=================

NAMN
----
git-http-fetch - Ladda ner från ett fjärrkodförråd från Git via HTTP


SYNOPSIS
--------
[verse]
'git http-fetch' [-c] [-t] [-a] [-d] [-v] [-w <filnamn>] [--recover] [--stdin | --packfile=<hash> | <incheckning>] <URL>

BESKRIVNING
-----------
Laddar ner ett Git-fjärrkodförråd via HTTP.

Kommandot hämtar alltid alla objekt. Historiskt sett fanns det tre alternativ `-a`, `-c` och `-t` för att välja vilka objekt som skulle laddas ner. De ignoreras nu tyst.

ALTERNATIV
----------
inchecknings-id::
        Antingen hashen eller filnamnet under [URL]/refs/ som ska hämtas.

-a::
-c::
-t::
	Dessa alternativ ignoreras av historiska skäl.

-v::
	Rapportera vad som laddats ner.

-w <filnamn>::
Skriver inchecknings-id:t till det angivna filnamnet under $GIT_DIR/refs/<filnamn> på den lokala änden efter att överföringen är klar.

--stdin::
	I stället för ett inchecknings-id på kommandoraden (vilket inte förväntas i det här fallet), förväntar sig 'git http-fetch' rader på stdin i formatet

		<inchecknings-id>['\t'<filnamn-som-i--w>]

--packfile=<hash>::
	Endast för internt bruk. I stället för ett inchecknings-id på kommandoraden (vilket inte förväntas i det här fallet) hämtar 'git http-fetch' packfilen direkt vid den angivna URL:en och använder index-pack för att generera motsvarande .idx- och .keep-filer. Hashen används för att bestämma namnet på den temporära filen och är godtycklig. Utdata från index-pack skrivs ut till stdout. Kräver --index-pack-args.

--index-pack-args=<args>::
	Endast för internt bruk. Kommandot ska köras på innehållet i det nedladdade paketet. Argumenten är URL-kodade och separerade med mellanslag.

--recover::
	Verifiera att allt som kan nås från målet hämtas. Används efter att en tidigare hämtning avbrutits.

GIT
---
En del av linkgit:git[1]-sviten
