git-show(1)
===========

NAMN
----
git-show - Visa olika typer av objekt


SYNOPSIS
--------
[synopsis]
git show [<options>] [<object>...]

BESKRIVNING
-----------
Visar ett eller flera objekt (blobbar, träd, taggar och incheckningar).

For commits it shows the log message and textual diff. It also presents the merge commit in a special format as produced by `git diff-tree --cc`.

För taggar, visar den taggmeddelandet och de refererade objekten.

For trees, it shows the names (equivalent to `git ls-tree` with `--name-only`).

För vanliga blobbar, visar den det vanliga innehållet.

Some options that `git log` command understands can be used to control how the changes the commit introduces are shown.

Den här manualsidan beskriver endast de mest använda alternativen.


ALTERNATIV
----------
`<object>...`::
	The names of objects to show (defaults to `HEAD`). For a more complete list of ways to spell object names, see "SPECIFYING REVISIONS" section in linkgit:gitrevisions[7].

include::pretty-options.adoc[]


include::pretty-formats.adoc[]


DIFF-FORMATERING
----------------
Alternativen nedan kan användas för att ändra hur `git show` genererar diff-utdata.

:git-log: 1
:diff-merges-default: `dense-combined`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]


EXEMPEL
-------

`git show v1.0.0`::
	Visar taggen `v1.0.0`, tillsammans med objektet som taggen pekar på.

`git show v1.0.0^{tree}`::
	Visar trädet som pekas på av taggen `v1.0.0`.

`git show -s --format=%s v1.0.0^{commit}`::
	Visar ämnet för den incheckning som pekas på av taggen `v1.0.0`.

`git show next~10:Documentation/README`::
	Visar innehållet i filen `Dokumentation/README` som det var aktuellt vid den tionde sista incheckningen av grenen `next`.

`git show master:Makefile master:t/Makefile`::
	Sammanfogar innehållet i nämnda Makefiles i huvudet på grenen `master`.

DISKUSSION
----------

include::i18n.adoc[]

GIT
---
En del av linkgit:git[1]-sviten
