git-credential-store(1)
=======================

NAMN
----
git-credential-store - Hjälpprogram för att lagra autentiseringsuppgifter på disk

SYNOPSIS
--------
-------------------
git config credential.helper 'store [<flaggor>]'
-------------------

BESKRIVNING
-----------

NOTE: Med detta hjälpprogram lagras lösenord okrypterade på disk, skyddade endast av filsystemets behörigheter. Om detta inte är en acceptabel säkerhetsavvägning kan linkgit:git-credential-cache[1] prövas, eller hitta ett hjälpprogram som integreras med säker lagring som tillhandahålls av operativsystemet.

Kommandot lagrar autentiseringsuppgifter på obestämd tid på disk för användning av framtida Git-program.

Kommandot är normalt inte avsett att anropas direkt; det är tänkt att användas som ett hjälpverktyg för autentiseringsuppgifter i andra delar av Git. Se linkgit:gitcredentials[7] eller `EXEMPEL` nedan.

ALTERNATIV
----------

--file=<sökväg>::

	Använd `<path>` för att slå upp och lagra inloggningsuppgifter. Filens filsystemrättigheter sätts så att andra användare på systemet inte kan läsa den, men den krypteras inte och skyddas inte på annat sätt. Om den inte anges söks inloggningsuppgifter i `~/.git-credentials` och `$XDG_CONFIG_HOME/git/credentials`, och de skrivs till `~/.git-credentials` om den finns, annars till `$XDG_CONFIG_HOME/git/credentials` om den finns och den första inte gör det. Se även <<FILES>>.

[[FILES]]
FILER
-----

Om det inte uttryckligen anges med `--file`, finns det två filer där git-credential-store söker efter inloggningsuppgifter i prioritetsordning:

~/.git-credentials::
	Användarspecifik inloggningsuppgifts-fil.

$XDG_CONFIG_HOME/git/credentials::
	Andra användarspecifika inloggningsuppgifter. Om '$XDG_CONFIG_HOME' inte är angivet eller tomt används `$HOME/.config/git/credentials`. Inloggningsuppgifter som lagras i filen kommer inte att användas om `~/.git-credentials` också har en matchande inloggningsuppgift. Det är klokt att inte skapa filen vid användning av äldre versioner av Git som inte stöder den.

Vid uppslagning av autentiseringsuppgifter läses filerna i den ordning som anges ovan, där den första matchande autentiseringsuppgiften som hittas prioriteras framför autentiseringsuppgifter som finns i filer längre ned i listan.

Lagringen av autentiseringsuppgifter skriver som standard till den första befintliga filen i listan. Om ingen av filerna finns skapas och skrivs `~/.git-credentials`.

När inloggningsuppgifter raderas kommer matchande autentiseringsuppgifter att raderas från alla filer.

EXEMPEL
-------

Poängen med det här hjälpprogrammet är att minska antalet gånger du måste skriva in ditt användarnamn eller lösenord. Till exempel:

------------------------------------------
$ git config credential.helper store
$ git push http://example.com/repo.git
Username: <ange användarnamn>
Password: <ange lösenord>

[flera dagar senare]
$ git push http://example.com/repo.git
[inloggningsuppgifterna används automatiskt]
------------------------------------------

LAGRINGSFORMAT
--------------

Filen `.git-credentials` lagras i klartext. Varje autentiseringsuppgift lagras på en egen rad som en URL, ungefär som:

------------------------------
https://user:pass@example.com
------------------------------

Inga andra typer av rader (t.ex. tomma rader eller kommentarsrader) är tillåtna i filen, även om vissa kan ignoreras tyst. Visa eller redigera inte filen med redigerare.

När Git behöver autentisering för en specifik URL-kontext kommer credential-store att betrakta den kontexten som ett mönster som matchas mot varje post i credentials-filen. Om protokollet, värdnamnet och användarnamnet (om vi redan har ett) matchar returneras lösenordet till Git. Se diskussionen om konfiguration i linkgit:gitcredentials[7] för mer information.

GIT
---
En del av linkgit:git[1]-sviten
