git-var(1)
==========

NAMN
----
git-var - Visa en logisk Git-variabel


SYNOPSIS
--------
[synopsis]
git var (-l | <variabel>)

BESKRIVNING
-----------
Skriver ut en logisk Git-variabel. Avslutas med kod 1 om variabeln inte har något värde.

ALTERNATIV
----------
`-l`::
	Visa de logiska variablerna. Dessutom listas alla variabler i Git-konfigurationsfilen .git/config. (Funktionen för att lista konfigurationsvariabler är dock föråldrad till förmån för `git config -l`.)

EXEMPEL
-------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


VARIABLER
---------
`GIT_AUTHOR_IDENT`::
    Författaren till en kodstycke.

`GIT_COMMITTER_IDENT`::
    Personen som lade in en kodsnutt i Git.

`GIT_EDITOR`::
    Textredigerare för användning av Git-kommandon. Värdet är avsett att tolkas av skalet när det används. Exempel: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. Preferensordningen är `$GIT_EDITOR`, sedan konfigurationsvärdet `core.editor`, sedan `$VISUAL`, sedan `$EDITOR` och sedan standardvärdet som valts vid kompileringstillfället, vilket vanligtvis är 'vi'.
ifdef::git-default-editor[]
    Byggversionen du använder valde '{git-default-editor}' som standard.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Textredigerare som används för att redigera 'todo'-filen när `git rebase -i` körs. Precis som `GIT_EDITOR` är värdet avsett att tolkas av skalet när det används. Preferensordningen är `$GIT_SEQUENCE_EDITOR`, sedan konfigurationsvärdet `sequence.editor` och sedan värdet för `git var GIT_EDITOR`.

`GIT_PAGER`::
    Textvisare för användning av Git-kommandon (t.ex. 'less'). Värdet är avsett att tolkas av skalet. Preferensordningen är `$GIT_PAGER`, sedan värdet för `core.pager`-konfigurationen, sedan `$PAGER` och sedan standardvärdet som valts vid kompileringstillfället (vanligtvis `less`).
ifdef::git-default-pager[]
    Bygget du använder valde '{git-default-pager}' som standard.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    Namnet på den första grenen som skapades i nyligen initierade kodförråd.

`GIT_SHELL_PATH`::
    Sökvägen till den binärfil som tillhandahåller POSIX-skalet för kommandon som använder skalet.

`GIT_ATTR_SYSTEM`::
    Sökvägen till systemfilen linkgit:gitattributes[5], om en sådan är aktiverad.

`GIT_ATTR_GLOBAL`::
    Sökvägen till den globala (per användare) linkgit:gitattributes[5]-filen.

`GIT_CONFIG_SYSTEM`::
    Sökvägen till systemkonfigurationsfilen, om en sådan är aktiverad.

`GIT_CONFIG_GLOBAL`::
    Sökvägen till de globala (per användare) konfigurationsfilerna, om några finns.

De flesta sökvägsvärden innehåller bara ett värde. Vissa kan dock innehålla flera värden, som är separerade med radbrytningar, och listas i ordning från högsta till lägsta prioritet. Anropare bör vara beredda på att sådana sökvägsvärden kan innehålla flera objekt.

Observera att sökvägar skrivs ut även om de inte finns, men inte om de är inaktiverade av andra miljövariabler.

SE ÄVEN
-------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
En del av linkgit:git[1]-sviten
