git-check-attr(1)
=================

NAMN
----
git-check-attr - Visar information om gitattributes


SYNOPSIS
--------
[verse]
'git check-attr' [--source <trädlikt>] [-a | --all | <attr>...] [--] <sökvägsnamn>...
'git check-attr' --stdin [-z] [--source <trädlikt>] [-a | --all | <attr>...]

BESKRIVNING
-----------
För varje sökvägsnamn listar det här kommandot om varje attribut är 'unspecified', 'set' eller 'unset' som ett gitattribut för den sökvägen.

ALTERNATIV
----------
-a::
--all::
	Lista alla attribut som är associerade med de angivna sökvägarna. Om det här alternativet används kommer attribut med värdet 'unspecified' inte att inkluderas i utdata.

--cached::
	Betrakta endast `.gitattributes` i indexet och ignorera arbetsträdet.

--stdin::
	Läs sökvägar från standardinmatningen, en per rad, i stället för från kommandoraden.

-z::
	Utdataformatet är modifierat för att vara maskinparsbart. Om `--stdin` också anges, separeras indatavägarna med ett NUL-tecken i stället för ett radmatningstecken.

--source=<trädlikt>::
	Kontrollera attribut mot det angivna trädlikt. Det är vanligt att ange källträdet genom att namnge en incheckning, gren eller tagg som är associerad med det.

\--::
	Tolka alla föregående argument som attribut och alla efterföljande argument som sökvägsnamn.

Om inget av `--stdin`, `--all` eller `--` används, kommer det första argumentet att behandlas som ett attribut och resten av argumenten som sökvägsnamn.

UTMATNING
---------

Utdata är av formen: <sökväg> COLON SP <attribut> COLON SP <info> LF

om inte `-z` är aktivt, i vilket fall NUL används som avgränsare: <sökväg> NUL <attribut> NUL <info> NUL


<sökväg> är sökvägen till en fil som efterfrågas, <attribute> är ett attribut som efterfrågas och <info> kan vara antingen:

'unspecified';; när attributet inte är definierat för sökvägen.
'unset';;	när attributet är definierat som falskt.
'set';;		när attributet är definierat som sant.
<värde>;;	när ett värde har tilldelats attributet.

Buffring sker enligt beskrivningen under `GIT_FLUSH`-alternativet i linkgit:git[1]. Anroparen ansvarar för att undvika dödlägen orsakade av överfyllning av en inbuffert eller läsning från en tom utbuffert.

EXEMPEL
-------

I exemplen, används följande '.gitattributes'-fil:

---------------
*.java diff=java -crlf myAttr
NoMyAttr.java !myAttr
README caveat=unspecified
---------------

* Lista ett enda attribut:
+
---------------
$ git check-attr diff org/example/MyClass.java
org/example/MyClass.java: diff: java
---------------

* Lista flera attribut för en fil:
+
---------------
$ git check-attr crlf diff myAttr -- org/example/MyClass.java
org/example/MyClass.java: crlf: unset
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Lista alla attribut för en fil:
+
---------------
$ git check-attr --all -- org/example/MyClass.java
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Lista ett attribut för flera filer:
+
---------------
$ git check-attr myAttr -- org/example/MyClass.java org/example/NoMyAttr.java
org/example/MyClass.java: myAttr: set
org/example/NoMyAttr.java: myAttr: unspecified
---------------

* Inte alla värden är lika entydiga:
+
---------------
$ git check-attr caveat README
README: caveat: unspecified
---------------

SE ÄVEN
-------
linkgit:gitattributes[5].

GIT
---
En del av linkgit:git[1]-sviten
