git-prune(1)
============

NAMN
----
git-prune - Ta bort alla onåbara objekt från objektdatabasen


SYNOPSIS
--------
[verse]
'git prune' [-n] [-v] [--progress] [--expire <tid>] [--] [<huvud>...]

BESKRIVNING
-----------

NOTE: I de flesta fall, bör användare köra 'git gc', som anropar 'git prune'. Se avsnittet "ANMÄRKNINGAR" nedan.

Detta kör 'git fsck --unreachable' med alla referenser som finns i `refs/`, eventuellt med en ytterligare uppsättning objekt som anges på kommandoraden, och beskär alla opackade objekt som inte kan nås från något av dessa huvudobjekt från objektdatabasen. Dessutom rensar det de opackade objekten som också finns i paket genom att köra 'git prune-packed'. Det tar också bort poster från .git/shallow som inte kan nås av någon referens.

Observera att oåtkomliga, packade objekt kommer att finnas kvar. Om detta inte önskas, se linkgit:git-repack[1].

ALTERNATIV
----------

-n::
--dry-run::
	Ta inte bort något; rapportera bara vad det skulle ta bort.

-v::
--verbose::
	Rapportera alla borttagna objekt.

--progress::
	Visa förlopp.

--expire <tid>::
	Only expire loose objects older than <time>.

\--::
	Tolka inte fler argument som alternativ.

<huvud>...::
	Förutom objekt som kan nås från någon av våra referenser, behåll objekt som kan nås från listade <huvud>en.

EXEMPEL
-------

För att rensa objekt som inte används av ditt kodförråd eller ett annat som lånar från ditt kodförråd via dess `.git/objects/info/alternates`:

------------
$ git prune $(cd ../another && git rev-parse --all)
------------

NOTERINGAR
----------

I de flesta fall behöver användare inte anropa 'git prune' direkt, utan bör istället anropa 'git gc', som hanterar rensning tillsammans med många andra hushållningssuppgifter.

För en beskrivning av vilka objekt som beaktas för beskärning, se 'git fsck's --unreachable-alternativ.

SE ÄVEN
-------

linkgit:git-fsck[1], linkgit:git-gc[1], linkgit:git-reflog[1]

GIT
---
En del av linkgit:git[1]-sviten
