SAMMANSLAGNINGSSTRATEGIER
-------------------------

Sammanslagningsmekanismen (kommandona `git merge` och `git pull`) gﾃｶr det mﾃｶjligt att vﾃ､lja bakﾃ､nda-'sammanslagningsstrategier' med alternativet `-s`. Vissa strategier kan ocksﾃ･ ta sina egna alternativ, vilka kan skickas genom att ge `-X<alternativ>`-argument till `git merge` och/eller `git pull`.

`ort`::
	Detta ﾃ､r standardstrategin fﾃｶr sammanslagning nﾃ､r man drar in ("pulla") eller sammanfogar en gren. Denna strategi kan bara lﾃｶsa tvﾃ･ huvuden med hjﾃ､lp av en 3-vﾃ､gs sammanslagningsalgoritm. Nﾃ､r det finns mer ﾃ､n en gemensam fﾃｶrfader som kan anvﾃ､ndas fﾃｶr 3-vﾃ､gs sammanslagning skapas ett sammanslaget trﾃ､d av de gemensamma fﾃｶrfﾃ､derna och anvﾃ､nds som referenstrﾃ､d fﾃｶr 3-vﾃ､gs sammanslagningen. Detta har rapporterats resultera i fﾃ､rre sammanslagningskonflikter utan att orsaka felsammanslagningar, enligt tester gjorda pﾃ･ faktiska sammanslagningscommits hﾃ､mtade frﾃ･n Linux 2.6-kﾃ､rnans utvecklingshistorik. Dessutom kan denna strategi upptﾃ､cka och hantera sammanslagningar som involverar namnbyten. Den anvﾃ､nder inte upptﾃ､ckta kopior. Namnet pﾃ･ denna algoritm ﾃ､r en akronym ("Ostensibly Recursive's Twin") och kommer frﾃ･n det faktum att den skrevs som en ersﾃ､ttning fﾃｶr den tidigare standardalgoritmen, "rekursiv".
+
I det fall dﾃ､r sﾃｶkvﾃ､gen ﾃ､r en undermodul, och undermodul-incheckningen som anvﾃ､nds pﾃ･ ena sidan av sammanslagnings-sekvensen ﾃ､r en underordnad undermodul-incheckning som anvﾃ､nds pﾃ･ den andra sidan av merge-sekvensen, fﾃｶrsﾃｶker Git att snabbspola fram till underordnad. Annars kommer Git att behandla detta fall som en konflikt och fﾃｶreslﾃ･ som en lﾃｶsning en undermodul-incheckningen som ﾃ､r underordnad de konflikterande, om en sﾃ･dan finns.
+
`ort`-strategin kan ha fﾃｶljande alternativ:

`ours`;;
	Det hﾃ､r alternativet tvingar motstridiga stycken att automatiskt lﾃｶsas upp pﾃ･ ett snyggt sﾃ､tt genom att favorisera 'vﾃ･r' version. ﾃ⏋dringar frﾃ･n det andra trﾃ､det som inte stﾃ･r i konflikt med vﾃ･r sida ﾃ･terspeglas i sammanslagningsresultatet. Fﾃｶr en binﾃ､r fil hﾃ､mtas hela innehﾃ･llet frﾃ･n vﾃ･r sida.
+
Detta bﾃｶr inte fﾃｶrvﾃ､xlas med `ours` sammanslagningsstrategi, som inte ens tittar pﾃ･ vad det andra trﾃ､det innehﾃ･ller alls. Den kasserar allt som det andra trﾃ､det gjorde och deklarerar att 'vﾃ･r' historia innehﾃ･ller allt som hﾃ､nde i det.

`theirs`;;
	Detta ﾃ､r motsatsen till `ours`; observera att det, till skillnad frﾃ･n `ours`, inte finns nﾃ･gon `theirs`-sammanslagningsstrategi att fﾃｶrvﾃ､xla detta sammanslagningsalternativ med.

`ignore-space-change`;;
`ignore-all-space`;;
`ignore-space-at-eol`;;
`ignore-cr-at-eol`;;
	Behandlar rader med den angivna typen av blankteckenﾃ､ndring som ofﾃｶrﾃ､ndrade fﾃｶr en trevﾃ､gssammanslagning. ﾃ⏋dringar av blanktecken blandade med andra ﾃ､ndringar pﾃ･ en rad ignoreras inte. Se ﾃ､ven linkgit:git-diff[1] `-b`, `-w`, `--ignore-space-at-eol` och `--ignore-cr-at-eol`.
+
* Om 'deras' version bara introducerar ﾃ､ndringar av blanksteg pﾃ･ en rad anvﾃ､nds 'vﾃ･r' version;
* Om 'vﾃ･r' version introducerar ﾃ､ndringar i blanksteg men 'deras' version inkluderar en vﾃ､sentlig ﾃ､ndring, anvﾃ､nds 'deras' version;
* Annars fortsﾃ､tter sammanslagningen pﾃ･ vanligt sﾃ､tt.

`renormalize`;;
	Detta kﾃｶr en virtuell utcheckning och incheckning av alla tre stegen i alla filer som behﾃｶver en trevﾃ､gssammanslagning. Det hﾃ､r alternativet ﾃ､r avsett att anvﾃ､ndas vid sammanslagning av grenar med olika rena filter eller normaliseringsregler fﾃｶr radslut. Se "Sammanfoga grenar med olika inchecknings-/utcheckningsattribut" i linkgit:gitattributes[5] fﾃｶr mer information.

`no-renormalize`;;
	Inaktiverar alternativet `renormalize`. Detta ﾃ･sidosﾃ､tter konfigurationsvariabeln `merge.renormalize`.

`find-renames[=<n>]`;;
	Aktivera namnbytesdetektering, och stﾃ､ll in likhetstrﾃｶskeln om du vill. Detta ﾃ､r standardinstﾃ､llningen. Detta ﾃ･sidosﾃ､tter konfigurationsvariabeln `merge.renames`. Se ﾃ､ven linkgit:git-diff[1] `--find-renames`.

`rename-threshold=<n>`;;
	Fﾃｶrﾃ･ldrad synonym fﾃｶr `find-renames=<n>`.

`no-renames`;;
	Stﾃ､ng av namnbytesdetektering. Detta ﾃ･sidosﾃ､tter konfigurationsvariabeln `merge.renames`. Se ﾃ､ven linkgit:git-diff[1] `--no-renames`.

`histogram`;;
	Fﾃｶrﾃ･ldrad synonym fﾃｶr `diff-algoritm=histogram`.

`patience`;;
	Fﾃｶrﾃ･ldrad synonym fﾃｶr `diff-algoritm=patience`.

`diff-algorithm=(histogram|minimal|myers|patience)`;;
	Anvﾃ､nd en annan diff-algoritm vid sammanslagning, vilket kan bidra till att undvika felsammanslagningar som uppstﾃ･r pﾃ･ grund av oviktiga matchande rader (som klammerparenteser frﾃ･n olika funktioner). Se ﾃ､ven linkgit:git-diff[1] `--diff-algorithm`. Observera att `ort` som standard har `diff-algorithm=histogram`, medan vanliga diffs fﾃｶr nﾃ､rvarande har konfigurationsinstﾃ､llningen `diff.algorithm`.

`subtree[=<sﾃｶkvﾃ､g>]`;;
	Det hﾃ､r alternativet ﾃ､r en mer avancerad form av "undertrﾃ､dsstrategi" ('subtree'), dﾃ､r strategin gissar hur tvﾃ･ trﾃ､d mﾃ･ste flyttas fﾃｶr att matcha varandra vid sammanslagning. Istﾃ､llet prefixeras den angivna sﾃｶkvﾃ､gen (eller tas bort frﾃ･n bﾃｶrjan) fﾃｶr att fﾃ･ formen pﾃ･ de tvﾃ･ trﾃ､den att matcha.

`recursive`::
	Detta ﾃ､r nu en synonym fﾃｶr `ort`. Det var en alternativ implementering fram till v2.49.0, men omdirigerades till att betyda `ort` i v2.50.0. Den tidigare rekursiva strategin var standardstrategin fﾃｶr att lﾃｶsa tvﾃ･ huvuden frﾃ･n Git v0.99.9k till v2.33.0.

`resolve`::
	Detta kan bara lﾃｶsa tvﾃ･ huvuden (dvs. den aktuella grenen och en annan gren du hﾃ､mtade frﾃ･n) med hjﾃ､lp av en 3-vﾃ､gs merge-algoritm. Den fﾃｶrsﾃｶker noggrant upptﾃ､cka korsvisa sammanslagings-tvetydigheter. Den hanterar inte namnbyten.

`octopus`::
	Detta lﾃｶser fall med fler ﾃ､n tvﾃ･ huvuden, men vﾃ､grar att gﾃｶra en komplex sammanslagning som krﾃ､ver manuell lﾃｶsning. Det ﾃ､r frﾃ､mst avsett att anvﾃ､ndas fﾃｶr att paketera ﾃ､mnesgrenhuvuden. Detta ﾃ､r standardsammanslagningsstrategin nﾃ､r man drar in ("pullar") eller sammanfogar mer ﾃ､n en gren.

`ours`::
	Detta kan bara lﾃｶsa tvﾃ･ huvuden (dvs. den aktuella grenen och en annan gren du hﾃ､mtade frﾃ･n) med hjﾃ､lp av en 3-vﾃ､gs sammanslagnings-algoritm. Den fﾃｶrsﾃｶker noggrant upptﾃ､cka korsvisa sammanslagnings-tvetydigheter. Den hanterar inte namnbyten.

`subtree`::
	Detta ﾃ､r en modifierad `ort`-strategi. Nﾃ､r trﾃ､d A och B sammanfogas, och B motsvarar ett undertrﾃ､d till A, justeras B fﾃｶrst fﾃｶr att matcha trﾃ､dstrukturen fﾃｶr A, istﾃ､llet fﾃｶr att lﾃ､sa trﾃ､den pﾃ･ samma nivﾃ･. Denna justering gﾃｶrs ocksﾃ･ pﾃ･ det gemensamma fﾃｶrfader-trﾃ､det.

Med strategier som anvﾃ､nder 3-vﾃ､gssammanslagning (inklusive standardvﾃ､rdet `ort`), om en ﾃ､ndring gﾃｶrs pﾃ･ bﾃ･da grenarna, men senare ﾃ･ngrad pﾃ･ en av grenarna, kommer den ﾃ､ndringen att finnas i det sammanslagna resultatet; vissa personer tycker att detta beteende ﾃ､r fﾃｶrvirrande. Det intrﾃ､ffar eftersom endast huvuden och sammanslagningsbasen beaktas nﾃ､r en sammanslagning utfﾃｶrs, inte de enskilda incheckningarna. Sammanslagningsalgoritmen betraktar dﾃ､rfﾃｶr den ﾃ･ngrade ﾃ､ndringen som ingen ﾃ､ndring alls och ersﾃ､tter den ﾃ､ndrade versionen istﾃ､llet.
