SAMMANSLAGNINGSSTRATEGIER
-------------------------

Sammanslagningsmekanismen (kommandona `git merge` och `git pull`) gör det möjligt att välja bakändens sammanslagningsstrategier med alternativet `-s`. Vissa strategier kan också ta sina egna alternativ, vilka kan skickas genom att ge `-X<alternativ>`-argument till `git merge` och/eller `git pull`.

`ort`::
	Det är standardstrategin för sammanslagning när man hämtar eller sammanfogar en gren. Denna strategi kan bara lösa två huvuden med hjälp av en 3-vägs sammanslagningsalgoritm. När det finns mer än en gemensam förfader som kan användas för 3-vägs sammanslagning skapas ett sammanslaget träd av de gemensamma förfäderna och används som referensträd för 3-vägs sammanslagningen. Detta har rapporterats resultera i färre sammanslagningskonflikter utan att orsaka felsammanslagningar, enligt tester gjorda på faktiska sammanslagningsincheckningar hämtade från Linux 2.6-kärnans utvecklingshistorik. Dessutom kan denna strategi upptäcka och hantera sammanslagningar som involverar namnbyten. Den använder inte upptäckta kopior. Namnet på denna algoritm är en akronym ("Ostensibly Recursive's Twin") och kommer från det faktum att den skrevs som en ersättning för den tidigare standardalgoritmen, "rekursiv".
+
I det fall där sökvägen är en undermodul, och undermodul-incheckningen som används på ena sidan av sammanslagnings-sekvensen är en underordnad undermodul-incheckning som används på den andra sidan av merge-sekvensen, försöker Git att snabbspola fram till underordnad. Annars kommer Git att behandla detta fall som en konflikt och föreslå som en lösning en undermodul-incheckningen som är underordnad de konflikterande, om en sådan finns.
+
`ort`-strategin kan ha följande alternativ:

`ours`;;
	Alternativet tvingar motstridiga hunks att automatiskt lösas upp på ett snyggt sätt genom att favorisera 'vår' version. Ändringar från det andra trädet som inte står i konflikt med vår sida återspeglas i sammanslagningsresultatet. För en binär fil hämtas hela innehållet från vår sida.
+
Det bör inte förväxlas med `ours` sammanslagningsstrategi, som inte ens tittar på vad det andra trädet innehåller alls. Den kasserar allt som det andra trädet gjorde och deklarerar att 'vår' historia innehåller allt som hände i det.

`theirs`;;
	Det är motsatsen till `ours`; observera att det, till skillnad från `ours`, inte finns någon `theirs`-sammanslagningsstrategi att förväxla detta sammanslagningsalternativ med.

`ignore-space-change`;;
`ignore-all-space`;;
`ignore-space-at-eol`;;
`ignore-cr-at-eol`;;
	Behandlar rader med den angivna typen av blankteckenändring som oförändrade för en trevägssammanslagning. Ändringar av blanktecken blandade med andra ändringar på en rad ignoreras inte. Se även linkgit:git-diff[1] `-b`, `-w`, `--ignore-space-at-eol` och `--ignore-cr-at-eol`.
+
* Om 'deras' version bara introducerar ändringar av blanksteg på en rad används 'vår' version;
* Om 'vår' version introducerar ändringar i blanksteg men 'deras' version inkluderar en väsentlig ändring, används 'deras' version;
* Annars fortsätter sammanslagningen på vanligt sätt.

`renormalize`;;
	Det kör en virtuell utcheckning och incheckning av alla tre stegen i alla filer som behöver en trevägssammanslagning. Alternativet är avsett att användas vid sammanslagning av grenar med olika rena filter eller normaliseringsregler för radslut. Se "Sammanfoga grenar med olika inchecknings-/utcheckningsattribut" i linkgit:gitattributes[5] för mer information.

`no-renormalize`;;
	Inaktiverar alternativet `renormalize`. Detta åsidosätter konfigurationsvariabeln `merge.renormalize`.

`find-renames[=<n>]`;;
	Aktivera namnbytesdetektering, och ställ in likhetströskeln om du vill. Detta är standardinställningen. Detta åsidosätter konfigurationsvariabeln `merge.renames`. Se även linkgit:git-diff[1] `--find-renames`.

`rename-threshold=<n>`;;
	Föråldrad synonym för `find-renames=<n>`.

`no-renames`;;
	Stäng av namnbytesdetektering. Detta åsidosätter konfigurationsvariabeln `merge.renames`. Se även linkgit:git-diff[1] `--no-renames`.

`histogram`;;
	Föråldrad synonym för `diff-algoritm=histogram`.

`patience`;;
	Föråldrad synonym för `diff-algoritm=patience`.

`diff-algorithm=(histogram|minimal|myers|patience)`;;
	Använd en annan diff-algoritm vid sammanslagning, vilket kan bidra till att undvika felsammanslagningar som uppstår på grund av oviktiga matchande rader (som klammerparenteser från olika funktioner). Se även linkgit:git-diff[1] `--diff-algorithm`. Observera att `ort` som standard har `diff-algorithm=histogram`, medan vanliga diffar för närvarande har konfigurationsinställningen `diff.algorithm`.

`subtree[=<sökväg>]`;;
	Alternativet är en mer avancerad form av "underträdsstrategi" ('subtree'), där strategin gissar hur två träd måste flyttas för att matcha varandra vid sammanslagning. I stället prefixeras den angivna sökvägen (eller tas bort från början) för att få formen på de två träden att matcha.

`recursive`::
	Det är nu en synonym för `ort`. Det var en alternativ implementering fram till v2.49.0, men omdirigerades till att betyda `ort` i v2.50.0. Den tidigare rekursiva strategin var standardstrategin för att lösa två huvuden från Git v0.99.9k till v2.33.0.

`resolve`::
	Det kan bara lösa två huvuden (dvs. den aktuella grenen och en annan gren du hämtade från) med hjälp av en 3-vägs sammanslagningsalgoritm. Den försöker noggrant upptäcka korsvisa sammanslagningsambiguiteter. Den hanterar inte namnbyten.

`octopus`::
	Det löser fall med fler än två huvuden, men vägrar att göra en komplex sammanslagning som kräver manuell lösning. Det är främst avsett att användas för att paketera ämnesgrenhuvuden. Detta är standardsammanslagningsstrategin när man hämtar eller sammanfogar mer än en gren.

`ours`::
	Det löser valfritt antal huvuden, men det resulterande trädet från sammanslagningen är alltid det från den aktuella grenens topp, vilket i praktiken ignorerar alla ändringar från alla andra grenar. Det är avsett att användas för att ersätta gammal utvecklingshistorik från sidogrenar. Observera att detta skiljer sig från alternativet `-Xours` till sammanslagningsstrategin `ort`.

`subtree`::
	Det är en modifierad `ort`-strategi. När träd A och B sammanfogas, och B motsvarar ett underträd till A, justeras B först för att matcha trädstrukturen för A, i stället för att läsa träden på samma nivå. Denna justering görs också på det gemensamma förfader-trädet.

Med strategier som använder 3-vägssammanslagning (inklusive standardvärdet `ort`), om en ändring görs på båda grenarna, men senare ångrad på en av grenarna, kommer den ändringen att finnas i det sammanslagna resultatet; vissa personer tycker att detta beteende är förvirrande. Det inträffar eftersom endast huvuden och sammanslagningsbasen beaktas när en sammanslagning utförs, inte de enskilda incheckningarna. Sammanslagningsalgoritmen betraktar därför den ångrade ändringen som ingen ändring alls och ersätter den ändrade versionen i stället.
