include::urls.adoc[]

FJÄRR[[REMOTES]]
----------------

Namnet på en av följande kan användas istället för en URL som _<kodförråd>_ argument:

* en fjärr i Git-konfigurationsfilen: `$GIT_DIR/config`,
* en fil i katalogen `$GIT_DIR/remotes`, eller
* en fil i katalogen `$GIT_DIR/branches`.

Alla dessa låter dig också utelämna referensspecifikationen från kommandoraden eftersom de var och en innehåller en referensspecifikation som git kommer att använda som standard.

Namngiven fjärr i konfigurationsfilen
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Du kan välja att ange namnet på en fjärren som du tidigare konfigurerat med hjälp av linkgit:git-remote[1], linkgit:git-config[1] eller till och med genom en manuell redigering av filen `$GIT_DIR/config`. URL:en för denna fjärr kommer att användas för att komma åt kodförrådet. Referensspecifikationen för denna fjärr kommer att användas som standard när du inte anger en referensspecifikation på kommandoraden. Posten i konfigurationsfilen skulle se ut så här:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

_<pushurl>_ används endast för sänding ("pusha"). Det är valfritt och standardvärdet är _<URL>_. Att säda till en fjärr påverkar alla definierade push-adresser eller alla definierade webbadresser om inga sänd-adresser (push) är definierade. Fetch hämtar dock bara från den först definierade webbadressen om flera webbadresser är definierade.

Namngiven fil i `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Du kan välja att ange namnet på en fil i `$GIT_DIR/remotes`. URL:en i den här filen kommer att användas för att komma åt kodförrådet. Referensspecifikationen i den här filen kommer att användas som standard när du inte anger en referensspecifikation på kommandoraden. Den här filen ska ha följande format:

------------
	URL: ett av ovanstående URL-format
	Push: <refspec>
	Pull: <refspec>

------------

`Push:`-rader används av `git push` och `Pull:`-rader används av `git pull` och `git fetch`. Flera `Push:`- och `Pull:`-rader kan anges för ytterligare grenmappningar.

Namngiven fil i `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Du kan välja att ange namnet på en fil i `$GIT_DIR/branches`. URL:en i den här filen kommer att användas för att komma åt kodförrådet. Filen ska ha följande format:


------------
	<URL>#<huvud>
------------

_<URL>_ krävs; `#<huvud>` är valfritt.

Beroende på operationen, kommer git att använda en av följande referensspecifikationer, om du inte anger någon på kommandoraden. _<gren>_ är namnet på den här filen i `$GIT_DIR/branches` och _<huvud>_ har som standard `master`.

git fetch använder:

------------
	refs/heads/<huvud>:refs/heads/<gren>
------------

git push använder:

------------
	HEAD:refs/heads/<huvud>
------------


[[UPSTREAM-BRANCHES]]
UPPSTRÖMS-GRENAR
----------------

Grenar i Git kan valfritt ha en uppströms fjärrgren. Git använder som standard uppströmsgrenen för fjärroperationer, till exempel:

* Det är standardvärdet för `git pull` eller `git fetch` utan argument.
* Det är standardinställningen för `git push` utan argument, med vissa undantag. Du kan till exempel använda alternativet `branch.<name>.pushRemote` för att pusha till en annan fjärr än den du hämtar från, och som standard med `push.default=simple` måste den uppströmsgren du konfigurerar ha samma namn.
* Olika kommandon, inklusive `git checkout` och `git status`, visar hur många incheckningar som har lagts till i din nuvarande grenen och upstream sedan du avgrenade från den, till exempel "Din branch och 'origin/main' har divergerat och har 2 respektive 3 olika incheckningar".

Uppströmmen lagras i `.git/config`, i fälten "`remote`" och "`merge`". Till exempel, om `main`s uppstrom är `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Du kan explicit ställa in en uppströmsgren med `git push --set-upstream <fjärr> <gren>` men Git kommer ofta automatiskt att ställa in uppströmsen åt dig, till exempel:

* När du klonar ett kodförråd kommer Git automatiskt att ställa in uppströmmen för standardgrenen.
* Om du har konfigurationsalternativet `push.autoSetupRemote` aktiverat, kommer `git push` automatiskt att ställa in uppströmsen första gången du pushar en branch.
* Att checka ut en fjärrspårningsgren med `git checkout <gren>` skapar automatiskt en lokal gren med det namnet och ställer in uppströmmen på den fjärranslutna grenen.

[NOTE]
Uppströms grenar kallas ibland för "spårningsinformation", som i "ange grenens spårningsinformation".
