Raw output format
-----------------

`git-diff-index`、`git-diff-tree`、`git-diff-files`、`git diff --raw`からの生の出力フォーマットは非常に似ています。

これらのコマンドはすべて、2つのセットを比較します。比較されるものは異なります：

`git-diff-index <tree-ish>`::
	_<tree-ish>_とファイルシステム上のファイルを比較します。

`git-diff-index --cached <tree-ish>`::
	_<tree-ish>_とインデックスを比較します。

`git-diff-tree [-r] <tree-ish-1> <tree-ish-2> [<パターン>...]`::
        2つの引数で指定されたツリーを比較します。

`git-diff-files [<パターン>...]`::
        インデックスとファイルシステム上のファイルを比較します。

`git-diff-tree`コマンドは、比較対象のハッシュを表示することから出力を始めます。その後、すべてのコマンドは変更されたファイルごとに1行の出力を表示します。

出力行はこのようなフォーマットになっています：

------------------------------------------------
in-place edit  :100644 100644 bcd1234 0123456 M file0
copy-edit      :100644 100644 abcd123 1234567 C68 file1 file2
rename-edit    :100644 100644 abcd123 1234567 R86 file1 file3
create         :000000 100644 0000000 1234567 A file4
delete         :100644 000000 1234567 0000000 D file5
unmerged       :000000 000000 0000000 0000000 U file6
------------------------------------------------

これは、左から右に：

. コロン。
. "src"のモード。作成またはマージされていない場合は 000000。
. 空白。
. "dst"のモード。削除またはマージされていない場合は 000000。
. 空白。
. "src"のsha1。作成またはマージされていない場合は 0\{40\}。
. 空白。
. "dst"のsha1。削除、マージされていない、または「ワークツリーがインデックスと同期していない」場合は 0\{40\}。
. 空白。
. ステータス、後ろにオプションで「スコア」の数字が続きます。
. タブ、`-z` オプションが使用されている場合はNUL。
. "src"のパス
. タブ、`-z` オプションが使用されている場合はNUL。 CまたはRの場合にのみ存在します。
. "dst"のパス。 CまたはRの場合にのみ存在します。
. LF、`-z` オプションが使用されている場合はNULで、レコードを終了します。

可能なステータス文字は:

- `A`: ファイルの追加
- `C`: ファイルを新しいファイルにコピー
- `D`: ファイルの削除
- `M`: ファイルの内容やモードの変更
- `R`: ファイルの名前変更
- `T`: ファイルの種類の変更 (通常のファイル、シンボリックリンク、サブモジュール)
- `U`: ファイルはマージされていません (コミットする前にマージを完了する必要があります)
- `X`: "不明な" 変更タイプ (おそらくバグです。報告してください)

ステータス文字`C`と`R`の後には常にスコア（移動やコピーのソースとターゲットの類似性の割合を示す）が付きます。ファイルの書き換えの場合、ステータス文字`M`の後にスコア（非類似度の割合を示す）が付くことがあります。

"dst"のsha1は、ファイルシステム上でファイルがインデックスと同期していない場合、すべて0と表示されます。

例:

------------------------------------------------
:100644 100644 5be4a4a 0000000 M file.c
------------------------------------------------

`-z` オプションをつけないと、設定変数 `core.quotePath` (linkgit:git-config[1]参照) の説明にしたがって、「普通でない」文字を含むパス名が引用されます。`-z` を使うと、ファイル名はそのまま出力され、行は NUL バイトで終了します。

マージ用のdiffフォーマット
---------------

`git-diff-tree`、`git-diff-files`、`git-diff --raw`は`-c`または`--cc`オプションを取り、マージコミットに対してもdiff出力を生成できます。出力は上記のフォーマットと以下の点で異なります：

. それぞれの親にコロンがある
. より多くの "src" モードと "src" sha1がある
. ステータスは各親のステータス文字を連結したもの
. オプションの "スコア" 数値はない
. タブで区切られたファイルのパス名(複数可)

`-c` と `--cc` では、ファイルの名前が歴史のいずれかの側で変更された場合でも、宛先または最終パスのみが表示されます。`--combined-all-paths` では、それぞれの親のパスの名前の後に、マージコミットのパスの名前が表示されます。

`--combined-all-paths` を使用しない `-c` および `--cc` の例：

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	phooey.c
------------------------------------------------

`--combined-all-paths` が `-c` または `--cc` のいずれかに追加された場合の例：

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c	desc.c	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	foo.sh	bar.sh	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	fooey.c	fuey.c	phooey.c
------------------------------------------------

'combined diff'は、すべての親から変更されたファイルのみをリストすることに注意してください。


include::diff-generate-patch.adoc[]


その他のdiffフォーマット
--------------

`--summary` オプションでは、新しく追加されたファイル、削除されたファイル、名前が変更されたファイル、コピーされたファイルについて説明します。`--stat` オプションは、`diffstat`(1)のグラフを出力に追加します。これらのオプションは、`-p` などの他のオプションと組み合わせることができ、人間が読むことを目的としています。

名前の変更やコピーを伴う変更を表示する場合、`--stat` の出力では、パス名の共通の接頭辞と接尾辞を組み合わせて、パス名をコンパクトにフォーマットします。例えば、`arch/i386/Makefile` を `arch/x86/Makefile` に移動し、4行を変更した場合、以下のように表示されます：

------------------------------------
arch/{i386 => x86}/Makefile    |   4 +--
------------------------------------

`--numstat` オプションは、diffstat(1)の情報を提供しますが、機械での処理が容易になるように設計されています。`--numstat` の出力のエントリは次のようになります：

----------------------------------------
1	2	README
3	1	arch/{i386 => x86}/Makefile
----------------------------------------

これは、左から右に:

. 追加された行の数;
. タブ;
. 削除された行の数;
. タブ;
. パス名 (場合によってはリネーム/コピー情報を含む);
. 改行。

出力オプションの `-z` が有効な場合、出力はこのようにフォーマットされます：

----------------------------------------
1	2	README NUL
3	1	NUL arch/i386/Makefile NUL arch/x86/Makefile NUL
----------------------------------------

これは:

. 追加された行の数;
. タブ;
. 削除された行の数;
. タブ;
. NUL (リネーム/コピーされた場合のみ存在);
. プリイメージのパス名;
. NUL (リネーム/コピーされた場合のみ存在);
. ポストイメージのパス名 (リネーム/コピーされた場合のみ存在);
. NUL。

名前を変更した場合のプリイメージパスの前に余分な `NUL` があるのは、出力を読むスクリプトが、現在読まれているレコードがシングルパスのレコードなのか、リネーム/コピーのレコードなのかを、先を読まずに判別できるようにするためです。追加された行や削除された行を読んだ後、`NUL` まで読めばパス名がわかりますが、それが `NUL` であれば、レコードは2つのパスを示します。
