`push.autoSetupRemote`::
	Якщо встановлено значення `true`, під час стандартного надсилання (push) передбачається використання параметра `--set-upstream`, якщо для поточної гілки відсутнє відстеження upstream; ця опція діє разом із значеннями параметра `push.default`: `simple`, `upstream` та `current`. Це корисно, якщо ви хочете, щоб нові гілки стандартно надсилалися до стандартного віддаленого репозиторію (як у випадку з `push.default=current`) і водночас бажаєте встановити відстеження upstream. Робочі процеси, які, найімовірніше, отримають користь від цієї опції, — це централізовані робочі процеси `simple`, де очікується, що всі гілки матимуть однакову назву на віддаленому сервері.

`push.default`::
	Визначає, яку дію має виконати команда `git push`, якщо не вказано refspec (ні в командному рядку, ні в конфігурації, ні деінде). Різні значення підходять для конкретних робочих процесів; наприклад, у суто централізованому робочому процесі (тобто джерело fetch збігається з пунктом призначення push) вам, ймовірно, підійде значення `upstream`. Можливі значення:
+
--
`nothing`;;
не виконувати жодних дій (видавати помилку), якщо не вказано refspec. Ця функція призначена насамперед для тих, хто хоче уникнути помилок, завжди вказуючи параметри явно.

`current`;;
надсилати поточну гілку, щоб оновити гілку з такою самою назвою на стороні одержувача. Працює як у централізованих, так і в децентралізованих робочих процесах.

`upstream`;;
надсилати поточну гілку назад до гілки, зміни якої зазвичай інтегруються в поточну гілку (яка називається `@{upstream}`). Цей режим має сенс лише в тому випадку, якщо ви надсилаєте дані до того самого репозиторію, з якого зазвичай отримуєте оновлення (тобто централізований робочий процес).

`tracking`;;
це застарілий синонім для `upstream`.

`simple`;;
надсилати поточну гілку з такою ж назвою до віддаленого репозиторію.
+
Якщо ви працюєте в централізованому робочому процесі (надсилаєте зміни до того ж репозиторію звідки ви отримуєте дані, який типово є `origin`), — вам треба налаштувати висхідну гілку з такою ж назвою.
+
Цей режим є стандартним в Git 2.0 та найбезпечнішим варіантом для початківців.

`matching`;;
надсилати всі гілки, що мають однакову назву на обох сторонах. Це дозволяє репозиторію, куди ви надсилаєте дані, запам’ятати набір гілок, які будуть надіслані (наприклад, якщо ви завжди надсилаєте туди гілки `maint` і `master`, а не інші, репозиторій, куди ви надсилаєте дані, матиме ці дві гілки, і ваші локальні гілки `maint` та `master` будуть туди надіслані).
+
Щоб ефективно використовувати цей режим, перед виконанням команди `git push` потрібно переконатися, що _всі_ гілки, які ви збираєтеся надіслати, готові до надсилання, оскільки суть цього режиму полягає в тому, щоб дозволити вам надіслати всі гілки за один раз. Якщо ви зазвичай закінчуєте роботу лише над однією гілкою і надсилаєте результат, тоді як інші гілки залишаються незавершеними, цей режим вам не підходить. Також цей режим не підходить для надсилання до спільного центрального репозиторію, оскільки інші люди можуть додавати туди нові гілки або оновлювати вершини наявних гілок поза вашим контролем.
+
Раніше це було стандартним налаштуванням, але з версії Git 2.0 це змінилося (тепер стандартним налаштуванням є `simple`).

--

`push.followTags`::
	Якщо встановлено — true, стандартно увімкнути опцію `--follow-tags`. Ви можете перевизначити це налаштування будь-коли за допомогою `--no-follow-tags`.

`push.gpgSign`::
	Може приймати булеве значення або рядок `if-asked`. Значення true призводить до того, що всі операції push підписуються GPG, так само, якби до команди linkgit:git-push[1] було передано параметр `--signed`. Рядок `if-asked` призводить до того, що надсилання підписуються, якщо сервер це підтримує, так само, якби до `git push` було передано `--signed=if-asked`. Значення false може замінити значення з файлу конфігурації з нижчим пріоритетом. Явний прапорець командного рядка завжди замінює цю опцію конфігурації.

`push.pushOption`::
	Коли в командному рядку немає аргументу `--push-option=<option>`, `git push` поводиться так ніби кожне значення _<option>_ цієї змінної було вказано через `--push-option=<option>`.
+
Це багатозначна змінна, і в конфігураційному файлі з вищим пріоритетом (наприклад, `.git/config` у репозиторії) можна вказати порожнє значення, щоб скинути значення, успадковані з конфігураційних файлів з нижчим пріоритетом (наприклад, `$HOME/.gitconfig`).
+
----

Приклад:

/etc/gitconfig
  push.pushoption = a
  push.pushoption = b

~/.gitconfig
  push.pushoption = c

repo/.git/config
  push.pushoption =
  push.pushoption = b

У результаті залишиться лише b (a та c будуть очищені).

----

`push.recurseSubmodules`::
	Може бути `check`, `on-demand`, `only` або `no`, з такою ж поведінкою як і в `push --recurse-submodules`. Якщо не встановлено, стандартним вважається значення — `no`, якщо тільки не встановлено submodule.recurse (в такому випадку `true` означатиме `on-demand`).

`push.useForceIfIncludes`::
	Якщо встановлено — true, це є еквівалентом до використання `--force-if-includes` як параметра linkgit:git-push[1] в командному рядку. Додавання `--no-force-if-includes` під час виконання надсилання перевизначає це налаштування.

`push.negotiate`::
	Якщо встановлено — true, намагатись зменшити розмір файлу pack через спроби узгодження, де клієнт та сервер намагаються знайти спільні коміти. Якщо значення — `false`, Git буде покладатись виключно на посилання, оголошені сервером, для пошуку спільних комітів.

`push.useBitmaps`::
	Якщо встановлено — `false`, використання бітових мап для команди `git push` буде вимкнено, навіть якщо для параметра `pack.useBitmaps` встановлено значення `true`, однак це не заважатиме використанню бітових мап в інших операціях git. Стандартне значення — `true`.
