rebase.backend::
	Стандартний бекенд, що використовується для перебазування. Можливі значення: 'apply' або 'merge'. В майбутньому, якщо бекенд 'merge' набуде всіх можливостей бекенда 'apply, цей параметр перестане використовуватись.

rebase.stat::
	Чи виводити diffstat для того що було змінено в upstream з моменту останнього перебазування. Стандартне значення — false.

rebase.autoSquash::
	Якщо значення — true, параметр `--autosquash` є стандартно увімкненим для linkgit:git-rebase[1] в інтерактивному режимі. Він може бути перевизначений за допомоги `--no-autosquash`.

rebase.autoStash::
	Якщо значення — true, автоматично створюється тимчасовий елемент stash перед початком операції та застосовується після її завершення. Це означає, що ви можете запустити перебазування на робочому дереві, що містить незафіксовані зміни. Однак використовуйте з обережністю: остаточне застосування stash після успішного перебазування може призвести до складних конфліктів. Цей параметр можна перевизначити параметрами `--no-autostash` та `--autostash` команди linkgit:git-rebase[1]. Стандартне значення — false.

rebase.updateRefs::
	Якщо значення — true, опція `--update-refs` є стандартно увімкненою.

rebase.missingCommitsCheck::
	Якщо значення — "warn", `git rebase -i …`буде показувати попередження якщо деякі з комітів будуть вилучені (напр. рядок коміту було вилучено), однак перебазування буде продовжене. Якщо значення — "error", буде показане попереднє попередження, а перебазування буде призупинене, для виправлення помилки можна скористатись `git rebase --edit-todo`. Якщо значення — "ignore", перевірки не виконуються. Для того, щоб відкинути коміт без попереджень чи помилок використовуйте команду `drop` в переліку завдань. Стандартне значення — "ignore".

rebase.instructionFormat::
	Рядок форматування, як зазначено в linkgit:git-log[1], який використовується для списку завдань під час інтерактивного перебазування. До цього рядка автоматично додається хеш коміту.

rebase.abbreviateCommands::
	Якщо значення — true, `git rebase` буде використовувати скорочені назви команд в переліку завдань, що призведе до чогось подібного:
+
-------------------------------------------
	p deadbee The oneline of the commit
	p fa1afe1 The oneline of the next commit
	...
-------------------------------------------
+
а не:
+
-------------------------------------------
	pick deadbee The oneline of the commit
	pick fa1afe1 The oneline of the next commit
	...
-------------------------------------------
+
Стандартне значення — false.

rebase.rescheduleFailedExec::
	Автоматично перепланувати команди `exec`, виконання яких завершилося з помилкою. Це має сенс лише в інтерактивному режимі (або якщо вказано параметр `--exec`). Це еквівалентно вказівці параметра `--reschedule-failed-exec`.

rebase.forkPoint::
	Якщо значення — false, опція `--no-fork-point` є стандартно увімкненою.

rebase.rebaseMerges::
	Чи стандартно встановлювати опцію `--rebase-merges` і як саме. Може приймати значення `rebase-cousins`, `no-rebase-cousins` або булеве значення. Встановлення значення true або `no-rebase-cousins` еквівалентно `--rebase-merges=no-rebase-cousins`, встановлення значення `rebase-cousins` еквівалентно `--rebase-merges=rebase-cousins`, а встановлення значення false еквівалентно `--no-rebase-merges`. Передача `--rebase-merges` у командному рядку, з аргументом або без нього, замінює будь-яку конфігурацію `rebase.rebaseMerges`.

rebase.maxLabelLength::
	Під час формування імен міток на основі тем комітів скорочувати імена до цієї довжини. Стандартно імена скорочуються до довжини, трохи меншої за `NAME_MAX` (щоб, наприклад, можна було створювати файли `.lock` для відповідних вільних посилань).
