ФАЙЛ КОНФИГУРАЦИИ
-----------------

Файл конфигурации Git содержит ряд переменных, влияющих на поведение команд Git. Файлы `.git/config` и, возможно, `config.worktree` (см. раздел «ФАЙЛ КОНФИГУРАЦИИ» в linkgit:git-worktree[1]) в каждом репозитории используются для хранения конфигурации для этого репозитория, а `$HOME/.gitconfig` используется для хранения общепользовательской конфигурации в качестве запасных значений для файла `.git/config`. Файл `/etc/gitconfig` можно использовать для хранения общесистемной конфигурации по умолчанию.

Переменные конфигурации используются как внутренними (plumbing) командами Git, так и высокоуровневыми (porcelain). Переменные разделены на разделы, причём полное имя переменной — это последний сегмент, разделённый точками, а имя раздела — всё, что находится перед последней точкой. Имена переменных не чувствительны к регистру, могут содержать только буквенно-цифровые символы и `-` и должны начинаться с буквы. Некоторые переменные могут встречаться несколько раз; в этом случае говорят, что переменная является многозначной.

Синтаксис
~~~~~~~~~

Синтаксис довольно гибкий и свободный. Пробельные символы, которыми в данном контексте являются символ пробела (SP) и горизонтальная табуляция (HT), в основном игнорируются. Символы '#' и ';' начинают комментарии до конца строки. Пустые строки игнорируются.

Файл состоит из разделов и переменных. Раздел начинается с имени раздела в квадратных скобках и продолжается до начала следующего раздела. Имена разделов не чувствительны к регистру. В именах разделов разрешены только буквенно-цифровые символы, `-` и `.`. Каждая переменная должна принадлежать некоторому разделу, что означает, что перед первой установкой переменной должен быть заголовок раздела.

Разделы могут быть дополнительно разделены на подразделы. Чтобы начать подраздел, поместите его имя в двойные кавычки, отделённые пробелом от имени раздела, в заголовке раздела, как в примере ниже:

--------
	[раздел "подраздел"]

--------

Имена подразделов чувствительны к регистру и могут содержать любые символы, кроме новой строки и нулевого байта. Двойные кавычки `"` и обратную косую черту можно включить, экранируя их как `\"` и `\\` соответственно. Обратные косые черты перед другими символами отбрасываются при чтении; например, `\t` читается как `t`, а `\0` читается как `0`. Заголовки разделов не могут занимать несколько строк. Переменные могут принадлежать непосредственно разделу или данному подразделу. Вы можете иметь `[раздел]`, если у вас есть `[раздел "подраздел"]`, но это не обязательно.

Существует также устаревший синтаксис `[раздел.подраздел]`. При этом синтаксисе имя подраздела преобразуется в нижний регистр, а также сравнивается с учётом регистра. Эти имена подразделов подчиняются тем же ограничениям, что и имена разделов.

Все остальные строки (и остаток строки после заголовка раздела) распознаются как установка переменных в форме 'имя = значение' (или просто 'имя', что является сокращением, означающим, что переменная является логической «true»). Имена переменных не чувствительны к регистру, могут содержать только буквенно-цифровые символы и `-` и должны начинаться с буквы.

Пробельные символы вокруг `имени`, `=` и `значения` отбрасываются. Внутренние пробельные символы внутри 'значения' сохраняются дословно. Комментарии, начинающиеся с `#` или `;` и продолжающиеся до конца строки, отбрасываются. Строка, определяющая значение, может быть продолжена на следующую строку, если завершить её обратной косой чертой (`\`); обратная косая черта и символы конца строки отбрасываются.

Если `значение` должно содержать начальные или конечные пробельные символы, оно должно быть заключено в двойные кавычки (`"`). Внутри двойных кавычек символы двойной кавычки (`"`) и обратной косой черты (`\`) должны быть экранированы: используйте `\"` для `"` и `\\` для `\`.

Распознаются следующие escape-последовательности (кроме `\"` и `\\`): `\n` для символа новой строки (NL), `\t` для горизонтальной табуляции (HT, TAB) и `\b` для backspace (BS). Другие escape-последовательности символов (включая восьмеричные escape-последовательности) недействительны.


Включает
~~~~~~~~

Разделы `include` и `includeIf` позволяют включать директивы конфигурации из другого источника. Эти разделы ведут себя идентично друг другу, за исключением того, что разделы `includeIf` могут быть проигнорированы, если их условие не вычисляется как true; см. «Условные включения» ниже.

Вы можете включить файл конфигурации из другого, установив специальную переменную `include.path` (или `includeIf.*.path`) в имя файла, который должен быть включён. Переменная принимает имя пути в качестве значения и подвержена расширению тильды. Эти переменные могут быть заданы несколько раз.

Содержимое включаемого файла вставляется немедленно, как если бы оно было найдено в месте расположения директивы include. Если значение переменной является относительным путём, путь считается относительным к файлу конфигурации, в котором была найдена директива include. Примеры см. ниже.

Условные включения
~~~~~~~~~~~~~~~~~~

Вы можете условно включить файл конфигурации из другого, установив переменную `includeIf.<условие>.path` в имя включаемого файла.

Условие начинается с ключевого слова, за которым следует двоеточие и некоторые данные, формат и значение которых зависят от ключевого слова. Поддерживаются следующие ключевые слова:

`gitdir`::
	Данные, следующие за ключевым словом `gitdir` и двоеточием, используются в качестве glob-шаблона. Если местоположение каталога .git соответствует шаблону, условие включения выполнено.
+
Местоположение .git может быть автоматически обнаружено или получено из переменной среды `$GIT_DIR`. Если репозиторий автоматически обнаружен через файл .git (например, из подмодулей или связанной рабочей копии), местоположением .git будет конечное местоположение каталога .git, а не то, где находится файл .git.
+
Шаблон может содержать стандартные wildcard-символы glob и два дополнительных, `**/` и `/**`, которые могут соответствовать нескольким компонентам пути. Подробности см. в linkgit:gitignore[5]. Для удобства:

 * Если шаблон начинается с `~/`, `~` будет заменён содержимым переменной среды `HOME`.

 * Если шаблон начинается с `./`, он заменяется каталогом, содержащим текущий файл конфигурации.

 * Если шаблон не начинается с `~/`, `./` или `/`, автоматически добавляется `**/`. Например, шаблон `foo/bar` становится `**/foo/bar` и будет соответствовать `/any/path/to/foo/bar`.

 * Если шаблон заканчивается на `/`, автоматически добавляется `**`. Например, шаблон `foo/` становится `foo/**`. Другими словами, он соответствует "foo" и всему, что внутри, рекурсивно.

`gitdir/i`::
	Это то же самое, что и `gitdir`, за исключением того, что сопоставление выполняется без учёта регистра (например, в файловых системах, не чувствительных к регистру)

`onbranch`::
	Данные, следующие за ключевым словом `onbranch` и двоеточием, интерпретируются как шаблон со стандартными wildcard-символами glob и двумя дополнительными, `**/` и `/**`, которые могут соответствовать нескольким компонентам пути. Если мы находимся в рабочей копии, где имя ветки, которая в данный момент переключена, соответствует шаблону, условие включения выполнено.
+
Если шаблон заканчивается на `/`, автоматически добавляется `**`. Например, шаблон `foo/` становится `foo/**`. Другими словами, он соответствует всем веткам, которые начинаются с `foo/`. Это полезно, если ваши ветки организованы иерархически, и вы хотите применить конфигурацию ко всем веткам в этой иерархии.

`hasconfig:remote.*.url`::
	Данные, следующие за этим ключевым словом и двоеточием, интерпретируются как шаблон со стандартными wildcard-символами glob и двумя дополнительными, `**/` и `/**`, которые могут соответствовать нескольким компонентам. При первом обнаружении этого ключевого слова остальная часть файлов конфигурации будет просканирована на наличие внешних URL-адресов (без применения каких-либо значений). Если существует хотя бы один внешний URL-адрес, соответствующий этому шаблону, условие включения выполнено.
+
Файлы, включённые этой опцией (прямо или косвенно), не могут содержать внешние URL-адреса.
+
Обратите внимание, что в отличие от других условий includeIf, разрешение этого условия зависит от информации, которая ещё неизвестна на момент чтения условия. Типичный вариант использования — эта опция присутствует в конфигурации системного или глобального уровня, а внешний URL-адрес находится в конфигурации локального уровня; отсюда необходимость сканирования вперёд при разрешении этого условия. Чтобы избежать проблемы курицы и яйца, при которой потенциально включаемые файлы могут влиять на то, будут ли такие файлы включены, Git разрывает цикл, запрещая этим файлам влиять на разрешение этих условий (таким образом, запрещая им объявлять внешние URL-адреса).
+
Что касается наименования этого ключевого слова, оно предназначено для прямой совместимости со схемой именования, которая поддерживает больше условий включения на основе переменных, но в настоящее время Git поддерживает только точно описанное выше ключевое слово.

Ещё несколько замечаний о сопоставлении с помощью `gitdir` и `gitdir/i`:

 * Символические ссылки в `$GIT_DIR` не разрешаются перед сопоставлением.

 * Как версия пути с символической ссылкой, так и версия realpath будут сопоставлены вне `$GIT_DIR`. Например, если ~/git является символической ссылкой на /mnt/storage/git, то и `gitdir:~/git`, и `gitdir:/mnt/storage/git` будут соответствовать.
+
Это было не так в первоначальном выпуске этой функции в v2.13.0, который соответствовал только версии realpath. Конфигурация, которая хочет быть совместимой с первоначальным выпуском этой функции, должна указывать только версию realpath или обе версии.

 * Обратите внимание, что «../» не является специальным и будет сопоставляться буквально, что вряд ли вам нужно.

Пример
~~~~~~

----
# Основные переменные
[core]
	; Не доверять режимам файлов
	filemode = false

# Наш алгоритм сравнения
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

[branch "devel"]
	remote = origin
	merge = refs/heads/devel

# Настройки прокси
[core]
	gitProxy="ssh" for "kernel.org"
	gitProxy=default-proxy ; для остальных

[include]
	path = /path/to/foo.inc ; включить по абсолютному пути
	path = foo.inc ; найти «foo.inc» относительно текущего файла
	path = ~/foo.inc ; найти «foo.inc» в вашем каталоге `$HOME`

; включить, если $GIT_DIR — это /path/to/foo/.git
[includeIf "gitdir:/path/to/foo/.git"]
	path = /path/to/foo.inc

; подключить для всех репозиториев внутри /path/to/group
[includeIf "gitdir:/path/to/group/"]
	path = /path/to/foo.inc

; подключить для всех репозиториев внутри $HOME/to/group
[includeIf "gitdir:~/to/group/"]
	path = /path/to/foo.inc

; относительные пути всегда отсчитываются от подключающего
; файла (если условие истинно); их расположение не
; зависит от условия
[includeIf "gitdir:/path/to/group/"]
	path = foo.inc

; подключить только если мы находимся в рабочем дереве, где
; в данный момент извлечена ветка foo-branch
[includeIf "onbranch:foo-branch"]
	path = foo.inc

; подключить только если существует удалённый репозиторий с данным URL (примечание:
; такой URL может быть указан позже в этом файле или в файле,
; прочитанном после этого, как показано в примере)
[includeIf "hasconfig:remote.*.url:https://example.com/**"]
	path = foo.inc
[remote "origin"]
	url = https://example.com/git
----

Значения
~~~~~~~~

Значения многих переменных трактуются как простые строки, но есть переменные, принимающие значения определённых типов, и существуют правила их записи.

логический::

       Когда говорится, что переменная принимает логическое значение, допускаются многие синонимы для 'true' и 'false'; все они нечувствительны к регистру.

	правда;; Литералы для логического значения «истина»: `yes`, `on`, `true` и `1`. Также переменная, определённая без `= <значение>`, считается истинной.

	ложь;; Литералы для логического значения «ложь»: `no`, `off`, `false`, `0` и пустая строка.
+
При преобразовании значения в каноническую форму с помощью спецификатора типа `--type=bool` команда 'git config' гарантирует, что вывод будет "true" или "false" (в нижнем регистре).

целое число::
       Значение для многих переменных, указывающих различные размеры, может иметь суффикс `k`, `M`,... означающий "умножить число на 1024", "на 1024x1024" и т.д.

color::
       Значение для переменной, принимающей цвет, — это список цветов (не более двух, один для переднего плана и один для фона) и атрибутов (сколько угодно), разделённых пробелами.
+
Основные принимаемые цвета: `normal`, `black`, `red`, `green`, `yellow`, `blue`, `magenta`, `cyan`, `white` и `default`. Первый указанный цвет — передний план; второй — фон. У всех основных цветов, кроме `normal` и `default`, есть яркий вариант, который можно указать, добавив префикс `bright`, например `brightred`.
+
Цвет `normal` не изменяет цвет. Он эквивалентен пустой строке, но может использоваться в качестве цвета переднего плана при указании только фонового цвета (например, "normal red").
+
Цвет `default` явно сбрасывает цвет к стандартному для терминала, например, чтобы указать очищенный фон. Хотя это зависит от терминала, обычно это не то же самое, что установка "white black".
+
Цвета также могут быть заданы числами от 0 до 255; это использует режим ANSI 256-цветов (но учтите, что не все терминалы могут его поддерживать). Если ваш терминал поддерживает, вы также можете указать 24-битные значения RGB в шестнадцатеричном виде, например `#ff0ab3`, или 12-битные значения RGB вроде `#f1b`, что эквивалентно 24-битному цвету `#ff11bb`.
+
Принимаемые атрибуты: `bold` (жирный), `dim` (тусклый), `ul` (подчёркивание), `blink` (мигание), `reverse` (инверсия), `italic` (курсив) и `strike` (зачёркивание). Позиция атрибутов относительно цветов (до, после или между) не имеет значения. Конкретные атрибуты можно отключить, добавив префикс `no` или `no-` (например, `noreverse`, `no-ul` и т.д.).
+
Псевдоатрибут `reset` сбрасывает все цвета и атрибуты перед применением указанной раскраски. Например, `reset green` приведёт к зелёному переднему плану и стандартному фону без каких-либо активных атрибутов.
+
Пустая цветовая строка не даёт никакого цветового эффекта. Это можно использовать, чтобы избежать раскраски определённых элементов, не отключая цвета полностью.
+
Для предопределённых цветовых слотов Git атрибуты должны сбрасываться в начале каждого элемента в цветном выводе. Поэтому установка `color.decorate.branch` в `black` окрасит имя ветки в простой `black`, даже если предыдущий элемент на той же строке вывода (например, открывающая скобка перед списком имён веток в выводе `log --decorate`) настроен на окраску с атрибутом `bold` или другим. Однако пользовательские форматы журнала могут использовать более сложную и слоистую раскраску, и там могут пригодиться отрицательные формы атрибутов.

pathname::
	Переменной, принимающей путь в качестве значения, можно передать строку, начинающуюся с "`~/`" или "`~user/`", и для такой строки выполняется обычное тильда-раскрытие: `~/` раскрывается в значение `$HOME`, а `~user/` — в домашний каталог указанного пользователя.
+
Если путь начинается с `%(prefix)/`, оставшаяся часть интерпретируется как путь, относительный к "префиксу времени выполнения" Git, т.е. относительно места, где установлен сам Git. Например, `%(prefix)/bin/` ссылается на каталог, в котором находится исполняемый файл Git. Если Git был собран без поддержки префикса времени выполнения, будет подставлен встроенный префикс. В маловероятном случае, когда нужно указать буквальный путь, который _не_ должен раскрываться, его нужно предварить `./`, например: `./%(prefix)/bin`.
+
Если путь предварен `:(optional)`, конфигурационная переменная трактуется как несуществующая, если указанный путь не существует.

Переменные
~~~~~~~~~~

Обратите внимание, что этот список не является исчерпывающим и не обязательно полным. Для переменных, специфичных для команд, вы найдёте более подробное описание в соответствующей странице руководства.

Другие инструменты, связанные с Git, могут и используют свои собственные переменные. При создании новых переменных для использования в своём инструменте убедитесь, что их имена не конфликтуют с теми, которые используются самим Git и другими популярными инструментами, и опишите их в своей документации.

include::config/add.adoc[]

include::config/advice.adoc[]

include::config/alias.adoc[]

include::config/am.adoc[]

include::config/apply.adoc[]

include::config/attr.adoc[]

include::config/bitmap-pseudo-merge.adoc[]

include::config/blame.adoc[]

include::config/branch.adoc[]

include::config/browser.adoc[]

include::config/bundle.adoc[]

include::config/checkout.adoc[]

include::config/clean.adoc[]

include::config/clone.adoc[]

include::config/color.adoc[]

include::config/column.adoc[]

include::config/commit.adoc[]

include::config/commitgraph.adoc[]

include::config/completion.adoc[]

include::config/core.adoc[]

include::config/credential.adoc[]

include::config/diff.adoc[]

include::config/difftool.adoc[]

include::config/extensions.adoc[]

include::config/fastimport.adoc[]

include::config/feature.adoc[]

include::config/fetch.adoc[]

include::config/filter.adoc[]

include::config/format.adoc[]

include::config/fsck.adoc[]

include::config/fsmonitor--daemon.adoc[]

include::config/gc.adoc[]

include::config/gitcvs.adoc[]

include::config/gitweb.adoc[]

include::config/gpg.adoc[]

include::config/grep.adoc[]

include::config/gui.adoc[]

include::config/guitool.adoc[]

include::config/help.adoc[]

include::config/http.adoc[]

include::config/i18n.adoc[]

include::config/imap.adoc[]

include::config/includeif.adoc[]

include::config/index.adoc[]

include::config/init.adoc[]

include::config/instaweb.adoc[]

include::config/interactive.adoc[]

include::config/log.adoc[]

include::config/lsrefs.adoc[]

include::config/mailinfo.adoc[]

include::config/mailmap.adoc[]

include::config/maintenance.adoc[]

include::config/man.adoc[]

include::config/merge.adoc[]

include::config/mergetool.adoc[]

include::config/notes.adoc[]

include::config/pack.adoc[]

include::config/pager.adoc[]

include::config/pretty.adoc[]

include::config/promisor.adoc[]

include::config/protocol.adoc[]

include::config/pull.adoc[]

include::config/push.adoc[]

include::config/rebase.adoc[]

include::config/receive.adoc[]

include::config/reftable.adoc[]

include::config/remote.adoc[]

include::config/remotes.adoc[]

include::config/repack.adoc[]

include::config/rerere.adoc[]

include::config/revert.adoc[]

include::config/safe.adoc[]

include::config/sendemail.adoc[]

include::config/sequencer.adoc[]

include::config/showbranch.adoc[]

include::config/sparse.adoc[]

include::config/splitindex.adoc[]

include::config/ssh.adoc[]

include::config/stash.adoc[]

include::config/status.adoc[]

include::config/submodule.adoc[]

include::config/tag.adoc[]

include::config/tar.adoc[]

include::config/trace2.adoc[]

include::config/trailer.adoc[]

include::config/transfer.adoc[]

include::config/uploadarchive.adoc[]

include::config/uploadpack.adoc[]

include::config/url.adoc[]

include::config/user.adoc[]

include::config/versionsort.adoc[]

include::config/web.adoc[]

include::config/worktree.adoc[]
