Сырой формат вывода
-------------------

Сырой формат вывода команд `git-diff-index`, `git-diff-tree`, `git-diff-files` и `git diff --raw` очень похож.

Все эти команды сравнивают два набора объектов, но то, что именно они сравнивают, отличается:

`git-diff-index <указатель-дерева>`::
	cравнивает _<указатель-дерева>_ и файлы в файловой системе.

`git-diff-index --cached <указатель-дерева>`::
	сравнивает содержимое файлов по _<указателю-дерева>_ и в индексе.

`git-diff-tree [-r] <указатель-дерева-1> <указатель-дерева-2> [<шаблон>...]`::
        сравнивает деревья, на которые указывают два аргумента.

`git-diff-files [<шаблон>...]`::
        сравнивает индекс и файлы в файловой системе.

Команда `git-diff-tree` начинает свой вывод с печати хеша того, что сравнивается. После чего она как и все остальные команды выводят информацию об изменённых файлах: по одной строке на файл.

Строки вывода выглядят следующим образом:

------------------------------------------------
изменения           :100644 100644 bcd1234 0123456 M файл0
копирование-правка  :100644 100644 abcd123 1234567 C68 файл1 файл2
переимещение-правка :100644 100644 abcd123 1234567 R86 файл1 файл3
создание            :000000 100644 0000000 1234567 A файл4
удаление            :100644 000000 1234567 0000000 D файл5
не-слитый           :000000 000000 0000000 0000000 U файл6
------------------------------------------------

Где, слева направо идут:

. двоеточие (`:`).
. режим доступа «исходного» состояния; 000000 при создании файла или когда он не слит.
. пробел.
. режим доступа «целевого» состояния; 000000 при удалении файла или когда он не слит.
. пробел.
. SHA1 для «исходного» состояния; 0\{40\} при создании файла или когда он не слит.
. пробел.
. SHA1 для «целевого» состояния; 0\{40\} при удалении файла, когда он не слит или когда рабочая копия не синхронизирована с индексом.
. пробел.
. статус за которым может следовать «рейтинг схожести» («score»).
. табуляция или NUL-символ (с параметром `-z`).
. «исходный» путь
. табуляция или NUL-символ (с параметром `-z`); только для статусов C и R.
. «целевой» путь; только для статусов C и R.
. символ LF или NUL (с параметром `-z`), который завершает запись.

Возможные обозначения для статуса:

- `A`: добавление файла (addition)
- `C`: копирование файла в новый (copy)
- `D': удаление файла (deletion)
- `M': изменение содержимого или режима доступа к файлу (modification)
- `R': переименование файла (renaming)
- `T`: изменение типа файла: обычный файл, символическая ссылка или подмодуль (type)
- `U`: файл не слит: вы должны будете завершить слияние, прежде чем будет возможно закоммитить файл (unmerged)
- `X`: «неизвестный» тип изменения (вероятно это ошибка, пожалуйста, сообщите о ней)

Статусы `C` и `R` всегда сопровождаются рейтингом схожести (обозначающим процент сходства между исходным и целевым состоянием при перемещении или копировании). Статус `M` также может сопровождаться рейтингом (обозначающим процент различий) для изменений файла.

Если файл в файловой системе ещё не синхронизирован с индексом, то SHA1 для «целевого» состояния будет отображается как строка из нулей.

Пример:

------------------------------------------------
:100644 100644 5be4a4a 0000000 M файл.c
------------------------------------------------

Без параметра `-z` пути с «необычными» символами берутся в кавычки, как это описано для переменной конфигурации `core.quotePath` (см. linkgit:git-config[1]). С параметром `-z` имя файла выводится без изменений, а строка завершается байтом NUL.

Формат списков изменений для слияний
------------------------------------

Команды `git-diff-tree`, `git-diff-files` и `git-diff --raw` принимают параметры `-c` или `--cc`, которые позволяют выводить списки изменений также и для коммитов слияний. Вывод отличается от описанного выше формата:

. для каждого родителя добавляется дополнительное двоеточие
. добавляются дополнительные режимы и SHA1 для «исходных» состояний
. статус представляет собой строку из символов статусов для каждого родителя
. нет (необязательного) значения «рейтинга схожести» («score»)
. несколько путей файлов, разделённых табуляциями

Для параметров `-c` и `--cc` показываются только целевой или конечный путь к файлу, даже если файл был переименован в одном из предков. С `--combined-all-paths` будут также выводиться пути в каждом из родителей, за которыми последует путь в коммите слияния.

Примеры для `-c` и `--cc` без `--combined-all-paths`:
------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	phooey.c
------------------------------------------------

Примеры, когда к `-c` или `--cc` добавляется `--combined-all-paths`:

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c	desc.c	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	foo.sh	bar.sh	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	fooey.c	fuey.c	phooey.c
------------------------------------------------

Обратите внимание, что в «комбинированном» формате в списке изменений перечисляются только те файлы, которые были изменены относительно всех родителей.


include::diff-generate-patch.adoc[]


Другие форматы списка изменений
-------------------------------

Параметр `--summary` выводит, какие файлы были созданы, удалены, переименованы и скопированы. А параметром `--stat` добавляет к выходу графики `diffstat`(1). Эти параметры могут использоваться совместно с другими, такими как `-p`, а их вывод предназначен для чтения человеком.

Когда отображаются изменения, связанное с переименованием или копированием, вывод `--stat` компактно форматирует пути, объединяя их общие префиксы и суффиксы. Например, если файл `arch/i386/Makefile` был перемещён в `arch/x86/Makefile` с изменением 4-х строк, это будет отображено как:

------------------------------------
arch/{i386 => x86}/Makefile    |   4 +--
------------------------------------

Параметр `--numstat` также выдаёт информацию в виде `diffstat`(1), но его вывод больше подходит для машинного чтения. Запись в выводе `--numstat` выглядит как:

----------------------------------------
1	2	README
3	1	arch/{i386 => x86}/Makefile
----------------------------------------

Где, слева направо идут:

. rоличество добавленных строк;
. табуляция;
. количество удалённых строк;
. табуляция;
. путь (возможно с информацией о переименовании/копировании);
. символ перехода на новую строку.

Если также используется параметр `-z`, то вывод форматируется следующим образом:

----------------------------------------
1	2	README NUL
3	1	NUL arch/i386/Makefile NUL arch/x86/Makefile NUL
----------------------------------------

Где:

. rоличество добавленных строк;
. табуляция;
. количество удалённых строк;
. табуляция;
. NUL-символ (только для переименований/копирований);
. путь исходного состояния;
. NUL-символ (только для переименований/копирований);
. пути целевого состояния (только для переименований/копирований);
. NUL-символ.

Дополнительный NUL-символ перед именем пути исходного файла в случае переименования позволяет сценариям, которые читают этот вывод, определить, содержит ли текущая запись только один путь или является записью переименования/копирования (с двумя путями), не прибегая к упреждающему чтению. После чтения количества добавленных и удалённых строк чтение до NUL-символа в обычной ситуации выдаёт путь к файлу, но если он оказывается пустым, то это означает, что в записи есть два пути.
