[[generate_patch_text_with_p]]
Создание патчей с помощью -p
----------------------------

Запуск команд linkgit:git-diff[1], linkgit:git-log[1], linkgit:git-show[1], linkgit:git-diff-index[1], linkgit:git-diff-tree[1], или linkgit:git-diff-files[1] с параметром `-p` выдаёт текст патча. Вы можете изменить некоторые аспекты этого создаваемого текста с помощью переменных окружения `GIT_EXTERNAL_DIFF` и `GIT_DIFF_OPTS` (см. linkgit:git[1]), а также атрибута `diff` (см. linkgit:gitattributes[5]).

Тот текст, которые получается на выходе при запуске с параметром `-p`, немного отличается от традиционного формата списка изменений:

1.   В начале идёт заголовок «git diff», который выглядит следующим образом:

       diff --git a/файл1 b/файл2
+
Имена файлов `a/` и `b/` одинаковы, если изменения не связаны с переименованием или копированием. В частности, даже для создания или удаления вместо имён файлов `a/` или `b/` _не_ используется `/dev/null` .
+
Когда же изменения являются переименование или копирование, `file1` и `file2` отображают имена исходного файла и того, который получается в результате переименования/копирования, соответственно.

2.   Далее следуют одна или несколько строк расширенного заголовка:
+
[synopsis]
old mode <режим>
new mode <режим>
deleted file mode <режим>
new file mode <режим>
copy from <путь>
copy to <путь>
rename from <путь>
rename to <путь>
similarity index <число>
dissimilarity index <число>
index <хеш>..<хеш> <режим>
+
Режимы файлов _`<режим>`_ печатаются как 6-значные восьмеричные числа, включающие тип файла и биты разрешений.
+
Пути в расширенных заголовках не включают префиксы `a/` и `b/`.
+
Индекс сходства — это процент не изменённых строк, а индекс различия — процент изменённых. Он представляет собой округлённое вниз целое число, за которым следует знак процента. Индекс сходства в 100% зарезервирован для двух абсолютно одинаковых файлов, а 100% различий означает, что ни одна строка из старого файла не вошла в новый.
+
Строка индекса включает имена бинарных объектов до и после изменения. Строка _<режима>_ добавляется, если режим файла не был изменён; в противном случае старый и новый режимы приводятся в отдельных строках.

3.  Путей с «необычными» символами берутся в кавычки, как это описано для переменной конфигурации `core.quotePath` (см. linkgit:git-config[1]).

4.  Все файлы `файл1` в выводе относятся к файлам до коммита, а все файлы `файл2` — к файлам после коммита. Неправильно было бы применять каждое изменение к каждому файлу последовательно. Например, следующий патч поменяет местами `a` и `b`:

      diff --git a/a b/b
      rename from a
      rename to b
      diff --git a/b b/a
      rename from b
      rename to a

5.  Заголовки отдельных блоков изменений упоминают имя функции, к которой применяется этот блок. См. подробности, о том, как это можно адаптировать для конкретного языка программирования в разделе «Определение пользовательского заголовка блока» в linkgit:gitattributes[5].


Комбинированный формат списков изменений
----------------------------------------

Любая команда, выводящая список изменений, принимает параметры `-c` или `--cc`, которые приводят к созданию списка изменений для слияний в «комбинированном» формате («combined diff»). Это формат по умолчанию при выводе слияний с помощью linkgit:git-diff[1] или linkgit:git-show[1]. Также обратите внимание, что для того, чтобы заставить эти команды выводить списки изменений в каком-либо другом формате, можно использовать параметр `--diff-merges` с соответствующими аргументами.

Комбинированный формат списков изменений выглядит следующим образом:

------------
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
------------

1.   В начале идёт заголовок «git diff», который выглядит следующим образом (при использовании параметра `-c`):

       diff --combined файл
+
или следующим (при использовании параметра `--cc`):

       diff --cc файл

2.   Далее следуют одна или несколько строк расширенного заголовка (в данном примере показано слияние с двумя родителями):
+
[synopsis]
index <хеш>,<хеш>..<хеш>
mode <режим>,<режим>..<режим>
new file mode <режим>
deleted file mode <режим>,<режим>
+
Строка `mode <режим>,<режим>..<режим>` присутствует только если хотя бы один из <режимов> отличается от остальных. Расширенные заголовки с информацией о найденных перемещениях содержимого (обнаруженных переименованиях и копированиях) предназначены для работы только со списком изменений строго двух _<указателей-дерева>_ и не используются в комбинированном формате.

3.   Далее следуют две строки заголовка, с указанием исходного и целевого файлов (из-файла/в-файл):

       --- a/файл
       +++ b/файл
+
Аналогично тому как это делается и в традиционном формате объединённого («unified») списка изменений, `/dev/null` используется для обозначения созданных или удалённых файлов.
+
Однако, если задан параметр `--combined-all-paths`, то вместо этих двух строк заголовка с из-файла/в-файл, вы получите расширенный заголовок из N+1 строки, где N — это количество родителей в коммите слияния:

       --- a/файл
       --- a/файл
       --- a/файл
       +++ b/файл
+
Этот расширенный формат может быть полезен, если у вас включено обнаружение переименований и копирований, так как это позволяет увидеть, как назывался файл в разных родителях до слияния.

4.   Формат заголовка блока списка изменений был специально модифицирован, чтобы предотвратить случайное применение его с помощью `patch -p1`. Комбинированный формат списков изменений был создан для рецензирования изменений в коммитах слияния и не предназначен для прямого применения в виде патчей. Эти модификации аналогичны тем, что были сделаны в расширенном заголовке `index`:

       @@@ <исходный-диапазон> <исходный-диапазон> <результирующий-диапазон> @@@
+
В заголовке блока для комбинированного формата (количество родителей + 1) символов `@`.

В отличие традиционном объединённого («unified») формата списка изменений, который показывает разницу между двумя файлами А и Б с одной колонкой, в которой содержится или `-` (минус — строка есть в А, но удалена в Б), или `+` (плюс — нет в А, но добавлена в Б), или `" "` (пробел — без изменений), этот формат сравнивает два или более файла файл1, файл2,... с одним файлом Х и показывает, чем Х отличается от каждого из файлов файлN. Так что по одному столбцу для каждого из файлов файлN добавляется в начало строк вывода, чтобы дать понять, как строки в Х отличается от строк в этих файлах.

Символ `-` в столбце N означает, что строка была в файле файлN, но ей нет в итоговом документе. Символ `+` в столбце N — что строка есть в итоговом документе, но её нет в файле файлN (т.е. с точки зрения этого родителя строка была добавлена).

В примере выше сигнатура функции была изменена в обоих файлах (следовательно, в примере два удаления из каждого из файлов файл1 и файл2, кроме того `++` означает что была добавлена одна строка, которая не появляется ни в файл1, ни в файл1). Также из файла файл1 были взяты восемь других строк, которых не было в файле файл2 (так что они помечены плюсом `+`).

Когда этот формат выводится командой `git diff-tree -c`, она сравнивает родителей коммита слияния с результатом слияния (т.е. файл1..файлN — это родители). А в выводе команды `git diff-files -c` сравниваются файлы в двух родителях неразрешённого слияния с файлом в рабочем каталоге (т.е. файл1 — это индекс 2, или «наша версия», файл2 — это индекс 3, или «их версия»).
