git-var(1)
==========

НАЗВАНИЕ
--------
git-var — Показать логическую переменную Git


ОБЗОР
-----
[synopsis]
git var (-l | <переменная>)

ОПИСАНИЕ
--------
Выводит логическую переменную Git. Завершается с кодом 1, если переменная не имеет значения.

ПАРАМЕТРЫ
---------
`-l`::
	Отображает логические переменные. Кроме того, также перечисляются все переменные из файла конфигурации Git .git/config. (Однако, функция вывода списка переменных конфигурации устарела в пользу `git config -l`.)

ПРИМЕРЫ
-------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


ПЕРЕМЕННЫЕ
----------
`GIT_AUTHOR_IDENT`::
    Автор фрагмента кода.

`GIT_COMMITTER_IDENT`::
    Лицо, поместившее фрагмент кода в Git.

`GIT_EDITOR`::
    Текстовый редактор для использования командами Git. Значение должно интерпретироваться оболочкой при его использовании. Примеры: `~/bin/vi`, `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe" --nofork`. Порядок предпочтения: `$GIT_EDITOR`, затем значение конфигурации `core.editor`, затем `$VISUAL`, затем `$EDITOR`, и затем значение по умолчанию, выбранное во время компиляции, обычно это 'vi'.
ifdef::git-default-editor[]
    Используемая вами сборка выбрала '{git-default-editor}' в качестве редактора по умолчанию.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    Текстовый редактор, используемый для редактирования файла 'todo' во время выполнения `git rebase -i`. Как и `GIT_EDITOR`, значение должно интерпретироваться оболочкой при его использовании. Порядок предпочтения: `$GIT_SEQUENCE_EDITOR`, затем значение конфигурации `sequence.editor`, и затем значение `git var GIT_EDITOR`.

`GIT_PAGER`::
    Средство просмотра текста для использования командами Git (например, 'less'). Значение должно интерпретироваться оболочкой. Порядок предпочтения: `$GIT_PAGER`, затем значение конфигурации `core.pager`, затем `$PAGER`, и затем значение по умолчанию, выбранное во время компиляции (обычно `less`).
ifdef::git-default-pager[]
    Используемая вами сборка выбрала '{git-default-pager}' в качестве средства просмотра по умолчанию.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    Имя первой ветки, создаваемой в только что инициализированных репозиториях.

`GIT_SHELL_PATH`::
    Путь к исполняемому файлу, предоставляющему оболочку POSIX для команд, которые используют оболочку.

`GIT_ATTR_SYSTEM`::
    Путь к системному файлу linkgit:gitattributes[5], если он включён.

`GIT_ATTR_GLOBAL`::
    Путь к глобальному (для каждого пользователя) файлу linkgit:gitattributes[5].

`GIT_CONFIG_SYSTEM`::
    Путь к системному конфигурационному файлу, если он включён.

`GIT_CONFIG_GLOBAL`::
    Путь к глобальным (для каждого пользователя) конфигурационным файлам, если они есть.

Большинство значений путей содержат только одно значение. Однако некоторые могут содержать несколько значений, разделённых символами новой строки, и перечисленных в порядке от наивысшего к наименьшему приоритету. Вызывающие стороны должны быть готовы к тому, что любое такое значение пути может содержать несколько элементов.

Обратите внимание, что пути выводятся, даже если они не существуют, но не выводятся, если они отключены другими переменными окружения.

СМ. ТАКЖЕ
---------
linkgit:git-commit-tree[1] linkgit:git-tag[1] linkgit:git-config[1]

GIT
---
Является частью пакета linkgit:git[1]
