git-stripspace(1)
=================

НАЗВАНИЕ
--------
git-stripspace — удаление ненужных пробелов


ОБЗОР
-----
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

ОПИСАНИЕ
--------

Читает текст, такой как сообщения коммитов, заметки, метки и описания веток, из стандартного ввода и очищает его в соответствии с методом, используемым Git.

Без аргументов это сделает следующее:

- удалить конечные пробельные символы из всех строк
- сжать несколько последовательных пустых строк в одну пустую строку
- удалить пустые строки из начала и конца ввода
- добавить недостающий '\n' в последнюю строку при необходимости.

В случае, когда входные данные полностью состоят из символов пробелов, вывод производиться не будет.

*ПРИМЕЧАНИЕ*: Это предназначено для очистки метаданных. Для исправления пробелов в патчах или файлах в репозитории предпочтительнее использовать режим `--whitespace=fix` команды linkgit:git-apply[1].

ПАРАМЕТРЫ
---------
-s::
--strip-comments::
	Пропустить и удалить все строки, начинающиеся с символа комментария (`core.commentChar`, по умолчанию `#`).

-c::
--comment-lines::
	Добавляет символ комментария и пробел в начало каждой строки. Строки автоматически завершаются символом новой строки. В пустых строках добавляется только символ комментария.

ПРИМЕРЫ
-------

Для следующих зашумлённых входных данных, где '$' обозначает конец строки:

---------
|Краткое введение   $
|   $
|$
|Новый абзац$
|# с закомментированной строкой    $
|объясняет много всего.$
|$
|# Старый абзац, также закомментированный. $
|      $
|Конец.$
|  $
---------

Используйте 'git stripspace' без аргументов, чтобы получить:

---------
|Краткое введение$
|$
|Новый абзац$
|# с закомментированной строкой$
|объясняет много всего.$
|$
|# Старый абзац, также закомментированный.$
|$
|Конец.$
---------

Используйте 'git stripspace --strip-comments', чтобы получить:

---------
|Краткое введение$
|$
|Новый абзац$
|объясняет много всего.$
|$
|Конец.$
---------

GIT
---
Является частью пакета linkgit:git[1]
