git-mailsplit(1)
================

НАЗВАНИЕ
--------
git-mailsplit — простая программа разделения почтовых ящиков UNIX mbox

ОБЗОР
-----
[verse]
'git mailsplit' [-b] [-f<чч>] [-d<точность>] [--keep-cr] [--mboxrd]
		-o<каталог> [--] [(<mbox>|<Maildir>)...]

ОПИСАНИЕ
--------
Разделяет файл mbox или Maildir на список файлов: "0001" "0002" .. в указанном каталоге, чтобы вы могли обработать их дальше оттуда.

IMPORTANT: Разделение Maildir полагается на то, что имена файлов сортируются для вывода патчей в правильном порядке.

ПАРАМЕТРЫ
---------
<mbox>::
	Файл mbox для разделения. Если не указан, mbox читается из стандартного ввода.

<Maildir>::
	Корень Maildir для разделения. Этот каталог должен содержать подкаталоги cur, tmp и new.

-o<directory>::
	Каталог, в котором размещаются отдельные сообщения.

-b::
	Если какой-либо файл не начинается со строки From, считать его одним почтовым сообщением вместо сигнализации об ошибке.

-d<prec>::
	Вместо 4 цифр по умолчанию с ведущими нулями для создаваемых имён файлов можно указать другую точность.

-f<nn>::
	Пропустить первые <чч> чисел, например, если указано -f3, начать нумерацию с 0004.

--keep-cr::
	Не удалять `\r` из строк, заканчивающихся на `\r\n`.

--mboxrd::
	Входные данные имеют формат "mboxrd", и экранирование строк "^>+From " отменяется.

GIT
---
Является частью пакета linkgit:git[1]
