git-mktree(1)
=============

НАЗВАНИЕ
--------
git-mktree - Построение объекта дерева из текста в формате ls-tree


ОБЗОР
-----
[verse]
'git mktree' [-z] [--missing] [--batch]

ОПИСАНИЕ
--------
Читает стандартный ввод в нерекурсивном формате вывода `ls-tree` и создаёт объекты-деревья. Порядок записей деревьев нормализуется самой командой `mktree`, поэтому предварительная сортировка входных данных не требуется. Имя созданного объекта-дерева выводится на стандартный вывод.

ПАРАМЕТРЫ
---------
-z::
	Читать записи разделённые NUL-символами (как в выводе `ls-tree -z`), вместо символов конца строки.

--missing::
	Разрешить отсутствующие объекты. По умолчанию (без этого параметра) проверяется, что хеш каждой записи дерева идентифицирует существующий объект. Этот параметр не влияет на обработку записей gitlink (также известных как «подмодули»), которые могут отсутствовать в любом случае.

--batch::
	Позволяет создавать более одного объекта-дерева перед выходом. Каждое дерево во вводе отделяется от соседних одной пустой строкой. Последняя пустая строка — опциональна. Примечание: если используется параметр `-z`, строки завершаются NUL-символом.

GIT
---
Является частью пакета linkgit:git[1]
