git-diff-files(1)
=================

НАЗВАНИЕ
--------
git-diff-files - Сравнить файлы в рабочем каталоге с индексом


ОБЗОР
-----
[verse]
'git diff-files' [-q] [-0|-1|-2|-3|-c|--cc] [<общие-параметры-diff>] [<путь>...]

ОПИСАНИЕ
--------
Сравнивает файлы в рабочем каталоге и индексе. Когда заданы пути, сравниваются только указанные пути. В противном случае сравниваются все записи в индексе. Формат вывода такой же, как и у `git diff-index` и `git diff-tree`.

ПАРАМЕТРЫ
---------
include::diff-options.adoc[]

-1 --base::
-2 --ours::
-3 --theirs::
-0::
	Сравнить с «базовой» версией, «нашей веткой» или «их веткой» соответственно. При передаче этих параметров различия в уже слитых записях не выводятся.
+
По умолчанию производится сравнение с нашей веткой (`-2`) и c включением уже начисто разрешённых путей. Параметр `-0` может быть указан, чтобы опускать вывод списка изменений для не слитых записей и вместо этого просто выводить «Unmerged» («Не слит»).

-c::
--cc::
	Сравнивает индекс 2 (наша ветка), индекс 3 (их ветка) и файл в рабочем каталоге и выводит комбинированный список изменений, аналогично тому, как `diff-tree` с этими флагами отображает коммит слияния.

-q::
	Не выводить ошибки даже если заданы несуществующие файлы.


include::diff-format.adoc[]

GIT
---
Является частью пакета linkgit:git[1]
