git-commit-tree(1)
==================

НАЗВАНИЕ
--------
git-commit-tree — создать новый объект коммита


ОБЗОР
-----
[verse]
'git commit-tree' <дерево> [(-p <родитель>)...]
'git commit-tree' [(-p <родитель>)...] [-S[<id-ключа>]] [(-m <сообщение>)...]
		  [(-F <файл>)...] <дерево>


ОПИСАНИЕ
--------
Обычно это не то, что конечный пользователь хочет запускать напрямую. Вместо этого см. linkgit:git-commit[1].

Создаёт новый объект коммита на основе предоставленного объекта дерева и выводит id нового объекта коммита в stdout. Сообщение журнала читается из стандартного ввода, если не указаны параметры `-m` или `-F`.

Параметры `-m` и `-F` могут быть указаны любое количество раз, в любом порядке. Сообщение журнала коммита будет составлено в том порядке, в котором указаны параметры.

Объект коммита может иметь любое количество родителей. Ровно с одним родителем это обычный коммит. Наличие более одного родителя делает коммит слиянием нескольких линий истории. Начальные (корневые) коммиты не имеют родителей.

В то время как дерево представляет определённое состояние каталога рабочего каталога, коммит представляет это состояние во "времени" и объясняет, как туда попасть.

Обычно коммит идентифицирует новое состояние "HEAD", и хотя Git не заботится о том, где вы сохраняете заметку об этом состоянии, на практике мы склонны просто записывать результат в файл, на который указывает `.git/HEAD`, чтобы мы всегда могли видеть, каким было последнее зафиксированное состояние.

ПАРАМЕТРЫ
---------
<tree>::
	Существующий объект дерева.

-p <родитель>::
	Каждый `-p` указывает id родительского объекта коммита.

-m <сообщение>::
	Абзац в сообщении журнала коммита. Это может быть указано более одного раза, и каждое <сообщение> становится отдельным абзацем.

-F <файл>::
	Прочитать сообщение журнала коммита из указанного файла. Используйте `-` для чтения из стандартного ввода. Это может быть указано более одного раза, и содержимое каждого файла становится отдельным абзацем.

-S[<id-ключа>]::
--gpg-sign[=<id-ключа>]::
--no-gpg-sign::
	Подписывать коммиты GPG. Аргумент `keyid` является необязательным и по умолчанию равен идентификатору коммиттера; если указан, он должен примыкать к параметру без пробела. `--no-gpg-sign` полезен для отмены параметра `--gpg-sign`, указанного ранее в командной строке.

Информация о коммите
--------------------

Коммит инкапсулирует:

- все id родительских объектов
- имя автора, адрес электронной почты и дата
- имя коммиттера, адрес электронной почты и время коммита.

Комментарий к коммиту читается из stdin. Если запись журнала изменений не предоставлена через перенаправление "<", 'git commit-tree' будет просто ждать, пока она не будет введена и не завершена с помощью ^D.

include::date-formats.adoc[]

Обсуждение
----------

include::i18n.adoc[]

ФАЙЛЫ
-----
/etc/mailname

СМ. ТАКЖЕ
---------
linkgit:git-write-tree[1] linkgit:git-commit[1]

GIT
---
Является частью пакета linkgit:git[1]
