git-mergetool{litdd}lib(1)
==========================

НАЗВАНИЕ
--------
git-mergetool--lib — общие скриплеты оболочки для инструментов слияния Git

ОБЗОР
-----
[verse]
'TOOL_MODE=(diff|merge) . "$(git --exec-path)/git-mergetool{litdd}lib"'

ОПИСАНИЕ
--------

Это не та команда, которая может представлять интерес для конечного пользователя. Никогда. Этот документ предназначен для людей, которые изучают и/или пишут новый сценарий, работающий с высокоуровневым «фарфоровым» программным интерфейсом Git.

Скриплет 'git-mergetool{litdd}lib' предназначен для включения (с помощью `.`) другими скриптами оболочки для настройки функций для работы с инструментами слияния Git.

Перед включением 'git-mergetool{litdd}lib' ваш сценарий должен установить `TOOL_MODE`, чтобы определить режим работы для перечисленных ниже функций. Допустимые значения: 'diff' и 'merge'.

ФУНКЦИИ
-------
get_merge_tool::
	Возвращает инструмент слияния. Код возврата равен 1, если был возвращён предполагаемый инструмент слияния, иначе 0. '$GIT_MERGETOOL_GUI' может быть установлен в 'true' для поиска соответствующего guitool.

get_merge_tool_cmd::
	Возвращает пользовательскую команду для инструмента слияния.

get_merge_tool_path::
	Возвращает пользовательский путь для инструмента слияния.

initialize_merge_tool::
	Вводит в область видимости функции, специфичные для инструмента слияния, чтобы их можно было использовать или переопределять.

run_merge_tool::
	Запускает инструмент слияния, используя имя инструмента и флаг true/false, указывающий, присутствует ли основа слияния. '$MERGED', '$LOCAL', '$REMOTE' и '$BASE' должны быть определены для использования инструментом слияния.

GIT
---
Является частью пакета linkgit:git[1]
