git-help(1)
===========

НАЗВАНИЕ
--------
git-help — Отображение справочной информации о Git

ОБЗОР
-----
[verse]
'git help' [-a|--all] [--[no-]verbose] [--[no-]external-commands] [--[no-]aliases]
'git help' [[-i|--info] [-m|--man] [-w|--web]] [<команда>|<документ>]
'git help' [-g|--guides]
'git help' [-c|--config]
'git help' [--user-interfaces]
'git help' [--developer-interfaces]

ОПИСАНИЕ
--------

Без параметров и без указания '<команда>' или '<документ>' в стандартный вывод выводится краткая сводка команды 'git' и список наиболее часто используемых команд Git.

Если указан параметр `--all` или `-a`, в стандартный вывод выводятся все доступные команды.

Если указан параметр `--guides` или `-g`, в стандартный вывод также выводится список руководств по концепциям Git.

Если указана команда или другая документация, будет вызвана соответствующая справочная страница. По умолчанию для этой цели используется программа 'man', но это может быть переопределено другими параметрами или переменными конфигурации.

Если указан псевдоним, git показывает определение псевдонима в стандартном выводе. Чтобы получить справочную страницу для команды, на которую указывает псевдоним, используйте `git <команда> --help`.

Обратите внимание, что `git --help ...` идентично `git help ...`, поскольку первое внутренне преобразуется во второе.

Чтобы отобразить справочную страницу linkgit:git[1], используйте `git help git`.

Эта страница может быть отображена с помощью 'git help help' или `git help --help`.

ПАРАМЕТРЫ
---------
-a::
--all::
	Вывести все доступные команды в стандартный вывод.

--no-external-commands::
	При использовании с `--all` исключить из списка внешние команды "git-*", найденные в `$PATH`.

--no-aliases::
	При использовании с `--all` исключить из списка настроенные псевдонимы.

--verbose::
	При использовании с `--all` выводить описание для всех распознанных команд. Это значение по умолчанию.

-c::
--config::
	Вывести список всех доступных переменных конфигурации. Это краткое изложение списка в linkgit:git-config[1].

-g::
--guides::
	Вывести список руководств по концепциям Git в стандартный вывод.

--user-interfaces::
	Вывести список документации по интерфейсам репозитория, команд и файлов в стандартный вывод.
+
Интерфейсы файлов внутри репозитория, такие как `.git/info/exclude`, документированы здесь (см. linkgit:gitrepository-layout[5]), а также конфигурация внутри дерева, такая как `.mailmap` (см. linkgit:gitmailmap[5]).
+
Этот раздел документации также охватывает общие или широко распространённые соглашения пользовательского интерфейса (например, linkgit:gitcli[7]) и псевдоконфигурацию, такую как файловый интерфейс `.git/hooks/*`, описанный в linkgit:githooks[5].

--developer-interfaces::
	Вывести список документации по файловым форматам, протоколам и другим интерфейсам разработчика в стандартный вывод.

-i::
--info::
	Отобразить справочную страницу для команды в формате 'info'. Для этой цели будет использована программа 'info'.

-m::
--man::
	Отобразить справочную страницу для команды в формате 'man'. Этот параметр может использоваться для переопределения значения, установленного в переменной конфигурации `help.format`.
+
По умолчанию для отображения справочной страницы будет использоваться программа 'man', но переменная конфигурации `man.viewer` может использоваться для выбора других программ отображения (см. ниже).

-w::
--web::
	Отобразить справочную страницу для команды в формате 'web' (HTML). Для этой цели будет использован веб-браузер.
+
Веб-браузер можно указать с помощью переменной конфигурации `help.browser` или `web.browser`, если первая не установлена. Если ни одна из этих переменных конфигурации не установлена, вспомогательный сценарий 'git web{litdd}browse' (вызываемый 'git help') выберет подходящее значение по умолчанию. Дополнительную информацию об этом см. в linkgit:git-web{litdd}browse[1].

ПЕРЕМЕННЫЕ КОНФИГУРАЦИИ
-----------------------

help.format
~~~~~~~~~~~

Если параметр командной строки не передан, будет проверена переменная конфигурации `help.format`. Для этой переменной поддерживаются следующие значения; они заставляют 'git help' вести себя как соответствующий параметр командной строки:

* "man" соответствует '-m|--man',
* "info" соответствует '-i|--info',
* "web" или "html" соответствуют '-w|--web'.

help.browser, web.browser и browser.<инструмент>.path
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`help.browser`, `web.browser` и `browser.<инструмент>.path` также будут проверены, если выбран формат 'web' (либо параметром командной строки, либо переменной конфигурации). См. '-w|--web' в разделе ПАРАМЕТРЫ выше и linkgit:git-web{litdd}browse[1].

man.viewer
~~~~~~~~~~

Переменная конфигурации `man.viewer` будет проверена, если выбран формат 'man'. В настоящее время поддерживаются следующие значения:

* "man": использовать программу 'man' как обычно,
* "woman": использовать 'emacsclient' для запуска режима "woman" в emacs (это работает только начиная с версий emacsclient 22),
* "konqueror": использовать 'kfmclient' для открытия справочной страницы в новой вкладке konqueror (см. «Примечание о konqueror» ниже).

Значения для других инструментов можно использовать, если существует соответствующая запись конфигурации `man.<инструмент>.cmd` (см. ниже).

Переменной конфигурации `man.viewer` может быть присвоено несколько значений. Соответствующие программы будут опробованы в порядке, указанном в файле конфигурации.

Например, такая конфигурация:

------------------------------------------------
	[man]
		viewer = konqueror
		viewer = woman
------------------------------------------------

сначала попробует использовать konqueror. Но это может не удаться (например, если DISPLAY не установлен), и в этом случае будет опробован режим woman из emacs.

Если всё не удаётся или если программа просмотра не настроена, будет опробована программа просмотра, указанная в переменной окружения `GIT_MAN_VIEWER`. Если и это не удаётся, в любом случае будет опробована программа 'man'.

man.<tool>.path
~~~~~~~~~~~~~~~

Вы можете явно указать полный путь к предпочитаемой программе просмотра справочных страниц, установив переменную конфигурации `man.<инструмент>.path`. Например, вы можете настроить абсолютный путь к konqueror, установив 'man.konqueror.path'. В противном случае 'git help' предполагает, что инструмент доступен в PATH.

man.<tool>.cmd
~~~~~~~~~~~~~~

Если программа просмотра справочных страниц, указанная переменными конфигурации `man.viewer`, не входит в число поддерживаемых, то будет выполнен поиск соответствующей переменной конфигурации `man.<инструмент>.cmd`. Если эта переменная существует, то указанный инструмент будет рассматриваться как пользовательская команда, и для её запуска будет использована команда оболочки eval, которой в качестве аргументов будет передана справочная страница.

Примечание о Konqueror
~~~~~~~~~~~~~~~~~~~~~~

Когда в переменной конфигурации `man.viewer` указан 'konqueror', мы запускаем 'kfmclient', чтобы попытаться открыть справочную страницу в уже открытом konqueror в новой вкладке, если это возможно.

Для единообразия мы также пробуем такой трюк, если 'man.konqueror.path' установлен во что-то вроде `A_PATH_TO/konqueror`. Это означает, что мы попытаемся запустить `A_PATH_TO/kfmclient` вместо него.

Если вы действительно хотите использовать 'konqueror', вы можете использовать что-то вроде следующего:

------------------------------------------------
	[man]
		viewer = konq

	[man "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

Примечание о git config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Обратите внимание, что все эти переменные конфигурации, вероятно, следует устанавливать с использованием флага `--global`, например, так:

------------------------------------------------
$ git config --global help.format web
$ git config --global web.browser firefox
------------------------------------------------

поскольку они, вероятно, более специфичны для пользователя, чем для репозитория. Дополнительную информацию об этом см. в linkgit:git-config[1].

GIT
---
Является частью пакета linkgit:git[1]
