git-diff(1)
===========

НАЗВАНИЕ
--------
git-diff - Вывод разницы между коммитами, коммитом и рабочим каталогом и так далее


ОБЗОР
-----
[synopsis]
git diff [<options>] [<commit>] [--] [<path>...]
git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]
git diff [<options>] [--merge-base] <commit> [<commit>...] <commit> [--] [<path>...]
git diff [<options>] <commit>...<commit> [--] [<path>...]
git diff [<options>] <blob> <blob>
git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]

ОПИСАНИЕ
--------
Вывод различий между рабочим каталогом и индексом или деревом коммита, различий между индексом и деревом коммита, различий между двумя деревьями коммитов, изменений, возникших в результате слияния, различий между двумя blob-объектами или различий между двумя файлами на диске.

`git diff [<параметры>] [--] [<путь>...]`::

	Эта форма команды используется для просмотра изменений, которые вы сделали, относительно индекса (т.е. относительно того, что проиндексировано и подготовлено для следующего коммита). Другими словами, те изменения, которые вы _могли бы_ сказать Git добавить в индекс, но ещё этого не сделали. Вы можете включить эти изменения в индекс, используя linkgit:git-add[1].

`git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]`::

	This form is to compare the given two paths on the filesystem. You can omit the `--no-index` option when running the command in a working tree controlled by Git and at least one of the paths points outside the working tree, or when running the command outside a working tree controlled by Git. This form implies `--exit-code`. If both paths point to directories, additional pathspecs may be provided. These will limit the files included in the difference. All such pathspecs must be relative as they apply to both sides of the diff.

`git diff [<параметры>] --cached [--merge-base] [<коммит>] [--] [<путь>...]`::

	Эта форма команды используется для просмотра изменений, которые вы подготовили для следующего коммита, относительно указанного _<коммита>_. Обычно интерес представляет сравнение этих изменений с последним коммитом, поэтому если вы не укажете _<коммит>_, по умолчанию будет использоваться `HEAD`. Если `HEAD` ещё не существует (например, в ветках, в которые только предстоит создать их первый коммит) и _<коммит>_ не указан, будут показаны все проиндексированные изменения. Параметр `--staged` является синонимом `--cached`.
+
Если указан параметр `--merge-base`, вместо непосредственно самого _<коммита>_ будет использоваться базовый коммит слияния _<коммита>_ и `HEAD`. Команда `git diff --cached --merge-base A` эквивалентна `git diff --cached $(git merge-base A HEAD)`.

`git diff [<параметры>] [--merge-base] <коммит> [--] [<путь>...]`::

	Эта форма команды используется для просмотра изменений в вашем рабочем каталоге относительно указанного _<коммита>_. Вы можете использовать `HEAD`, чтобы сравнить с последним коммитом, или имя другой ветки для сравнения с её верхушкой.
+
Если указан параметр `--merge-base`, вместо непосредственно самого _<коммита>_ будет использоваться базовый коммит слияния _<коммита>_ и `HEAD`. Команда `git diff --merge-base A` эквивалентна `git diff $(git merge-base A HEAD)`.

`git diff [<параметры>] [--merge-base] <коммит> <коммит> [--] [<путь>...]`::

	Эта форма команды используется для просмотра изменений между двумя произвольными _<коммитами>_.
+
Если указан параметр `--merge-base`, вместо непосредственно самого _<коммита>_ будет использоваться базовый коммит слияния _<коммита>_ и `HEAD`. Команда `git diff --merge-base A B` эквивалентна `git diff $(git merge-base A B) B`.

`git diff [<параметры>] <коммит> <коммит>...<коммит> [--] [<путь>...]`::

	Эта форма команды используется для просмотра результатов коммита слияния. Первый заданный _<коммит>_ должен быть собственно коммитом слияния; оставшиеся два или более коммитов должны быть его родителями. Удобный способ получения необходимого набора редакций — использовать суффиксы `@` и `^!`. Если `A` является коммитом слияния, то `git diff A A^@`, `git diff A^!` и `git show A` все выдают одинаковый комбинированный список изменений.

`git diff [<параметры>] <коммит>..<коммит> [--] [<путь>...]`::

	Эта форма команды эквивалентна ранее упомянутой форме (без `..`) для просмотра изменений между двумя произвольными _<коммитами>_. Если _<коммит>_ с одной из сторон опущен, это будет означать то же самое, что и указание `HEAD` на его месте.

`git diff [<параметры>] <коммит>...<коммит> [--] [<путь>...]`::

	Эта форма команды используется для просмотра изменений, произошедших в ветке, содержащей второй _<коммит>_, между общим предком обоих _<коммитов>_ и вторым коммитом. Команда `git diff A...B` эквивалентна `git diff $(git merge-base A B) B`. Если один из _<коммитов>_ опущен, это будет означать то же самое, что и указание `HEAD` на его месте.

На случай, если вы делаете что-то экзотическое, следует отметить, что вместо любого аргумента _<коммит>_ в вышеприведённом списке (за исключении формы с `--merge-base`, а также в двух последних форм с нотацией через точки `..`), может использоваться любой _<дерево>_. В частности, одно из деревьев, которое представляет интерес, — это то, на которое указывает ссылка с именем `AUTO_MERGE`, которая записывается стратегией слияния `ort` при возникновении конфликтов слияния (см. linkgit:git-merge[1]). Сравнение рабочего каталога с `AUTO_MERGE` покажет те изменения, которые вы на данный момент сделали для разрешения конфликтов в тексте (см. примеры ниже).

Для более полного списка способов указания _<коммитов>_, см. раздел «УКАЗАНИЕ РЕДАКЦИЙ» в linkgit:gitrevisions[7]. Однако команда `diff` предназначена для сравнения двух _конечных точек_, а не диапазонов; так что нотация с указанием диапазона (`<коммит>..<коммит>` и `<коммит>...<коммит>`) на самом деле не означают «диапазон», как это постулируется в разделе «УКАЗАНИЕ РЕДАКЦИЙ» в linkgit:gitrevisions[7].

`git diff [<параметры>] <blob> <blob>`::

	Эта форма используется для просмотра различий между сырыми содержимыми двух blob-объектов.

ПАРАМЕТРЫ
---------
:git-diff: 1
include::diff-options.adoc[]

`-1`::
`--base`::
`-2`::
`--ours`::
`-3`::
`--theirs`::
	Сравнение рабочего каталога с:
+
--
 * «базовой» версией (индекс №1) при использовании `-1` или `--base`,
 * «нашей веткой» (индекс №2) при использовании `-2` или `--ours`, или
 * «их веткой» (индекс №3) при использовании `-3` или `--theirs`.
--
+
Все эти три индекса существуют только для не слитых записей, т.е. при разрешении конфликтов. См. подробности в linkgit:git-read-tree[1] в разделе «Трёхходовое слияние».

`-0`::
	Опускать вывод списка изменений для не слитых записей и вместо этого просто выводить «Unmerged» («Не слит»). Данный параметр может использоваться только при сравнении рабочего каталога с индексом.

`<путь>…`::
	При указании _<путей>_ в аргументах выводимый список изменений ограничивается изменениями только в указанных путях (можно также указать имена каталогов и получить список изменений для всех файлов внутри этих каталогах).


include::diff-format.adoc[]

ПРИМЕРЫ
-------

Различные способы проверить состояние вашего рабочего каталога::
+
------------
$ git diff            <1>
$ git diff --cached   <2>
$ git diff HEAD       <3>
$ git diff AUTO_MERGE <4>
------------
+
<1> Изменения в рабочем каталоге, которые ещё не были проиндексированы для следующего коммита.
<2> Изменения между вашим последним коммитом и индексом; то, что будет закоммичено, если вы выполните `git commit` без параметра `-a`.
<3> Изменения в рабочем каталоге с момента вашего последнего коммита; то, что будет закоммичено, если вы выполните `git commit -a`.
<4> Изменения в рабочем каталоге, которые вы на данный момент сделали для разрешения конфликтов в текстах.

Сравнение с произвольными коммитами::
+
------------
$ git diff test            <1>
$ git diff HEAD -- ./test  <2>
$ git diff HEAD^ HEAD      <3>
------------
+
<1> Вместо верхушки текущей ветки, сравнить с верхушкой ветки «test».
<2> Вместо сравнения с верхушкой ветки «test», сравнить с верхушкой текущей ветки, но ограничиться сравнением только файла «test».
<3> Сравнить состояние перед последним коммитом и после него.

Сравнение веток::
+
------------
$ git diff topic master    <1>
$ git diff topic..master   <2>
$ git diff topic...master  <3>
------------
+
<1> Изменения между верхушками веток topic и master.
<2> То же, что и предыдущее.
<3> Изменения, которые произошли в ветке master с момента ответвления от неё ветки topic.

Ограничение вывода diff::
+
------------
$ git diff --diff-filter=MRC            <1>
$ git diff --name-status                <2>
$ git diff arch/i386 include/asm-i386   <3>
------------
+
<1> Показать только изменения, переименования и копирования, но не добавления или удаления.
<2> Показать только имена и характер изменений, но не сами изменения.
<3> Ограничиться только изменениями в заданных поддеревьями при выводе списка изменений.

Изменение вывода diff::
+
------------
$ git diff --find-copies-harder -B -C  <1>
$ git diff -R                          <2>
------------
+
<1> Потратить дополнительные ресурсы на поиск переименований, копирований и изменений, которые полностью переписывают файл (очень затратно).
<2> Выводить diff в обратном порядке.

КОНФИГУРАЦИЯ
------------

include::includes/cmd-config-section-all.adoc[]

:git-diff: 1
include::config/diff.adoc[]

СМОТРИТЕ ТАКЖЕ
--------------
`diff`(1), linkgit:git-difftool[1], linkgit:git-log[1], linkgit:gitdiffcore[7], linkgit:git-format-patch[1], linkgit:git-apply[1], linkgit:git-show[1]

GIT
---
Является частью пакета linkgit:git[1]
