git-whatchanged(1)
==================

НАЗВАНИЕ
--------
git-whatchanged — Показать журналы с изменениями, которые вносит каждый коммит


ОБЗОР
-----
[synopsis]
git whatchanged <параметр>...

ПРЕДУПРЕЖДЕНИЕ
--------------
`git whatchanged` устарела и запланирована к удалению в будущей версии Git, поскольку она является всего лишь `git log` с другими параметрами по умолчанию.

ОПИСАНИЕ
--------

Показывает журналы коммитов и вывод списка изменений, который вносит каждый коммит.

Новым пользователям рекомендуется использовать вместо неё linkgit:git-log[1]. Команда `whatchanged` по сути та же, что и linkgit:git-log[1], но по умолчанию показывает список изменений в необработанном формате и пропускает слияния:

----
git log --raw --no-merges
----

Команда сохраняется в основном по историческим причинам; пальцы многих людей, которые изучили Git задолго до того, как был изобретён `git log`, читая список рассылки ядра Linux, обучены набирать её.


Примеры
-------
`git whatchanged -p v2.6.12.. include/scsi drivers/scsi`::

	Показать в виде изменений коммиты, начиная с версии 'v2.6.12', которые изменили любой файл в подкаталогах include/scsi или drivers/scsi

`git whatchanged --since="2 weeks ago" -- gitk`::

	Показать изменения за последние две недели в файле 'gitk'. "--" необходим, чтобы избежать путаницы с *веткой* с именем 'gitk'

GIT
---
Является частью пакета linkgit:git[1]
