git-fetch-pack(1)
=================

НАЗВАНИЕ
--------
git-fetch-pack — получение недостающих объектов из другого репозитория


ОБЗОР
-----
[verse]
'git fetch-pack' [--all] [--quiet|-q] [--keep|-k] [--thin] [--include-tag]
	[--upload-pack=<git-upload-pack>]
	[--depth=<число>] [--no-progress]
	[-v] <репозиторий> [<ссылки>...]

ОПИСАНИЕ
--------
Обычно вместо этого вы захотите использовать 'git fetch', который является более высокоуровневой обёрткой этой команды.

Вызывает 'git-upload-pack' в возможно внешнем репозитории и просит его отправить объекты, отсутствующие в этом репозитории, чтобы обновить именованные головы. Список доступных локально коммитов определяется путём сканирования локальной иерархии refs/ и отправляется 'git-upload-pack', работающему на другой стороне.

Эта команда вырождается в загрузку всего для завершения запрошенных ссылок с внешней стороны, когда у локальной стороны нет общего коммита-предка.


ПАРАМЕТРЫ
---------
--all::
	Получить все внешние ссылки.

--stdin::
	Брать список ссылок из stdin, по одной на строку. Если в командной строке указаны ссылки в дополнение к этому параметру, то ссылки из stdin обрабатываются после указанных в командной строке.
+
Если `--stateless-rpc` указан вместе с этим параметром, то список ссылок должен быть в формате пакетов (pkt-line). Каждая ссылка должна быть в отдельном пакете, и список должен заканчиваться пакетом сброса.

-q::
--quiet::
	Передать флаг `-q` в 'git unpack-objects'; это делает процесс клонирования менее подробным.

-k::
--keep::
	Не вызывать 'git unpack-objects' для полученных данных, а вместо этого создать из них один pack-файл и сохранить его в базе данных объектов. Если указано дважды, пакет блокируется от переупаковки.

--thin::
	Получает "тонкий" пакет, который записывает объекты в дельтифицированной форме на основе объектов, не включённых в пакет, для уменьшения сетевого трафика.

--include-tag::
	Если внешняя сторона поддерживает это, аннотированные объекты меток будут загружены по тому же соединению, что и другие объекты, если объект, на который ссылается метка, загружается. В противном случае вызывающая сторона должна сама определить метки, которые сделал доступными этот параметр.

--upload-pack=<git-upload-pack>::
	Используйте это, чтобы указать путь к 'git-upload-pack' на внешней стороне, если он не найден в вашем $PATH. Установки sshd игнорируют сценарии настройки среды пользователя для оболочек входа в систему (например, .bash_profile), и ваш частным образом установленный git может не быть найден в системном $PATH по умолчанию. Другой предлагаемый обходной путь — настроить ваш $PATH в ".bashrc", но этот флаг предназначен для людей, которые не хотят платить накладные расходы для неинтерактивных оболочек, имея минимальный файл .bashrc (они настраивают большинство вещей в .bash_profile).

--exec=<git-upload-pack>::
	То же, что и --upload-pack=<git-upload-pack>.

--depth=<n>::
	Ограничивает получение цепочками предков длиной не более n. 'git-upload-pack' рассматривает специальную глубину 2147483647 как бесконечную, даже если есть такая длинная цепочка предков.

--shallow-since=<дата>::
	Углубить или сократить историю частичного репозитория, чтобы включить все достижимые коммиты после <даты>.

--shallow-exclude=<ссылка>::
	Углубляет или укорачивает историю мелкого репозитория, чтобы исключить коммиты, достижимые из указанной удалённой ветки или тега. Эту опцию можно указать несколько раз.

--deepen-relative::
	Аргумент --depth указывает количество коммитов от текущей границы частичности вместо верхушки истории каждой внешней ветки.

--refetch::
	Пропускает согласование коммитов с сервером, чтобы получить все соответствующие объекты. Используйте, чтобы повторно применить новый фильтр blob-объектов/деревьев для частичного клона.

--no-progress::
	Не показывать ход выполнения.

--check-self-contained-and-connected::
	Вывести "connectivity-ok", если полученный пакет является самодостаточным и связным.

-v::
	Работать подробно (verbose).

<репозиторий>::
	URL-адрес внешнего репозитория.

<refs>...::
	Внешние головы для обновления. Это относительно $GIT_DIR (например, "HEAD", "refs/heads/master"). Если не указано, обновлять из всех голов, которые есть на внешней стороне.
+
Если внешний репозиторий включил параметры `uploadpack.allowTipSHA1InWant`, `uploadpack.allowReachableSHA1InWant` или `uploadpack.allowAnySHA1InWant`, они могут альтернативно быть 40-шестнадцатеричными sha1, присутствующими на внешней стороне.

СМ. ТАКЖЕ
---------
linkgit:git-fetch[1]

GIT
---
Является частью пакета linkgit:git[1]
