git-mv(1)
=========

НАЗВАНИЕ
--------
git-mv - Перемещение или переименование файла, каталога или символической ссылки


ОБЗОР
-----

[synopsis]
'git mv' [-v] [-f] [-n] [-k] <источник> <назначение>
'git mv' [-v] [-f] [-n] [-k] <источник>... <каталог-назначения>

ОПИСАНИЕ
--------
Перемещение или переименование файла, каталога или символической ссылки.

В первой форме переименовывает _<источник>_, который должен существовать и быть файлом, символьной ссылкой или каталогом, в _<назначение>_. Во второй форме _<каталог-назначения>_ должен быть существующим каталогом; указанные источники будут перемещены в этот каталог.

Индекс обновляется после успешного завершения, но изменение всё равно должно быть закоммичено.

ПАРАМЕТРЫ
---------
`-f`::
`--force`::
	Принудительное переименование или перемещение файла, даже если <назначение> существует.
`-k`::
	Пропустить действия перемещения или переименования, которые привели бы к ошибке. Ошибка возникает, когда источник не существует и не контролируется Git или когда он перезаписал бы существующий файл, если не указан `-f`.
`-n`::
`--dry-run`::
	Ничего не делать; только показать, что произошло бы

`-v`::
`--verbose`::
	Сообщать имена файлов по мере их перемещения.

ПОДМОДУЛИ
---------
Перемещение подмодуля с использованием git-файла (что означает, что они были клонированы с версией Git 1.7.8 или новее) обновит git-файл и настройку core.worktree, чтобы подмодуль работал в новом расположении. Он также попытается обновить настройку `submodule.<имя>.path` в файле linkgit:gitmodules[5] и проиндексировать этот файл (если не используется `-n`).

ОШИБКИ
------
Каждый раз, когда обновление суперпроекта перемещает заполненный подмодуль (например, при переключении между коммитами до и после перемещения), устаревшее переключение подмодуля остаётся в старом расположении, а в новом расположении появляется пустой каталог. Чтобы снова заполнить подмодуль в новом расположении, пользователю придётся позже выполнить "git submodule update". Удаление старого каталога безопасно только в том случае, если он использует git-файл, в противном случае история подмодуля также будет удалена. Оба шага устареют, когда будет реализовано рекурсивное обновление подмодулей.

GIT
---
Является частью пакета linkgit:git[1]
