git-gui(1)
==========

НАЗВАНИЕ
--------
git-gui — Переносимый графический интерфейс для Git

ОБЗОР
-----
[verse]
'git gui' [<команда>] [<аргументы>]

ОПИСАНИЕ
--------
Графический пользовательский интерфейс к Git на основе Tcl/Tk. 'git gui' сосредоточен на предоставлении пользователям возможности вносить изменения в свой репозиторий путём создания новых коммитов, исправления существующих, создания веток, выполнения локальных слияний и получения/отправки во внешние репозитории.

В отличие от 'gitk', 'git gui' сосредоточен на создании коммитов и аннотации отдельных файлов и не показывает историю проекта. Однако он предоставляет действия в меню для запуска сеанса 'gitk' изнутри 'git gui'.

Известно, что 'git gui' работает во всех популярных системах UNIX, Mac OS X и Windows (как под Cygwin, так и под MSYS). По возможности соблюдаются специфичные для ОС рекомендации по пользовательскому интерфейсу, что делает 'git gui' довольно родным интерфейсом для пользователей.

КОМАНДЫ
-------
blame::
	Запустить просмотрщик blame для указанного файла в данной версии (или рабочего каталога, если не указано).

браузер::
	Запустить обозреватель дерева, показывающий все файлы в указанном коммите. Файлы, выбранные через обозреватель, открываются в просмотрщике blame.

citool::
	Запустить 'git gui' и организовать выполнение ровно одного коммита перед завершением и возвратом в оболочку. Интерфейс ограничен только действиями с коммитами, что немного сокращает время запуска приложения и упрощает строку меню.

версия::
	Отобразить текущую работающую версию 'git gui'.


Примеры
-------
`git gui blame Makefile`::

	Показывает содержимое файла 'Makefile' в текущем рабочем каталоге и предоставляет аннотации как для исходного автора каждой строки, так и для того, кто переместил строку в её текущее местоположение. Незафиксированный файл аннотируется, а незафиксированные изменения (если есть) явно приписываются 'Not Yet Committed'.

`git gui blame v0.99.8 Makefile`::

	Показывает содержимое 'Makefile' в редакции 'v0.99.8' и предоставляет аннотации для каждой строки. В отличие от приведённого выше примера, файл читается из базы данных объектов, а не из рабочего каталога.

`git gui blame --line=100 Makefile`::

	Загружает аннотации, как описано выше, и автоматически прокручивает вид, чтобы центрировать строку '100'.

`git gui citool`::

	Сделать один коммит и вернуться в оболочку после его завершения. Эта команда возвращает ненулевой код выхода, если окно было закрыто любым способом, кроме как через создание коммита.

`git gui citool --amend`::

	Автоматически перейти в режим интерфейса 'Исправить последний коммит'.

`git gui citool --nocommit`::

	Вести себя как обычный citool, но вместо создания коммита просто завершиться с нулевым кодом выхода. Он по-прежнему проверяет, что индекс не содержит не слитых записей, поэтому вы можете использовать его как графическую версию linkgit:git-mergetool[1]

`git citool`::

	То же, что и `git gui citool` (выше).

`git gui browser maint`::

	Показать обозреватель для дерева ветки 'maint'. Файлы, выбранные в обозревателе, можно просмотреть с помощью внутреннего просмотрщика blame.

СМ. ТАКЖЕ
---------
linkgit:gitk[1]::
	Обозреватель репозитория Git. Показывает ветки, историю коммитов и различия в файлах. gitk — это утилита, запускаемая действиями 'Визуализировать репозиторий' в 'git gui'.

Другое
------
'git gui' на самом деле поддерживается как независимый проект, но стабильные версии распространяются как часть пакета Git для удобства конечных пользователей.

Официальный репозиторий проекта 'git gui' можно найти по адресу:

  https://github.com/j6t/git-gui

GIT
---
Является частью пакета linkgit:git[1]
