git-fmt-merge-msg(1)
====================

НАЗВАНИЕ
--------
git-fmt-merge-msg — Создание сообщения коммита слияния


ОБЗОР
-----
[verse]
'git fmt-merge-msg' [-m <сообщение>] [--into-name <ветка>] [--log[=<n>] | --no-log]
'git fmt-merge-msg' [-m <сообщение>] [--log[=<n>] | --no-log] -F <файл>

ОПИСАНИЕ
--------
Принимает список слитых объектов на stdin и создаёт подходящее сообщение коммита, которое будет использоваться для коммита слияния, обычно передаваемое как аргумент '<сообщение-слияния>' в 'git merge'.

Эта команда предназначена в основном для внутреннего использования сценариями, автоматически вызывающими 'git merge'.

ПАРАМЕТРЫ
---------

--log[=<n>]::
	В дополнение к именам веток заполнять сообщение журнала однострочными описаниями из фактических коммитов, которые сливаются. Будет использовано не более <n> коммитов от каждого родителя слияния (20, если <n> опущено). Это переопределяет переменную конфигурации `merge.log`.

--no-log::
	Не выводить однострочные описания из фактических сливаемых коммитов.

--summary::
--no-summary::
	Синонимы для --log и --no-log; они устарели и будут удалены в будущем.

-m <сообщение>::
--message <сообщение>::
	Использовать <сообщение> вместо имён веток для первой строки сообщения журнала. Для использования с `--log`.

--into-name <ветка>::
	Подготовить сообщение слияния так, как если бы слияние выполнялось в ветку `<ветка>`, вместо имени реальной ветки, в которую выполняется слияние.

-F <файл>::
--file <файл>::
	Взять список слитых объектов из <файла> вместо stdin.

КОНФИГУРАЦИЯ
------------
include::config/fmt-merge-msg.adoc[]

merge.summary::
	Синоним для `merge.log`; он устарел и будет удалён в будущем.

ПРИМЕРЫ
-------

---------
$ git fetch origin master
$ git fmt-merge-msg --log <$GIT_DIR/FETCH_HEAD
---------

Вывести сообщение журнала, описывающее слияние ветки «master» из внешнего репозитория «origin».


СМ. ТАКЖЕ
---------
linkgit:git-merge[1]

GIT
---
Является частью пакета linkgit:git[1]
