git-check-mailmap(1)
====================

НАЗВАНИЕ
--------
git-check-mailmap - Вывод каноничных имён и адресов электронной почты контактов


ОБЗОР
-----
[verse]
'git check-mailmap' [<параметры>] <контакт>…


ОПИСАНИЕ
--------

Для каждого ``Имя $$<пользователь@хост>$$'', ``$$<пользователь@хост>$$'' или ``$$пользователь@хост$$'' из командной строки или стандартного ввода (при использовании `--stdin`) найти каноническое имя и адрес электронной почты человека (см. "Сопоставление авторов" ниже). Если найдено, вывести их; в противном случае вывести ввод как есть.


ПАРАМЕТРЫ
---------
--stdin::
	Читать контакты, по одному на строку, из стандартного ввода после исчерпания контактов, предоставленных в командной строке.

--mailmap-file=<файл>::
	В дополнение к любым настроенным файлам mailmap читать указанный файл mailmap. Записи в этом файле имеют приоритет над записями в файле mailmap по умолчанию или в любом настроенном файле mailmap.

--mailmap-blob=<blob-объект>::
	Как `--mailmap-file`, но рассматривать значение как ссылку на blob-объект в репозитории. Если указаны и `--mailmap-file`, и `--mailmap-blob`, записи в `--mailmap-file` будут иметь приоритет.

ВЫВОД
-----

Для каждого контакта выводится одна строка, заканчивающаяся символом новой строки. Если имя предоставлено или известно 'mailmap', выводится ``Имя $$<пользователь@хост>$$''; в противном случае выводится только ``$$<пользователь@хост>$$''.


КОНФИГУРАЦИЯ
------------

См. `mailmap.file` и `mailmap.blob` в linkgit:git-config[1] о том, как указать пользовательский целевой файл или объект `.mailmap`.


СОПОСТАВЛЕНИЕ АВТОРОВ
---------------------

См. linkgit:gitmailmap[5].


GIT
---
Является частью пакета linkgit:git[1]
