git-format-patch(1)
===================

НАЗВАНИЕ
--------
git-format-patch - Подготовка изменений (патчей) для отправки по электронной почте


ОБЗОР
-----
[verse]
'git format-patch' [-k] [(-o|--output-directory) <каталог> | --stdout]
		   [--no-thread | --thread[=<стиль>]]
		   [(--attach|--inline)[=<граница>] | --no-attach]
		   [-s | --signoff]
		   [--signature=<подпись> | --no-signature]
		   [--signature-file=<файл>]
		   [-n | --numbered | -N | --no-numbered]
		   [--start-number <n>] [--numbered-files]
		   [--in-reply-to=<id-сообщения>] [--suffix=.<суффикс>]
		   [--ignore-if-in-upstream] [--always]
		   [--cover-from-description=<режим>]
		   [--rfc[=<rfc>]] [--subject-prefix=<префикс-темы>]
		   [(--reroll-count|-v) <n>]
		   [--to=<email>] [--cc=<email>]
		   [--[no-]cover-letter] [--quiet]
		   [--[no-]encode-email-headers]
		   [--no-notes | --notes[=<ссылка>]]
		   [--interdiff=<предыдущий>]
		   [--range-diff=<предыдущий> [--creation-factor=<процент>]]
		   [--filename-max-length=<n>]
		   [--progress]
		   [<общие-параметры-diff>]
		   [ <начиная-с> | <диапазон-редакций> ]

ОПИСАНИЕ
--------

Подготавливает каждый коммит без слияния с его «изменением» (патчем) в одном «сообщении» на коммит, отформатированном так, чтобы напоминать почтовый ящик UNIX. Вывод этой команды удобен для отправки по электронной почте или для использования с 'git am'.

«Сообщение», созданное командой, состоит из трёх частей:

* Краткий заголовок метаданных, который начинается с `From <коммит>` с фиксированной временной меткой `Mon Sep 17 00:00:00 2001`, чтобы помочь таким программам, как «file(1)», распознать, что файл является выводом этой команды, поля, записывающие личность автора, дату автора и заголовок изменения (взятый из первого абзаца сообщения журнала коммита).

* Второй и последующие абзацы сообщения журнала коммита.

* "Патч", который является выводом "diff -p --stat" (см. linkgit:git-diff[1]) между коммитом и его родителем.

Сообщение журнала и патч разделены строкой с тремя дефисами.

Существует два способа указать, с какими коммитами работать.

1. Одиночный коммит, <начиная-с>, указывает, что должны быть выведены коммиты, ведущие к верхушке текущей ветки, которых нет в истории, ведущей к <начиная-с>.

2. Выражение <диапазон-редакций> общего вида (см. раздел "ЗАДАНИЕ РЕВИЗИЙ" в linkgit:gitrevisions[7]) означает коммиты в указанном диапазоне.

В случае одиночного <коммита> первое правило имеет приоритет. Чтобы применить второе правило, т.е. отформатировать всё с начала истории до <коммита>, используйте параметр `--root`: `git format-patch --root <коммит>`. Если вы хотите отформатировать только сам <коммит>, вы можете сделать это с помощью `git format-patch -1 <коммит>`.

По умолчанию каждый выходной файл нумеруется последовательно, начиная с 1, и использует первую строку сообщения коммита (обработанную для безопасности имени пути) в качестве имени файла. С параметром `--numbered-files` имена выходных файлов будут только номерами, без добавления первой строки коммита. Имена выходных файлов выводятся в стандартный вывод, если не указан параметр `--stdout`.

Если указан `-o`, выходные файлы создаются в <каталог>. В противном случае они создаются в текущем рабочем каталоге. Путь по умолчанию можно задать с помощью переменной конфигурации `format.outputDirectory`. Параметр `-o` имеет приоритет над `format.outputDirectory`. Чтобы сохранять патчи в текущем рабочем каталоге, даже если `format.outputDirectory` указывает в другое место, используйте `-o .`. Все компоненты каталога будут созданы.

По умолчанию тема одного патча — "[PATCH] ", за которым следует объединение строк из сообщения коммита до первой пустой строки (см. раздел ОБСУЖДЕНИЕ в linkgit:git-commit[1]).

Когда выводится несколько патчей, префикс темы будет "[PATCH n/m] ". Чтобы принудительно добавить 1/1 для одного патча, используйте `-n`. Чтобы опустить номера патчей в теме, используйте `-N`.

Если указан `--thread`, `git-format-patch` создаст заголовки `In-Reply-To` и `References`, чтобы сделать второе и последующие письма с патчами ответами на первое письмо; это также создаёт заголовок `Message-ID` для ссылки.

ПАРАМЕТРЫ
---------
:git-format-patch: 1
include::diff-options.adoc[]

-<n>::
	Подготовить патчи из верхних <число> коммитов.

-o <каталог>::
--output-directory <каталог>::
	Использовать <каталог> для хранения результирующих файлов вместо текущего рабочего каталога.

-n::
--numbered::
	Именовать вывод в формате '[PATCH n/m]', даже для одного патча.

-N::
--no-numbered::
	Именовать вывод в формате '[PATCH]'.

--start-number <n>::
	Начать нумерацию патчей с <n>, а не с 1.

--numbered-files::
	Имена выходных файлов будут простой числовой последовательностью без добавления первой строки коммита по умолчанию.

-k::
--keep-subject::
	Не удалять/не добавлять '[PATCH]' из первой строки сообщения журнала коммита.

-s::
--signoff::
	Добавляет трейлер `Signed-off-by` в сообщение коммита, используя вашу личность коммитера. Для получения дополнительной информации см. опцию signoff в linkgit:git-commit[1].

--stdout::
	Выводить все коммиты в стандартный вывод в формате mbox вместо создания файла для каждого из них.

--attach[=<boundary>]::
	Создавать вложение multipart/mixed, первая часть которого — сообщение коммита, а сам патч — во второй части, с `Content-Disposition: attachment`.

--no-attach::
	Отключить создание вложения, переопределяя параметр конфигурации.

--inline[=<boundary>]::
	Создавать вложение multipart/mixed, первая часть которого — сообщение коммита, а сам патч — во второй части, с `Content-Disposition: inline`.

--thread[=<style>]::
--no-thread::
	Управляет добавлением заголовков `In-Reply-To` и `References`, чтобы сделать второе и последующие письма ответами на первое. Также управляет генерацией заголовка `Message-ID` для ссылки.
+
Необязательный аргумент <стиль> может быть `shallow` или `deep`. Поток 'shallow' делает каждое письмо ответом на начало серии, где начало выбирается из сопроводительного письма, `--in-reply-to` и первого письма с патчем в этом порядке. Поток 'deep' делает каждое письмо ответом на предыдущее.
+
По умолчанию используется `--no-thread`, если не задана конфигурация `format.thread`. `--thread` без аргумента эквивалентен `--thread=shallow`.
+
Имейте в виду, что по умолчанию 'git send-email' сам формирует поток писем. Если вы хотите, чтобы `git format-patch` занимался формированием потока, вам нужно убедиться, что формирование потока отключено для `git send-email`.

--in-reply-to=<id-сообщения>::
	Сделать первое письмо (или все письма с `--no-thread`) ответом на указанный <id-сообщения>, что позволяет не разрывать поток при отправке новой серии патчей.

--ignore-if-in-upstream::
	Не включать патч, соответствующий коммиту в <до>..<начиная-с>. Это проверит все патчи, достижимые из <начиная-с>, но не из <до>, и сравнит их с создаваемыми патчами; любой соответствующий патч игнорируется.

--always::
	Включать патчи для коммитов, которые не вносят никаких изменений (по умолчанию они опускаются).

--cover-from-description=<режим>::
	Управляет тем, какие части сопроводительного письма будут автоматически заполнены с использованием описания ветки.
+
Если `<режим>` — `message` или `default`, тема сопроводительного письма будет заполнена текстом-заполнителем. Тело сопроводительного письма будет заполнено описанием ветки. Это режим по умолчанию, когда не указана ни конфигурация, ни параметр командной строки.
+
Если `<режим>` — `subject`, первый абзац описания ветки заполнит тему сопроводительного письма. Остальная часть описания заполнит тело сопроводительного письма.
+
Если `<режим>` — `auto`, то если первый абзац описания ветки больше 100 байт, режим будет `message`, в противном случае будет использован `subject`.
+
Если `<режим>` — `none`, и тема, и тело сопроводительного письма будут заполнены текстом-заполнителем.

--description-file=<файл>::
	Использовать содержимое <файла> вместо описания ветки для создания сопроводительного письма.

--subject-prefix=<префикс-темы>::
	Вместо стандартного префикса '[PATCH]' в строке темы использовать '[<префикс-темы>]'. Это можно использовать для именования серии патчей и комбинировать с параметром `--numbered`.
+
Переменная конфигурации `format.subjectPrefix` также может использоваться для задания префикса темы, применяемого ко всем патчам для данного репозитория. Это часто полезно в списках рассылки, которые получают патчи для нескольких репозиториев, и может использоваться для устранения неоднозначности патчей (например, со значением "PATCH my-project").

--filename-max-length=<n>::
	Вместо стандартных 64 байт обрезать имена создаваемых выходных файлов примерно до '<число>' байт (слишком короткое значение будет автоматически увеличено до разумной длины). По умолчанию используется значение переменной конфигурации `format.filenameMaxLength` или 64, если не задано.

--rfc[=<rfc>]::
	Добавляет строку _<rfc>_ (по умолчанию "RFC") в начало префикса темы. Поскольку префикс темы по умолчанию — "PATCH", по умолчанию вы получите "RFC PATCH".
+
RFC означает "Request For Comments" (Запрос комментариев); используйте это при отправке экспериментального патча для обсуждения, а не для применения. "--rfc=WIP" также может быть полезным способом указать, что патч ещё не завершён ("WIP" расшифровывается как "Work In Progress" — "в процессе работы").
+
Если в сообществе получателей принято, чтобы определённая дополнительная строка располагалась _после_ префикса темы, строку _<rfc>_ можно предварить дефисом ("`-`"), чтобы указать, что остальная часть строки _<rfc>_ должна быть добавлена к префиксу темы, например, `--rfc='-(WIP)'` даёт "PATCH (WIP)".

-v <n>::
--reroll-count=<n>::
	Помечает серию как <число>-ю итерацию темы. К именам выходных файлов добавляется `v<число>`, а к префиксу темы (по умолчанию "PATCH", но настраивается через параметр `--subject-prefix`) добавляется ` v<число>`. Например, `--reroll-count=4` может создать файл `v4-0001-add-makefile.patch`, содержащий "Subject: [PATCH v4 1/20] Add makefile". `<число>` не обязательно должно быть целым (например, допускается "--reroll-count=4.4" или "--reroll-count=4rev2"), но недостаток использования такого числа повторного выпуска в том, что range-diff/interdiff с предыдущей версией не указывает точно, с какой версией сравнивается новая итерация.

--to=<email>::
	Добавляет заголовок `To:` в заголовки письма. Это дополнение к любым настроенным заголовкам, может использоваться несколько раз. Отрицательная форма `--no-to` отбрасывает все заголовки `To:`, добавленные до этого (из конфигурации или командной строки).

--cc=<email>::
	Добавляет заголовок `Cc:` в заголовки письма. Это дополнение к любым настроенным заголовкам, может использоваться несколько раз. Отрицательная форма `--no-cc` отбрасывает все заголовки `Cc:`, добавленные до этого (из конфигурации или командной строки).

--from::
--from=<ident>::
	Использовать `идентификатор` в заголовке `From:` каждого письма с коммитом. Если идентификатор автора коммита текстуально не совпадает с указанным `идентификатором`, поместить заголовок `From:` в тело сообщения с исходным автором. Если `идентификатор` не указан, использовать идентификатор коммиттера.
+
Обратите внимание, что этот параметр полезен только если вы действительно отправляете письма и хотите идентифицировать себя как отправителя, но сохранить исходного автора (и `git am` правильно распознает заголовок в теле). Также учтите, что `git send-email` уже выполняет это преобразование за вас, и этот параметр не следует использовать, если вы передаёте результат в `git send-email`.

--force-in-body-from::
--no-force-in-body-from::
	Когда отправитель письма указан через параметр `--from`, по умолчанию в тело сообщения вверху добавляется "From:" для идентификации реального автора коммита, если отправитель отличается от автора. С этим параметром "From:" в теле добавляется даже когда у отправителя и автора одинаковые имя и адрес, что может помочь, если программное обеспечение списка рассылки искажает личность отправителя. По умолчанию используется значение переменной конфигурации `format.forceInBodyFrom`.

--add-header=<header>::
	Добавляет произвольный заголовок в заголовки письма. Это дополнение к любым настроенным заголовкам, может использоваться несколько раз. Например, `--add-header="Organization: git-foo"`. Отрицательная форма `--no-add-header` отбрасывает *все* заголовки (`To:`, `Cc:` и пользовательские), добавленные до этого из конфигурации или командной строки.

--cover-letter::
--no-cover-letter::
	В дополнение к патчам создаёт файл сопроводительного письма, содержащий описание ветки, краткий журнал и общую статистику различий. Вы можете заполнить описание в файле перед отправкой.

--encode-email-headers::
--no-encode-email-headers::
	Кодировать заголовки электронной почты, содержащие не-ASCII символы, с помощью "Q-encoding" (описано в RFC 2047), вместо вывода заголовков как есть. По умолчанию используется значение переменной конфигурации `format.encodeEmailHeaders`.

--interdiff=<previous>::
	В качестве помощи рецензенту вставляет интердифф в сопроводительное письмо или в комментарий к единственному патчу серии из одного патча, показывая различия между предыдущей версией серии патчей и серией, которая в данный момент форматируется. `предыдущая` — это одна редакция, указывающая на верхушку предыдущей серии, которая имеет общую основу с форматируемой серией (например, `git format-patch --cover-letter --interdiff=feature/v1 -3 feature/v2`).

--range-diff=<previous>::
	В качестве помощи рецензенту вставляет range-diff (см. linkgit:git-range-diff[1]) в сопроводительное письмо или в комментарий к единственному патчу серии из одного патча, показывая различия между предыдущей версией серии патчей и серией, которая в данный момент форматируется. `предыдущая` может быть одной редакцией, указывающей на верхушку предыдущей серии, если она имеет общую основу с форматируемой серией (например, `git format-patch --cover-letter --range-diff=feature/v1 -3 feature/v2`), или диапазоном редакций, если две версии серии не пересекаются (например, `git format-patch --cover-letter --range-diff=feature/v1~3..feature/v1 -3 feature/v2`).
+
Обратите внимание, что параметры сравнения, переданные команде, влияют на то, как создаётся основной продукт `format-patch`, и они не передаются в механизм `range-diff`, используемый для создания материала сопроводительного письма (это может измениться в будущем).

--creation-factor=<percent>::
	Используется с `--range-diff`, настраивает эвристику, которая сопоставляет коммиты между предыдущей и текущей сериями патчей, путём регулировки фактора корректировки стоимости создания/удаления. Подробности см. в linkgit:git-range-diff[1]).
+
По умолчанию используется 999 (linkgit:git-range-diff[1] использует 60), так как вариант использования — показать сравнение с более старой итерацией той же темы, и инструмент должен находить больше соответствий между двумя наборами патчей.

--notes[=<ссылка>]::
--no-notes::
	Добавляет заметки (см. linkgit:git-notes[1]) для коммита после строки с тремя дефисами.
+
Ожидаемый вариант использования этого — написать пояснение для коммита, которое не относится к самому сообщению журнала коммита, и включить его в отправку патча. Хотя можно просто написать эти пояснения после выполнения `format-patch`, но до отправки, хранение их в виде заметок Git позволяет поддерживать их между версиями серии патчей (но см. обсуждение параметров конфигурации `notes.rewrite` в linkgit:git-notes[1] для использования этого рабочего процесса).
+
По умолчанию используется `--no-notes`, если не задана конфигурация `format.notes`.

--signature=<подпись>::
--no-signature::
	Добавляет подпись к каждому созданному сообщению. Согласно RFC 3676, подпись отделяется от тела строкой с '-- ' на ней. Если параметр подписи опущен, подпись по умолчанию — номер версии Git.

--signature-file=<file>::
	Работает точно так же, как --signature, за исключением того, что подпись читается из файла.

--suffix=.<sfx>::
	Вместо использования `.patch` в качестве суффикса для создаваемых имён файлов использовать указанный суффикс. Распространённая альтернатива — `--suffix=.txt`. Если оставить это пустым, суффикс `.patch` будет удалён.
+
Обратите внимание, что первый символ не обязательно должен быть точкой; например, вы можете использовать `--suffix=-patch`, чтобы получить `0001-description-of-my-change-patch`.

-q::
--quiet::
	Не выводить имена созданных файлов в стандартный вывод.

--no-binary::
	Не выводить содержимое изменений в двоичных файлах, вместо этого показывать уведомление о том, что эти файлы изменились. Патчи, созданные с использованием этого параметра, не могут быть правильно применены, но они всё ещё полезны для проверки кода.

--zero-commit::
  Выводить нулевой хеш в заголовке From каждого патча вместо хеша коммита.

--no-base::
--base[=<коммит>]::
	Записывает информацию о базовом дереве для идентификации состояния, к которому применяется серия патчей. Подробности см. в разделе ИНФОРМАЦИЯ О БАЗОВОМ ДЕРЕВЕ ниже. Если <коммит> — "auto", базовый коммит выбирается автоматически. Параметр `--no-base` переопределяет конфигурацию `format.useAutoBase`.

--root::
	Обрабатывать аргумент редакции как <диапазон-редакций>, даже если это просто один коммит (который обычно обрабатывается как <начиная-с>). Обратите внимание, что корневые коммиты, включённые в указанный диапазон, всегда форматируются как патчи создания, независимо от этого флага.

--progress::
	Показывать отчёты о ходе выполнения в stderr по мере создания патчей.

КОНФИГУРАЦИЯ
------------
Вы можете указать дополнительные строки заголовков письма для добавления к каждому сообщению, значения по умолчанию для префикса темы и суффикса файла, нумеровать патчи при выводе более одного патча, добавлять заголовки "To:" или "Cc:", настраивать вложения, изменять выходной каталог патчей и подписывать патчи с помощью переменных конфигурации.

------------
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <адрес-электронной-почты>
	cc = <адрес-электронной-почты>
	attach [ = строка-границы-mime ]
	signOff = true
	outputDirectory = <каталог>
	coverLetter = auto
	coverFromDescription = auto
------------


ОБСУЖДЕНИЕ
----------

Патч, создаваемый 'git format-patch', имеет формат почтового ящика UNIX с фиксированной "магической" меткой времени, указывающей, что файл является выводом format-patch, а не настоящим почтовым ящиком, например:

------------
From 8f72bad1baf19a53459661343e21d6491c3908d3 Mon Sep 17 00:00:00 2001
From: Tony Luck <tony.luck@intel.com>
Date: Tue, 13 Jul 2010 11:42:54 -0700
Subject: [PATCH] =?UTF-8?q?[IA64]=20Put=20ia64=20config=20files=20on=20the=20?=
 =?UTF-8?q?Uwe=20Kleine-K=C3=B6nig=20diet?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

файлы конфигурации arch/arm были уменьшены с помощью скрипта python
(См. комментарий к коммиту c2330e286f68f1c408b4aa6515ba49d57f05beae)

Сделайте то же самое для ia64, чтобы мы могли иметь изящный и подтянутый вид
...
------------

Обычно он помещается в папку черновиков MUA, редактируется для добавления своевременных комментариев, которые не должны попадать в журнал изменений после трёх дефисов, а затем отправляется как сообщение, тело которого в нашем примере начинается с "файлы конфигурации arch/arm были...". На принимающей стороне читатели могут сохранить интересующие патчи в почтовом ящике UNIX и применить их с помощью linkgit:git-am[1].

Когда патч является частью текущего обсуждения, патч, созданный 'git format-patch', можно настроить для использования возможности 'git am --scissors'. После вашего ответа на обсуждение идёт строка, состоящая только из "`-- >8 --`" (ножницы и перфорация), за которой следует патч с удалёнными ненужными полями заголовка:

------------
...
> Итак, мы должны сделать то-то и то-то.

Звучит разумно. Как насчёт такого патча?

-- >8 --
Subject: [IA64] Посадим файлы конфигурации ia64 на диету Уве Кляйне-Кёнига

файлы конфигурации arch/arm были уменьшены с помощью скрипта python
...
------------

При отправке патча таким образом, чаще всего вы отправляете свой собственный патч, поэтому в дополнение к маркеру "`From $SHA1 $magic_timestamp`" вам следует опустить строки `From:` и `Date:` из файла патча. Заголовок патча, вероятно, будет отличаться от темы обсуждения, на которое отвечает патч, поэтому, скорее всего, вы захотите сохранить строку Subject:, как в примере выше.

Проверка на повреждение патча
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Многие почтовые программы, если они настроены неправильно, повреждают пробелы. Вот два распространённых типа повреждений:

* Пустые строки контекста, не имеющие _никаких_ пробелов.

* Непустые строки контекста, имеющие один лишний пробел в начале.

Один из способов проверить, правильно ли настроена ваша MUA:

* Отправьте патч себе, точно так же, как вы бы отправили, за исключением строк To: и Cc:, которые не содержат адрес списка и сопровождающего.

* Сохраните этот патч в файл в формате почтового ящика UNIX. Назовите его, например, a.patch.

* Примените его:

    $ git fetch <проект> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

Если он не применяется правильно, причин может быть несколько.

* Сам патч не применяется чисто. Это _плохо_, но мало связано с вашей MUA. В этом случае вы, возможно, захотите переместить патч с помощью linkgit:git-rebase[1] перед его повторным созданием.

* MUA повредила ваш патч; "am" будет жаловаться, что патч не применяется. Посмотрите в подкаталог .git/rebase-apply/ и посмотрите, что содержит файл 'patch', и проверьте наличие распространённых шаблонов повреждений, упомянутых выше.

* Заодно проверьте также файлы 'info' и 'final-commit'. Если то, что находится в 'final-commit', не совсем то, что вы хотели бы видеть в сообщении журнала коммита, вполне вероятно, что получатель в итоге будет вручную редактировать сообщение журнала при применении вашего патча. Такие вещи, как "Привет, это мой первый патч.\n" в письме с патчем, должны идти после строки с тремя дефисами, которая обозначает конец сообщения коммита.

СОВЕТЫ ДЛЯ КОНКРЕТНЫХ MUA
-------------------------
Здесь приведены некоторые советы о том, как успешно отправлять патчи в виде встроенного текста с помощью различных почтовых программ.

GMail
~~~~~
GMail не имеет возможности отключить перенос строк в веб-интерфейсе, поэтому он исказит любые отправляемые вами письма. Однако вы можете использовать "git send-email" и отправлять свои патчи через SMTP-сервер GMail или использовать любой почтовый клиент IMAP для подключения к серверу IMAP google и пересылать письма через него.

Советы по использованию 'git send-email' для отправки патчей через SMTP-сервер GMail см. в разделе ПРИМЕРЫ linkgit:git-send-email[1].

Советы по отправке с использованием интерфейса IMAP см. в разделе ПРИМЕРЫ linkgit:git-imap-send[1].

Thunderbird
~~~~~~~~~~~
По умолчанию Thunderbird будет как переносить письма, так и помечать их как 'format=flowed', и то и другое сделает результирующее письмо непригодным для использования Git.

Существует три разных подхода: использовать дополнение для отключения переноса строк, настроить Thunderbird так, чтобы он не искажал патчи, или использовать внешний редактор, чтобы Thunderbird не искажал патчи.

Подход №1 (дополнение)
^^^^^^^^^^^^^^^^^^^^^^

Установите дополнение Toggle Line Wrap, доступное по адресу https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap. Оно добавляет кнопку "Line Wrap" на панель инструментов редактора, которую вы можете отключить. Теперь вы можете составлять сообщение как обычно (вырезать + вставить, 'git format-patch' | 'git imap-send' и т.д.), но вы должны вручную вставлять разрывы строк в любой вводимый текст.

В качестве дополнительной функции дополнение может обнаруживать текст патча в редакторе и предупреждать, когда перенос строк ещё не отключён.

Дополнение требует нескольких настроек расширенной конфигурации (about:config). Они перечислены на странице загрузки.

Подход №2 (конфигурация)
^^^^^^^^^^^^^^^^^^^^^^^^
Три шага:

1. Настройте составление почты как обычный текст: Правка...Настройки учётной записи...Составление и адресация, снимите флажок "Составлять сообщения в HTML".

2. Настройте ваше общее окно составления так, чтобы оно не переносило строки.
+
В Thunderbird 2: Правка..Настройки..Составление, переносить сообщения в обычном тексте на 0
+
В Thunderbird 3: Правка..Настройки..Дополнительно..Редактор конфигурации. Найдите "mail.wrap_long_lines". Переключите его, чтобы убедиться, что он установлен в `false`. Также найдите "mailnews.wraplength" и установите значение 0.

3. Отключите использование format=flowed: Правка..Настройки..Дополнительно..Редактор конфигурации. Найдите "mailnews.send_plaintext_flowed". Переключите его, чтобы убедиться, что он установлен в `false`.

После этого вы сможете составлять письма как обычно (вырезать + вставить, 'git format-patch' | 'git imap-send' и т.д.), и патчи не будут искажены.

Подход №3 (внешний редактор)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Требуются следующие расширения Thunderbird: AboutConfig с https://mjg.github.io/AboutConfig/ и External Editor с https://globs.org/articles.php?lng=en&pg=8

1. Подготовьте патч в виде текстового файла, используя выбранный вами метод.

2. Перед открытием окна составления используйте Правка->Настройки учётной записи, чтобы снять флажок "Составлять сообщения в формате HTML" на панели "Составление и адресация" учётной записи, которая будет использоваться для отправки патча.

3. В главном окне Thunderbird 'до' открытия окна составления для патча используйте Инструменты->about:config, чтобы установить следующие значения:
+
----------
	mailnews.send_plaintext_flowed  => false
	mailnews.wraplength             => 0
----------

4. Откройте окно составления и нажмите значок внешнего редактора.

5. В окне внешнего редактора прочитайте файл патча и выйдите из редактора обычным способом.

Примечание: возможно, шаг 2 можно выполнить с помощью about:config и следующих настроек, но никто ещё не пробовал.

----------
	mail.html_compose                       => false
	mail.identity.default.compose_html      => false
	mail.identity.id?.compose_html          => false
----------

В contrib/thunderbird-patch-inline есть сценарий, который может помочь вам легко включать патчи с помощью Thunderbird. Чтобы использовать его, выполните описанные выше действия, а затем используйте сценарий в качестве внешнего редактора.

KMail
~~~~~
Это должно помочь вам отправлять патчи в виде встроенного текста с помощью KMail.

1. Подготовьте патч в виде текстового файла.

2. Нажмите на Новое письмо.

3. Перейдите в "Параметры" в окне редактора и убедитесь, что "Перенос по словам" не установлен.

4. Используйте Сообщение -> Вставить файл... и вставьте патч.

5. Вернитесь в окно составления: добавьте любой другой текст, который хотите, в сообщение, заполните поля адресации и темы и нажмите отправить.

ИНФОРМАЦИЯ О БАЗОВОМ ДЕРЕВЕ
---------------------------

Блок информации о базовом дереве используется сопровождающими или сторонними тестировщиками, чтобы узнать точное состояние, к которому применяется серия патчей. Он состоит из 'базового коммита', который является широко известным коммитом, являющимся частью стабильной части истории проекта, от которой отталкиваются все остальные, и нуля или более 'предварительных патчей', которые представляют собой широко известные патчи в обработке, ещё не являющиеся частью 'базового коммита', которые необходимо применить поверх 'базового коммита' в топологическом порядке, прежде чем могут быть применены патчи.

'Базовый коммит' показывается как "base-commit: " с последующим 40-шестнадцатеричным именем объекта коммита. 'Предварительный патч' показывается как "prerequisite-patch-id: " с последующим 40-шестнадцатеричным 'id патча', который можно получить, передав патч через команду `git patch-id --stable`.

Представьте, что поверх общедоступного коммита P вы применили широко известные патчи X, Y и Z от кого-то другого, а затем создали свою серию из трёх патчей A, B, C, история будет выглядеть так:

................................................
---P---X---Y---Z---A---B---C
................................................

С помощью `git format-patch --base=P -3 C` (или его вариантов, например, с `--cover-letter` или с использованием `Z..C` вместо `-3 C` для указания диапазона), блок информации о базовом дереве показывается в конце первого сообщения, которое выводит команда (либо первый патч, либо сопроводительное письмо), например:

------------
base-commit: P
prerequisite-patch-id: X
prerequisite-patch-id: Y
prerequisite-patch-id: Z
------------

Для нелинейной топологии, такой как

................................................
---P---X---A---M---C
    \         /
     Y---Z---B
................................................

Вы также можете использовать `git format-patch --base=P -3 C` для создания патчей для A, B и C, а идентификаторы для P, X, Y, Z добавляются в конец первого сообщения.

Если в командной строке указан `--base=auto`, он автоматически вычислит базовый коммит как основу слияния коммита-верхушки отслеживаемой внешней ветки и диапазона редакций, указанного в командной строке. Для локальной ветки вам нужно настроить её на отслеживание внешней ветки с помощью `git branch --set-upstream-to` перед использованием этого параметра.

ПРИМЕРЫ
-------

* Извлечь коммиты между редакциями R1 и R2 и применить их поверх текущей ветки с помощью 'git am', чтобы скопировать их:
+
------------
$ git format-patch -k --stdout R1..R2 | git am -3 -k
------------

* Извлечь все коммиты, которые находятся в текущей ветке, но не в ветке origin:
+
------------
$ git format-patch origin
------------
+
Для каждого коммита в текущем каталоге создаётся отдельный файл.

* Извлечь все коммиты, которые ведут к 'origin' с момента создания проекта:
+
------------
$ git format-patch --root origin
------------

* То же самое, что и предыдущее:
+
------------
$ git format-patch -M -B origin
------------
+
Кроме того, он интеллектуально обнаруживает и обрабатывает переименования и полные переписывания для создания патча переименования. Патч переименования уменьшает объём текстового вывода и в целом упрощает проверку. Обратите внимание, что программы "patch" не из Git не понимают патчи переименования, поэтому используйте это только когда вы знаете, что получатель использует Git для применения вашего патча.

* Извлечь три верхних коммита из текущей ветки и отформатировать их как патчи, готовые к отправке по электронной почте:
+
------------
$ git format-patch -3
------------

ПРЕДУПРЕЖДЕНИЯ
--------------

Обратите внимание, что `format-patch` будет опускать коммиты слияния из вывода, даже если они являются частью запрошенного диапазона. Простой "патч" не содержит достаточно информации для того, чтобы принимающая сторона могла воспроизвести тот же самый коммит слияния.

СМ. ТАКЖЕ
---------
linkgit:git-am[1], linkgit:git-send-email[1]

GIT
---
Является частью пакета linkgit:git[1]
