git-show(1)
===========

НАЗВАНИЕ
--------
git-show - Показ различных типов объектов


ОБЗОР
-----
[synopsis]
git show [<параметры>] [<объект>...]

ОПИСАНИЕ
--------
Показывает один или несколько объектов (blob-объекты, деревья, метки и коммиты).

Для коммитов показывает сообщение журнала и текстовую разницу. Также представляет коммит слияния в специальном формате, создаваемом `git diff-tree --cc`.

Для меток показывает сообщение метки и объекты, на которые она ссылается.

Для деревьев показывает имена (эквивалентно `git ls-tree` с `--name-only`).

Для обычных blob-объектов показывает обычное содержимое.

Некоторые параметры, которые понимает команда `git log`, можно использовать для управления тем, как показываются изменения, вносимые коммитом.

Эта справочная страница описывает только наиболее часто используемые параметры.


ПАРАМЕТРЫ
---------
`<объект>...`::
	Имена объектов для показа (по умолчанию `HEAD`). Более полный список способов указания имён объектов см. в разделе «УКАЗАНИЕ РЕВИЗИЙ» в linkgit:gitrevisions[7].

include::pretty-options.adoc[]


include::pretty-formats.adoc[]


ФОРМАТИРОВАНИЕ РАЗНИЦ
---------------------
Параметры ниже можно использовать для изменения способа генерации вывода diff командой `git show`.

:git-log: 1
:diff-merges-default: `dense-combined`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]


ПРИМЕРЫ
-------

`git show v1.0.0`::
	Показывает метку `v1.0.0` вместе с объектом, на который указывает метка.

`git show v1.0.0^{tree}`::
	Показывает дерево, на которое указывает метка `v1.0.0`.

`git show -s --format=%s v1.0.0^{commit}`::
	Показывает заголовок коммита, на который указывает метка `v1.0.0`.

`git show next~10:Documentation/README`::
	Показывает содержимое файла `Documentation/README` таким, каким оно было в 10-м последнем коммите ветки `next`.

`git show master:Makefile master:t/Makefile`::
	Объединяет содержимое указанных Makefile в голове ветки `master`.

ОБСУЖДЕНИЕ
----------

include::i18n.adoc[]

GIT
---
Является частью пакета linkgit:git[1]
