git-web{litdd}browse(1)
=======================

НАЗВАНИЕ
--------
git-web--browse — вспомогательный сценарий Git для запуска веб-браузера

ОБЗОР
-----
[verse]
'git web{litdd}browse' [<параметры>] (<URL>|<файл>)...

ОПИСАНИЕ
--------

Этот сценарий пытается, насколько это возможно, отображать URL-адреса и ФАЙЛЫ, переданные в качестве аргументов, в виде HTML-страниц в новых вкладках уже открытого веб-браузера.

В настоящее время поддерживаются следующие браузеры (или команды):

* firefox (это значение по умолчанию в X Window, когда не используется KDE)
* iceweasel
* seamonkey
* iceape
* chromium (также поддерживается как chromium-browser)
* google-chrome (также поддерживается как chrome)
* konqueror (это значение по умолчанию в KDE, см. 'Примечание о konqueror' ниже)
* opera
* w3m (это значение по умолчанию вне графических сред)
* elinks
* links
* lynx
* dillo
* open (это значение по умолчанию в Mac OS X GUI)
* start (это значение по умолчанию в MinGW)
* cygstart (это значение по умолчанию в Cygwin)
* xdg-open

Также могут быть указаны пользовательские команды.

ПАРАМЕТРЫ
---------
-b <браузер>::
--browser=<браузер>::
	Использовать указанный браузер. Он должен быть в списке поддерживаемых браузеров.

-t <браузер>::
--tool=<браузер>::
	То же, что и предыдущее.

-c <переменная-конфигурации>::
--config=<conf.var>::
	ПЕРЕМЕННАЯ-КОНФИГУРАЦИИ ищется в файлах конфигурации Git. Если она установлена, то её значение указывает браузер, который должен использоваться.

ПЕРЕМЕННЫЕ КОНФИГУРАЦИИ
-----------------------

ПЕРЕМЕННАЯ-КОНФИГУРАЦИИ (из параметра -c) и web.browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Веб-браузер может быть указан с помощью переменной конфигурации, переданной с параметром командной строки -c (или --config), или переменной конфигурации `web.browser`, если первая не используется.

browser.<инструмент>.path
~~~~~~~~~~~~~~~~~~~~~~~~~

Вы можете явно указать полный путь к вашему предпочтительному браузеру, установив переменную конфигурации `browser.<инструмент>.path`. Например, вы можете настроить абсолютный путь к firefox, установив 'browser.firefox.path'. В противном случае 'git web{litdd}browse' предполагает, что инструмент доступен в PATH.

browser.<инструмент>.cmd
~~~~~~~~~~~~~~~~~~~~~~~~

Когда браузер, указанный параметрами или переменными конфигурации, не находится среди поддерживаемых, будет выполняться поиск соответствующей переменной конфигурации `browser.<инструмент>.cmd`. Если эта переменная существует, то 'git web{litdd}browse' будет рассматривать указанный инструмент как пользовательскую команду и будет использовать eval оболочки для выполнения команды с переданными URL-адресами в качестве аргументов.

ПРИМЕЧАНИЕ О KONQUEROR
----------------------

Когда 'konqueror' указан параметром командной строки или переменной конфигурации, мы запускаем 'kfmclient', чтобы попытаться открыть HTML-страницу руководства в уже открытом konqueror в новой вкладке, если это возможно.

Для согласованности мы также пытаемся использовать такой трюк, если 'browser.konqueror.path' установлен во что-то вроде `ПУТЬ_К/konqueror`. Это означает, что вместо этого мы попытаемся запустить `ПУТЬ_К/kfmclient`.

Если вы действительно хотите использовать 'konqueror', вы можете использовать что-то вроде следующего:

------------------------------------------------
	[web]
		browser = konq

	[browser "konq"]
		cmd = ПУТЬ_К/konqueror
------------------------------------------------

Примечание о git-config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Обратите внимание, что эти переменные конфигурации, вероятно, следует устанавливать с помощью флага `--global`, например, так:

------------------------------------------------
$ git config --global web.browser firefox
------------------------------------------------

поскольку они, вероятно, более специфичны для пользователя, чем для репозитория. Дополнительную информацию об этом см. в linkgit:git-config[1].

GIT
---
Является частью пакета linkgit:git[1]
