git-config(1)
=============

НАЗВАНИЕ
--------
git-config — Получение и установка опций репозитория или глобальных опций


ОБЗОР
-----
[verse]
'git config list' [<параметр-файла>] [<параметр-отображения>] [--includes]
'git config get' [<параметр-файла>] [<параметр-отображения>] [--includes] [--all] [--regexp] [--value=<шаблон>] [--fixed-value] [--default=<значение-по-умолчанию>] [--url=<url>] <имя>
'git config set' [<параметр-файла>] [--type=<тип>] [--all] [--value=<шаблон>] [--fixed-value] <имя> <значение>
'git config unset' [<параметр-файла>] [--all] [--value=<шаблон>] [--fixed-value] <имя>
'git config rename-section' [<параметр-файла>] <старое-имя> <новое-имя>
'git config remove-section' [<параметр-файла>] <имя>
'git config edit' [<параметр-файла>]
'git config' [<параметр-файла>] --get-colorbool <имя> [<stdout-это-tty>]

ОПИСАНИЕ
--------
Вы можете использовать эту команду для проверки/установки/замены значений параметров. Имя секции и ключа разделены точкой, и значение будет скрыто.

Несколько строк могут быть добавлены к параметру с помощью параметра `--append`. Если вы хотите обновить или снять параметр, который может встречаться в нескольких строках, необходимо указать `--value=<шаблон>` (который является расширенным регулярным выражением, если только не указан параметр `--fixed-value`). Только существующие значения, соответствующие шаблону, обновляются или снимаются. Если вы хотите обрабатывать строки, которые *не* соответствуют шаблону, просто добавьте один восклицательный знак в начале (см. также <<EXAMPLES>>), но обратите внимание, что это работает только тогда, когда параметр `--fixed-value` не используется.

Параметр `--type=<тип>` указывает 'git config' гарантировать, что входящие и исходящие значения могут быть канонизированы в соответствии с указанным <типом>. Если `--type=<тип>` не указан, канонизация выполняться не будет. Вызывающие могут снять существующий спецификатор `--type` с помощью `--no-type`.

При чтении значения по умолчанию читаются из системных, глобальных и локальных для репозитория файлов конфигурации, а параметры `--system`, `--global`, `--local`, `--worktree` и `--file <имя-файла>` можно использовать, чтобы указать команде читать только из этого местоположения (см. <<FILES>>).

При записи новое значение по умолчанию записывается в локальный для репозитория файл конфигурации, а параметры `--system`, `--global`, `--worktree`, `--file <имя-файла>` можно использовать, чтобы указать команде записывать в это местоположение (вы можете указать `--local`, но это значение по умолчанию).

Эта команда завершится с ненулевым статусом при ошибке. Некоторые коды выхода:

- Раздел или ключ недействительны (ret=1),
- не указан раздел или имя (ret=2),
- файл конфигурации недействителен (ret=3),
- файл конфигурации не может быть записан (ret=4),
- вы пытаетесь снять параметр, который не существует (ret=5),
- вы пытаетесь снять/установить параметр, для которого совпадает несколько строк (ret=5), или
- вы пытаетесь использовать недопустимое регулярное выражение (ret=6).

В случае успеха команда возвращает код выхода 0.

Список всех доступных переменных конфигурации можно получить с помощью команды `git help --config`.

КОМАНДЫ
-------

list::
	Перечислить все переменные и их значения, установленные в конфигурационном файле.

get::
	Выдаёт значение указанного ключа. Если ключ присутствует в конфигурации несколько раз, выдаёт последнее значение. Если указан `--all`, выдаёт все значения, связанные с ключом. Возвращает код ошибки 1, если ключ отсутствует.

set::
	Устанавливает значение для одного или нескольких параметров конфигурации. По умолчанию эта команда отказывается записывать многозначные параметры конфигурации. Передача `--all` заменит все многозначные параметры конфигурации на новое значение, тогда как `--value=` заменит все параметры конфигурации, значения которых соответствуют указанному шаблону.

unset::
	Снимает значение для одного или нескольких параметров конфигурации. По умолчанию эта команда отказывается снимать многозначные ключи. Передача `--all` снимет все многозначные параметры конфигурации, тогда как `--value` снимет все параметры конфигурации, значения которых соответствуют указанному шаблону.

rename-section::
	Переименовать указанную секцию.

remove-section::
	Удалить из конфигурационного файла указанную секцию.

edit::
	Открывает редактор для изменения указанного файла конфигурации; `--system`, `--global`, `--local` (по умолчанию), `--worktree`, или `--file <файл-конфигурации>`.

[[OPTIONS]]
ПАРАМЕТРЫ
---------

--replace-all::
	Поведение по умолчанию — замена не более одной строки. Это заменяет все строки, соответствующие ключу (и, опционально, `--value=<шаблон>`).

--append::
	Добавляет новую строку к параметру без изменения существующих значений. Это то же самое, что указать '--value=^$' в `set`.

--comment <сообщение>::
	Добавляет комментарий в конец новых или изменённых строк.
+
Если _<сообщение>_ начинается с одного или нескольких пробелов, за которыми следует "#", оно используется как есть. Если оно начинается с "#", перед его использованием добавляется пробел. В противном случае к нему добавляется строка " # " (пробел, за которым следует решётка, за которой следует пробел). И результирующая строка помещается сразу после значения, определённого для переменной. _<сообщение>_ не должно содержать символов перевода строки (многострочные комментарии не разрешены).

--all::
	С `get` возвращает все значения для многозначного ключа.

--regexp::
	С `get` интерпретирует имя как регулярное выражение. Сопоставление с регулярным выражением в настоящее время чувствительно к регистру и выполняется против канонизированной версии ключа, в которой имена разделов и переменных приводятся к нижнему регистру, а имена подразделов — нет.

--url=<URL>::
	Когда указано двухкомпонентное <имя> как <раздел>.<ключ>, возвращается значение для <раздел>.<URL>.<ключ>, чья часть <URL> лучше всего соответствует данному URL (если такого ключа не существует, значение для <раздел>.<ключ> используется как резервное). Когда указан только <раздел> в качестве имени, сделать это для всех ключей в разделе и перечислить их. Возвращает код ошибки 1, если значение не найдено.

--global::
	Для записи параметров: записывать в глобальный файл `~/.gitconfig`, а не в `.git/config` репозитория, записывать в файл `$XDG_CONFIG_HOME/git/config`, если этот файл существует, а файл `~/.gitconfig` не существует.
+
Для чтения параметров: читать только из глобального `~/.gitconfig` и из `$XDG_CONFIG_HOME/git/config`, а не из всех доступных файлов.
+
См. также <<FILES>>.

--system::
	Для записи параметров: записывать в общесистемный `$(prefix)/etc/gitconfig`, а не в `.git/config` репозитория.
+
Для чтения параметров: читать только из общесистемного `$(prefix)/etc/gitconfig`, а не из всех доступных файлов.
+
См. также <<FILES>>.

--local::
	Для записи параметров: записывать в файл `.git/config` репозитория. Это поведение по умолчанию.
+
Для чтения параметров: читать только из `.git/config` репозитория, а не из всех доступных файлов.
+
См. также <<FILES>>.

--worktree::
	Аналогично `--local`, за исключением того, что `$GIT_DIR/config.worktree` читается или записывается, если включён `extensions.worktreeConfig`. Если не включён, то это то же самое, что `--local`. Обратите внимание, что `$GIT_DIR` равен `$GIT_COMMON_DIR` для основного рабочего каталога, но имеет вид `$GIT_DIR/worktrees/<id>/` для других рабочих каталогов. Чтобы узнать, как включить `extensions.worktreeConfig`, см. linkgit:git-worktree[1].

-f <файл-конфигурации>::
--file <файл-конфигурации>::
	Для записи параметров: записывать в указанный файл, а не в `.git/config` репозитория.
+
Для чтения параметров: читать только из указанного файла, а не из всех доступных файлов.
+
См. также <<FILES>>.

--blob <blob-объект>::
	Аналогично `--file`, но использовать указанный blob-объект вместо файла. Например, вы можете использовать 'master:.gitmodules', чтобы читать значения из файла '.gitmodules' в ветке master. Более полный список способов написания имён blob-объектов см. в разделе "ЗАДАНИЕ РЕВИЗИЙ" в linkgit:gitrevisions[7].

`--value=<шаблон>`::
`--no-value`::
	С `get`, `set` и `unset` сопоставлять только с _<шаблон>_. Шаблон является расширенным регулярным выражением, если только не указан `--fixed-value`.
+
Используйте `--no-value`, чтобы снять _<шаблон>_.

--fixed-value::
	При использовании с `--value=<шаблон>` обрабатывать _<шаблон>_ как точную строку вместо регулярного выражения. Это ограничит сопоставляемые пары имя/значение только теми, где значение точно равно _<шаблон>_.

--type <тип>::
  'git config' гарантирует, что любой ввод или вывод действителен в соответствии с заданными ограничениями типа, и будет канонизировать исходящие значения в канонической форме `<типа>`.
+
Допустимыми `<тип>`ами являются:
+
- 'bool': канонизировать значения `true`, `yes`, `on` и положительные числа как "true", а значения `false`, `no`, `off` и `0` как "false".
- 'int': канонизировать значения как простые десятичные числа. Необязательный суффикс 'k', 'm' или 'g' приведёт к умножению значения на 1024, 1048576 или 1073741824 при вводе.
- 'bool-or-int': канонизировать в соответствии с 'bool' или 'int', как описано выше.
- 'path': канонизировать путём раскрытия начального `~` в значение `$HOME` и `~user` в домашний каталог для указанного пользователя. Этот спецификатор не имеет эффекта при установке значения (но вы можете использовать `git config раздел.переменная ~/` из командной строки, чтобы ваша оболочка выполнила раскрытие.)
- 'expiry-date': канонизировать путём преобразования из фиксированной или относительной строки даты в метку времени. Этот спецификатор не имеет эффекта при установке значения.
- 'color': При получении значения канонизировать путём преобразования в escape-последовательность цвета ANSI. При установке значения выполняется проверка работоспособности, чтобы убедиться, что данное значение может быть канонизировано как цвет ANSI, но оно записывается как есть.
+

--bool::
--int::
--bool-or-int::
--path::
--expiry-date::
  Исторические параметры для выбора спецификатора типа. Вместо этого предпочтительнее использовать `--type` (см. выше).

--no-type::
  Снимает ранее установленный спецификатор типа (если он был установлен ранее). Этот параметр требует, чтобы 'git config' не канонизировал полученную переменную. `--no-type` не имеет эффекта без `--type=<тип>` или `--<тип>`.

-z::
--null::
	Для всех параметров, которые выводят значения и/или ключи, всегда завершать значения нулевым символом (вместо новой строки). Использовать новую строку в качестве разделителя между ключом и значением. Это позволяет безопасно анализировать вывод, не путаясь, например, из-за значений, содержащих разрывы строк.

--name-only::
	Выводить только имена переменных конфигурации для `list` или `get`.

`--show-names`::
`--no-show-names`::
	С `get` показывать ключи конфигурации в дополнение к их значениям. По умолчанию используется `--no-show-names`, если только не указан `--url` и в _<имя>_ нет подразделов.

--show-origin::
	Дополняет вывод всех запрошенных параметров конфигурации типом источника (файл, стандартный ввод, blob-объект, командная строка) и фактическим источником (путь к файлу конфигурации, ссылка или идентификатор blob-объекта, если применимо).

--show-scope::
	Аналогично `--show-origin` тем, что дополняет вывод всех запрошенных параметров конфигурации областью действия этого значения (рабочий каталог, локальный, глобальный, системный, команда).

--get-colorbool <имя> [<stdout-это-tty>]::

	Находит настройку цвета для `<имя>` (например, `color.diff`) и выводит "true" или "false". `<stdout-это-tty>` должно быть либо "true", либо "false" и учитывается, когда в конфигурации указано "auto". Если `<stdout-это-tty>` отсутствует, то проверяет стандартный вывод самой команды и завершается со статусом 0, если цвет должен использоваться, или со статусом 1 в противном случае. Когда настройка цвета для `имя` не определена, команда использует `color.ui` в качестве резервного варианта.

--includes::
--no-includes::
	Соблюдать директивы `include.*` в файлах конфигурации при поиске значений. По умолчанию `off`, когда указан конкретный файл (например, с помощью `--file`, `--global` и т.д.), и `on` при поиске во всех файлах конфигурации.

--default <значение>::
  При использовании `get`, если запрошенная переменная не найдена, вести себя так, как если бы <значение> было значением, присвоенным этой переменной.

УСТАРЕВШИЕ РЕЖИМЫ
-----------------

Следующие режимы устарели в пользу подкоманд. Рекомендуется перейти на новый синтаксис.

'git config <имя>'::
	Заменено на `git config get <имя>`.

'git config <имя> <значение> [<шаблон-значения>]'::
	Заменено на `git config set [--value=<шаблон>] <имя> <значение>`.

-l::
--list::
	Заменено на `git config list`.

--get <имя> [<шаблон-значения>]::
	Заменено на `git config get [--value=<шаблон>] <имя>`.

--get-all <имя> [<шаблон-значения>]::
	Заменено на `git config get [--value=<шаблон>] --all <имя>`.

--get-regexp <регулярное-выражение-имени>::
	Заменено на `git config get --all --show-names --regexp <регулярное-выражение-имени>`.

--get-urlmatch <имя> <URL>::
	Заменено на `git config get --all --show-names --url=<URL> <имя>`.

--get-color <имя> [<значение-по-умолчанию>]::
	Заменено на `git config get --type=color [--default=<значение-по-умолчанию>] <имя>`.

--add <имя> <значение>::
	Заменено на `git config set --append <имя> <значение>`.

--unset <имя> [<шаблон-значения>]::
	Заменено на `git config unset [--value=<шаблон>] <имя>`.

--unset-all <имя> [<шаблон-значения>]::
	Заменено на `git config unset [--value=<шаблон>] --all <имя>`.

--rename-section <старое-имя> <новое-имя>::
	Заменено на `git config rename-section <старое-имя> <новое-имя>`.

--remove-section <имя>::
	Заменено на `git config remove-section <имя>`.

-e::
--edit::
	Заменено на `git config edit`.

КОНФИГУРАЦИЯ
------------
`pager.config` учитывается только при выводе списка конфигурации, т.е. при использовании `list` или `get`, которые могут возвращать несколько результатов. По умолчанию используется пейджер.

[[FILES]]
ФАЙЛЫ
-----

По умолчанию 'git config' читает параметры конфигурации из нескольких файлов:

$(prefix)/etc/gitconfig::
	Системный файл конфигурации.

$XDG_CONFIG_HOME/git/config::
~/.gitconfig::
	Пользовательские файлы конфигурации. Когда переменная среды XDG_CONFIG_HOME не установлена или пуста, $HOME/.config/ используется как $XDG_CONFIG_HOME.
+
Они также называются «глобальными» файлами конфигурации. Если оба файла существуют, оба файла читаются в порядке, указанном выше.

$GIT_DIR/config::
	Файл конфигурации, специфичный для репозитория.

$GIT_DIR/config.worktree::
	Это необязательно и используется только тогда, когда `extensions.worktreeConfig` присутствует в $GIT_DIR/config.

Вы также можете предоставить дополнительные параметры конфигурации при запуске любой команды git, используя параметр `-c`. Подробности см. в linkgit:git[1].

Параметры будут читаться из всех доступных файлов. Если глобальные или общесистемные файлы конфигурации отсутствуют или нечитаемы, они будут проигнорированы. Если файл конфигурации репозитория отсутствует или нечитаем, 'git config' завершится с ненулевым кодом ошибки. Сообщение об ошибке выдаётся, если файл нечитаем, но не если он отсутствует.

Файлы читаются в порядке, указанном выше, причём последнее найденное значение имеет приоритет над значениями, прочитанными ранее. Когда берутся несколько значений, используются все значения ключа из всех файлов.

По умолчанию параметры записываются только в файл конфигурации, специфичный для репозитория. Обратите внимание, что это также влияет на такие параметры, как `set` и `unset`. *'git config' всегда изменяет только один файл за раз*.

Вы можете ограничить, какие источники конфигурации читаются или в которые записываются, указав путь к файлу с помощью параметра `--file` или указав область действия конфигурации с помощью `--system`, `--global`, `--local` или `--worktree`. Подробнее см. <<OPTIONS>> выше.

[[SCOPES]]
ОБЛАСТИ ДЕЙСТВИЯ
----------------

Каждый источник конфигурации попадает в определённую область действия конфигурации. Области действия:

система::
	$(prefix)/etc/gitconfig

глобально::
	$XDG_CONFIG_HOME/git/config
+
~/.gitconfig

локально::
	$GIT_DIR/config

рабочая копия (worktree)::
	$GIT_DIR/config.worktree

команда::
	Переменные среды GIT_CONFIG_{COUNT,KEY,VALUE} (см. <<ENVIRONMENT>> ниже)
+
параметр `-c`

За исключением 'command', каждая область действия соответствует параметру командной строки: `--system`, `--global`, `--local`, `--worktree`.

При чтении параметров указание области действия приведёт к чтению параметров только из файлов в этой области действия. При записи параметров указание области действия приведёт к записи в файлы в этой области действия (вместо файла конфигурации, специфичного для репозитория). Полное описание см. в <<OPTIONS>> выше.

Большинство параметров конфигурации учитываются независимо от области действия, в которой они определены, но некоторые параметры учитываются только в определённых областях действия. Полные сведения см. в документации по соответствующему параметру.

Защищённая конфигурация
~~~~~~~~~~~~~~~~~~~~~~~

Защищённая конфигурация относится к областям действия 'system', 'global' и 'command'. По соображениям безопасности некоторые параметры учитываются только тогда, когда они указаны в защищённой конфигурации, и игнорируются в противном случае.

Git рассматривает эти области действия как контролируемые пользователем или доверенным администратором. Это связано с тем, что злоумышленник, контролирующий эти области, может нанести значительный вред без использования Git, поэтому предполагается, что среда пользователя защищает эти области от злоумышленников.

[[ENVIRONMENT]]
ОКРУЖЕНИЕ
---------

GIT_CONFIG_GLOBAL::
GIT_CONFIG_SYSTEM::
	Брать конфигурацию из указанных файлов вместо глобальной или системной конфигурации. Подробности см. в linkgit:git[1].

GIT_CONFIG_NOSYSTEM::
	Следует ли пропускать чтение настроек из общесистемного файла $(prefix)/etc/gitconfig. Подробности см. в linkgit:git[1].

См. также <<FILES>>.

GIT_CONFIG_COUNT::
GIT_CONFIG_KEY_<n>::
GIT_CONFIG_VALUE_<n>::
	Если GIT_CONFIG_COUNT установлен в положительное число, все пары среды GIT_CONFIG_KEY_<n> и GIT_CONFIG_VALUE_<n> до этого числа будут добавлены в конфигурацию времени выполнения процесса. Пары конфигурации индексируются с нуля. Любой отсутствующий ключ или значение рассматривается как ошибка. Пустой GIT_CONFIG_COUNT обрабатывается так же, как GIT_CONFIG_COUNT=0, то есть никакие пары не обрабатываются. Эти переменные среды будут переопределять значения в файлах конфигурации, но сами будут переопределены любыми явными параметрами, переданными через `git -c`.
+
Это полезно в случаях, когда вы хотите породить несколько команд git с общей конфигурацией, но не можете полагаться на файл конфигурации, например, при написании сценариев.

GIT_CONFIG::
	Если параметр `--file` не предоставлен `git config`, использовать файл, заданный `GIT_CONFIG`, как если бы он был предоставлен через `--file`. Эта переменная не влияет на другие команды Git и в основном предназначена для исторической совместимости; обычно нет причин использовать её вместо параметра `--file`.

[[EXAMPLES]]
ПРИМЕРЫ
-------

Дан файл .git/config, подобный этому:

------------
#
# Это файл конфигурации, и
# символ '#' или ';' обозначает
# комментарий
#

; основные переменные
[core]
	; Не доверять режимам файлов
	filemode = false

; Наш алгоритм сравнения
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

; Настройки прокси
[core]
	gitproxy=proxy-command for kernel.org
	gitproxy=default-proxy ; для всех остальных

; HTTP
[http]
	sslVerify
[http "https://weak.example.com"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
------------

вы можете установить filemode в true с помощью

------------
% git config set core.filemode true
------------

Гипотетические записи команды прокси на самом деле имеют постфикс, чтобы различать, к какому URL они применяются. Вот как изменить запись для kernel.org на "ssh".

------------
% git config set --value='for kernel.org$' core.gitproxy '"ssh" for kernel.org'
------------

Это гарантирует, что заменяется только пара ключ/значение для kernel.org.

Чтобы удалить запись для renames, выполните

------------
% git config unset diff.renames
------------

Если вы хотите удалить запись для многозначной переменной (например, core.gitproxy выше), вы должны предоставить регулярное выражение, соответствующее значению ровно одной строки.

Чтобы запросить значение для данного ключа, выполните

------------
% git config get core.filemode
------------

или, чтобы запросить многозначную переменную:

------------
% git config get --value="for kernel.org$" core.gitproxy
------------

Если вы хотите узнать все значения для многозначной переменной, выполните:

------------
% git config get --all --show-names core.gitproxy
------------

Если вы любите жить опасно, вы можете заменить *все* core.gitproxy новым с помощью

------------
% git config set --all core.gitproxy ssh
------------

Однако, если вы действительно хотите заменить только строку для прокси по умолчанию, т.е. ту, у которой нет постфикса "for ...", сделайте что-то вроде этого:

------------
% git config set --value='! for ' core.gitproxy ssh
------------

Чтобы действительно сопоставлять только значения с восклицательным знаком, вы должны

------------
% git config set --value='[!]' раздел.ключ значение
------------

Чтобы добавить новый прокси, не изменяя ни одного из существующих, используйте

------------
% git config set --append core.gitproxy '"proxy-command" for example.com'
------------

Пример использования пользовательского цвета из конфигурации в вашем сценарии:

------------
#!/bin/sh
WS=$(git config get --type=color --default="blue reverse" color.diff.whitespace)
RESET=$(git config get --type=color --default="reset" "")
echo "${WS}ваш цвет пробелов или синий обратный${RESET}"
------------

Для URL-адресов в `https://weak.example.com` `http.sslVerify` установлен в false, в то время как для всех остальных он установлен в `true`:

------------
% git config get --type=bool --url=https://good.example.com http.sslverify
true
% git config get --type=bool --url=https://weak.example.com http.sslverify
false
% git config get --url=https://weak.example.com http
http.cookieFile /tmp/cookie.txt
http.sslverify false
------------

include::config.adoc[]

ОШИБКИ
------
При использовании устаревшего синтаксиса `[раздел.подраздел]` изменение значения приведёт к добавлению многострочного ключа вместо изменения, если подраздел указан хотя бы с одним символом в верхнем регистре. Например, когда конфигурация выглядит так

--------
  [раздел.подраздел]
    key = value1
--------

и выполнение `git config раздел.Подраздел.key value2` приведёт к

--------
  [раздел.подраздел]
    key = value1
    key = value2
--------


GIT
---
Является частью пакета linkgit:git[1]
