git-http-fetch(1)
=================

НАЗВАНИЕ
--------
git-http-fetch — загрузка из внешнего репозитория Git через HTTP


ОБЗОР
-----
[verse]
'git http-fetch' [-c] [-t] [-a] [-d] [-v] [-w <имя-файла>] [--recover] [--stdin | --packfile=<хеш> | <коммит>] <URL>

ОПИСАНИЕ
--------
Загружает из внешнего репозитория Git с помощью HTTP.

Эта команда всегда получает все объекты. Исторически существовало три параметра `-a`, `-c` и `-t` для выбора, какие объекты загружать. Сейчас они молча игнорируются.

ПАРАМЕТРЫ
---------
commit-id::
        Либо хеш, либо имя файла в [URL]/refs/ для получения.

-a::
-c::
-t::
	Эти параметры игнорируются по историческим причинам.

-v::
	Сообщать, что загружается.

-w <имя-файла>::
Записывает id коммита в указанное имя файла в $GIT_DIR/refs/<имя-файла> на локальной стороне после завершения передачи.

--stdin::
	Вместо id коммита в командной строке (который в этом случае не ожидается), 'git http-fetch' ожидает строки в stdin в формате

		<commit-id>['\t'<filename-as-in--w>]

--packfile=<хеш>::
	Только для внутреннего использования. Вместо id коммита в командной строке (который в этом случае не ожидается), 'git http-fetch' получает pack-файл непосредственно по указанному URL и использует index-pack для создания соответствующих файлов .idx и .keep. Хеш используется для определения имени временного файла и является произвольным. Вывод index-pack выводится в stdout. Требует --index-pack-args.

--index-pack-args=<аргументы>::
	Только для внутреннего использования. Команда для выполнения над содержимым загруженного пакета. Аргументы кодируются в URL и разделяются пробелами.

--recover::
	Проверить, что всё достижимое из целевого объекта получено. Используется после прерывания предыдущего получения.

GIT
---
Является частью пакета linkgit:git[1]
