git-request-pull(1)
===================

НАЗВАНИЕ
--------
git-request-pull - Генерирует сводку ожидающих изменений

ОБЗОР
-----
[verse]
'git request-pull' [-p] <начало> <URL> [<конец>]

ОПИСАНИЕ
--------

Сгенерировать запрос с просьбой к вашему вышестоящему (upstream) проекту извлечь (pull) изменения в их дерево. Запрос, выводимый в стандартный вывод, начинается с описания ветки, содержит сводку изменений и указывает, откуда их можно извлечь.

Ожидается, что в вышестоящем (upstream) проекте есть коммит, указанный `<начало>`, и вывод просит его интегрировать изменения, сделанные вами с того коммита вплоть до коммита, указанного `<конец>`, обратившись к репозиторию, указанному `<URL>`.


ПАРАМЕТРЫ
---------
-p::
	Включить текст изменения (патча) в вывод.

<start>::
	Коммит, с которого начать. Указывает на коммит, который уже есть в вышестоящей (upstream) истории.

<URL>::
	URL-адрес репозитория, из которого следует извлечь (pull) изменения.

<end>::
	Коммит, которым закончить (по умолчанию HEAD). Указывает на коммит, находящийся на верхушке (tip) истории, которую вы просите извлечь.
+
Если в репозитории, указанном `<URL>`, коммит находится на верхушке ссылки, которая отличается от ссылки, имеющейся у вас локально, вы можете использовать синтаксис `<локальное>:<внешнее>`, указав её локальное имя, двоеточие `:` и её внешнее имя.


ПРИМЕРЫ
-------

Представьте, что вы построили свою работу в своей ветке `master` поверх выпуска `v1.0` и хотите, чтобы она была интегрирована в проект. Сначала вы отправляете это изменение в свой публичный репозиторий, чтобы другие могли его увидеть:

	git push https://git.ko.xz/project master

Затем вы выполняете эту команду:

	git request-pull v1.0 https://git.ko.xz/project master

что создаст запрос к вышестоящему (upstream) репозиторию с кратким описанием изменений между выпуском `v1.0` и вашей веткой `master`, чтобы извлечь (pull) их из вашего публичного репозитория.

Если вы отправили своё изменение в ветку, имя которой отличается от той, что у вас локально, например.

	git push https://git.ko.xz/project master:for-linus

тогда вы можете попросить извлечь это с помощью

	git request-pull v1.0 https://git.ko.xz/project master:for-linus


GIT
---
Является частью пакета linkgit:git[1]
