git-blame(1)
============

НАЗВАНИЕ
--------
git-blame — Показать, какая ревизия и какой автор последними изменили каждую строку файла

ОБЗОР
-----
[verse]
'git blame' [-c] [-b] [-l] [--root] [-t] [-f] [-n] [-s] [-e] [-p] [-w] [--incremental]
	    [-L <диапазон>] [-S <файл-редакций>] [-M] [-C] [-C] [-C] [--since=<дата>]
	    [--ignore-rev <ред>] [--ignore-revs-file <файл>]
	    [--color-lines] [--color-by-age] [--progress] [--abbrev=<число>]
	    [ --contents <файл> ] [<ред> | --reverse <ред>..<ред>] [--] <файл>

ОПИСАНИЕ
--------

Аннотирует каждую строку в указанном файле информацией из ревизии, которая последней изменила эту строку. При желании можно начать аннотирование с заданной ревизии.

При указании один или несколько раз `-L` ограничивает аннотацию запрошенными строками.

Происхождение строк автоматически отслеживается при переименованиях целых файлов (в настоящее время нет параметра для отключения отслеживания переименований). Чтобы отследить строки, перемещённые из одного файла в другой, или строки, скопированные и вставленные из другого файла и т.д., см. параметры `-C` и `-M`.

Отчёт не сообщает вам ничего о строках, которые были удалены или заменены; вам нужно использовать такой инструмент, как 'git diff' или интерфейс "pickaxe", кратко упомянутый в следующем абзаце.

Помимо поддержки аннотации файлов, Git также поддерживает поиск по истории разработки, чтобы узнать, когда фрагмент кода появился в изменении. Это позволяет отследить, когда фрагмент кода был добавлен в файл, перемещён или скопирован между файлами и в конечном итоге удалён или заменён. Это работает путём поиска текстовой строки в сравнении. Небольшой пример интерфейса pickaxe, который ищет `blame_usage`:

-----------------------------------------------------------------------------
$ git log --pretty=oneline -S'blame_usage'
5040f17eba15504bad66b14a645bddd9b015ebb7 blame -S <файл-родословной>
ea4c7f9bf69e781dd0cd88d2bccb2bf5cc15c9a7 git-blame: Make the output
-----------------------------------------------------------------------------

ПАРАМЕТРЫ
---------
include::blame-options.adoc[]

-c::
	Использовать тот же режим вывода, что и в linkgit:git-annotate[1] (По умолчанию: откл).

--score-debug::
	Включает отладочную информацию, связанную с перемещением строк между файлами (см. `-C`) и строк, перемещённых внутри файла (см. `-M`). Первое указанное число — это оценка. Это количество буквенно-цифровых символов, которые, как обнаружено, были перемещены между файлами или внутри них. Она должна превышать определённый порог, чтобы 'git blame' считал эти строки кода перемещёнными.

-f::
--show-name::
	Показывает имя файла в исходном коммите. По умолчанию имя файла показывается, если есть какая-либо строка, которая поступила из файла с другим именем из-за обнаружения переименования.

-n::
--show-number::
	Показывать номер строки в исходном коммите (по умолчанию: выкл).

-s::
	Подавлять имя автора и метку времени в выводе.

-e::
--show-email::
	Показывать адрес электронной почты автора вместо имени автора (по умолчанию: выкл). Это также можно контролировать с помощью параметра конфигурации `blame.showEmail`.

-w::
	Игнорировать пробелы при сравнении версии родителя и потомка, чтобы найти, откуда взялись строки.

include::diff-algorithm-option.adoc[]

--abbrev=<n>::
	Вместо использования 7+1 шестнадцатеричных цифр по умолчанию в качестве сокращённого имени объекта использовать <m>+1 цифр, где <m> не меньше <n>, но обеспечивает уникальность имён объектов коммитов. Обратите внимание, что 1 столбец используется для символа '^' для пометки граничного коммита.


ФОРМАТ ПО УМОЛЧАНИЮ
-------------------

Когда не указаны ни параметр `--porcelain`, ни `--incremental`, `git blame` будет выводить аннотацию для каждой строки с:

- сокращённое имя объекта для коммита, из которого пришла строка;
- идентификатор автора (по умолчанию имя автора и дата, если не указаны `-s` или `-e`); и
- номер строки

перед содержимым строки.

ФАРФОРОВЫЙ ФОРМАТ
-----------------

В этом формате каждая строка выводится после заголовка; заголовок как минимум содержит первую строку, которая имеет:

- 40-байтовый SHA-1 коммита, которому приписывается строка;
- номер строки в исходном файле;
- номер строки в конечном файле;
- в строке, которая начинает группу строк из другого коммита, отличного от предыдущего, количество строк в этой группе. В последующих строках это поле отсутствует.

За этой строкой заголовка следует следующая информация по крайней мере один раз для каждого коммита:

- имя автора ("author"), адрес электронной почты ("author-mail"), время ("author-time") и часовой пояс ("author-tz"); аналогично для коммиттера.
- имя файла в коммите, которому приписывается строка.
- первая строка сообщения журнала коммита («summary»).

Содержимое фактической строки выводится после вышеуказанного заголовка, перед ним ставится символ TAB. Это сделано для возможности добавления дополнительных элементов заголовка в будущем.

Фарфоровый формат обычно подавляет информацию о коммите, которая уже встречалась. Например, две строки, приписанные одному и тому же коммиту, будут показаны обе, но подробности этого коммита будут показаны только один раз. Информация, специфичная для отдельных строк, не будет сгруппирована вместе, например, редакции, помеченные как 'ignored' или 'unblamable'. Это более эффективно, но может потребовать сохранения большего состояния читателем. Параметр `--line-porcelain` можно использовать для вывода полной информации о коммите для каждой строки, что позволяет использовать более простое (но менее эффективное) использование, например:

	# подсчитать количество строк, приписанных каждому автору
	git blame --line-porcelain файл |
	sed -n 's/^author //p' |
	sort | uniq -c | sort -rn


УКАЗАНИЕ ДИАПАЗОНОВ
-------------------

В отличие от 'git blame' и 'git annotate' в старых версиях git, область аннотации может быть ограничена как диапазонами строк, так и диапазонами редакций. Параметр `-L`, который ограничивает аннотацию диапазоном строк, может быть указан несколько раз.

Если вас интересует происхождение строк 40-60 для файла `foo`, вы можете использовать параметр `-L` следующим образом (они означают одно и то же — оба запрашивают 21 строку, начиная со строки 40):

	git blame -L 40,60 foo
	git blame -L 40,+21 foo

Также вы можете использовать регулярное выражение для указания диапазона строк:

	git blame -L '/^sub hello {/,/^}$/' foo

что ограничивает аннотацию телом подпрограммы `hello`.

Если вас не интересуют изменения старше версии v2.6.18 или изменения старше 3 недель, вы можете использовать спецификаторы диапазона редакций, аналогичные 'git rev-list':

	git blame v2.6.18.. -- foo
	git blame --since=3.weeks -- foo

Когда для ограничения аннотации используются спецификаторы диапазона редакций, строки, которые не изменились с момента границы диапазона (либо коммита v2.6.18, либо самого последнего коммита старше 3 недель в приведённом выше примере), приписываются этому граничному коммиту диапазона.

Особенно полезный способ — проверить, есть ли в добавленном файле строки, созданные копированием и вставкой из существующих файлов. Иногда это указывает на то, что разработчик был небрежен и не провёл рефакторинг кода должным образом. Сначала вы можете найти коммит, который ввёл файл, с помощью:

	git log --diff-filter=A --pretty=short -- foo

а затем аннотировать изменение между коммитом и его родителями, используя обозначение `commit^!`:

	git blame -C -C -f $коммит^! -- foo


ИНКРЕМЕНТАЛЬНЫЙ ВЫВОД
---------------------

При вызове с параметром `--incremental` команда выводит результат по мере его построения. Вывод обычно будет говорить о строках, затронутых более поздними коммитами, в первую очередь (т.е. строки будут аннотироваться не по порядку) и предназначен для использования интерактивными просмотрщиками.

Формат вывода похож на фарфоровый формат, но не содержит фактических строк из аннотируемого файла.

. Каждая запись blame всегда начинается со строки:

	<40-байтовый-шестнадцатеричный-sha1> <исходная-строка> <строка-результата> <число-строк>
+
Номера строк считаются с 1.

. Когда коммит впервые появляется в потоке, о нём выводится различная другая информация с одноключевым тегом в начале каждой строки, описывающим дополнительную информацию о коммите (автор, адрес электронной почты, коммиттер, даты, сводка и т.д.).

. В отличие от фарфорового формата, информация об имени файла всегда предоставляется и завершает запись:

	"filename" <сюда-помещается-заключённое-в-кавычки-имя-файла>
+
и, таким образом, его действительно довольно легко анализировать для некоторого построчного и пословного анализатора (что должно быть вполне естественно для большинства языков сценариев).
+
[NOTE]
Для тех, кто занимается анализом: чтобы сделать его более надёжным, просто игнорируйте любые строки между первой и последней (строки "<sha1>" и "filename"), где вы не распознаёте ключевые слова (или вам не важна эта конкретная информация) в начале строк "расширенной информации". Таким образом, если когда-либо будет добавлена информация (например, кодировка коммита или расширенный комментарий к коммиту), просмотрщик blame не будет обращать на неё внимания.


СОПОСТАВЛЕНИЕ АВТОРОВ
---------------------

См. linkgit:gitmailmap[5].

КОНФИГУРАЦИЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/blame.adoc[]

СМ. ТАКЖЕ
---------
linkgit:git-annotate[1]

GIT
---
Является частью пакета linkgit:git[1]
