git-diff-index(1)
=================

НАЗВАНИЕ
--------
git-diff-index - Сравнение дерева файлов с рабочим каталогом или индексом


ОБЗОР
-----
[verse]
'git diff-index' [-m] [--cached] [--merge-base] [<общие-параметры-diff>] <указатель-дерева> [<путь>...]

ОПИСАНИЕ
--------
Сравнить содержимое и режимы доступа к файлам blob-объектов, найденных в объекте-дереве, с соответствующими отслеживаемыми файлами в рабочем каталоге или с соответствующими путями в индексе. Если в качестве аргументов задан один или несколько <путей>, то сравнивать только файлы, пути которых соответствуют этим шаблонам. В противном случае — сравнивать все отслеживаемые файлы.

ПАРАМЕТРЫ
---------
include::diff-options.adoc[]

<указатель-дерева>::
	Идентификатор объекта-дерева, с которым следует производить сравнение.

--cached::
	Не учитывать файлы на диске вообще.

--merge-base::
	Вместо непосредственного сравнения <указателя-дерева>, использовать базу слияния между <указателем-дерева> и HEAD; <указатель-дерева> должен быть коммитом.

-m::
	По умолчанию файлы, хранящиеся в индексе, но не извлечённые в рабочую копию, помечаются как удалённые. Этот флаг заставляет 'git diff-index' считать, что все не извлечённые файлы находятся в актуальном состоянии.

include::diff-format.adoc[]

РЕЖИМЫ РАБОТЫ
-------------
Вы можете выбрать, доверять ли полностью файлу индекса (с помощью флага `--cached`) или попросить алгоритм сравнения показывать любые файлы, чьё состояние stat отличается, как «предварительно изменённые». На самом деле, обе эти операции очень полезны.

РЕЖИМ CACHED
------------
Указание параметра `--cached`, позволяет вам попросить:

	покажи мне различия между HEAD и текущим содержимым индекса
	(т.е. тем, что было бы записано с помощью 'git write-tree')

Например, предположим, что вы работали в своём рабочем каталоге, обновили некоторые файлы в индексе и готовы к коммиту. Вы хотите увидеть в точности *что* именно вы собираетесь закоммитить, без необходимости записывать новый объект-дерево и сравнивать его таким образом, так что для этого вы просто делаете:

	git diff-index --cached HEAD

Пример: предположим, я переименовал `commit.c` в `git-commit.c`, и я сделал `update-index`, чтобы это возымело эффект в файле индекса. `git diff-files` ничего не покажет, поскольку индексный файл соответствует моему рабочему каталогу. Но запуск `git diff-index` покажет:

  torvalds@ppc970:~/git> git diff-index --cached HEAD
  :100644 000000 4161aecc6700a2eb579e842af0b7f22b98443f74 0000000000000000000000000000000000000000 D	commit.c
  :000000 100644 0000000000000000000000000000000000000000 4161aecc6700a2eb579e842af0b7f22b98443f74 A	git-commit.c

Вы можете с лёгкостью заметить, что это является переименованием.

По сути, `git diff-index --cached` *всегда* должен быть полностью эквивалентен выполнению `git write-tree` и сравнению с получившимся деревом. Однако это намного проще в ситуации, когда вы просто хотите определиться, что происходит.

Таким образом, выполнение `git diff-index --cached` очень полезно, когда вы спрашиваете себя «что я уже отметил для коммита, и в чём отличие от предыдущего дерева».

РЕЖИМ БЕЗ CACHED
----------------
Режим «без cached» использует другой подход и потенциально является более полезным, поскольку то, что он делает, нельзя эмулировать с помощью 'git write-tree' + 'git diff-tree'. Так что он является режимом по умолчанию. Версия без cached ставит вопрос:

  покажи мне различия между HEAD и текущим извлечённым деревом — содержимым
  индекса _и_ файлами, которые не находятся в актуальном состоянии

что, очевидно, также является очень полезным запросом, поскольку это говорит вам, что вы *можете* закоммитить[1]. Опять же, вывод совпадает с выводом `git diff-tree -r` до мелочей, но с одной изюминкой.

Изюминка заключается в том, что если какой-то файл отличается от его версии в индексе, у нас нет для него резервного хранилища, и мы используем волшебный «нулевой» sha1, чтобы показать это. Итак, допустим, вы отредактировали `kernel/sched.c`, но еще не сделали `git update-index`, так что с новым состоянием не связан никакой «объект», и вы получаете:

  torvalds@ppc970:~/v2.6/linux> git diff-index --abbrev HEAD
  :100644 100644 7476bb5ba 000000000 M	kernel/sched.c

то есть он показывает, что дерево изменилось и что `kernel/sched.c` не является актуальным и может содержать новые данные. «Нулевой» sha1 означает, что для получения реального списка изменений вам нужно смотреть на объект непосредственно в рабочем каталоге, а не искать различая объект-к-объекту.

NOTE: Как и в случае с другими командами этого типа, 'git diff-index' на самом деле вообще не смотрит на содержимое файла. Так что, может быть, собственно содержимое `kernel/sched.c` на самом деле не было изменено, а просто было обновлено его время последнего изменения. В любом случае, это означает, что вам нужно выполнить 'git update-index', чтобы синхронизировать индекс.

NOTE: Вы можете получить смесь файлов, отображаемых как «был обновлён» и «всё ещё грязный в рабочем каталоге». Вы всегда можете сказать, какой файл в каком состоянии, поскольку для «обновлённых» файлов отображается корректная sha1-сумма, а для «не синхронизированных с индексом» файлов — всегда специальный «нулевой» sha1.

GIT
---
Является частью пакета linkgit:git[1]
