git-mergetool(1)
================

НАЗВАНИЕ
--------
git-mergetool - Запуск инструментов разрешения конфликтов слияния

ОБЗОР
-----
[synopsis]
git mergetool [--tool=<инструмент>] [-y | --[no-]prompt] [<файл>...]

ОПИСАНИЕ
--------

Используйте `git mergetool` для запуска одной из нескольких утилит слияния для разрешения конфликтов слияния. Обычно он запускается после `git merge`.

Если указан один или несколько параметров <файл>, программа инструмента слияния будет запущена для разрешения различий в каждом файле (пропуская те, в которых нет конфликтов). Указание каталога включит все неразрешённые файлы в этом пути. Если имена _<файлов>_ не указаны, `git mergetool` запустит программу инструмента слияния для каждого файла с конфликтами слияния.

ПАРАМЕТРЫ
---------
`-t <инструмент>`::
`--tool=<инструмент>`::
	Использовать программу разрешения слияния, указанную _<инструментом>_. Допустимые значения включают `emerge`, `gvimdiff`, `kdiff3`, `meld`, `vimdiff` и `tortoisemerge`. Выполните `git mergetool --tool-help` для получения списка допустимых настроек `<инструмента>`.
+
Если программа разрешения слияния не указана, `git mergetool` будет использовать переменную конфигурации `merge.tool`. Если переменная конфигурации `merge.tool` не установлена, `git mergetool` выберет подходящее значение по умолчанию.
+
Вы можете явно указать полный путь к инструменту, установив переменную конфигурации `mergetool.<инструмент>.path`. Например, вы можете настроить абсолютный путь к kdiff3, установив `mergetool.kdiff3.path`. В противном случае `git mergetool` предполагает, что инструмент доступен в `$PATH`.
+
Вместо запуска одной из известных программ слияния, `git mergetool` можно настроить для запуска альтернативной программы, указав командную строку для вызова в переменной конфигурации `mergetool.<инструмент>.cmd`.
+
Когда `git mergetool` вызывается с этим инструментом (либо через опцию `-t` или `--tool`, либо через переменную конфигурации `merge.tool`), настроенная командная строка будет вызвана с переменными: `BASE` — имя временного файла, содержащего общую базу для слияния, если доступно; `LOCAL` — имя временного файла, содержащего содержимое файла в текущей ветке; `REMOTE` — имя временного файла, содержащего содержимое файла для слияния; `MERGED` — имя файла, в который инструмент слияния должен записать результат разрешения слияния.
+
Если пользовательский инструмент слияния правильно указывает на успех разрешения слияния с помощью своего кода выхода, то переменная конфигурации `mergetool.<инструмент>.trustExitCode` может быть установлена в `true`. В противном случае `git mergetool` предложит пользователю указать успех разрешения после выхода пользовательского инструмента.

`--tool-help`::
	Вывести список утилит, которые можно использовать с параметром `--tool`.

`-y`::
`--no-prompt`::
	Не запрашивать перед каждым вызовом программы разрешения слияния. Это значение по умолчанию, если программа разрешения слияния явно указана с помощью параметра `--tool` или переменной конфигурации `merge.tool`.

`--prompt`::
	Запрашивать перед каждым вызовом программы разрешения слияния, чтобы дать пользователю возможность пропустить путь.

`-g`::
`--gui`::
	Когда `git-mergetool` вызывается с опцией `-g` или `--gui`, инструмент слияния по умолчанию будет прочитан из настроенной переменной `merge.guitool` вместо `merge.tool`. Если `merge.guitool` не установлен, будет использоваться инструмент, настроенный в `merge.tool`. Это может быть автоматически выбрано с помощью переменной конфигурации `mergetool.guiDefault`.

`--no-gui`::
	Это переопределяет предыдущую настройку `-g` или `--gui` или конфигурацию `mergetool.guiDefault` и читает инструмент слияния по умолчанию из настроенной переменной `merge.tool`.

`-O<файл-порядка>`::
	Обрабатывать файлы в порядке, указанном в `<файле-порядка>`, который содержит по одному шаблону glob оболочки на строку. Это переопределяет переменную конфигурации `diff.orderFile` (см. linkgit:git-config[1]). Чтобы отменить `diff.orderFile`, используйте `-O/dev/null`.

КОНФИГУРАЦИЯ
------------
:git-mergetool: 1

include::includes/cmd-config-section-all.adoc[]

include::config/mergetool.adoc[]

ВРЕМЕННЫЕ ФАЙЛЫ
---------------
`git mergetool` создаёт резервные файлы `*.orig` во время разрешения слияний. Их можно безопасно удалить после того, как файл был слит и сеанс `git mergetool` для него завершён.

Установка переменной конфигурации `mergetool.keepBackup` в `false` заставляет `git mergetool` автоматически удалять резервные файлы по мере успешного слияния файлов.

СОВЕТЫ ДЛЯ КОНКРЕТНЫХ ВНУТРЕННИХ МЕХАНИЗМОВ
-------------------------------------------

vimdiff
~~~~~~~
include::mergetools/vimdiff.adoc[]

GIT
---
Является частью пакета linkgit:git[1]
