git-status(1)
=============

НАЗВАНИЕ
--------
git-status - показать состояние рабочего каталога


ОБЗОР
-----

[synopsis]
git status [<options>] [--] [<pathspec>...]

ОПИСАНИЕ
--------
Отображает пути, которые имеют различия между файлом индекса и текущим коммитом HEAD, пути, которые имеют различия между рабочим каталогом и файлом индекса, а также пути в рабочем каталоге, которые не отслеживаются Git (и не игнорируются linkgit:gitignore[5]). Первые — это то, что вы _закоммитили бы_, выполнив `git commit`; вторые и третьи — это то, что вы _могли бы закоммитить_, выполнив `git add` перед выполнением `git commit`.

ПАРАМЕТРЫ
---------

`-s`::
`--short`::
	Выдавать вывод в кратком формате.

`-b`::
`--branch`::
	Показывать ветку (и какую внешнюю ветку она отслеживает) даже в коротком формате.

`--show-stash`::
	Показывать количество записей, в настоящее время спрятанных.

`--porcelain[=<version>]`::
	Выдавать вывод в формате, удобном для анализа сценариями. Это похоже на краткий вывод, но останется стабильным во всех версиях Git и независимо от конфигурации пользователя. Подробности см. ниже.
+
Параметр _<версия>_ используется для указания версии формата. Он необязателен и по умолчанию имеет исходный формат `v1`.

`--long`::
	Выдавать вывод в длинном формате. Это значение по умолчанию.

`-v`::
`--verbose`::
	В дополнение к именам изменённых файлов также показывать текстовые изменения, которые проиндексированы для фиксации (т.е. как вывод `git diff --cached`). Если `-v` указан дважды, также показывать изменения в рабочем каталоге, которые ещё не проиндексированы (т.е. как вывод `git diff`).

`-u[<режим>]`::
`--untracked-files[=<режим>]`::
	Отображать неотслеживаемые файлы.
+
--
Параметр режима используется для указания обработки неотслеживаемых файлов. Он необязателен: по умолчанию `all`, и если указан, он должен примыкать к параметру (например, `-uno`, но не `-u no`).

Возможные значения аргумента:

`no`:: Не показывать неотслеживаемые файлы.
`normal`:: Показывать неотслеживаемые файлы и каталоги.
`all`:: Также показывать отдельные файлы в неотслеживаемых каталогах.

Когда параметр `-u` не используется, показываются неотслеживаемые файлы и каталоги (т.е. то же самое, что указание `normal`), чтобы помочь вам не забыть добавить новые созданные файлы. Поскольку для поиска неотслеживаемых файлов в файловой системе требуется дополнительная работа, этот режим может занять некоторое время в большом рабочем каталоге. Рассмотрите возможность включения кэша неотслеживаемых файлов и разделённого индекса, если они поддерживаются (см. `git update-index --untracked-cache` и `git update-index --split-index`). В противном случае вы можете использовать `no`, чтобы `git status` возвращал результат быстрее, не показывая неотслеживаемые файлы. Все обычные варианты написания для булева значения `true` принимаются как `normal`, а `false` — как `no`.

По умолчанию можно изменить с помощью переменной конфигурации `status.showUntrackedFiles`, описанной в linkgit:git-config[1].
--

`--ignore-submodules[=<when>]`::
	Iгнорировать изменения в подмодулях при поиске изменений. _<когда>_ может быть `none`, `untracked`, `dirty` или `all`, что является значением по умолчанию.
`none`;; будет считать подмодуль изменённым, когда он содержит неотслеживаемые или изменённые файлы, или его HEAD отличается от коммита, записанного в суперпроекте, и может использоваться для переопределения любых настроек параметра `ignore` в linkgit:git-config[1] или linkgit:gitmodules[5].
`untracked`;; подмодули не считаются изменёнными, когда они содержат только неотслеживаемое содержимое (но они всё равно сканируются на предмет изменённого содержимого).
`dirty`;; игнорировать все изменения в рабочем каталоге подмодулей, показываются только изменения в коммитах, хранящихся в суперпроекте (это было поведением до версии 1.7.0).
`all`;; скрывать все изменения в подмодулях (и подавлять вывод сводок по подмодулям, когда установлен параметр конфигурации `status.submoduleSummary`).

`--ignored[=<mode>]`::
	Также показывать игнорируемые файлы.
+
--
Параметр режима используется для указания обработки игнорируемых файлов. Он необязателен: по умолчанию `traditional`.

Возможные значения аргумента:

`traditional`:: Показывать игнорируемые файлы и каталоги, если только
не указан `--untracked-files=all`, и в этом случае
 отображаются отдельные файлы в игнорируемых
 каталогах.
`no`:: Не показывать игнорируемые файлы.
`matching`:: Показать игнорируемые файлы и каталоги, соответствующие шаблону игнорирования.
+
Пути, которые явно соответствуют шаблону игнорирования, показываются. Если каталог соответствует шаблону игнорирования, то он показывается, но не пути, содержащиеся в игнорируемом каталоге. Если каталог не соответствует шаблону игнорирования, но всё его содержимое игнорируется, то каталог не показывается, но всё содержимое показывается.
--

`-z`::
	Завершать записи символом _NUL_ вместо _LF_. Это подразумевает формат вывода `--porcelain=v1`, если не указан другой формат.

`--column[=<параметры>]`::
`--no-column`::
	Отображать неотслеживаемые файлы в столбцах. См. конфигурационную переменную `column.status` для синтаксиса параметров. `--column` и `--no-column` без параметров эквивалентны `always` и `never` соответственно.

`--ahead-behind`::
`--no-ahead-behind`::
	Отображать или не отображать подробные сведения о количестве опережений/отставаний для ветки относительно её вышестоящей ветки. По умолчанию `true`.

`--renames`::
`--no-renames`::
	Включает/отключает обнаружение переименований независимо от конфигурации пользователя. См. также linkgit:git-diff[1] `--no-renames`.

`--find-renames[=<n>]`::
	Включает обнаружение переименований, опционально устанавливая порог схожести. См. также linkgit:git-diff[1] `--find-renames`.

`<спецификатор-пути>…`::
	См. запись 'pathspec' в linkgit:gitglossary[7].

ВЫВОД
-----
Вывод этой команды предназначен для использования в качестве комментария-шаблона коммита. Формат по умолчанию, длинный, предназначен для удобочитаемости, подробности и описательности. Его содержимое и формат могут быть изменены в любое время.

Пути, упомянутые в выводе, в отличие от многих других команд Git, являются относительными относительно текущего каталога, если вы работаете в подкаталоге (это сделано намеренно, чтобы помочь копированию и вставке). См. параметр конфигурации status.relativePaths ниже.

Короткий формат
~~~~~~~~~~~~~~~

При использовании короткого формата статус каждого пути отображается в одном из следующих форм:

	<xy> <путь>
	<xy> <исходный-путь> -> <путь>

где _<orig-path>_ — это место, откуда было переименовано/скопировано содержимое. _<orig-path>_ отображается только в том случае, если запись была переименована или скопирована. _<xy>_ — это двухбуквенный код состояния `XY`.

Поля (включая `->`) отделяются друг от друга одним пробелом. Если имя файла содержит пробелы или другие непечатаемые символы, это поле будет заключено в кавычки в стиле строкового литерала C: окружено символами ASCII двойной кавычки (34), а внутренние специальные символы экранированы обратной косой чертой.

Существует три различных типа состояний, которые показываются с использованием этого формата, и каждый из них использует синтаксис _<xy>_ по-разному:

* Когда происходит слияние и оно было успешным, или вне слияния
	ситуации, `X` показывает статус индекса, а `Y` показывает статус рабочего каталога.
* Когда возник конфликт слияния и он ещё не разрешён, `X` и `Y`
	показывают состояние, внесённое каждой головой слияния, относительно общего предка. Эти пути называются _не слитыми_.
* Когда путь не отслеживается, `X` и `Y` всегда одинаковы, поскольку они
	неизвестны индексу. `??` используется для неотслеживаемых путей. Игнорируемые файлы не перечисляются, если не используется `--ignored`; если используется, игнорируемые файлы обозначаются `!!`.

Обратите внимание, что термин _merge_ здесь также включает перемещения с использованием стратегии `--merge` по умолчанию, копирование коммитов и всё остальное, что использует механизм слияния.

В следующей таблице эти три класса показаны в отдельных разделах, и эти символы используются для полей `X` и `Y` в первых двух разделах, показывающих отслеживаемые пути:

' ':: неизменено
`M`:: изменено
`T`:: изменён тип файла (обычный файл, символьная ссылка или подмодуль)
`A`:: добавлен
`D`:: удалено
`R`:: переименовано
`C`:: скопирован (если параметр конфигурации status.renames установлен в «copies»)
`U`:: обновлён, но не слит

[cols="^1m,^1m,<2", options="header"]
|===
|X        |  Y     |Значение
|         |[AMD]   |не обновлено
|M        |[ MTD]  |обновлён в индексе
|T        |[ MTD]  |тип изменён в индексе
|A        |[ MTD]  |добавлен в индекс
|D        |        |удалён из индекса
|R        |[ MTD]  |переименовано в индексе
|C        |[ MTD]  |скопирован в индексе
|[MTARC]  |        |индекс и рабочий каталог совпадают
|[ MTARC] |M       |рабочий каталог изменён с момента индекса
|[ MTARC] |T       |тип изменён в рабочем каталоге с момента индекса
|[ MTARC] |D       |удалён в рабочем каталоге
|         |R       |переименован в рабочем каталоге
|         |C       |скопирован в рабочем каталоге
|D        |D       |не слит, оба удалены
|A        |U       |не слит, добавлено нами
|U        |D       |не слит, удалено ими
|U        |A       |не слит, добавлено ими
|D        |U       |не слит, удалено нами
|A        |A       |не слито, оба добавлены
|U        |U       |не слито, оба изменены
|?        |?       |неотслеживаемый
|!        |!       |игнорируемый
|===

Подмодули имеют больше состояний и вместо этого сообщают

`M`:: подмодуль имеет HEAD, отличный от записанного в индексе
`m`:: подмодуль изменил содержимое
`?`:: в подмодуле есть неотслеживаемые файлы

Это связано с тем, что изменённое содержимое или неотслеживаемые файлы в подмодуле не могут быть добавлены через `git add` в суперпроекте для подготовки коммита.

`m` и `?` применяются рекурсивно. Например, если вложенный подмодуль в подмодуле содержит неотслеживаемый файл, это также сообщается как `?`.

Если используется `-b`, краткому формату статуса предшествует строка

[synopsis]
{empty}## <имя-ветки> <информация-об-отслеживании>


Формат Porcelain версии 1
~~~~~~~~~~~~~~~~~~~~~~~~~

Формат Porcelain версии 1 похож на краткий формат, но гарантированно не изменяется несовместимым образом между версиями Git или в зависимости от конфигурации пользователя. Это делает его идеальным для анализа сценариями. Описание краткого формата выше также описывает Porcelain формат, за исключением нескольких моментов:

1. Конфигурация `color.status` пользователя не учитывается; цвет всегда будет выключен.

2. Конфигурация `status.relativePaths` пользователя не учитывается; показанные пути всегда будут относительными корня репозитория.

Существует также альтернативный формат `-z`, рекомендуемый для машинного анализа. В этом формате поле статуса остаётся тем же, но некоторые другие вещи меняются. Во-первых, `->` опускается из записей переименования, и порядок полей меняется на обратный (например, `from -> to` становится `to from`). Во-вторых, после каждого имени файла следует _NUL_ (ASCII 0), заменяющий пробел в качестве разделителя полей и завершающий символ новой строки (но пробел по-прежнему отделяет поле статуса от первого имени файла). В-третьих, имена файлов, содержащие специальные символы, не форматируются специальным образом; не выполняется никаких кавычек или экранирования обратной косой чертой.

Любые изменения в подмодулях сообщаются как изменённые `M` вместо `m` или одиночного `?`.

Формат Porcelain версии 2
~~~~~~~~~~~~~~~~~~~~~~~~~

Формат версии 2 добавляет более подробную информацию о состоянии рабочего каталога и изменённых элементах. Версия 2 также определяет расширяемый набор легко анализируемых необязательных заголовков.

Строки заголовков начинаются с `#` и добавляются в ответ на определённые аргументы командной строки. Анализаторы должны игнорировать заголовки, которые они не распознают.

Заголовки веток
^^^^^^^^^^^^^^^

Если указан `--branch`, выводится серия строк заголовков с информацией о текущей ветке.

[cols="<1,<1", options="header"]
|===
|Строка                                     |Заметки
|`# branch.oid <коммит> \| (initial)`     |Текущий коммит.
|`# branch.head <ветка> \| (отсоединённый)`   |Текущая ветка.
|`# branch.upstream <вышестоящая-ветка>`    |Если вышестоящая ветка установлена.
|`# branch.ab +<впереди> -<позади>`         |Если вышестоящая ветка установлена и
					  коммит присутствует.
|===

Информация о спрятанных изменениях
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Если указан `--show-stash`, выводится одна строка, показывающая количество спрятанных записей, если оно ненулевое:

    # stash <N>

Изменённые отслеживаемые записи
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

После заголовков выводится серия строк для отслеживаемых записей. В зависимости от типа изменения для описания записи может использоваться один из трёх различных форматов строк. Отслеживаемые записи выводятся в неопределённом порядке; анализаторы должны допускать смешение 3 типов строк в любом порядке.

Обычные изменённые записи имеют следующий формат:

[synopsis]
1 <XY> <sub> <mH> <mI> <mW> <hH> <hI> <путь>

Переименованные или скопированные записи имеют следующий формат:

[synopsis]
2 <XY> <sub> <mH> <mI> <mW> <hH> <hI> <X><оценка> <путь><разделитель><исходный-путь>

[cols="<1,<1a", options="header"]
|===
|Поле       | Значение

|_<XY>_
|Двухсимвольное поле, содержащее проиндексированные и
неиндексированные значения XY, описанные в кратком формате,
с неизменёнными, обозначенными "." вместо
пробела.
|_<под>_
|Четырёхсимвольное поле, описывающее состояние подмодуля.
"N...", когда запись не является подмодулем.
`S<c><m><u>`, когда запись является подмодулем.

* _<c>_ — "C", если коммит изменился; в противном случае ".".
* _<m>_ — "M", если есть отслеживаемые изменения; в противном случае ".".
* _<u>_ — "U", если есть неотслеживаемые изменения; в противном случае ".".
|_<mH>_       |Восьмеричный режим файла в HEAD.
|_<mI>_       |Восьмеричный режим файла в индексе.
|_<mW>_       |Восьмеричный режим файла в рабочем каталоге.
|_<hH>_       |Имя объекта в HEAD.
|_<hI>_       |Имя объекта в индексе.
|_<X><оценка>_ |Оценка переименования или копирования (обозначающая процент
сходства между источником и целью перемещения или копирования).
Например, «R100» или «C75».
|_<путь>_
|Имя пути. В переименованной/скопированной записи это целевой путь.
|_<разделитель>_
|Когда используется параметр `-z`, два имени пути разделяются
байтом _NUL_ (ASCII 0x00); в противном случае их разделяет
байт _TAB_ (ASCII 0x09).
|_<исходный-путь>_
|Имя пути в коммите в HEAD или в индексе.
Присутствует только в переименованной/скопированной записи и
указывает, откуда взялось переименованное/скопированное содержимое.
|===

Не слитые записи имеют следующий формат; первый символ — "u", чтобы отличить их от обычных изменённых записей.

[synopsis]
u <XY> <sub> <m1> <m2> <m3> <mW> <h1> <h2> <h3> <путь>

[cols="<1,<1a", options="header"]
|===
|Поле       |Значение
|_<XY>_      |Двухсимвольное поле, описывающее тип конфликта
	    как описано в кратком формате.
|_<под>_     |Четырёхсимвольное поле, описывающее состояние подмодуля
	    как описано выше.
|_<m1>_      |Восьмеричный режим файла на стадии 1.
|_<m2>_      |Восьмеричный режим файла на стадии 2.
|_<m3>_      |Восьмеричный режим файла на стадии 3.
|_<mW>_      |Восьмеричный режим файла в рабочем каталоге.
|_<h1>_      |Имя объекта на этапе 1.
|_<h2>_      |Имя объекта на этапе 2.
|_<h3>_      |Имя объекта на этапе 3.
|_<путь>_    |Имя пути.
|===

Другие элементы
^^^^^^^^^^^^^^^

После отслеживаемых записей (и если запрошено) будет выведена серия строк для неотслеживаемых, а затем игнорируемых элементов, найденных в рабочем каталоге.

Неотслеживаемые элементы имеют следующий формат:

    ? <путь>

Игнорируемые элементы имеют следующий формат:

    ! <путь>

Примечания к формату имени пути и -z
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Когда указан параметр `-z`, имена путей выводятся как есть, без каких-либо кавычек, а строки завершаются байтом _NUL_ (ASCII 0x00).

Без параметра `-z` имена путей с "необычными" символами заключаются в кавычки, как объяснено для переменной конфигурации `core.quotePath` (см. linkgit:git-config[1]).


КОНФИГУРАЦИЯ
------------

Команда учитывает переменные конфигурации `color.status` (или `status.color` — они означают одно и то же, и последняя сохранена для обратной совместимости) и `color.status.<слот>` для раскрашивания своего вывода.

Если переменная конфигурации `status.relativePaths` установлена в false, то все показанные пути являются относительными относительно корня репозитория, а не текущего каталога.

Если `status.submoduleSummary` установлен в ненулевое число или true (идентично -1 или неограниченному числу), сводка по подмодулям будет включена для длинного формата, и будет показана сводка коммитов для изменённых подмодулей (см. параметр `--summary-limit` команды linkgit:git-submodule[1]). Обратите внимание, что вывод сводки из команды status будет подавлен для всех подмодулей, когда `diff.ignoreSubmodules` установлен в `all`, или только для тех подмодулей, где `submodule.<имя>.ignore=all`. Чтобы также просмотреть сводку для игнорируемых подмодулей, вы можете использовать параметр командной строки `--ignore-submodules=dirty` или команду 'git submodule summary', которая показывает похожий вывод, но не учитывает эти настройки.

ФОНОВОЕ ОБНОВЛЕНИЕ
------------------

По умолчанию `git status` автоматически обновляет индекс, обновляя кэшированную информацию stat из рабочего каталога и записывая результат. Запись обновлённого индекса является оптимизацией, которая не является строго необходимой (`status` вычисляет значения для себя, но их запись предназначена только для того, чтобы избавить последующие программы от повторения наших вычислений). Когда `status` запускается в фоновом режиме, блокировка, удерживаемая во время записи, может конфликтовать с другими параллельными процессами, вызывая их сбой. Сценариям, запускающим `status` в фоновом режиме, следует рассмотреть возможность использования `git --no-optional-locks status` (подробности см. в linkgit:git[1]).

НЕОТСЛЕЖИВАЕМЫЕ ФАЙЛЫ И ПРОИЗВОДИТЕЛЬНОСТЬ
------------------------------------------

`git status` может быть очень медленным в больших рабочих каталогах, если/когда ему нужно искать неотслеживаемые файлы и каталоги. Существует множество доступных параметров конфигурации для ускорения этого процесса либо путём избежания работы, либо путём использования кэшированных результатов из предыдущих команд Git. Не существует единого оптимального набора настроек, подходящего для всех. Мы перечислим сводку соответствующих параметров, чтобы помочь вам, но перед тем, как перейти к списку, вы можете запустить `git status` ещё раз, потому что ваша конфигурация, возможно, уже кэширует результаты `git status`, поэтому он может быть быстрее при последующих запусках.

* Флаг `--untracked-files=no` или
	конфигурация `status.showUntrackedFiles=no` (см. выше для обоих): указывает, что `git status` не должен сообщать о неотслеживаемых файлах. Это самый быстрый вариант. `git status` не будет перечислять неотслеживаемые файлы, поэтому вам нужно быть внимательным, чтобы помнить, если вы создаёте какие-либо новые файлы, и вручную выполнять `git add` для них.

* `advice.statusUoption=false` (см. linkgit:git-config[1]):
	установка этой переменной в `false` отключает предупреждающее сообщение, выдаваемое, когда перечисление неотслеживаемых файлов занимает более 2 секунд. В большом проекте это может занять больше времени, и пользователь, возможно, уже принял компромисс (например, использование `-uno` может быть неприемлемым параметром для пользователя), и в этом случае нет смысла выдавать предупреждающее сообщение, и в таком случае отключение предупреждения может быть лучшим решением.

* `core.untrackedCache=true` (см. linkgit:git-update-index[1]):
	включить функцию кэша неотслеживаемых файлов и искать только каталоги, которые были изменены с момента предыдущей команды `git status`. Git запоминает набор неотслеживаемых файлов в каждом каталоге и предполагает, что если каталог не был изменён, то набор неотслеживаемых файлов внутри него не изменился. Это гораздо быстрее, чем перечисление содержимого каждого каталога, но всё же не бесплатно, потому что Git всё равно должен искать набор изменённых каталогов. Кэш неотслеживаемых файлов хранится в файле `.git/index`. Снижение затрат на поиск неотслеживаемых файлов несколько компенсируется увеличением размера индекса и затратами на его поддержание в актуальном состоянии. Это сокращение времени поиска обычно стоит дополнительного размера.

* `core.untrackedCache=true` и `core.fsmonitor=true` или
	`core.fsmonitor=<путь-к-команде-перехватчика>` (см. linkgit:git-update-index[1]): включить как кэш неотслеживаемых файлов, так и функции FSMonitor, и искать только каталоги, которые были изменены с момента предыдущей команды `git status`. Это быстрее, чем использование только кэша неотслеживаемых файлов, потому что Git также может избежать поиска изменённых каталогов. Git должен перечислить только точный набор каталогов, которые изменились недавно. Хотя функция FSMonitor может быть включена без кэша неотслеживаемых файлов, преимущества в этом случае значительно снижаются.

Обратите внимание, что после включения кэша неотслеживаемых файлов и/или функций FSMonitor может потребоваться несколько команд `git status`, чтобы различные кэши прогрелись, прежде чем вы увидите улучшенное время выполнения команды. Это нормально.

СМ. ТАКЖЕ
---------
linkgit:gitignore[5]

GIT
---
Является частью пакета linkgit:git[1]
