git-log(1)
==========

НАЗВАНИЕ
--------
git-log — показать журналы коммитов


ОБЗОР
-----
[synopsis]
'git log' [<параметры>] [<диапазон-редакций>] [[--] <путь>...]

ОПИСАНИЕ
--------
Показывает журналы коммитов.

:git-log: 1
include::rev-list-description.adoc[]

Команда принимает параметры, применимые к команде linkgit:git-rev-list[1], чтобы управлять тем, что и как показывается, и параметры, применимые к команде linkgit:git-diff[1], чтобы управлять тем, как показываются изменения, вносимые каждым коммитом.


ПАРАМЕТРЫ
---------

`--follow`::
	Продолжить отображение истории файла за пределами переименований (работает только для одного файла).

`--no-decorate`::
`--decorate[=(short|full|auto|no)]`::
	Выводить имена ссылок любых показанных коммитов. Возможные значения:
+
----
`short`;; префиксы имён ссылок `refs/heads/`, `refs/tags/` и
	`refs/remotes/` не выводятся.
`full`;; выводится полное имя ссылки (включая префикс).
`auto`:: если вывод направляется в терминал, имена ссылок
	показываются так, как если бы был указан `short`, в противном случае
	имена ссылок не показываются.
----
+
Параметр `--decorate` является краткой формой для `--decorate=short`. По умолчанию используется значение конфигурации `log.decorate`, если оно задано, в противном случае — `auto`.

`--decorate-refs=<шаблон>`::
`--decorate-refs-exclude=<шаблон>`::
	Для каждого кандидата в ссылки не использовать его для оформления, если он соответствует любому из параметров _<шаблон>_, переданных в `--decorate-refs-exclude`, или если он не соответствует ни одному из параметров _<шаблон>_, переданных в `--decorate-refs`. Параметр конфигурации `log.excludeDecoration` позволяет исключать ссылки из оформления, но явный шаблон `--decorate-refs` имеет приоритет над совпадением в `log.excludeDecoration`.
+
Если ни один из этих параметров или настроек конфигурации не задан, то ссылки используются для оформления, если они соответствуют `HEAD`, `refs/heads/`, `refs/remotes/`, `refs/stash/` или `refs/tags/`.

`--clear-decorations`::
	При указании этот параметр очищает все предыдущие параметры `--decorate-refs` или `--decorate-refs-exclude` и ослабляет фильтр оформления по умолчанию, включая все ссылки. Этот параметр подразумевается, если значение конфигурации `log.initialDecorationSet` установлено в `all`.

`--source`::
	Выводить имя ссылки, указанное в командной строке, с помощью которой был достигнут каждый коммит.

`--mailmap`::
`--no-mailmap`::
`--use-mailmap`::
`--no-use-mailmap`::
	Использовать файл mailmap для сопоставления имён и адресов электронной почты автора и коммиттера с каноническими реальными именами и адресами электронной почты. См. linkgit:git-shortlog[1].

`--full-diff`::
	Без этого флага `git log -p <путь>...` показывает коммиты, которые затрагивают указанные пути, и различия для тех же указанных путей. С этим флагом для коммитов, затрагивающих указанные пути, показывается полное сравнение; это означает, что "`<путь>...`" ограничивает только коммиты и не ограничивает сравнение для этих коммитов.
+
Обратите внимание, что это влияет на все типы вывода на основе сравнения, например, создаваемые `--stat` и т.д.

`--log-size`::
	Включать строку `log size <число>` в вывод для каждого коммита, где _<число>_ — это длина сообщения этого коммита в байтах. Предназначено для ускорения инструментов, которые читают сообщения журнала из вывода `git log`, позволяя им заранее выделять место.

include::line-range-options.adoc[]

_<диапазон-редакций>_::
	Показывать только коммиты в указанном диапазоне редакций. Если _<диапазон-редакций>_ не указан, по умолчанию используется `HEAD` (т.е. вся история, ведущая к текущему коммиту). `origin..HEAD` указывает все коммиты, достижимые из текущего коммита (т.е. `HEAD`), но не из `origin`. Полный список способов указания _<диапазона-редакций>_ см. в разделе 'Указание диапазонов' в linkgit:gitrevisions[7].

`[--] <путь>...`::
	Показывать только коммиты, достаточные для объяснения того, как появились файлы, соответствующие указанным путям. Подробности и другие режимы упрощения см. в разделе 'Упрощение истории' ниже.
+
Пути может потребоваться предварить `--`, чтобы отделить их от параметров или диапазона редакций, когда возникает путаница.

include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

ФОРМАТИРОВАНИЕ РАЗНИЦ
---------------------

По умолчанию `git log` не создаёт никакого вывода сравнения. Следующие параметры можно использовать для отображения изменений, внесённых каждым коммитом.

Обратите внимание, что если явно не указан один из вариантов `--diff-merges` (включая краткие параметры `-m`, `-c`, `--cc` и `--dd`), коммиты слияния не будут показывать сравнение, даже если выбран такой формат сравнения, как `--patch`, и они не будут соответствовать параметрам поиска, таким как `-S`. Исключение составляет случай, когда используется `--first-parent`, в этом случае `first-parent` является форматом по умолчанию для коммитов слияния.

:git-log: 1
:diff-merges-default: `off`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]

ПРИМЕРЫ
-------
`git log --no-merges`::

	Показать всю историю коммитов, но пропустить любые слияния

`git log v2.6.12.. include/scsi drivers/scsi`::

	Показать все коммиты начиная с версии 'v2.6.12', которые изменили любой файл в подкаталогах `include/scsi` или `drivers/scsi`

`git log --since="2 недели назад" -- gitk`::

	Показать изменения за последние две недели в файле `gitk`. `--` необходим, чтобы избежать путаницы с *веткой* с именем `gitk`

`git log --name-status release..test`::

	Показать коммиты, которые находятся в ветке "`test`", но ещё не в ветке "`release`", вместе со списком путей, которые изменяет каждый коммит.

`git log --follow builtin/rev-list.c`::

	Показывает коммиты, которые изменили `builtin/rev-list.c`, включая те коммиты, которые произошли до того, как файл получил своё текущее имя.

`git log --branches --not --remotes=origin`::

	Показывает все коммиты, которые находятся в любой из локальных веток, но не в отслеживаемых внешних ветках для `origin` (то, что есть у вас, но чего нет в origin).

`git log master --not --remotes=*/master`::

	Показывает все коммиты, которые находятся в локальной ветке master, но не в ветках master ни одного внешнего репозитория.

`git log -p -m --first-parent`::

	Показывает историю, включая различия изменений, но только с точки зрения ``основной ветки'', пропуская коммиты из слитых веток и показывая полные различия изменений, внесённых слияниями. Это имеет смысл только при соблюдении строгой политики слияния всех тематических веток при нахождении на одной интеграционной ветке.

`git log -L '/int main/',/^}/:main.c`::

	Показывает, как функция `main()` в файле `main.c` развивалась во времени.

`git log -3`::

	Ограничивает количество показываемых коммитов до 3.

ОБСУЖДЕНИЕ
----------

include::i18n.adoc[]

КОНФИГУРАЦИЯ
------------

См. linkgit:git-config[1] для основных переменных и linkgit:git-diff[1] для настроек, связанных с созданием сравнений.

`format.pretty`::
	Значение по умолчанию для параметра `--format`. (См. 'Форматы вывода' выше.) По умолчанию — `medium`.

`i18n.logOutputEncoding`::
	Кодировка, используемая при отображении журналов. (См. 'Обсуждение' выше.) По умолчанию — значение `i18n.commitEncoding`, если оно задано, в противном случае UTF-8.

include::includes/cmd-config-section-rest.adoc[]

include::config/log.adoc[]

include::config/notes.adoc[]

GIT
---
Является частью пакета linkgit:git[1]
