git-credential-cache(1)
=======================

НАЗВАНИЕ
--------
git-credential-cache - Вспомогательная программа для временного хранения паролей в памяти

ОБЗОР
-----
-----------------------------
git config credential.helper 'cache [<параметры>]'
-----------------------------

ОПИСАНИЕ
--------

Эта команда кэширует учётные данные для использования будущими программами Git. Сохранённые учётные данные хранятся в памяти процесса cache-daemon (вместо записи в файл) и забываются после настраиваемого таймаута. Учётные данные забываются раньше, если процесс cache-daemon умирает, например, при перезапуске системы. Кэш доступен через сокет домена Unix, доступ к которому ограничен текущим пользователем правами файловой системы.

Вероятно, вы не захотите вызывать эту команду напрямую; она предназначена для использования в качестве вспомогательной программы для учётных данных (credential helper) другими частями Git. См. linkgit:gitcredentials[7] или `ПРИМЕРЫ` ниже.

ПАРАМЕТРЫ
---------

--timeout <секунды>::

	Количество секунд для кэширования учётных данных (по умолчанию: 900).

--socket <путь>::

	Используйте `<путь>` для связи с запущенным процессом cache-daemon (или запуска нового cache-daemon, если он не запущен). По умолчанию используется `$XDG_CACHE_HOME/git/credential/socket`, если не существует `~/.git-credential-cache/`, в этом случае вместо него используется `~/.git-credential-cache/socket`. Если ваш домашний каталог находится в сетевой файловой системе, вам может потребоваться изменить это на локальную файловую систему. Вы должны указать абсолютный путь.

УПРАВЛЕНИЕ ДЕМОНОМ
------------------

Если вы хотите, чтобы демон завершился досрочно, забыв все кэшированные учётные данные до истечения их таймаута, вы можете выполнить действие `exit`:

--------------------------------------
git credential-cache exit
--------------------------------------

ПРИМЕРЫ
-------

Смысл этой вспомогательной программы — уменьшить количество раз, когда вам нужно вводить имя пользователя или пароль. Например:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <введите имя пользователя>
Password: <введите пароль>

[работа в течение следующих 5 минут]
$ git push http://example.com/repo.git
[ваши учётные данные используются автоматически]
------------------------------------

Вы можете указать параметры через переменную конфигурации credential.helper (в этом примере время кэширования увеличивается до 1 часа):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

ПЕРСОНАЛЬНЫЕ МАРКЕРЫ ДОСТУПА
----------------------------

Некоторые внешние репозитории принимают персональные маркеры доступа, которые генерируются случайным образом и их трудно запомнить. Обычно они имеют срок действия в недели или месяцы.

git-credential-cache по своей сути не подходит для постоянного хранения персональных маркеров доступа. Учётные данные будут забыты после истечения таймаута кэша. Даже если вы настроите большой таймаут, учётные данные будут забыты, если демон завершится.

Чтобы избежать частой повторной генерации персональных маркеров доступа, настройте вспомогательную программу для учётных данных (credential helper) с постоянным хранилищем. В качестве альтернативы настройте вспомогательную программу для учётных данных OAuth для автоматической генерации учётных данных. См. linkgit:gitcredentials[7], разделы "Доступные помощники" и "OAuth".

GIT
---
Является частью пакета linkgit:git[1]
