git-verify-pack(1)
==================

НАЗВАНИЕ
--------
git-verify-pack — проверка упакованных архивных файлов Git


ОБЗОР
-----
[synopsis]
'git verify-pack' [-v | --verbose] [-s | --stat-only] [--] <пакет>.idx...


ОПИСАНИЕ
--------
Читает каждый idx-файл для упакованного архива Git, указанного в командной строке, и проверяет idx-файл и соответствующий pack-файл.

ПАРАМЕТРЫ
---------
`-v`::
`--verbose`::
	После проверки пакета показывает список объектов, содержащихся в пакете, и гистограмму длины цепочки дельт.

`-s`::
`--stat-only`::
	Не проверять содержимое пакета; показывать только гистограмму длины цепочки дельт. С `--verbose` также показывается список объектов.

`--`::
	Не рассматривать остальные аргументы командной строки в качестве параметров.

ФОРМАТ ВЫВОДА
-------------
При указании параметра `-v` используется следующий формат:

	имя-объекта тип размер размер-в-pack-файле смещение-в-pack-файле

для объектов, которые не дельтифицированы в пакете, и

	имя-объекта тип размер размер-в-pack-файле смещение-в-pack-файле глубина имя-базового-объекта

для объектов, которые дельтифицированы.

GIT
---
Является частью пакета linkgit:git[1]
