git-rev-list(1)
===============

НАЗВАНИЕ
--------
git-rev-list — Выводит список объектов коммитов в обратном хронологическом порядке


ОБЗОР
-----
[verse]
'git rev-list' [<параметры>] <коммит>... [--] [<путь>...]

ОПИСАНИЕ
--------

:git-rev-list: 1
include::rev-list-description.adoc[]

'rev-list' — это важная команда Git, поскольку она предоставляет возможность строить и обходить графы родословной коммитов. По этой причине она имеет много различных параметров, которые позволяют использовать её таким разным командам, как 'git bisect' и 'git repack'.

ПАРАМЕТРЫ
---------

:git-rev-list: 1
include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

ПРИМЕРЫ
-------

* Вывести список коммитов достижимых из текущей ветки.
+
----------
git rev-list HEAD
----------

* Вывести список коммитов в этой ветке, отсутствующих в вышестоящей ветке.
+
----------
git rev-list @{вышестоящая}..HEAD
----------

* Форматировать коммиты с их автором и сообщением коммита (см. также высокоуровневый программный интерфейс linkgit:git-log[1]).
+
----------
git rev-list --format=medium HEAD
----------

* Форматировать коммиты вместе с их различиями (см. также высокоуровневый программный интерфейс linkgit:git-log[1], который может сделать это в одном процессе).
+
----------
git rev-list HEAD |
git diff-tree --stdin --format=medium -p
----------

* Вывести список коммитов в текущей ветке, которые затронули любой файл в каталоге `Documentation`.
+
----------
git rev-list HEAD -- Documentation/
----------

* Вывести список коммитов, автором которых являетесь вы за последний год, в любой ветке, метке или другой ссылке.
+
----------
git rev-list --author=you@example.com --since=1.year.ago --all
----------

* Вывести список объектов, достижимых из текущей ветки (т.е. всех коммитов и содержащихся в них blob-объектов и деревьев).
+
----------
git rev-list --objects HEAD
----------

* Сравнить размер на диске всех достижимых объектов с объектами, достижимыми из журналов ссылок, и с общим упакованным размером. Это может сказать вам, может ли выполнение `git repack -ad` уменьшить размер репозитория (за счёт удаления недостижимых объектов) и может ли помочь истечение срока действия журналов ссылок.
+
----------
# достижимые объекты
git rev-list --disk-usage --objects --all
# плюс журналы ссылок
git rev-list --disk-usage --objects --all --reflog
# общий используемый размер на диске
du -c .git/objects/pack/*.pack .git/objects/??/*
# альтернатива du: сложить поля "size" и "size-pack"
git count-objects -v
----------

* Сообщить размер на диске каждой ветки, не включая объекты, используемые текущей веткой. Это может найти выбросы, которые способствуют раздуванию размера репозитория (например, потому что кто-то случайно закоммитил большие артефакты сборки).
+
----------
git for-each-ref --format='%(refname)' |
while read branch
do
	size=$(git rev-list --disk-usage --objects HEAD..$branch)
	echo "$size $branch"
done |
sort -n
----------

* Сравнить размер на диске веток в одной группе ссылок, исключая другую. Если вы смешиваете объекты из нескольких внешних репозиториев в одном репозитории, это может показать, какие внешние репозитории вносят вклад в размер репозитория (принимая размер `origin` за базовый уровень).
+
----------
git rev-list --disk-usage --objects --remotes=$suspect --not --remotes=origin
----------

GIT
---
Является частью пакета linkgit:git[1]
