git-hash-object(1)
==================

НАЗВАНИЕ
--------
git-hash-object — Вычислить идентификатор объекта и, при желании, создать объект из файла


ОБЗОР
-----
[verse]
'git hash-object' [-t <тип>] [-w] [--path=<файл> | --no-filters]
		[--stdin [--literally]] [--] <файл>...
'git hash-object' [-t <тип>] [-w] --stdin-paths [--no-filters]

ОПИСАНИЕ
--------
Вычисляет значение идентификатора объекта для объекта указанного типа с содержимым именованного файла (который может находиться за пределами рабочего каталога) и опционально записывает результирующий объект в базу данных объектов. Сообщает свой идентификатор объекта в стандартный вывод. Если <тип> не указан, по умолчанию используется «blob».

ПАРАМЕТРЫ
---------

-t <тип>::
	Указывает тип создаваемого объекта (по умолчанию: "blob"). Возможные значения: `commit`, `tree`, `blob` и `tag`.

-w::
	Собственно произвести запись объекта в базу данных объектов.

--stdin::
	Читать объект из стандартного ввода вместо файла.

--stdin-paths::
	Читать имена файлов из стандартного ввода, по одному на строку, вместо командной строки.

--path::
	Хеширует объект так, как если бы он находился по указанному пути. Расположение файла напрямую не влияет на значение хеша, но путь используется для определения того, какие фильтры Git следует применить к объекту перед тем, как он может быть помещён в базу данных объектов. В результате применения фильтров фактический blob-объект, помещённый в базу данных объектов, может отличаться от данного файла. Этот параметр в основном полезен для хеширования временных файлов, находящихся за пределами рабочего каталога, или файлов, прочитанных из stdin.

--no-filters::
	Хеширует содержимое как есть, игнорируя любой входной фильтр, который мог бы быть выбран механизмом атрибутов, включая преобразование концов строк. Если файл читается из стандартного ввода, это всегда подразумевается, если только не указан параметр `--path`.

--literally::
	Позволяет `--stdin` хешировать любой мусор в несжатый объект, который в противном случае мог бы не проходить стандартный анализ объектов или проверки git-fsck. Полезно для нагрузочного тестирования самого Git или воспроизведения характеристик повреждённых или поддельных объектов, встречающихся в реальных условиях.

GIT
---
Является частью пакета linkgit:git[1]
