git-credential-store(1)
=======================

НАЗВАНИЕ
--------
git-credential-store - Вспомогательная программа для хранения учётных данных на диске

ОБЗОР
-----
-------------------
git config credential.helper 'store [<параметры>]'
-------------------

ОПИСАНИЕ
--------

NOTE: Использование этой вспомогательной программы будет хранить ваши пароли в нешифрованном виде на диске, защищённые только правами доступа файловой системы. Если это неприемлемый компромисс с точки зрения безопасности, попробуйте linkgit:git-credential-cache[1] или найдите вспомогательную программу, которая интегрируется с безопасным хранилищем, предоставляемым вашей операционной системой.

Эта команда сохраняет учётные данные на диске на неопределённый срок для использования будущими программами Git.

Вероятно, вы не захотите вызывать эту команду напрямую; она предназначена для использования в качестве вспомогательной программы для учётных данных другими частями git. Смотрите linkgit:gitcredentials[7] или `ПРИМЕРЫ` ниже.

ПАРАМЕТРЫ
---------

--file=<path>::

	Используйте `<путь>` для поиска и хранения учётных данных. Файл получит такие права доступа файловой системы, чтобы предотвратить его чтение другими пользователями системы, но он не будет зашифрован или иным образом защищён. Если не указано, учётные данные будут искаться в `~/.git-credentials` и `$XDG_CONFIG_HOME/git/credentials`, а учётные данные будут записаны в `~/.git-credentials`, если он существует, или в `$XDG_CONFIG_HOME/git/credentials`, если он существует, а первый нет. См. также <<ФАЙЛЫ>>.

[[FILES]]
ФАЙЛЫ
-----

Если явно не указано с помощью `--file`, существует два файла, в которых git-credential-store будет искать учётные данные в порядке приоритета:

~/.git-credentials::
	Файл учётных данных пользователя.

$XDG_CONFIG_HOME/git/credentials::
	Второй файл учётных данных пользователя. Если '$XDG_CONFIG_HOME' не задан или пуст, будет использоваться `$HOME/.config/git/credentials`. Любые учётные данные, хранящиеся в этом файле, не будут использоваться, если `~/.git-credentials` также имеет совпадающие учётные данные. Лучше не создавать этот файл, если вы иногда используете старые версии Git, которые его не поддерживают.

Для поиска учётных данных файлы читаются в порядке, указанном выше, причём первые найденные совпадающие учётные данные имеют приоритет над учётными данными, найденными в файлах ниже по списку.

Хранилище учётных данных по умолчанию будет записывать в первый существующий файл в списке. Если ни один из этих файлов не существует, будет создан и записан `~/.git-credentials`.

При стирании учётных данных совпадающие учётные данные будут стёрты из всех файлов.

ПРИМЕРЫ
-------

Смысл этой вспомогательной программы — уменьшить количество раз, когда вам нужно вводить имя пользователя или пароль. Например:

------------------------------------------
$ git config credential.helper store
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

[several days later]
$ git push http://example.com/repo.git
[your credentials are used automatically]
------------------------------------------

ФОРМАТ ХРАНЕНИЯ
---------------

Файл `.git-credentials` хранится в виде обычного текста. Каждые учётные данные хранятся в отдельной строке в виде URL, например:

------------------------------
https://user:pass@example.com
------------------------------

Никакие другие виды строк (например, пустые строки или строки комментариев) не допускаются в файле, даже если некоторые могут молча игнорироваться. Не просматривайте и не редактируйте файл с помощью редакторов.

Когда Git требует аутентификации для определённого контекста URL, credential-store будет рассматривать этот контекст как шаблон для сопоставления с каждой записью в файле учётных данных. Если протокол, имя хоста и имя пользователя (если оно у нас уже есть) совпадают, то пароль возвращается Git. Смотрите обсуждение конфигурации в linkgit:gitcredentials[7] для получения дополнительной информации.

GIT
---
Является частью пакета linkgit:git[1]
