git-http-push(1)
================

НАЗВАНИЕ
--------
git-http-push — Отправка объектов в другой репозиторий через HTTP/DAV


ОБЗОР
-----
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ссылка> [<ссылка>...]

ОПИСАНИЕ
--------
Отправляет недостающие объекты во внешний репозиторий и обновляет внешнюю ветку.

*ПРИМЕЧАНИЕ*: Эта команда временно отключена, если ваша libcurl старше 7.16, так как сообщалось, что эта комбинация не работает и иногда повреждает репозиторий.

ПАРАМЕТРЫ
---------
--all::
	Не предполагать, что внешний репозиторий является полным в своём текущем состоянии, и проверять, что все объекты в истории всей локальной ссылки существуют во внешнем репозитории.

--force::
	Обычно команда отказывается обновлять внешнюю ссылку, которая не является предком локальной ссылки, используемой для её перезаписи. Этот флаг отключает проверку. А это означает, что внешний репозиторий может потерять коммиты; используйте его с осторожностью.

--dry-run::
	Сделать всё, кроме фактической отправки обновлений.

--verbose::
	Сообщает список объектов, обрабатываемых локально, и список объектов, успешно отправленных во внешний репозиторий.

-d::
-D::
	Удалить <ссылку> из внешнего репозитория. Указанная ветка не может быть внешним HEAD. Если указан -d, должны также выполняться следующие условия:

	- Внешний HEAD должен преобразовываться в объект, который существует локально
	- Указанная ветка преобразовывается в объект, который существует локально
	- Указанная ветка является предком внешнего HEAD

<ref>...::
	Внешние ссылки для обновления.


ОПРЕДЕЛЕНИЕ ССЫЛОК
------------------

Спецификация '<ссылка>' может быть либо одним шаблоном, либо парой таких шаблонов, разделённых двоеточием ":" (это означает, что имя ссылки не может содержать двоеточие). Одиночный шаблон '<имя>' — это просто сокращение для '<имя>:<имя>'.

Каждая пара шаблонов '<src>:<dst>' состоит из исходной стороны (до двоеточия) и целевой стороны (после двоеточия). Отправляемая ссылка определяется путём поиска совпадения, соответствующего исходной стороне, а то, куда она отправляется, определяется с использованием целевой стороны.

 - Ошибкой является, если '<src>' не соответствует ровно одной из локальных ссылок.

 - Если '<dst>' не соответствует ни одной внешней ссылке, либо

   * он должен начинаться с «refs/»; <dst> используется буквально как назначение в этом случае.

   * <src> == <dst>, и ссылка, соответствующая <src>, не должна существовать в наборе внешних ссылок; ссылка, соответствующая <src> локально, используется в качестве имени назначения.

Без `--force` ссылка <src> сохраняется во внешнем репозитории, только если <dst> не существует или <dst> является собственным подмножеством (т.е. предком) <src>. Эта проверка, известная как "проверка перемотки вперёд", выполняется, чтобы случайно не перезаписать внешнюю ссылку и не потерять оттуда чужие коммиты.

С `--force` проверка перемотки вперёд отключена для всех ссылок.

Опционально, параметру <ссылка> может предшествовать знак плюса '+', чтобы отключить проверку перемотки вперёд только для этой ссылки.

GIT
---
Является частью пакета linkgit:git[1]
