git-quiltimport(1)
==================

НАЗВАНИЕ
--------
git-quiltimport — применение набора патчей quilt к текущей ветке


ОБЗОР
-----
[verse]
'git quiltimport' [--dry-run | -n] [--author <автор>] [--patches <каталог>]
		[--series <файл>] [--keep-non-patch]


ОПИСАНИЕ
--------
Применяет набор патчей quilt к текущей ветке Git, сохраняя границы патчей, порядок патчей и описания патчей, присутствующие в наборе патчей quilt.

Для каждого патча код пытается извлечь автора из описания патча. Если это не удаётся, он возвращается к автору, указанному с помощью --author. Если флаг --author не был указан, отображается описание патча, и пользователю предлагается интерактивно ввести автора патча.

Если тема не найдена в описании патча, имя патча сохраняется как однострочная тема в описании Git.

ПАРАМЕТРЫ
---------

-n::
--dry-run::
	Проходит по патчам в серии и предупреждает, если не может найти всю необходимую информацию для фиксации патча. На момент написания этого текста предупреждение выводится только об отсутствующей информации об авторе.

--author 'Имя Автора <Электронная-почта Автора>'::
	Имя автора и адрес электронной почты, используемые, когда в описании патча не удаётся найти информацию об авторе.

--patches <каталог>::
	Каталог для поиска патчей quilt.
+
По умолчанию для каталога патчей используется 'patches' или значение переменной среды `$QUILT_PATCHES`.

--series <файл>::
	Файл серии quilt.
+
По умолчанию для файла серии используется <patches>/series или значение переменной среды `$QUILT_SERIES`.

--keep-non-patch::
	Передаёт флаг `-b` в 'git mailinfo' (см. linkgit:git-mailinfo[1]).

GIT
---
Является частью пакета linkgit:git[1]
