git-instaweb(1)
===============

НАЗВАНИЕ
--------
git-instaweb — Мгновенный просмотр вашего рабочего репозитория в gitweb

ОБЗОР
-----
[verse]
'git instaweb' [--local] [--httpd=<httpd>] [--port=<порт>]
               [--browser=<браузер>]
'git instaweb' [--start] [--stop] [--restart]

ОПИСАНИЕ
--------
Простой сценарий для настройки `gitweb` и веб-сервера для просмотра локального репозитория.

ПАРАМЕТРЫ
---------

-l::
--local::
	Привязать веб-сервер только к локальному IP-адресу (127.0.0.1).

-d::
--httpd::
	Командная строка HTTP-демона, который будет выполнен. Здесь могут быть указаны параметры командной строки, а файл конфигурации будет добавлен в конец командной строки. В настоящее время поддерживаются apache2, lighttpd, mongoose, plackup, python и webrick. (По умолчанию: lighttpd)

-m::
--module-path::
	Путь к модулям (требуется только если httpd — Apache). (По умолчанию: /usr/lib/apache2/modules)

-p::
--port::
	Номер порта, к которому привязать httpd. (По умолчанию: 1234)

-b::
--browser::
	Веб-браузер, который следует использовать для просмотра страницы gitweb. Он будет передан вспомогательному сценарию 'git web{litdd}browse' вместе с URL-адресом экземпляра gitweb. Дополнительную информацию об этом см. в linkgit:git-web{litdd}browse[1]. Если сценарий завершится ошибкой, URL-адрес будет выведен в stdout.

старт::
--start::
	Запустить экземпляр httpd и выйти. При необходимости перегенерировать файлы конфигурации для запуска нового экземпляра.

стоп::
--stop::
	Остановить экземпляр httpd и выйти. Это не генерирует файлы конфигурации для запуска нового экземпляра и не закрывает браузер.

перезапуск::
--restart::
	Перезапустить экземпляр httpd и выйти. При необходимости перегенерировать файлы конфигурации для запуска нового экземпляра.

КОНФИГУРАЦИЯ
------------

Вы можете указать конфигурацию в вашем .git/config

-----------------------------------------------------------------------
[instaweb]
	local = true
	httpd = apache2 -f
	port = 4321
	browser = konqueror
	modulePath = /usr/lib/apache2/modules

-----------------------------------------------------------------------

Если переменная конфигурации `instaweb.browser` не установлена, вместо неё будет использоваться `web.browser`, если он определён. Дополнительную информацию об этом см. в linkgit:git-web{litdd}browse[1].

СМ. ТАКЖЕ
---------
linkgit:gitweb[1]

GIT
---
Является частью пакета linkgit:git[1]
