git-bugreport(1)
================

НАЗВАНИЕ
--------
git-bugreport — сбор информации для пользователя для сообщения об ошибке

ОБЗОР
-----
[verse]
'git bugreport' [(-o | --output-directory) <путь>]
		[(-s | --suffix) <формат> | --no-suffix]
		[--diagnose[=<режим>]]

ОПИСАНИЕ
--------
Собирает информацию о машине пользователя, клиенте Git и состоянии репозитория, а также форму, запрашивающую информацию о наблюдаемом поведении, и сохраняет её в одном текстовом файле, которым пользователь может затем поделиться, например, со списком рассылки Git, чтобы сообщить об обнаруженной ошибке.

У пользователя запрашивается следующая информация:

 - Шаги для воспроизведения
 - Ожидаемое поведение
 - Фактическое поведение

Следующая информация собирается автоматически:

 - 'git version --build-options'
 - строки uname sysname, release, version и machine
 - Строка информации, специфичной для компилятора
 - Список включённых перехватчиков
 - $SHELL

Дополнительная информация может быть собрана в отдельный zip-архив с помощью параметра `--diagnose` и может быть приложена к документу bugreport, чтобы предоставить читателям дополнительный контекст.

Этот инструмент вызывается через типичный процесс настройки Git, что означает, что в некоторых случаях он может не запуститься — например, если соответствующий файл конфигурации нечитаем. В таком сценарии может быть полезно вручную собрать информацию, указанную выше, при обращении за помощью.

ПАРАМЕТРЫ
---------
-o <путь>::
--output-directory <путь>::
	Поместить результирующий файл отчёта об ошибке в `<путь>` вместо текущего каталога.

-s <формат>::
--suffix <формат>::
--no-suffix::
	Указывает альтернативный суффикс для имени отчёта об ошибке, чтобы создать файл с именем 'git-bugreport-<отформатированный-суффикс>'. Это должна быть строка формата strftime(3); будет использоваться текущее локальное время. `--no-suffix` отключает суффикс, и файл называется просто `git-bugreport` без каких-либо мер по устранению неоднозначности.

--no-diagnose::
--diagnose[=<режим>]::
	Создаёт zip-архив дополнительной информации о машине пользователя, клиенте Git и состоянии репозитория. Архив записывается в тот же выходной каталог, что и отчёт об ошибке, и называется 'git-diagnostics-<отформатированный-суффикс>'.
+
Без указания `режима` диагностический архив будет содержать стандартный набор статистики, сообщаемой `git diagnose`. Может быть указано необязательное значение `режима`, чтобы изменить, какая информация включается в архив. Список допустимых значений для `режима` и подробности их использования см. в linkgit:git-diagnose[1].

GIT
---
Является частью пакета linkgit:git[1]
