git-merge(1)
============

НАЗВАНИЕ
--------
git-merge - Объединение одной или нескольких историй разработки вместе


ОБЗОР
-----
[synopsis]
git merge [-n] [--stat] [--compact-summary] [--no-commit] [--squash] [--[no-]edit]
	[--no-verify] [-s <стратегия>] [-X <параметр-стратегии>] [-S[<id-ключа>]]
	[--[no-]allow-unrelated-histories]
	[--[no-]rerere-autoupdate] [-m <сообщение>] [-F <файл>]
	[--into-name <ветка>] [<коммит>...]
git merge (--continue | --abort | --quit)

ОПИСАНИЕ
--------
Включает изменения из указанных коммитов (с момента расхождения их историй с текущей веткой) в текущую ветку. Эта команда используется `git pull` для включения изменений из другого репозитория и может использоваться вручную для слияния изменений из одной ветки в другую.

Предположим, существует следующая история, и текущая ветка — `master`:

------------
          A---B---C topic
         /
    D---E---F---G master
------------

Затем `git merge topic` повторно применит изменения, сделанные в ветке `topic` с момента её расхождения с `master` (т.е. `E`) до её текущего коммита (`C`), поверх `master`, и запишет результат в новый коммит вместе с именами двух родительских коммитов и сообщением журнала от пользователя, описывающим изменения. Перед операцией `ORIG_HEAD` устанавливается на верхушку (tip) текущей ветки (`G`).

------------
          A---B---C topic
         /         \
    D---E---F---G---H master
------------

Слияние останавливается, если возникает конфликт, который не может быть разрешён автоматически, или если при инициировании слияния был указан `--no-commit`. В этот момент вы можете выполнить `git merge --abort` или `git merge --continue`.

`git merge --abort` прервёт процесс слияния и попытается восстановить состояние до слияния. Однако, если на момент начала слияния были незафиксированные изменения (и особенно если эти изменения были дополнительно изменены после начала слияния), `git merge --abort` в некоторых случаях не сможет восстановить исходные (до слияния) изменения. Поэтому:

WARNING: Выполнение `git merge` с нетривиальными незафиксированными изменениями не рекомендуется: хотя это возможно, в случае конфликта вы можете оказаться в состоянии, из которого трудно выбраться.

ПАРАМЕТРЫ
---------
:git-merge: 1

include::merge-options.adoc[]

`-m <сообщение>`::
	Установить сообщение коммита, которое будет использовано для коммита слияния (если он создаётся).
+
Если указан `--log`, к указанному сообщению будет добавлен краткий журнал (shortlog) сливаемых коммитов.
+
Команда `git fmt-merge-msg` может использоваться для создания хорошего значения по умолчанию для автоматических вызовов `git merge`. Автоматическое сообщение может включать описание ветки.

`--into-name <ветка>`::
	Подготовить сообщение слияния по умолчанию так, как если бы слияние выполнялось в ветку _<ветка>_, вместо имени реальной ветки, в которую выполняется слияние.

`-F <файл>`::
`--file=<файл>`::
	Прочитать сообщение коммита, которое будет использовано для коммита слияния (если он создаётся).
+
Если указан `--log`, к указанному сообщению будет добавлен краткий журнал (shortlog) сливаемых коммитов.

include::rerere-options.adoc[]

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	Незаметно перезаписывать игнорируемые файлы из результата слияния. Это поведение по умолчанию. Используйте `--no-overwrite-ignore`, чтобы прервать операцию.

`--abort`::
	Прервать текущий процесс разрешения конфликта и попытаться восстановить состояние до слияния. Если присутствует запись автоатайника (autostash), применить её к рабочему каталогу.
+
Если на момент начала слияния присутствовали незафиксированные изменения в рабочем каталоге, `git merge --abort` в некоторых случаях не сможет восстановить эти изменения. Поэтому рекомендуется всегда фиксировать или прятать (stash) свои изменения перед запуском `git merge`.
+
`git merge --abort` эквивалентен `git reset --merge`, когда присутствует `MERGE_HEAD`, если только также не присутствует `MERGE_AUTOSTASH`, и в этом случае `git merge --abort` применяет запись из тайника (stash) к рабочему каталогу, тогда как `git reset --merge` сохранит спрятанные изменения в списке тайников.

`--quit`::
	Забыть о текущем процессе слияния. Оставить индекс и рабочий каталог в текущем состоянии. Если присутствует `MERGE_AUTOSTASH`, запись из тайника будет сохранена в список тайников.

`--continue`::
	После остановки `git merge` из-за конфликтов вы можете завершить слияние, выполнив `git merge --continue` (см. раздел «КАК РАЗРЕШАТЬ КОНФЛИКТЫ» ниже).

`<коммит>...`::
	Коммиты, обычно головы других веток, для слияния в нашу ветку. Указание более одного коммита создаст слияние с более чем двумя родителями (ласково называемое слиянием Octopus).
+
Если коммит не указан в командной строке, выполнить слияние отслеживаемых внешних веток, которые текущая ветка настроена использовать в качестве своей вышестоящей (upstream) ветки. См. также раздел конфигурации этой справочной страницы.
+
Когда указан `FETCH_HEAD` (и никакой другой коммит), ветки, записанные в файле `.git/FETCH_HEAD` предыдущим вызовом `git fetch` для слияния, сливаются с текущей веткой.


ПРОВЕРКИ ПЕРЕД СЛИЯНИЕМ
-----------------------

Перед применением внешних изменений вы должны привести свою работу в порядок и зафиксировать её локально, чтобы она не была затёрта в случае конфликтов. См. также linkgit:git-stash[1]. `git pull` и `git merge` остановятся без каких-либо действий, когда локальные незафиксированные изменения пересекаются с файлами, которые `git pull`/`git merge` могут потребовать обновить.

Чтобы избежать записи несвязанных изменений в коммит слияния, `git pull` и `git merge` также прервутся, если в индексе есть какие-либо изменения относительно коммита `HEAD`. (В зависимости от используемой стратегии слияния могут существовать особые узкие исключения из этого правила, но обычно индекс должен соответствовать `HEAD`.)

Если все указанные коммиты уже являются предками `HEAD`, `git merge` завершится досрочно с сообщением «Уже актуально.» (Already up to date.)

СЛИЯНИЕ ПЕРЕМОТКОЙ ВПЕРЁД
-------------------------

Часто голова текущей ветки является предком указанного коммита. Это самый распространённый случай, особенно при вызове из `git pull`: вы отслеживаете вышестоящий (upstream) репозиторий, у вас нет зафиксированных локальных изменений, и теперь вы хотите обновиться до более новой вышестоящей редакции. В этом случае новый коммит не нужен для хранения объединённой истории; вместо этого `HEAD` (вместе с индексом) обновляется, чтобы указывать на указанный коммит, без создания дополнительного коммита слияния.

Это поведение можно подавить с помощью опции `--no-ff`.

ИСТИННОЕ СЛИЯНИЕ
----------------

За исключением слияния перемоткой вперёд (см. выше), сливаемые ветки должны быть связаны коммитом слияния, у которого обе они являются родителями.

Фиксируется объединённая версия, согласовывающая изменения из всех сливаемых веток, и ваш `HEAD`, индекс и рабочий каталог обновляются до неё. Допустимо наличие изменений в рабочем каталоге, если они не пересекаются; обновление сохранит их.

Когда неочевидно, как согласовать изменения, происходит следующее:

1. Указатель `HEAD` остаётся тем же.
2. Ссылка `MERGE_HEAD` устанавливается указывать на голову другой ветки.
3. Пути, которые слились чисто, обновляются как в файле индекса, так и в вашем рабочем каталоге.
4. Для конфликтующих путей файл индекса хранит до трёх версий: этап 1 хранит версию от общего предка, этап 2 от `HEAD`, а этап 3 от `MERGE_HEAD` (вы можете просмотреть этапы с помощью `git ls-files -u`). Файлы рабочего каталога содержат результат операции слияния; т.е. результаты трёхстороннего слияния со знакомыми маркерами конфликтов +<<<+ `===` +>>>+.
5. Записывается ссылка с именем `AUTO_MERGE`, указывающая на дерево, соответствующее текущему содержимому рабочего каталога (включая маркеры конфликтов для текстовых конфликтов). Обратите внимание, что эта ссылка записывается только при использовании стратегии слияния `ort` (по умолчанию).
6. Никаких других изменений не делается. В частности, локальные изменения, которые у вас были до начала слияния, останутся такими же, и записи индекса для них останутся такими, как были, т.е. соответствующими `HEAD`.

Если вы попытались выполнить слияние, которое привело к сложным конфликтам, и хотите начать заново, вы можете восстановиться с помощью `git merge --abort`.

СЛИЯНИЕ МЕТКИ
-------------

При слиянии аннотированной (и, возможно, подписанной) метки Git всегда создаёт коммит слияния, даже если возможно слияние перемоткой вперёд, и шаблон сообщения коммита подготавливается с сообщением метки. Кроме того, если метка подписана, проверка подписи сообщается как комментарий в шаблоне сообщения. См. также linkgit:git-tag[1].

Когда вы хотите просто интегрироваться с работой, ведущей к коммиту, который оказался помеченным, например, синхронизируясь с точкой вышестоящего (upstream) выпуска, вы можете не захотеть создавать ненужный коммит слияния.

В таком случае вы можете самостоятельно «развернуть» метку перед передачей её в `git merge` или передать `--ff-only`, если у вас нет своей работы. например

----
git fetch origin
git merge v1.2.3^0
git merge --ff-only v1.2.3
----

КАК ПРЕДСТАВЛЯЮТСЯ КОНФЛИКТЫ
----------------------------

Во время слияния файлы рабочего каталога обновляются, чтобы отразить результат слияния. Среди изменений, внесённых в версию общего предка, непересекающиеся (то есть вы изменили область файла, в то время как другая сторона оставила эту область нетронутой, или наоборот) включаются в конечный результат дословно. Однако, когда обе стороны внесли изменения в одну и ту же область, Git не может случайным образом выбрать одну сторону над другой и просит вас разрешить это, оставляя то, что обе стороны сделали с этой областью.

По умолчанию Git использует тот же стиль, что и программа «merge» из набора RCS, для представления такого конфликтного блока, например:

------------
Вот строки, которые либо не изменились по сравнению с общим
предком, либо чисто разрешены, потому что изменилась только одна сторона,
либо чисто разрешены, потому что обе стороны изменились одинаково.
<<<<<<< yours:sample.txt
Разрешение конфликтов — это сложно;
пойдём по магазинам.
=======
Git делает разрешение конфликтов лёгким.
>>>>>>> theirs:sample.txt
А вот другая строка, которая либо чисто разрешена, либо не изменена.
------------

Область, где произошла пара конфликтующих изменений, помечена маркерами +<<<<<<<+, `=======` и +>>>>>>>+. Часть до `=======` обычно представляет вашу сторону, а часть после — их сторону.

Формат по умолчанию не показывает, что говорилось в исходном тексте в конфликтующей области. Вы не можете сказать, сколько строк удалено и заменено на замечание Барби с вашей стороны. Единственное, что вы можете сказать, это то, что ваша сторона хочет сказать, что это сложно, и вы предпочли бы пойти по магазинам, в то время как другая сторона хочет утверждать, что это легко.

Альтернативный стиль можно использовать, установив переменную конфигурации `merge.conflictStyle` в `diff3` или `zdiff3`. В стиле `diff3` вышеуказанный конфликт может выглядеть так:

------------
Вот строки, которые либо не изменились по сравнению с общим
предком, либо чисто разрешены, потому что изменилась только одна сторона,
<<<<<<< yours:sample.txt
либо чисто разрешены, потому что обе стороны изменились одинаково.
Разрешение конфликтов — это сложно;
пойдём по магазинам.
||||||| base:sample.txt
либо чисто разрешены, потому что обе стороны изменились идентично.
Разрешение конфликтов — это сложно.
=======
либо чисто разрешены, потому что обе стороны изменились одинаково.
Git делает разрешение конфликтов лёгким.
>>>>>>> theirs:sample.txt
А вот другая строка, которая либо чисто разрешена, либо не изменена.
------------

тогда как в стиле `zdiff3` это может выглядеть так:

------------
Вот строки, которые либо не изменились по сравнению с общим
предком, либо чисто разрешены, потому что изменилась только одна сторона,
либо чисто разрешены, потому что обе стороны изменились одинаково.
<<<<<<< yours:sample.txt
Разрешение конфликтов — это сложно;
пойдём по магазинам.
||||||| base:sample.txt
либо чисто разрешены, потому что обе стороны изменились идентично.
Разрешение конфликтов — это сложно.
=======
Git делает разрешение конфликтов лёгким.
>>>>>>> theirs:sample.txt
А вот другая строка, которая либо чисто разрешена, либо не изменена.
------------

В дополнение к маркерам +<<<<<<<+, `=======` и +>>>>>>>+ он использует ещё один маркер +|||||||+, за которым следует исходный текст. Вы можете сказать, что исходный текст просто констатировал факт, а ваша сторона просто согласилась с этим утверждением и сдалась, в то время как другая сторона попыталась иметь более позитивный настрой. Иногда вы можете придумать лучшее разрешение, просмотрев исходный текст.


КАК РАЗРЕШАТЬ КОНФЛИКТЫ
-----------------------

Увидев конфликт, вы можете сделать две вещи:

 * Решить не сливать. Единственная необходимая очистка — сбросить файл индекса до коммита `HEAD`, чтобы отменить шаг 2, и очистить изменения в рабочем каталоге, сделанные на шагах 2 и 3; для этого можно использовать `git merge --abort`.

 * Разрешить конфликты. Git отметит конфликты в рабочем каталоге. Отредактируйте файлы в нужную форму и выполните `git add` для них в индекс. Используйте `git commit` или `git merge --continue`, чтобы завершить дело. Последняя команда проверяет, есть ли (прерванное) слияние в процессе, перед вызовом `git commit`.

Вы можете проработать конфликт с помощью ряда инструментов:

 * Используйте инструмент слияния (mergetool). `git mergetool` запускает графический инструмент слияния, который проведёт вас через слияние.

 * Посмотрите на различия. `git diff` покажет трёхстороннее сравнение, выделяя изменения как из версии `HEAD`, так и из `MERGE_HEAD`. `git diff AUTO_MERGE` покажет, какие изменения вы внесли на данный момент для разрешения текстовых конфликтов.

 * Посмотрите на различия из каждой ветки. `git log --merge -p <путь>` покажет различия сначала для версии `HEAD`, а затем для версии `MERGE_HEAD`.

 * Посмотрите на оригиналы. `git show :1:имя_файла` показывает общего предка, `git show :2:имя_файла` показывает версию `HEAD`, а `git show :3:имя_файла` показывает версию `MERGE_HEAD`.


ПРИМЕРЫ
-------

* Выполнить слияние веток `fixes` и `enhancements` поверх текущей ветки, создавая слияние octopus:
+
------------------------------------------------
$ git merge fixes enhancements
------------------------------------------------

* Выполнить слияние ветки `obsolete` в текущую ветку, используя стратегию слияния `ours` (наша):
+
------------------------------------------------
$ git merge -s ours obsolete
------------------------------------------------

* Выполнить слияние ветки `maint` в текущую ветку, но не создавать новый коммит автоматически:
+
------------------------------------------------
$ git merge --no-commit maint
------------------------------------------------
+
Это можно использовать, когда вы хотите включить дополнительные изменения в слияние или написать собственное сообщение коммита слияния.
+
Вам следует воздерживаться от злоупотребления этим параметром, чтобы протаскивать существенные изменения в коммит слияния. Небольшие исправления, такие как изменение имени выпуска/версии, будут приемлемы.


include::merge-strategies.adoc[]

КОНФИГУРАЦИЯ
------------

`branch.<имя>.mergeOptions`::
	Устанавливает параметры по умолчанию для слияния в ветку _<имя>_. Синтаксис и поддерживаемые параметры такие же, как в `git merge`, но значения параметров, содержащие пробельные символы, в настоящее время не поддерживаются.

include::includes/cmd-config-section-rest.adoc[]

include::config/merge.adoc[]

СМОТРИТЕ ТАКЖЕ
--------------
linkgit:git-fmt-merge-msg[1], linkgit:git-pull[1], linkgit:gitattributes[5], linkgit:git-reset[1], linkgit:git-diff[1], linkgit:git-ls-files[1], linkgit:git-add[1], linkgit:git-rm[1], linkgit:git-mergetool[1]

GIT
---
Является частью пакета linkgit:git[1]
