git-rev-parse(1)
================

НАЗВАНИЕ
--------
git-rev-parse — выделение и преобразование параметров


ОБЗОР
-----
[verse]
'git rev-parse' [<параметры>] <аргумент>...

ОПИСАНИЕ
--------

Многие команды Git (фарфороподобные) принимают смесь флагов (т.е. параметров, начинающихся с дефиса '-') и параметров, предназначенных для нижележащей команды 'git rev-list', которую они используют внутренне, а также флагов и параметров для других команд, которые они используют после 'git rev-list'. Основная цель этой команды — позволить вызывающим программам различать их. Существует несколько других режимов работы, не связанных с вышеупомянутой "помощью в анализе параметров командной строки".

Если не указано иное, большинство параметров и режимов работы требуют, чтобы вы запускали эту команду внутри репозитория git или рабочего каталога, находящегося под управлением репозитория git, и в противном случае выдадут критическую ошибку.


ПАРАМЕТРЫ
---------

Режимы работы
~~~~~~~~~~~~~

Каждый из этих параметров должен появляться первым в командной строке.

--parseopt::
	Использовать 'git rev-parse' в режиме анализа параметров (см. раздел PARSEOPT ниже). Команда в этом режиме может использоваться вне репозитория или рабочего каталога, контролируемого репозиторием.

--sq-quote::
	Использовать 'git rev-parse' в режиме цитирования оболочки (см. раздел SQ-QUOTE ниже). В отличие от параметра `--sq` ниже, этот режим только добавляет кавычки. Больше ничего не делается с вводом команды. Команда в этом режиме может использоваться вне репозитория или рабочего каталога, контролируемого репозиторием.

Параметры для --parseopt
~~~~~~~~~~~~~~~~~~~~~~~~

--keep-dashdash::
	Имеет смысл только в режиме `--parseopt`. Указывает анализатору параметров выводить первый встреченный `--` вместо его пропуска.

--stop-at-non-option::
	Имеет смысл только в режиме `--parseopt`. Позволяет анализатору параметров останавливаться на первом аргументе, не являющемся параметром. Это можно использовать для анализа подкоманд, которые сами принимают параметры.

--stuck-long::
	Имеет смысл только в режиме `--parseopt`. Выводить параметры в их длинной форме, если доступно, и с прикреплёнными аргументами.

Параметры для фильтрации
~~~~~~~~~~~~~~~~~~~~~~~~

--revs-only::
	Не выводить флаги и параметры, не предназначенные для команды 'git rev-list'.

--no-revs::
	Не выводить флаги и параметры, предназначенные для команды 'git rev-list'.

--flags::
	Не выводить параметры, не являющиеся флагами.

--no-flags::
	Не выводить параметры-флаги.

Параметры для вывода
~~~~~~~~~~~~~~~~~~~~

--default <аргумент>::
	Если пользователь не указал параметр, использовать вместо него `<аргумент>`.

--prefix <аргумент>::
	Вести себя так, как если бы 'git rev-parse' был вызван из подкаталога `<аргумент>` рабочего каталога. Любые относительные имена файлов разрешаются так, как если бы к ним был добавлен префикс `<аргумент>`, и будут выведены в этой форме.
+
Это можно использовать для преобразования аргументов команды, запускаемой в подкаталоге, чтобы их можно было использовать после перемещения на верхний уровень репозитория. Например:
+
----
префикс=$(git rev-parse --show-prefix)
cd "$(git rev-parse --show-toplevel)"
# rev-parse предоставляет --, необходимый для 'set'
eval "set $(git rev-parse --sq --prefix "$префикс" -- "$@")"
----

--verify::
	Проверить, что предоставлен ровно один параметр и что он может быть преобразован в необработанный 20-байтовый SHA-1, который можно использовать для доступа к базе данных объектов. Если это так, вывести его в стандартный вывод; в противном случае завершиться ошибкой.
+
Если вы хотите убедиться, что вывод действительно именует объект в вашей базе данных объектов и/или может использоваться как определённый тип объекта, который вам требуется, вы можете добавить к параметру оператор снятия шелухи `^{тип}`. Например, `git rev-parse "$VAR^{commit}"` гарантирует, что `$VAR` именует существующий объект, являющийся указателем коммита (т.е. коммит или аннотированную метку, указывающую на коммит). Чтобы убедиться, что `$VAR` именует существующий объект любого типа, можно использовать `git rev-parse "$VAR^{object}"`.
+
Обратите внимание, что если вы проверяете имя из недоверенного источника, разумно использовать `--end-of-options`, чтобы аргумент имени не был принят за другой параметр.

-q::
--quiet::
	Имеет смысл только в режиме `--verify`. Не выводить сообщение об ошибке, если первый аргумент не является допустимым именем объекта; вместо этого молча завершиться с ненулевым статусом. SHA-1 для допустимых имён объектов выводятся в stdout в случае успеха.

--sq::
	Обычно вывод состоит из одной строки на флаг и параметр. Этот параметр делает вывод одной строкой, правильно заключённой в кавычки для использования оболочкой. Полезно, когда вы ожидаете, что ваш параметр будет содержать пробелы и символы новой строки (например, при использовании pickaxe `-S` с 'git diff-{asterisk}'). В отличие от параметра `--sq-quote`, ввод команды по-прежнему интерпретируется как обычно.

--short[=<длина>]::
	То же, что и `--verify`, но сокращает имя объекта до уникального префикса длиной не менее `длина` символов. Минимальная длина — 4, значение по умолчанию — эффективное значение переменной конфигурации `core.abbrev` (см. linkgit:git-config[1]).

--not::
	При показе имён объектов добавлять к ним префикс '{caret}' и удалять префикс '{caret}' из имён объектов, которые уже имеют его.

--abbrev-ref[=(strict|loose)]::
	Неоднозначное короткое имя объекта. Параметр core.warnAmbiguousRefs используется для выбора строгого режима сокращения.

--symbolic::
	Обычно имена объектов выводятся в форме SHA-1 (с возможным префиксом '{caret}'); этот параметр заставляет выводить их в форме, максимально близкой к исходному вводу.

--symbolic-full-name::
	Это похоже на --symbolic, но опускает ввод, который не является ссылками (т.е. имена веток или меток; или более явно устраняющая неоднозначность форма "heads/master", когда вы хотите назвать ветку "master", когда существует неудачно названная метка "master"), и показывает их как полные имена ссылок (например, "refs/heads/master").

--output-object-format=(sha1|sha256|storage)::

	Разрешить ввод oid из любого формата объектов, который поддерживает текущий репозиторий.
+
Указание «sha1» переводит при необходимости и возвращает oid sha1.
+
Указание «sha256» переводит при необходимости и возвращает oid sha256.
+
Указание «storage» переводит при необходимости и возвращает oid, закодированный в алгоритме хеша хранения.

Параметры для объектов
~~~~~~~~~~~~~~~~~~~~~~

--all::
	Показать все ссылки, найденные в `refs/`.

--branches[=<шаблон>]::
--tags[=<шаблон>]::
--remotes[=<шаблон>]::
	Показать все ветки, метки или отслеживаемые внешние ветки соответственно (т.е. ссылки, найденные в `refs/heads`, `refs/tags` или `refs/remotes` соответственно).
+
Если указан `шаблон`, показываются только ссылки, соответствующие данному glob-шаблону оболочки. Если шаблон не содержит символа подстановки (`?`, `*` или `[`), он превращается в сопоставление префикса путём добавления `/*`.

--glob=<шаблон>::
	Показать все ссылки, соответствующие glob-шаблону оболочки `шаблон`. Если шаблон не начинается с `refs/`, это добавляется автоматически. Если шаблон не содержит символа подстановки (`?`, `*` или `[`), он превращается в сопоставление префикса путём добавления `/*`.

--exclude=<glob-шаблон>::
	Не включать ссылки, соответствующие '<шаблон-glob>', которые в противном случае учитывались бы следующим параметром `--all`, `--branches`, `--tags`, `--remotes` или `--glob`. Повторения этого параметра накапливают шаблоны исключения до следующего параметра `--all`, `--branches`, `--tags`, `--remotes` или `--glob` (другие параметры или аргументы не очищают накопленные шаблоны).
+
Заданные шаблоны не должны начинаться с `refs/heads`, `refs/tags` или `refs/remotes` при применении к `--branches`, `--tags` или `--remotes` соответственно, и они должны начинаться с `refs/` при применении к `--glob` или `--all`. Если подразумевается завершающий '/{asterisk}', он должен быть указан явно.

--exclude-hidden=(fetch|receive|uploadpack)::
	Не включать ссылки, которые были бы скрыты `git-fetch`, `git-receive-pack` или `git-upload-pack` путём обращения к соответствующей конфигурации `fetch.hideRefs`, `receive.hideRefs` или `uploadpack.hideRefs` вместе с `transfer.hideRefs` (см. linkgit:git-config[1]). Этот параметр влияет на следующий параметр псевдоссылки `--all` или `--glob` и очищается после их обработки.

--disambiguate=<prefix>::
	Показать каждый объект, имя которого начинается с указанного префикса. <префикс> должен иметь длину не менее 4 шестнадцатеричных цифр, чтобы случайно не перечислить каждый объект в репозитории.

Параметры для файлов
~~~~~~~~~~~~~~~~~~~~

--local-env-vars::
	Перечислить переменные среды GIT_*, которые являются локальными для репозитория (например, GIT_DIR или GIT_WORK_TREE, но не GIT_EDITOR). Перечисляются только имена переменных, а не их значения, даже если они установлены.

--path-format=(absolute|relative)::
	Управляет поведением некоторых других параметров. Если указано как absolute, пути, выводимые этими параметрами, будут абсолютными и каноническими. Если указано как relative, пути будут относительными относительно текущего рабочего каталога, если это возможно. Значение по умолчанию зависит от параметра.
+
Этот параметр может быть указан несколько раз и влияет только на аргументы, которые следуют за ним в командной строке, либо до конца командной строки, либо до следующего экземпляра этого параметра.

Следующие параметры изменяются с помощью `--path-format`:

--git-dir::
	Показать `$GIT_DIR`, если определён. В противном случае показать путь к каталогу .git. Показанный путь, если он относительный, является относительным относительно текущего рабочего каталога.
+
Если `$GIT_DIR` не определён и текущий каталог не обнаружен в репозитории Git или рабочем каталоге, вывести сообщение в stderr и завершиться с ненулевым статусом.

--git-common-dir::
	Показать `$GIT_COMMON_DIR`, если определён, иначе `$GIT_DIR`.

--resolve-git-dir <путь>::
	Проверить, является ли <путь> допустимым репозиторием или git-файлом, указывающим на допустимый репозиторий, и вывести местоположение репозитория. Если <путь> является git-файлом, выводится разрешённый путь к реальному репозиторию.

--git-path <путь>::
	Разрешает "$GIT_DIR/<путь>" и учитывает другие переменные перемещения путей, такие как $GIT_OBJECT_DIRECTORY, $GIT_INDEX_FILE... Например, если $GIT_OBJECT_DIRECTORY установлен в /foo/bar, то "git rev-parse --git-path objects/abc" вернёт /foo/bar/abc.

--show-toplevel::
	Показать (по умолчанию абсолютный) путь к верхнему каталогу рабочего каталога. Если рабочего каталога нет, сообщить об ошибке.

--show-superproject-working-tree::
	Показать абсолютный путь к корню рабочего каталога суперпроекта (если существует), который использует текущий репозиторий в качестве своего подмодуля. Не выводит ничего, если текущий репозиторий не используется в качестве подмодуля ни одним проектом.

--shared-index-path::
	Показать путь к общему файлу индекса в режиме разделённого индекса или пустую строку, если не в режиме разделённого индекса.

На следующие параметры `--path-format` не влияет:

--absolute-git-dir::
	Как `--git-dir`, но его вывод всегда является канонизированным абсолютным путем.

--is-inside-git-dir::
	Если текущий рабочий каталог находится ниже каталога репозитория, вывести "true", в противном случае "false".

--is-inside-work-tree::
	Если текущий рабочий каталог находится внутри рабочего каталога репозитория, вывести "true", в противном случае "false".

--is-bare-repository::
	Если репозиторий голый, вывести «true», в противном случае «false».

--is-shallow-repository::
	Если репозиторий частичный, вывести «true», в противном случае «false».

--show-cdup::
	Когда команда вызывается из подкаталога, показать путь к верхнему каталогу относительно текущего каталога (обычно последовательность "../" или пустая строка).

--show-prefix::
	Когда команда вызывается из подкаталога, показать путь текущего каталога относительно верхнего каталога.

--show-object-format[=(storage|input|output|compat)]::
	Показать формат объекта (алгоритм хеша), используемый для репозитория для хранения внутри каталога `.git`, ввода, вывода или совместимости. Для ввода может быть выведено несколько алгоритмов, разделённых пробелами. Если запрошен `compat` и не включён ни один алгоритм совместимости, выводится пустая строка. Если не указано, по умолчанию используется «storage».

--show-ref-format::
	Показать формат хранения ссылок, используемый во внешнем репозитории.


Другие параметры
~~~~~~~~~~~~~~~~

--since=<строка-даты>::
--after=<строка-даты>::
	Проанализировать строку даты и вывести соответствующий параметр --max-age= для 'git rev-list'.

--until=<строка-даты>::
--before=<строка-даты>::
	Проанализировать строку даты и вывести соответствующий параметр --min-age= для 'git rev-list'.

<аргумент>...::
	Флаги и параметры для анализа.


include::revisions.adoc[]

PARSEOPT
--------

В режиме `--parseopt` 'git rev-parse' помогает преобразовывать параметры, предоставляя сценариям оболочки те же возможности, что и встроенные функции C. Он работает как нормализатор параметров (например, разделяет одиночные переключатели, агрегирует значения), немного похоже на `getopt(1)`.

Он принимает из стандартного ввода спецификацию параметров для анализа и понимания и выводит в стандартный вывод строку, подходящую для `eval` `sh(1)`, чтобы заменить аргументы нормализованными. В случае ошибки он выводит использование в стандартный поток ошибок и завершается с кодом 129.

Примечание: Убедитесь, что вы заключаете результат в кавычки при передаче его в `eval`. Пример см. ниже.

Формат ввода
~~~~~~~~~~~~

Формат ввода 'git rev-parse --parseopt' полностью основан на тексте. Он имеет две части, разделённые строкой, содержащей только `--`. Строки перед разделителем (должна быть одна или несколько) используются для описания использования. Строки после разделителя описывают параметры.

Каждая строка параметров имеет следующий формат:

------------
<спецификация-параметра><флаги>*<подсказка-аргумента>? SP+ справка LF
------------

`<opt-spec>`::
	её формат: символ короткого параметра, затем длинное имя параметра, разделённые запятой. Обе части не обязательны, хотя необходима хотя бы одна. Не может содержать ни одного из символов `<флаги>`. `h,help`, `dry-run` и `f` являются примерами правильной `<спецификация-параметра>`.

`<flags>`::
	`<флаги>` могут быть `*`, `=`, `?` или `!`.
	* Используйте `=`, если параметр принимает аргумент.

	* Используйте `?`, чтобы указать, что параметр принимает необязательный аргумент. Вероятно, вы захотите использовать режим `--stuck-long`, чтобы иметь возможность однозначно анализировать необязательный аргумент.

	* Используйте `*`, чтобы указать, что этот параметр не должен перечисляться в использовании, генерируемом для аргумента `-h`. Он показывается для `--help-all`, как описано в linkgit:gitcli[7].

	* Используйте `!`, чтобы не делать доступным соответствующий отрицающий длинный параметр.

`<arg-hint>`::
	`<подсказка-аргумента>`, если указана, используется как имя аргумента в выводе справки для параметров, принимающих аргументы. `<подсказка-аргумента>` завершается первым пробелом. Принято использовать дефис для разделения слов в многословной подсказке аргумента.

Остаток строки после удаления пробелов используется как справка, связанная с параметром.

Пустые строки игнорируются, а строки, не соответствующие этой спецификации, используются как заголовки групп параметров (начинайте строку с пробела, чтобы намеренно создать такие строки).

Пример
~~~~~~

------------
СПЕЦИФИКАЦИЯ_ПАРАМЕТРОВ="\
некоторая-команда [<параметры>] <аргументы>...

некоторая-команда делает foo и bar!
--
h,help! показать справку

foo какой-то отличный параметр --foo bar= какой-то классный параметр --bar с аргументом baz=arg другой классный параметр --baz с именованным аргументом qux?path qux может принимать аргумент пути, но имеет значение сам по себе

  Заголовок группы параметров
C?        параметр C с необязательным аргументом"

eval "$(echo "$СПЕЦИФИКАЦИЯ_ПАРАМЕТРОВ" | git rev-parse --parseopt -- "$@" || echo exit $?)"
------------


Текст использования
~~~~~~~~~~~~~~~~~~~

Когда `"$@"` в приведённом выше примере равно `-h` или `--help`, будет показан следующий текст использования:

------------
использование: некоторая-команда [<параметры>] <аргументы>...

    некоторая-команда делает foo и bar!

    -h, --help            показать справку
    --[no-]foo            какой-то отличный параметр --foo
    --[no-]bar ...        какой-то классный параметр --bar с аргументом
    --[no-]baz <arg>      другой классный параметр --baz с именованным аргументом
    --[no-]qux[=<путь>]   qux может принимать аргумент пути, но имеет значение сам по себе

Заголовок группы параметров
    -C[...]               параметр C с необязательным аргументом
------------

SQ-QUOTE
--------

В режиме `--sq-quote` 'git rev-parse' выводит в стандартный вывод одну строку, подходящую для `eval` `sh(1)`. Эта строка создаётся путём нормализации аргументов, следующих за `--sq-quote`. Ничего, кроме добавления кавычек к аргументам, не делается.

Если вы хотите, чтобы ввод команды по-прежнему интерпретировался как обычно 'git rev-parse' перед тем, как вывод будет заключён в кавычки оболочкой, см. параметр `--sq`.

Пример
~~~~~~

------------
$ cat >ваш-git-сценарий.sh <<\EOF
#!/bin/sh
args=$(git rev-parse --sq-quote "$@")   # заключить в кавычки предоставленные пользователем аргументы
command="git frotz -n24 $args"          # и использовать его внутри
					# сконструированной командной строки
eval "$command"
EOF

$ sh ваш-git-сценарий.sh "a b'c"
------------

ПРИМЕРЫ
-------

* Вывести имя объекта текущего коммита:
+
------------
$ git rev-parse --verify HEAD
------------

* Вывести имя объекта коммита из редакции в переменной оболочки $REV:
+
------------
$ git rev-parse --verify --end-of-options $REV^{commit}
------------
+
Это завершится ошибкой, если $REV пуст или не является допустимой редакцией.

* Аналогично вышеизложенному:
+
------------
$ git rev-parse --default master --verify --end-of-options $REV
------------
+
но если $REV пуст, будет выведено имя объекта коммита из master.

GIT
---
Является частью пакета linkgit:git[1]
