git-pull(1)
===========

НАЗВАНИЕ
--------
git-pull - Получение и слияние изменений из другого репозитория или локальной ветки


ОБЗОР
-----
[synopsis]
'git pull' [<параметры>] [<репозиторий> [<спецификатор-ссылки>...]]


ОПИСАНИЕ
--------

Интегрировать изменения из внешнего репозитория в текущую ветку.

Сначала `git pull` выполняет `git fetch` с теми же аргументами (исключая параметры слияния), чтобы получить внешнюю ветку (ветки). Затем он решает, какую внешнюю ветку интегрировать: если вы запускаете `git pull` без аргументов, по умолчанию это <<UPSTREAM-BRANCHES,вышестоящая>> для текущей ветки. Затем он интегрирует эту ветку в текущую ветку.

Существует 4 основных параметра для интеграции внешней ветки:

1. `git pull --ff-only` будет выполнять только обновления "перемоткой вперёд": он завершается ошибкой, если ваша локальная ветка разошлась с внешней веткой. Это значение по умолчанию.
2. `git pull --rebase` выполняет `git rebase`
3. `git pull --no-rebase` выполняет `git merge`.
4. `git pull --squash` выполняет `git merge --squash`

Вы также можете установить параметры конфигурации `pull.rebase`, `pull.squash` или `pull.ff` в соответствии с предпочтительным поведением.

Если во время слияния или перемещения возник конфликт слияния, который вы не хотите обрабатывать, вы можете безопасно прервать его с помощью `git merge --abort` или `git rebase --abort`.

ПАРАМЕТРЫ
---------

_<репозиторий>_::
	«Внешний» репозиторий, из которого выполняется получение. Это может быть либо URL (см. раздел <<URLS,URL-АДРЕСА GIT>> ниже), либо имя внешнего репозитория (см. раздел <<REMOTES,ВНЕШНИЕ РЕПОЗИТОРИИ>> ниже).
+
По умолчанию используется настроенная вышестоящая для текущей ветки или `origin`. См. <<UPSTREAM-BRANCHES,ВЫШЕСТОЯЩИЕ ВЕТКИ>> ниже для получения дополнительной информации о настройке вышестоящих.

_<спецификатор-ссылки>_::
	Какая ветка или другие ссылки должны быть получены и интегрированы в текущую ветку, например `main` в `git pull origin main`. По умолчанию используется настроенная вышестоящая для текущей ветки.
+
Это может быть ветка, метка или другая коллекция ссылок. Полный синтаксис см. в <<fetch-refspec,_<спецификатор-ссылки>_>> ниже в разделе "Параметры, связанные с получением", а о том, как `git pull` использует этот аргумент для определения того, какую внешнюю ветку интегрировать, см. в разделе <<DEFAULT-BEHAVIOUR,ПОВЕДЕНИЕ ПО УМОЛЧАНИЮ>> ниже.

`-q`::
`--quiet`::
	Это передаётся как нижележащему git-fetch для подавления отчётов во время передачи, так и нижележащему git-merge для подавления вывода во время слияния.

`-v`::
`--verbose`::
	Передать `--verbose` в git-fetch и git-merge.

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	Этот параметр управляет тем, должны ли быть получены новые коммиты заполненных подмодулей и должны ли также быть обновлены рабочие каталоги активных подмодулей (см. linkgit:git-fetch[1], linkgit:git-config[1] и linkgit:gitmodules[5]).
+
Если переключение выполняется через перемещение, локальные коммиты подмодулей также перемещаются.
+
Если обновление выполняется через слияние, конфликты подмодулей разрешаются и переключаются.

Параметры, связанные со слиянием
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; переместить текущую ветку поверх вышестоящей ветки после получения. Если существует отслеживаемая внешняя ветка, соответствующая вышестоящей ветке, и вышестоящая ветка была перемещена с момента последнего получения, перемещение использует эту информацию, чтобы избежать перемещения нелокальных изменений. Это значение по умолчанию.

`merges`;; перемещение с использованием `git rebase --rebase-merges`, чтобы локальные коммиты слияния были включены в перемещение (подробности см. в linkgit:git-rebase[1]).
`false`;; слить вышестоящую ветку в текущую ветку.
`interactive`;; включить интерактивный режим перемещения.

+
См. `pull.rebase`, `branch.<имя>.rebase` и `branch.autoSetupRebase` в linkgit:git-config[1], если вы хотите, чтобы `git pull` всегда использовал `--rebase` вместо слияния.
+
[NOTE]
Это потенциально _опасный_ режим работы. Он переписывает историю, что не сулит ничего хорошего, если вы уже опубликовали эту историю. *Не* используйте этот параметр, если вы внимательно не прочитали linkgit:git-rebase[1].

`--no-rebase`::
	Это краткая форма для `--rebase=false`.

Параметры, связанные с извлечением изменений
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
ПОВЕДЕНИЕ ПО УМОЛЧАНИЮ
----------------------

Часто люди используют `git pull` без указания каких-либо параметров. Традиционно это было эквивалентно `git pull origin`. Однако, когда присутствует конфигурация `branch.<имя>.remote`, а вы находитесь на ветке `<имя>`, это значение используется вместо `origin`.

Чтобы определить, какой URL использовать для получения, используется значение конфигурации `remote.<origin>.url`, и если такой переменной нет, используется значение в строке `URL:` в `$GIT_DIR/remotes/<origin>`.

Чтобы определить, какие внешние ветки получать (и опционально сохранять в отслеживаемых внешних ветках), когда команда запускается без параметров спецификатора ссылки в командной строке, используются значения переменной конфигурации `remote.<origin>.fetch`, а если их нет, используется `$GIT_DIR/remotes/<origin>` и используются его строки `Pull:`. В дополнение к форматам спецификаторов ссылок, описанным в разделе ПАРАМЕТРЫ, вы можете иметь спецификатор ссылки с подстановочными знаками, который выглядит так:

------------
refs/heads/*:refs/remotes/origin/*
------------

Спецификатор ссылки с подстановочными знаками должен иметь непустую правую часть (т.е. должен сохранять полученное в отслеживаемых внешних ветках), и его левая и правая части должны заканчиваться на `/*`. Вышеуказанное указывает, что все внешние ветки отслеживаются с использованием отслеживаемых внешних веток в иерархии `refs/remotes/origin/` под тем же именем.

Правило определения того, какую внешнюю ветку сливать после получения, довольно сложное, чтобы не нарушить обратную совместимость.

Если явные спецификаторы ссылок были указаны в командной строке `git pull`, все они сливаются.

Если в командной строке не был указан спецификатор ссылки, то `git pull` использует спецификатор ссылки из конфигурации или `$GIT_DIR/remotes/<origin>`. В таких случаях применяются следующие правила:

. Если существует конфигурация `branch.<имя>.merge` для текущей ветки _<имя>_, то это имя ветки на внешнем сайте, которая сливается.

. Если спецификатор ссылки содержит подстановочные знаки, ничего не сливается.

. В противном случае сливается внешняя ветка первого спецификатора ссылки.


ПРИМЕРЫ
-------

* Обновить отслеживаемые внешние ветки для репозитория, из которого вы клонировали, затем слить одну из них в вашу текущую ветку:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
Обычно сливаемая ветка — это `HEAD` внешнего репозитория, но выбор определяется параметрами `branch.<имя>.remote` и `branch.<имя>.merge`; подробности см. в linkgit:git-config[1].

* Слить в текущую ветку внешнюю ветку `next`:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
Это оставляет копию `next` временно в `FETCH_HEAD` и обновляет отслеживаемую внешнюю ветку `origin/next`. То же самое можно сделать, вызвав fetch и merge:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


Если вы попробовали выполнить pull, который привёл к сложным конфликтам, и хотите начать заново, вы можете восстановиться с помощью `git reset`.


include::transfer-data-leaks.adoc[]

ОШИБКИ
------
Использование `--recurse-submodules` в настоящее время может получать только новые коммиты в уже переключённых подмодулях. Когда, например, вышестоящая ветка добавляет новый подмодуль в только что полученные коммиты суперпроекта, сам подмодуль не может быть получен, что делает невозможным переключение этого подмодуля позже без повторного выполнения fetch. Ожидается, что это будет исправлено в будущей версии Git.

СМ. ТАКЖЕ
---------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
Является частью пакета linkgit:git[1]
