git-check-attr(1)
=================

НАЗВАНИЕ
--------
git-check-attr — Отображение информации gitattributes


ОБЗОР
-----
[verse]
'git check-attr' [--source <указатель-дерева>] [-a | --all | <атрибут>...] [--] <имя-пути>...
'git check-attr' --stdin [-z] [--source <указатель-дерева>] [-a | --all | <атрибут>...]

ОПИСАНИЕ
--------
Для каждого имени пути эта команда выведет, является ли каждый атрибут 'unspecified' (неопределён), 'set' (установлен) или 'unset' (снят) как gitattribute для этого пути.

ПАРАМЕТРЫ
---------
-a::
--all::
	Вывести все атрибуты, связанные с указанными путями. Если используется эта опция, то атрибуты 'unspecified' не будут включены в вывод.

--cached::
	Учитывать `.gitattributes` только в индексе, игнорируя рабочий каталог.

--stdin::
	Читать имена путей из стандартного ввода (stdin), по одному в строке, вместо командной строки.

-z::
	Формат вывода изменён для возможности машинного разбора. Если также указан `--stdin`, входные пути разделяются символом NUL вместо символа перевода строки.

--source=<указатель-дерева>::
	Проверить атрибуты для указанного указателя-дерева. Обычно исходное дерево указывается именованием коммита, ветки или метки, связанной с ним.

\--::
	Интерпретировать все предшествующие аргументы как атрибуты, а все последующие аргументы как имена путей.

Если не используются ни `--stdin`, ни `--all`, ни `--`, первый аргумент будет рассматриваться как атрибут, а остальные аргументы как имена путей.

ВЫВОД
-----

Вывод имеет форму: <путь> ДВОЕТОЧИЕ ПРОБЕЛ <атрибут> ДВОЕТОЧИЕ ПРОБЕЛ <информация> ПЕРЕВОД_СТРОКИ

если не действует `-z`, в этом случае в качестве разделителя используется NUL: <путь> NUL <атрибут> NUL <информация> NUL


<путь> — это путь запрашиваемого файла, <атрибут> — это запрашиваемый атрибут, а <информация> может быть одним из следующих:

'unspecified';; когда атрибут не определён для пути.
'unset';;	когда атрибут определён как false.
'set';;		когда атрибут определён как true.
<value>;;	когда атрибуту присвоено значение.

Буферизация происходит так, как описано в параметре `GIT_FLUSH` в linkgit:git[1]. Вызывающая сторона отвечает за предотвращение взаимных блокировок (deadlocks), вызванных переполнением входного буфера или чтением из пустого выходного буфера.

ПРИМЕРЫ
-------

В примерах используется следующий файл '.gitattributes':

---------------
*.java diff=java -crlf myAttr
NoMyAttr.java !myAttr
README caveat=unspecified
---------------

* Вывод одного атрибута:
+
---------------
$ git check-attr diff org/example/MyClass.java
org/example/MyClass.java: diff: java
---------------

* Вывод нескольких атрибутов для файла:
+
---------------
$ git check-attr crlf diff myAttr -- org/example/MyClass.java
org/example/MyClass.java: crlf: unset
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Вывод всех атрибутов для файла:
+
---------------
$ git check-attr --all -- org/example/MyClass.java
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Вывод атрибута для нескольких файлов:
+
---------------
$ git check-attr myAttr -- org/example/MyClass.java org/example/NoMyAttr.java
org/example/MyClass.java: myAttr: set
org/example/NoMyAttr.java: myAttr: unspecified
---------------

* Не все значения одинаково однозначны:
+
---------------
$ git check-attr caveat README
README: caveat: unspecified
---------------

СМ. ТАКЖЕ
---------
linkgit:gitattributes[5].

GIT
---
Является частью пакета linkgit:git[1]
