git-diff-tree(1)
================

НАЗВАНИЕ
--------
git-diff-tree - Сравнение содержимого и режима blob-объектов, найденных через два объекта-дерева


ОБЗОР
-----
[verse]
'git diff-tree' [--stdin] [-m] [-s] [-v] [--no-commit-id] [--pretty]
	      [-t] [-r] [-c | --cc] [--combined-all-paths] [--root] [--merge-base]
	      [<общие-параметры-diff>] <указатель-дерева> [<указатель-дерева>]
	      [<путь>...]

ОПИСАНИЕ
--------
Сравнить содержимое и режим доступа к файлу blob-объектов, найденных через два объекта-дерева.

Если задан только один <указатель-дерева>, коммит сравнивается с его родительскими коммитами (см. `--stdin` ниже).

Обратите внимание, что 'git diff-tree' может использовать дерево, инкапсулированное в объекте коммита.

ПАРАМЕТРЫ
---------
include::diff-options.adoc[]

<указатель-дерева>::
	Идентификатор объекта-дерева.

<путь>...::
	Если заданы, результаты ограничиваются подмножеством файлов, соответствующих одному из указанных спецификаторов путей.

-r::
	Рекурсивно обходить поддеревья.

-t::
	Отображать саму запись дерева, а также поддеревья. Подразумевает `-r`.

--root::
	Когда задан параметр `--root`, начальный коммит будет отображаться как событие создание большого количества объектов, что эквивалентно сравнению с пустым деревом.

--merge-base::
	Вместо непосредственного сравнения между двумя <указателями-дерева>, использовать их базу слияния в качестве начального состояния. Должны быть указаны два <указателя-дерева>, и оба должны быть коммитами.

--stdin::
	Когда задан параметр `--stdin`, команда не принимает <указатели-дерева> в качестве аргументов командной строки. Вместо этого она считывает строки, содержащие либо два <дерева>, либо один <коммит>, либо список <коммитов> из стандартного ввода. (Используйте один пробел в качестве разделителя.)
+
Когда заданы два дерева, команда сравнивает первое дерево со вторым. Когда задан один коммит — коммит сравнивается с его родителями. Остальные коммиты, если заданы, используются так, как если бы они были родителями первого коммита.
+
При сравнении двух деревьев перед списком изменений выводятся идентификаторы обоих деревьев (разделённые пробелом и завершаемые переводом строки). При сравнении коммитов — идентификатор первого (или единственного) коммита (за которым следует перевод строки).
+
Следующие флаги оказывают дополнительное влияние на поведение при сравнении коммитов (но не деревьев).

-m::
	По умолчанию `git diff-tree --stdin` не показывает списки изменений для коммитов слияний. С этим флагом выводятся списки изменений для таких коммитов относительно всех его родителей. См. также `-c`.

-s::
	По умолчанию `git diff-tree --stdin` показывает списки изменений либо в машиночитаемой форме (без `-p`), либо в форме патча (с `-p`). Этот вывод можно подавить. Данный параметр полезен только с флагом `-v`.

-v::
	Этот флаг заставляет 'git diff-tree --stdin' также отображать сообщение коммита перед списком изменений.

include::pretty-options.adoc[]

--no-commit-id::
	`git diff-tree` выводит строку с идентификатором коммита, когда это применимо. Этот флаг подавляет вывод идентификатора коммита.

-c::
	Этот флаг изменяет способ отображения коммита слияния (что означает, что он полезен только тогда, когда команде задан либо один <указатель-дерева>, либо `--stdin`). Когда он задан выводятся список изменений результата слияния относительно всех его родителей одновременно, а не попарно между каждым из родителей и результатом слияния (как это происходит с параметром `-m`). Кроме того, он перечисляет только те файлы, которые были изменены относительно всех родителей.

--cc::
	Этот флаг изменяет способ отображения коммита слияния подобно тому, как это делает параметр `-c`. Он подразумевает параметры `-c` и `-p` и дополнительно ужимает выводимый патч, опуская неинтересные блоки, содержимое которых у родителей присутствует только в двух вариантах, а результат слияния просто выбирает один из них без изменений. Когда все блоки, составляющие коммит, являются «неинтересными», сам коммит и его сообщение не выводятся, так же, как и в случае любого другого «пустого» списка изменений.

--combined-all-paths::
	Этот флаг заставляет комбинированные списки изменений (используемые для коммитов слияния) перечислять имена файла во всех его родителях. Таким образом, этот параметр имеет эффект только, когда используется совместно с -c или --cc, и, вероятно, полезен только в том случае, если будут обнаружены изменения имени файла (т.е. когда включено обнаружение переименования или копирования).

--always::
	Показывать сам коммит и сообщение коммита, даже если его список изменений пуст.


include::pretty-formats.adoc[]

include::diff-format.adoc[]

GIT
---
Является частью пакета linkgit:git[1]
