git-shortlog(1)
===============

НАЗВАНИЕ
--------
git-shortlog - Сводка вывода 'git log'

ОБЗОР
-----
[verse]
'git shortlog' [<параметры>] [<диапазон-редакций>] [[--] <путь>...]
git log --pretty=short | 'git shortlog' [<параметры>]

ОПИСАНИЕ
--------
Обобщает вывод 'git log' в формате, подходящем для включения в анонсы выпусков. Каждый коммит будет сгруппирован по автору и заголовку.

Кроме того, из описания коммита будет удалено "[PATCH]".

Если в командной строке не переданы редакции и либо стандартный ввод не является терминалом, либо нет текущей ветки, 'git shortlog' выведет сводку журнала, прочитанного из стандартного ввода, без ссылки на текущий репозиторий.

ПАРАМЕТРЫ
---------

-n::
--numbered::
	Сортировать вывод по количеству коммитов на автора вместо алфавитного порядка авторов.

-s::
--summary::
	Подавлять описание коммита и предоставлять только сводку количества коммитов.

-e::
--email::
	Отображать email адрес каждого автора.

--format[=<format>]::
	Вместо темы коммита используйте другую информацию для описания каждого коммита. '<формат>' может быть любой строкой, принимаемой параметром `--format` команды 'git log', например '* [%h] %s'. (См. раздел "ФОРМАТЫ ВЫВОДА" в linkgit:git-log[1].)
+
Каждый красиво напечатанный коммит будет перевёрстан перед показом.

--date=<формат>::
	Показывать даты, отформатированные в соответствии с заданной строкой даты. (См. параметр `--date` в разделе "Форматирование коммитов" в linkgit:git-log[1]). Полезно с `--group=format:<формат>`.

--group=<тип>::
	Группировать коммиты на основе `<тип>`. Если параметр `--group` не указан, по умолчанию используется `author`. `<тип>` может быть одним из:
+
--
 - `author`, коммиты группируются по автору
 - `committer`, коммиты группируются по коммиттеру (то же, что и `-c`)
 - `trailer:<поле>`, `<поле>` интерпретируется как завершитель (trailer) сообщения коммита без учёта регистра (см. linkgit:git-interpret-trailers[1]). Например, если ваш проект использует завершители `Reviewed-by`, вы можете увидеть, кто рецензировал, с помощью `git shortlog -ns --group=trailer:reviewed-by`.
+
Обратите внимание, что коммиты, не содержащие завершитель, не будут подсчитываться. Аналогично, коммиты с несколькими завершителями (например, несколько подписей) могут быть подсчитаны более одного раза (но только один раз для каждого уникального значения завершителя в этом коммите).
+
Shortlog попытается проанализировать каждое значение завершителя как идентичность `имя <email>`. В случае успеха применяется mailmap, и email опускается, если не указан параметр `--email`. Если значение не может быть проанализировано как идентичность, оно будет принято буквально и полностью.

 - `format:<формат>`, любая строка, принимаемая параметром `--format` команды 'git log'. (См. раздел "ФОРМАТЫ ВЫВОДА" в linkgit:git-log[1].)
--
+
Если `--group` указан несколько раз, коммиты подсчитываются для каждого значения (но опять же, только один раз для каждого уникального значения в этом коммите). Например, `git shortlog --group=author --group=trailer:co-authored-by` подсчитывает как авторов, так и соавторов.

-c::
--committer::
	Это псевдоним для `--group=committer`.

-w[<width>[,<indent1>[,<indent2>]]]::
	Выполняет перенос строк вывода, оборачивая каждую строку на `ширина`. Первая строка каждой записи имеет отступ в `отступ1` пробелов, а вторая и последующие строки имеют отступ в `отступ2` пробела. Значения `ширина`, `отступ1` и `отступ2` по умолчанию равны 76, 6 и 9 соответственно.
+
Если ширина равна `0` (нулю), то строки вывода имеют отступ без их переноса.

<диапазон-редакций>::
	Показывать только коммиты в указанном диапазоне редакций. Если <диапазон-редакций> не указан, по умолчанию используется `HEAD` (т.е. вся история, ведущая к текущему коммиту). `origin..HEAD` указывает все коммиты, достижимые из текущего коммита (т.е. `HEAD`), но не из `origin`. Полный список способов указания <диапазона-редакций> см. в разделе "Указание диапазонов" в linkgit:gitrevisions[7].

[--] <путь>...::
	Рассматривать только те коммиты, которые достаточны для объяснения того, как появились файлы, соответствующие указанным путям.
+
Пути может потребоваться предварить `--`, чтобы отделить их от параметров или диапазона редакций, когда возникает путаница.

:git-shortlog: 1
include::rev-list-options.adoc[]

СОПОСТАВЛЕНИЕ АВТОРОВ
---------------------

См. linkgit:gitmailmap[5].

Обратите внимание, что если `git shortlog` запускается вне репозитория (для обработки содержимого журнала из стандартного ввода), он будет искать файл `.mailmap` в текущем каталоге.

GIT
---
Является частью пакета linkgit:git[1]
