git-fsck(1)
===========

НАЗВАНИЕ
--------
git-fsck - Проверка связности и валидности объектов в базе данных


ОБЗОР
-----
[verse]
'git fsck' [--tags] [--root] [--unreachable] [--cache] [--no-reflogs]
	 [--[no-]full] [--strict] [--verbose] [--lost-found]
	 [--[no-]dangling] [--[no-]progress] [--connectivity-only]
	 [--[no-]name-objects] [--[no-]references] [<объект>...]

ОПИСАНИЕ
--------
Проверка связности и валидности объектов в базе данных.

ПАРАМЕТРЫ
---------
<объект>::
	Объект, который следует рассматривать как голову трассировки недостижимости.
+
Если объекты не заданы, 'git fsck' по умолчанию использует в качестве голов файл индекса, все ссылки SHA-1 в пространстве имён `refs` и все журналы ссылок (если не указан --no-reflogs).

--unreachable::
	Вывести объекты, которые существуют, но не достижимы ни из одного из узлов ссылок.

--dangling::
--no-dangling::
	Вывести объекты, которые существуют, но никогда не используются 'напрямую' (по умолчанию). `--no-dangling` можно использовать для исключения этой информации из вывода.

--root::
	Вывести отчёт по корневым узлам.

--tags::
	Вывести отчёт по меткам.

--cache::
	Считать любой объект, записанный в индексе, также головным узлом для трассировки недостижимости.

--no-reflogs::
	Не считать достижимыми коммиты, на которые ссылается только запись в журнале ссылок (reflog). Эта опция предназначена только для поиска коммитов, которые раньше были в ссылке, но теперь нет, но всё ещё находятся в соответствующем журнале ссылок.

--full::
	Проверять не только объекты в GIT_OBJECT_DIRECTORY ($GIT_DIR/objects), но также те, которые находятся в дополнительных пулах объектов, перечисленных в GIT_ALTERNATE_OBJECT_DIRECTORIES или $GIT_DIR/objects/info/alternates, и в упакованных архивах Git, находящихся в $GIT_DIR/objects/pack и соответствующих подкаталогах pack в дополнительных пулах объектов. Теперь это значение по умолчанию; вы можете отключить его с помощью --no-full.

--connectivity-only::
	Проверять только связность достижимых объектов, убеждаясь, что любые объекты, на которые ссылается достижимая метка, коммит или дерево, присутствуют. Это ускоряет операцию, полностью избегая чтения blob-объектов (хотя всё равно проверяется существование упомянутых blob-объектов). Это обнаружит повреждения в коммитах и деревьях, но не будет выполнять никаких семантических проверок (например, на ошибки формата). Повреждения в blob-объектах не будут обнаружены вообще.
+
Недостижимые метки, коммиты и деревья также будут доступны для поиска верхушек (tips) болтающихся (dangling) сегментов истории. Используйте `--no-dangling`, если вас не волнует этот вывод и вы хотите ещё больше ускорить процесс.

--strict::
	Включить более строгую проверку, а именно выявлять режим файла, записанный с установленным битом g+w, который создавался старыми версиями Git. Существующие репозитории, включая ядро Linux, сам Git и репозиторий sparse, имеют старые объекты, которые вызывают эту проверку, но рекомендуется проверять новые проекты с этим флагом.

--verbose::
	Быть многословным.

--lost-found::
	Записывать болтающиеся (dangling) объекты в .git/lost-found/commit/ или .git/lost-found/other/ в зависимости от типа. Если объект является blob-объектом, содержимое записывается в файл, а не его имя объекта.

--name-objects::
	При отображении имён достижимых объектов, помимо SHA-1, также отображать имя, описывающее *как* они достижимы, совместимое с linkgit:git-rev-parse[1], например `HEAD@{1234567890}~25^2:src/`.

--progress::
--no-progress::
	Состояние выполнения по умолчанию выводится в стандартный поток ошибок, если он подключён к терминалу, если не указан --no-progress или --verbose. --progress принудительно выводит состояние выполнения, даже если стандартный поток ошибок не направлен на терминал.

--references::
--no-references::
	Управляет тем, следует ли проверять согласованность базы данных ссылок с помощью 'git refs verify'. Подробности см. в linkgit:git-refs[1]. По умолчанию база данных ссылок проверяется.

КОНФИГУРАЦИЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/fsck.adoc[]

ОБСУЖДЕНИЕ
----------

git-fsck проверяет SHA-1 и общую целостность объектов, а также полностью отслеживает результирующую достижимость и всё остальное. Он выводит любые найденные повреждения (отсутствующие или испорченные объекты), и если вы используете флаг `--unreachable`, он также выведет объекты, которые существуют, но не достижимы ни из одного из указанных головных узлов (или из набора по умолчанию, как упоминалось выше).

Любые повреждённые объекты вам придётся искать в резервных копиях или других архивах (т.е. вы можете просто удалить их и выполнить 'rsync' с другим сайтом в надежде, что у кого-то ещё есть объект, который вы повредили).

Если core.commitGraph имеет значение true, файл графа коммитов также будет проверен с помощью 'git commit-graph verify'. См. linkgit:git-commit-graph[1].

Извлечённая диагностика
-----------------------

unreachable <тип> <объект>::
	На объект <объект> типа <тип> нет прямых или косвенных ссылок ни в одном из просмотренных деревьев или коммитов. Это может означать, что существует другой корневой узел, который вы не указали, или дерево повреждено. Если вы не пропустили корневой узел, то вы можете смело удалять недостижимые узлы, поскольку они не могут быть использованы.

missing <тип> <объект>::
	На объект <объект> типа <тип> имеется ссылка, но он отсутствует в базе данных.

dangling <тип> <объект>::
	Объект <объект> типа <тип> присутствует в базе данных, но никогда не используется 'напрямую'. Болтающийся (dangling) коммит может быть корневым узлом.

hash mismatch <объект>::
	В базе данных есть объект, хеш которого не соответствует значению в базе данных объектов. Это указывает на серьёзную проблему целостности данных.


СООБЩЕНИЯ FSCK
--------------

Ниже перечислены типы ошибок, обнаруживаемых `git fsck`, и значение каждой ошибки с их серьёзностью по умолчанию. Серьёзность ошибки, кроме тех, которые помечены как «(FATAL)», можно изменить, установив соответствующую переменную конфигурации `fsck.<id-сообщения>`.

include::fsck-msgids.adoc[]


Переменные окружения
--------------------

GIT_OBJECT_DIRECTORY::
	используется для указания корня базы данных объектов (обычно $GIT_DIR/objects)

GIT_INDEX_FILE::
	используется для указания файла индекса

GIT_ALTERNATE_OBJECT_DIRECTORIES::
	используется для указания дополнительных корней базы данных объектов (обычно не установлено)

GIT
---
Является частью пакета linkgit:git[1]
