git-count-objects(1)
====================

НАЗВАНИЕ
--------
git-count-objects — Подсчёт количества непакованных объектов и их дискового потребления

ОБЗОР
-----
[verse]
'git count-objects' [-v] [-H | --human-readable]

ОПИСАНИЕ
--------
Подсчитывает количество непакованных (unpacked) файлов объектов и занимаемое ими дисковое пространство, чтобы помочь вам решить, когда наступило подходящее время для переупаковки (repack).


ПАРАМЕТРЫ
---------
-v::
--verbose::
	Предоставить более подробные отчёты:
+
count: количество непакованных (loose) объектов
+
size: дисковое пространство, занимаемое непакованными объектами, в КиБ (если не указан -H)
+
in-pack: количество объектов в пакетах
+
packs: количество файлов пакетов
+
size-pack: дисковое пространство, занимаемое пакетами, в КиБ (если не указан -H)
+
prune-packable: количество непакованных (loose) объектов, которые также присутствуют в пакетах. Эти объекты могут быть подчищены (pruned) с помощью `git prune-packed`.
+
garbage: количество файлов в базе данных объектов, которые не являются ни допустимыми непакованными объектами, ни допустимыми пакетами
+
size-garbage: дисковое пространство, занимаемое мусорными файлами, в КиБ (если не указан -H)
+
alternate: абсолютный путь к дополнительным базам данных объектов; может появляться несколько раз, по одной строке на путь. Обратите внимание, что если путь содержит непечатаемые символы, он может быть окружён двойными кавычками и содержать escape-последовательности в стиле C с обратной косой чертой.

-H::
--human-readable::

Вывести размеры в удобочитаемом для человека формате

GIT
---
Является частью пакета linkgit:git[1]
