git-archimport(1)
=================

НАЗВАНИЕ
--------
git-archimport - Импорт репозитория GNU Arch в Git


ОБЗОР
-----
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <глубина>] [-t <временный_каталог>]
	       <архив>/<ветка>[:<ветка-git>]...

ОПИСАНИЕ
--------
Импортирует проект из одного или нескольких репозиториев GNU Arch. Он будет следовать за ветками и репозиториями в пространствах имён, определённых предоставленными параметрами <архив>/<ветка>. Если он не может найти удалённую ветку, из которой происходит слияние, он просто импортирует её как обычный коммит. Если он может найти её, он будет отмечать её как слияние, когда это возможно (см. обсуждение ниже).

Скрипт ожидает, что вы предоставите ключевые корни, с которых он может начать импорт из коммита Arch типа 'initial import' или 'tag'. Он будет следовать и импортировать новые ветки в пределах предоставленных корней.

Он ожидает работы только с одним проектом. Если он увидит ветки с разными корнями, он откажется запускаться. В этом случае отредактируйте параметры <архив>/<ветка>, чтобы чётко определить область импорта.

'git archimport' широко использует `tla` в фоновом режиме для доступа к репозиторию Arch. Убедитесь, что у вас есть последняя версия `tla` в пути. `tla` должен знать о репозиториях, которые вы передаёте в 'git archimport'.

Для первоначального импорта 'git archimport' ожидает найти себя в пустом каталоге. Для отслеживания разработки проекта, использующего Arch, запустите 'git archimport' с теми же параметрами, что и при первоначальном импорте, чтобы выполнить инкрементный импорт.

Хотя 'git archimport' пытается создавать разумные имена веток для импортируемых архивов, также можно указать имена веток Git вручную. Для этого после каждого параметра <архив>/<ветка> через двоеточие напишите имя ветки Git. Так вы сможете сократить имена веток Arch и преобразовать жаргон Arch в жаргон Git, например, сопоставив ветку "PROJECT{litdd}devo{litdd}VERSION" с веткой "master".

Можно связать несколько веток Arch с одной веткой Git; результат будет иметь наибольший смысл только в том случае, если после создания второй ветки в первую ветку не будет сделано коммитов. Тем не менее, это полезно для преобразования репозиториев Arch, которые периодически ротировались.


СЛИЯНИЯ
-------
Данные о слиянии патчей из Arch также используются для пометки слияний в Git. Git не слишком заботится об отслеживании патчей и рассматривает слияние только тогда, когда ветка включает все коммиты с момента точки их расхождения. В конечном итоге Git будет хорошо представлять, насколько разошлись ветки. Таким образом, процесс импорта теряет некоторые метаданные об обмене патчами.

К счастью, когда вы пытаетесь слить ветки, импортированные из Arch, Git найдёт хорошую базу слияния и имеет все шансы идентифицировать патчи, которыми обменивались между ветками не по порядку.

ПАРАМЕТРЫ
---------

-h::
	Показать справку по использованию.

-v::
	Подробный вывод.

-T::
	Много меток. Будет создавать метку для каждого коммита, отражающую имя коммита в репозитории Arch.

-f::
	Использовать быструю стратегию импорта набора патчей. Это может быть значительно быстрее для больших деревьев, но не может обрабатывать переименования каталогов или изменения прав доступа. Стратегия по умолчанию медленная и безопасная.

-o::
	Используйте это для совместимости со старым стилем имён веток, применявшимся в более ранних версиях 'git archimport'. Имена веток в старом стиле были категория{litdd}ветка, тогда как имена в новом стиле — архив,категория{litdd}ветка{litdd}версия. В обоих случаях имена, указанные в командной строке, переопределяют автоматически сгенерированные.

-D <глубина>::
	Следовать по родословной слияний и пытаться импортировать деревья, из которых были выполнены слияния. Укажите глубину больше 1, если журналы патчей были сокращены.

-a::
	Попытаться автоматически зарегистрировать архивы на `http://mirrors.sourcecontrol.net`. Это особенно полезно с параметром -D.

-t <врем_каталог>::
	Переопределить временный каталог по умолчанию.


<архив>/<branch>::
	Идентификатор <архив>/<ветка> в формате, который понимает `tla log`.


GIT
---
Является частью пакета linkgit:git[1]
