git-fetch(1)
============

НАЗВАНИЕ
--------
git-fetch - Загрузка объектов и ссылок из другого репозитория


ОБЗОР
-----
[synopsis]
git fetch [<параметры>] [<репозиторий> [<спецификатор-ссылки>...]]
git fetch [<параметры>] <группа>
git fetch --multiple [<параметры>] [(<репозиторий>|<группа>)...]
git fetch --all [<параметры>]


ОПИСАНИЕ
--------
Получает (fetch) ветки и/или метки (совместно называемые «ссылки») из одного или нескольких других репозиториев вместе с объектами, необходимыми для завершения их историй. Отслеживаемые внешние ветки обновляются (способы управления этим поведением см. в описании _<спецификатор-ссылки>_ ниже).

По умолчанию любая метка, указывающая на получаемые истории, также получается; в результате получаются метки, указывающие на ветки, которые вас интересуют. Это поведение по умолчанию можно изменить, используя параметры `--tags` или `--no-tags` или настроив `remote.<имя>.tagOpt`. Используя спецификатор ссылки, который явно получает метки, вы также можете получать метки, которые не указывают на интересующие вас ветки.

`git fetch` может получать данные либо из одного именованного репозитория или URL-адреса, либо сразу из нескольких репозиториев, если задана _<группа>_ и в файле конфигурации есть запись `remotes.<группа>`. (См. linkgit:git-config[1]).

Если внешний репозиторий не указан, по умолчанию будет использоваться внешний репозиторий `origin`, если только для текущей ветки не настроена вышестоящая (upstream) ветка.

Имена полученных ссылок вместе с именами объектов, на которые они указывают, записываются в `.git/FETCH_HEAD`. Эта информация может использоваться сценариями или другими командами git, такими как linkgit:git-pull[1].

ПАРАМЕТРЫ
---------
include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

`--stdin`::
	Читать спецификаторы ссылок (refspecs), по одному на строку, из stdin в дополнение к тем, которые предоставлены в качестве аргументов. Формат "tag _<имя>_" не поддерживается.

include::urls-remotes.adoc[]

[[CRTB]]
НАСТРОЕННЫЕ ОТСЛЕЖИВАЕМЫЕ ВНЕШНИЕ ВЕТКИ
---------------------------------------

Вы часто взаимодействуете с одним и тем же внешним репозиторием, регулярно и многократно получая из него данные. Чтобы отслеживать прогресс такого внешнего репозитория, `git fetch` позволяет вам настроить переменные конфигурации `remote.<репозиторий>.fetch`.

Обычно такая переменная может выглядеть так:

------------------------------------------------
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
------------------------------------------------

Эта конфигурация используется двумя способами:

* Когда `git fetch` запускается без указания того, какие ветки и/или метки получать в командной строке, например `git fetch origin` или `git fetch`, значения `remote.<репозиторий>.fetch` используются в качестве спецификаторов ссылок — они определяют, какие ссылки получать и какие локальные ссылки обновлять. Приведённый выше пример получит все ветки, существующие в `origin` (т.е. любую ссылку, соответствующую левой части значения, `refs/heads/*`), и обновит соответствующие отслеживаемые внешние ветки в иерархии `refs/remotes/origin/*`.

* Когда `git fetch` запускается с явными ветками и/или метками для получения в командной строке, например `git fetch origin master`, _<спецификаторы-ссылки>_, заданные в командной строке, определяют, что должно быть получено (например, `master` в примере, что является сокращением для `master:`, что в свою очередь означает «получить ветку `master`, но я явно не указываю, какую отслеживаемую внешнюю ветку обновить с её помощью из командной строки»), и пример команды получит _только_ ветку `master`. Значения `remote.<репозиторий>.fetch` определяют, какая отслеживаемая внешняя ветка (если таковая имеется) обновляется. При использовании таким образом значения `remote.<репозиторий>.fetch` не влияют на решение _что_ получать (т.е. значения не используются в качестве спецификаторов ссылок, когда командная строка перечисляет спецификаторы ссылок); они используются только для определения _где_ хранятся полученные ссылки, действуя как отображение.

Последнее использование значений `remote.<репозиторий>.fetch` можно переопределить, указав параметр(ы) `--refmap=<спецификатор-ссылки>` в командной строке.

ОБРЕЗКА
-------

Git по умолчанию хранит данные, если они не удалены явно; это распространяется и на хранение локальных ссылок на ветки во внешних репозиториях, которые сами удалили эти ветки.

Если позволить им накапливаться, эти устаревшие ссылки могут ухудшить производительность в больших и активных репозиториях с частым изменением веток и, например, сделать вывод таких команд, как `git branch -a --contains <коммит>`, излишне подробным, а также повлиять на всё остальное, что работает с полным набором известных ссылок.

Эти отслеживаемые внешние ссылки могут быть удалены разово с помощью одной из следующих команд:

------------------------------------------------
# Во время получения (fetch)
$ git fetch --prune <имя>

# Только подчистка (prune), без получения (fetch)
$ git remote prune <имя>
------------------------------------------------

Чтобы подчищать ссылки как часть вашего обычного рабочего процесса без необходимости помнить о запуске этой команды, установите `fetch.prune` глобально или `remote.<имя>.prune` для каждого внешнего репозитория в конфигурации. См. linkgit:git-config[1].

Здесь всё становится сложнее и конкретнее. Функция подчистки на самом деле не заботится о ветках; вместо этого она подчищает локальные <--> внешние ссылки как функцию спецификатора ссылки внешнего репозитория (см. `<спецификатор-ссылки>` и <<CRTB,НАСТРОЕННЫЕ ОТСЛЕЖИВАЕМЫЕ ВНЕШНИЕ ВЕТКИ>> выше).

Поэтому, если спецификатор ссылки для внешнего репозитория включает, например, `refs/tags/*:refs/tags/*`, или вы вручную выполняете, например, `git fetch --prune <имя> "refs/tags/*:refs/tags/*"`, то будут удалены не устаревшие отслеживаемые внешние ветки, а любые локальные метки, которые не существуют во внешнем репозитории.

Это может быть не тем, что вы ожидаете, т.е. вы хотите подчистить внешний репозиторий _<имя>_, но также явно получаете из него метки, поэтому при получении из него вы удаляете все свои локальные метки, большинство из которых могли изначально и не поступать из внешнего репозитория _<имя>_.

Поэтому будьте осторожны при использовании этого с таким спецификатором ссылки, как `refs/tags/*:refs/tags/*`, или любым другим спецификатором ссылки, который может отображать ссылки из нескольких внешних репозиториев в одно и то же локальное пространство имён.

Поскольку поддержание актуальности как веток, так и меток во внешнем репозитории является распространённым случаем использования, опция `--prune-tags` может быть предоставлена вместе с `--prune` для подчистки локальных меток, которых нет во внешнем репозитории, и принудительного обновления тех меток, которые отличаются. Подчистка меток также может быть включена с помощью `fetch.pruneTags` или `remote.<имя>.pruneTags` в конфигурации. См. linkgit:git-config[1].

Параметр `--prune-tags` эквивалентен объявлению `refs/tags/*:refs/tags/*` в спецификаторах ссылок внешнего репозитория. Это может привести к некоторым, казалось бы, странным взаимодействиям:

------------------------------------------------
# Оба этих варианта получают метки
$ git fetch --no-tags origin 'refs/tags/*:refs/tags/*'
$ git fetch --no-tags --prune-tags origin
------------------------------------------------

Причина, по которой он не завершается ошибкой при предоставлении без `--prune` или его версий в конфигурации, заключается в гибкости настроенных версий и в поддержании соответствия 1:1 между тем, что делают флаги командной строки, и тем, что делают версии в конфигурации.

Разумно, например, настроить `fetch.pruneTags=true` в `~/.gitconfig`, чтобы метки подчищались всякий раз, когда выполняется `git fetch --prune`, не делая каждый вызов `git fetch` без `--prune` ошибочным.

Подчистка меток с помощью `--prune-tags` также работает при получении из URL-адреса вместо именованного внешнего репозитория. Все эти команды подчистят метки, не найденные в origin:

------------------------------------------------
$ git fetch origin --prune --prune-tags
$ git fetch origin --prune 'refs/tags/*:refs/tags/*'
$ git fetch <url-of-origin> --prune --prune-tags
$ git fetch <url-of-origin> --prune 'refs/tags/*:refs/tags/*'
------------------------------------------------

ВЫВОД
-----

Вывод «git fetch» зависит от используемого транспортного метода; в этом разделе описывается вывод при получении по протоколу Git (локально или через ssh) и по протоколу Smart HTTP.

Статус получения выводится в табличной форме, где каждая строка представляет статус одной ссылки. Каждая строка имеет вид:

-------------------------------
 <флаг> <сводка> <откуда> -> <куда> [<причина>]
-------------------------------

При использовании `--porcelain` формат вывода предназначен для машинного разбора. В отличие от удобочитаемых форматов вывода, он выводит данные в стандартный вывод (stdout) вместо стандартного потока ошибок. Каждая строка имеет вид:

-------------------------------
<флаг> <старый-id-объекта> <новый-id-объекта> <локальная-ссылка>
-------------------------------

Состояние актуальных ссылок показывается только в том случае, если используется параметр `--verbose`.

В компактном режиме вывода, задаваемом переменной конфигурации fetch.output, если вся строка _<откуда>_ или _<куда>_ найдена в другой строке, она будет заменена на `*` в другой строке. Например, `master -> origin/master` превращается в `master -> origin/*`.

флаг::
	Один символ, указывающий статус ссылки:
(пространство);; для успешно полученной перемотки вперёд (fast-forward);
`+`;; для успешного принудительного обновления;
`-`;; для успешно подчищенной ссылки;
`t`;; для успешного обновления метки;
`*`;; для успешно полученной новой ссылки;
`!`;; для ссылки, которая была отклонена или не обновлена; и
`=`;; для ссылки, которая была актуальна и не требовала получения.

summary::
	Для успешно полученной ссылки в сводке показываются старое и новое значения ссылки в форме, подходящей для использования в качестве аргумента `git log` (в большинстве случаев это `<старое>..<новое>`, а для принудительных обновлений, не являющихся перемоткой вперёд — `<старое>...<новое>`).

из::
	Имя получаемой внешней ссылки без префикса `refs/<тип>/`. В случае удаления имя внешней ссылки — «(none)».

в::
	Имя обновляемой локальной ссылки без префикса `refs/<тип>/`.

причина::
	Пояснение, понятное человеку. В случае успешно полученных ссылок пояснение не требуется. Для неудачной ссылки описывается причина сбоя.

ПРИМЕРЫ
-------

* Обновить отслеживаемые внешние ветки:
+
------------------------------------------------
$ git fetch origin
------------------------------------------------
+
Вышеуказанная команда копирует все ветки из пространства имён внешнего репозитория `refs/heads/` и сохраняет их в локальное пространство имён `refs/remotes/origin/`, если только опция `remote.<репозиторий>.fetch` не используется для указания нестандартного спецификатора ссылки.

* Использование спецификаторов ссылок явно:
+
------------------------------------------------
$ git fetch origin +seen:seen maint:tmp
------------------------------------------------
+
Это обновляет (или создаёт при необходимости) ветки `seen` и `tmp` в локальном репозитории, получая из внешнего репозитория ветки `seen` и `maint` соответственно.
+
Ветка `seen` будет обновлена, даже если это не перемотка вперёд (fast-forward), потому что она имеет префикс в виде знака плюс; `tmp` — нет.

* Заглянуть в ветку внешнего репозитория, не настраивая внешний репозиторий в вашем локальном репозитории:
+
------------------------------------------------
$ git fetch git://git.kernel.org/pub/scm/git/git.git maint
$ git log FETCH_HEAD
------------------------------------------------
+
Первая команда получает ветку `maint` из репозитория по адресу `git://git.kernel.org/pub/scm/git/git.git`, а вторая команда использует `FETCH_HEAD` для просмотра ветки с помощью linkgit:git-log[1]. Полученные объекты в конечном итоге будут удалены встроенными средствами обслуживания git (см. linkgit:git-gc[1]).

include::transfer-data-leaks.adoc[]

КОНФИГУРАЦИЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/fetch.adoc[]

ОШИБКИ
------
Использование `--recurse-submodules` может получать только новые коммиты в подмодулях, которые присутствуют локально, например, в `$GIT_DIR/modules/`. Если вышестоящий (upstream) репозиторий добавляет новый подмодуль, этот подмодуль не может быть получен, пока он не будет клонирован, например, с помощью `git submodule update`. Ожидается, что это будет исправлено в будущей версии Git.

СМ. ТАКЖЕ
---------
linkgit:git-pull[1]

GIT
---
Является частью пакета linkgit:git[1]
