git-revert(1)
=============

НАЗВАНИЕ
--------
git-revert — отмена некоторых существующих коммитов

ОБЗОР
-----
[verse]
'git revert' [--[no-]edit] [-n] [-m <номер-родителя>] [-s] [-S[<id-ключа>]] <коммит>...
'git revert' (--continue | --skip | --abort | --quit)

ОПИСАНИЕ
--------

При наличии одного или нескольких существующих коммитов отменяет изменения, вносимые соответствующими патчами, и записывает несколько новых коммитов, которые их фиксируют. Это требует, чтобы ваш рабочий каталог был чистым (без изменений относительно коммита HEAD).

Примечание: 'git revert' используется для записи некоторых новых коммитов, чтобы отменить эффект некоторых более ранних коммитов (часто только ошибочного). Если вы хотите отбросить все незафиксированные изменения в вашем рабочем каталоге, вам следует обратиться к linkgit:git-reset[1], в частности к параметру `--hard`. Если вы хотите извлечь конкретные файлы такими, какими они были в другом коммите, вам следует обратиться к linkgit:git-restore[1], в частности к параметру `--source`. Будьте осторожны с этими альтернативами, так как обе они отбросят незафиксированные изменения в вашем рабочем каталоге.

См. "Сброс, восстановление и отмена" в linkgit:git[1] для получения информации о различиях между тремя командами.

ПАРАМЕТРЫ
---------
<commit>...::
	Коммиты для отмены. Более полный список способов написания имён коммитов см. в linkgit:gitrevisions[7]. Также могут быть указаны наборы коммитов, но по умолчанию обход не выполняется, см. linkgit:git-rev-list[1] и его параметр `--no-walk`.

-e::
--edit::
	С этим параметром 'git revert' позволит вам отредактировать сообщение коммита перед фиксацией отмены. Это значение по умолчанию, если вы запускаете команду из терминала.

-m <номер-родителя>::
--mainline <номер-родителя>::
	Обычно вы не можете отменить слияние, потому что не знаете, какая сторона слияния должна считаться основной линией. Этот параметр указывает номер родителя (начиная с 1) основной линии и позволяет отменять изменение относительно указанного родителя.
+
Отмена коммита слияния объявляет, что вы никогда не захотите изменений в дереве, внесённых слиянием. В результате последующие слияния будут включать только изменения дерева, внесённые коммитами, которые не являются предками ранее отменённого слияния. Это может соответствовать вашим желаниям, а может и нет.
+
Более подробную информацию см. в link:howto/revert-a-faulty-merge.html[revert-a-faulty-merge How-To].

--no-edit::
	С этим параметром 'git revert' не будет запускать редактор сообщений коммита.

--cleanup=<режим>::
	Этот параметр определяет, как сообщение коммита будет очищено перед передачей механизму фиксации. Дополнительные сведения см. в linkgit:git-commit[1]. В частности, если '<режиму>' присвоено значение `scissors`, в случае конфликта к `MERGE_MSG` будет добавлен разделитель `scissors` перед передачей.

-n::
--no-commit::
	Обычно команда автоматически создаёт некоторые коммиты с сообщениями журнала коммитов, указывающими, какие коммиты были отменены. Этот флаг применяет изменения, необходимые для отмены указанных коммитов, к вашему рабочему каталогу и индексу, но не создаёт коммиты. Кроме того, при использовании этого параметра ваш индекс не должен соответствовать коммиту HEAD. Отмена выполняется относительно начального состояния вашего индекса.
+
Это полезно, когда вы отменяете эффект более чем одного коммита в вашем индексе подряд.

-S[<id-ключа>]::
--gpg-sign[=<id-ключа>]::
--no-gpg-sign::
	Подписывать коммиты с помощью GPG. Аргумент `id-ключа` необязателен, и если не указан, в качестве значения по умолчанию будет использоваться личное имя коммиттера; если аргумент указан, он должен следовать сразу после параметра, без пробела. Параметр `--no-gpg-sign` полезен, если нужно отменить переменную конфигурации `commit.gpgSign` или параметр `--gpg-sign`, заданный ранее.

-s::
--signoff::
	Добавляет завершитель (trailer) `Signed-off-by` в конец сообщения коммита. Дополнительную информацию см. в описании опции signoff в linkgit:git-commit[1].

--strategy=<strategy>::
	Использовать указанную стратегию слияния. Должна использоваться только один раз. Подробности см. в разделе СТРАТЕГИИ СЛИЯНИЯ в linkgit:git-merge[1].

-X<option>::
--strategy-option=<option>::
	Передать параметр, специфичный для стратегии слияния, самой стратегии слияния. Подробности см. в linkgit:git-merge[1].

include::rerere-options.adoc[]

--reference::
	Вместо начала тела сообщения журнала с "This reverts <полное-имя-объекта-отменяемого-коммита>." ссылаться на коммит с использованием формата "--pretty=reference" (ср. linkgit:git-log[1]). Переменная конфигурации `revert.reference` может использоваться для включения этого параметра по умолчанию.


ПОДКОМАНДЫ ПОСЛЕДОВАТЕЛЯ (SEQUENCER)
------------------------------------
include::sequencer.adoc[]

ПРИМЕРЫ
-------
`git revert HEAD~3`::

	Отменить изменения, указанные четвёртым с конца коммитом в HEAD, и создать новый коммит с отменёнными изменениями.

`git revert -n master~5..master~2`::

	Отменить изменения, сделанные коммитами от пятого с конца коммита в master (включительно) до третьего с конца коммита в master (включительно), но не создавать никаких коммитов с отменёнными изменениями. Отмена изменяет только рабочий каталог и индекс.

ОБСУЖДЕНИЕ
----------

Хотя git автоматически создаёт базовое сообщение коммита, _настоятельно_ рекомендуется объяснять, почему исходный коммит отменяется. Кроме того, многократная отмена отмен приведёт к всё более громоздким строкам темы, например 'Reapply "Reapply "<original-subject>""'. Пожалуйста, рассмотрите возможность переформулировать их, чтобы сделать короче и уникальнее.

КОНФИГУРАЦИЯ
------------

include::includes/cmd-config-section-all.adoc[]

include::config/revert.adoc[]

СМ. ТАКЖЕ
---------
linkgit:git-cherry-pick[1]

GIT
---
Является частью пакета linkgit:git[1]
