СТРАТЕГИИ СЛИЯНИЯ
-----------------

Механизм слияния (команды `git merge` и `git pull`) позволяет выбирать внутренние 'стратегии слияния' с помощью параметра `-s`. Некоторые стратегии также могут принимать свои собственные параметры, которые можно передать, указав аргументы `-X<параметр>` для `git merge` и/или `git pull`.

`ort`::
	Это стратегия слияния по умолчанию при получении или слиянии одной ветки. Эта стратегия может разрешить только две головы с использованием алгоритма трёхходового слияния. Когда существует более одного общего предка, который может быть использован для трёхходового слияния, она создаёт слитое дерево общих предков и использует его в качестве эталонного дерева для трёхходового слияния. Сообщается, что это приводит к уменьшению количества конфликтов слияния без неправильных слияний по результатам тестов, проведённых на реальных коммитах слияния из истории разработки ядра Linux 2.6. Кроме того, эта стратегия может обнаруживать и обрабатывать слияния, включающие переименования. Она не использует обнаруженные копии. Название этого алгоритма — аббревиатура ("Ostensibly Recursive's Twin") и возникло из-за того, что он был написан как замена предыдущему алгоритму по умолчанию, `recursive`.
+
В случае, когда путь является подмодулем, если коммит подмодуля, используемый на одной стороне слияния, является потомком коммита подмодуля, используемого на другой стороне слияния, Git пытается выполнить перемотку вперёд к потомку. В противном случае Git будет рассматривать этот случай как конфликт, предлагая в качестве разрешения коммит подмодуля, который является потомком конфликтующих, если таковой существует.
+
Стратегия `ort` может принимать следующие параметры:

`ours`;;
	Этот параметр заставляет конфликтующие блоки автоматически разрешаться чисто в пользу 'нашей' версии. Изменения из другого дерева, которые не конфликтуют с нашей стороной, отражаются в результате слияния. Для двоичного файла всё содержимое берётся с нашей стороны.
+
Это не следует путать со стратегией слияния `ours`, которая вообще даже не смотрит на то, что содержит другое дерево. Она отбрасывает всё, что сделало другое дерево, объявляя, что 'наша' история содержит всё, что в нём произошло.

`theirs`;;
	Это противоположность `ours`; обратите внимание, что, в отличие от `ours`, нет стратегии слияния `theirs`, с которой можно было бы перепутать этот параметр слияния.

`ignore-space-change`;;
`ignore-all-space`;;
`ignore-space-at-eol`;;
`ignore-cr-at-eol`;;
	Обрабатывает строки с указанным типом изменения пробелов как неизменённые для целей трёхходового слияния. Изменения пробелов, смешанные с другими изменениями в строке, не игнорируются. См. также linkgit:git-diff[1] `-b`, `-w`, `--ignore-space-at-eol` и `--ignore-cr-at-eol`.
+
* Если 'их' версия вносит только изменения пробелов в строку, используется 'наша' версия;
* Если 'наша' версия вносит изменения пробелов, но 'их' версия включает существенное изменение, используется 'их' версия;
* В противном случае слияние продолжается обычным образом.

`renormalize`;;
	Это выполняет виртуальное переключение и фиксацию всех трёх стадий любого файла, которому требуется трёхходовое слияние. Этот параметр предназначен для использования при слиянии веток с разными фильтрами очистки или правилами нормализации концов строк. Подробности см. в разделе "Слияние веток с различными атрибутами фиксации/переключения" в linkgit:gitattributes[5].

`no-renormalize`;;
	Отключает параметр `renormalize`. Это переопределяет переменную конфигурации `merge.renormalize`.

`find-renames[=<n>]`;;
	Включает обнаружение переименований, опционально устанавливая порог схожести. Это поведение по умолчанию. Это переопределяет переменную конфигурации `merge.renames`. См. также linkgit:git-diff[1] `--find-renames`.

`rename-threshold=<число>`;;
	Устаревший синоним для `find-renames=<число>`.

`no-renames`;;
	Отключает обнаружение переименований. Это переопределяет переменную конфигурации `merge.renames`. См. также linkgit:git-diff[1] `--no-renames`.

`histogram`;;
	Устаревший синоним для `diff-algorithm=histogram`.

`patience`;;
	Устаревший синоним для `diff-algorithm=patience`.

`diff-algorithm=(histogram|minimal|myers|patience)`;;
	Использовать другой алгоритм сравнения при слиянии, что может помочь избежать неправильных слияний, возникающих из-за неважных совпадающих строк (например, скобок из разных функций). См. также linkgit:git-diff[1] `--diff-algorithm`. Обратите внимание, что `ort` по умолчанию использует `diff-algorithm=histogram`, в то время как обычные сравнения в настоящее время по умолчанию используют настройку конфигурации `diff.algorithm`.

`subtree[=<путь>]`;;
	Этот параметр является более продвинутой формой стратегии 'subtree', когда стратегия делает предположение о том, как два дерева должны быть сдвинуты, чтобы соответствовать друг другу при слиянии. Вместо этого указанный путь добавляется в начало (или удаляется из начала), чтобы форма двух деревьев совпадала.

`recursive`::
	Теперь это синоним для `ort`. Это была альтернативная реализация до v2.49.0, но в v2.50.0 была перенаправлена на `ort`. Предыдущая рекурсивная стратегия была стратегией по умолчанию для разрешения двух голов начиная с Git v0.99.9k до v2.33.0.

`resolve`::
	Эта стратегия может разрешить только две головы (т.е. текущую ветку и другую ветку, которую вы получили) с использованием алгоритма трёхходового слияния. Она пытается тщательно обнаруживать неоднозначности перекрёстного слияния. Она не обрабатывает переименования.

`octopus`::
	Эта стратегия разрешает случаи с более чем двумя головами, но отказывается выполнять сложное слияние, требующее ручного разрешения. Она в первую очередь предназначена для объединения голов тематических веток вместе. Это стратегия слияния по умолчанию при получении или слиянии более чем одной ветки.

`ours`::
	Эта стратегия разрешает любое количество голов, но результирующее дерево слияния всегда является деревом головы текущей ветки, фактически игнорируя все изменения из всех других веток. Она предназначена для замены старой истории разработки побочных веток. Обратите внимание, что это отличается от параметра `-Xours` для стратегии слияния `ort`.

`subtree`::
	Это модифицированная стратегия `ort`. При слиянии деревьев A и B, если B соответствует поддереву A, B сначала настраивается в соответствии со структурой дерева A, вместо того чтобы читать деревья на одном уровне. Эта настройка также выполняется для дерева общего предка.

Со стратегиями, использующими трёхходовое слияние (включая стратегию по умолчанию, `ort`), если изменение вносится в обе ветки, но позже отменяется в одной из веток, это изменение будет присутствовать в результате слияния; некоторые люди находят такое поведение запутанным. Это происходит потому, что при выполнении слияния учитываются только головы и основа слияния, а не отдельные коммиты. Поэтому алгоритм слияния считает отменённое изменение вообще отсутствием изменения и вместо него подставляет изменённую версию.
