Перечислить коммиты, достижимые при следовании по ссылкам `parent` (родитель) от указанного(ых) коммита(ов), но исключить коммиты, достижимые из того(ых), перед которыми указан '{caret}'. По умолчанию вывод выполняется в обратном хронологическом порядке.

Это можно представить как операцию над множествами. Коммиты, достижимые из любого из коммитов, указанных в командной строке, образуют множество, а затем коммиты, достижимые из любого из тех, перед которыми стоит '{caret}', вычитаются из этого множества. Оставшиеся коммиты выводятся в результате работы команды. Различные другие параметры и параметры путей могут использоваться для дальнейшего ограничения результата.

Таким образом, следующая команда:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list foo bar ^baz
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log foo bar ^baz
-----------------------------------------------------------------------
endif::git-log[]

означает «перечислить все коммиты, достижимые из 'foo' или 'bar', но не из 'baz'».

Специальное обозначение "`<коммит1>..<коммит2>`" можно использовать как сокращение для "`^<коммит1> <коммит2>`". Например, любое из следующих может использоваться взаимозаменяемо:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list origin..HEAD
$ git rev-list HEAD ^origin
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log origin..HEAD
$ git log HEAD ^origin
-----------------------------------------------------------------------
endif::git-log[]

Ещё одно специальное обозначение — "`<коммит1>...<коммит2>`", которое полезно для слияний. Результирующее множество коммитов представляет собой симметрическую разность двух операндов. Следующие две команды эквивалентны:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list A B --not $(git merge-base --all A B)
$ git rev-list A...B
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log A B --not $(git merge-base --all A B)
$ git log A...B
-----------------------------------------------------------------------
endif::git-log[]
