УКАЗАНИЕ РЕДАКЦИЙ
-----------------

Параметр редакции '<ред>' обычно (но не обязательно) указывает на объект-коммит. Он использует так называемый синтаксис 'расширенного SHA-1'. Вот различные способы указания имён объектов. Те, которые перечислены ближе к концу этого списка, указывают на деревья и blob-объекты, содержащиеся в коммите.

NOTE: В этом документе показан «сырой» синтаксис, каким его видит git. Оболочка и другие пользовательские интерфейсы могут потребовать дополнительного заключения в кавычки для защиты специальных символов и предотвращения разделения слов.

'<sha1>', например 'dae86e1950b1277e545cee180551750029cfe735', 'dae86e'::
  Полное имя объекта SHA-1 (40-байтовая шестнадцатеричная строка) или ведущая подстрока, уникальная в пределах репозитория. Например, dae86e1950b1277e545cee180551750029cfe735 и dae86e оба указывают на один и тот же объект-коммит, если в вашем репозитории нет другого объекта, чьё имя начинается с dae86e.

'<describeOutput>', например 'v1.7.4.2-679-g3bee7fb'::
  Вывод `git describe`; т.е. ближайшая метка, за которой могут следовать дефис, количество коммитов, затем дефис, 'g' и сокращённое имя объекта.

'<имя-ссылки>', например 'master', 'heads/master', 'refs/heads/master'::
  Символическое имя ссылки. Например, 'master' обычно означает объект-коммит, на который ссылается 'refs/heads/master'. Если у вас есть и 'heads/master', и 'tags/master', вы можете явно указать 'heads/master', чтобы сообщить Git, какую вы имеете в виду. В случае неоднозначности '<имя-ссылки>' однозначно идентифицируется путём поиска первого совпадения по следующим правилам:
+
  . Если существует '$GIT_DIR/<имя-ссылки>', то это то, что вы имеете в виду (обычно это полезно только для `HEAD`, `FETCH_HEAD`, `ORIG_HEAD`, `MERGE_HEAD`, `REBASE_HEAD`, `REVERT_HEAD`, `CHERRY_PICK_HEAD`, `BISECT_HEAD` и `AUTO_MERGE`);

  . в противном случае, 'refs/<имя-ссылки>', если существует;

  . в противном случае, 'refs/tags/<имя-ссылки>', если существует;

  . в противном случае, 'refs/heads/<имя-ссылки>', если существует;

  . в противном случае, 'refs/remotes/<имя-ссылки>', если существует;

  . в противном случае, 'refs/remotes/<имя-ссылки>/HEAD', если существует.

+
  `HEAD`:::
    указывает на коммит, на основе которого вы внесли изменения в рабочем каталоге.
  `FETCH_HEAD`:::
    записывает ветку, которую вы получили (fetch) из внешнего репозитория
    вашим последним вызовом `git fetch`.
  `ORIG_HEAD`:::
    создаётся командами, которые радикально перемещают ваш `HEAD` (`git
    am`, `git merge`, `git rebase`, `git reset`), чтобы записать положение
    `HEAD` до их выполнения, чтобы вы могли легко вернуть верхушку ветки
    в состояние, предшествующее их выполнению.
  `MERGE_HEAD`:::
    записывает коммит(ы), которые вы сливаете в свою ветку, когда
    вы выполняете `git merge`.
  `REBASE_HEAD`:::
    во время перемещения (rebase) записывает коммит, на котором операция
    в данный момент остановлена, либо из-за конфликтов, либо из-за команды `edit`
    в интерактивном перемещении.
  `REVERT_HEAD`:::
    записывает коммит, который вы отменяете (revert) при выполнении `git revert`.
  `CHERRY_PICK_HEAD`:::
    записывает коммит, который вы копируете (cherry-pick) при выполнении `git
    cherry-pick`.
  `BISECT_HEAD`:::
    записывает текущий коммит для тестирования, когда вы выполняете `git bisect
    --no-checkout`.
  `AUTO_MERGE`:::
    записывает объект-дерево, соответствующий состоянию, которое
    стратегия слияния 'ort' записала в рабочий каталог, когда операция слияния
    привела к конфликтам.

+
Обратите внимание, что любой из вышеперечисленных случаев 'refs/*' может поступать либо из каталога `$GIT_DIR/refs`, либо из файла `$GIT_DIR/packed-refs`. Хотя кодировка имени ссылки не указана, предпочтительнее UTF-8, так как некоторая обработка вывода может предполагать имена ссылок в UTF-8.

'@'::
  '@' само по себе является сокращением для `HEAD`.

'[<имя-ссылки>]@{<дата>}', например 'master@\{yesterday\}', 'HEAD@{5 minutes ago}'::
  Ссылка, за которой следует суффикс '@' со спецификацией даты, заключённой в фигурные скобки (например, '\{yesterday\}', '{1 month 2 weeks 3 days 1 hour 1 second ago}' или '{1979-02-26 18:30:00}'), указывает значение ссылки в предыдущий момент времени. Этот суффикс может использоваться только непосредственно после имени ссылки, и для ссылки должен существовать журнал ('$GIT_DIR/logs/<ссылка>'). Обратите внимание, что это ищет состояние вашей *локальной* ссылки в заданное время; например, что было в вашей локальной ветке 'master' на прошлой неделе. Если вы хотите просмотреть коммиты, сделанные в определённое время, см. `--since` и `--until`.

'<имя-ссылки>@{<n>}', например 'master@\{1\}'::
  Ссылка, за которой следует суффикс '@' с порядковой спецификацией, заключённой в фигурные скобки (например, '\{1\}', '\{15\}'), указывает n-е предыдущее значение этой ссылки. Например, 'master@\{1\}' — это непосредственно предыдущее значение 'master', а 'master@\{5\}' — это 5-е предыдущее значение 'master'. Этот суффикс может использоваться только непосредственно после имени ссылки, и для ссылки должен существовать журнал ('$GIT_DIR/logs/<имя-ссылки>').

'@{<n>}', например '@\{1\}'::
  Вы можете использовать конструкцию '@' с пустой частью ссылки, чтобы получить запись журнала ссылок (reflog) текущей ветки. Например, если вы находитесь в ветке 'blabla', то '@\{1\}' означает то же, что и 'blabla@\{1\}'.

'@{-<n>}', например '@{-1}'::
  Конструкция '@{-<n>}' означает <n>-ю ветку/коммит, переключенные перед текущим.

'[<имя-ветки>]@\{upstream\}', например 'master@\{upstream\}', '@\{u\}'::
  Ветка B может быть настроена для построения поверх ветки X (настраивается с помощью `branch.<имя>.merge`) во внешнем репозитории R (настраивается с помощью `branch.<имя>.remote`). B@{u} ссылается на отслеживаемую внешнюю ветку для ветки X, взятую из внешнего репозитория R, обычно находящуюся в `refs/remotes/R/X`.

'[<имя-ветки>]@\{push\}', например 'master@\{push\}', '@\{push\}'::
  Суффикс '@\{push}' сообщает ветку «куда мы бы отправили», если бы `git push` был выполнен, когда `имя-ветки` была переключена (или текущий `HEAD`, если имя ветки не указано). Как и для '@\{upstream\}', мы сообщаем отслеживаемую внешнюю ветку, которая соответствует этой ветке во внешнем репозитории.
+
Вот пример, чтобы прояснить:
+
------------------------------
$ git config push.default current
$ git config remote.pushdefault myfork
$ git switch -c mybranch origin/master

$ git rev-parse --symbolic-full-name @{upstream}
refs/remotes/origin/master

$ git rev-parse --symbolic-full-name @{push}
refs/remotes/myfork/mybranch
------------------------------
+
Обратите внимание в примере, что мы настроили треугольный рабочий процесс, в котором мы извлекаем (pull) из одного места и отправляем в другое. В нетреугольном рабочем процессе '@\{push}' совпадает с '@\{upstream}', и нет необходимости в нём.
+
Этот суффикс также принимается, если написан в верхнем регистре, и означает то же самое независимо от регистра.

'<ред>{caret}[<n>]', напр., 'HEAD{caret}, v1.5.1{caret}0'::
  Суффикс '{caret}' у параметра редакции означает первого родителя этого объекта-коммита. '{caret}<n>' означает <n>-го родителя (т.е. '<ред>{caret}' эквивалентно '<ред>{caret}1'). По особому правилу '<ред>{caret}0' означает сам коммит и используется, когда '<ред>' является именем объекта-метки, которая ссылается на объект-коммит.

'<ред>{tilde}[<n>]', например 'HEAD{tilde}, master{tilde}3'::
  Суффикс '{tilde}' у параметра редакции означает первого родителя этого объекта-коммита. Суффикс '{tilde}<n>' у параметра редакции означает объект-коммит, который является предком <n>-го поколения указанного объекта-коммита, следуя только первым родителям. Т.е. '<ред>{tilde}3' эквивалентно '<ред>{caret}{caret}{caret}', что эквивалентно '<ред>{caret}1{caret}1{caret}1'. Ниже приведена иллюстрация использования этой формы.

'<ред>{caret}{<тип>}', например 'v0.99.8{caret}\{commit\}'::
  Суффикс '{caret}', за которым следует имя типа объекта, заключённое в фигурные скобки, означает рекурсивное разыменование объекта по адресу '<ред>' до тех пор, пока не будет найден объект типа '<тип>' или объект больше не может быть разыменован (в этом случае происходит ошибка). Например, если '<ред>' является указателем коммита (commit-ish), '<ред>{caret}\{commit\}' описывает соответствующий объект-коммит. Аналогично, если '<ред>' является указателем дерева (tree-ish), '<ред>{caret}\{tree\}' описывает соответствующий объект-дерево. '<ред>{caret}0' является сокращением для '<ред>{caret}\{commit\}'.
+
'<ред>{caret}\{object\}' можно использовать, чтобы убедиться, что '<ред>' указывает на существующий объект, не требуя, чтобы '<ред>' был меткой, и без разыменования '<ред>'; поскольку метка уже является объектом, её не нужно разыменовывать даже один раз, чтобы добраться до объекта.
+
'<ред>{caret}\{tag\}' можно использовать, чтобы гарантировать, что '<ред>' идентифицирует существующий объект-метку.

'<ред>{caret}{}', например 'v0.99.8{caret}{}'::
  Суффикс '{caret}', за которым следует пустая пара фигурных скобок, означает, что объектом может быть метка, и рекурсивно разыменовывать метку до тех пор, пока не будет найден объект, не являющийся меткой.

'<ред>{caret}{/<текст>}', например 'HEAD^{/fix nasty bug}'::
  Суффикс '{caret}' у параметра редакции, за которым следует пара фигурных скобок, содержащих текст, начинающийся с косой черты, аналогичен синтаксису ':/fix nasty bug' ниже, за исключением того, что он возвращает самый молодой соответствующий коммит, который достижим из '<ред>' перед '{caret}'.

':/<текст>', например ':/fix nasty bug'::
  Двоеточие, за которым следует косая черта, а затем текст, указывает коммит, сообщение которого соответствует указанному регулярному выражению. Это имя возвращает самый молодой соответствующий коммит, который достижим из любой ссылки, включая HEAD. Регулярное выражение может соответствовать любой части сообщения коммита. Чтобы сопоставить сообщения, начинающиеся со строки, можно использовать, например, ':/^foo'. Специальная последовательность ':/!' зарезервирована для модификаторов сопоставления. ':/!-foo' выполняет отрицательное сопоставление, а ':/!!foo' сопоставляет буквальный символ '!', за которым следует 'foo'. Любая другая последовательность, начинающаяся с ':/!', пока зарезервирована. В зависимости от заданного текста правила разделения слов оболочки могут потребовать дополнительного заключения в кавычки.

'<ред>:<путь>', напр., 'HEAD:README', 'master:./README'::
  Суффикс ':', за которым следует путь, указывает на blob-объект или дерево по заданному пути в объекте-указателе-дерева, названном частью перед двоеточием. Путь, начинающийся с './' или '../', является относительным к текущему рабочему каталогу. Заданный путь будет преобразован в относительный относительно корневого каталога рабочего каталога. Это наиболее полезно для обращения к blob-объекту или дереву из коммита или дерева, которое имеет ту же структуру дерева, что и рабочий каталог.

':[<n>:]<путь>', например ':0:README', ':README'::
  Двоеточие, за которым может следовать номер этапа (от 0 до 3) и двоеточие, а затем путь, указывает на blob-объект в индексе по заданному пути. Отсутствующий номер этапа (и следующее за ним двоеточие) указывает на запись этапа 0. Во время слияния этап 1 — это общий предок, этап 2 — версия целевой ветки (обычно текущей ветки), а этап 3 — версия из ветки, с которой выполняется слияние.

Вот иллюстрация от Джона Лёлигера. Оба узла коммитов B и C являются родителями узла коммита A. Родительские коммиты упорядочены слева направо.

........................................
G   H   I   J
 \ /     \ /
  D   E   F
   \  |  / \
    \ | /   |
     \|/    |
      B     C
       \   /
        \ /
         A
........................................

    A =      = A^0
    B = A^   = A^1     = A~1
    C =      = A^2
    D = A^^  = A^1^1   = A~2
    E = B^2  = A^^2
    F = B^3  = A^^3
    G = A^^^ = A^1^1^1 = A~3
    H = D^2  = B^^2    = A^^^2  = A~2^2
    I = F^   = B^3^    = A^^3^
    J = F^2  = B^3^2   = A^^3^2


УКАЗАНИЕ ДИАПАЗОНОВ
-------------------

Команды обхода истории, такие как `git log`, работают с набором коммитов, а не только с одним коммитом.

Для этих команд указание одной редакции с использованием обозначений, описанных в предыдущем разделе, означает набор коммитов, `достижимых` из указанного коммита.

Указание нескольких редакций означает набор коммитов, достижимых из любого из указанных коммитов.

Достижимое множество коммита — это сам коммит и коммиты в его цепочке предков.

Существует несколько обозначений для указания набора связанных коммитов (называемого «диапазоном редакций»), проиллюстрированных ниже.


Исключения коммитов
~~~~~~~~~~~~~~~~~~~

Обозначение '{caret}<ред>' (циркумфлекс)::
 Для исключения коммитов, достижимых из коммита, используется префикс '{caret}'. Например, '{caret}r1 r2' означает коммиты, достижимые из 'r2', но исключает коммиты, достижимые из 'r1' (т.е. 'r1' и его предков).

Обозначения диапазонов с точками
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Обозначение диапазона '..' (две точки)::
 Операция над множествами '{caret}r1 r2' встречается так часто, что для неё существует сокращение. Когда у вас есть два коммита 'r1' и 'r2' (названных в соответствии с синтаксисом, объяснённым в разделе УКАЗАНИЕ РЕВИЗИЙ выше), вы можете запросить коммиты, достижимые из r2, исключая те, которые достижимы из r1, с помощью '{caret}r1 r2', и это может быть записано как 'r1..r2'.

Обозначение симметрической разности '\...' (три точки)::
 Похожее обозначение 'r1\...r2' называется симметрической разностью 'r1' и 'r2' и определяется как 'r1 r2 --not $(git merge-base --all r1 r2)'. Это набор коммитов, которые достижимы либо из 'r1' (левая сторона), либо из 'r2' (правая сторона), но не из обоих.

В этих двух сокращённых обозначениях вы можете опустить один конец, и он будет по умолчанию равен HEAD. Например, 'origin..' является сокращением для 'origin..HEAD' и спрашивает: «Что я сделал с тех пор, как ответвился от ветки origin?» Аналогично, '..origin' является сокращением для 'HEAD..origin' и спрашивает: «Что сделал origin с тех пор, как я от него ответвился?» Обратите внимание, что '..' будет означать 'HEAD..HEAD', что является пустым диапазоном, который одновременно и достижим, и недостижим из HEAD.

Существуют команды, специально предназначенные для приёма двух различных диапазонов (например, «git range-diff R1 R2» для сравнения двух диапазонов), но они являются исключениями. Если не указано иное, все команды «git», которые работают с набором коммитов, работают с одним диапазоном редакций. Другими словами, запись двух обозначений «диапазона из двух точек» рядом друг с другом, например.

    $ git log A..B C..D

для большинства команд *не* указывает два диапазона редакций. Вместо этого она будет указывать один связный набор коммитов, т.е. те, которые достижимы либо из B, либо из D, но не достижимы ни из A, ни из C. В линейной истории, подобной этой:

    ---A---B---o---o---C---D

поскольку A и B достижимы из C, диапазон редакций, указанный этими двумя диапазонами с точками, представляет собой единственный коммит D.


Другие сокращённые обозначения родителей <ред>{caret}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Существуют три других сокращения, особенно полезных для коммитов слияния, для обозначения набора, образованного коммитом и его родительскими коммитами.

Обозначение 'r1{caret}@' означает всех родителей 'r1'.

Обозначение 'r1{caret}!' включает коммит 'r1', но исключает всех его родителей. Само по себе это обозначение обозначает единственный коммит 'r1'.

Обозначение '<ред>{caret}-[<n>]' включает '<ред>', но исключает <n>-го родителя (т.е. сокращение для '<ред>{caret}<n>..<ред>'), причём '<n>' = 1, если не указано. Обычно это полезно для коммитов слияния, где вы можете просто передать '<коммит>{caret}-', чтобы получить все коммиты в ветке, которая была слита в коммите слияния '<коммит>' (включая сам '<коммит>').

В то время как '<rev>{caret}<n>' касался указания одного родителя коммита, эти три обозначения также учитывают его родителей. Например, вы можете сказать 'HEAD{caret}2{caret}@', но не можете сказать 'HEAD{caret}@{caret}2'.

Сводка по диапазонам редакций
-----------------------------

'<rev>'::
	Включить коммиты, достижимые из <ред> (т.е. <ред> и его предков).

'{caret}<rev>'::
	Исключить коммиты, достижимые из <ред> (т.е. <ред> и его предков).

'<rev1>..<rev2>'::
	Включить коммиты, достижимые из <ред2>, но исключить те, которые достижимы из <ред1>. Если <ред1> или <ред2> опущены, по умолчанию используется `HEAD`.

'<rev1>\...<rev2>'::
	Включить коммиты, достижимые из <ред1> или <ред2>, но исключить те, которые достижимы из обоих. Если <ред1> или <ред2> опущены, по умолчанию используется `HEAD`.

'<ред>{caret}@', например 'HEAD{caret}@'::
  Суффикс '{caret}', за которым следует символ @, означает то же, что и перечисление всех родителей '<ред>' (т.е. включить всё, что достижимо из его родителей, но не сам коммит).

'<ред>{caret}!', например 'HEAD{caret}!'::
  Суффикс '{caret}', за которым следует восклицательный знак, означает то же, что и указание коммита '<ред>' и всех его родителей с префиксом '{caret}', чтобы исключить их (и их предков).

'<ред>{caret}-<n>', например 'HEAD{caret}-, HEAD{caret}-2'::
	Эквивалентно '<ред>{caret}<n>..<ред>', причём '<n>' = 1, если не указано.

Вот несколько примеров с использованием иллюстрации Лёлигера выше, где каждый шаг развёртывания и выбора обозначения тщательно расписан:

....
   Аргументы   Развёрнутые аргументы    Выбранные коммиты
   D                            G H D
   D F                          G H I J D F
   ^G D                         H D
   ^D B                         E I J F B
   ^D B C                       E I J F B C
   C                            I J F C
   B..C   = ^B C                C
   B...C  = B ^F C              G H D E B C
   B^-    = B^..B
	  = ^B^1 B              E I J F B
   C^@    = C^1
	  = F                   I J F
   B^@    = B^1 B^2 B^3
	  = D E F               D G H E F I J
   C^!    = C ^C^@
	  = C ^C^1
	  = C ^F                C
   B^!    = B ^B^@
	  = B ^B^1 ^B^2 ^B^3
	  = B ^D ^E ^F          B
   F^! D  = F ^I ^J D           G H D F
....
