include::urls.adoc[]

ВНЕШНИЕ РЕПОЗИТОРИИ[[REMOTES]]
------------------------------

Имя одного из следующих может использоваться вместо URL в качестве аргумента _<репозиторий>_:

* внешний репозиторий в файле конфигурации Git: `$GIT_DIR/config`,
* файл в каталоге `$GIT_DIR/remotes` или
* файл в каталоге `$GIT_DIR/branches`.

Все они также позволяют вам опустить спецификатор ссылки в командной строке, поскольку каждый из них содержит спецификатор ссылки, который git будет использовать по умолчанию.

Именованный внешний репозиторий в файле конфигурации
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Вы можете указать имя внешнего репозитория, который вы ранее настроили с помощью linkgit:git-remote[1], linkgit:git-config[1] или даже путём ручного редактирования файла `$GIT_DIR/config`. URL этого внешнего репозитория будет использоваться для доступа к репозиторию. Спецификатор ссылки этого внешнего репозитория будет использоваться по умолчанию, если вы не укажете спецификатор ссылки в командной строке. Запись в файле конфигурации будет выглядеть так:

------------
	[remote "<имя>"]
		url = <URL>
		pushurl = <URL-отправки>
		push = <спецификатор-ссылки>
		fetch = <спецификатор-ссылки>
------------

_<URL-отправки>_ используется только для отправки. Он необязателен и по умолчанию равен _<URL>_. Отправка во внешний репозиторий влияет на все определённые pushurl-ы или все определённые url-ы, если pushurl-ы не определены. Однако получение будет выполняться только из первого определённого url, если определено несколько url-ов.

Именованный файл в `$GIT_DIR/remotes`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Вы можете указать имя файла в `$GIT_DIR/remotes`. URL в этом файле будет использоваться для доступа к репозиторию. Спецификатор ссылки в этом файле будет использоваться по умолчанию, если вы не укажете спецификатор ссылки в командной строке. Этот файл должен иметь следующий формат:

------------
	URL: один из вышеуказанных форматов URL
	Push: <спецификатор-ссылки>
	Pull: <спецификатор-ссылки>

------------

Строки `Push:` используются `git push`, а строки `Pull:` используются `git pull` и `git fetch`. Для дополнительных сопоставлений веток может быть указано несколько строк `Push:` и `Pull:`.

Именованный файл в `$GIT_DIR/branches`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Вы можете указать имя файла в `$GIT_DIR/branches`. URL в этом файле будет использоваться для доступа к репозиторию. Этот файл должен иметь следующий формат:


------------
	<URL>#<голова>
------------

_<URL>_ обязателен; `#<голова>` необязателен.

В зависимости от операции git будет использовать один из следующих спецификаторов ссылок, если вы не укажете его в командной строке. _<ветка>_ — это имя этого файла в `$GIT_DIR/branches`, а _<голова>_ по умолчанию равна `master`.

git fetch использует:

------------
	refs/heads/<голова>:refs/heads/<ветка>
------------

git push использует:

------------
	HEAD:refs/heads/<голова>
------------


[[UPSTREAM-BRANCHES]]
ВЫШЕСТОЯЩИЕ ВЕТКИ
-----------------

Ветки в Git могут опционально иметь вышестоящую внешнюю ветку. Git по умолчанию использует вышестоящую ветку для операций с внешними репозиториями, например:

* Это значение по умолчанию для `git pull` или `git fetch` без аргументов.
* Это значение по умолчанию для `git push` без аргументов, с некоторыми исключениями. Например, вы можете использовать параметр `branch.<имя>.pushRemote`, чтобы отправлять в другой внешний репозиторий, отличный от того, из которого вы получаете, и по умолчанию с `push.default=simple` настраиваемая вами вышестоящая ветка должна иметь то же имя.
* Различные команды, включая `git checkout` и `git status`, покажут вам, сколько коммитов было добавлено в вашу текущую ветку и вышестоящую с момента ответвления от неё, например: "Ваша ветка и 'origin/main' разошлись, и имеют 2 и 3 разных коммита соответственно".

Вышестоящая ветка хранится в `.git/config` в полях "`remote`" и "`merge`". Например, если вышестоящей для `main` является `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Вы можете явно установить вышестоящую ветку с помощью `git push --set-upstream <внешний-репозиторий> <ветка>`, но Git часто автоматически устанавливает вышестоящую ветку за вас, например:

* Когда вы клонируете репозиторий, Git автоматически устанавливает вышестоящую ветку для ветки по умолчанию.
* Если у вас установлен параметр конфигурации `push.autoSetupRemote`, `git push` автоматически установит вышестоящую ветку при первой отправке ветки.
* Переключение на отслеживаемую внешнюю ветку с помощью `git checkout <ветка>` автоматически создаст локальную ветку с этим именем и установит вышестоящую ветку на внешнюю ветку.

[NOTE]
Вышестоящие ветки иногда называют "информацией об отслеживании", как в выражении "установить информацию об отслеживании ветки".
